### ISSUE TITLE
Extra &amp; being added to XML files

### ISSUE THREAD

**Issue by huawuxin** [iBotPeaches/Apktool#10]
Please help to fix a problem introduced since the original brut version of apktool: http://code.google.com/p/android-apktool/issues/detail?id=101

In addition to the "& a m p;" being decoded as "& a m p ; a m p ;"  problem, " & l t;" also being decoded as "& a m p ; l t". (sorry for the addtional white spaces)

Please take care of it. Thank you.

**Comment by iBotPeaches** [comment]
fixed at some point in v2.0 development.
