### ISSUE TITLE
LGTeleService cannot be recompiled

### ISSUE THREAD

**Issue by szecs** [iBotPeaches/Apktool#1013]
https://drive.google.com/folderview?id=0B-0rLZ5HEnOQbTFDOUJZcDZhUVk&usp=sharing
Here are all necessary files including the log file. Cannot recompile LGTeleservice.apk. Decompiling went ok, however, apktool created a folder "unknown". Windows 10, java 7, fw properly installed.

**Comment by szecs** [comment]
Apktool was latest 2.0.2 snapshot just built by me today.

**Comment by iBotPeaches** [comment]
I think I broke my local copy of libpng.

```
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/btn_send_msg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/btn_default_focused_holo_light.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi-v4/dial_num_2_sub_wht.png
S: Could not decode file, replacing by FALSE value: drawable-ldpi-v4/ic_dial_action_call_sim_01.png
S: Could not decode file, replacing by FALSE value: drawable-ldpi-v4/stat_sys_phone_vt.png
```

for every image... This is not the error you had, I believe I broke my local install. Let me fix that and redo this.

**Comment by iBotPeaches** [comment]
Investigated this. Sorry for delay, and there is no bug here.

I took a look at why nearly half of the resources were failing decode. Starting with the first few

```
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/btn_dial_action_blue_disabled.9.png
S: Could not decode file, replacing by FALSE value: drawable-ldpi-v4/picture_unknown.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/btn_rec_rec_disabled.png
```

So I did some checking.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1013$ unzip -l LGTeleService.apk | grep 'drawable-hdpi-v4/btn_dial_action_blue_disabled.9.png'
```

Yeah none of these resources exist in the apk, so Apktool is doing exactly what it is suppose to, which doesn't effect the build.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1013/LGTeleService$ apktool b
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1013/LGTeleService$ 
```
