### ISSUE TITLE
Decode apk with apktool v1.4.3

### ISSUE THREAD

**Issue by artistika** [iBotPeaches/Apktool#1015]
How should i create the project with android studio so that it can be decoded with apktool v1.4.3.
I created a "Hello World" app, but couldn't decode it with this version of apktool.
I get this error: http://prntscr.com/80o1q5.

P.S. The app must be decoded with this version of apktool.

**Comment by iBotPeaches** [comment]
P.S - why?

New apks can't be used with an old apktool. It is as simple as that.
