### ISSUE TITLE
Decompile/Recompile breaking sysbar alignment

### ISSUE THREAD

**Issue by mirek190** [iBotPeaches/Apktool#1023]
Decompiling "SystemUI.apk", 
in workarea "_WorkArea4", using "apktool_2.0.1.jar" 
 
With Tickle My Android 11.0.0. 
(tinyurl.com\ticklemyandroid) 

 ----------------
```
I: Using Apktool 2.0.1 on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\mirek190\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
 ----------------
Decompile Successful! 

But when I compile again even no touch anything inside I get 

Recompiling "SystemUI.apk" With Original Signature,
in work area "_WorkArea4", using "apktool_2.0.1.jar" 
 
With Tickle My Android 11.0.0. 
(tinyurl.com\ticklemyandroid) 

 ----------------
```
I: Using Apktool 2.0.1
I: Smaling smali folder into classes.dex...
I: Building resources...
warning: string 'accessibility_quick_settings_airplane' has no default translation.
warning: string 'accessibility_quick_settings_bluetooth' has no default translation.
warning: string 'battery_low_subtitle' has no default translation.
warning: string 'done_button' has no default translation.
warning: string 'jelly_bean_dream_name' has no default translation.
warning: string 'keyguard_accessibility_status' has no default translation.
warning: string 'kg_password_wrong_pin_code' has no default translation.
warning: string 'notifications_off_text' has no default translation.
warning: string 'notifications_off_title' has no default translation.
warning: string 'quick_settings_wifi_display_label' has no default translation.
warning: string 'quick_settings_wifi_display_no_connection_label' has no default translation.
warning: string 'ssl_ca_cert_dialog_title' has no default translation.
warning: string 'ssl_ca_cert_info_message' has no default translation.
warning: string 'ssl_ca_cert_settings_button' has no default translation.
warning: string 'ssl_ca_cert_warning_message' has no default translation.
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy META-INF...
I: Building apk file...
```
 ----------------
Recompile Successful! 

And always I have broke my status bar  alignment - should be in the center ...

![screenshot_2015-08-16-01-39-35](https://cloud.githubusercontent.com/assets/6817266/9291443/df7df1ba-43b7-11e5-964f-a8130e47674b.png)
![screenshot_2015-08-16-01-33-33](https://cloud.githubusercontent.com/assets/6817266/9291444/df7f57c6-43b7-11e5-896f-711bb1d300ca.png)

**Comment by iBotPeaches** [comment]
Moved a lot of bugs to this one, to make it the primary. It appears aapt is at fault here, switching the order of attributes in various xml files. This seems to be the problem.

The previous two linked bugs involve Samsung/Touchwiz. My knowledge of OEM skins is suffering, so I'm not sure if this is as well, but the issues are all the same.

**Comment by Jertlok** [comment]
Well, iBotPeaches i've found what happens inside most of the xml files. For example in my status_bar_expanded_header.xml it has changed the android:layout_gravity from "center_horizontal" to "bottom|clip_horizontal.
I don't know if this info can be useful..

**Comment by Jertlok** [comment]
I've compiled again ApkTool with your latest commits and now the issue has disappeared. Also the bootom|clip_horizontal have gone! :D
Now the SystemUI works flawlessly and the XMLs look very good!

**Comment by iBotPeaches** [comment]
Good to hear. Our attribute parsing was having some troubles when references were involved. Still making a few more unit tests, because I think there are some edge cases that are missed.

**Comment by iBotPeaches** [comment]
Added unit-test - https://github.com/iBotPeaches/Apktool/commit/52dc52c2d3dba0ca785fa40e69a3ecd11036a1cf

Closing this. Lemme know if this needs to be re-opened.
