### ISSUE TITLE
brut.androlib.AndrolibException: Multiple resources: spec=0x7f06000a array/random_choose_from, config=[DEFAULT]

### ISSUE THREAD

**Issue by tieum** [iBotPeaches/Apktool#1024]
Happens when I try to decode the huawei launcher HwLauncher6.apk

I have the same error when I install the corresponding framework

I can upload the framework if needed.

Thanks,
tieum

**Comment by tieum** [comment]
uploaded the apk on mega:
hwlauncher6.apk https://mega.nz/#!jVZXWBTA!2g49ExGQSy8lAKY2UEoqrpavAaI4FW6PWILJmB6Rymk
framework-res.apk https://mega.nz/#!rYIx2DKL!sGlzypL2FK-aM-2pP6HWkIqdLFwwU3pb9P7FFHw-ULE
framework-res-hwext.apk https://mega.nz/#!jVZXWBTA!2g49ExGQSy8lAKY2UEoqrpavAaI4FW6PWILJmB6Rymk

**Comment by iBotPeaches** [comment]
Huawei isn't supported. Sorry.

**Comment by tieum** [comment]
didn't see https://github.com/iBotPeaches/Apktool/issues/966, sorry bout that, will investigate.
Thanks!
