### ISSUE TITLE
Doesn't rebuild -- Can't execute command /tmp/brut_util_Jar...

### ISSUE THREAD

**Issue by rboninsegna** [iBotPeaches/Apktool#1028]
Using OpenJDK 8 and working on a Moto E 5.1 stock ROM (very close to AOSP).
OS is x64 Devuan Testing, without x86 multilib.

Unlike the report on XDA page 360, I've confirmed /tmp is executable, and using an external AAPT doesn't solve the problem anyway.

Output: http://pastie.org/10381801

**Comment by rboninsegna** [comment]
Workaround found: enable multilib and install **libstdc++6:i386** and **zlib1g:i386**!

**Comment by iBotPeaches** [comment]
Sweet! glad you solved it.
