### ISSUE TITLE
Decomplile error

### ISSUE THREAD

**Issue by iamstudentVN** [iBotPeaches/Apktool#1030]
I try this file: https://www.dropbox.com/s/uv5wm5gj4luxhhh/xemtt.apk?dl=0
but i get errors, i need file strings.xml.

![tainhaccode](https://cloud.githubusercontent.com/assets/12800744/9572993/c1fa235e-4fe0-11e5-9e85-a49e294f842c.jpeg)

**Comment by pwelyn** [comment]
update apktool to 2.0.1, then remove $HOME/apktool/framework/1.apk

**Comment by iamstudentVN** [comment]
thanks @pwelyn
