### ISSUE TITLE
Tests fail when building from current repo.

### ISSUE THREAD

**Issue by WhiteMarlin** [iBotPeaches/Apktool#1046]
* What version of the tool are you using? On what Operating System?

Fresh git clone, Mac OS X 10.7.5.
$ java -version
java version "1.7.0_15"
Java(TM) SE Runtime Environment (build 1.7.0_15-b03)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)

* What is the expected output? What do you see instead?

BUILD SUCCEEDED. BUILD FAILED. Please see below for more details.

* What steps will reproduce this problem?

git clone git://github.com/iBotPeaches/Apktool.git
cd Apktool
./gradlew
./gradlew build fatJar

* Any additional information?

... [everything looks good up to here] ...

:brut.apktool:apktool-lib:processTestResources
:brut.apktool:apktool-lib:testClasses
:brut.apktool:apktool-lib:test

brut.androlib.BuildAndDecodeJarTest > classMethod FAILED
    brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/brut_util_Jar_5137908162466168074.tmp, p, -F, /var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/BRUT7255073696378486490.tmp/testjar.jar, -0, arsc, /var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/BRUT7255073696378486490.tmp/testjar-orig/build/apk]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildApk(Androlib.java:667)
        at brut.androlib.Androlib.build(Androlib.java:296)
        at brut.androlib.BuildAndDecodeJarTest.beforeClass(BuildAndDecodeJarTest.java:45)

        Caused by:
        brut.common.BrutException: could not exec command: [/var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/brut_util_Jar_5137908162466168074.tmp, p, -F, /var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/BRUT7255073696378486490.tmp/testjar.jar, -0, arsc, /var/folders/yq/n1413tks19n8g9hnvrx_3x4c0000gp/T/BRUT7255073696378486490.tmp/testjar-orig/build/apk]
            at brut.util.OS.exec(OS.java:89)
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
            ... 3 more

... [and other test failures] ...

**Comment by WhiteMarlin** [comment]
Further information:

ps.waitFor() on line 88 of OS.java is returning 132.

**Comment by WhiteMarlin** [comment]
Perhaps this is caused by SIGILL, illegal instruction.

**Comment by iBotPeaches** [comment]
I can't duplicate this on my Mac install. I don't have the same java version, but I think this is isolated to your environment, especially since the error is related to execution of binaries.

**Comment by WhiteMarlin** [comment]
So perhaps a word to the effect of "doesn't work on 10.7.5" would be in order? (I wonder which versions it does work on?)
