### ISSUE TITLE
Remove SmaliDebugging

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#1061]
Continuing to support this feature, with the means of Smalidea out seem like a waste of resources at this point. Four years ago, there was no better option to debug closed source applications.

Now with https://github.com/JesusFreke/smali/wiki/smalidea - and IntelliJ, the stress/work that apktool had to do is resolved with a simple decode from baksmali, and one can experience 10x the features that smali-debugging (apktool version) had.

Pros
------------------------------
1. Less code to maintain
2. Removal of smali into a maven dependency
3. Easier updates of smali project
4. More focus on resources (with the increase of resource obfuscation) is big plus.

Cons
------------------------------
1. We lose SmaliDebugging (our version), which is hit/miss in terms of IDE and support these days.
2. Those who still depend on this feature will have to transition to smali idea plugin.
3. smali-idea is in Alpha still

If we decide to process the removal, the options would be.
1. Remove all smali patches.
2. Remove smali submodule
3. Add smali dependency
4. Remove all apktool related smali debug files
5. Ensure apktool builds with smali as dependency vs submodule

Opinions? @brutall ? More or less want to spark a discussion here.

**Comment by rover12421** [comment]
Support!

**Comment by sheep0704** [comment]
···
