### ISSUE TITLE
Ubuntu bash/zenity graphical script

### ISSUE THREAD

**Issue by draekko** [iBotPeaches/Apktool#1067]
In case anyone else finds it useful; i've created a bash script with Zenity frontend (also works from the command line) to select and extract files from the desktop and included a .deb file to install it for Ubuntu (possibly Debian as well). I created a project page at https://github.com/draekko/apktool4ubuntu to share it.

**Comment by iBotPeaches** [comment]
Thanks. Might have to add a wiki page for community contributions tools/scripts/helpers/etc

**Comment by draekko** [comment]
Sounds like a good idea :)
