### ISSUE TITLE
Couldn't build latest head

### ISSUE THREAD

**Issue by alxchk** [iBotPeaches/Apktool#1069]
:brut.apktool:apktool-lib:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java:19: error: package org.jf.baksmali does not exist
import org.jf.baksmali.baksmali;
                      ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java:20: error: package org.jf.smali does not exist
import org.jf.smali.main;
                   ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/IndentingWriter.java:24: error: package org.jf.util does not exist
public class IndentingWriter extends org.jf.util.IndentingWriter {
                                                ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:20: error: package org.antlr.runtime does not exist
import org.antlr.runtime.*;
^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:21: error: package org.antlr.runtime.tree does not exist
import org.antlr.runtime.tree.CommonTree;
                             ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:22: error: package org.antlr.runtime.tree does not exist
import org.antlr.runtime.tree.CommonTreeNodeStream;
                             ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:24: error: package org.jf.dexlib2.writer.builder does not exist
import org.jf.dexlib2.writer.builder.DexBuilder;
                                    ^
/opt/Software/android/android-apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:25: error: package org.jf.smali does not exist
import org.jf.smali.*;
^

**Comment by iBotPeaches** [comment]
There are new build instructions. Please delete brut.apktool.smali and run applyPatches, then the build command.
