### ISSUE TITLE
Build process seems to be broken

### ISSUE THREAD

**Issue by StevenArzt** [iBotPeaches/Apktool#1070]
The gradle build process seems to be broken since the 12th. We build APKTool on a Jenkins build server and now get errors like the following:

```
:brut.apktool.smali:baksmali:compileJava/var/lib/jenkins/jobs/APKTool/workspace/brut.apktool.smali/baksmali/src/main/java/org/jf/baksmali/main.java:31: error: package com.google.common.collect does not exist
import com.google.common.collect.Lists;
                                ^
/var/lib/jenkins/jobs/APKTool/workspace/brut.apktool.smali/baksmali/src/main/java/org/jf/baksmali/main.java:32: error: package org.apache.commons.cli does not exist
import org.apache.commons.cli.*;
^
/var/lib/jenkins/jobs/APKTool/workspace/brut.apktool.smali/baksmali/src/main/java/org/jf/baksmali/main.java:33: error: package org.jf.dexlib2 does not exist
import org.jf.dexlib2.DexFileFactory;
                     ^
```

Have there been changes to the build system that require reconfiguration?

**Comment by iBotPeaches** [comment]
Yes they changed. An additional requirement is `git` installed now.


`./gradlew clean` - cleans up everything to prepare new build procedure 
`./gradlew applyPatches` - clones smali project into `brut.apktool.smali` and applies patches.
`./gradlew build fatJar proguard` - Builds apktool binary.
