### ISSUE TITLE
breaks service after d and b

### ISSUE THREAD

**Issue by samsongli** [iBotPeaches/Apktool#1074]
I found this issue when analyzing an android malware using apktool, to prove this is an apktool specific issue I used one of my own app, ran apktool to decompile it, recompile it and install, the service stopped working.

My app listens to RECEIVE_BOOT_COMPLETED and start the service, the service calls my server to report the phone's location. Let's call my own app target.apk

Here're the steps to repro: 
1. apktool d target.apk
2. apktool b target
3. run jarsigner  to sign the newly built app
4. run zipalign -v 4 to align the app // this is optional
5. uninstall the original app from device and install the app built by apktool, and the service no longer call my server when the phone is rebooted.
6. the recompiled app itself can still start and show its start UI, so I guess nothing's wrong when I rebuilt the app, but somehow the service part is broken

**Comment by iBotPeaches** [comment]
So a test app that uses the `RECEIVE_BOOT_COMPLETED` event and starts a service for demo purposes just writes to logcat? 

I can make a test app for that and investigate.

**Comment by samsongli** [comment]
well my app does a little bit more than that - its service reads the phone's location and upload to my server, but I guess let the service write to logcat is a good starting point to investigate. thanks.

**Comment by iBotPeaches** [comment]
Wrote up the test apk, then ran outta time - https://github.com/iBotPeaches/TestApks/commit/5de5c35b8c7b08a0d638d517552e3a8b3b72ada2

**Comment by samsongli** [comment]
cloned test code and built, got an issue with my android sdk - missing android-23, I'll update my sdk and re-test later.

**Comment by samsongli** [comment]
so how to generate the apk? I tried `gradlew dexRelease` with no luck, not familiar with gradle...

**Comment by iBotPeaches** [comment]
I believe it's `assembleDebug`.

**Comment by samsongli** [comment]
I was able to build the app, installed app-debug.apk on my device and tested, everything seems fine and I saw the expected logcat entry upon boot complete.

when I tried to decompile the app I got an exception:

apktool d app-debug.apk
I: Using Apktool 2.0.2 on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Song\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x01010462
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:502)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by samsongli** [comment]
downloaded 2.0.0 rc3 and it fixed the 0x01010462 issue when decompiling the test case, however got another error, which is discussed in https://github.com/iBotPeaches/Apktool/issues/745

searched online and found a sample app of listening OnBootComplete and start service: http://www.e-nature.ch/tech/wp-content/uploads/2012/06/OnBootCompletedExample.zip

This app can be decompiled and recompiled using apktool, logcat shows the apk built directly from the sample project can start the service, the decompile / recomplie apk cannot start the service. Hopefully this sample can save us some effort so that we can focus on the issue itself.

thanks

**Comment by iBotPeaches** [comment]
Yeah I duplicated with this test apk. Sorry for the delay. I think this is related to the `AndroidManifest.xml` as nothing else changes.

**Comment by samsongli** [comment]
I agree. It seems the binary AndroidManifest.xml is where the problem is after decompile / recompile. One particular thing I noticed, is that if you take the original test apk, decompile, recompile, and decompile again, the AndroidManifest.xml file generated from each decompile step is equivalent to the original AndroidManifest.xml.

Not knowing enough about the binary AndroidManifest.xml's format, I am guessing the bug lies in the recompile part of apktool, where the plain text AndroidManifest.xml is converted to binary format. Hope this helps.

**Comment by JehandadK** [comment]
Any work around on this? I believe this is happening for almost all compile recompile.  Is this version specific, which version are you using?

**Comment by iBotPeaches** [comment]
This was due to Android turning resources public so they don't change. However Android has restrictions on these when used in select manifest fields, which are rejected. This is such a big change to not automatically keep ids public, but instead remap them to keep them private.

This is tracked in our roadmap as it is rivals a rewrite of parts of the tool - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#automatic-remapping-of-resourceid

Closing.
