### ISSUE TITLE
execute ./gradlew error

### ISSUE THREAD

**Issue by menshen** [iBotPeaches/Apktool#1076]
/Users/lidongxu/workspace/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java:19: 错误: 程序包org.jf.baksmali不存在
import org.jf.baksmali.baksmali;

org.jf.baksmali does not exist

**Comment by iBotPeaches** [comment]
Build steps updated.

1. `git submodule update --init --recursive`
2. `gradlew applyPatches`
3. `gradlew build fatJar`
