### ISSUE TITLE
9 months later and issues still not solved... forgotten???

### ISSUE THREAD

**Issue by HardyG** [iBotPeaches/Apktool#1078]
Dear all,

9 months ago I've been posting an issue on apktool:
https://github.com/wting/android-apktool/issues/780

It was closed with the hint that it's a duplicate of this one:
https://github.com/wting/android-apktool/issues/657

I've been trying out if it was solved by former releases and now by release 2.0.2 but it is not!!!
Can you please tell me when this issue will be fixed?

Thanks a lot and Kind regards,
Hardy

**Comment by iBotPeaches** [comment]
1) You are referencing a repository that was not made by me. Someone thought they were being helpful exporting a large open source project from Googlecode -> Github against the Project's wishes, which actually was not helpful. 

2) This is actually bug #767 here (I think). Once again, referencing a repo I don't control nor support doesn't help anyone.

3) Last time I checked Apktool was open source and free. I don't get paid to work on anything. I work on this as a hobby for free with time I have. Bugs I fix are based on severity and ease of solution. Some bugs have been here for 2+ years before I fixed them. That sucks, but that is the fact of the matter when I am one person, who is a student, maintaining this tool.

There is no eta when your issue will be fixed, I think there is a pending pull request to fix the issue, but I remember some troubles I encountered testing it, so it has not been merged.

You are welcome to make a pull request or research the solution yourself.

**Comment by HardyG** [comment]
Sorry, my hint was not meant to blame anyone! It was just meant as a reminder!
(sorry for my maybe insufficiant, missleading english - I'm not a native speaker)
You are doing a great job here and I know you're doing it in spare time.
So - thanks a lot for all your effort!!!
