### ISSUE TITLE
Gradle Building Problem

### ISSUE THREAD

**Issue by TheGeekdu74** [iBotPeaches/Apktool#1090]
I have this issue, can anyone help me ?

 What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:compileJava'.
Compilation failed; see the compiler error output for details.

If you wants more details, tell me, I'll answer you when I'm connected

**Comment by iBotPeaches** [comment]
Almost 99% this is in reference to the new build steps.

Check #1076
