### ISSUE TITLE
couldn't compile the apktool

### ISSUE THREAD

**Issue by kaneawk** [iBotPeaches/Apktool#1093]
my steps:
git clone --recursive git://github.com/iBotPeaches/Apktool.git
cd Apktool
./gradlew

but it will repost those error:
```
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java:19: error: package org.jf.baksmali not found
import org.jf.baksmali.baksmali;
                      ^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java:20: error: package org.jf.smali not found
import org.jf.smali.main;
                   ^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:20: error: package org.antlr.runtime not found
import org.antlr.runtime.*;
^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:21: error: package org.antlr.runtime.tree not found
import org.antlr.runtime.tree.CommonTree;
                             ^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:22: error: package org.antlr.runtime.tree not found
import org.antlr.runtime.tree.CommonTreeNodeStream;
                             ^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:24: error: package org.jf.dexlib2.writer.builder not found
import org.jf.dexlib2.writer.builder.DexBuilder;
                                    ^
/home/kaneawk/Project/apktool/apktool-ori/build/Apktool/brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java:25: error: package org.jf.smali not found
import org.jf.smali.*;
^
..............etc....
```
I don't know why...

**Comment by iBotPeaches** [comment]
Please use the correct build instructions as per - http://ibotpeaches.github.io/Apktool/build/

```
git clone --recursive git://github.com/iBotPeaches/Apktool.git
cd Apktool
./gradlew applyPatches
./gradlew build fatJar proguard
```

**Comment by kaneawk** [comment]
OK,Thanks.

**Comment by Cmdmac** [comment]
run ./gradlew applyPatches get error:
fatal: destination path '/Users/fengzhiping/AndroidStudioProjects/Apktool/brut.apktool.smali' already exists and is not an empty directory.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyPatches'.
> Process returned error code. Expression: (result == 0). Values: result = 128

**Comment by Cmdmac** [comment]
I delete brut.apktool.smail folder and rebuild, but get the error:
brut.androlib.LargeIntsInManifestTest > checkIfLargeIntsAreHandledTest FAILED
    brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/brut_util_Jar_1688022803647293307.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/APKTOOL4058251484565670959.tmp, -0, arsc, -0, arsc, -I, /Users/fengzhiping/Library/apktool/framework/1.apk, -S, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/res, -M, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.LargeIntsInManifestTest.checkIfLargeIntsAreHandledTest(LargeIntsInManifestTest.java:61)

        Caused by:
        brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/brut_util_Jar_1688022803647293307.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/APKTOOL4058251484565670959.tmp, -0, arsc, -0, arsc, -I, /Users/fengzhiping/Library/apktool/framework/1.apk, -S, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/res, -M, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/AndroidManifest.xml]
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
            at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
            ... 3 more

            Caused by:
            brut.common.BrutException: could not exec command: [/var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/brut_util_Jar_1688022803647293307.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/APKTOOL4058251484565670959.tmp, -0, arsc, -0, arsc, -I, /Users/fengzhiping/Library/apktool/framework/1.apk, -S, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/res, -M, /var/folders/hb/0wrqbx_n2bvdyxhsqmmp3s8r0000gp/T/BRUT4833733153013929213.tmp/issue767.apk.out/AndroidManifest.xml]
                at brut.util.OS.exec(OS.java:90)
                at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
                ... 4 more

61 tests completed, 1 failed
:brut.apktool:apktool-lib:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
> There were failing tests. See the report at: file:///Users/fengzhiping/AndroidStudioProjects/Apktool/brut.apktool/apktool-lib/build/reports/tests/index.html

I found It can build apktool-cli.jar no other jars.

**Comment by bigpopxx** [comment]
I got build fail too

    brut.androlib.LargeIntsInManifestTest > checkIfLargeIntsAreHandledTest FAILED
    brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5031702990891764249.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL8709828659983887902.tmp, -0, arsc, -0, arsc, -I, /home/xx/apktool/framework/1.apk, -S, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/res, -M, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:462)
        at brut.androlib.Androlib.buildResources(Androlib.java:400)
        at brut.androlib.Androlib.build(Androlib.java:288)
        at brut.androlib.LargeIntsInManifestTest.checkIfLargeIntsAreHandledTest(LargeIntsInManifestTest.java:61)

        Caused by:
        brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5031702990891764249.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL8709828659983887902.tmp, -0, arsc, -0, arsc, -I, /home/xx/apktool/framework/1.apk, -S, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/res, -M, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/AndroidManifest.xml]
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
            at brut.androlib.Androlib.buildResourcesFull(Androlib.java:448)
            ... 3 more

            Caused by:
            brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5031702990891764249.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL8709828659983887902.tmp, -0, arsc, -0, arsc, -I, /home/xx/apktool/framework/1.apk, -S, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/res, -M, /tmp/BRUT446911560928469098.tmp/issue767.apk.out/AndroidManifest.xml]
                at brut.util.OS.exec(OS.java:95)
                at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:428)
                ... 4 more

    61 tests completed, 1 failed
    :brut.apktool:apktool-lib:test FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':brut.apktool:apktool-lib:test'.
    > There were failing tests. See the report at:  ...

**Comment by BurgerZ** [comment]
@bigpopxx This is because you have previously installed framework. You have to delete it manually, then build process will success. 

````
rm ~/apktool/framework/1.apk
````
After this build apktool again.

**Comment by bigpopxx** [comment]
@BurgerZ, It's worked, thx a lot:)

**Comment by Benjamin-Dobell** [comment]
__Note for OS X users:__ On OS X the file location is different.

     rm ~/Library/apktool/framework/1.apk
