### ISSUE TITLE
decompile apk fail, error: java.nio.charset.UnmappableCharacterException: Input length = 2

### ISSUE THREAD

**Issue by aj3423** [iBotPeaches/Apktool#1094]
I just checkout and compiled the latest apktool, trying to decompile an apk but failed.
Here's the error:
![apktool](https://cloud.githubusercontent.com/assets/4710875/11462589/6883358c-9751-11e5-8b77-01e59d5a09fc.png)

**Comment by aj3423** [comment]
the apk:  http://www.52plp.com/bottle.apk

**Comment by aj3423** [comment]
This error happens on Win7-32bit
Everything works perfectly on Ubuntu.

**Comment by bursoft-git** [comment]
aj3423, this file decompile and recompile well

--------------------------------------------------
Batch ApkTool                : 3.4.1
SMALI                        : smali-2.1.0.jar
API level                    : 21
APKTOOL                      : apktool_2.0.3.jar
build in EXPERT mode         : NO
Sign output APKs             : NO
--------------------------------------------------

[*] Decompiling bottle.apk
I: Using Apktool 2.0.3_1101_ on bottle.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: bin\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

DONE

[*] Recompiling bottle
I: Using Apktool 2.0.3_1101_
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...

DONE

**Comment by aj3423** [comment]
@bursoft-git , thank you, what operating system do you use? I'll try it.

**Comment by bursoft-git** [comment]
aj3423, i use Windows 7 x64 and Batch Apktool
try to clean up apktool framework directory (%USERPROFILE%\apktool\framework on Windows)

**Comment by iBotPeaches** [comment]
```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1094$ apktool d bottle.apk 
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT on bottle.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
l I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1094$ apktool b bottle
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1094$ 
```

No problem here. BTW, don't use `-d` unless you are planning on doing SmaliDebugging.

Usually the error shown for you, means you can't handle UTF8 chars. You could try changing your locale and font to a supported UTF8 lang or use `chcp 65001` to force the code page to UTF8.

**Comment by aj3423** [comment]
@iBotPeaches, @bursoft-git  I forgot to mention that I need to do the smali debugging, so I must use -d, the error only occurs with -d specified.

1. on Win7 it fails to de-compile(with the wrapper script from https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/windows/apktool.bat), error is shown in the first image
2. on Ubuntu it's ok to de-compile,  but fails to re-compile, error looks like:
![err](https://cloud.githubusercontent.com/assets/4710875/11478376/90619686-97c7-11e5-8570-0d2dc833781a.PNG)
   echo $LANG == en_US.UTF-8
The error message seems has something to do with resource. My framework.apk was copied from an Android 5.x machine, imported via "apktool if ....". And I installed aapt via "apt-get install aapt". What do I miss?
