### ISSUE TITLE
cannot hack Settings.apk

### ISSUE THREAD

**Issue by pangqingyuan1991** [iBotPeaches/Apktool#1095]
My phone runs androidl 5.0.2
I try to decompile and recompile Settings.apk.
No change to any file.
Then I replace AndroidManifest.xml in original Settings.apk with the recompile one, keeping original signatrue.
When I reboot my phone,Settings app is gone.
What I got from adb logcat is as below:
```
 I/Launcher.Model( 2109): Invalid package: ComponentInfo{com.android.settings/com.android.settings.Settings} (check again later)
......
I/ActivityManager( 1156): launch app----- startActivityLocked::setLaunchedPackage packageName is com.android.settings
I/ActivityManager( 1156): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10808000 cmp=com.android.settings/.UsbSettings} from uid 1000 on display 0
......
I/Launcher.Model( 2109): Package not found: com.android.settings
......
```
When I recovery the original Settings.apk and reboot, Settings app is back again.

So,what is the right steps to hack system app under androidl?

**Comment by BurgerZ** [comment]
If you replace the original manifest with recompiled one, then you need to re-sign the apk, otherwise your apk will not work.

**Comment by iBotPeaches** [comment]
What @BurgerZ said. With some earlier Android versions you can get around with replacing modified files without resigning, but the only exception to that rule is the `AndroidManifest.xml` file. 

So this isn't a bug.

**Comment by pangqingyuan1991** [comment]
Settings.apk is system app.We shouldn't change the signatrue of system app,isn't it?

**Comment by pangqingyuan1991** [comment]
Oh, I have found a solution:
decompile services.odex and hack static comparesignature function
then just sign Settings.apk with any key.

**Comment by iBotPeaches** [comment]
Not much of a solution, but a hack. You are removing intentional security measures at your own peril.
