### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by kidesigner** [iBotPeaches/Apktool#1096]
I was decode: 

`apktool d Gold_Miner_HD_2015.apk`

and re-build successfuly with below command:

`apktool b Gold_Miner_HD_2015 -c / --copy-original`

but when i running app apk with BlueStack it's not working:

`INSTALL_PARSE_FAILED_NO_CERTIFICATES`

Please help me. Thank you!

**Comment by iBotPeaches** [comment]
I unfortunately need to remove -c, as of lollipop and marshmallow it no longer works in my research. A manual signing of the built application is required. Using signapk.jar will work.

**Comment by kidesigner** [comment]
Thank you so much, it's working!
