### ISSUE TITLE
Could not decode attr value. 

### ISSUE THREAD

**Issue by root-expert** [iBotPeaches/Apktool#1098]
I was trying to decompile TouchWiz apk but i got some errors. I have installed twframework-res.apk as i couldn't found any framework-res.apk in the rom.

I got this error: http://pastebin.com/VWpcp6m1

Android Version: 5.1.1

Apktool version:2.0.2

Apk being decompiled: https://drive.google.com/file/d/0B0J0tRCO1FVLejM5amNyc2RHOTg/view?usp=sharing

Framework file:https://drive.google.com/file/d/0B0J0tRCO1FVLd0pPM0t1dEpLNzA/view?usp=sharing

Thanks.

**Comment by iBotPeaches** [comment]
Do you have the `framework-res.apk` apk from the ROM? The failure resources are from `pkgId` 1, which is `framework-res.apk`.

**Comment by root-expert** [comment]
The rom doesn't have a framework-res.apk. I'll check one again.

**Comment by root-expert** [comment]
If I install framework-res.apk i get this errors
```
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c003f
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c003d
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c003d
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c003d
```

**Comment by iBotPeaches** [comment]
Upload it and let me take a look :)

**Comment by root-expert** [comment]
[https://drive.google.com/file/d/0B5__WCqiPUr9MDVEVi1EaldmMGc/view?usp=sharing]

Thanks :D

**Comment by root-expert** [comment]
I successfully decompiled it. Probably it was a wrong framework-res.apk. :D
