### ISSUE TITLE
	Unable to run application after recompiling using apktool 2.0.2

### ISSUE THREAD

**Issue by raghavendhra45** [iBotPeaches/Apktool#1104]
We are trying to decompile and recompile an application which uses android support design library, we are able to recompile using apktools 2.0.2. While running the application we are getting the following exception.

```
12-08 11:49:58.235: E/AndroidRuntime(6057): FATAL EXCEPTION: main
12-08 11:49:58.235: E/AndroidRuntime(6057): Process: jp.co.jiec.myapplication, PID: 6057
12-08 11:49:58.235: E/AndroidRuntime(6057): java.lang.IllegalStateException: Expected 18 but was 17
12-08 11:49:58.235: E/AndroidRuntime(6057):     at com.android.dex.EncodedValueReader.checkType(EncodedValueReader.java:283)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at com.android.dex.EncodedValueReader.readType(EncodedValueReader.java:183)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:704)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
12-08 11:49:58.235: E/AndroidRuntime(6057):     at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
```

code : 

```
while (childClass != null &&
                    (defaultBehavior = childClass.getAnnotation(DefaultBehavior.class)) == null) {
                childClass = childClass.getSuperclass();
            }
```

**Comment by iBotPeaches** [comment]
I haven't had a chance to test this code, but you are basically saying that using this code. Using baksmali/smali to disassemble and re-assemble creates an apk that is broken that otherwise would have worked if baksmali was not involved?

If so, copy this over to https://github.com/JesusFreke/smali 
My forte isn't smali :)

**Comment by raghavendhra45** [comment]
Thanks for response, we are not using baksmali/smali we just decompiled the apk using 

"new ProcessBuilder(APKTOOL_PATH, "d", "-s", apkPath, "-o", tempDirPath).start()"
 and then recompiled 

"new ProcessBuilder(APKTOOL_PATH, "b", "-a", AAPT_PATH, directory, "-o",outputApkPath);"

**Comment by iBotPeaches** [comment]
Sorry very old ticket here. In the future use a pull request when wanting to change code. Otherwise you get what happened here. A lost ticket in the mess of this backlog.
