### ISSUE TITLE
java.util.zip.ZipException: invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by pwelyn** [iBotPeaches/Apktool#1105]
```
I: Using Apktool 2.0.2 on xytools_v1.1_public.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad signature)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:281)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:90)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad signature)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:279)
	... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
```
[File links](https://drive.google.com/file/d/0B-bpT3N3gxy0U2tpNFpaU0d5aEk/view?usp=sharing)

**Comment by iBotPeaches** [comment]
```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1105$ zipinfo xytools_v1.1_public.apk 
Archive:  xytools_v1.1_public.apk
Zip file size: 2897235 bytes, number of entries: 178
warning [xytools_v1.1_public.apk]:  1025 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [xytools_v1.1_public.apk]:  reported length of central directory is
  -1025 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
```

If my memory is correct. This is either the ZIp64 (4.5 spec) or something else entirely. I know the base Java 1.6 ZipFile does not support the 4.5 spec, so I might have to look towards Apache Commons Compress. It handles (as of `1.3`) `Zip64`. 

Or I'm completely wrong and this isn't a `Zip64` file. I'll research more.

**Comment by iBotPeaches** [comment]
Yeah switching to Commons Compress fixed it, but then I had to patch smali too which I'm trying not to, as I want to switch to the binary smali vs building it. I'll need to research this a bit more.

**Comment by NGTmeaty** [comment]
@iBotPeaches what's the status?

**Comment by iBotPeaches** [comment]
Still a bug that is accepted. Decided against route of Commons Compress especially since modifying smali was not something I was interested in doing. However, smali is now a dependency so that concern is resolved. Accepting any PRs that handle this with passing unit tests.

**Comment by iBotPeaches** [comment]
I guess in helping in moving towards a smali dependency vs a git submodule this has made it more difficult to patch.

```
➜  Bug1105 apktool d xytools_v1.1_public.apk 
I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on xytools_v1.1_public.apk
I: Loading resource table...
W: Skipping "android" package group
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: xytools_v1.1_public.apk is not an apk, dex, odex or oat file.
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:186)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:74)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:93)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:131)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)

➜  Bug1105 
```

As you can see, it works for apktool side of things but chokes on smali getting the ZipFile. I'm still confused on one thing though. I see the `Java.ZipFile` gained support for Zip64 here - https://blogs.oracle.com/xuemingshen/entry/zip64_support_for_4g_zipfile in b55+

Which I have.

```
➜  Bug1105 java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

I pushed the PR live in case someone wants to mess with it - https://github.com/iBotPeaches/Apktool/pull/1177/files

**Comment by iBotPeaches** [comment]
This actually isn't a Zip64 file. I built one myself and the Oracle 1.7 Java and OpenJDK handled it fine. This is some trickery to the ZIP file that Android handles fine, but apktool does not.

The solution for me was simple, repack the APK using my own native ZIP program than decode it. At this point, it worked fine. I'm hesitant to change our underlying Zip handling code for a dependency for such an edge case. For this reason, I'm closing this.

Here is the OP apk - https://www.virustotal.com/en/file/08b7f64cd6fe69cc2d9f5d6066479aaa2ca54c7a13bb124fce5515ee952d84e7/analysis/1456841253/

Here is my test Zip64 apk - https://www.virustotal.com/en/file/c1ce25b32c0ef4c5cf4d0e9fd12b1090551908748c0e37f17c8c85a1a567af47/analysis/1456841468/

As you can see, VirusTotal doesn't even perceive it as an Android APK. I'm not going to pretend I understand the Zip Format enough, but this is not standard and you can simply repack the APK removing these weird properties and then use apktool.

**Comment by NGTmeaty** [comment]
How would I repack the APK?

**Comment by vivekbsable** [comment]
am generating ePub of size more then 2 GB.

I create zip file first and then rename to .epub

I am using zip64

Python:
`
zp = zipfile.ZipFile(zipFileName, "w", zipfile.ZIP_DEFLATED, allowZip64=True)`

more details: http://stackoverflow.com/questions/37783643/allowzip64-true-will-work-for-small-size-files

Then I pass ePub to ePub Checker and this give following exception.

`FATAL(PKG-008): ./NOID.epub/NOID.epub(-1,-1): Unable to read file 'invalid CEN header (bad signature)'.`

these means that epub can not read by the ePub Checker, so it will not given any error from ePub.

Java Version:

```
$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (rhel-2.6.6.4.el6_8-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

ePubcheck Version:
`
$ /opt/apache-tomcat-8.0.0/webapps/epubcheck4.0.1/epubcheck.jar `

If Zip i.e. ePub file size is less than 2 GB then this error is not coming, but Zip i.e. ePub file size is more than 2 GB then this error is coming.

where is I am wrong?

**Comment by nguyenvulong** [comment]
I recently tested this APK, it is working fine with Oreo version (8.1)

You guys have any idea how the author created this type of APK?

Thanks
