### ISSUE TITLE
Load Moto x style android 6.0 framework-res error

### ISSUE THREAD

**Issue by kaneawk** [iBotPeaches/Apktool#1111]
error log:

> D:\Tools\API23>java -jar apktool-2.0.3-237283-SNAPSHOT-small.jar if framework-res.apk
> W: Config flags size > 52. Exceeding bytes: 0x16662214.
> W: Invalid config flags detected: string-mcc204-mnc4-ERR0
> W: Config flags size > 52. Exceeding bytes: 0x16662214.
> W: Invalid config flags detected: array-mcc204-mnc4-ERR1
> W: Config flags size > 52. Exceeding bytes: 0x16662214.
> W: Invalid config flags detected: bool-mcc204-mnc4-ERR2
> I: Framework installed to: C:\Users\Kane\apktool\framework\1.apk

motox style android 6.0 framework-res download link:

https://mega.nz/#!r9RjCA4Q!4GZjI63nl4jUgvE7DqL74gLtz_gcMPBlKcXbfZN-GMI

when recompile and push to system,the phone will display a broken dialog background.

like this pic:

https://mega.nz/#!jwYxlaLQ!2_INPT21V_e1g_Tifsz9NVN_4cTvsptrpOg-ZrTw1FY

**Comment by kaneawk** [comment]
OK, I try to use b0eb58 version(
https://github.com/iBotPeaches/Apktool/commit/b0eb58a4263a198bc587f50c5ca855e849442d5d)
it will no longer display broken background.Config flags size problem persists.

**Comment by iBotPeaches** [comment]
I have not seen a `Configuration` with more than 52 bytes yet.

```
I: Using Apktool 2.0.3-831765-SNAPSHOT on framework-res.apk
I: Loading resource table...
W: Config flags size > 52. Exceeding bytes: 0x16662214.
W: Invalid config flags detected. Dropping resources: string-mcc204-mnc4-ERR0
W: Config flags size > 52. Exceeding bytes: 0x16662214.
W: Invalid config flags detected. Dropping resources: array-mcc204-mnc4-ERR1
W: Config flags size > 52. Exceeding bytes: 0x16662214.
W: Invalid config flags detected. Dropping resources: bool-mcc204-mnc4-ERR2
```

This is strange. Will investigate. Better not be custom qualifiers.

**Comment by kaneawk** [comment]
But,What's the problem about display a broken backgroud???I found that two issue is NOT one problem.  :)

**Comment by iBotPeaches** [comment]
You said resolved the broken background by using the newest version, therefore the only problem is the configuration flags.

**Comment by kaneawk** [comment]
No No No,display a broken backgroud and apktool error message(Config flags size) is not one problem.
Before I thought that those was caused by the same problem(Config flags size),but I was wrong."Config flags size" just is a steps,seemingly doesn't affect to use.
Maybe between https://github.com/iBotPeaches/Apktool/commit/b0eb58a4263a198bc587f50c5ca855e849442d5d to lasted version https://github.com/iBotPeaches/Apktool/commit/237283c01d1936672cb036f65451f495cc9a0930 commits caused display a broken background problem.
Not only motorola motox style use the lasted version will display a broken background,but samsung galaxy s6 android 5.1.1 also occurs this problem.Hahaha.

**Comment by juliocesark** [comment]
I recommend closing the issue because the code solves a problem that does not exist and is long open since 2016.

**Comment by iBotPeaches** [comment]
Closing because its been 5+ years and no real movement here, not to mention config qualifiers have been updated many many times.
