### ISSUE TITLE
java 1.8

### ISSUE THREAD

**Issue by FarajiMehrdad** [iBotPeaches/Apktool#1112]
can use Apktool 2.x with java 1.8 installed?

**Comment by iBotPeaches** [comment]
Yes.

**Comment by musafirsafwan** [comment]
I think it should be reflected [here](https://ibotpeaches.github.io/Apktool/install/). People may think that it will work only with Java 1.7

**Comment by iBotPeaches** [comment]
@musafirsafwan  - Updated - https://github.com/iBotPeaches/Apktool/commit/c63816391232a03968a0eeed8852ad9ce69b588f
