### ISSUE TITLE
Android M HTC One M9 framework-res: Animations getting broken when recompiling

### ISSUE THREAD

**Issue by jtothe4n** [iBotPeaches/Apktool#1116]
When recompiling framework-res, even without any changes done, it breaks some animations.
Decompiling the recompiled framework-res again doesn't show any changes (for me) though, besides some created apktool id dummies..and that the resources.arsc is a few kb bigger in size.

I tried with official 2.0.2 and 2.0.1 (resources.arsc is a few kb smaller here)
Tried to build from source, but it failes, found a version from 21.12.15, no luck either.

Attached is the stock framework-res an the recompiled one.
Also attached two vids that show the issue/difference.
Working animation: fades smooth from right top edge.
Broken animation: well you will see it, its stutters a lot.

[framework-res files.zip](https://github.com/iBotPeaches/Apktool/files/72516/framework-res.files.zip)
[vids.zip](https://github.com/iBotPeaches/Apktool/files/72515/vids.zip)

**Comment by mythtrandyr** [comment]
i recompile you framework-res.apk, using Apktool 2.0.3-831765-SNAPSHOT
Test it: https://www.dropbox.com/s/xcae0ov4sjdz669/framework-res.apk

**Comment by jtothe4n** [comment]
Animations still broken and it seems to broke some more styles.
The android.app.Dialog looks like that now: https://goo.gl/65p5Os
Icons gone and yeah, it looks weird black background with a white frame.

How were you able to compile from source? Getting missing symbols everywhere

**Comment by jtothe4n** [comment]
I know that the HTC framework files can be a bitch sometimes...there were issues in the past and still are. We decided to let the framework-res.apk untouched an introduce our own framework-res-venom.apk

**Comment by iBotPeaches** [comment]
![diff](https://cloud.githubusercontent.com/assets/611784/12092740/8756b73e-b2c4-11e5-93d5-68c86623a95a.png)

Decode. Build. Decode Built application and compare. The changes have nothing to do with animations & styles, with the exception of one dummy resource.

This is a mix of #1119 #1111 #1019 or #1097 (public resources)

So in short. Still no idea. This issue plaguing multiple apks needs more research.

**Comment by jtothe4n** [comment]
Thanks that you made the effort to take a quick look at it.
I also can't explain why its messing up the animations.
Theres also an issue again with framework-res-htc.apk.
On 2.0.2 also with Settings.apk again, here its fixed with the latest apktool build from source though.

**Comment by xpirt** [comment]
The exact same issues is facing LG's MM framework.

**framework-res.apk**
With 2.0.3, after decompiling/recompiling I get dialogboxes with black background and white frame (some FCs too).

**lge-res.apk**
With 2.0.3, after decompiling/recompiling everything works fine except for menu animations broken (same exact glitch happening on HTC)

lge-res.apk: [http://dl.fulmics.com/g3/lge-res.apk](http://dl.fulmics.com/g3/lge-res.apk)

**Comment by xpirt** [comment]
@iBotPeaches Did you have a chance to re-look into it?

**Comment by iBotPeaches** [comment]
The above commit **might** fix this. I haven't done a real life APK test yet, only unit-tests.

**Comment by jtothe4n** [comment]
I'll test it quickly for you. gimme 5 mins

**Comment by jtothe4n** [comment]
can confirm that it works. thanks a lot! Will make the life for themers a lot more easier.

**Comment by iBotPeaches** [comment]
Thanks for the quick test. When I have time, I'll close this up and check the related issues and update the changelog.

**Comment by iBotPeaches** [comment]
Closing per fixed in #1270
