### ISSUE TITLE
If the assets directory files have the suffix is null

### ISSUE THREAD

**Issue by zhiyiLi** [iBotPeaches/Apktool#1122]
If the assets directory files have the suffix is null
i found the apktool.yml would be show:
doNotCompress:
- arsc
- dat
- xml
- uwc
- jar
- dgc
- ''
- cbx
- bin
- zip
- so

if will compile failed!

ERROR: input directory 'cbx' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\lizhiy
i\AppData\Local\Temp\brut_util_Jar_7888769076672255551.tmp, p, --forced-package-
id, 127, --min-sdk-version, 9, --version-code, 100, --version-name, 1.0.0, -F, C
:\Users\lizhiyi\AppData\Local\Temp\APKTOOL7651220129081251202.tmp, -0, arsc, -0,
 dat, -0, xml, -0, uwc, -0, jar, -0, dgc, -0, , -0, cbx, -0, bin, -0, zip, -0, s
o, -0, arsc, -I, C:\Users\lizhiyi\apktool\framework\1.apk, -S, D:\Program Files\
AnySDK\tool\win\sss\res, -M, D:\Program Files\AnySDK\tool\win\sss\AndroidManifes
t.xml]

i guess command was wrong!

**Comment by iBotPeaches** [comment]
A pull request is already in to fix this. Thanks for the report.

**Comment by iBotPeaches** [comment]
https://github.com/BurgerZ/Apktool/commit/22bd5b0acc15abf9405028f473a7f14e3e16e954 fixed, including for `2.1.0` release.

**Comment by SSOOnline** [comment]
how to download apktool.jar with 2.1.0

**Comment by rockz5555** [comment]
Apktool 2.0.3

ERROR: input directory 'arsc' does not exist

**Comment by rockz5555** [comment]
@iBotPeaches 

Apktool 2.0.3
ERROR: input directory 'arsc' does not exist

**Comment by BurgerZ** [comment]
@rockz5555 upload your apk.

**Comment by iBotPeaches** [comment]
To everyone who keeps reporting this bug. Yes I know, its affecting a lot of people. All you have to do is remove the blank entry from the `apktool.yml` file.

If you see an entry that is blank in that list then remove it. I detailed the workaround here - https://github.com/iBotPeaches/Apktool/issues/1137#issuecomment-171961666
