### ISSUE TITLE
apktool 2.0.3 breaks HTC One M8 marshmallow framework.style

### ISSUE THREAD

**Issue by lyapota** [iBotPeaches/Apktool#1123]
Recompiled with apktool 2.0.3 framework-res lost null pointed lines and AlertDialog get black background with black text.
correct styles decompiled with apktool 2.0.2

    <style name="AlertDialog.Material" parent="@style/AlertDialog">
        <item name="fullDark">@null</item>
        <item name="topDark">@null</item>
        <item name="centerDark">@null</item>
        <item name="bottomDark">@null</item>
        <item name="fullBright">@null</item>
        <item name="topBright">@null</item>
        <item name="centerBright">@null</item>
        <item name="bottomBright">@null</item>
        <item name="bottomMedium">@null</item>
        <item name="centerMedium">@null</item>
        <item name="layout">@layout/alert_dialog_material</item>
        <item name="listLayout">@layout/select_dialog_material</item>
        <item name="multiChoiceItemLayout">@layout/select_dialog_multichoice_material</item>
        <item name="singleChoiceItemLayout">@layout/select_dialog_singlechoice_material</item>
        <item name="listItemLayout">@layout/select_dialog_item_material</item>
        <item name="progressLayout">@layout/progress_dialog_material</item>
        <item name="horizontalProgressLayout">@layout/alert_dialog_progress_material</item>
    </style>

not correct styles decompiled with apktool 2.0.3

    <style name="AlertDialog.Material" parent="@style/AlertDialog">
        <item name="layout">@layout/alert_dialog_material</item>
        <item name="listLayout">@layout/select_dialog_material</item>
        <item name="multiChoiceItemLayout">@layout/select_dialog_multichoice_material</item>
        <item name="singleChoiceItemLayout">@layout/select_dialog_singlechoice_material</item>
        <item name="listItemLayout">@layout/select_dialog_item_material</item>
        <item name="progressLayout">@layout/progress_dialog_material</item>
        <item name="horizontalProgressLayout">@layout/alert_dialog_progress_material</item>
    </style>

**Comment by iBotPeaches** [comment]
Can I have the apk to investigate? I thought I patched `@null` correctly, but looks like I actually broke it.

**Comment by lyapota** [comment]
Of course. Here original file. And after recompile it, we(HTC M8/M9 MM users) getting a litle broken new MM menu animation.Animation MXL files recompiles correctly, but looks like we lost some attributes.
Anyway it other story...
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/78097/framework-res.apk.zip)
 Thx...

**Comment by TeutonJon78** [comment]
I had a similar problem on an iFive air. 2.0.2 unpack/repack correctly. 2.0.3 gives an inverted dialog.
![screenshot_2016-01-04-00-56-46](https://cloud.githubusercontent.com/assets/1771400/12184201/b9216fc6-b548-11e5-9571-bdde3d228b82.png)

**Comment by iBotPeaches** [comment]
![test](https://cloud.githubusercontent.com/assets/611784/12185932/0bc8e108-b564-11e5-8982-8f67c33c1aa9.png)

left = 2.0.3
right = dev

It looks like its fixed, all the `@null` values are back (which for this apk) was only one.
