### ISSUE TITLE
error code during installation

### ISSUE THREAD

**Issue by amainyebriggs** [iBotPeaches/Apktool#1125]
the rcompile apk does not install on android 4.2.2 ,4.3 , 4.0 ,4.1 ,3.0 ,2.3 2.6 but work on 4.4 , 5.0 ,6.1
am using apktool 2.02  smali 2.08 , baksmali 2.08

**Comment by iBotPeaches** [comment]
Gonna need a lot more details than that. APK, stacktrace, logcat of problem.

**Comment by amainyebriggs** [comment]
i decompiled an apk file that works on andriod os 4.1.2 to 5.1  and when i recompiled it that was not installing on android 4.1, 4.2 ,4.3 any longer but still works on 4.4.2,5.0,5.1
am using apktool 2.02 baksmali and smali 2.08

thanks

**Comment by jack16099** [comment]
check minsdk/targetsdk in yml file

**Comment by iBotPeaches** [comment]
Let this report fall behind it seems. There isn't much to go on here even with the explanation. Need a stacktrace or APK to investigate this further.
