### ISSUE TITLE
applyPatches failed

### ISSUE THREAD

**Issue by jerry-bond** [iBotPeaches/Apktool#1127]
D:\projects\Apktool>gradlew.bat applyPatches
Building SNAPSHOT (master): a64a03
:updateSubmodules UP-TO-DATE
:applyPatches
Creating D:\projects\Apktool\brut.apktool.smali repository...
Resetting D:\projects\Apktool\brut.apktool.smali...
Applying patches from D:\projects\Apktool\gradle\smali-patches to D:\projects\Apktool\brut.apktool.smali
:applyPatches FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':applyPatches'.
 Process returned error code. Expression: (result == 0). Values: result = 1
Try:
Run with --stacktrace option to get the stack trace. Run with --info or 
--debug option to get more log output.

BUILD FAILED

Total time: 9.768 secs

I followed these steps described on  `http://ibotpeaches.github.io/Apktool/build/`, but failed as above.
How does `applyPatches` task defined and How to resolve it? 

I only find some relative thing in `build.gradle`,but it doesn't say how to make patch.

    patches {
       submodule = 'smali'
       target = file('brut.apktool.smali')
       patches = file('gradle/smali-patches')
    }

`gradle\smali-patches\001-baksmali-diffpre.patch` and 6 other patch files exist, the target files are not patched as these 7 file described.

**Comment by rover12421** [comment]
```shell
rm -rf brut.apktool.smali
cd smali
gradle build
cd ..
gradle applyPatches
gradle fatjar
```

**Comment by jerry-bond** [comment]
Re: rover12421
    
    rm -rf brut.apktool.smali
    cd smali
    gradle build
    cd ..
    gradle applyPatches
    
Same error, but thank you.

**Comment by rover12421** [comment]
Note that line breaks windows platform. If not newline "\n", will lead to `applyPatches` failure.

**Comment by jerry-bond** [comment]
Re: rover12421 
On windows platform all files end up with 0xd 0xa, I still cann't find out why `applyPatches` failed so I give it up. I compiled successfully on ubuntu. Thanks a lot.
