### ISSUE TITLE
 error: Public symbol style/XXXXXXXXXX declared here is not defined.

### ISSUE THREAD

**Issue by Henry-T** [iBotPeaches/Apktool#1132]
I encounter this problem when repackaging.

```apktool b``` failed because of 

```bash
public.xml:787: error: Public symbol style/unipay_dialog_land declared here is not defined.
```

The style **unipay_dialog_land** is defined in android project like this:

```xml
<style name="unipay_dialog.land">
    <item name="android:layout_marginLeft">80dp</item>
    <item name="android:layout_marginRight">80dp</item>
</style>
```

So it is looking for **unipay_dialog_land** but declaration is **unipay_dialog.land**.

I don't know much about android theme. But as a feature, I think theme parenting is widely used. Maybe its result of some other things, haven't get a clue by now.

> style/XXXXX not defined is the only error type

![image](https://cloud.githubusercontent.com/assets/4081321/12222212/9557e2aa-b7f0-11e5-862e-0371fce09aa0.png)

**Comment by iBotPeaches** [comment]
So the decode to the `styles.xml` fail and generate the wrong name? IE it wrote `unipay_dialog.land` when it should have used `unipay_dialog_land`.

Or was this just a badly written application that is only be detecting with a more restrictive aapt binary? APK would help :)

**Comment by Henry-T** [comment]
Hello, iBotPeaches. The problem is solved and it's not a issue of apktool.

My own tool chain generates public.xml from R.java. Aapt renames unipay_dialog.land to unipay_dialog_land during R.java generation phase.

**Comment by jochasinga** [comment]
> So the decode to the `styles.xml` fail and generate the wrong name? IE it wrote `unipay_dialog.land` when it should have used `unipay_dialog_land`.
> 
> Or was this just a badly written application that is only be detecting with a more restrictive aapt binary? APK would help :)

Would be great to spin off this "naming convention" topic as a wiki since I've been seeing this more and more with apktool/aapt from non-english apks.

**Comment by AlexWatson1418** [comment]
Can plz anyone help me with this problem. i have stucked with the same problem and i dont know how to solve it.

**Comment by AlexWatson1418** [comment]
W: /home/kali/Desktop/Ugly/res/values/public.xml:66: error: Public symbol array/error_reporter declared here is not defined.
W: /home/kali/Desktop/Ugly/res/values/public.xml:67: error: Public symbol array/sound_effect_array declared here is not defined.

**Comment by AlexWatson1418** [comment]
![Screenshot 2020-04-25 18:21:12](https://user-images.githubusercontent.com/64321532/80284372-c32f1e80-8750-11ea-8164-2b24154d4105.png)

**Comment by sakibguy** [comment]
W: c:\dev\tiktok\com.zhiliaoapp.musically\res\values\public.xml:18893: error: no definition for declared symbol 'com.zhiliaoapp.musically:layout/a0j'.
W: c:\dev\tiktok\com.zhiliaoapp.musically\res\values\public.xml:18895: error: no definition for declared symbol 'com.zhiliaoapp.musically:layout/a0l'.
W: c:\dev\tiktok\com.zhiliaoapp.musically\res\values\public.xml:18902: error: no definition for declared symbol 'com.zhiliaoapp.musically:layout/a0s'.
W: c:\dev\tiktok\com.zhiliaoapp.musically\res\values\public.xml:18907: error: no definition for declared symbol 'com.zhiliaoapp.musically:layout/a0x'.
W: c:\dev\tiktok\com.zhiliaoapp.musically\res\values\public.xml:18911: error: no definition for declared symbol 'com.zhiliaoapp.musically:layout/a11'.
W: error: failed linking references.
