### ISSUE TITLE
Apktool Failing to recompile obfuscated apk(using apktool 2.0.3)

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1134]
Apktool is failing to recompile obfuscated apk. Error showed is, "illegal characters in manifest. There are some uniocode characters in manifest file due to obfuscation. Can we expect a solution for this anytime soon?

**Comment by iBotPeaches** [comment]
Duplicate of #885

**Comment by jack16099** [comment]
so any fix coming?

**Comment by iBotPeaches** [comment]
if//when I figure it out. Yes
