### ISSUE TITLE
Apktool only for the AndroidManifest

### ISSUE THREAD

**Issue by AresS31** [iBotPeaches/Apktool#1135]
Hi,

I have a request for proposal. I think that it will be a nice feature to add an option to only decode/encode the AndroidManifest. Indeed, since in the script that I develop since a while I am using apktool to only perform this task. It is a waste of time and resourcing to proceed the whole apk when I am only interested by the AndroidManifest.
I am not sure that here is the best place to post this message. If it is the case please feel free to redirect me to the proper place for this kind of requests.

Best regards,
Alexandre

**Comment by iBotPeaches** [comment]
Unfortunately `AndroidManifest.xml` decoding is very different across APKs. Some reference strings/ids are only available in frameworks and the apk itself. This makes a proper decode near impossible, unless you like looking at resource ids vs real human readable names.

So I don't see this happening any time soon.

**Comment by jaredrummler** [comment]
Have a look here: https://github.com/jaredrummler/APKParser

```java
AndroidManifest manifest = ApkParser.create(file).getAndroidManifest();
```

Would be awesome to see something like this in ApkTool. :+1:

**Comment by jifang** [comment]
aapt tool can extract the information from apk, too.
`aapt l -a ${PATH_TO_APK}`
It is not the xml output, but you can parse the result yourself. It is a much faster solution.
