### ISSUE TITLE
build error- loop did not match anything at input

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1136]
Was trying to build an obfuscated apk and a small change in the smali file caused build failure. But even after removing the change from the edited smali to the previous original smali, apktool is giving same error ie, loop did not match anything at input '?'. exception in thread "main" brut.androlib.AndrolibException:   Could not smali file: o/?.smali

BTW, I searched whole smali folder but I cant find ?.smali. Not sure I missed it or not but I searched it multiple times. Not sure the file even exist. 

Simply saying, app was recompiling before making a small change in a smali file but after doing it, the above mentioned error started coming. But even after removing the change from that particular smali file, apktool is giving same error on next build attempts. using apktool 2.0.3

**Comment by iBotPeaches** [comment]
Seems to be a UTF8/locale issue here. During decode you couldn't represent the characters needed (Obfuscation using plenty strange ones)

**Comment by jack16099** [comment]
Tried manual smali method without apktool. then too, same issue. if no changes are made to the smali files, it will build without any issue. but even if a small change is made and then we delete that change, even then it will not backsmali. So this is a a UTF8/locale issue?

**Comment by jack16099** [comment]
btw, here's the exact error message.

test.apk\o\?.smali[1,0] required <...>+ loop did not match anything at input '?'

**Comment by iBotPeaches** [comment]
I'm having a hard time understanding what you are saying. Why don't you just upload the apk and let me investigate if I can build/decode.

**Comment by jack16099** [comment]
sorry, here's the app link

https://play.google.com/store/apps/details?id=com.in.hammervpn

here's the apk link http://dl3.apk-dl.com/root/apk/2015/12/27/com.in.hammervpn_28.apk?f=Hammer%20VPN%20-%20%20Anti%20-%20DPI%20VPN_apk-dl.com.apk

**Comment by jack16099** [comment]
You were right. It was a UTF encoding issue. Finally I used notepad++ and used the option convert to UTF-8(encoding menu) and it successfully compiled. Might be useful for somebody in the future. Thanks for the help.
