### ISSUE TITLE
skipping dir '_240x' due to ANDROID_AAPT_IGNORE pattern '_*'

### ISSUE THREAD

**Issue by jmspt** [iBotPeaches/Apktool#1139]
When I decompile and compile a APK with Apktool I am getting this problem:

INFO: Building apk file...
    (skipping dir '_240x' due to ANDROID_AAPT_IGNORE pattern '_*')
    (skipping dir '_320x' due to ANDROID_AAPT_IGNORE pattern '_*')
    (skipping dir '_480x' due to ANDROID_AAPT_IGNORE pattern '_*')

I'm not modify any file.

**Comment by iBotPeaches** [comment]
This is aapt telling you it is ignoring resource directories, because it doesn't know about them. Not a bug.
