### ISSUE TITLE
2.0.3:  empty item (- '') added to doNotCompress in apktool.yml => no compression at all

### ISSUE THREAD

**Issue by d4rkd3v1l** [iBotPeaches/Apktool#1144]
In apktool 2.0.0rc2 everything was working fine, but since upgrading to 2.0.3 the repacked apk seems not to be compressed correctly. 
original apk: 60mb, repacked: 250mb

I did some tests, and found out, that the new apktool adds some stuff to the "doNotCompress" section in apktool.yml, which leads to the big apk.

**Comment by BurgerZ** [comment]
Could you upload this apk?

**Comment by d4rkd3v1l** [comment]
I created a test apk (sorry, but I cannot upload the original one), this is just 11mb in size, and after repacking only 11.1mb, but it at least added one item to `doNotCompress`

    doNotCompress:
    - arsc

Is there any documentation, on what, will be added here, and how to disable it?

In the original .apk I got a lot of stuff there:

    doNotCompress:
    - arsc
    - html
    - otf
    - sqlite
    - ''
    - txt
    - sql

The .apks were created using Unity 5.3.1 (if that matters).
Please let me know if you need any further information.

[test.apk.zip](https://github.com/iBotPeaches/Apktool/files/103381/test.apk.zip)

**Comment by BurgerZ** [comment]
All is correct:
in this apk resources.arsc is not compressed, so 
````
doNotCompress:
- arsc
````
is correct. 
I see no issues here.

**Comment by d4rkd3v1l** [comment]
Ok, did not know how to check, if it was compressed before, however, I just figured out that `- ''` in `doNotCompress:` matches any file and leads to no compression at all.

I'll do some more test, to find out where it comes from.

**Comment by BurgerZ** [comment]
before your test, build apktool, because I made a commit to fix that ('' - empty item).

**Comment by d4rkd3v1l** [comment]
Ok just figured out, that this empty item `''` is being added, when there is a file, without extension, that is not compressed ;-)

**Comment by d4rkd3v1l** [comment]
Sorry, but where is this commit? I didn't find it.. Anyhow I don't have everything set up to make a build of apktool. 
But I'll upload the modified apk, so that you're able to reproduce the issue. When is it expected to see this fix in the a release?

[test_mod.apk.zip](https://github.com/iBotPeaches/Apktool/files/103551/test_mod.apk.zip)

**Comment by BurgerZ** [comment]
11 038 194 - original apk
11 038 178 - rebuilt apk

**Comment by d4rkd3v1l** [comment]
With or without your fix?
Please note, that I just added a test file with probably just a few KB for testing.
Just check the `apktool.yml` to see the `- ''` entry.

**Comment by BurgerZ** [comment]
With "fix".
No '' entries.

**Comment by BurgerZ** [comment]
Try this jar I've just built

[apktool.zip](https://github.com/iBotPeaches/Apktool/files/103614/apktool.zip)

**Comment by d4rkd3v1l** [comment]
Nice, and thank you very much!

Where can I get the fix, or is there already an estimate for the apktool release, where this fix is included?

**Comment by d4rkd3v1l** [comment]
Awesome! Thx a lot for your help, really appreciated it!

**Comment by BurgerZ** [comment]
Does it help you? If so, close the issue as it's fixed in current build :+1:

**Comment by d4rkd3v1l** [comment]
Yes, works like a charm now, using 2.1.0-114af9-SNAPSHOT.
