### ISSUE TITLE
Still multiple resources error while installing framework with apktool_2.0.3

### ISSUE THREAD

**Issue by Jaarviss** [iBotPeaches/Apktool#1146]
I get this error while  installing framework of blisspop 4.0.3
My device is Yureka(tomato) 
But strange thing is that apktool snapshot build installs that framework but alpha version not... 
Any solution? 
 
![screenshot 1](https://cloud.githubusercontent.com/assets/15812066/12574562/e692f100-c42a-11e5-90e1-56dab009ea48.png)

**Comment by Jaarviss** [comment]
Helpful nature would be really appreciated

**Comment by iBotPeaches** [comment]
APK please if you have it. Also note that taking screenshots of stack traces isn't that helpful. Searches cannot read the text in the image, so future searches won't find this bug report.

**Comment by Jaarviss** [comment]
Should i upload framework?

**Comment by iBotPeaches** [comment]
Yes please.

**Comment by Jaarviss** [comment]
Here is the framework 
https://drive.google.com/file/d/0ByaTM8ZfV_eTVW5LcTJScDhrU1U/view?usp=docslist_api

**Comment by BurgerZ** [comment]
Just exception in text:

````
java -jar apktool-2.1.0-114af9-SNAPSHOT.jar if framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0103035f style/Theme.DeviceDefault.Resolver, config=-round
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:252)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:212)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:154)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:608)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:590)
        at brut.androlib.Androlib.installFramework(Androlib.java:673)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
````

**Comment by Jaarviss** [comment]
Any temporary solution?

**Comment by iBotPeaches** [comment]
This APK has unknown qualifiers. Probably from a custom ROM modification or other crazy OEM. We currently have support for Xiaomi (MIUI), because they provide source changes for their modifications.

This APK has `-darktheme` qualifier, which is not listed on Android spec sheet here - http://developer.android.com/guide/topics/resources/providing-resources.html

You will have to ask your ROM developer to create a custom build for you to modify, which isn't easy due to the change required in both `aapt` and `apktool`.

**Comment by Jaarviss** [comment]
Yes sir
It is a custom rom 'Blisspop'  for Yureka device 
They implimented inbuilt theme resources in framework

BTW
Thanx a lot

**Comment by BurgerZ** [comment]
@iBotPeaches I can't find `-darktheme` in this apk. Whare did you find it?
BTW, here is BlissRoms source code https://github.com/BlissRoms

**Comment by Jaarviss** [comment]
@BurgerZ 
Check this out 
![screenshot_2016-01-28-21-45-13](https://cloud.githubusercontent.com/assets/15812066/12650360/8f36a05c-c608-11e5-9975-ce08a803a0d6.png)

**Comment by BurgerZ** [comment]
@Jaarviss thanks, but I tried to dump it with aapt and there was no these qualifiers. I'll try to investigate it deeper.

**Comment by BurgerZ** [comment]
I've found it!!)
https://github.com/TeamBliss-LP/android_frameworks_base/blob/lp5.1/tools/aapt/AaptConfig.cpp
`
bool parseUiThemeMode(const char* name, ResTable_config* out) {
    if (strcmp(name, kWildcardName) == 0) {
      if (out) out->uiThemeMode = out->UI_THEME_MODE_ANY;
        return true;
    } else if (strcmp(name, "darktheme") == 0) {
      if (out) out->uiThemeMode = out->UI_THEME_MODE_HOLO_DARK;
        return true;
    } else if (strcmp(name, "lighttheme") == 0) {
      if (out) out->uiThemeMode = out->UI_THEME_MODE_HOLO_LIGHT;
        return true;
    }

    return false;
}
`

**Comment by iBotPeaches** [comment]
@BurgerZ They won't show up in `aapt d configurations`, because the native aapt you are using doesn't know those qualifiers. I discovered them by simply examining the `apk` file visually with a zip program and noticed the directories.

The code above is all I need, but I don't know the numerical values of the changes yet. I included MIUI because they picked values large enough away that even after 20 releases of AOSP, they would never collide with the values they used.

I also don't know if I will include them, otherwise this becomes a norm of including 3rd party changes into mainline apktool.

**Comment by BurgerZ** [comment]
@iBotPeaches Thanks. I can find out all stuff by myself. Then make a PR for apktool and aapt.

**Comment by Jaarviss** [comment]
I would like to add one more thing
I had used your SNAPSHOT BUILD 2.0.0  Before this latest version, That build had installed  'this'  framework with warning but only one problem with  that was, apktool did not compile 'darktheme' resources along with others 

See  pics of dialer,here dialer contained darktheme resources before compilation ; but after compiling, all are gone(strange thing is that apktool compiles it without errors as well as Dialer still working fine) 
PS-I just changed the layout gravity of 'Call'  button to center by editing styles.xml only because it was not align with the center HOME button (hardware button)  while
![screenshot_2016-01-28-23-12-15](https://cloud.githubusercontent.com/assets/15812066/12653638/7ae31320-c616-11e5-867c-d674c5050d70.png)
![screenshot_2016-01-28-23-12-51](https://cloud.githubusercontent.com/assets/15812066/12653657/8c39e5f4-c616-11e5-8318-6c4d1c7d1361.png)

 changing the dpi of screen
