### ISSUE TITLE
2.0.3 rebuild Apk file becomes mush larger than 2.0.2!!!!!

### ISSUE THREAD

**Issue by GeorgeValentin** [iBotPeaches/Apktool#1149]
on my mac

$ du -sh  123.apk
**7.9M	123.apk**

$ ./apktool --version
**2.0.2**
$./apktool d -f 123.apk -o 123
$./apktool b 123 -o 456.apk
$ du -sh 456.apk
**7.8M	456.apk**

$ ./apktool --version
**2.0.3**
$./apktool d -f 123.apk -o 123
$./apktool b 123 -o 789.apk
$ du -sh 789.apk
**14M	789.apk**

**Comment by BurgerZ** [comment]
I think it's fixed in master branch. Just try this apktool - https://github.com/iBotPeaches/Apktool/files/103614/apktool.zip

**Comment by GeorgeValentin** [comment]
thanks, but  my apk rebuild by 2.0.2

**Comment by GeorgeValentin** [comment]
But Resulting apk file by **2.0.2** is a little **smaller(24k in my case)** than original.
Resulting apk file by **2.1.0-114af9-SNAPSHOT** https://github.com/iBotPeaches/Apktool/files/103614/apktool.zip is a little **larger(36k in my case)** than original.



And:
The FAQ http://ibotpeaches.github.io/Apktool/documentation/#faq says:
_**Resulting apk file is much smaller than original! Is there something missing?**_
There are a couple of reasons that might cause this.

Apktool builds unsigned apks. This means an entire directory META-INF is missing.
New aapt binary. Newer versions of apktool contain a newer aapt which optimizes images differently.
These points might have contributed to a smaller than normal apk

**Comment by iBotPeaches** [comment]
There is no way to maintain a perfect 1-1 size ratio between original and rebuilt. The application naturally runs through aapt compression, dex assemble/disassemble and a full reconstruction of the resources.arsc file.

If you want to investigate and find the files that are differing then we might be able to look if this a bug or just naturally effect of using apktool.
