### ISSUE TITLE
Where is the source of builtin aapt?

### ISSUE THREAD

**Issue by pangqingyuan1991** [iBotPeaches/Apktool#1150]
Is it accessable?

**Comment by BurgerZ** [comment]
https://github.com/iBotPeaches/platform_frameworks_base

**Comment by pangqingyuan1991** [comment]
It is so kind of you @BurgerZ

**Comment by iBotPeaches** [comment]
Yes, and in case you didn't notice the work is done on branch `apktool-mm`. For the marshmallow release of AOSP.
