### ISSUE TITLE
Can't install .apk after build

### ISSUE THREAD

**Issue by emanf** [iBotPeaches/Apktool#1151]
hi,

i decoded a apk file and i didn't change anything after that i just build it and then i tried to install the apk but i got below error even after some basic change.

what i did:(using windows cmd)
`apktool d somename.apk -o testfolder`
then 
`apktool b testfolder`

and:
```
adb install somename.apk
        pkg: /data/local/tmp/somename.apk
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
rm failed for -f, No such file or directory
```

can you help me about it?

**Comment by iBotPeaches** [comment]
Did you resign it? Was it a system app? This isn't a support form, this is for bugs. Please try StackOverflow or XDA.

**Comment by emanf** [comment]
>  Was it a system app?
no.

> Did you resign it
no. how?

please help me in
http://stackoverflow.com/questions/35099474/cant-install-apk-after-buildapktool-apkstudio

**Comment by BurgerZ** [comment]
@emanf http://stackoverflow.com/questions/35099474/cant-install-apk-after-buildapktool-apkstudio/35099912#35099912

**Comment by emanf** [comment]
thanks. it works now. i just forgot to resign it.
