### ISSUE TITLE
Android M AOSP Custom Rom @ framework-res: Animations;"Animator duration scale animations" getting broken when recompiling

### ISSUE THREAD

**Issue by jangett** [iBotPeaches/Apktool#1155]
When recompiling framework-res, without any changes done, it breaks "Animator duration scale animations"
This Animations may affect "menu button dialog & nav-bar button at push animation"

This situation occurs in other custom rom base on Android M (6.0.1) AOSP Source; Custom Rom. (ex. Chroma, Cataclysm, etc.)

I tried with official 2.0.2 and 2.0.3, unoffical 2.1.0.8525be-SNAPSHOT version. (compile directly with ubuntu)
But, Occur same situation.

I've found issues forum, and these people are experiencing the same problem.
https://github.com/iBotPeaches/Apktool/issues/1116

Attached is the framework-res an the recompiled one.
framework-res.apk : https://www.dropbox.com/s/397c2jkbtjodk3t/framework-res.apk?dl=0
Recompiled framework-res.apk : https://www.dropbox.com/s/v8i896v0pfjvs5u/Recomplied-framework-res.apk?dl=0

This framework is Original Nexus 5 Custom Rom (Chroma 1/18/2015)'s framework-res.apk & Re-compiled (Not revised) framework-res.apk

Thanks for reading and I hope fix this problem.

framework-res files.zip
vids.

**Comment by iBotPeaches** [comment]
You found the duplicate bug report, but then opened a new one? Yes, this is a known problem. 

Duplicate: #1116
