### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.Direc toryException: java.util.zip.ZipException: error in opening zip fil

### ISSUE THREAD

**Issue by PhoenixICE** [iBotPeaches/Apktool#1162]
"Exception in thread "main" brut.androlib.AndrolibException: brut.directory.Direc toryException: java.util.zip.ZipException: error in opening zip file"

Attempting to open the file in any zip format comes back with no data

This is using apktools 2.0.3 - the apk file: http://www.mediafire.com/download/15bar6ivp0t67tc/com.nhnent.SKQUEST-1.apk

According to Riu the apk might have a "PKZIP cipher"

**Comment by iBotPeaches** [comment]
Correct. It has some weird protection. Either the extra bit or Zip64.

Though, I have no luck using the application on host. So if the application doesn't even install on Android, not going to put any effort into figuring this out.

```
➜  Bug1162  adb install com.nhnent.SKQUEST-1.apk 
5690 KB/s (31461089 bytes in 5.398s)
	pkg: /data/local/tmp/com.nhnent.SKQUEST-1.apk
Failure [INSTALL_FAILED_INVALID_APK]
```

**Comment by PhoenixICE** [comment]
Thanks, not sure how I managed to pull that dll from my phone, re-downloaded and everything was fine, possibly corrupt file?
