### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by SlamberGamer** [iBotPeaches/Apktool#1163]
Hi sir,

i can decompile app but each time i tried to compile it will give me error

Error Log:

> -------------------------------------------------------------------------- 
> |Sun 02/14/2016 -- 21:43:17.58| 
> -------------------------------------------------------------------------- 
> java version "1.8.0_66"
> Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
> Java HotSpot(TM) Client VM (build 25.66-b18, mixed mode)
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\layout-v21\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\layout-v21\listview_episode.xml:8: error: No resource identifier found for attribute 'buttonTint' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\layout-v21\view_settings.xml:7: error: No resource identifier found for attribute 'buttonTint' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\layout-v21\view_settings.xml:12: error: No resource identifier found for attribute 'buttonTint' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\layout-v21\view_settings.xml:17: error: No resource identifier found for attribute 'buttonTint' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_fast_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlX1' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_fast_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlY1' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_fast_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlX2' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_fast_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlY2' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_linear_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlX1' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_linear_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlY1' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_linear_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlX2' in package 'android'
> 
> C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res\interpolator-v21\mr_linear_out_slow_in.xml:2: error: No resource identifier found for attribute 'controlY2' in package 'android'
> 
> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Kira\AppData\Local\Temp\brut_util_Jar_2343828901134476114.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 78, --version-name, 7.8, -F, C:\Users\Kira\AppData\Local\Temp\APKTOOL2318890397569293590.tmp, -0, arsc, -0, arsc, -I, C:\Users\Kira\apktool\framework\1.apk, -S, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res, -M, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\AndroidManifest.xml]
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
> 	at brut.androlib.Androlib.buildResources(Androlib.java:410)
> 	at brut.androlib.Androlib.build(Androlib.java:298)
> 	at brut.androlib.Androlib.build(Androlib.java:268)
> 	at brut.apktool.Main.cmdBuild(Main.java:225)
> 	at brut.apktool.Main.main(Main.java:84)
> Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Kira\AppData\Local\Temp\brut_util_Jar_2343828901134476114.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 78, --version-name, 7.8, -F, C:\Users\Kira\AppData\Local\Temp\APKTOOL2318890397569293590.tmp, -0, arsc, -0, arsc, -I, C:\Users\Kira\apktool\framework\1.apk, -S, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res, -M, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\AndroidManifest.xml]
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
> 	... 5 more
> Caused by: brut.common.BrutException: could not exec command: [C:\Users\Kira\AppData\Local\Temp\brut_util_Jar_2343828901134476114.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 78, --version-name, 7.8, -F, C:\Users\Kira\AppData\Local\Temp\APKTOOL2318890397569293590.tmp, -0, arsc, -0, arsc, -I, C:\Users\Kira\apktool\framework\1.apk, -S, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\res, -M, C:\APK-Multi-Tool-WIP-2.0\projects\Animania.apk\AndroidManifest.xml]
> 	at brut.util.OS.exec(OS.java:89)
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
> 	... 6 more

`

This is the apk file

http://mobi24.net/apks/Animania.apk

Solution that i have tried.

Update all apktool, smali and baksmali to the latest version.

**Comment by iBotPeaches** [comment]
```
➜  Bug1163  apktool d Animania.apk 
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT on Animania.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1163  apktool b Animania
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1163  
```

Give Framework Files a read - http://ibotpeaches.github.io/Apktool/documentation/#framework-files

You probably have an outdated `$HOME/apktool/framework/1.apk`

**Comment by SlamberGamer** [comment]
hi thank for the reply.. i have installed the latest framework in my android.

i dont know why it still wont work.. can you share with me the framework apk that u using?

**Comment by iBotPeaches** [comment]
I use the latest in the apktool binary. Delete frameworks and apktool re-populates it. This isn't a support forum. This is my last response.

**Comment by SlamberGamer** [comment]
sory ibotpeaches.. problem solved now.. thx you..  what i do.. use the latest framework in my android. if u have install it before u need to manually delete the 1.apk inside the apktool/framework that located in user/"pcname"/apktool/framework .. update apktool. smali and baksmali to the latest version.

incase anyone with my problem finding for solution..
