### ISSUE TITLE
apktool b No resource found (2.0.3)

### ISSUE THREAD

**Issue by bxfxf** [iBotPeaches/Apktool#1167]
1. apktool if framework-res.apk
  apktool if framework-ext-res.apk
  apktool if miui.apk
  apktool if miuisystem.apk
2.apktool d MiuiSystemUI.apk
3. apktool b MiuiSystemUI
then it reports these errors:

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/drawable/toggle_bg.xml:6: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/toggle_bg_n').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/drawable/tracking_view_page_style_bg.xml:2: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/tracking_view_page_style_bg_tile').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/color/tab_lable_color.xml:4: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_p').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/color/tab_lable_color.xml:5: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_p').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/color/tab_lable_color.xml:6: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_n').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/color/toggle_lable_color.xml:4: error: Error: No resource found that matches the given name (at 'color' with value '@color/toggle_lable_color_p').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/color/toggle_lable_color.xml:5: error: Error: No resource found that matches the given name (at 'color' with value '@color/toggle_lable_color_n').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/menu/notification_popup_menu.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/notification_inspect_item').

/home/bxf/android/miui7_port/z9mini/out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI/res/menu/notification_popup_menu.xml:4: error: Error: No resource found that matches the given name (at 'title' with value '@string/status_bar_notification_inspect_item_title').

In fact ,these resources is in existence.

attach files:
[tmp.zip](https://github.com/iBotPeaches/Apktool/files/139530/tmp.zip)

**Comment by iBotPeaches** [comment]
No longer patching MIUI related bugs. #806 is the last MIUI bug I'm investigating.

Sorry.
