### ISSUE TITLE
Parse error ( There is a problem parsing your package )

### ISSUE THREAD

**Issue by mcirsta** [iBotPeaches/Apktool#1172]
I've unpacked an apk ( this one : https://drive.google.com/file/d/0BwMYodgF7T1cNW9MX19ta3EyLWM/view?usp=sharing  )

using: java -jar apktool-cli.jar d -s ..\GearS\SamsungGear_v2.2.16011842.apk

then made no modifications to anything and just did:

java -jar apktool-cli.jar b SamsungGear_v2.2.16011842

After that I copied the apk and using the phone file manager tried to install it. I got and error saying that "There is a problem parsing your package" ).

The only thing of interest I've found in logcat is 

D/SystemAdController( 1618): Activity:ActivityInfo{30b2f0f5 com.android.packageinstaller.PackageInstallerActivity}is not the default one
E/ActivityManager(  772): Invalid thumbnail dimensions: 0x0
E/ActivityThread( 8102): Failed to find provider info for com.xiaomi.gamecenter.exportdbcache
W/PackageInstaller( 8102): Parse error when parsing manifest. Discontinuing installation

Apktool is the latest from git ( build by me on Windows ) and Andoid on the phone is 5.0.2 ( MIUI as it's a Xiaomi device )

I might have done something wrong here but I can't really figure out what.

**Comment by iBotPeaches** [comment]
```
➜  dist adb install SamsungGear_v2.2.16011842.apk
7062 KB/s (1035837 bytes in 0.143s)
	pkg: /data/local/tmp/SamsungGear_v2.2.16011842.apk
Success
```

I couldn't duplicate a problem. Ensure you are using the newest apktool and resigning prior to install.

**Comment by mcirsta** [comment]
It was silly of me. I didn't know I had to sign the apk. I don't think the documentation mentions that often ( didn't find it at a quick glance ).
 I'd be really, really nice if apktool had an option to also sign your apk. Maybe I can contribute that if you're willing to add it.

**Comment by iBotPeaches** [comment]
The problem with including it is it kinda bloats apktool greatly. Signing an apk requires either the inclusion of a dependency (`signapk.jar`) or utilizing the code internally.

However, then we need keys and that means an introduction to a new parameter to pass keys. At this point apktool becomes a multi tool. I believe this is best kept as a separate tool.

I do however agree that the documentation and maybe instruction revolving around the use of a tool like `signapk.jar` could be better.

**Comment by mcirsta** [comment]
http://ibotpeaches.github.io/Apktool/documentation/  under Building doesn't really mention signing. A one liner about the signing would help IMO .
 Signing might be obviously need to people that are used to this but it wasn't obvious to me.
 As for the bloating part yes I know people don't want to mix things together and such but the way I see it signapk.jar is 8 KB while the needed files ( pk8 and pem ) are 2 KB, compared to 9777 KB of apktool-cli.jar .
 Maybe just have something for the lazy man ( sign using default keys ) and whoever wants something more can manually do it. So just -g -n to apktool b would get you the final apk that you can just place on your device and install.
 Still I won't insist too much on this. It would be nice to have though.

**Comment by iBotPeaches** [comment]
We can update the docs to include information about signing. I'll need to think on the signing aspect.

**Comment by hooman-pro** [comment]
I have same problem i do these stepes : 
1- run : apktool d my.apk
2- run apktool b my
3- copy my.apk from \dist folder in my  android device honer 5x
when i try to install it say problem with parsing.

note: my.apk is my program file i make it with android studio. and have no sign key.

i try it with multi .apk file and all of theme have same problem.


plz put a good document to how build apk to run in all device. 


and also an other question i see this video: https://www.youtube.com/watch?v=eDbBTqKfgVE
use apktool and also apktool advanced where is advanced files??
