### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by xtianus** [iBotPeaches/Apktool#1174]
All downloads after apktool_2.0.0rc4.jar result in 0-byte files.

**Comment by iBotPeaches** [comment]
Yes aware. Out of my control. Blame bitbucket.

http://connortumbleson.com/apktool/ (mirrors)

**Comment by xtianus** [comment]
The mirror works, thank you.

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/commit/93ab25887db150525ed70a89138ac514d6578f5f#commitcomment-16560635 - Post Mortem if interested.
