### ISSUE TITLE
Miui 7 some apk's can't be decompiled, recompiled

### ISSUE THREAD

**Issue by kolbi077** [iBotPeaches/Apktool#1178]
The mistake generally it, how are you the decompile does not succeed. I tried apktool 2.0.3 and .2.1.0 snapsot the result same thing.

Installed apk's for framework:
- framework-ext-res.apk
- framework-res.apk
- miui.apk
- miuisystem.apk
- MiuiSystemUI.apk

apk decompile examle:

Settings.apk

```
d:\test>apktool d -s Settings.apk
I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on Settings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Martin\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\Martin\apktool\framework\16.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\Martin\apktool\framework\17.apk
I: Decoding Shared Library (miui), pkgId: 16
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textColor, value=0x0106012d
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textColor, value=0x0106012d
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textColor, value=0x0106012d
W: Could not decode attr value, using undecoded value instead: ns=android, name=
summary, value=0x01040698
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textColor, value=0x0106012d
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x01010501
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:507)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:261
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)

d:\test>
```

MiuiCamera.apk decompile ok but the recompile fail:

```
Decompile:

d:\test>apktool d -s MiuiCamera.apk
I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on MiuiCamera.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Martin\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Loading resource table from file: C:\Users\Martin\apktool\framework\16.apk
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

d:\test>

Recompile:

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\Martin\AppData\Local\Temp\brut_util_Jar_7090668814826040442.tmp, p, --forced-
package-id, 7, --min-sdk-version, 16, --target-sdk-version, 19, --version-code,
1, --version-name, 1, -F, C:\Users\Martin\AppData\Local\Temp\APKTOOL16237399698
20867296.tmp, -x, -0, dex, -0, arsc, -0, xml, -0, graph, -0, arsc, -I, C:\Users\
Martin\apktool\framework\1.apk, -I, C:\Users\Martin\apktool\framework\16.apk, -S
, d:\test\MiuiCamera\res, -M, d:\test\MiuiCamera\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\Martin\AppData\Local\Temp\brut_util_Jar_709066
8814826040442.tmp, p, --forced-package-id, 7, --min-sdk-version, 16, --target-sd
k-version, 19, --version-code, 1, --version-name, 1, -F, C:\Users\Martin\AppDat
a\Local\Temp\APKTOOL1623739969820867296.tmp, -x, -0, dex, -0, arsc, -0, xml, -0,
 graph, -0, arsc, -I, C:\Users\Martin\apktool\framework\1.apk, -I, C:\Users\Martin\apktool\framework\16.apk, -S, d:\test\MiuiCamera\res, -M, d:\test\MiuiCamera\
AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:430)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
Martin\AppData\Local\Temp\brut_util_Jar_7090668814826040442.tmp, p, --forced-pa
ckage-id, 7, --min-sdk-version, 16, --target-sdk-version, 19, --version-code, 1,
 --version-name, 1, -F, C:\Users\Martin\AppData\Local\Temp\APKTOOL1623739969820
867296.tmp, -x, -0, dex, -0, arsc, -0, xml, -0, graph, -0, arsc, -I, C:\Users\Martin\apktool\framework\1.apk, -I, C:\Users\Martin\apktool\framework\16.apk, -S,
d:\test\MiuiCamera\res, -M, d:\test\MiuiCamera\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:424)
        ... 6 more
```

[> Please Help.

> Thank's.](url)

**Comment by iBotPeaches** [comment]
@ingbrzy Do you have these errors with MIUI 7 apks?

**Comment by kolbi077** [comment]
Yes.

**Comment by kolbi077** [comment]
Yes, I uploaded files.
[miui7.zip](https://github.com/iBotPeaches/Apktool/files/151166/miui7.zip)

**Comment by ingbrzy** [comment]
@iBotPeaches we are not using your aapt....

**Comment by iBotPeaches** [comment]
Thanks @ingbrzy 

Yep, not supporting MIUI. Sorry @kolbi077

**Comment by peter23** [comment]
I made some investigation about this problem and I hope my information will be useful. It is related to MIUI (both 7 and 8) based on Android 5.*. There are several related things:
- MIUI uses non-standard IDs for system applications - 7. This Settings.apk also has ID 7. In AOSP all system applications have ID 1.
- In Android 5 support for ^attr-private was added. Values with that type are in MIUI's framework and several of them are used by Settings.apk.
- In Android 5 aapt was changed. Two lines are important in our case:
  - https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/libs/androidfw/ResourceTypes.cpp#4722
  - https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/libs/androidfw/ResourceTypes.cpp#4738
SYS_PACKAGE_ID is set to 0x01, so MIUI system apps are not considered as system. It leads to errors during building of MIUI system apps with aapt from Android 5.
- So, what we have? aapt from Android 4 can not build apk with ^attr-private and aapt from Android 5 can not build apk of system apps with ID != 1. I'm not sure how Xiaomi.eu solved this problem, but there are values in Xiaomi.eu's Settings.apk, which are references to ^attr-private in framework, and they are incorrect references. It is the reason of this issue. I found six incorrect references:
  - 0x01010501 should be 0x0116001e
  - 0x01010502 should be 0x0116001f
  - 0x01010503 should be 0x01160020
  - 0x01010560 should be 0x0116007f
  - 0x01010561 should be 0x01160080
  - 0x01010562 should be 0x01160081
@ingbrzy, maybe it it interesting for you.

Latest version of apktool (starting from https://github.com/iBotPeaches/Apktool/commit/c1cb9425d5f217beb273dee5a7cea7b0c9aa9b28) just ignores such references. And maybe the next version will show messages about them (using https://github.com/iBotPeaches/Apktool/pull/1413).

Also for my needs I made a patch to aapt from Android 5 which allows to build system apps with ID != 1: http://pastebin.com/iUbDCExN
@iBotPeaches, is it useful if I'll make more clean solution? For example add option to aapt like '--allow-sys-packages-with-any-id'. And add the same option to apktool, which will just translate it to aapt.



If someone can read in Russian then you can also see my posts on 4pda.ru/forum/:
http://4pda.ru/forum/index.php?showtopic=557858&view=findpost&p=51479597
http://4pda.ru/forum/index.php?showtopic=557858&view=findpost&p=51491728
http://4pda.ru/forum/index.php?showtopic=557858&view=findpost&p=51497921

**Comment by iBotPeaches** [comment]
Closing because MIUI and aapt2 is out really changing the entire resource game. 3+ years without a response. This isn't going anywhere.
