### ISSUE TITLE
Res9patchStreamDecoder.java decodes incorrectly on non-RGBA 9patch PNGs

### ISSUE THREAD

**Issue by mattsarett** [iBotPeaches/Apktool#1180]
PNGs may encoded in multiple different formats (ex: Color table, RGB, RGBA, Gray, GrayAlpha etc.).  Previous versions of aapt would always use an RGBA encoding on 9patch PNGs.

The upcoming version of aapt will encode 9patch PNGs in any format.  This triggers a bug in Res9patchStreamDecoder.java, where some types of PNGs are handled incorrectly.

I'm currently working on a fix for this.  Would you be receptive to taking this fix?  Please let me know if you have any thoughts or input!

Best,
Matt

**Comment by iBotPeaches** [comment]
By upcoming aapt do you mean aapt2? Or a patch aapt release?

I'm aware of plenty of bugs with our 9patch decoder. I've been meaning to update it in spec with the new format listed here - https://github.com/iBotPeaches/platform_frameworks_base/blob/apktool-mm/include/androidfw/ResourceTypes.h#L50 , but life and other bugs have gotten the best of me.

Any fix towards 9 patch will be appreciated.

**Comment by mattsarett** [comment]
I mean the aapt that will ship with upcoming versions of Android.  I don't really know much about aapt2.

I'm hopeful that the fix will be somewhat simple and won't interfere with any future plans to support more 9patch features.

**Comment by mattsarett** [comment]
I think I have the fix here:
https://github.com/mattsarett/Apktool/commit/ae6f8083f1d34326786a254a65e723c0ed37062e

I plan to submit a pull request, but I'd like to wait to make sure it passes all of my tests.

**Comment by iBotPeaches** [comment]
Fixed by - https://github.com/iBotPeaches/Apktool/pull/1182
