### ISSUE TITLE
Performance: usage of String.format in ARSCDecoder.addMissingResSpecs

### ISSUE THREAD

**Issue by dnault** [iBotPeaches/Apktool#1186]
ARSCDecoder.addMissingResSpecs calls String.format several thousand times in a tight loop. Replacing it with string concatenation significantly reduces the amount of time it takes to parse the Android framework (cuts it in half on my machine).

**Comment by iBotPeaches** [comment]
Fixed via - https://github.com/iBotPeaches/Apktool/issues/1187
