### ISSUE TITLE
Question APKTOOL 2.1.0

### ISSUE THREAD

**Issue by Fays** [iBotPeaches/Apktool#1191]
Hello
I wanted to know why with APKTOOL 2.1.0 in dev
When I decompile it generates me more lines on my files (strings.xml)
```
name="APKTOOL_DUMMY_163">false</item>
name="APKTOOL_DUMMY_164">false</item>
 name="APKTOOL_DUMMY_165">false</item>
name="APKTOOL_DUMMY_166">false</item>
name="APKTOOL_DUMMY_167">false</item>
name="APKTOOL_DUMMY_168">false</item>
name="APKTOOL_DUMMY_169">false</item>
name="APKTOOL_DUMMY_16a">false</item>
name="APKTOOL_DUMMY_16b">false</item>
```
log decompil
```
AntiSpam.apk
I: Using Apktool 2.1.0-ea2c82-SNAPSHOT on AntiSpam.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fayz/apktool/framework/1-MI4c.apk
I: Loading resource table from file: /home/fayz/apktool/framework/16-MI4c.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

**Comment by iBotPeaches** [comment]
Do these same dummy attributes happen on `2.0.3`?

**Comment by Fays** [comment]
Yes with apktool-2.0.3 present and not present at apktool-2.0.2

**Comment by iBotPeaches** [comment]
So happens on `2.0.3`+? `2.0.2` is fine? Can I have apk?

**Comment by Fays** [comment]
yes reaches apktool 2.0.3
and did not exist on 2.0.2

info: ( en .odex or deodex idem )

[AntiSpam.zip](https://github.com/iBotPeaches/Apktool/files/170057/AntiSpam.zip)

**Comment by iBotPeaches** [comment]
Could I have the framework files for this? (Deodexed file too if you have it)

**Comment by Fays** [comment]
Here frameworks ( deodexed )
[framework.zip](https://github.com/iBotPeaches/Apktool/files/174827/framework.zip)

**Comment by Fays** [comment]
Hello
Information about this little désagrement

**Comment by iBotPeaches** [comment]
Sorry forgot to tag this. No longer supporting MIUI. Please see #806 as the last MIUI bug here.
