### ISSUE TITLE
I believe that why not encoding only androidmanifest ?

### ISSUE THREAD

**Issue by JaspreetSinghXDA** [iBotPeaches/Apktool#1196]
i guess if it is possible to decode only androidmanifest.xml and encode it back without have to deal with resources.arsc ?

most of the changes are required only needed in androidmanifest.xml

is that feasible ?

**Comment by iBotPeaches** [comment]
To decode resources back to human readable format, we need frameworks and `resources.arsc`, especially with all the obfuscation techniques going on now. So no, not possible.

The best case is a hacked out file raw, but then it will just have IDs in key/value places where we couldn't find the real value name.
