### ISSUE TITLE
Issues on integer values using apktool version 2.0.3

### ISSUE THREAD

**Issue by ayac** [iBotPeaches/Apktool#1199]
I did `apktool d` `apktool b` without changing anything on the package Launcher3.apk (http://www.filedropper.com/launcher3).
Then decompiled the rebuilt package, it shows some differences from the original decompiled one for some integer value in xml files. For istance:
ORIGINAL:
<favorite launcher:className="com.android.contacts.activities.PeopleActivity" launcher:packageName="com.android.contacts" launcher:container="-101" launcher:screen="\ 1" launcher:x="\ 1" launcher:y="\ 0" launcher:spanX="\ 1" launcher:spanY="\ 1" />
REBUILT:
<favorite launcher:className="com.android.contacts.activities.PeopleActivity" launcher:packageName="com.android.contacts" launcher:container="-101" launcher:screen="\ 1" launcher:x="\ 1" launcher:y="\u0015" launcher:spanX="\ 1" launcher:spanY="\ 1" /> 

Notice how launcher:y="\ 0" become launcher:y="\u0015".

Did not happen using version 2.0.2/2.0.1 of apktool.

**Comment by aleksander0m** [comment]
FYI; I've seen the same issue with 2.0.3, but not with the version from git.

**Comment by aleksander0m** [comment]
Looks like f3e21023ac25a09e662aa876cd0a62db34e4e5a4 fixed your issue.

**Comment by iBotPeaches** [comment]
As @aleksander0m said, this has already been fixed via the commit linked.
