### ISSUE TITLE
Problem to run apktool form cmd

### ISSUE THREAD

**Issue by markazie** [iBotPeaches/Apktool#1204]
Hi 

I download apktool version 2.0.3
and install for windows through these steps 
Windows:
  1-  Download Windows wrapper script (Right click, Save Link As apktool.bat)
  2-  Download apktool-2 (find newest here)
  3-  Rename downloaded jar to apktool.jar
  4-  Move both files (apktool.jar & apktool.bat) to your Windows directory (Usually C://Windows)
  5- Try running apktool via command prompt
Now when i want to running apktool via command prompt i have problem
![error](https://cloud.githubusercontent.com/assets/16987161/14013375/ce60abe6-f1c9-11e5-9404-e4e2ca5a6fe7.jpg)
Windows : 7-64Bit
anyone can help?

Thanks & Best Regards

**Comment by iBotPeaches** [comment]
Double check your PATH Environment variables and confirm that the path that `apktool` and `apktool.jar` are located at are in that path.

Unfortunately this bug tracker is for bugs in the product and not support. You may find luck, if my response doesn't help to try XDA or Stackoverflow.

**Comment by markazie** [comment]
@iBotPeaches 
thanks for feedback
mean i should be copy apktool and apktool.jar to the Java Folder?

**Comment by iBotPeaches** [comment]
Please don't email me minutes after responding to a bug report. This isn't one on one support. Get java running so you can execute `java` in CLI. Then add the two apktool files like I mentioned in previous response into PATH.

You will need to do some research here. Don't just ask questions over and over. The internet is full of solutions, read up my man.
