### ISSUE TITLE
the size of apk changes to be bigger after rebuilding

### ISSUE THREAD

**Issue by laimt** [iBotPeaches/Apktool#1206]
### Information
1. **Apktool Version (`apktool -version`)** -2.0.3
2. **Operating System (Mac, Linux, Windows)** -Red Hat 6.4 2.6.32-358.el6.x86_64 
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat
I'm sorry that I got no message about the error. Apktool works perfectly but sometimes the size of apk changes to be bigger after rebuilding. I just added a textfile about 1KB into the apk. the most worst is that it is three times more than the size of source apk.
```
here is my step by using apktool:
java -jar apktool.jar d -f -r -s -q -o "unpackDirPath“ ”apkFilePath“
java -jar apktool.jar b -q -o "repackApkFilePath” unpackDirPath

**Comment by iBotPeaches** [comment]
Bugs like this have to be looked at on a case by case basis. There is usually something different in each case. Apktool reads the compression type of files and re-adds them as such preventing a bloat in apk size.

Its not exactly easy to investigate something when its just "bigger". If you can provide where you added the file, how you built the file, what the file is, etc then maybe we can add a similar file in the unit tests and go from there.

Currently this is simply too broad to take any action on.
