### ISSUE TITLE
FC after repack LG MM apk

### ISSUE THREAD

**Issue by Eduardgur** [iBotPeaches/Apktool#1209]
### Information
1. **Apktool Version (`apktool -version`)** - 2.0.3 / 2.0.2 / 2.1.0_57a8eb-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - From ROM - any apk
### Frameworks

Attached framework-res, lge-res, cameraApp
https://mega.nz/#!G49yVC4S!KFsFg3ZEhihzF9x4hDAVSyNa-xf-QBkH1B9WDb5J7bU

Device: LG F600L MM
I tried to work with 202 and 203 and 2.1.0_57a8eb-SNAPSHOT, after repacking with no changes I get F/C on any apk I tried.
Important to notice there are no errors on any stage.

**Comment by iBotPeaches** [comment]
Do you have the `adb logcat` of the failure during F/C?

Additionally, the APK has a password on it.

**Comment by Eduardgur** [comment]
No password its stock apk that I tried only for the example of this problem

logcat:

`--------- beginning of crash

[ 01-01 14:21:13.376  4474: 4474 E/AndroidRuntime ]

FATAL EXCEPTION: main

Process: com.lge.camera, PID: 4474

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference

	at android.app.LoadedApk.getAssets(LoadedApk.java:587)

	at android.app.LoadedApk.makeApplication(LoadedApk.java:643)

	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4794)

	at android.app.ActivityThread.access$1600(ActivityThread.java:157)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)

	at android.os.Handler.dispatchMessage(Handler.java:102)

	at android.os.Looper.loop(Looper.java:148)

	at android.app.ActivityThread.main(ActivityThread.java:5551)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)





[ 01-01 14:21:13.382  1803: 3298 W/ActivityManager ]

Process com.lge.camera has crashed too many times: killing!



[ 01-01 14:21:13.397  1803: 1842 I/ActivityManager ]

Process com.lge.camera (pid 4474) has died



[ 01-01 14:21:13.398  1803: 1842 W/ActivityManager ]

Re-adding persistent process ProcessRecord{fd24044 4474:com.lge.camera/u0a20}



[ 01-01 14:21:13.411  1803: 1842 I/ActivityManager ]

Start proc 4488:com.lge.camera/u0a20 for restart com.lge.camera`

**Comment by iBotPeaches** [comment]
I meant the download link you gave me for the apk has a password :)

**Comment by Eduardgur** [comment]
Ohh sorry my bad
https://mega.nz/#!G49yVC4S!KFsFg3ZEhihzF9x4hDAVSyNa-xf-QBkH1B9WDb5J7bU

**Comment by Eduardgur** [comment]
Its enough ?

**Comment by iBotPeaches** [comment]
Sorry, I'll be just be honest. I never looked at this and now its 4-5 years later. There are so many new versions. I'm just going to close this.
