### ISSUE TITLE
Remove all .lines from smali?

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1211]
Hello,

I have seen some APKs does not have any .lines in smali. They have removed them all to prevent code comparsion.

How can i remove all .lines from smali?

**Comment by BurgerZ** [comment]
Just read help output from apktool. 
Take a look at **writeDebugInfo** option (**-b**).

**Comment by iBotPeaches** [comment]
http://ibotpeaches.github.io/Apktool/documentation/#decode - Yep as @BurgerZ said.
