### ISSUE TITLE
Implicit Version Qualifiers added - Windows

### ISSUE THREAD

**Issue by pirracas77** [iBotPeaches/Apktool#1212]
Hello:

It seems that it is still adding version qualifiers after build  that there weren't there before

![captura](https://cloud.githubusercontent.com/assets/18216098/14219960/6b3bc646-f85d-11e5-8c65-977e5a48d5f5.PNG)
### Information
1. **Apktool Version (`apktool -version`)** - Apktool v2.1.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM
### Stacktrace/Logcat

```
Include stacktrace here
```
### Steps to Reproduce

apktool if lewa-res.apk
apktool if framework-res.apk
apktool if mediatek-res.apk
apktool d SystemUI SystemUI.apk
... edit some xml and then ..

apktool b SystemUi -o c:\apktool\dist\new.apk
### Frameworks & APK

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/200323/framework-res.zip)
[lewa-res.zip](https://github.com/iBotPeaches/Apktool/files/200327/lewa-res.zip)

[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/200322/SystemUI.zip)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?

Yes, the behaviour is the same, qualifiers are added.
1. If you are trying to install a modified apk, did you resign it?

it is a system apk, I didn't resign it.
1. Are you using the latest apktool version?

yes.

**Comment by iBotPeaches** [comment]
Yeah I'm not duplicating this locally. This makes me think the windows binary has been broken for far too long and just now been reported.

More investigating.

**Comment by iBotPeaches** [comment]
Updating internal aapts to `android-6.0.1_r31` and re-applying my custom patches.

**Comment by iBotPeaches** [comment]
Please see this comment in regards to why this is broken and not fixable - https://github.com/iBotPeaches/Apktool/issues/1458#issuecomment-294473007
