### ISSUE TITLE
FC error after decompile & recompile with MiuisystemUI.apk  

### ISSUE THREAD

**Issue by puppyfox** [iBotPeaches/Apktool#1219]
**Hi Guys!**

I  like to help in this problem:

I use next:
apktool-2.1.0-285da3-SNAPSHOT-BZ with jBART v3h build 20160329.03
Windows 7 x64 ultimate with jdk-8u77-windows-x64.exe
MIUI 7 6.3.25 4.4.4

I want to modified MiuiSystemUI.apk, but i got always  FC.
I tried lot of Apktool and MIUI framewoks from dev and stable rom but i got always same.
Decomplie and compile run without any errors.
I tried more MiuisystemUI.apk decompile, and i got same thing in this case.
In public.xml I found next:
`<public type="drawable" name="APKTOOL_DUMMY_0102" id="0x7f020102" />
    <public type="drawable" name="APKTOOL_DUMMY_0103" id="0x7f020103" />
    <public type="drawable" name="APKTOOL_DUMMY_0104" id="0x7f020104" />
    <public type="drawable" name="APKTOOL_DUMMY_0105" id="0x7f020105" />
    <public type="drawable" name="APKTOOL_DUMMY_0106" id="0x7f020106" />
    <public type="drawable" name="APKTOOL_DUMMY_0107" id="0x7f020107" />
    <public type="drawable" name="APKTOOL_DUMMY_0108" id="0x7f020108" />
    <public type="drawable" name="APKTOOL_DUMMY_0109" id="0x7f020109" />
    <public type="drawable" name="APKTOOL_DUMMY_010b" id="0x7f02010b" />
    <public type="drawable" name="APKTOOL_DUMMY_010c" id="0x7f02010c" />
    <public type="drawable" name="APKTOOL_DUMMY_010d" id="0x7f02010d" />
    <public type="drawable" name="APKTOOL_DUMMY_010e" id="0x7f02010e" />
    <public type="drawable" name="APKTOOL_DUMMY_010f" id="0x7f02010f" />
    <public type="drawable" name="APKTOOL_DUMMY_0110" id="0x7f020110" />
    <public type="drawable" name="APKTOOL_DUMMY_0111" id="0x7f020111" />
    <public type="drawable" name="APKTOOL_DUMMY_0112" id="0x7f020112" />
    <public type="drawable" name="APKTOOL_DUMMY_01a4" id="0x7f0201a4" />
    <public type="drawable" name="APKTOOL_DUMMY_01a7" id="0x7f0201a7" />
    <public type="drawable" name="APKTOOL_DUMMY_01aa" id="0x7f0201aa" />
    <public type="drawable" name="APKTOOL_DUMMY_01ad" id="0x7f0201ad" />`

and apktool ganarate values-mcc9460-mnc9000-xhdpi-v4 folder with dummy drawables.xml.

I read lot of thing but didnt solved my problem. Please help me.
 Thanx!

**Comment by iBotPeaches** [comment]
Sorry. Not supporting or researching MIUI any further. What is in apktool now will stay, future research into a 3rd party OEMs that constantly change AOSP is not worth my time.

#806

**Comment by BurgerZ** [comment]
Just notice (for @iBotPeaches ): apktool-2.1.0-285da3-SNAPSHOT-BZ is just an original apktool, but with changed ALLOWED/IGNORED packages to match latest MIUI changes.
And I think that I've found some issues in source code of the apktool. Testing now.
