### ISSUE TITLE
aapt build in apktool is not support new options

### ISSUE THREAD

**Issue by Bhb2011** [iBotPeaches/Apktool#1232]
### Information
1. **Apktool Version (`apktool -version`)** -
2.1.0
2. **Operating System (Mac, Linux, Windows)** -
Mac, Windows
3. **APK From? (Playstore, ROM, Other)** -
Other

I use apktool 2.1.0. and some apk cannot build by it. 
skip process, as a result. 
I guessing it's reason is new building option. (maybe maybe not)

try next building option is OK:
/Users/WhoAmI/Library/Android/sdk/build-tools/23.0.3/aapt p -S recently_decom/res -M recently_decom/AndroidManifest.xml --no-crunch --generate-dependencies -f -I /Users/WhoAmI/Library/Android/sdk/platforms/android-23/android.jar -F test

but apktool is not OK
W: ERROR: Failure processing PNG image W: /Users/WhoAmI/ttttt/recently_decom/res/values/public.xml:2148: error: Public symbol drawable/abc_ab_bottom_solid_dark_holo declared here is not defined.
W: /Users/WhoAmI/ttttt/recently_decom/res/values/public.xml:2149: error: Public symbol drawable/abc_ab_bottom_solid_light_holo declared here is not defined.
W: /Users/WhoAmI/ttttt/recently_decom/res/values/public.xml:2150: error: Public symbol drawable/abc_ab_bottom_transparent_dark_holo declared here is not defined.
W: /Users/WhoAmI/ttttt/recently_decom/res/values/public.xml:2151: error: Public symbol drawable/abc_ab_bottom_transparent_light_holo declared here is not defined.
... ... ... 

and aapt that bulid-in apktool have no --no-crunch options. 
can you update aapt with --no-crunch options?
thank you

**Comment by iBotPeaches** [comment]
Apktool has 23.0.0 aapt. Updating aapt is quite the task to do as building 3 platform binaries takes some time. I'll probably just update aapt like normal during the release of Android N. However, that is probably 4-5 months away.

I'll see if the codebase differed much between `23.0.0` and `23.0.3` and if my changes can be rebased easily.

**Comment by iBotPeaches** [comment]
Updating internal aapts to `android-6.0.1_r31`. Please follow #1212 for updates, closing this one as duplicate.
