### ISSUE TITLE
settings.apk from meizu latest flyme 5 ROM. 4 resource errors

### ISSUE THREAD

**Issue by mgeranimus** [iBotPeaches/Apktool#1241]
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.0
2. **Operating System (Mac, Linux, Windows)** - Windows 8.1 pro 64 bit
3. **APK From? (Playstore, ROM, Other)** - apk Settings.apk from original MEIZU M2 mini flyme stable 5.1.5.0y ROM, tested from other phones that file and result the same

### Stacktrace/Logcat
C:\Java>apktool if framework-res.apk
I: Framework installed to: C:\Users\Mger\apktool\framework\1.apk

C:\Java>apktool if flyme-res.apk
I: Framework installed to: C:\Users\Mger\apktool\framework\10.apk

C:\Java>apktool if mediatek-res.apk
I: Framework installed to: C:\Users\Mger\apktool\framework\8.apk

C:\Java>apktool d framework-res.apk
I: Using Apktool 2.1.0 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Java>apktool d Settings.apk
I: Using Apktool 2.1.0 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (flyme), pkgId: 10
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Mger\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\Mger\apktool\framework\10.apk
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Java>apktool d SystemUI.apk
I: Using Apktool 2.1.0 on SystemUI.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (flyme), pkgId: 10
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Mger\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\Mger\apktool\framework\10.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Java>apktool b framework-res
I: Using Apktool 2.1.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...

C:\Java>apktool b Settings
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: E/ResourceType(  788): Failed resolving ResTable_map name at 1732 with ident
0x0a0f000b
W: E/ResourceType(  788): Failed resolving ResTable_map name at 1796 with ident
0x0a0f000d
W: W/ResourceType(  788): Attempt to retrieve bag 0x0a010009 which is invalid or
 in a cycle.
W: E/ResourceType(  788): Failed resolving ResTable_map name at 2616 with ident
0x0a0f0017
W: warning: Package not found for resource #0a010009
W: warning: Package not found for resource #0a01000a
W: warning: Package not found for resource #0a010009
W: warning: Package not found for resource #0a010023
I: Building apk file...
I: Copying unknown files/dir...

C:\Java>apktool b SystemUI
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'data_connection_datach_timeout_error_msg' has no default tra
nslation.
W: warning: string 'gemini_4g_3g_disable_warning_case1' has no default translati
on.
W: warning: string 'gemini_4g_3g_disable_warning_case2' has no default translati
on.
I: Building apk file...
I: Copying unknown files/dir...

C:\Java>
Include stacktrace here
``
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

system image is here > https://downloads.meizufans.eu/m2/firmware/stable/5.1.5.0/y/update.zip
top of this topic added all log, as you can see framework-res.apk recompiled good, resigned and moved from twrps file manager to system/framework/ that file works.

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? i tried to install but get bootloop, tried t resign nothing happens better.
3. Are you using the latest apktool version? maybe yes

**Comment by iBotPeaches** [comment]
The mess of warnings and stuff is from aapt. I haven't made progress figuring out if this is just a more restrictive aapt or an actual flaw in apktool. Either way, its being tracked already in #857
