### ISSUE TITLE
Use Android Studio XML decompiler?

### ISSUE THREAD

**Issue by bootstraponline** [iBotPeaches/Apktool#1248]
Google announced XML resource decompilation in Android Studio 2.2. Thoughts on using their code to improve the reliability of apktool?

**Comment by iBotPeaches** [comment]
Last Android release started work on aapt2, which looked powerful, yet never materialized into production. That may change this release.

I inspect new Android releases for any tools that may help Apktool. Something as big as a resource decoder is probably too big to merge in without a v3 version tag. Our resource decoder is hooked in so many places in the codebase a change of that would be quite the rewrite.

**Comment by bootstraponline** [comment]
<img width="438" alt="new_aapt" src="https://cloud.githubusercontent.com/assets/1173057/15403360/a4119b2e-1dc6-11e6-9778-31ee5109f73c.png">

Looks like aapt2 is coming.

**Comment by iBotPeaches** [comment]
I can't imagine the work ahead of me than :o

**Comment by iBotPeaches** [comment]
Played around with this a bit. It seems to have

 - Dex class method reading
 - XML parsed from AXML to human readable
 - List of APK and files showing raw/compressed file size
 - You can read the resources.arsc file for types and get a list of all IDs, names and configurations its from.

Will have to peek at source when it officially drops. 

![apktool2](https://cloud.githubusercontent.com/assets/611784/17437061/7187aeea-5ae9-11e6-8f93-8a904c5ba6b9.png)
![apktool](https://cloud.githubusercontent.com/assets/611784/17437062/7194948e-5ae9-11e6-9c55-839b0b0b4bba.png)

**Comment by iBotPeaches** [comment]
This just uses aapt2 and smali. There is no additional tools that Apktool can benefit from here.
