### ISSUE TITLE
Crash on compiling Settings.apk

### ISSUE THREAD

**Issue by TheShadowRunner** [iBotPeaches/Apktool#1250]
### Information
apktool 2.1.1
Windows XP 32 bit
Settings.apk from ROM (Sony Z1C 5.1.1).
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) Client VM (build 24.79-b02, mixed mode, sharing)

### Stacktrace/Logcat
```
C:\Unzipped\a>java -Xmx512m -jar apktool.jar b Settings
I: Using Apktool 2.1.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_item_bg_pressed.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-ldrtl
-xhdpi-v4\appwidget_item_bg_pressed.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_mid_c_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_mid_l_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_mid_r_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_off_c_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_off_l_holo.9.png
W: libpng error: Not enough image data
Exception in thread "main" W: ERROR: Failure processing PNG image C:\Unzipped\a\
Settings\res\drawable-xhdpi-v4\appwidget_settings_ind_off_r_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_on_c_holo.9.png
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_on_l_holo.9.png
W: libpng error: Not enough image data
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.Br
utException: could not exec (exit code = -1073741819): [C:\DOCUME~1\Alcahest\LOC
ALS~1\Temp\brut_util_Jar_3446688124575471834.tmp, p, --forced-package-id, 127, -
-min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-na
me, 5.1.1-1, -F, C:\DOCUME~1\Alcahest\LOCALS~1\Temp\APKTOOL5190510540205529305.t
mp, -0, arsc, -0, arsc, -I, C:\Documents and Settings\Alcahest\apktool\framework
\1.apk, -I, C:\Documents and Settings\Alcahest\apktool\framework\2.apk, -S, C:\U
nzipped\a\Settings\res, -M, C:\Unzipped\a\Settings\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = -1073741819): [C:\DOCUME~1\Alcahest\LOCALS~1\Temp\brut_util_J
ar_3446688124575471834.tmp, p, --forced-package-id, 127, --min-sdk-version, 22,
--target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-1, -F, C:\DO
CUME~1\Alcahest\LOCALS~1\Temp\APKTOOL5190510540205529305.tmp, -0, arsc, -0, arsc
, -I, C:\Documents and Settings\Alcahest\apktool\framework\1.apk, -I, C:\Documen
ts and Settings\Alcahest\apktool\framework\2.apk, -S, C:\Unzipped\a\Settings\res
, -M, C:\Unzipped\a\Settings\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = -1073741819):
[C:\DOCUME~1\Alcahest\LOCALS~1\Temp\brut_util_Jar_3446688124575471834.tmp, p, --
forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --versi
on-code, 22, --version-name, 5.1.1-1, -F, C:\DOCUME~1\Alcahest\LOCALS~1\Temp\APK
TOOL5190510540205529305.tmp, -0, arsc, -0, arsc, -I, C:\Documents and Settings\A
lcahest\apktool\framework\1.apk, -I, C:\Documents and Settings\Alcahest\apktool\
framework\2.apk, -S, C:\Unzipped\a\Settings\res, -M, C:\Unzipped\a\Settings\Andr
oidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:430)
        ... 6 more
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-xhdpi
-v4\appwidget_settings_ind_on_r_holo.9.png
```
### Steps to Reproduce
java -Xmx512m -jar apktool.jar b Settings

### Frameworks
Apk is from Sony OEM ROM.
Frameworks: framework-res.apk & SemcGenericUxpRes.apk

### APK
Attached is the APK and its 2 frameworks.
http://videoff7.free.fr/apk+frameworks.zip

Here for the apktool.yml : http://videoff7.free.fr/apktool.yml

### Questions to ask before submission
I just decompile it using: java -Xmx512m -jar apktool.jar d -s Settings.apk (thanks for the java heap size trick)
I did NOT modify anything, then recompiled it: java -Xmx512m -jar apktool.jar b Settings
Thanks a lot for your support!

**Comment by TheShadowRunner** [comment]
A bit more on the subject. I was told the issue could be my ROM being odexed, so I ran a patch to deodex it. 
Now Settings.apk filesize increased a little bit (no changes whatsoever to the frameworks, identical MD5), but the issue remains the same.
Here is the log with the new deodexed Settings.apk (I made no changes whatsoever to any file after decompiling):

---
C:\Unzipped\a>java -Xmx512m -jar apktool.jar b Settings
I: Using Apktool 2.1.1
I: Copying Settings classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-ldrtl
-xhdpi-v4\appwidget_item_bg_normal.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = -1073741819)
: [C:\DOCUME~1\Alcahest\LOCALS~1\Temp\brut_util_Jar_8689254320354725281.tmp, p,
--forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --ver
sion-code, 22, --version-name, 5.1.1-1, -F, C:\DOCUME~1\Alcahest\LOCALS~1\Temp\A
PKTOOL4246719049219962226.tmp, -0, arsc, -0, arsc, -I, C:\Documents and Settings
\Alcahest\apktool\framework\1.apk, -I, C:\Documents and Settings\Alcahest\apktoo
l\framework\2.apk, -S, C:\Unzipped\a\Settings\res, -M, C:\Unzipped\a\Settings\An
droidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = -1073741819): [C:\DOCUME~1\Alcahest\LOCALS~1\Temp\brut_util_J
ar_8689254320354725281.tmp, p, --forced-package-id, 127, --min-sdk-version, 22,
--target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-1, -F, C:\DO
CUME~1\Alcahest\LOCALS~1\Temp\APKTOOL4246719049219962226.tmp, -0, arsc, -0, arsc
, -I, C:\Documents and Settings\Alcahest\apktool\framework\1.apk, -I, C:\Documen
ts and Settings\Alcahest\apktool\framework\2.apk, -S, C:\Unzipped\a\Settings\res
, -M, C:\Unzipped\a\Settings\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = -1073741819):
[C:\DOCUME~1\Alcahest\LOCALS~1\Temp\brut_util_Jar_8689254320354725281.tmp, p, --
forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --versi
on-code, 22, --version-name, 5.1.1-1, -F, C:\DOCUME~1\Alcahest\LOCALS~1\Temp\APK
TOOL4246719049219962226.tmp, -0, arsc, -0, arsc, -I, C:\Documents and Settings\A
lcahest\apktool\framework\1.apk, -I, C:\Documents and Settings\Alcahest\apktool\
framework\2.apk, -S, C:\Unzipped\a\Settings\res, -M, C:\Unzipped\a\Settings\Andr
oidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:430)
        ... 6 more

---
At least the "W: Could not find sources" issue from before is gone ^^;
Deodexed Settings.apk can be found here:
http://videoff7.free.fr/deo_Settings.zip
(I didn't upload the frameworks because they didn't change)

Thanks for your support!

**Comment by iBotPeaches** [comment]
```
W: libpng error: Not enough image data
W: ERROR: Failure processing PNG image C:\Unzipped\a\Settings\res\drawable-ldrtl
-xhdpi-v4\appwidget_item_bg_normal.9.png
```

You can see from this that your local version of `libpng` is having trouble handling this image. Since its a 9patch image, its not exactly easy to open that `.9.png` and fix it. Unless you have the tools to edit 9patch images.

```
➜  Bug1249 apktool b Settings
I: Using Apktool 2.1.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'accessibility_service_no_apps_message' has no default translation.
// - warnings about strings
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1249 
```

As you can see, my version of `libpng` is having no trouble with this apk.

**Comment by TheShadowRunner** [comment]
iBotPeaches, thanks for looking into it, but i'm really not sure what I should do to fix the issue on my end?
Where is my libpng even supposed to be installed and could you link me to yours?
Thanks in advance.

**Comment by iBotPeaches** [comment]
According to your original report. You are rocking Windows XP. I'm on Ubuntu 16.04, Windows 10 and El Captain. All I've done on those systems is installed Android SDK and the rest has worked. 

I don't have the time to investigate non-issues especially on an ancient system. Sorry.

**Comment by TheShadowRunner** [comment]
I'm confused, the only thing I have on this PC is your soft, APKTool, I installed nothing else pertaining to Android development (nor does it say on the Apktool how-to-use page that anything else needs to be installed..?).
So the outdated/incompatible libpng on my end has to come from within APKTool itself?

Man I just need to change 2 lines in an XML, it's proving so incredibly complex xD
Like a bottle in the sea, could you possibly do it for me? I've been litteraly 3 days trying to sort this out and have no other PC at hand.

I just would need this edited file [ http://videoff7.free.fr/xperia_connectivity_settings.xml ] replaced at Settings\res\xml\xperia_connectivity_settings.xml , that's it.
That'd be pretty damn sweet at this point..

**Comment by Furniel** [comment]
**TheShadowRunner** 
It's not a support forum, in future it's better to ask help in [apktool thread on xda](http://forum.xda-developers.com/showthread.php?t=1755243&page=420)
Here you are to versions of settings.apk
Settings.apk - modded apk with original signature
Settings_resigned.apk - modded apk resigned with platform key
Not sure which version will work on your device, maybe no one.
https://mega.nz/#F!1oNB0LAK!nzYqmKze4jGkWZ7L19hG_A

**Comment by TheShadowRunner** [comment]
Hi Furniel,
Thank you very much for rebuilding it, you are my savior!
Before I try them (I will try original signature first), can you tell me if
you rebuilt the ODEX version or the DEODEX version? (I linked the 2
variants in my bug report as now I have deodexed my rom).
Please let me know!
Regards,

TSR

**Comment by Furniel** [comment]
@TheShadowRunner 
I rebuilt odexed versions(missed that you deodexed your rom). Uploaded folder with deodexed versions(link is the same).

**Comment by TheShadowRunner** [comment]
Thank you so much, finally it works!
I used the one not resigned (so, used the one with orginal Sony
signing), and it worked straight away, beautiful.
Thank you very much for your help with this, extremely appreciated ;)
Regards,

TSR
