### ISSUE TITLE
compiling using OpenJDK

### ISSUE THREAD

**Issue by anantshri** [iBotPeaches/Apktool#1251]
Looks like compilation fails when we are using openjdk. Error logs can also be seen on the travisci bug log. as its marked as ignore error at this point so i  am assuming author is aware of it. Can you suggest what's the reason why compilation is failing. any plans on getting it to build on openjdk.

**Comment by iBotPeaches** [comment]
Yes compilation with OpenJDK does not work. The build requires the Oracle JDK (7 or 8) currently. I'll update the build information to specify that.
