### ISSUE TITLE
Ressources error recompilation from Samsung SecSettings2 

### ISSUE THREAD

**Issue by edzamber** [iBotPeaches/Apktool#1259]
### Information
1. *_Apktool Version : 2.1.1 *_-
2. *_Operating System : Windows 10 *_ -
3. *_APK From? Deodex official MM Samsung Rom *_ -
### Decompil

Without errors 

```
Recompil 

Recompiling "SecSettings2.apk" With Original Signature,

in work area "_WorkArea1", using "apktool_2.1.1.jar" 



With Tickle My Android 13.0.0. 

(tinyurl.com\ticklemyandroid) 



 ----------------



I: Using Apktool 2.1.1

I: Smaling smali folder into classes.dex...

I: Building resources...

W: E/ResourceType( 7212): Failed resolving ResTable_map name at 3052 with ident 0x02040075

W: warning: string 'device_info_software_summary_wifi' has no default translation.

W: warning: string 'device_info_status_summary_wifi' has no default translation.

W: warning: string 'incorrect_dialog_wipe_1' has no default translation.

W: warning: string 'incorrect_dialog_wipe_2' has no default translation.

W: warning: string 'pdg_summary_title' has no default translation.

W: warning: Package not found for resource #02010052

I: Copy original files...

I: Copy AndroidManifest.xml...

I: Copy META-INF...

I: Building apk file...

I: Copying unknown files/dir...



 ----------------



Recompile Successful!



```
### Steps to Reproduce
1. `apktool`
### Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

https://mega.nz/#!moFURIgA!iFQcDjLt7fTZxLDghsjs-5g3M-5BO29cuPpq7DmMt1U
### APK

If this APK can be freely shared, please upload/attach a link to it.

https://mega.nz/#!uhUHQJqY!GFB6vOlSgfFu0RFAUxJInC8uTOIPfrZvifRQ_nB0tS8
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
   
   Yes, working but if i mod something in res/values Folder  this error is there.
2. If you are trying to install a modified apk, did you resign it? 

No only use original signature as its a system app
1. Are you using the latest apktool version?

Yes

**Comment by edzamber** [comment]
News from xda by @tamirda :

Its seems to be cause by apktool messes a style in styles.xml called TimePicker that refrences to twframework-res and fix twframework-res.apk decompil/compil should fix issue... 


http://forum.xda-developers.com/showthread.php?p=67073998

**Comment by CrazyJ36** [comment]
I'm getting A different error as well during decompile if any insight can be put into it at the moment. SecSetttings2.apk from an s7 port for note 4 n910T. 

C:\Users\crazy\apktool>java -jar apktool.jar if framework-res.apk
I: Framework installed to: C:\Users\crazy\apktool\framework\1.apk

C:\Users\crazy\apktool>java -jar apktool.jar d SecSettings2.apk
I: Using Apktool 2.1.1 on SecSettings2.apk
I: Loading resource table...
I: Decoding Shared Library (touchwiz), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\crazy\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Can't find framework resources for package of id: 2. You must install proper framework files, see project website for more info.

C:\Users\crazy\apktool>

**Comment by edzamber** [comment]
@CrazyJ36

I think you have to use Framework-res.apk and twframework-res.apk from original S7 to be able to decompil without errors as its a ported Rom from S7 to Note 4...

**Comment by iBotPeaches** [comment]
To take a step back. Trying to figure out what you are reporting.

Are the two lines here

```
W: E/ResourceType(25767): Failed resolving ResTable_map name at 3052 with ident 0x02040075
W: warning: Package not found for resource #02010052
```

what you are concerned about? You mentioned there is no error if you simply decode/rebuild, but the error only appears when you modify a value in `/res/values`, so that kinda points at the changes you are making.

Let me know what you changed.

**Comment by tamirda** [comment]
@iBotPeaches the error appears even without edits, only decompile and compile.
The error appears also on CocktailBarService.apk.
I have posted the log and files here:

http://forum.xda-developers.com/showthread.php?p=66610660

I think the error is still twframeworkres, it installs it incorrectly and even can not decompile it.

Thank you

**Comment by edzamber** [comment]
@ibotpeaches, 

@jovy23 have found temporary solution by change some lines in SecSettings2/res/values/styles.xml

http://forum.xda-developers.com/showthread.php?p=67075887

It referes to twframework-res.apk. 

Effectivelly error appears only when mod ressources.arsc (res/values). 

I made changes in strings.xml, arrays.xml. Only add some strings or arrays and error is there. 

If think that's cause by @twframework-res.apk references that are not recoded correctly because twframework-res.apk can't be decompiled or recompiled correctly, even if its installed with Framework-res.apk on Apktool Frameworks (if apktool framework-res.apk and if apktool twframework-res.apk)

**Comment by iBotPeaches** [comment]
Closing as solution found above.
