### ISSUE TITLE
Unable to compile samli files with special charcters

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1261]
Tried to compile an apk which contains special characters like this   and apktool is failing to compile those smali files with error code: error for input '?' invalid text..... could not smali file. using latest apktool_2.1.1.

**Comment by iBotPeaches** [comment]
This is probably related to the charset on your end. Since you didn't follow the issue template, there isn't much we can do here due to lack of information.

**Comment by jack16099** [comment]
I don't understand. I didn't do anything. I just tried to recompile and all smali files contains these types of characters.

**Comment by jack16099** [comment]
And i tried to change encoding to UTF-8 but still the same errors

**Comment by iBotPeaches** [comment]
This isn't a support forum. You can follow the issue guidelines template or try XDA/Stackoverflow.
