### ISSUE TITLE
Copying original certificate--app not installed error

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1271]
### Information
1. **Apktool Version 2.1.1
2. **Operating System- Windows 7
3. **APK From? Playstore, other

Tried to copy original certificate using -c / --copy-original command and apktool successfully builds apk with copied signature inside. But during install, i'm getting "app not installed" error. When i checked logcat, i can see  this error. But when i opened apk with winrar, i can see meta inf folder there.

Package com.xxx.xxx has no certificates at entry classes.dex; ignoring!

Installation error code: -103

Tried this on some apks and this is one of it.
https://play.google.com/store/apps/details?id=com.uc.browser.en&hl=en

**Comment by iBotPeaches** [comment]
`-c / --copy-original` worked early on even up to ICS and even Jellybean. I've noticed that simply using `-c` with Lollipop/Marshmallow still requires a resign.

I'll update docs to reflect this.

**Comment by jack16099** [comment]
Even manually copying meta inf and manifest file via winrar etc will cause "app not installed" error. But recently, i saw an apk which uses signature of a facebook app. I don't know how they did it. It's not a working app. But the apk have a different purpose. I decompiled apk and noticed that even manifest files are edited but somehow it's using same signature of fb. I'm sure it's using same signature because i compared fb's signature and this apk's signature and both are identical. An idea how they did it?  That too, with manifest editing..

**Comment by jack16099** [comment]
is this really a bug? i don't think so. I think it was a security vulnerability in android and google fixed it. because if we can easily retain signature after editing important code, an attacker can modify code and add anything to the app, retain original signature, give it as an update to the real app. But I wonder how the app i mentioned in my previous comment got the same signature

**Comment by iBotPeaches** [comment]
There are tips and tricks to this that I can't pretend to know all about. Simply injection files to the existing APK (with exception of `AndroidManifest.xml`) used to work and retain the original signature. Thats about where my knowledge fails.

I've updated the docs to reflect the usage of this feature.
