### ISSUE TITLE
Cannot decompile APK File using APKTool- Help Needed

### ISSUE THREAD

**Issue by staphoent** [iBotPeaches/Apktool#1273]
### Information
1. **Apktool Version (`apktool -version`)** - APK Tool 2.1.1
2. **Operating System (Mac, Linux, Windows)** - Mac OSX El Capitan
3. **APK From? (Playstore, ROM, Other)** - Yotaphone2 System Apps

Can somebody please help me understand why I cannot decompile the following system APK which I have taken from my android YotaPhone 2. I am having a nightmare with it.

[YD_YotaphoneSDK.apk.zip](https://github.com/iBotPeaches/Apktool/files/314294/YD_YotaphoneSDK.apk.zip)
https://1drv.ms/u/s!As3ob0Phb3hmgRP5ZMwFY2XrjNuM

I was able to perfectly decompile 2 other APK's taken from the same location however when attempting to do so with this one using Mac's terminal the following error occured:
```
Users-Mac-mini:bin user$ ./apktool d YD_yotaphonesdk.apk
I: Using Apktool 2.1.1 on YD_yotaphonesdk.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/user/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01000000
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:513)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
```
I have searched for a solution on the internet and have tried deleting the framework file that came with APKTool but that didnt seem to work.

Any advice and guidance will be very helpfull.

Regards

**Comment by iBotPeaches** [comment]
Generally that error is fixed deleting the framework installed (as its usually out of date). However, you said you already tried that.

I'll take a look when I get free.

**Comment by staphoent** [comment]
thanks, yeah i have tried that, nothing i seem to try is working at the moment. Or if its possible to decompile it yourself and send it to me that would be excellent as I dont need to do it more than once.

**Comment by staphoent** [comment]
everytime i delete it and re-run the process, the 1.apk file returns to the framework folder

**Comment by staphoent** [comment]
is there anyway to delete it and ensure it doesnt return?

**Comment by iBotPeaches** [comment]
> is there anyway to delete it and ensure it doesnt return?

No it requires it.

I need the framework files from this OEM. You pulled the APK from the Yodaphone system, which means you need the Yodaphone framework files.

**Comment by staphoent** [comment]
thanks, I rooted my phone and installed the framework file using the 'if' function and I am getting the same result. How can i be sure that it has definitely installed the new frameork file? I have attached the pulled framework apk here. Regards
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/322318/framework-res.apk.zip)

**Comment by staphoent** [comment]
I have also used one opf the older framework files found on the net to no avail

**Comment by iBotPeaches** [comment]
Not sure. I've seen this error before in #1065 

I don't think that resource ID is valid, as the type pair is `00`.

**Comment by staphoent** [comment]
what is your suggestion for overocming this issue?

**Comment by iBotPeaches** [comment]
Research a solution or wait.

**Comment by nccho** [comment]
After I change file that "C:\Users\WindowAccount\apktool\framework\1.apk", I resolve this issue.

**Comment by Bhagat-Aadmi** [comment]
decompile 'screenlocker.apk' using apktool ... fail
