### ISSUE TITLE
Rebiuild Framework Samsung

### ISSUE THREAD

**Issue by LorDo** [iBotPeaches/Apktool#1278]
### Information
1. **Apktool Version (`2.1.1`)** -
2. **Operating System (Windows 10 Pro 64bit)** -
3. **APK From? (ROM VZW-G900VVRU2DPD1-20160603114654)** -
4. **JRE/JDK Version (jre1.8.0_92/jdk1.8.0_92)** -
### Stacktrace/Logcat

http://pastebin.com/raw/CTV02T0C (too long)
### Steps to Reproduce
1. `apktool`
   The error says that the resource is not found, but if you search on RES folder is 4 matches.

http://prntscr.com/birpil (screenshot)
### Frameworks

http://www.mediafire.com/download/ui0346z12ix8atf/framework-res.apk
http://www.mediafire.com/download/thrjuqbp175zmuv/twframework-res.apk
### APK

http://www.mediafire.com/download/thrjuqbp175zmuv/twframework-res.apk
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? | YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? | YES

**Comment by iBotPeaches** [comment]
I duplicate the problem.

**Comment by iBotPeaches** [comment]
Confirmed still on 2.2.2, I think this is related to #1361

**Comment by iBotPeaches** [comment]
```
➜  Bug1278 apktool if framework-res.apk -t 1278      
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-1278.apk
➜  Bug1278 apktool d twframework-res.apk -t 1278 -f
I: Using Apktool 2.2.2-b60db0-SNAPSHOT on twframework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-1278.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1278 apktool b twframework-res
I: Using Apktool 2.2.2-b60db0-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1278 
```

Confirmed fixed with changes from https://github.com/iBotPeaches/platform_frameworks_base/pull/2

Will be in 2.2.2
