### ISSUE TITLE
Simple Grammar

### ISSUE THREAD

**Issue by XVicarious** [iBotPeaches/Apktool#1280]
### Information
1. **Apktool Version (`2.1.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (N/A)** -

The issue is simple, and that of grammar.  

### Stacktrace/Logcat

```
I: Checking whether sources has changed...
```
"has" should be changed to "have"
This also applies to the resources check.

### Steps to Reproduce
1. `apktool b <path>`

**Comment by iBotPeaches** [comment]
I've known about this, but due to applications using regex to read apktool output, I've decided against breaking those applications due to a grammar change.
