### ISSUE TITLE
UndefinedResObject Exception

### ISSUE THREAD

**Issue by QuaternionsRock** [iBotPeaches/Apktool#1281]
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\User>cd "C:\Users\User\Desktop\apktool"

C:\Users\User\Desktop\apktool>apktool d com.supercell.clashroyale-1.apk
I: Using Apktool 2.1.1 on com.supercell.clashroyale-1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\User\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=background, value=0x0101045c
W: Could not decode attr value, using undecoded value instead: ns=android, name=background, value=0x0101045c
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010479
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:72)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:513)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
C:\Users\User\Desktop\apktool>
```

### Steps to Reproduce
1. Install apktool
2. Move `framework-res.apk` and `SystemUI.apk` to Download folder in MEmu
3. Download Clash Royale, move APK to Download folder in MEmu
4. Move APKs from `C:\Users\User\Downloads\MEmu Download` to `C:\Users\User\Desktop\apktool`
5. Run `apktool if framework-res.apk' and 'apktool if SystemUI.apk'
6. Run `apktool d com.supercell.clashroyale-1.apk`
7. Sit back and relax as it all goes down hill.
8. (NOTE: Decompiling is successful prior to installing frameworks, but outputs a bunch of unreadable CSVs and `AndroidManifest.xml` is messed up. After installing frameworks, the decompilation cuts out early, but produces a perfect `AndroidManifest.xml` and a bunch of properly decompiled PNGs in the `res\` folder.)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) - https://goo.gl/042hu2 (MEmu 2.6.2 (not the latest version) framework-res and SystemUI attached. Not sure why SystemUI is needed but... it can't do any harm, can it?)

### APK
If this APK can be freely shared, please upload/attach a link to it. - It can't :\ https://goo.gl/FCU95y here is the Google Play Store link, though...

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes.
2. If you are trying to install a modified apk, did you resign it? - What? I think I know what you mean, but it isn't modified. So no. Or yes. The right one.
3. Are you using the latest apktool version? - Yes.

**Comment by iBotPeaches** [comment]
Thanks for following the template. Made this easy to investigate. Your problem stems from using an outdated framework file. Since this APK is a regular old PlayStore version, you don't need to mess around with any of the frameworks from your source ROM.

```

C:\Users\Connor\Desktop\bin>java -jar apktool.jar d clash-royale.apk
I: Using Apktool 2.1.1 on clash-royale.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Connor\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\Connor\Desktop\bin>
```

The location of frameworks are changing in 2.2.0, but for 2.1.1 delete the `1.apk` file at `$HOME/apktool/framework/` and then try again.

**Comment by nmr8acme** [comment]
Note that if you installed with brew the file is in a slightly different path, `~/Library/apktool/framework/1.apk`
