### ISSUE TITLE
META-INF folder missing in recompiled apk...

### ISSUE THREAD

**Issue by brainhacker550** [iBotPeaches/Apktool#1282]
Hey, i'm having a problem with apktool.....the original apk im decompiling has a "META-INF" folder in it...but when i decompile and recompile it... the "META-INF" folder goes missing.....What can i do?please help....Thanks in advance.

**Comment by iBotPeaches** [comment]
As per - http://ibotpeaches.github.io/Apktool/documentation/#rebuild

You can use `-c / --copy-original` to retain the `META-INF` and original `AndroidManifest.xml`. Note the warning that this method of retaining original signature doesn't appear to work past API 18.

Either way, this isn't a support forum at all. This is a bug tracker.

**Comment by brainhacker550** [comment]
Thanks that helped...
