### ISSUE TITLE
Some apks dont recompile on linux

### ISSUE THREAD

**Issue by brainhacker550** [iBotPeaches/Apktool#1284]
Hey im having this error letely using apktool on linux...... specific apks dont seem to recompile but they decompile fine....
there is some Exceotions and aapt gets stuck... this is very annoying....whats interesting is all apks work fine on windows including those which didnt recompile on linux...Thanks in advance...

**Comment by iBotPeaches** [comment]
Gotta meet me halfway. There is literally nothing I can do with this report. Don't remove the issue template. Fill it out, provide the apks, stacktraces.

Will reopen if report becomes usable.
