### ISSUE TITLE
Fc after recompile DownloadProviderUi.apk Miui 8

### ISSUE THREAD

**Issue by ale8530** [iBotPeaches/Apktool#1285]
1. Apktool snapshot 2.2.0
2. Linux 64bit
3. ROM Miui 8

Procedure decompile/recompile apk-->http://pastebin.com/30wvQNYk

Logcat error-->http://pastebin.com/0d0jZDhw

I have error only touch "Mostra altri 3"--Screenshot [here](https://db.tt/hajSOlLX)

AndroidManifest.xml original after decompile apk-->http://pastebin.com/KRvj1yiW

Apk and framework [here](https://db.tt/V13iuPZW)

I have installed alls framework.

I do not understand why I have this problem, it not error strings

**Comment by iBotPeaches** [comment]
MIUI is no longer supported. I am sorry.
