### ISSUE TITLE
Decode obfuscated apk using Dexguard

### ISSUE THREAD

**Issue by amjadaziz817** [iBotPeaches/Apktool#1286]
### Information
1. **Apktool Version (2.1.1)** -
2. **Operating System ( Linux)** -
3. **APK From? (Other)** -

### Issue:
In my application its required to display Android application's (apk) information like icon, version, name, description etc. If apk is unobfuscated, all the information is fetched perfectly, but when the apk is obfuscated using Dexguard, my application is failed to fetch information like icon, version etc.
After doing some research I came to know that apktool is unable to recover resources names and values in AndroidManifest.xml and other xml files. 
I am not Android developer and do not know much about Dexguard. I am expecting apktool should recover all resources and configuration files.
Can you please guide me to the right direction ?

### Steps to Reproduce
1. `apktool ` d Obfuscated.apk
2. After successfully decode, the resources are placed under unknown folder with wired/empty names except values.
3. AndroidManifest.xml contains wired values for icons and other configurations etc i.e. APKTOOL_DUMMYVAL_(DEXVAL).

**Comment by iBotPeaches** [comment]
The `DUMMYVAL` resources and more are there to allow decode. There has been 0 success of recovering any human readable name. Android doesn't care about resource names, it cares about resource IDs. Dexguard strips the human readable name, so remaking the APK back to human readable format is nearly impossible.

**Comment by binsalem** [comment]
thanks for your
