### ISSUE TITLE
Moto X 2014 Framework Flags Error

### ISSUE THREAD

**Issue by socraticbliss** [iBotPeaches/Apktool#1290]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Stock ROM

### Stacktrace/Logcat
W: Config flags size > 52. Size = 56. Exceeding bytes: 0x16662214.
W: Invalid config flags detected: string-mcc204-mnc4-ERR0
W: Config flags size > 52. Size = 56. Exceeding bytes: 0x16662214.
W: Invalid config flags detected: array-mcc204-mnc4-ERR1
W: Config flags size > 52. Size = 56. Exceeding bytes: 0x16662214.
W: Invalid config flags detected: bool-mcc204-mnc4-ERR2
I: Framework installed to: C:\Users\heheoops\AppData\Local\apktool\framework\1-2014.apk

### Steps to Reproduce
1. apktool if -t 2014 framework-res.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

**Rename the .zip to .apk**

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/380358/framework-res.zip)

**Comment by iBotPeaches** [comment]
Hmm. Not good at all. It has a 56 byte header for the configurations. This is what I'm expecting for Android Nougat, I just don't know what the 4 extra bytes are yet.

This however is a 2014 framework so either 1) They used new build tools, thus 56 byte header or 2) changed something in resource configurations to cause the difference.

Will investigate after Nougat source drops - #1223

**Comment by socraticbliss** [comment]
So I just retried with 2.2.1-81b22d-SNAPSHOT and the issue seems to have been resolved! 👍 

apktool if -t 2014 framework-res.apk
I: Framework installed to: C:\Users\JJ\AppData\Local\apktool\framework\1-2014.apk

Fantastic work!

**Comment by iBotPeaches** [comment]
The 4 bytes are still unknown however. Glad it worked, but its more of a band aid then permanent solution.
