### ISSUE TITLE
String is Truncated in Strings.xml

### ISSUE THREAD

**Issue by jacobsoo** [iBotPeaches/Apktool#1291]
### Information
1. **Apktool Version 2.0 to 2.1.1** -
2. Windows 7, Windows 10 and Mac OSX
3. This is a malware apk downloaded from Virustotal
### Steps to Reproduce
1. `apktool d <hash>`
   The hash is `f3634c72596056db20d9e14c2eeb7b9dcca24865c5510ebc6c1fdb07adc74674`
### APK

The apk which i'm analysing is `https://virustotal.com/en/file/f3634c72596056db20d9e14c2eeb7b9dcca24865c5510ebc6c1fdb07adc74674/analysis/`

As the file is a malware, i will attached the strings.xml generated by apktool and a screenshot of the resources.asrc file with a hex editor instead.  You can see that base64 encodeds string in the strings.xml is truncated.
[Compressed file.zip](https://github.com/iBotPeaches/Apktool/files/380898/Compressed.file.zip)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
   Yes i've tried it.
2. If you are trying to install a modified apk, did you resign it?
   Nope, just doing static analysis.
3. Are you using the latest apktool version?
   I'm trying out 2.0 to 2.1.1

**Comment by iBotPeaches** [comment]
I seem to require Premium API to download files on VirusTotal, which I don't have. If you can provide the APK please provide the application to me (ibotpeaches (at) gmail (dot) com) that would be great.

I need the `resources.arsc` file to see the string prior to the decoded state to triage this.

**Comment by jacobsoo** [comment]
Hi sir,

i have just send the sample to the email which you have kindly provided.

Please let me know if there is anything that i can help out.

Thanks & Regards
Jacob Soo

**Comment by iBotPeaches** [comment]
Yes I see the problem. It looks like a base64 encoded string of an APK which is strange as hell.

**Comment by jacobsoo** [comment]
Hi sir, 

the earlier file which i gave you is the malware dropper that will base64 decode this string and drop the actual malicious malware. The malware family is called OmniRat. 

Thanks & Regards
Jacob Soo

**Comment by iBotPeaches** [comment]
Sorry for the mega year delay on this. Going through tickets and noticed this is actually a limitation of Android now. Strings longer than 32,767 bytes are not to be used in `strings.xml`.

> The apk file format can only support strings up to 32,767 bytes. AAPT previously wrote out the string to the apk file, but would accidentally truncate the encoded length of string (34952 = 0x8888 and 2184 = 0x888). This lead to the file format being incorrect. We no longer allow strings to be longer than the maximum length and apk can encode.
> In build tools 28.0.0-rc1 and later, we replace strings that are too long with a STRING_TOO_LARGE value and log warnings. We advise developers to save larger strings in other files and read those data files at runtime. We can't simply change the file format because those apks would be invalid on every previous version of the operating system.
https://issuetracker.google.com/issues/73456167#comment2
