### ISSUE TITLE
2.1.1 doesn't compress assets directory when these are pkm files

### ISSUE THREAD

**Issue by zhengtuqiang** [iBotPeaches/Apktool#1298]
http://stackoverflow.com/questions/38690764/android-how-to-compress-assets-directory-using-apktool

**Comment by iBotPeaches** [comment]
I believe this was fixed in 2.2.0 here - https://github.com/iBotPeaches/Apktool/commit/3a982948eadfdc6964d96a441ae0a735df287662

Closing since there is no APK to test against.

**Comment by zhengtuqiang** [comment]
actually not.

**Comment by iBotPeaches** [comment]
Meet me halfway then. APK, Stacktrace or anything that I can go off of. I can't fix what I can't replicate.

**Comment by zhengtuqiang** [comment]
I will provide you a video when I am not so busy. As for apk, sorry, I can't give it to you cause it is our company's product.

**Comment by zhengtuqiang** [comment]
By the way. v2.0.2 can avoid this problem.

**Comment by iBotPeaches** [comment]
Could you at least run `aapt list -v name.apk` and email that to me (ibotpeaches (at) gmail (dot) com). That will allow me to investigate more so than a video.

**Comment by zhengtuqiang** [comment]
I had send an email to you moment ago.

**Comment by iBotPeaches** [comment]
I don't see a problem with any the extensions or unknown files in your dump. None of them conflict with the non-compressed extensions

```
/* these formats are already compressed, or don't compress well */
static const char* kNoCompressExt[] = {
    ".jpg", ".jpeg", ".png", ".gif",
    ".wav", ".mp2", ".mp3", ".ogg", ".aac",
    ".mpg", ".mpeg", ".mid", ".midi", ".smf", ".jet",
    ".rtttl", ".imy", ".xmf", ".mp4", ".m4a",
    ".m4v", ".3gp", ".3gpp", ".3g2", ".3gpp2",
    ".amr", ".awb", ".wma", ".wmv"
};
```

Sorry.

**Comment by zhengtuqiang** [comment]
I need apktool to compress files with extension pkm, and apktool 2.2.0 doesn't do that, but apktool 2.0.2 do that. So, did something involved this changed when 2.0.2 -> 2.0.3? And it influences the version from 2.0.3 to 2.2.0.

**Comment by iBotPeaches** [comment]
Still can't duplicate. Sorry. I even wrote a passing unit-test.

So I guess email me APK or submit PR. There is nothing more to do here.

**Comment by zhengtuqiang** [comment]
I sent an email to you again.
