### ISSUE TITLE
Class not found in recompiled apk

### ISSUE THREAD

**Issue by geopapyrus** [iBotPeaches/Apktool#1299]
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lo/ΐ;

I decompiled an app with

apktool d -f -r  app.apk

and then recompiled with

apktool b app

It seems to be an issue with the accent character.

I'm using 2.2.0

I did not make any changes to the app. Just decompiled and recompiled.

**Comment by iBotPeaches** [comment]
The template for the issue is there to help me help you. This is probably Dexguard and I need to examine these APKs on a case by case basis if you can upload/link it.

**Comment by geopapyrus** [comment]
sorry!

here you go:

[akp.zip](https://github.com/iBotPeaches/Apktool/files/410064/akp.zip)

thanks for the help!

**Comment by iBotPeaches** [comment]
Didn't get any errors replicating your steps. I did get some warnings though

```
08-10 06:32:39.438  6512  6512 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'long com.designfuture.music.IMediaPlaybackService.getTimestamp()' on a null object reference
08-10 06:32:39.438  6512  6512 W System.err: 	at o.ˉ.ι(SourceFile:2575)
08-10 06:32:39.438  6512  6512 W System.err: 	at o.і.onStart(SourceFile:343)
```

and

```
08-10 06:32:39.586  6592  6600 W CursorWrapperInner: Cursor finalized without prior close()
08-10 06:32:39.594  6592  6592 W cr_AwBrowserProcess: Failed to create lock file /data/user/0/com.musixmatch.android.lyrify/app_webview/webview_data.lock
08-10 06:32:39.594  6592  6592 W cr_AwBrowserProcess: java.io.IOException: fcntl failed: EAGAIN (Try again)
08-10 06:32:39.594  6592  6592 W cr_AwBrowserProcess: 	at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
```

Are you on Windows by chance? It sometimes has problems with charsets that might clobber class names and lead to that error.

**Comment by iBotPeaches** [comment]
No response from author in 4 years. Closing.

**Comment by code-with-sohail-king** [comment]
`[git add file](url)`
