### ISSUE TITLE
"screenSize" value for "configChanges" in AndroidManifest.xml lost

### ISSUE THREAD

**Issue by Joebrave** [iBotPeaches/Apktool#13]
<activity android:name="Guide" android:exported="true" android:enabled="true"
		    android:configChanges="orientation|keyboardHidden|navigation|screenSize" android:launchMode="singleTop" android:icon="@drawable/icon">
	    	<intent-filter>
	    		<action android:name="com.***.Guide"></action>
	    		<action android:name="android.intent.action.MAIN"></action>
	    		<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>

After decoded by apktool, the screenSize disapears as bellow:

       <activity android:name="Guide" android:icon="@drawable/icon" android:exported="true" android:enabled="true" android:configChanges="keyboardHidden|navigation|orientation" android:launchMode="singleTop">
            <intent-filter>
                <action android:name="com.***.Guide" />
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by iBotPeaches** [comment]
Closing before merge of GoogleCode issues.
