### ISSUE TITLE
Cannot build gmail , chrome apk files without any changes

### ISSUE THREAD

**Issue by momenimohammad23** [iBotPeaches/Apktool#1302]
Hi 
I can decompile gmail and chrome apk but when i want to build it apktool cannot find some xml file 
apktool b gmail

> I: Using Apktool 2.2.0
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> W: /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/AndroidManifest.xml:50: error: No resource identifier found for attribute 'networkSecurityConfig' in package 'android'
> W: 
> W: /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/AndroidManifest.xml:50: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
> W: 
> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4674134376593598354.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 58383328, --version-name, 6.7.128801648.release, -F, /tmp/APKTOOL3950359885408230238.tmp, -0, arsc, -0, opng, -0, webp, -0, html, -0, arsc, -I, /home/mohammadq/.local/share/apktool/framework/1.apk, -S, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/res, -M, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/AndroidManifest.xml]
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
> 	at brut.androlib.Androlib.buildResources(Androlib.java:407)
> 	at brut.androlib.Androlib.build(Androlib.java:306)
> 	at brut.androlib.Androlib.build(Androlib.java:263)
> 	at brut.apktool.Main.cmdBuild(Main.java:224)
> 	at brut.apktool.Main.main(Main.java:84)
> Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4674134376593598354.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 58383328, --version-name, 6.7.128801648.release, -F, /tmp/APKTOOL3950359885408230238.tmp, -0, arsc, -0, opng, -0, webp, -0, html, -0, arsc, -I, /home/mohammadq/.local/share/apktool/framework/1.apk, -S, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/res, -M, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/AndroidManifest.xml]
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
> 	... 5 more
> Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4674134376593598354.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 58383328, --version-name, 6.7.128801648.release, -F, /tmp/APKTOOL3950359885408230238.tmp, -0, arsc, -0, opng, -0, webp, -0, html, -0, arsc, -I, /home/mohammadq/.local/share/apktool/framework/1.apk, -S, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/res, -M, /home/mohammadq/Documents/Social_apps/Gmail/6.7.128801648/gmail/AndroidManifest.xml]
> 	at brut.util.OS.exec(OS.java:95)
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
> 	... 6 more

**Comment by iBotPeaches** [comment]
This looks like Android Nougat resources. I see `networkSecurityConfig` here - https://developer.android.com/preview/features/security-config.html

and `resizeableActivity` here - https://developer.android.com/preview/features/multi-window.html

These will be fixed once Android N support is added. #1226

**Comment by momenimohammad23** [comment]
@iBotPeaches  Thanks So much :) 
i love apktool <3

**Comment by iBotPeaches** [comment]
This should be fixed with this - https://github.com/iBotPeaches/Apktool/commit/64644a1242d47d8f69fb358f590b4312eeab5a12

Requires framework update - https://ibotpeaches.github.io/Apktool/documentation/#faq
