### ISSUE TITLE
Could not decode 9.png-files (MIUI8)

### ISSUE THREAD

**Issue by Dreamsthinker** [iBotPeaches/Apktool#1305]
### Information
1. **Apktool Version** - apktool_**2.1.0_a19**, apktool_**2.2.0**, apktool_**2.2.0_a**, apktool_**2.2.1**
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** -
ROM, **MIUI8 6.8.18**: miui_HMNote2_6.8.18_ae8823a1ce_5.0
http://en.miui.com/download-274.html#396

### Stacktrace/Logcat
`[*]` Installing framework framework-ext-res.apk
I: Decoding Shared Library (miui), pkgId: 16
I: Framework installed to: bin\framework\17.apk
`[*]` Installing framework framework-res.apk
I: Framework installed to: bin\framework\1.apk
`[*]` Installing framework mediatek-res.apk
I: Framework installed to: bin\framework\8.apk
`[*]` Installing framework miui.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Framework installed to: bin\framework\16.apk
`[*]` Installing framework miuisystem.apk
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Framework installed to: bin\framework\18.apk

`[*]` Decompiling InCallUI.apk
I: Using Apktool 2.2.1_0819 on InCallUI.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: bin\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_reject_call_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/last_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/last_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_dark.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/list_item_overstepped_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/call_card_mask_transparent.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_light.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/single_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_split_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_zoom_big_dark.9.png
I: Loading resource table from file: bin\framework\16.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_incoming.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_reject_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_header.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/blue_background.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_default.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/first_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/single_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_suspect_info_bg.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_call_card_mask_top.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_toggle_dialpad_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_split_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_bg.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_answer_button_n.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_round_corner_frame.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_reject_button_p.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_answer_call_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mask_speak_on.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_toggle_dialpad_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_multi_call_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_reject_button_n.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_zoom_big.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/first_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_answer_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/incoming_answer_voice.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_answer_button_p.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_call_card_mask_bottom.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_end_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_end_call_button_bkgnd_normal.9.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

DONE

**Comment by Dreamsthinker** [comment]
Solved with the latest version of Java - 1.8.0_102-b14 (Java 8u102).

**Comment by Dreamsthinker** [comment]
**MIUI8 6.8.25**

`[*]` Installing framework framework-ext-res.apk
I: Decoding Shared Library (miui), pkgId: 16
I: Framework installed to: bin\framework\17.apk
`[*]` Installing framework framework-res.apk
I: Framework installed to: bin\framework\1.apk
`[*]` Installing framework mediatek-res.apk
I: Framework installed to: bin\framework\8.apk
`[*]` Installing framework miui.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Framework installed to: bin\framework\16.apk
`[*]` Installing framework miuisystem.apk
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Framework installed to: bin\framework\18.apk

`[*]` Decompiling InCallUI.apk
I: Using Apktool 2.2.0 on InCallUI.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: bin\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_zoom_big_dark.9.png
I: Loading resource table from file: bin\framework\16.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_answer_button_n.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/single_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/call_card_mask_transparent.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_dark.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/single_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/incoming_answer_voice.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_toggle_dialpad_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_call_card_mask_bottom.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_split_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_suspect_info_bg.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_incoming.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_reject_call_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_end_call_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_call_card_mask_top.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_multi_call_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mask_speak_on.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_reject_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/last_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_default.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_header.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_answer_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/first_item_bg_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_zoom_big.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_end_call_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_bg.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_reject_button_n.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/last_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/blue_background.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/bg_conference_split_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/call_card_mask_light.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_answer_button_p.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/list_item_overstepped_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_toggle_dialpad_button_bkgnd_pressed.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/first_item_bg_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/fraud_call_reject_button_p.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_answer_call_button_bkgnd_normal.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/jeejen_round_corner_frame.9.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

DONE

**Comment by iBotPeaches** [comment]
MIUI is no longer supported. Sorry.
