### ISSUE TITLE
[Recompile stock apk Failure]De/Recompile lge-res.apk [LGG3 KK 4.4.2 Stock]

### ISSUE THREAD

**Issue by Ry3yr** [iBotPeaches/Apktool#1307]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows 7, x64 bit
3. **APK From? (Playstore, ROM, Other)** - pulled from device via Tickle my Android (/system/framework/lge-res.apk
   (adb pull /system/framework/lge-res.apk
### Stacktrace/Logcat

```
Include stacktrace here
```
### Steps to Reproduce
1. `apktool  b`
### Frameworks

APK from OEM LG Electronics LG G3 Device, FW 4.4.2. Kit Kat Stock
(`.apks` that live in `/system/framework` or `/system/priv-app`)
### APK

If this APK can be freely shared, please upload/attach a link to it.

lge-res.apk
[[[[Link to APK: https://www.sendspace.com/file/ud7a2v]]]
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?: yes, recompiling fails
2. If you are trying to install a modified apk, did you resign it? - n/A
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
```
➜  Bug1307 apktool b lge-res
I: Using Apktool 2.2.1-76eb39-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1682: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_267'.
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1767: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_3a8'.
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1786: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_410'.
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1787: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_411'.
W: 
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1788: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_412'.
W: /home/ibotpeaches/Downloads/Apktool/Bug1307/lge-res/res/values/styles.xml:1789: error: Error: No resource found that matches the given name: attr '@android:attr/APKTOOL_DUMMY_413'.
```

Requires more investigation. Not sure if a an unknown type or duplicate resource name that led to non existing attribute resources to be used.

**Comment by iBotPeaches** [comment]
Sorry - 4years later.

> Sorry, the file you requested is not available.


I don't have the file. I'm sure you might not care either this much later. Closing.
