### ISSUE TITLE
APKTool ignores my changes

### ISSUE THREAD

**Issue by ohaz** [iBotPeaches/Apktool#1322]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

No stacktrace or similar.

So, I'm using apktool to analyze an apk (and deobfuscate it in the process). I used apktool d <file.apk> to disassemble the file, changed some smali files and folders and tried to reassemble it with apktool b -f <folder>. However, it seems to ignore all changes - Packages are missing, packages still have the old name, files still have the old name etc. Am I doing something wrong?

**Comment by iBotPeaches** [comment]
This looks like more of a support request than bug. If apktool wasn't including any changes, this would be a large problem. Both unit tests and real world usage shows this isn't a problem.

Seems isolated to your use.
