### ISSUE TITLE
 error: No resource identifier found for attribute 'resizeableActivity' in package 'android'

### ISSUE THREAD

**Issue by chendz** [iBotPeaches/Apktool#1326]
### Information
1. **Apktool 2.2.0** -
2. **Windows** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

警告: d:\tmp12\u11\AndroidManifest.xml:879: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):

**Comment by pjakubczyk** [comment]
I think this one is related to https://github.com/iBotPeaches/Apktool/pull/1226 since this attribute is from Android Nougat

**Comment by iBotPeaches** [comment]
As said said, `resizableActivity` is from the MultiWindow of Android Nougat so this is a framework problem.
