### ISSUE TITLE
MIUI 8 Framework APKs: No resource found

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#1328]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Pro (x64)
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat
It's too long. Basically a bunch of false "No resource found that matches the given name" errors.

### Steps to Reproduce
Pulled the 4 framework APKs from MIUI 8. "framework-res.apk" decompiles and recompiles perfectly.
However, the other three ("framework-ext-res.apk", "miui-res.apk" and "miuisystem-res.apk") decompile, but when you try to recompile them, there are tons of "No resource found that matches the given name" errors being thrown, even if the resources are actually there. Not sure what to do here...

### Frameworks
https://cloud.mail.ru/public/HzVy/PTcWQ2niF

### APK
The APKs in question are "framework-ext-res.apk", "miui-res.apk" and "miuisystem-res.apk", that are included in the zip above.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No.
2. If you are trying to install a modified apk, did you resign it? Irrelevant.
3. Are you using the latest apktool version? Yes.

**Comment by Fays** [comment]
MIUI is no longer supported

**Comment by iBotPeaches** [comment]
Yes, unfortunately due to the rapid non conforming AOSP changes that MIUI makes, apktool cannot be updated effectively without having 2 versions (miui/regular) or a real hacky code base. For this reason I've decided to no longer support it.
