### ISSUE TITLE
App per decompile -> compile crashes when running, even unchanged

### ISSUE THREAD

**Issue by mmoole** [iBotPeaches/Apktool#1329]
Hi, I wanted to try to change some things in google keyboard, but it seems its not working well with Apktool. When running the recompiled app (even without changes) the setup assistant works well, but as soon as the keyboard should come up, it crashes.
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1-81b22d-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Mac, OSX 10.11.6
3. **APK From? (Playstore, ROM, Other)** - apkmirror
### Stacktrace/Logcat

```
➜  test2 apktool d /z_temp/NeuerOrdner/Custom-google-keyboard/com.google.android.inputmethod.latin_5.1.23.127065177-x86_64-24512320_minAPI17\(x86_64\)\(nodpi\)_apkmirror.com.apk 
I: Using Apktool 2.2.1-81b22d-SNAPSHOT on com.google.android.inputmethod.latin_5.1.23.127065177-x86_64-24512320_minAPI17(x86_64)(nodpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/sammy/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  test2 cd /z_temp/NeuerOrdner/Custom-google-keyboard/test2/com.google.android.inputmethod.latin_5.1.23.127065177-x86_64-24512320_minAPI17\(x86_64\)\(nodpi\)_apkmirror.com 
➜  com.google.android.inputmethod.latin_5.1.23.127065177-x86_64-24512320_minAPI17(x86_64)(nodpi)_apkmirror.com apktool b
I: Using Apktool 2.2.1-81b22d-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```
### Steps to Reproduce
1. `apktool d com.google.android.inputmethod.latin_5.1.23.127065177-x86_64-24512320_minAPI17\(x86_64\)\(nodpi\)_apkmirror.com.apk`
2. `apktool b`
### Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
### APK

If this APK can be freely shared, please upload/attach a link to it:
https://www.apkmirror.com/apk/google-inc/google-keyboard/google-keyboard-5-1-23-127065177-release/google-keyboard-5-1-23-127065177-x86_64-android-apk-download/download/
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes
2. If you are trying to install a modified apk, did you resign it? - yes, with ZipSingner and testkey
3. Are you using the latest apktool version? - i hope yes. Latest 'release' could not compile due similar errors as in bug#1157

**Comment by iBotPeaches** [comment]
Sorry for effectively ignoring this ticket for 4+ years. My gut is you don't care anymore about this issue as 200+ new google keyboards have come out and may not even work on this specific thing again.

I'm striving to control this backlog so this doesn't happen again. However, the downside being that this ticket would require me to install/decode/sign/put-on-phone and more. Though being that I never even triaged it this back then, I guess I should do that now.

```
apktool d%                                                                      ➜  1329 apktool d 1329.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on 1329.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1329 apktool b 1329
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  1329 
```
Unfortunately my OP5 can't install that older version due to ABI incompatibility. Lots of new versions and fixes have come in you'd like to peek again. Closing.
