### ISSUE TITLE
Error "The filename or extension is too long" when rebuild APK

### ISSUE THREAD

**Issue by JustDragon** [iBotPeaches/Apktool#1336]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/legacy-of-discord-furiouswings/com.gtarcade.lod/download?from=details

### Steps to Reproduce
1. Decompile APK.
2. Rebuild APK and you have this error.

**Comment by iBotPeaches** [comment]
This is a known limitation on Windows. A lookup table to store files in a shorter directory name, but store them differently will have to be made which is a rather large change. Additionally a duplicate of #1272

**Comment by JustDragon** [comment]
I just notice that in Apktool 2.1.1 version, I don't have this error.

**Comment by Octolus** [comment]
Any fix? I am running apktool_2.2.3

**Comment by Octolus** [comment]
Caused by: java.io.IOException: Cannot run program "C:\Users\Octolus\AppData\Local\Temp\brut_util_Jar_2835839177993353302.tmp": CreateProcess error=206, Filnavnet eller filtypen er for lang
