### ISSUE TITLE
Problem in packaging apk with apktool 2.1.1

### ISSUE THREAD

**Issue by AshiqKony** [iBotPeaches/Apktool#1337]
### Information
1. apktool 2.1.1
2. Centos 5.10
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

Following error is thrown while packing the apk

./aapt: /lib/libc.so.6: version `GLIBC_2.11' not found (required by ./aapt)
./aapt: /lib/libz.so.1: no version information available (required by ./aapt)

### Steps to Reproduce
1. `apktool `b -f example -o sample.apk

### APK
it is happening for any apk

**Comment by iBotPeaches** [comment]
This is a host platform problem where you are missing some needed binaries/dependencies. You could try installing AOSP and following the guide there as you are missing libc/libz.

Apktool has nothing to do with this, this error is from the native aapt binary.
