### ISSUE TITLE
Wrong recompressing strings, contents &lt;

### ISSUE THREAD

**Issue by AlexStrannik** [iBotPeaches/Apktool#1341]
Apks: play store, viber, gmail, etc

I just decompilied them to make mod, but found &amp&lt; instead of &lt; in plurals.xml - many times, in strings.xml - sometimes. All language files had had this bug.
After recompiling I'd saw tags in toasts instead of seeing bold text.

Please, fix it, ya?

I am using apktool-2.2.1

**Comment by iBotPeaches** [comment]
Sounds like #315

Will investigate.

**Comment by iBotPeaches** [comment]
Closing. 4+ years later, sorry.  Never got a chance and without application, no chance.
