### ISSUE TITLE
getResourceAsStream() always null。

### ISSUE THREAD

**Issue by FynnHan** [iBotPeaches/Apktool#1344]
Why is it error to run on the android studio every time？

error code：
InputStream in = AndrolibResources.class.getResourceAsStream("/brut/androlib/android-framework.jar");
result is "in = null"

InputStream in = ApktoolProperties.class.getResourceAsStream("/properties/apktool.properties");
result is "in = null"

**Comment by iBotPeaches** [comment]
Not sure what you are trying to report here.

**Comment by FynnHan** [comment]
The reason is that my path is wrong.

**Comment by 2191265529** [comment]
I have same problem, have you resolved the problem?
