### ISSUE TITLE
Samsung twframework_res error

### ISSUE THREAD

**Issue by rakeshraimca** [iBotPeaches/Apktool#1347]
Hello,

I am getting issue while decopiling and recompiling again twframework_res file.

I am using latedt 2.2 apktool for marshmallow framework

Here is my error file
https://drive.google.com/file/d/0B5yEFQJPxvK6eFJqYmF5NmdBZm8/view?usp=drivesdk

I didnt evn change anything  and when recompiling ..it shows many class id errors...so  might be issue with apktool

Can u plz check on this.

**Comment by iBotPeaches** [comment]
There are like 3 other Samsung bug reports like this - #1258 and #1259 and #1278
