### ISSUE TITLE
Build in batch file without exit finish

### ISSUE THREAD

**Issue by Claris2000** [iBotPeaches/Apktool#1363]
Hello,

I am trying to building with Apktool in .bat file like this:

Apktool b path

Everything works fine, but at the end build the cmd closed automatically.

I would like to be able to add more lines and run them after compiling and before closing the cmd.

it's possible? Thank you.

**Comment by iBotPeaches** [comment]
The Apktool CLI returns 0 if completion succeeds like any other CLI application. If you are having it close automatically adjust your scripts to keep it active through many of the tricks to do so.

This has nothing to do with apktool and I don't want to edit the helper files to enforce an artificial pause so closing this.
