### ISSUE TITLE
Decode and Build 2 times in a row fails on smali_assets

### ISSUE THREAD

**Issue by gilhartman** [iBotPeaches/Apktool#1364]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Public site

### Stacktrace/Logcat
```
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
5/smali_assets/dex/adcolony/com/immersion/content/EndpointWarp.smali[10,9] Class Lcom/immersion/content/EndpointWarp; has already been interned
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: dex/adcolony/com/immersion/content/EndpointWarp.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:77)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:405)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:351)
	at brut.androlib.Androlib.build(Androlib.java:293)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
```
### Steps to Reproduce
1. `apktool d com.mobzapp.screenstream.trial_2016-09-01.apk -o 1`
2. `apktool b 1 -o 1.apk`
3. `apktool d 1.apk -o 2`
4. `apktool b 2 -o 2.apk`

### Frameworks
Nexus 5X Android 7.0

### APK
http://www.apkmonk.com/download-app/com.mobzapp.screenstream.trial/2_com.mobzapp.screenstream.trial_2016-09-01.apk/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Not relevant
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Confirmed. Nice find. Subfolders for dex files are being properly disassembled, but improperly built so then when they are disassembled the 2nd time they are in a wrong format and thus can't be re-built.

**Comment by tracer8** [comment]
This is not resolve yet, i'm still face this when use Facebook Audience Network SDK.

**Comment by iBotPeaches** [comment]
Sorry for ignoring this for 4+ years. I don't have the application and smali/baksmali v2.4.0 will be in Apktool v2.5.0. If that doesn't work, we should probably upstream it to that project.

Closing.

**Comment by L1ghtingBolt** [comment]
Still not fixed
