### ISSUE TITLE
Error when building apktool on  CentOS-7

### ISSUE THREAD

**Issue by rezamnejad** [iBotPeaches/Apktool#1374]
### Information
1. **Apktool Version (`apktool -version`)** - bash: apktool: command not found...
2. **Operating System (Mac, Linux, Windows)** - CentOS-7-x86_64-Everything-1511.iso
3. **APK From? (Playstore, ROM, Other)** - https://github.com/sonyxperiadev/ApkAnalyser

### Stacktrace/Logcat

```
Include stacktrace here
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] apktool ............................................ SUCCESS [ 10.630 s]
[INFO] apktool library .................................... FAILURE [  3.002 s]
[INFO] apktool cli ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.632 s
[INFO] Finished at: 2016-12-05T15:17:59-05:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project apktool-lib: Could not resolve dependencies for project brut.apktool:apktool-lib:jar:1.4.4-SNAPSHOT: The following artifacts could not be resolved: brut.j:dir:jar:1.0, brut.j:util:jar:1.0, brut.j:common:jar:1.0: Could not find artifact brut.j:dir:jar:1.0 in android-apktool.googlecode.com (http://android-apktool.googlecode.com/svn/m2-releases) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apktool-lib

###Prerequisites:
1. Get the latest code 
git clone git://github.com/sonyxperiadev/ApkAnalyser.git

2. Build smali project
cd smali
mvn install

### Steps to Reproduce
1. cd ../apktool
2. mvn install

### Additional info:
mvn -version
Apache Maven 3.3.9

All I have done so far is uninstall the JDK 1.8 that comes with the CentOS-7-x86_64-Everything-1511.iso and installed jdk-7u79-linux-x64.tar.

Please let me know where I can download the brut.j:dir:jar:1.0, brut.j:util:jar:1.0, brut.j:common:jar:1.0: artifacts.

Thanks in advance!

**Comment by iBotPeaches** [comment]
Wow. Thats an old apktool. Almost 5 years old. We left the maven build system a long time ago in favor of gradle. The most up to date repo for building you are commenting on. Please use the latest apktool here.

Not going to debug a 5 year old source base, sorry about that. Closing.
