### ISSUE TITLE
Could not find the main class: 

### ISSUE THREAD

**Issue by parulkhanna** [iBotPeaches/Apktool#1375]
### Information
1. **Apktool Version (`apktool -version`)** - 2.0
2. **Operating System (Mac, Linux, Windows)** - Ubuntu
3. **APK From? (Playstore, ROM, Other)** - apkmirror

Hi,

###I am using following script to initiate apktool decompilation. Whenever I try to decompile a specific apk, I get an error. Please have a look at the script and then the errors I am getting 

`
#!/bin/bash

DARE=$(dirname $0)/dare-1.1.0-linux/dare

if [ "$(uname)" == "Darwin" ]; then
    DARE=$(dirname $0)/dare-1.1.0-macos/dare
fi

APKTOOL=$(dirname $0)/apktool-2.0.0rc4/apktool

preprocessAPK() {
    # Expand the APK file path (only works in Linux)
    if [ "$(uname)" == "Darwin" ]; then
        apkFile=$(greadlink -f $1)
    else
        apkFile=$(readlink -f $1)
    fi

    apkDir=$(dirname "$apkFile")

    # Extract app name from APK file
    appName=$(basename "$apkFile")
    appName="${appName%.*}"

    apkDir=${apkDir}/${appName}

    # Create output directory and place APK file in there
    mkdir ${apkDir}.dir
    mv $apkFile ${apkDir}.dir/${appName}.apk
    mv ${apkDir}.dir ${apkDir}

    apkFile=${apkDir}/${appName}.apk
    extractedApkDir=${apkDir}/apk
    dareDir=${apkDir}/dare

    # Use apktool to expand the APK file and copy the manifest
    ${APKTOOL} d -o ${extractedApkDir} -s ${apkFile}
    #cp ${extractedApkDir}/AndroidManifest.xml ${apkDir}/AndroidManifest.xml

    # Use dare to convert Dex bytecode to Java bytecode and place class files into jar
    ${DARE} -d ${dareDir} ${apkFile}
    jar cf ${extractedApkDir}/classes.jar -C ${dareDir}/retargeted/${appName} .
    rm -r ${dareDir}
}

preprocessAPKDir() {
    # Expand the APK directory path (only works in Linux)
    if [ "$(uname)" == "Darwin" ]; then
        apkFile=$(greadlink -f $1)
    else
        apkDir=$(readlink -f $1)
    fi

    # Extract app name from APK directory
    appName=$(basename "$apkDir")

    extractedApkDir=${apkDir}/apk

    if [[ ! -e "${extractedApkDir}" ]] || [[ ! -e "${extractedApkDir}/classes.jar" ]]; then
        apkFile=${apkDir}/${appName}.apk
        dareDir=${apkDir}/dare

        # Use apktool to expand the APK file and copy the manifest
        ${APKTOOL} d -f -o ${extractedApkDir} -s ${apkFile}
        #cp ${extractedApkDir}/AndroidManifest.xml ${apkDir}/AndroidManifest.xml

        # Use dare to convert Dex bytecode to Java bytecode and place class files into jar
        ${DARE} -d ${dareDir} ${apkFile}
        jar cf ${extractedApkDir}/classes.jar -C ${dareDir}/retargeted/${appName} .
        rm -r ${dareDir}
    fi
}
`

### Stacktrace/Logcat (ERRORS)

@-desktop:~/Documents/IntelliDroid/AppAnalysis$ ./preprocess/PreprocessAPK.sh ./dropbox.apk mv: cannot stat ‘/home//Documents/IntelliDroid/AppAnalysis/dropbox.apk’: No such file or directory Exception in thread "main" java.lang.UnsupportedClassVersionError: brut/apktool/Main : Unsupported major.minor version 51.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631) at java.lang.ClassLoader.defineClass(ClassLoader.java:615) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) at java.net.URLClassLoader.access$000(URLClassLoader.java:58) at java.net.URLClassLoader$1.run(URLClassLoader.java:197) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:190) at java.lang.ClassLoader.loadClass(ClassLoader.java:306) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) at java.lang.ClassLoader.loadClass(ClassLoader.java:247) Could not find the main class: brut.apktool.Main. Program will exit. Processing class #0: Landroid/support/v4/app/ActionBarDrawerToggle$1; Processing class #1: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;

End of the output
Processing class #4398: Ldbxyzptlk/db240510/z/e; Processing class #4399: Ldbxyzptlk/db240510/z/g; Assembling classes java.io.FileNotFoundException: /home/Documents/IntelliDroid/AppAnalysis/dropbox/apk/classes.jar (No such file or directory) at java.io.FileOutputStream.open(Native Method) at java.io.FileOutputStream.<init>(FileOutputStream.java:194) at java.io.FileOutputStream.<init>(FileOutputStream.java:84) at sun.tools.jar.Main.run(Main.java:167) at sun.tools.jar.Main.main(Main.java:1147)
```


### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
YES
2. If you are trying to install a modified apk, did you resign it?
NA
3. Are you using the latest apktool version?
NO ( Because I am decompilings apps for older Android version)

**Comment by iBotPeaches** [comment]
```
Unsupported major.minor version 51.0 at java.lang.ClassLoader.defineClass1(Native Method) at 
```

If you run `java -version`, what do you get?

Per the [install](https://ibotpeaches.github.io/Apktool/install/) docs you need at least 1.7.

**Comment by iBotPeaches** [comment]
Closing due to support question. Apktool requires at least Java 7.
