### ISSUE TITLE
special characters in decoded manifest (possible continuation to your patch on 1389?)

### ISSUE THREAD

**Issue by fryjustinc** [iBotPeaches/Apktool#1393]
Hi there, 

decoding the latest facebook apk stable release, and there seems to be an issue (or it's possible I'm not familiar enough with the code). The apk will decode successfully with a simple apktool d facebook.apk command, and it can subsequently build that with a debug flag. However, The process is not being shown as debuggable in developer options or in the android studio debug manager( opened decode folder as project with smali set as source root). I then tried to edit the manifest manually to enable it as debuggable, only to see that the manifest is totally filled with special characters and nothing that resembles proper xml. Here are a couple samples:

`  xz   ��           l          "   <   V   t   �   �   �   �   �     *  D  \  �  �  �  �  �  �  �      2  F  f  ~  �  �  �    (  P  h  ~  �  �  �         4  H  p  �  �  �  �    "  <  H  Z  �  �  �  �  0  D  b  �  �  �  �  �  �  (  l  �  �  6  �  �  	  @	  x	  �	  
  V
  �
  �
  F  �  �     p  �  

  &
  X
  �
  �
  V  �  �  .  d  �  �  2  v  �  �  8  �  �  &  �  �  �  N  d  �  �  N  �  �  �  �  0  @  �  �  �    p  �  �  �  X  �  .  �    l  �     �  �  4  ~  �  �  J  �    l  �  (  �  4  H  �  �  (   �   0!  �!   "  >"  N"  �"  #  �#   $  �$  (%  �%  <&  �&  ^'  (  Z(  �(  P)  *  �*  ^+  �+  X,  �,  0-  �-  .  �.  �.  z/  �/  @0  �0  1  v1  �1  �1  ,2  �2  03  �3  4  �4  5  �5  �5  ~6  �6  L7  �7  ,8  �8  �8  h9  |9  �9  P:  �:  *;  �;   <  �<  2  =  �=  �=  2>  �>  �>  2?  z?  �?  �?  �?  @   @  @@  R@  ^@  l@  ~@  �@  �@  �@  2A  RA  vA  �A  �A  0B  ~B  �B  C  TC  fC  vC  �C  D  tD  �D  E  E  ^E  pE  �E  �E  xF  �F  G  <G  �G  �G  fH  �H  6I  �I  J  �J  K  �K  FL  �L  HM  �M  *N  �N  O  RO  �O  �P   Q  RQ  �Q  R  �R  �R  \S  �S  T  zT  �T  2U  �U  �U  RV  �V  :W  �W   X  rX  �X  4Y  �Y  "Z  �Z  �Z  V[  �[  \  r\  �\  0]  �]  �]  t^  �^  J_  �_  `  h`  �`  a  Ha  �a  &b  �b  �b  fc  d  zd  �d  $e  ~e  f  �f  g  ng  �g  h  �h  i  Pi  �i  2j  �j  k  �k  �k  rl  �l  dm  �m  Hn  �n  >o  �o  �o  ,p  �p  �p  Rq  �q  <r  �r  &s  �s  t  �t  �t  \u  �`

'i n s t a l l L o c a t i o n    v e r s i o n C o d e    v e r s i o n N a m e   
 s c r e e n D e n s i t y   
 s c r e e n S i z e   
 m i n S d k V e r s i o n    t a r g e t S d k V e r s i o n    n a m e    r e q u i r e d    p r o t e c t i o n L e v e l    g l E s V e r s i o n    a l l o w B a c k u p   
 d e b u g g a b l e    h a r d w a r e A c c e l e r a t e d    i c o n    l a b e l   	 l a r g e H e a p    s u p p o r t s R t l    t h e m e   
 v m S a f e M o d e    v a l u e    r e s o u r c e    a u t h o r i t i e s    e x p o r t e d    r e a d P e r m i s s i o n   
 p e r m i s s i o n    g r a n t U r i P e r m i s s i o n s   
 c o n f i g C h a n g e s    p r o c e s s    w i n d o w S o f t I n p u t M o d e    s c r e e n O r i e n t a t i o n    e x c l u d e F r o m R e c e n t s'

as you can see, something is clearly wrong. Any thoughts?

**Comment by iBotPeaches** [comment]
So two things.

1. To enable the debug flag (debuggable), during build use the parameter `-d / --debug`. This inserts the `debuggable="true"` to the manifest.

2. I don't think you are editing the right file. The decoded `AndroidManifest.xml` lives in the root of the decoded application folder. There is also a `build` and `original` folders that will have the AXML equivalent or compiled `AndroidManifest.xml` file, so those would present as unreadable like above.

Merry Christmas if you celebrate it, I'm going to close this because I believe this is just a support / misunderstanding and nothing Apktool is doing wrong.
