### ISSUE TITLE
mistake in script

### ISSUE THREAD

**Issue by digininja** [iBotPeaches/Apktool#1397]
### Information
1. **Apktool Version (`apktool -version`)** - latest from git
2. **Operating System (Mac, Linux, Windows)** - linux

In the file 

/scripts/linux/apktool

line 52 talks about uncommenting the next line for more memory but the next line is not commented.

**Comment by iBotPeaches** [comment]
We already do this. Line 56 - https://github.com/iBotPeaches/Apktool/blob/master/scripts/linux/apktool#L56

It sets the memory allocation pool to 512M

**Comment by digininja** [comment]
The point was that the comment says "uncomment the line below" but it isn't
commented out.
