### ISSUE TITLE
libpng problem in apk

### ISSUE THREAD

**Issue by waloooer** [iBotPeaches/Apktool#1398]
after recompiling everything was cool the apk worked but when i did upload it in google store they sent me an email explaining that the application has a vulnerability issue and that i need to update libpng i dont know how if you could help me please ,thanks a lot for all dude:)

**Comment by iBotPeaches** [comment]
https://support.google.com/faqs/answer/7011127?hl=en

Apktool won't automatically patch outdated binaries.
