### ISSUE TITLE
php  exec  apktool  without apk package out

### ISSUE THREAD

**Issue by moto2002** [iBotPeaches/Apktool#1403]
### Information
1. **Apktool Version (`2.1`)** -
2. **Operating System  windows
3. **my apk

i install a wamp server on window ,and use php script to call apktool to recompile my apk ,but the execution only generate build/class.dex ,without apk file ,and no errors , any idea please?

thanks very much

**Comment by iBotPeaches** [comment]
Not really enough details to go on here, sorry. You can try executing with `-v` to log more information.
