### ISSUE TITLE
Unable to decompile SystemWebView.apk; I (think) am using wrong resource pack but not sure which one to use?

### ISSUE THREAD

**Issue by wrightpt** [iBotPeaches/Apktool#1408]
### Information
1. **Apktool Version (`apktool -version`)** -  Apktool Version 2.2.1

2. **Operating System (Mac, Linux, Windows)** - Linux 

3. **APK From? (Playstore, ROM, Other)** -  Other - Chromium build

### Stacktrace/Logcat

```
c@c:/usr/local/bin$ sudo apktool d SystemWebView.apk
I: Using Apktool 2.2.1 on SystemWebView.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool `
 Samsung S5: framework-res.apk
Downloaded from this link (also available at link below): https://www.androidfilehost.com/?fid=24052804347769438

sudo apktool if framework-res.apk
I: Framework installed to: /root/.local/share/apktool/framework/1.apk

sudo apktool d SystemWebView.apk

Tried deleting 1.apk, with same result

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://drive.google.com/open?id=0B6ddrp5rzEzbOWVfYVk4dWlSbVU

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Not modified
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Seems to be resolved with the upcoming 2.2.2 release. Hold tight.

```
➜  Bug1408 apktool d framework-res.apk 
I: Using Apktool 2.2.2-b6127d-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1408 
```

Release is set for this week.

**Comment by iBotPeaches** [comment]
Wrong stacktrace attached. My bad.

```
➜  Bug1408 apktool d SystemWebView.apk 
I: Using Apktool 2.2.2-b6127d-SNAPSHOT on SystemWebView.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1408 
```

**Comment by wrightpt** [comment]
no worries. I got around it. No longer need the apk. Thank you though
