### ISSUE TITLE
Windows - apktool build fails due to UTF8 filename

### ISSUE THREAD

**Issue by bovirus** [iBotPeaches/Apktool#1414]
With the latets two updates I cannot compiled the apktool under Windows (non changes are amde in Windows) bwcause report an error during tests.

tested with java JDK 1.7.0.80 and 1.8.0.122.

compiling the sources with the command

build fatJar proguard

I got this error. 
```
brut.androlib.BuildAndDecodeTest > unicodeAssetTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at brut.androlib.BuildAndDecodeTest.compareBinaryFolder(BuildAndDecodeTest.java:435)
        at brut.androlib.BuildAndDecodeTest.compareAssetsFolder(BuildAndDecodeTest.java:447)
        at brut.androlib.BuildAndDecodeTest.unicodeAssetTest(BuildAndDecodeTest.java:382)

80 tests completed, 1 failed
:brut.apktool:apktool-lib:test FAILED
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
> There were failing tests. See the report at: file:///D:/GIT/Apktool/brut.apktool/apktool-lib/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Before the last two apktool updates it worked fine.

**Comment by BurgerZ** [comment]
What is in the file D:/GIT/Apktool/brut.apktool/apktool-lib/build/reports/tests/test/index.html ?

**Comment by bovirus** [comment]
@BurgerZ

Test Summary 75

tests 1

failures 0

ignored
   
2m9.39s
duration
   
98%
successful

  * {Failed tests}  
  * {Packages}  
  * {Classes}  
Failed tests
  * {BuildAndDecodeTest}. {unicodeAssetTest}  
Packages
Package   Tests   Failures   Ignored   Duration   Success rate    
{brut.androlib}    75   1   0   2m9.39s   98%   
Classes
Class   Tests   Failures   Ignored   Duration   Success rate    
{brut.androlib.AndResGuardTest}   1   0   0   29.835s   100%  
{brut.androlib.BuildAndDecodeJarTest}   1   0   0   0s   100%  
{brut.androlib.BuildAndDecodeTest}   61   1   0   0.137s   98%  
{brut.androlib.DebugTagRetainedTest}   2   0   0   0.032s   100%  
{brut.androlib.DoubleExtensionUnknownFileTest}   1   0   0   8.477s   100%  
{brut.androlib.LargeIntsInManifestTest}   1   0   0   37.628s   100%  
{brut.androlib.MissingVersionManifestTest}   1   0   0   8.894s   100%  
{brut.androlib.ProviderAttributeTest}   1   0   0   17.508s   100%  
{brut.androlib.ReferenceVersionCodeTest}   1   0   0   9.086s   100%  
{brut.androlib.SharedLibraryTest}   3   0   0   17.795s   100%  
{brut.androlib.UnknownCompressionTest}   2   0   0   0s   100%   
Wrap lines   
Generated by {Gradle 2.3} at 8-gen-2017 21.01.08

It happens only under Windows.
Under Linux (running with vMWare) compilation is OK (no error during tests)

**Comment by jack16099** [comment]
same issue here

**Comment by iBotPeaches** [comment]
```
➜  unicode-txt git:(master) ls
∂-unicode.txt
➜  unicode-txt git:(master) python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir('.')
['\xe2\x88\x82-unicode.txt']
>>> 
```

It's a valid UTF8 file. Windows must be choking on it.

**Comment by bovirus** [comment]
@iBotPeaches

Thanks for tehr eport.
What could I do to fix the problem in Windows?

**Comment by edzamber** [comment]
I successfully compil under Cygwin but with this command :

. /gradlew release fatjar 

Try on windows with git app with :

. /gradlew.bat release fatjar

**Comment by bovirus** [comment]
@edzamber 

In this way you bypass the tests. But is not correct.
Under Linux the compilation works fine with tests.

**Comment by edzamber** [comment]
Yes test are bypassed but Apktool working perfectly. I have test on my SystemUI, no issue with decompil/recompil.

**Comment by bovirus** [comment]
@edzamber 
Thanks for teh confirm.

I wrote it befroe because the author answer in the forum that the test are necessary.

Now i'm compiling it under Linux.
No errors with tests.

**Comment by edzamber** [comment]
For test on windows or Cygwin it doesn't working. 
Fail to pass test 
Working only with release command. 

I use JDK 8u112

**Comment by bovirus** [comment]
@edzamber 
It's the same for me.
I'm using JDK 1.8.121 (in Windows and Linux)

In Windows fail with build gradle option (fail 1 test) but work with release gradle option (bypass test)

In Linux work with build gradle option (pass all tests).

**Comment by iBotPeaches** [comment]
The release command is for me only. That creates non-snapshot builds, so they look official so please don't go using `release` and then releasing those binaries into the public.

Please look into the tests and how Java and Windows handles UTF8 characters. Messing with how gradle executes is not the problem.

**Comment by edzamber** [comment]
@Bovirus,

Yes same problem with jdk 8u121...

@iBotPeaches,

No problem, i use only for me. I know how release option compil, that's why i'll never share it in public. 

I tried to find what is the problem with Windows and Cygwin but i don't see how to solve this. 

It worked one time for build december commits but with news commits it don't working anymore.

**Comment by iBotPeaches** [comment]
It broke because of this commit - https://github.com/iBotPeaches/Apktool/commit/b6127d2a31e2149ab30e10cd4c68de68846e32a0

I'm not reverting it though, because it tests whether we properly insert unicode filenames into the rebuild application.

There are a ton of articles about Java, Windows, Cygwin and UTF8. Building on Windows will just be on a hiatus for a bit till someone or myself finds a patch.

**Comment by bovirus** [comment]
@iBotPeaches

Please take care that Windows don't allow to use UTF8 at OS level (you can do it for single app like Notepad++, etc - but not at OS level).
The commit that you did is regarding MacOS file and MacOS and Linux handle UTF8 natively.

I propose you to add to the source a if/check condition for this test (just this test fail and is the UTF8 test) to bypass it if the OS running is Windows.
If you have MacOS/Linux as OS the develop make all tests
If you have Windows as OS the compilation make all tests except 1 (UTF8 that failed on Windows)

If different for Windows users bypass the tests at all (no tests) then to make all tests except UTF8 (just it failed - not the others).

Thanks.
