### ISSUE TITLE
App FC in loop MiuiHome.apk

### ISSUE THREAD

**Issue by Fays** [iBotPeaches/Apktool#1415]
### Information
1. **Apktool Version (`apktool -2.2.2 `)** -
2. **Operating System (Linux Mint 18.1)** -
3. **APK From? (MIUI 8)** -

Bug Present version 2.2.2-dd4a207
Not present version 2.2.2-e3c6db

### Stacktrace/Logcat
https://mega.nz/#!c4pCkA4T!vKfCa7dCsOnuy0w5gRUGQwzYWOMxbMdLSSbjckiGfWY

Framework pkgId: 27 : 
https://mega.nz/#!cg4w3QyY!EQmty2tcboo5Tuc-gAyyctP_nIE71vbJMs7MYcewf2A
Application MiuiHome FC : https://mega.nz/#!EspDERTb!PtWtkurKIVhfzL7grEzh96hzD2Q7rF0tBeuCLcbzev8

Patch apktool.yml for MiuiHome pkgId: 27 

**Decompilation**
```
I: Using Apktool 2.2.2-dd4a207-SNAPSHOT on MiuiHome.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (com.miui.home.launcher.assistant), pkgId: 27
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fayz/.local/share/apktool/framework/1-HMPro.apk
I: Loading resource table from file: /home/fayz/.local/share/apktool/framework/16-HMPro.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

```
**Recompilation**
```
I: Using Apktool 2.2.2-dd4a207-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
```

**Comment by iBotPeaches** [comment]
Merging into MIUI bug report - #1178
