### ISSUE TITLE
MOTO: Additional configuration qualifiers.

### ISSUE THREAD

**Issue by kaneawk** [iBotPeaches/Apktool#1420]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.3-6cc251-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** -Windows 10
3. **APK From? (Playstore, ROM, Other)** - Moto Z  android 7.0 framework-res.apk (CN Retail Stock firmware)

### Stacktrace/Logcat

```I: Using Apktool 2.2.3-6cc251-SNAPSHOT on framework-res.apk
I: Loading resource table...
W: Config flags size > 56. Size = 64. Exceeding bytes: 0x1666221400000000.
W: Invalid config flags detected. Dropping resources: string-mcc204-mnc4-ERR0
W: Config flags size > 56. Size = 64. Exceeding bytes: 0x1666221400000000.
W: Invalid config flags detected. Dropping resources: array-mcc204-mnc4-ERR1
W: Config flags size > 56. Size = 64. Exceeding bytes: 0x1666221400000000.
W: Invalid config flags detected. Dropping resources: bool-mcc204-mnc4-ERR2
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[lenovo-res.zip.txt](https://github.com/iBotPeaches/Apktool/files/735401/lenovo-res.zip.txt)
[framework-res.zip.txt](https://github.com/iBotPeaches/Apktool/files/735404/framework-res.zip.txt)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?no
3. Are you using the latest apktool version?yes

I'm tried recompile framework-res.apk, but it show this error, I did not change anything, then I replaced the original file, the phone will be in black, did not show anything, it can't enter the launcher. 😢

**Comment by iBotPeaches** [comment]
Sorry for the delay. Cleaning up tickets that have no response/activity. Dropped the ball on getting to this.

This issue is because there is a new qualifier known as `spn` with an insane value range. The value I see now is `895679974`. It seems connected to mcc/mnc. I'll do some research, but this issue much like other OEMs who break AOSP qualifiers tend to cause problems with apktool.

**Comment by iBotPeaches** [comment]
I can't patch this safely. This is another qualifier and future AOSP updates may use the same space this "3rd party" qualifier is using and thus if I pack this qualifier into apktool, then AOSP update comes out everything will be decoded incorrectly.

I do not know the best way to patch this. One way is a patch/plugin/parameter system that allows you to specify different qualifiers. That works great for apktool, but adding that functionality into `aapt` is another story.

**Comment by Magendanz** [comment]
Can you recommend a workaround?  This is affecting most Motorola custom ROM development.

**Comment by iBotPeaches** [comment]
Years later. This is being added into backlog of ROADMAP. My guess is newer OEMs aren't doing this because its insane and clashes with CTS and AOSP merges.

https://github.com/iBotPeaches/Apktool/commit/d61e33048f8bf7aa28a69f40ee6fc3624534f68d
