### ISSUE TITLE
Apktool decodes/disassembles or decompiles?

### ISSUE THREAD

**Issue by dimpol** [iBotPeaches/Apktool#1429]
Sorry for the odd question but i would like to use the correct wording when referring to Apktool.

To the best of my understand Apktool decodes or let's say disassembles an APK, it doesn't decompile it.
Am i correct?

To decompile it you can use dex2jar and then use a java decompiler.

**Comment by iBotPeaches** [comment]
Correct. The correct terminology is "disassembles source", but we also decode the resources.arsc file, so a lot of people just chunk apktool under the "decode" category.
