### ISSUE TITLE
Can this be installed on Android?

### ISSUE THREAD

**Issue by limeblack** [iBotPeaches/Apktool#1434]
### Information
1. **Apktool Version (`apktool -version`)** - newest version
2. **Operating System (Mac, Linux, Windows)** - Android

It says the following

    Is it possible to run apktool on a device? 
    Sadly not. There are some incompatibilities with SnakeYAML, java.nio and aapt 

Could this be clarified to me that android isn't supported if that is what this is supposed to mean.

I would assuming noroot Debian is the best option and might work.

**Comment by pangqingyuan1991** [comment]
Yes . This is just a java program. Every platform with jre can run it. I can let it run on android too.

**Comment by iBotPeaches** [comment]
We leverage a couple of Java7 features that aren't completely in AOSP yet. Most of this being the java.nio2 library. Additionally our YAML library (SnakeYAML isn't compatible on top of Android).

Finally, our native binary (aapt) that has builds for Mac 64/32, Unix 64/32 and Windows doesn't have an ARM build for AOSP. That is why.
