### ISSUE TITLE
Instant run generated apks could not be decompiled

### ISSUE THREAD

**Issue by udaykoushik** [iBotPeaches/Apktool#1436]
### Information
1. **Apktool Version (`2.2.2`)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool d <app.apk>`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? DOESN'T APPLY
2. If you are trying to install a modified apk, did you resign it? DOESN'T APPLY
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment]
This is just a submission of the issue template.

**Comment by udaykoushik** [comment]
The apks which are generated with instant run could not be decompiled using apktool.
There is a "instant-run.zip" in the unknown folder.
There is NO other data i can submit, except for asking you how to do it.

**Comment by iBotPeaches** [comment]
There is no support for Instant Run apps then. Not until I get a sample and can investigate.

**Comment by LoadV** [comment]
艹 你们能不能别说了  我现在正难受 艹

**Comment by LoadV** [comment]
烦死了

**Comment by iBotPeaches** [comment]
Please use English on this tracker. I am simply asking for a sample. There is no need to insult me or I will lock this.

**Comment by udaykoushik** [comment]
Whoa! easy! wasn't me, i'll try and upload a sample soon.
Thanks

**Comment by iBotPeaches** [comment]
Any progress on a sample "instant built" application? Just working through bug tracker.

**Comment by udaykoushik** [comment]
I couldn't get my hands on a sample "instant built" app. Thanks for the consideration.
