### ISSUE TITLE
Apktool 2.2.2 error in disassembling K9Mail

### ISSUE THREAD

**Issue by kmicinski** [iBotPeaches/Apktool#1442]
### Information
1. **2.2.2** -
2. **Mac** -
3. **Many recent K9Mail releases. E.g., I tried on K-9 Mail v5.010 (stable): https://github.com/k9mail/k-9/releases?after=5.113** -

### Stacktrace/Logcat

```
wireless-10-104-40-86:redexer micinski$ java -jar /Users/micinski/projects/redexer/scripts/../tools/apktool.jar d -f --no-src --keep-broken-res -o tmp_dir_wrtbagjm /Users/micinski/Downloads/k9-5.113-release.apk
I: Using Apktool 2.2.0 on k9-5.113-release.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/micinski/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `java -jar /Users/micinski/projects/redexer/scripts/../tools/apktool.jar d -f --no-src --keep-broken-res -o tmp_dir_wrtbagjm /Users/micinski/Downloads/k9-5.113-release.apk`

### APK
https://github.com/k9mail/k-9/releases/download/5.113/k9-5.113-release.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?

Yes.

2. If you are trying to install a modified apk, did you resign it?

No. Just disassemble vanilla app (no modification).

3. Are you using the latest apktool version?

Yes. 2.2.2 just downloaded from website.

**Comment by laststandingdroid** [comment]
According to the log you posted you're still using 2.2.0

I: Using Apktool 2.2.0 on k9-5.113-release.apk
I: Loading resource table...

You are not using latest release

**Comment by kmicinski** [comment]
How embarrassing of me! Looks like this version does work, but thanks for looking into it. My environment caused me to use an older version.
