### ISSUE TITLE
APKTool 2.2.2 - ClassCastException ResColorValue -> ResAttr

### ISSUE THREAD

**Issue by hylo926** [iBotPeaches/Apktool#1444]
https://github.com/iBotPeaches/Apktool/issues/1060
It is almost the same issue with above.
Apktook tried to cast ResStringValue to ResAttr and it got an exception.
Only this time it is ResColorValue.
I personally modified the source as above and rebuilt the apktool, and it decompiled the apk without a problem.
I'd like to report here just in case it is a bug.

```
10:36 $ git diff
diff --git a/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java b/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java
index cc96e65..acba323 100644
--- a/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java
+++ b/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java
@@ -68,7 +68,7 @@ public class ResStyleValue extends ResBagValue implements
             if (resource.contains("ResReferenceValue@")) {
                 continue;
             } else if (resource.contains("ResStringValue@") || resource.contains("ResStyleValue@") ||
-                    resource.contains("ResBoolValue@")) {
+                    resource.contains("ResBoolValue@") || resource.contains("ResColorValue@")) {
                 name = "@" + spec.getFullName(res.getResSpec().getPackage(), false);
             } else {
                 ResAttr attr = (ResAttr) spec.getDefaultResource().getValue();
```

### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
$ java -jar ../apktool_2.2.2.jar d -f xxx.apk
I: Using Apktool 2.2.2 on xxx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\yyy\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResColorValue cannot be cast to brut.androlib.res.data.value.ResAttr
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:74)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:517)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. java -jar ../apktool_2.2.2.jar d -f xxx.apk

**Comment by iBotPeaches** [comment]
It seems like a hacky fix of mine to continually add all types to this check, when all it does it get the spec name. I think we can evolve this check to be a smarter to simply call this method, except in situations where its a ResReference and/or the object doesn't extend or support the ResAttr.

Any name of apk or link to playstore entry? Can email if private (ibotpeaches) (dot) gmail (dot) com, just so I don't have to waste time building a fake apk in order to duplicate this.

**Comment by hylo926** [comment]
I sent you a mail about the apk I used.
I hope it's not too late.

Yes, it's a hacky fix. 
It would be good for all of us if you evolve this to a smarter way.

**Comment by iBotPeaches** [comment]
APK obtained. Confirmed problem. Will work on a more enhanced fix.
