### ISSUE TITLE
Adding network_security_config.xml to res/xml folder failed

### ISSUE THREAD

**Issue by rpw98** [iBotPeaches/Apktool#1446]
Hi, I decompiled an apk using apktool and added my own network_security_config.xml to res/xml folder. Also edited manifest file to include it. Then I built it with apktool and get a new apk. Just for testing, I decompiled the new apk. But I could not find network_security_config.xml in res/xml folder. Why was it not included in the new build? Can anyone tell me how to fix it?

Thank you!

### Information
1. **Apktool Version (2.2.2)** -
2. **Operating System (Mac)** -

**Comment by maxerbox** [comment]
Maybe the file is detected as a Unknow file

**Comment by iBotPeaches** [comment]
![test](https://cloud.githubusercontent.com/assets/611784/23749707/85678784-0497-11e7-9e3c-fd90148b3464.png)

Could not duplicate. If you can make a failing unit tests or a bit more detail, maybe I can look into it again.
