### ISSUE TITLE
ApkTool 2.2.2 takes long to decode apk compared to 2.1.0

### ISSUE THREAD

**Issue by amjadaziz817** [iBotPeaches/Apktool#1450]
### Information
1. **Apktool Version (`2.2.2`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

I am trying to decode apk using latest apktool. It is taking longer than v2.1.0.
Current version 2.2.2 takes about 11 seconds to decode an apk however apktool v2.1.0 takes 4.5 seconds for same apk file at same machine with same load.

Please find the attachments decoding apk file using two different apktool versions.

Any comment will be appreciated.

Thanks,
Amjad 

![apktool_v2 1 0](https://cloud.githubusercontent.com/assets/10373411/23748317/ea4ef284-04e4-11e7-8ba6-79a6531de070.jpg)
![apktool_v2 2 2](https://cloud.githubusercontent.com/assets/10373411/23748322/f0c6545e-04e4-11e7-8c56-e43e104e89a7.jpg)

**Comment by iBotPeaches** [comment]
Quite a lot of changes between `2.1.0` & `2.2.2`. Is `2.2.2` the first time you experienced this? If so I can start bissecting between `2.2.1` and `2.2.2`

There is `2.1.0` -> `2.1.1` -> `2.2.0` -> `2.2.1` -> `2.2.2`, so quite a lot to look into it.

**Comment by amjadaziz817** [comment]
Hi Connor,

Thanks for reply.

Initially I faced this issue from `v2.1.1` to `v2.2.0` but the delay was not much. It increased from 4.5 seconds to 5.5 seconds.
But for `v2.2.1` the time increased two times from previous release `v2.2.0`.

It looks like the issue is with `android-framework.jar` updated in `v2.2.1`. 

If I use platform from `v2.2.0`, decoding apk using `v2.2.1` is almost same(5.5 seconds) without cleaning framework of previous release.

After cleaning platform through `apktool empty-framework-dir`

`v2.2.1` takes around 11 seconds to decode same apk.

Hope this information will help.

Let me know if you need to know anything.

Thanks,
Amjad

**Comment by iBotPeaches** [comment]
I looked into this, I can make 2.2.2 just as fast as 2.1.0 if I use the internal framework of 2.1.0. Frameworks are getting larger and this is slowing down apktool. There is really nothing I can do here, the design of apktool is how it is which is iterations over resources. This will increase time of execution as resource count increases (which it does with every release)

**Comment by amjadaziz817** [comment]
Thanks.
Just a quick question, is it safe to use framework of `v2.1.0` in `v2.2.2` ?

**Comment by iBotPeaches** [comment]
Not really. You lose support for Android N and M if you do that.

**Comment by amjadaziz817** [comment]
Thanks.
