### ISSUE TITLE
Java error whilst decompressing an APK file.

### ISSUE THREAD

**Issue by Roman-Port** [iBotPeaches/Apktool#1451]
ApkTool version 2.0.0rc3
Windows 10
Apk comes from Google Play Store.

Log: 
[log.txt](https://github.com/iBotPeaches/Apktool/files/840071/log.txt)

How to reproduce:
I'm trying to decode the YouTube APK. Upon running the script, it will successfully decompress the resource table, and the manifest before failing while decoding a "attr value". 

This APK cannot be redistributed, but it is the stock YouTube app.

I have tried various versions of ApkTool, none of them can get past this step.

**Comment by Roman-Port** [comment]
Wow, I'm an idiot. Figured it out. I'm genuinely sorry, but I can't figure out how to delete my post.

**Comment by iBotPeaches** [comment]
All good, glad you figured it out. Closing.
