### ISSUE TITLE
Apk loses MAPS function after edit with this tool

### ISSUE THREAD

**Issue by lastblade** [iBotPeaches/Apktool#1452]
Hi,

I have one apk which render on google map and it draw path at google map it gets from server API.
Original apk works fine but when I do the decoding and build again without any change.
New apk installed properly but I am not able to see google map on rebuild apk.

I tried :
use the "key manager" inside this tool ( with and without  "keystore generation")
use ApkSigner (https://shatter-box.com/knowledgebase/android-apk-signing-tool-apk-signer/) to creating a new keystore, sign and align.

nothing...

**Comment by CunningLogic** [comment]
Google maps API keys are (or used to be) specific to the signature of the application. Sign up for a new API key.

**Comment by lastblade** [comment]
A how i can do that without having the source code ?

**Comment by iBotPeaches** [comment]
As far as I'm convinced, it is just API keys to change which are usually in `/res/xml` in some file.

Closing this, as I believe jcase is correct.
