### ISSUE TITLE
 a problem- after compile APK line bar removed- picture here

### ISSUE THREAD

**Issue by israrami** [iBotPeaches/Apktool#1462]
hello, i try compile any app on miui 8 system , but the problem that after compile i lost the bar top, and it be black always,the color on top of screen removed after compile, someone here know how to fix that , I want after compile all be green on top bar not black bar, someone know how fix?
![41](https://cloud.githubusercontent.com/assets/26686760/24360666/a49593d0-1310-11e7-838f-43d0b5ff4432.jpg)

**Comment by iBotPeaches** [comment]
1. MIUI isn't supported
2. This was already fixed with a reference fix here - https://github.com/iBotPeaches/Apktool/issues/1382
3. You gotta keep the issue template. its impossible to diagnose issues when its deleted.
