### ISSUE TITLE
Error when i compiled apk

### ISSUE THREAD

**Issue by maxben14** [iBotPeaches/Apktool#1468]
--------------------------------------------------
Batch ApkTool                : 3.6.2
SMALI                        : smali-2.2.jar
Уровень API                  : 23
Подпись                      : ДА
--------------------------------------------------

[*] Рекомпиляция (smali) 444...
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 74246
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:338)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1039)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:818)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
	at org.jf.smali.Smali.assemble(Smali.java:130)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:99)

[*] ---> Ошибка рекомпиляции (smali) "444"

How fixed error ?

**Comment by BORETS24** [comment]
это обозначает, что произошло превышение максимального количества методов на один класс classes.dex. необходимо перенести папку, где Вы производили изменения,к примеру, из smali в smali_classes2, сохранив тот же путь. К примеру, проводили изменения в smali/android/os, так вот вырезать папку os и переместить её в smali_classes2/android, чтоб получилось smali_classes2/android/os

**Comment by maxben14** [comment]
А как дебажить тогда второй дех файл ? А то не понятно как его дебажить в случае мультидекса ?

**Comment by BORETS24** [comment]
я не знаю, как и для чего дебазжить, я сам сталкивался с подобной ошибкой при сборке framework.jar, перенес в смали классес2- стало собираться и работать. А вообще бывает оччччень много классес декс, я вот для примера разбирал системуи от андроида 7, так там вообще 30 штук classes.dex-и ничего
![default](https://cloud.githubusercontent.com/assets/15519242/24621503/58f2af2c-18aa-11e7-991b-3b478219ce5a.png)

**Comment by maxben14** [comment]
Я хотел провести отладку приложения через ида про, думал как второй дех файл дебажить.

**Comment by BORETS24** [comment]
ну я так глубоко не копаю и не разбираюсь в программировании, так, редактирую фреймворки и арк для телефонов- кое-что получается

**Comment by iBotPeaches** [comment]
English please :)

You've hit the limit of functions in a dex file. See these two smali tickets

https://github.com/JesusFreke/smali/issues/268
https://github.com/JesusFreke/smali/issues/301

Split them into more dex files, as the screenshots and text above I assume says.

**Comment by maxben14** [comment]
How debug functions in 2 dex file with ida pro if i split functions on two dex files ?
