### ISSUE TITLE
apktool rebuild - unresolved class , unresolved super class

### ISSUE THREAD

**Issue by gmistick** [iBotPeaches/Apktool#1469]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool decode`
2. `make modifications to manifest and code`
3. `apktool build`
4. `sign apk`
5. install apk
6. run app , everything working great. sometimes it crash due to unresolved class access which is something i didnt touch or is any relevant to the code i touched.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

None

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? 2.2.0

I localized an app, and it works most of the time, and it crashes in some other times because of "unresolved class ...." , "unresolved super class"... of classes i never touched.

i use apktool decode, then make modifications very carefully, apktool build , sign and install.
the app works great ( for months.. ), but sometimes it crashes with the error above.

**Comment by iBotPeaches** [comment]
Do you have an `adb logcat` of the host device during this crash/failure? Seems smali related, but with no binary or log nothing really I can do here.

**Comment by iBotPeaches** [comment]
Closing due to no response in 1+ months. I need either an apk or `adb logcat` of the failure to investigate. I can re-open and re-investigate if provided.
