### ISSUE TITLE
DexProtector - APKTOOL_DUPLICATENAME_0x7f0f0001

### ISSUE THREAD

**Issue by maxben14** [iBotPeaches/Apktool#1474]
I try decompiled apk resource but after decompilation all names in resources as k_APKTOOL_DUPLICATENAME_0x7f0f0001 names. Why so work apktool ? How fixed ?

If you need my apk i can upload apk your for research mistakes in apktool.

**Comment by iBotPeaches** [comment]
Sure, upload the apk. `DUPLICATENAME` should only happen with Dexguard applications so maybe a mistake was made.

**Comment by maxben14** [comment]
http://rgho.st/68gldNwQV
My apk.

**Comment by maxben14** [comment]
Do you get my apk ? What about mistake in apktol ?

**Comment by maxben14** [comment]
Have you looked at my apk file? Did you manage to find the error? I am interested in your answer and hope to see a revised version of the apktool.

**Comment by iBotPeaches** [comment]
@maxben14 see - https://github.com/iBotPeaches/Apktool/issues/1480#issuecomment-294970099

You have generated 6 emails in my inbox today. Please wait until I have time to process this.

**Comment by iBotPeaches** [comment]
> File is deleted

Can't confirm or investigate. Closing this.

**Comment by maxben14** [comment]
My apk http://rgho.st/6MCmqYV8c

**Comment by maxben14** [comment]
Do you see apk ? Find mistake ?  Please write about research.

**Comment by iBotPeaches** [comment]
Seems to be an enhanced form of obfuscation, maybe AndResGuard or something. Closing into #1427 to organize these related tickets.

**Comment by maxben14** [comment]
The program is packed with the help of dexprotector https: //dexprotector.com
This is not a pro-guard defense, as I understand it.
I also have a problem with decompiling, I get empty resource files in the folder /res/main. You can tell why this happens, is not compiled back because of the empty resource files in the folde /res/main.

**Comment by iBotPeaches** [comment]
Thanks, DexProtector and Dexguard now. These are some smart tools. I'll keep this one as DexProtector ticket.

**Comment by maxben14** [comment]
Tell me please about the smart tools against dexprotector.

**Comment by iBotPeaches** [comment]
Not sure what you mean by that. Probably outside the scope of this project any who.

**Comment by maxben14** [comment]
Ok, other question about resource. I try decompile resource in apk with apktool last version, but i get empty resource in folder res/menu. Do you can see my apk, try decompile and write why apktool do empty resource files only in folder res/menu, in other folder res/* very good.

**Comment by iBotPeaches** [comment]
Sorry left this for 4+ years. I don't have apk.

> File is deleted


Going to close as not able to do anything.
