### ISSUE TITLE
Build App is broken

### ISSUE THREAD

**Issue by hevilp** [iBotPeaches/Apktool#1477]
1. **Apktool Version 2.2.2**
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Internal

### Stacktrace/Logcat
App cannot be installed something is broken

I only decoded and build the app with:
java -jar C:\Windows\apktool.jar d D:\MScAN_2.2.apk D:\test

D:\test>java -jar C:\Windows\apktool.jar b .

On installing the app there comes an error:

App is broken...

Compiling without any errors

**Comment by iBotPeaches** [comment]
Run `adb logcat` during application install to get the real error as there isn't much, if any, information to go on here.

**Comment by iBotPeaches** [comment]
Closing due to no response in 1+ month. If you can get an `adb logcat` of the failure and potentially apk as well we can revisit.
