### ISSUE TITLE
Only values folder is present in the res directory [No name for the files in unknown directory]

### ISSUE THREAD

**Issue by MujammilAhamed** [iBotPeaches/Apktool#1483]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Yes

### Stacktrace/Logcat
![a5ab6813-974a-432f-841d-56c986cdddde](https://cloud.githubusercontent.com/assets/17060947/25326390/9edbee42-28ed-11e7-9c85-d2f58e170bf3.png)

```
apktool d jp_morgan.apk
I: Using Apktool 2.2.2 on jp_morgan.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

apktool b jp_morgan
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'APKTOOL_DUMMYVAL_0x7f080090' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...

```
### Steps to Reproduce
1. `apktool  d jp_morgan.apk`
2. `apktool b jp_morgan.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it. Yes,https://play.google.com/store/apps/details?id=com.jpm.sig.android&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Welcome to Dexguard. This is what it does and the scope of Apktool isn't to undo the large amount of anti-tampering features it has. 

```
04-27 08:45:59.247   197   815 D AudioFlinger: mixer(0xb4180000) throttle end: throttle time(4)
04-27 08:45:59.264  4402  4402 D Chase   : ScreenID=[Ljava.lang.String;@dd6704c
04-27 08:45:59.312  4402  4402 D Chase   : -- DexGuard: Tampering detected --
04-27 08:45:59.333  4402  4402 D Chase   : -- DexGuard: Different certificate detected --
```

It can be decoded and rebuilt, which is a huge improvement in apktool from previous iterations. So nothing really for apktool to do here.
