### ISSUE TITLE
Very slow performance of AndroidLib.decodeManifestWithResources

### ISSUE THREAD

**Issue by prsekar** [iBotPeaches/Apktool#1489]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0 and above
2. **Operating System (Mac, Linux, Windows)** - linux and mac
3. **APK From? (Playstore, ROM, Other)** - any large apk 5mb or more its very evident

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. We call the java api AndroidLib.decodeManifestWithResources from our src code which is slowing down the unwrapping APK when compared with apktool 2.1.1.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes even cmdline is slow but its much more slower within jvm
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
This is because of the larger and larger framework files Apktool has to decode. Perhaps we can re-engineer the storage of these framework files into a format more suitable for apktool to process.

**Comment by prsekar** [comment]
We had been using 2.1.1 and it has been working like a charm for the same fat apk. Once we upgrade 2.2.0 or above we see the slow performance. Did something drastically change between those versions w.r.t the storage architecture?

**Comment by iBotPeaches** [comment]
2.2.0 gained the Nougat framework which was huge in size in comparison to 2.1.1

**Comment by prsekar** [comment]
Back to the redesign of storage architecture, if you have plans, let me know if i could be of help.

Thanks for this oss library. Its very helpful.

**Comment by iBotPeaches** [comment]
I've been thinking, we read the framework file (but store the framework file prior to decode) based on tags, etc. So decodes have to decode the framework file and then the internal framework of the apk in question. This is proving to take longer and longer. However, we are reading the file for one reason - the resources.

I might research the best flat file format for Java to parse and read, since at the end of the day we might be able to get away with a simple k/v store of resourceId -> resourceName (with some additional type data)

**Comment by iBotPeaches** [comment]
Moving all the speed/memory enhancement tickets together. The first report was #1396 so closing this one in favor of that one.

**Comment by iBotPeaches** [comment]
While closed. This change: https://github.com/iBotPeaches/Apktool/commit/b45054e65ea7babd3247b276686a1adbbc3b59f3 has greatly helped in the speed execution.

```
apktool_224 d callrecorder.apk -f  14.76s user 2.68s system 276% cpu 6.307 total
apktool_223 d callrecorder.apk -f  25.46s user 3.64s system 195% cpu 14.853 total
```
