### ISSUE TITLE
Apktool loses values for recompilation

### ISSUE THREAD

**Issue by ale8530** [iBotPeaches/Apktool#1495]
### Information
1. Apktool version 2.2.2
2. Ubuntu 64bit
3. Settings.apk from MIUI android 7.0

I know exactly that you do not like to see MIUI problems, but I would like to know if by chance it may be a generic apktool problem, because during recompilation you lose the value </li>

When decompile Settings.apk i have:
![e9be51ee-31de-11e7-880c-ee58d0bc3469](https://cloud.githubusercontent.com/assets/6189615/25795412/87a43fca-33d5-11e7-9cab-b2eef83c732e.png)

**If I rebuild without editing anything I have an error because the tag is missing </li>**

To recompile, I must enter the highlighted value in this screenshot:

![2a0b58d6-31e0-11e7-8b44-3c862d71a86a](https://cloud.githubusercontent.com/assets/6189615/25795476/c1c966da-33d5-11e7-92ec-332d10427030.png)

Can it be an apktool bug losing this value?

Thanks for your attention

**Comment by iBotPeaches** [comment]
`<li>` doesn't look like a valid HTML tag at the `strings.xml` level - https://developer.android.com/guide/topics/resources/string-resource.html#StylingWithHTML

> The work-around to this is to write the HTML tags with escaped entities

I assume applies to non-standard tags. This is not escaped. Apktool is probably doing the best it can. Do `aapt d --values resources foo.apk` and see what the actual value is (escaped or not).

You then could also write this string into a new qualifier for organization and make a `string.xml` test file with `test1` as the string and submit a failing pull request. That saves having to upload a bunch of frameworks and stuff if you can isolate the failing string.

**Comment by ale8530** [comment]
Thanks Ibot for your reply.

[Log](https://drive.google.com/open?id=0B7Jt4O5aMbsVTzJnOTk5ZU9IZjQ) for this command -->aapt d --values resources Settings.apk

[Files originals apk](https://drive.google.com/open?id=0B7Jt4O5aMbsVbWhtQ3NoQk9BVE0) for your test

**Comment by iBotPeaches** [comment]
Interesting.

```
 resource 0x7f0e045b com.android.settings:string/wifi_and_mobile_skipped_message: t=0x03 d=0x00000072 (s=0x0008 r=0x00)
          (string8) "If you skip WLAN:\n\nYour phone won’t have an Internet connection.\n\nYou won’t get software updates until you connect to the Internet.\n\nYou can’t activate device protection features at this time."
```

The log says they are newlines, not list elements. Not sure whats going on here. I'll need to look at applications later.

**Comment by ale8530** [comment]
Thank you for taking the time :)

**Comment by ale8530** [comment]
News?
