### ISSUE TITLE
Problem Decompile source !!!

### ISSUE THREAD

**Issue by Fays** [iBotPeaches/Apktool#1497]
### Information
1. **Apktool Version (`Apktool 2.2.3-ea16f3-SNAPSHOT`)** -
2. **Operating System (Linux Mint 18.1)** -
3. **APK From? (Xiaomi Mi-Drone-0.0.59.17)** -

Lien apk: http://app.mi.com/details?id=com.fimi.soul&ref=search

### Stacktrace/Logcat

```
java -jar apktool-cli-all.jar d Mi-Drone-0.0.59.17.apk 
I: Using Apktool 2.2.3-ea16f3-SNAPSHOT on Mi-Drone-0.0.59.17.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fayz/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
La/ab;-><init>(La/s;La/q;)V: Invalid debug offset
La/aa;-><init>(La/s;La/ae;La/q;Ljava/util/concurrent/Executor;)V: Invalid debug offset
La/a;-><init>(Ljava/lang/String;[Ljava/lang/Throwable;)V: Invalid debug offset
L0/0;-><init>()V: Invalid debug offset
La/ab;-><init>(La/s;La/q;)V: Invalid debug offset
La/a;-><init>(Ljava/lang/String;[Ljava/lang/Throwable;)V: Invalid debug offset
La/aa;-><init>(La/s;La/ae;La/q;Ljava/util/concurrent/Executor;)V: Invalid debug offset
La/a;-><init>(Ljava/util/List;)V: Invalid debug offset
La/ab;->a(La/s;)La/s;: Invalid debug offset
La/ab;->a(La/s;)La/s;: Invalid debug offset
La/ac;-><init>(La/s;La/q;)V: Invalid debug offset
La/ac;-><init>(La/s;La/q;)V: Invalid debug offset
La/ac;->a(La/s;)La/s;: Invalid debug offset
La/ab;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/ab;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/ac;->a(La/s;)La/s;: Invalid debug offset
La/aa;->a(La/s;)Ljava/lang/Void;: Invalid debug offset
La/ac;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/ac;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/a;-><init>(Ljava/util/List;)V: Invalid debug offset
La/aa;->a(La/s;)Ljava/lang/Void;: Invalid debug offset
La/ae;-><init>(La/s;)V: Invalid debug offset
La/a;->a()Ljava/util/List;: Invalid debug offset
La/ae;-><init>(La/s;)V: Invalid debug offset
La/a;->b()[Ljava/lang/Throwable;: Invalid debug offset
La/ae;-><init>(La/s;La/t;)V: Invalid debug offset
La/ae;-><init>(La/s;La/t;)V: Invalid debug offset
La/ad;-><init>(La/q;La/s;La/ae;)V: Invalid debug offset
La/aa;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/aa;->then(La/s;)Ljava/lang/Object;: Invalid debug offset
La/ae;->a()La/s;: Invalid debug offset
La/af;-><init>(Landroid/content/Context;)V: Invalid debug offset
La/ae;->a(Ljava/lang/Exception;)Z: Invalid debug offset
La/af;-><init>(Landroid/content/Context;)V: Invalid debug offset
La/ag;-><init>(La/af;Landroid/net/Uri;)V: Invalid debug offset
La/af;->a(Ljava/util/Map;Landroid/net/Uri;)La/e;: Invalid debug offset
La/ag;-><init>(La/af;Landroid/net/Uri;)V: Invalid debug offset
```
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Did decode fail? This is just baksmali letting you know that someone inserted bogus debug offsets in order to crash the tool. Baksmali has since been updated, but is still letting you know that it encountered invalid data.

See: https://github.com/JesusFreke/smali/commit/384161e060fc2bb40848b818d75f201c0ec037c8 & https://github.com/JesusFreke/smali/issues/502 & https://github.com/JesusFreke/smali/issues/415#issuecomment-251004019

**Comment by quyeticb** [comment]
I have same problem. I'm using both [apktool online](https://apk.tools/tools/apktool) and apktool offline, same results. Can not decode

**Comment by iBotPeaches** [comment]
@quyeticb These issues are not related at all and the stack trace you are posting was literally posted yesterday. This is the bug you want to watch - #1500 , not this one.

**Comment by iBotPeaches** [comment]
```
Lit/sephiroth/android/library/R$styleable;-><init>()V: Invalid debug offset
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1497 apktool b com.fimi.soul
I: Using Apktool 2.2.3-bd62f7-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1497 
```

Dug into this. Sorry for the delay. This is because this application is attempting to put debug offset ids outside of normal range, thus throwing NPE errors. Smali is correctly catching them and issuing a warning, but you get a lot of them. Nothing is broken, simply warnings.

**Comment by Fays** [comment]
Yes
But the bug application FC

**Comment by Fays** [comment]
Using apktool d -s midrone.apk
 same application does not work

**Comment by iBotPeaches** [comment]
If the application is FC`ing, you need to get a `logcat` of the failure. The original issue this was opened for was resolved.
