### ISSUE TITLE
 How do I run an application's source code on Android Studio after decompiling it through apktool?

### ISSUE THREAD

**Issue by BishalSaha** [iBotPeaches/Apktool#1502]
How do I run an application's source code on Android Studio after decompiling it through apktool?
How do I run an application's source code on Android Studio after decompiling it through apktool?
How do I run an application's source code on Android Studio after decompiling it through apktool?

**Comment by iBotPeaches** [comment]
Apktool disassembles to smali, not human readable java code so execution through Android Studio would not be possible. You can use Smali Idea which provides syntax highlighting and this might kinda help - https://github.com/JesusFreke/smali/wiki/smalidea

Either way, this is a bug tracker. Not a support forum. I'm closing this.
