### ISSUE TITLE
corrupt jar file from working apk

### ISSUE THREAD

**Issue by kinergy** [iBotPeaches/Apktool#1505]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 16.04
3. **APK From? (Playstore, ROM, Other)** - http://www.apkmonk.com/download-app/cn.ninebot.ninebot/2_cn.ninebot.ninebot_2017-05-10.apk/

### Steps to Reproduce
1. `apktool d cn.ninebot.ninebot_2017-05-10.apk`
2. `cd cn.ninebot.ninebot_2017-05-10/assets/`
3. `unzip -l classes0.jar`

the jar file seems to be incomplete or corrupt.

**Comment by iBotPeaches** [comment]
Without apktool you can extract this jar file and notice it is also incomplete/corrupt. You could try digging around the application to see if it attempting to load this file in anyway, perhaps compressed/encrypted. 

I can take a closer look later, but this doesn't seem to be a bug in apktool at all.

**Comment by iBotPeaches** [comment]
Dug into this more. Apktool is doing nothing wrong here. The JAR using a simple extract suffers the same consequence as apktool decoding it. Closing as nothing apktool can do here.
