### ISSUE TITLE
no main manifest attribute, in brut.apktool.jar

### ISSUE THREAD

**Issue by B4RD4k** [iBotPeaches/Apktool#1507]
Hey Guys,
I build the APKTOOL using gradle but i can't use the final jar since this error message:
no main manifest attribute, in brut.apktool.jar

what should i do?

**Comment by portorwang** [comment]
me too, how do you deal with it ?

**Comment by limkokhole** [comment]
The error is due to building Apktool with `./gradlew build` instead of `./gradlew build shadowJar proguard`.
