### ISSUE TITLE
Missing optical insets in 9Patch

### ISSUE THREAD

**Issue by phhusson** [iBotPeaches/Apktool#1511]
aapt supports npLb PNG tags, which are then used by the framework, which will assume its value is 0 if it is not here.
In my understanding, this is simply a pre-processing done in aapt, which would just need to be (re?)enabled in apktool's aapt, though I'm not sure how/why is it disabled in apktool's aapt.

This leads to some graphical differences, with buttons being offset-ted from its actual position:
https://drive.google.com/file/d/0B5fQwPNvh3h0OVltb2N2eE90Smc/view?usp=sharing
(left is expected, center is actual result, right is the delta)
I can confirm that doing unzip framework-res-origina.apk res/drawable-hdpi-v4/btn_switch_to_o'*'
fixes the issue for the related resource (and the previously-mentioned delta-test)

I'm currently working on understanding why this code is not triggered in apktool's aapt, so hopefully I'll have a PR.

**Comment by phhusson** [comment]
Ok, so this isn't a simple pre-processing, that information is stored as red pixel in the outling frame, so it would just need to reconstruct it

**Comment by iBotPeaches** [comment]
Thanks for the research. So it seems like reconstructing the black border for the 9patch format itself, we need to additionally support optical inserts by reconstructing red pixels. 

Will have to dig into the internals of 9patch more, some recent changes include

https://github.com/iBotPeaches/platform_frameworks_base/commit/6381dd4ff212a95be30d2b445d40ff419ab076b4 - LP64: Make 9 patches architecture agnostic.

https://github.com/iBotPeaches/platform_frameworks_base/commit/a730ef3f77fc495bc90199b4d45efab26d609782 -  Handle bad ninepatch data.
