### ISSUE TITLE
Can not rebuild after package name changed

### ISSUE THREAD

**Issue by siebeneicher** [iBotPeaches/Apktool#1514]
Using apktool 2.2.2 on windows.

Decompiling and recompiling without changing anything works great.

But after changing the package name, recompiling throws weird error: _Exception in thread "main" brut.androlib.AndrolibException: Unable to rename temporary file_

> I: Checking whether sources has changed...
> I: Smaling smali_classes9 folder into classes9.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> I: Copying libs... (/lib)
> I: Building apk file...
> I: Copying unknown files/dir...
> Exception in thread "main" brut.androlib.AndrolibException: Unable to rename temporary file
>         at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:592)
>         at brut.androlib.Androlib.build(Androlib.java:318)
>         at brut.androlib.Androlib.build(Androlib.java:263)
>         at brut.apktool.Main.cmdBuild(Main.java:227)
>         at brut.apktool.Main.main(Main.java:84)

So the build goes through, but copying unknown files/dir did not!?

apktool.yml _unknownFiles_ looks okay, files and dirs are existing:

> unknownFiles:
>   build-data.properties: '8'
>   com/facebook/java2js/annotation/FBGlobalStrings.cpp: '8'
>   jsr305_annotations/Jsr305_annotations.gwt.xml: '8'
>   templates/release-notes.vm: '8'

Where could I start searching?

I have followed https://github.com/iBotPeaches/Apktool/issues/1088 in order to change the package name.

Any help appreciated!!

**Comment by iBotPeaches** [comment]
This looks like a permission problem. What apktool does under the hood is create a temporary zip file (of the soon to be built apk). This temporary file is injected with unknown files to maintain the compression they used original file. However, you said it previously worked so not entirely sure.

Can you check if the directory has a file called `AndroidManifest.xml.org` in it? If so, can you delete it and try again?

**Comment by siebeneicher** [comment]
I got it working, not sure why, but a previous build created the apk file, which could not be replaced by the new build. Deleting the previous apk, does allowed to finish the current build. Thanks for tips!
