### ISSUE TITLE
No Drawable & Layout Folder

### ISSUE THREAD

**Issue by ajigile** [iBotPeaches/Apktool#1527]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Linux Mint 18.1 64bit
3. **APK From? (Playstore, ROM, Other)** - playstore

xxx@xxx ~/xxx/xxx/xxx $ apktool d xxx.apk
I: Using Apktool 2.2.2 on xxx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/xxx/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

everything is fine, but no drawable, layout, and xml folder... 
thanks

FILE here --> https://goo.gl/9TlZCw

**Comment by argraur** [comment]
Weird. If we unpack this apk all files that should be in res folder are encoded and placed in root of zip, what is wrong though, and they are having weird names, check your 'unknown' folder, apktool should put that files into that folder

**Comment by iBotPeaches** [comment]
Intentional. Welcome to applications making things difficult to decode.

**Comment by iBotPeaches** [comment]
There is nothing apktool can do here.

```
    3063  Stored     3063   0% 05-31-2017 13:15 647607a3   ������.png
    3862  Stored     3862   0% 05-31-2017 13:15 37eaf92e  ���^L .png
    1459  Defl:N     1222  16% 05-31-2017 13:15 821415bf  ���^L���
     472  Defl:N      219  54% 05-31-2017 13:15 cd409bd8  ������.xml
```

These are clever named resources as a form of resource obfuscation. Something in this application (probably in the also obfuscated source) handles the loading of these resources. There is nothing apktool can do to resolve this. It survived decoding and rebuilding which is really where apktool ends. Anything outside of that (like automated resource obfuscation remapping is out of scope)
