### ISSUE TITLE
It is not a bug though a feature

### ISSUE THREAD

**Issue by Jasi2169** [iBotPeaches/Apktool#1539]
what i am looking is that can't we decode only layout xml and encode it back 

> apk/res/layout

or any kind of feature which allows us to decode one xml and encode it back as well ?

the reason why i am saying is that because encoding resources back always have problems ,so having option to decode one xml file or files in specific directory and encoding it back ?

**Comment by iBotPeaches** [comment]
How do you decode one file? Any layout file probably has tons of references to styles, strings and more and you can't decode those styles, strings and more without `resources.arsc` decoding and at that point you've already decoded most of the application. The only remaining resource files would be the remaining layouts and images.

Thats the real reason, so not on my radar to support this enhancement.

**Comment by Jasi2169** [comment]
this library works
https://github.com/wtchoi/axml

i can decode and encode on android itself with application

maybe you can try better if you wanna take a look

**Comment by iBotPeaches** [comment]
Thanks, but apktool is not engineered in a way to support this. Feel free to use that library though.
