### ISSUE TITLE
Prebuilt aapt not found if apktool jar is built into a spring boot app

### ISSUE THREAD

**Issue by bingqiao** [iBotPeaches/Apktool#1543]
I'm trying to use apktool jar in a Spring boot project and found that prebuilt aapt binaries are not accessible in the Spring boot executable jar while android-framework.jar is.
The cause of this is that Jar#extractToTmp calls getResourceAsStream on Class.class instead of AndrolibResources.class. And in the context of Spring boot, this call fails because the prebuilt aapt binaries are not packaged in the root directory.

Any chance to change this method and those calling it to something like this?
```
public static File extractToTmp(String resourcePath, String tmpPrefix, Class clazz)
		throws BrutException {
	try {
		InputStream in = clazz.getResourceAsStream(resourcePath);
		if (in == null) {
			throw new FileNotFoundException(resourcePath);
		}
		File fileOut = File.createTempFile(tmpPrefix, null);
		fileOut.deleteOnExit();
		OutputStream out = new FileOutputStream(fileOut);
		IOUtils.copy(in, out);
		in.close();
		out.close();
		return fileOut;
	} catch (IOException ex) {
		throw new BrutException(
			"Could not extract resource: " + resourcePath, ex);
	}
}

public static File extractToTmp(String resourcePath, String tmpPrefix) throws BrutException {
	return extractToTmp(resourcePath, tmpPrefix, Class.class);
}
```

**Comment by iBotPeaches** [comment]
> prebuilt aapt binaries are not accessible in the Spring boot executable jar while android-framework.jar is.

Why is that? `android-framework.jar` is at `/brut/androlib/`, while `aapt` is at `/prebuilt/aapt`. While different directories they are both 2 directories deep. Granted, `android-framework` is in the folder path of the Brut Androlib package.

You can also do a Pull Request to propose changes to this functionality in that is easier to describe an enhancement or tweak.

**Comment by bingqiao** [comment]
Class.class.getResourceAsStream tries to load resource from root directory. This fails when apktool is built into a fat jar like Spring boot executable becasue the classloader of Class tries to load the resource from the root directory of the Spring boot jar instead of that of the bundled appktool jar. The loading of android-framework.jar works because it's the classloader of AndrolibResources loading the jar.

I created a pull request to show the fix that works for my app.

**Comment by bingqiao** [comment]
This is the classloader for AndrolibResources: org.springframework.boot.loader.LaunchedURLClassLoader.
And "Class" is loaded by BootStrap ClassLoader. The latter doesn't work when apktool jar is packaged inside a Spring boot jar without having prebuilt in the root directory of the Spring boot jar. I'm not sure if apktool is not supposed to be used this way but so far it seems to work perfectly except for this. I could package another copy of prebuilt in the root directory of Spring boot jar or build apktool with the aforementioned fix (I'd have to build it myself anyway to use it in a maven project).

**Comment by iBotPeaches** [comment]
Thanks for the report and quick pull request. This has been merged into master.
