### ISSUE TITLE
Decompile failes with aap2 changes

### ISSUE THREAD

**Issue by forkoz** [iBotPeaches/Apktool#1555]
> (Exception in thread "main" java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized. at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:116) at brut.androlib.res.xml.ResXmlPatcher.loadDocument(ResXmlPatcher.java:261) at brut.androlib.res.xml.ResXmlPatcher.removeManifestVersions(ResXmlPatcher.java:203) at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:220) at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137) at brut.androlib.ApkDecoder.decode(ApkDecoder.java:113) at brut.apktool.Main.cmdDecode(Main.java:166) at brut.apktool.Main.main(Main.java:80) Process exited with code 1
> )

App used to decompile with the latest realease.

**Comment by iBotPeaches** [comment]
Seems to be a problem with JDK versions - https://bugs.openjdk.java.net/browse/JDK-8016153

Not isolated to apktool.
