### ISSUE TITLE
Windows build failed

### ISSUE THREAD

**Issue by bovirus** [iBotPeaches/Apktool#1558]
After latest update I cannot get error about wrong license but I get this kind of error

Building SNAPSHOT (master): 380cb9

Missing header in: brut.j.common\src\main\java\brut\common\BrutException.java
Missing header in: brut.j.common\src\main\java\brut\common\InvalidUnknownFileException.java
Missing header in: brut.j.common\src\main\java\brut\common\RootUnknownFileException.java
Missing header in: brut.j.common\src\main\java\brut\common\TraversalUnknownFileException.java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.j.common:licenseMain'.
> License violations were found: D:\GIT\Apktool\brut.j.common\src\main\java\brut\common\BrutException.java,D:\GIT\Apktool\brut.j.common\src\main\java\brut\common\InvalidUnknownFile
Exception.java,D:\GIT\Apktool\brut.j.common\src\main\java\brut\common\RootUnknownFileException.java,D:\GIT\Apktool\brut.j.common\src\main\java\brut\common\TraversalUnknownFileExcep
tion.java}

OS: Windows 7 64bit - Java JDK 1.7.080

**Comment by iBotPeaches** [comment]
#1553 Duplicate. Pretty much exact issue title

**Comment by bovirus** [comment]
How can fix that?
I didn't find any fix in the code (latest fix was 17 hours ago).

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/issues/1553 isn't Closed.....

Therefore not fixed.
