### ISSUE TITLE
 Invalid or corrupt jarfile bin/apktool.jar

### ISSUE THREAD

**Issue by japrogramer** [iBotPeaches/Apktool#1569]
### Information
1. **Apktool Version (`apktool -version`)** -
apktool_2.2.3.jar
2. **Operating System (Mac, Linux, Windows)** -
```
--- ~/bin » uname -r; pacman -Q linux                                                                                                                                                                                       130 ↵
4.11.9-1-ARCH
linux 4.11.9-1
--- ~/bin » java -version                                                                                                                                                                                                     1 ↵ 
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

```
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat
$apktool
Error: Invalid or corrupt jarfile /home/archangel/bin/apktool.jar

odd thin is that when i do java -cp apktool it prints out the help page but i cannot pass in arguments to apktool like this

```
unzip -lf apktool.jar | ack manifest -i
       56  2017-06-12 08:29   META-INF/MANIFEST.MF
```

**Comment by iBotPeaches** [comment]
I double checked the hashes on 2.2.3

* md5 `0662ded7b486d64a3f7424de1c29fe59`
* sha256 `8d05868a9fdef7ed43742b44f45c10a77263526b236e478cc9602d6a4e053f87`

Confirm that your binary is that. There is no problem on BitBucket or the mirror server - https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.3.jar

**Comment by japrogramer** [comment]
thanks, for whatever reason my md5 sum was different.

**Comment by KhAm7** [comment]
i have same problem root@ado:~/Downloads# md5sum apktool_2.2.3.jar
0662ded7b486d64a3f7424de1c29fe59  apktool_2.2.3.jar root@ado:~# apktool
Error: Invalid or corrupt jarfile /usr/local/bin/apktool.jar
