### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by yudongyy** [iBotPeaches/Apktool#1573]
<img width="1272" alt="default" src="https://user-images.githubusercontent.com/12558863/28754376-7d67c918-7576-11e7-9c8d-a4012952a59e.png">

**Comment by iBotPeaches** [comment]
Do you have an example application? Usually the template that you just removed, is for your benefit :)

**Comment by Droid-MAX** [comment]
![s70821-205446](https://user-images.githubusercontent.com/12762435/29520394-7b5d21a0-8646-11e7-9fdc-2a81398f55db.jpg)
![s70821-205637](https://user-images.githubusercontent.com/12762435/29520495-de32b010-8646-11e7-8cfa-c4b13ce8216d.jpg)

**Comment by Droid-MAX** [comment]
I can not get help from the error message

**Comment by iBotPeaches** [comment]
@Droid-MAX Apktool does not work on the device, it is not officially supported therefore I will not debug an issue that is being done from a device. This issue also has nothing to do with the original report.

**Comment by iBotPeaches** [comment]
Closing due to no response from original reporter in over a month. I can revisit if details provided.
