### ISSUE TITLE
Spotify Rebuilding Error

### ISSUE THREAD

**Issue by madScript01** [iBotPeaches/Apktool#1581]
### Information
1. 2.2.4
2. Linux (Kali Linux)
3. Spotify Apk from APKPure (Original Playstore Version)

### Stacktrace/Logcat

Logcat attached below

### Steps to Reproduce
1. apktool d -f -o Spotify /root/Desktop/Spotify\ Music_v8.4.9.271_apkpure.com.apk
2. apktool b Spotify -vvv

### APK

https://download.apkpure.com/b/apk/Y29tLnNwb3RpZnkubXVzaWNfMjA5NzIzMzRfNTIwNDcxZGY?_fn=U3BvdGlmeSBNdXNpY192OC40LjkuMjcxX2Fwa3B1cmUuY29tLmFwaw%3D%3D&k=fc37aa73e69ccaea35c8a49217032a155989a597&as=a394fc3c341e2bdb5043352cfeb19fe95987030f&_p=Y29tLnNwb3RpZnkubXVzaWM%3D&c=1%7CMUSIC_AND_AUDIO

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes
2. If you are trying to install a modified apk, did you resign it?
I can't rebuild it
3. Are you using the latest apktool version?
Yes, the version 2.2.4

[spotifylog.txt](https://github.com/iBotPeaches/Apktool/files/1203042/spotifylog.txt)

**Comment by iBotPeaches** [comment]
```
➜  Bug1581 apktool d com.spotify.music_v8.4.9.271-20972334_Android-4.0.3.apk 
I: Using Apktool 2.2.4 on com.spotify.music_v8.4.9.271-20972334_Android-4.0.3.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1581 apktool b com.spotify.music_v8.4.9.271-20972334_Android-4.0.3
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1581 
```

Couldn't duplicate. From your error log, there was no error. Execution simply stopped and died out. There isn't any error to look for. Perhaps execution took too long and something killed the binary from running?

**Comment by madScript01** [comment]
I don't know, I wasn't running nothing else and facebook app which tooks me more time to rebuild than the spotify one works perfectly
