### ISSUE TITLE
Smali filenames generated that easily exceed MAX_PATH

### ISSUE THREAD

**Issue by Magendanz** [iBotPeaches/Apktool#1582]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Enterprise (Build 15063)
3. **APK From? (Playstore, ROM, Other)** - Amlogic SDK 7.1

### Stacktrace/Logcat

```
See dir output of files created
```

### Steps to Reproduce
1. `apktool d services.jar`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) - Done

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

Looking through the smali files created, some of these are extremely long and include code from the beginning of the contents.

For example,
* ConnectivityService$-void__init__android_content_Context_context_android_os_INetworkManagementService_netManager_android_net#_statsService_android_net_INetworkPolicyManager_policyManager_android_net_metrics_IpConnectivityLog_logger_LambdaImpl0.smali
* AccountManagerService$-boolean_removeAccountInternal_com_android_server_accounts_AccountManagerService$UserAccounts_accounts_android_accounts_Account_account_int_callingUid_LambdaImpl0.smali
* SyncManager$-void_scheduleSync_android_accounts_Account_requestedAccount_int_userId_int_reason_java_lang_String_requestedAuthority_android_os_Bundle_extras_int_targetSyncState_long_minDelayMillis_LambdaImpl0.smali
* DreamController$DreamRecord$-void__init__com_android_server_dreams_DreamController_this$0_android_os_Binder_token_android_con#nt_ComponentName_name_boolean_isTest_boolean_canDoze_int_userId_android_os_PowerManager$WakeLock_wakeLock_LambdaImpl0.smali
* ShortcutService$LocalService$-java_util_List_getShortcuts_int_launcherUserId_java_lang_String_callingPackage_long_changedSinc#kageName_java_util_List_shortcutIds_android_content_ComponentName_componentName_int_queryFlags_int_userId_LambdaImpl0.smali

As you can see, these suckers are huge and quickly eat up the 260 characters (MAX_PATH) available in Windows to address a file.  You can't open them in Notepad or Visual Studio.  Basically, all you can do is move them to the root or delete them.
[files.txt](https://github.com/iBotPeaches/Apktool/files/1210085/files.txt)
[services.zip](https://github.com/iBotPeaches/Apktool/files/1210087/services.zip)

**Comment by iBotPeaches** [comment]
Hmm. Thought smali had something internally to handle this. Let me look into this some more.

**Comment by iBotPeaches** [comment]
Yeah, smali still has support for this https://github.com/JesusFreke/smali/blob/master/util/src/main/java/org/jf/util/ClassFileNameHandler.java

Per the comment.

```
/**
 * This class handles the complexities of translating a class name into a file name. i.e. dealing with case insensitive
 * file systems, windows reserved filenames, class names with extremely long package/class elements, etc.
 *
 * The types of transformations this class does include:
 * - append a '#123' style numeric suffix if 2 physical representations collide
 * - replace some number of characters in the middle with a '#' character name if an individual path element is too long
 * - append a '#' if an individual path element would otherwise be considered a reserved filename
 */
```

I don't have access to a Windows machine right now, so obviously can't test at the moment, but code says this shouldn't be a problem.

**Comment by iBotPeaches** [comment]
```
C:\Users\Connor\Desktop\bin>java -jar apktool.jar d services.jar
I: Using Apktool 2.2.4 on services.jar
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
C:\Users\Connor\Desktop\bin>java -jar apktool.jar b services.jar.out
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
W: Could not find resources
I: Building apk file...
I: Copying unknown files/dir...
C:\Users\Connor\Desktop\bin>
```

I also edited these long files in Notepad without a problem. My directory tree wasn't anything special. It went `Users\Connor\Desktop\bin`. Additionally the files you provided are at 249 characters so smali's workaround did not occur. I don't see a problem here as the limit code is introduced at 250 characters. These files stop at 249.

**Comment by Magendanz** [comment]
So, you're saying it's by design to include all this junk in the smali filename?  And the "fix" is to just move them closer to the root?

Note: The problem is not as much with the ClassFileNameHandler, but with the synthetic class name generation.  If you look at the contents of these files (which may require moving them file closer to the root), they all start with ".class final synthetic".

**Comment by iBotPeaches** [comment]
The smali filename is by generation the class name of the file, except when the filename conflicts with the rules in place by ClassFileNameHandler.

```
.class final synthetic Lcom/android/server/ConnectivityService$-void__init__android_content_Context_context_android_os_INetworkManagementService_netManager_android_net_INetworkStatsService_statsService_android_net_INetworkPolicyManager_policyManager_android_net_metrics_IpConnectivityLog_logger_LambdaImpl0;
.super Ljava/lang/Object;
.source "ConnectivityService.java"
```
That is the header of a file. The class is that massive name therefore the filename is. If the naming is invalid that would be something I would bring up with the smali project - https://github.com/JesusFreke/smali/issues as Apktool leverages smali as a dependency to handle this.

**Comment by Magendanz** [comment]
Also, while Java seems to handle the long paths and the apktool build does succeed, I can't open these files in the file explorer by double-clicking them, even when just on my desktop (C:\Users\Chad\Desktop).  For that, I've got to move them closer to the root.

More importantly, I can't edit them in Visual Studio 2017 or search their contents using Find in Files.

**Comment by Magendanz** [comment]
Okay, I opened a related issue there:  https://github.com/JesusFreke/smali/issues/541

**Comment by eladkarako** [comment]
workarounds. for Windows users. if you are interested...

short the apk as much as possible and place the apk as low as possible (`D:\APKs\`).
switch to oracle java 17, grab the portable version from archive, modify yourself (patch) the exe and dll files everywhere so their manifest would include long path awareness.
https://github.com/eladkarako/manifest/blob/master/example_manifests/generic.manifest#L13

there are some batch files for easy drag and drop here https://github.com/eladkarako/manifest  
Win10 needs a reg-patch to opt-in this feature, Win11 has it turned on already.

I'm not explaining 1-to-1 what to do. but as long you are working on a separate folder and afterwards changing the JAVA_HOME, (etc..) environment variables, you'll be fine, maximum length will be about 32k characters. and on some cases pretty much unlimited (and MAX_PATH will be ignored by all the file API).

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html
