### ISSUE TITLE
what should i do to solve this ?

### ISSUE THREAD

**Issue by anilyadav851996** [iBotPeaches/Apktool#1585]
brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 10, --target-sdk-version, 21, --version-code, 20, --version-name, 1.2.11, --no-version-vectors, -F, /data/data/per.pqy.apktool/APKTOOL6364707453993546091.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/backups/apps/Internet123_src/res, -M, /storage/emulated/0/backups/apps/Internet123_src/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
There is no error here. Only the failure. Please follow the issue template (including full stacktrace & apk if possible).

That issue template ensures I don't have to spend time asking 10 questions. Emptying it out and putting a small part of the exception does not help anyone.
