### ISSUE TITLE
Apktool needlessly complains about non-writable home directory

### ISSUE THREAD

**Issue by sfzhi** [iBotPeaches/Apktool#1586]
### Information
1. **Apktool Version** - 2.2.4, the same issue exists in master.
2. **Operating System** - Linux
3. **APK From?** - N/A

### Apktool Output

```
S: WARNING: Could not write to $HOME (/home/user), using /tmp instead...
```

### Steps to Reproduce
1. Run apktool when the home directory is not writable, but `$HOME/.local/share/apktool` is.

Apktool here is assuming too much. It wants to use the directory `$HOME/.local/share/apktool/framework`, so it should do just that and not poke around in other places. It should complain only when **that** directory is not writable, or doesn't exist and cannot be created.

By the way, it also complains when `framework` is a file, which makes sense, but is not entirely correct. On many OS (such as Linux and UNIX) there are other types of directory entries than file and directory, so the check `isFile()` would better be replaced with `!isDirectory()`.

**Comment by iBotPeaches** [comment]
You are welcome to create a pull request if you believe the detection of an invalid file/pointer in the framework folder location could be enhanced.

As for the first issue. I will run some tests, but seems like I just need to update the error message.

**Comment by iBotPeaches** [comment]
Pull request in (pending review). I adapted the checks to only check the location that Apktool will use.

**Comment by Giszmo** [comment]
Using Apktool 2.4.1 I now get `Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: /var/lib/tomcat8/.local/share/apktool/framework` and it does not fall back to `/tmp/`.
