### ISSUE TITLE
Android Oreo Changes

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#1594]
- [x] [Wide Color Gamut & HDR](https://github.com/android/platform_frameworks_base/commit/c9ba55902123be5abcf2dcda5af9995be0b8d3d8)
- [x] [VR Headset Qualifiers](https://github.com/android/platform_frameworks_base/commit/1a6acdbb86c3e72bdb0a4dcab3bda58cbc4ea34c)
- [x] [Font Support](https://github.com/android/platform_frameworks_base/commit/9bbe787822502e8c09d9abe963e6539647bea346)
- [x] Upgrade AAPT to `android-8.0.0_r4`
- [x] [Add support for ResTable_sparseTypeEntry](https://github.com/android/platform_frameworks_base/commit/c8f71aa67ea599cb80205496cb67e9e7a121299c)
- [x] Update tests

The reserved `res0` & `res1` got tweaked in favor of some spare entry

```
   enum {
        // If set, the entry is sparse, and encodes both the entry ID and offset into each entry,
        // and a binary search is used to find the key. Only available on platforms >= O.
        // Mark any types that use this with a v26 qualifier to prevent runtime issues on older
        // platforms.
        FLAG_SPARSE = 0x01,
    };
    uint8_t flags;

    // Must be 0.
uint16_t reserved;
```
Color Gamut cleaned up - https://github.com/android/platform_frameworks_base/commit/e84ad491c82168228f042644285a2581fc619baf

**Comment by iBotPeaches** [comment]
I have upgraded our flavored version of AAPT to (`android_8.0.0_r4`), all patches applied - https://github.com/iBotPeaches/platform_frameworks_base/tree/apktool_8.0.0

Will work on builds of aapt and then onward to Apktool qualifier changes.

**Comment by iBotPeaches** [comment]
Linux (32/64) aapt builds are working fine. After confirmed working with our manual patches and new qualifiers, I will build Windows/Mac versions.

**Comment by iBotPeaches** [comment]
Initial commit(s) + support for mac os x. A few more platforms to add and a bunch more tests. It seems if you request qualifier `vrheadset`, aapt knows that won't be used in less than API 26, so it drops it.

If you include the -v26 qualifier, it passes. Note this is all moot in Android Studio, because it does it behind the scene implicitly versioning things via aapt.

**Comment by iBotPeaches** [comment]
Linux is failing due to libc++ no longer being static compiled. Time to dig into the mess of AOSP to figure out why this is the case.

**Comment by iBotPeaches** [comment]
Okay with those commits, everything should be fixed. Just some testing to do.

**Comment by freegraphy** [comment]
The attached APK fails with the decode and Build. 
It works well in Windows environments, but in the linux environment, it fails. 
Perhaps it is a problem with APPT, which is prebuilted in APPTOOL. 
Can you tell me why it fails? 
If you have any issues with the issue, we would appreciate it if you would let us know if the patches were due.

APK : hearthstone.apk

The execution command is shown below.

Decode : 
java -jar /home/ether/apktool_2.2.4.jar d -m --keep-broken-res -f ./hearthstone.apk -o ./hearthstone.apk_smali -p /apktool/framework/android-24

Build : 
java -jar /home/ether/apktool_2.2.4.jar b ./hearthstone.apk_smali -o ./repack_hearthstone.apk -p /apktool/framework/android-24

**Comment by remenyo** [comment]
Is 32bit support ended?
