### ISSUE TITLE
[minor][Windows] output with Unicode support

### ISSUE THREAD

**Issue by eladkarako** [iBotPeaches/Apktool#1595]
apktool.bat

from:
```cmd
java "-Duser.language=en" -jar "%~dp0\apktool.jar" %*
```
<img src="https://i.imgur.com/OrBSgKq.png"/>

to:

```cmd
chcp 65001 2>nul >nul
java "-Duser.language=en" -jar "%~dp0\apktool.jar" %*
```
<img src="http://i.imgur.com/5ofNJ9t.png"/>

it will allow Unicode characters to be shown correctly across the entire run of the tool (not just for the author's name part..

<em>Ps. optionally add <code>-Dfile.encoding=UTF8</code> for Java output-pipe.</em>

**Comment by iBotPeaches** [comment]
Thanks! I'll give this a test when I'm in front of my Windows computer and get this added.
