### ISSUE TITLE
Hi I'm having issues and apktool has tones of exceptions!

### ISSUE THREAD

**Issue by mattwhite43214** [iBotPeaches/Apktool#1603]
Hi, I have a Vodafone smart first 7 and I'm trying to get rid of that annoying carrier name but when I try and recompile my systemui apk it throws lots of exceptions about brut.android.exception.blah blah blah and I would include a stack trace but I'm not on my laptop currently and also I use windows 10 so I don't think I can do one, I can't link any .apk files and the picture I took to show the error

**Comment by iBotPeaches** [comment]
I don't see an image or stacktrace or apk :(

In the future, please keep the template of an issue report. It allows me to find all the information I need to diagnose a ticket. Will reopen if more information provided.

**Comment by mattwhite43214** [comment]
How do you capture a stack trace and how do I attach the folder in trying to recompile, sorry I don't have a lot of experience in the java world
