### ISSUE TITLE
!!brut.androlib.meta.MetaInfo in apktool.yml breaks yaml parsing

### ISSUE THREAD

**Issue by amarekano** [iBotPeaches/Apktool#1610]
Hi, is there a reason why '!!brut.androlib.meta.MetaInfo' is being added to apktool.yml? I'm not sure if this is a bug or an intended feature. I've noticed this in v2.2.4 to v2.2.1

This isn't an issue with apktool v2.0.3

### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4, 2.2.3 and 2.2.1
2. **Operating System (Mac, Linux, Windows)** - Tested this on Linux and Windows
3. **APK From? (Playstore, ROM, Other)** - Any valid APK

### Steps to Reproduce
1. `apktool d somefile.apk`
2. inspect the first line in someapk/apktool.yml

**Comment by iBotPeaches** [comment]
Yes, so we can implement v2 of the MetaInfo without breaking backward compatibility.
