### ISSUE TITLE
After recompile, only black screen.

### ISSUE THREAD

**Issue by NeutrinoBR** [iBotPeaches/Apktool#1613]
### Information
1. **Apktool Version (2.2.4)** -
2. **Operating System (Ubuntu 16.04.3)** -
3. **APK From? (MI Store & PlayStore)** -

### Stacktrace/Logcat

```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
```

OR

```
LogCat
[2017-09-11-17-57-09.txt](https://github.com/iBotPeaches/Apktool/files/1294042/2017-09-11-17-57-09.txt)

```

### Steps to Reproduce
1. `apktool b com.fimi.soul`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
```
09-11 17:56:26.274 I/ActivityManager(1444): Start proc 10569:com.fimi.soul/u0a209 for activity com.fimi.soul/.module.login.LaunchedActivity
09-11 17:56:26.276 D/CompatibilityInfo(1444): mCompatibilityFlags - 0
09-11 17:56:26.276 D/CompatibilityInfo(1444): applicationDensity - 420
09-11 17:56:26.276 D/CompatibilityInfo(1444): applicationScale - 1.0
09-11 17:56:26.278 D/CompatibilityInfo(1444): mCompatibilityFlags - 0
09-11 17:56:26.278 D/CompatibilityInfo(1444): applicationDensity - 420
09-11 17:56:26.278 D/CompatibilityInfo(1444): applicationScale - 1.0
09-11 17:56:26.377 D/EmbryoManager(1444): prepare com.fimi.soul
09-11 17:56:26.377 I/ActivityManager(1444): Process com.fimi.soul (pid 10569) has died
```

Not sure. Didn't find anything in logcat to point at anything.

**Comment by NeutrinoBR** [comment]
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.

I do not know either. Do you need more information?

**Comment by iBotPeaches** [comment]
The APK and the frameworks for my own detailed investigation is probably the only thing left.

**Comment by NeutrinoBR** [comment]
APK: http://mu.dadf.eng.br/com.fimi.soul.apk

I'm not using any framework. because it is not an OEM apk of the system.

**Comment by NeutrinoBR** [comment]
The application has an obfuscator.
Anyway thank you.
