### ISSUE TITLE
Unfortunally App has stopped

### ISSUE THREAD

**Issue by izidro2928** [iBotPeaches/Apktool#1614]
### Information
1. **Apktool Version (latest version)** -
2. **Operating System (Windows and linux)** -
3. **APK From? (Cartoon hd apk)** -

I have no erros while decoding and rebuilding...
When i install the app it says that has stopped.

I already tried other app like terrarium tv and it works fine.

Just some apps say that have stopped.

**Comment by iBotPeaches** [comment]
Probably need a logcat `adb logcat` to do anything further with this ticket.

**Comment by izidro2928** [comment]
I know why is crashing! Because i delete the ads folder It crashes only when I delete the ads folder from smali/com/google/ ads and olso google/android/gms/ads. But I don't know what to do. Any help?

**Comment by iBotPeaches** [comment]
Unfortunately just deleting things and hoping an application will work isn't exactly a full proof method. Since this is a support question more so than a bug in apktool. I am going to close this. Your best bet may be XDA or some forum.
