### ISSUE TITLE
Unable to fully decompile Google Play Services (com.google.android.gms)

### ISSUE THREAD

**Issue by Jayrod76** [iBotPeaches/Apktool#1619]
### Information
1. **Apktool Version (`apktool -version`)** - Any
2. **Operating System (Mac, Linux, Windows)** -Any
3. **APK From? (Playstore, ROM, Other)** PlayStore_Device_APKMirror-

Since Version 10.0.84 (now at 11.5.09 on my device)  APKTool does not decompile the Layouts/Values (colors,Styles,etc)/Drawables of any kind/Color...etc . This is well known through the theming community but I haven't seen any type of documentation of these issues so Im not even sure if you were aware of this.

**Comment by daveyannihilation** [comment]
To add to what JayRod has written, here is a log of the problem:

https://hastebin.com/uwokupalez.cs

Notice that the package name gets renamed to FFFFFFFFFFFFFFFFFFF right at the end?

After the decompilation finishes, the only folders in /res are the values folders, and they all only have their appropriate strings.xml and then the main values folder also has public.xml in it.

Looking into the Google Play Services apk, it has a resources.arsc file in the root of it which is quite small (roughly 2mb) compared to most other resources.arsc files. 
![photo5634419797664049065](https://user-images.githubusercontent.com/4631055/30769035-c9b3cf2c-a043-11e7-9f30-ee16cfddf8cd.jpg)

Then looking into the /assets folder, it has another AndroidManifest.xml and also a metaresources.arsc which is about 13mb (about the size of what you would expect from a normal resources.arsc file).
![photo5634419797664049066](https://user-images.githubusercontent.com/4631055/30769041-d2a5ba14-a043-11e7-82f4-e91a757bb6ca.jpg)

**Comment by iBotPeaches** [comment]
Sorry, 3+ years later. I didn't look and now I have no chance.

Closing.
