### ISSUE TITLE
Apktool does not work if jre folder is renamed

### ISSUE THREAD

**Issue by bhuga123** [iBotPeaches/Apktool#1624]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Device Alcatel One toruch

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. I tried to decode framework APK from one of my test devices and found the below error:

 C:\Users\BGADKAR1\apktool>apktool decode framework-res.apk
Error: could not open `C:\Program Files\Java\jre1.8.0_144\lib\amd64\jvm.cfg'

I guess this might be due to the renaming of the java folders jdk and jre names. I had renamed the jre folder from 'jre1.8.0_144' to just 'jre'. I need the jre folder to be named as 'jre' for running appium related stuff 

After I changed it back to jre1.8.0_144 apktool works correctly:
C:\Users\BGADKAR1\apktool>apktool decode framework-res.apk
I: Using Apktool 2.3.0 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

### Frameworks
If this APK is from an OEM RO
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/1330441/framework-res.zip)
M (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes. Without changing the jre folder names then it works good.
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
This is an environment issue. Apktool has no responsibility for what happens when you start renaming Java folders.
