### ISSUE TITLE
Badly needed clarification regarding Apktool v2.3.0... 

### ISSUE THREAD

**Issue by ibuprophen1** [iBotPeaches/Apktool#1631]
Hello There! 

I just wanted to provide a copy of the post i had made on your xda-developers Forum Thread here just for posterity. 

The Information from the following thread is as follows:
https://forum.xda-developers.com/showpost.php?p=73979293&postcount=5060

I, as well as many other members, are in need (very badly) of a clarification regarding the mixed message on your Apktool v2.3.0 release. 

According to the v2.3.0 Changelog (taken from [url]https://connortumbleson.com/2017/09/21/apktool-v2-3-0-released/[/url]), it does state "Dropped support for all 32 bit binaries, except Windows."

Your post (i had quoted above), that was made prior to the v2.3.0 release, states something that reads much broader and a bit contradictory from what's reflected on the Changelog. 

Separately, I understand them both completely but, together, I really could use more clarification. 

I use Windows 8.1 Professional x64 (64-Bit) and I'm having some "Apktool Errors" with the v2.3.0 that I don't experience on the previous release. This error is being reflected on 3 different types of software that has been leading me to the Apktool itself but, I can't rule anything in or out as the culprit without additional information/clarification which will help point the way to one or the other or even both.  

I'm still trying to figure this out in my PC. I'm thinking that I may have to create a directory in my "C:\Program Files" for the software since that's the typical installation directory used for the x64 (64-Bit) software. 

In addition, I've seen this confusion posted on various threads with half the responses pointing to your post (above) and the other half pointing to your Changelog and, after so long, I wasn't sure which was which. 

It would be GREAT if you could provide a bottom line clarification that would clear this whole (very crazy) ordeal up. 

Thank you so much for your time, patience and understanding with this! 

~Ibuprophen 
(xda-developers Forum)

**Comment by iBotPeaches** [comment]
Lets talk on XDA. I responded fairly quickly to that thread. We don't need to track this in two places.

**Comment by ibuprophen1** [comment]
My apologies on the Delay and will do...

Thank you very much!
