### ISSUE TITLE
Apktool error on recompiling any apk on arm64(armhf) kali nethunter

### ISSUE THREAD

**Issue by lightakun** [iBotPeaches/Apktool#1633]
Apktool
Version:2.2.2
Device Leeco LeTv Le2 
Software:Android 6.0.1 with kali nethunter(armhf) arm64

I have all dependencies installed for apktool and it successfully decompiles any apk by "apktool d apk.apk"
But when i try to recompile it by "apktool b apk" it gives me error on every apk i tried
https://imgur.com/a/xXbQT

Please look into this problem
eagerly waiting for ur reply @iBotPeaches
....
:)

**Comment by iBotPeaches** [comment]
Apktool is not supported on Android. There is no ARM support for the aapt binary, hence why you are getting that cryptic error.

When apktool is supported on Android, the docs and project page will reflect that. Sorry.

**Comment by lightakun** [comment]
@iBotPeaches thats ok...
eagerly waiting for android release of apktool! :)

**Comment by Dorabot2222** [comment]
I am running this on a proot distro still same error it does not matter what i am using it in it does not work
