### ISSUE TITLE
[Fatal Error] :1:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by WilsonCP** [iBotPeaches/Apktool#1634]
### Information
1. **Apktool Version (`apktool -version`)** - **2.3.0**
2. **Operating System (Mac, Linux, Windows)** - **Linux**
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
apktool b framework-res
I: Using Apktool 2.3.0
W: Could not find sources
[Fatal Error] :1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...

```

### Steps to Reproduce
1. `apktool b frameword-res `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **YES**
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? **YES**

Hi, I've pasted above the message I'm getting when building framework-res folder. On Decompiling, I have no problem whatsoever. The only change I did with the folder is changing default_wallpaper and nothing else. Hope you could help me with this.

By the way, Thanks for this awesome project.

**Comment by iBotPeaches** [comment]
Seems like the build completed, what commands did you use for the decode? It seems the decoding of the resources was skipped or a binary manifest was provided, hence why it threw that strange error.

**Comment by WilsonCP** [comment]
> apktool d framwork-res.apk

Yeah, but after the building I dont get updated apk.

**Comment by iBotPeaches** [comment]
Hmm. I still can't replicate this. Since no apk provided I just tried a random set of applications and never got that warning with those steps.

Any ideas?

**Comment by WilsonCP** [comment]
Sorry If I can't provide the exact framework-res.apk

Right now, I was able to recompile it, dunno what I did, but it worked, the problem is (maybe this should be a different issue), my device is stucked at boot screen when I put the edited framework-res.apk, again, I've only changed the default_wallpaper.jpg.

Thanks man for the response

**Comment by iBotPeaches** [comment]
Devices stuck at boot screen point to a different issue. Usually the `log-cat` will have more information for this. It could be anything from a missing signature or wrong key, system rejected, etc.

I am going to confirm this for the warning "Prolog" error, which has nothing to do with your error.
