### ISSUE TITLE
Build is missing from 2.3.0 release 

### ISSUE THREAD

**Issue by brendonjohn** [iBotPeaches/Apktool#1637]
[Apktool-2.3.0.zip](https://github.com/iBotPeaches/Apktool/files/1377325/Apktool-2.3.0.zip)

> Here's one I prepared earlier

I built this from the source download provided on the release page. To build I just ran ./gradlew on MacOS.

**Comment by iBotPeaches** [comment]
Thanks! Release updated - https://github.com/iBotPeaches/Apktool/releases/tag/v2.3.0

I guess my script failed to deploy that version. Confirmed MD5 matches, valid binary released.

**Comment by brendonjohn** [comment]
Thanks mate!
