### ISSUE TITLE
Regression: if frame-path does not exist

### ISSUE THREAD

**Issue by janvidar** [iBotPeaches/Apktool#1639]
https://github.com/iBotPeaches/Apktool/blob/3ec4f360ab09782421e47d16f88a95dd7f7d2058/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java#L793

Ten lines further down the directory is created if it does not exist already.

**Comment by iBotPeaches** [comment]
Thanks, good catch. Need to adapt my unit-tests to catch this in the future.
