### ISSUE TITLE
Throw exception instead of calling System.exit() in library code

### ISSUE THREAD

**Issue by janvidar** [iBotPeaches/Apktool#1640]
These does not belong here - and prevents Androlib from being used as a library.
An exception should be thrown instead in the following two places:

https://github.com/iBotPeaches/Apktool/blob/3ec4f360ab09782421e47d16f88a95dd7f7d2058/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java#L795

https://github.com/iBotPeaches/Apktool/blob/3ec4f360ab09782421e47d16f88a95dd7f7d2058/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java#L795

**Comment by iBotPeaches** [comment]
Confirmed. Thanks for report.
