### ISSUE TITLE
APK Tool 2.3.0 Not Working

### ISSUE THREAD

**Issue by sirsendu** [iBotPeaches/Apktool#1643]
I tried `apktool d`, `apktool b` without changing anything. And it gives me parse error while installing to Android device. The message "There was a problem parsing the package".

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to try and provide any logcat and/or stacktrace possible. I can reopen this if details are provided.
