### ISSUE TITLE
I tried `apktool d`, `apktool b` without changing anything

### ISSUE THREAD

**Issue by dvash01** [iBotPeaches/Apktool#1648]
### Information
1. **Apktool Version (`apktool -version`)** -2.3
2. **Operating System (Mac, Linux, Windows)** -Windows 7
3. **APK From? (Playstore, ROM, Other)** -ROM

### Stacktrace/Logcat
I did this in SystemUI
For Samsung S6310

Include stack trace 

[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/1424982/SystemUI.zip)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/1424983/framework-res.zip)

here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes
thanks
dvash01@gmail.com

**Comment by dvash01** [comment]
this is the log

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\משרד\Desktop\apktool>apktool b SystemUI
I: Using Apktool 2.3.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'abbrev_wday_abbrev_month_day_no_year' has n
tion.
W: warning: string 'abbrev_wday_day_abbrev_month_no_year' has n
tion.
W: warning: string 'abbrev_wday_month_day_no_year' has no defau
W: warning: string 'abbrev_wday_month_day_year' has no default
W: warning: string 'am' has no default translation.
W: warning: string 'day_of_week_long_friday' has no default tra
W: warning: string 'day_of_week_long_monday' has no default tra
W: warning: string 'day_of_week_long_saturday' has no default t
W: warning: string 'day_of_week_long_sunday' has no default tra
W: warning: string 'day_of_week_long_thursday' has no default t
W: warning: string 'day_of_week_long_tuesday' has no default tr
W: warning: string 'day_of_week_long_wednesday' has no default
W: warning: string 'day_of_week_medium_friday' has no default t
W: warning: string 'day_of_week_medium_monday' has no default t
W: warning: string 'day_of_week_medium_saturday' has no default
W: warning: string 'day_of_week_medium_sunday' has no default t
W: warning: string 'day_of_week_medium_thursday' has no default
W: warning: string 'day_of_week_medium_tuesday' has no default
W: warning: string 'day_of_week_medium_wednesday' has no defaul
W: warning: string 'day_of_week_short_friday' has no default tr
W: warning: string 'day_of_week_short_monday' has no default tr
W: warning: string 'day_of_week_short_saturday' has no default
W: warning: string 'day_of_week_short_sunday' has no default tr
W: warning: string 'day_of_week_short_thursday' has no default
W: warning: string 'day_of_week_short_tuesday' has no default t
W: warning: string 'day_of_week_short_wednesday' has no default
W: warning: string 'day_of_week_shortest_friday' has no default
W: warning: string 'day_of_week_shortest_monday' has no default
W: warning: string 'day_of_week_shortest_saturday' has no defau
W: warning: string 'day_of_week_shortest_sunday' has no default
W: warning: string 'day_of_week_shortest_thursday' has no defau
W: warning: string 'day_of_week_shortest_tuesday' has no defaul
W: warning: string 'day_of_week_shortest_wednesday' has no defa
W: warning: string 'full_wday_month_day_no_year' has no default
W: warning: string 'month_long_april' has no default translatio
W: warning: string 'month_long_august' has no default translati
W: warning: string 'month_long_december' has no default transla
W: warning: string 'month_long_february' has no default transla
W: warning: string 'month_long_january' has no default translat
W: warning: string 'month_long_july' has no default translation
W: warning: string 'month_long_june' has no default translation
W: warning: string 'month_long_march' has no default translatio
W: warning: string 'month_long_may' has no default translation.
W: warning: string 'month_long_november' has no default transla
W: warning: string 'month_long_october' has no default translat
W: warning: string 'month_long_september' has no default transl
W: warning: string 'month_long_standalone_april' has no default
W: warning: string 'month_long_standalone_august' has no defaul
W: warning: string 'month_long_standalone_december' has no defa
W: warning: string 'month_long_standalone_february' has no defa
W: warning: string 'month_long_standalone_january' has no defau
W: warning: string 'month_long_standalone_july' has no default
W: warning: string 'month_long_standalone_june' has no default
W: warning: string 'month_long_standalone_march' has no default
W: warning: string 'month_long_standalone_may' has no default t
W: warning: string 'month_long_standalone_november' has no defa
W: warning: string 'month_long_standalone_october' has no defau
W: warning: string 'month_long_standalone_september' has no def

W: warning: string 'month_medium_april' has no default translat
W: warning: string 'month_medium_august' has no default transla
W: warning: string 'month_medium_december' has no default trans
W: warning: string 'month_medium_february' has no default trans
W: warning: string 'month_medium_january' has no default transl
W: warning: string 'month_medium_july' has no default translati
W: warning: string 'month_medium_june' has no default translati
W: warning: string 'month_medium_march' has no default translat
W: warning: string 'month_medium_may' has no default translatio
Exception in thread "main" W: warning: string 'month_medium_nov
ault translation.
W: warning: string 'month_medium_october' has no default transl
brut.androlib.AndrolibException: brut.androlib.AndrolibExceptio
utException: could not exec (exit code = 1): [C:\Users\A4B8~1\A
\brut_util_Jar_4579273775422926312.tmp, p, --min-sdk-version, 1
ersion, 16, --version-code, 16, --version-name, 4.1.2-S6310TDVA
-vectors, -F, C:\Users\A4B8~1\AppData\Local\Temp\APKTOOL3020633
 -0, resources.arsc, -0, arsc, -I, C:\Users\משרד\AppData\Local\
\1.apk, -S, C:\Users\משרד\Desktop\apktool\SystemUI\res, -M, C:\
p\apktool\SystemUI\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.j
        at brut.androlib.Androlib.buildResources(Androlib.java:
        at brut.androlib.Androlib.build(Androlib.java:318)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutExc
 exec (exit code = 1): [C:\Users\A4B8~1\AppData\Local\Temp\brut
775422926312.tmp, p, --min-sdk-version, 16, --target-sdk-versio
code, 16, --version-name, 4.1.2-S6310TDVAMD4, --no-version-vect
\A4B8~1\AppData\Local\Temp\APKTOOL3020633775473452799.tmp, -0,
0, arsc, -I, C:\Users\משרד\AppData\Local\apktool\framework\1.ap
שרד\Desktop\apktool\SystemUI\res, -M, C:\Users\משרד\Desktop\apk
roidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(Andr
a:454)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.j
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code
A4B8~1\AppData\Local\Temp\brut_util_Jar_4579273775422926312.tmp
rsion, 16, --target-sdk-version, 16, --version-code, 16, --vers
6310TDVAMD4, --no-version-vectors, -F, C:\Users\A4B8~1\AppData\
L3020633775473452799.tmp, -0, resources.arsc, -0, arsc, -I, C:\
a\Local\apktool\framework\1.apk, -S, C:\Users\משרד\Desktop\apkt
 -M, C:\Users\משרד\Desktop\apktool\SystemUI\AndroidManifest.xml
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(Andr
a:448)
        ... 6 more
W: warning: string 'month_medium_september' has no default tran
W: warning: string 'month_shortest_april' has no default transl
W: warning: string 'month_shortest_august' has no default trans
W: warning: string 'month_shortest_december' has no default tra
W: warning: string 'month_shortest_february' has no default tra
W: warning: string 'month_shortest_january' has no default tran
W: warning: string 'month_shortest_july' has no default transla
W: warning: string 'month_shortest_june' has no default transla
W: warning: string 'month_shortest_march' has no default transl
W: warning: string 'month_shortest_may' has no default translat
W: warning: string 'month_shortest_november' has no default tra
W: warning: string 'month_shortest_october' has no default tran
W: warning: string 'month_shortest_september' has no default tr
W: warning: string 'pm' has no default translation.
W: warning: string 'quickpanel_data_roaming_disable_toast' has
ation.
W: warning: string 'quickpanel_data_roaming_enable_toast' has n
tion.
W: warning: string 'today' has no default translation.
W: warning: string 'tomorrow' has no default translation.
W: warning: string 'twelve_hour_time_format' has no default tra
W: warning: string 'yesterday' has no default translation.
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
el_title.xml:14: error: Error: No resource found that matches t
 'style' with value '@style/StatusBarNotificationText').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
el_title.xml:19: error: Error: No resource found that matches t
 'style' with value '@style/StatusBarNotificationText').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
el_title.xml:21: error: Error: No resource found that matches t
 'style' with value '@style/StatusBarNotificationText').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:5: error: Error: No resource found that matches the given nam
h value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:6: error: Error: No resource found that matches the given nam
h value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:7: error: Error: No resource found that matches the given nam
h value '@style/StatusBarPanelSettingsContents').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:10: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:11: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:12: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:13: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsContents').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:15: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:16: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:17: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:18: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsContents').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:21: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:22: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:23: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:26: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:27: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:28: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:29: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsContents').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:32: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:33: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsRow').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:34: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsIcon').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:35: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsContents').
W:
W: C:\Users\ε∙°π\Desktop\apktool\SystemUI\res\layout\system_bar
l:37: error: Error: No resource found that matches the given na
th value '@style/StatusBarPanelSettingsPanelSeparator').
W:

C:\Users\משרד\Desktop\apktool>

**Comment by iBotPeaches** [comment]
Sorry for the delay.

This APK doesn't make much sense at all. Usually the resource files in `drawable/*.xml` are AXML, so we can decode them into human readable XML.

However, take for example this file

```
➜  1648 aapt d xmltree SystemUI.apk res/drawable/tw_ic_sysbar_back.xml
W/ResourceType(17207): Bad XML block: header size 28024 or total size 1702240364 is larger than data size 289
ERROR: Resource res/drawable/tw_ic_sysbar_back.xml is corrupt
```

The decode failed. So I extracted that file to take a look.

```
<?xml version="1.0" encoding="utf-8"?>
<selector
  xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true" android:drawable="@drawable/tw_ic_sysbar_app_press" />
    <item android:drawable="@drawable/tw_ic_sysbar_app_normal" />
</selector>
```

Plain human readable XML in the compiled application. There is no way this is valid at all and not sure Apktool can even do anything about this.
