### ISSUE TITLE
[Question Need Help] | Renamed manifest package found!

### ISSUE THREAD

**Issue by dannyZhou** [iBotPeaches/Apktool#1651]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
No error.
```
 
### Output when apktool d 

```
I: Using Apktool 2.3.0 on lh1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/danny/.local/share/apktool/framework/1.apk
I: Renamed manifest package found! Replacing com.***.x1 with com.***
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

### Question

I don't know why the line `Renamed manifest package found`

How can we write a demo apk to reproduce `Renamed manifest package found` when `apktool d demo.apk` using Android Studio ? 

OR

How to change a compiled apk to reproduce `Renamed manifest package found` when `apktool d demo.apk`?

Who can help me?

**Comment by iBotPeaches** [comment]
I don't understand. Renaming the package is required when a renamed manifest is discovered during decode. Failure to fix the Manifest prevents a rebuild.

**Comment by dannyZhou** [comment]
Not a question. Sorry.

My English is poor...... :sob: :sob: :sob:
