### ISSUE TITLE
Feature Request: only extract/build AndroidManifest.xml

### ISSUE THREAD

**Issue by nioncode** [iBotPeaches/Apktool#1658]
Is it possible to only extract the plaintext `AndroidManifest.xml` from an apk and, after I did some modifications to it, only package the modified AndroidManifest.xml back into the apk?

I'm using apktool in an automated environment for many apps, and going through the full `apktool d` - modify - `apktool b` cycle takes a long time.

Does the way resources are packed even allow something like this?

**Comment by iBotPeaches** [comment]
Unfortunately they are not. An `AndroidManifest.xml` might have framework references or even local references (`resources.arsc`) which makes this feature not possible.
