### ISSUE TITLE
decompile, recompile with no edits not reproducing original

### ISSUE THREAD

**Issue by kalemeister** [iBotPeaches/Apktool#1661]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

Decompiled, recompiled apk installs but crashes immediately after starting.
Decompiled, recompiled, signed, aligned apk file size differs from original.
No errors occur during decompile and recompile.

I tried doing the same thing on a different random apk (random game apk I downloaded) and decompiled, recompiled, signed, aligned apk file size is the same, game starts and plays without error.

`apktool empty-framework-dir --force`
was also tried as was discussed in a different issue thread:
https://github.com/iBotPeaches/Apktool/issues/1655

### Steps to Reproduce
1. *rename downloaded apk to 'hikari.apk'
2. `apktool d hikari.apk`
3. `apktool b hikari -o hikaritest.apk`
4. sign hikaritest.apk
5. zipalign hikaritest.apk

### APK
https://apkpure.com/%E3%81%B2%E3%81%8B%E3%82%8A%EF%BD%94%EF%BD%96%E3%81%A9%E3%81%93%E3%81%A7%E3%82%82/jp.co.plala.Dokodemo/download/333-APK?from=details%2Fversion

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **yes**
2. If you are trying to install a modified apk, did you resign it? **yes**
3. Are you using the latest apktool version? **yes**

**Comment by kalemeister** [comment]
I think I narrowed this down to baksmali/smali not working properly with this apk. I tried baksmali and smali on the classes.dex and after smali the new classes.dex isn't the same (when doing no edits to smali files at all). The classes.dex was the same for the other random game apk. So I guess I should raise this at the baksmali/smali project page?

**Comment by iBotPeaches** [comment]
> I tried doing the same thing on a different random apk (random game apk I downloaded) and decompiled

Just for clarification. APKs are vastly different. One application might have anti-tampering code or any hundred combinations of code able to detect modifications. So changing applications and confirming no issue is not proof :) 

The best thing to do here is to capture the `adb logcat` of the application crashing and look for the real error in the logcat. This might give us more details as to what went wrong. Might be a simple signing issue or a more complicated problem with making an intended private resource public.

**Comment by iBotPeaches** [comment]
Closing as no response in 3+ years.
