### ISSUE TITLE
Facebook fails to repack properly (failing to load language packs at runtime)

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1669]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64
3. **APK From? (Playstore, ROM, Other)** - Play store (retrieved via adb pull)

### Steps to Reproduce
1. `apktool ` d -s fb.apk -o unpacked
1.5. Open unpacked/res/values/styles.xml and delete line 11418 (duplicate resource property). This is a workaround for a known apktool issue, without which the resources will not rebuild properly.
2. `apktool ` b unpacked -o repacked.apk
3. Sign and install repacked.apk
4. Launch repacked.apk and notice that the UI controls on the login screen are all missing their captions. This is accompanied in logcat messages relating to locales. Upon login, the following message is seen in logcat, if this helps: 
fb4a.X.K1m: X.0Xx: No QT files found for build 81374859 and locale en and user <blah blah blah>

NOTE: Passing the -r option to apktool when decoding will effectively work around this, but prevents me from editing resources. 

### APK
Facebook 151.0-0.44.205 for Android 4.x. Apkmirror only contains the Beta version, so here's a direct link to what I installed from the Play Store.
https://www.dropbox.com/s/rc5yucavqba7oih/fb.apk?dl=0

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, but this fails to rebuild. Using "apktool d -s -r" followed by "apktool b" produces a working APK without the problem described here.
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Thanks for the detailed PR. I have downloaded the application and will take a look shortly.

**Comment by evilwombat** [comment]
Thank you!

**Comment by evilwombat** [comment]
Hey dude. For what it's worth, I tried comparing the contents of the res/ directories between the stock APK and the repacked version (that is, the version where apktool decompiles and recompiles the resources). It seems like the file list is mostly a match between the two versions, with one major difference: the stock APK contains a bunch of res/values/ directories (res/values, res/values-XX where XX is a language code, etc), and the repacked version is missing all res/values items. I hope this helps in some way...

**Comment by iBotPeaches** [comment]
Sorry. Forgot about taking care of bug tracker for 3-4 years and this happens.

> This item was deleted

I'll strive to not let this happen again. Closing as I can't triage/investigate.
