### ISSUE TITLE
how to include google play in apktool in recompile apk

### ISSUE THREAD

**Issue by mahdi00021** [iBotPeaches/Apktool#1671]
how to include google play in apktool in recompile apk

I after recompile apk like waze navigate but Dont work correct 

Needed to googley play that there is not

**Comment by iBotPeaches** [comment]
This is a bug tracker, not a support forum. Please follow the issue template if you are reporting a bug. Questions & Comments can be provided on various other mediums like XDA, Google Groups, etc.

**Comment by mahdi00021** [comment]
But must apktool included google play  to apk

**Comment by iBotPeaches** [comment]
That doesn't make sense. Take your time, do some research. This is not the place.
