### ISSUE TITLE
How declaration jni files in decompiled apk

### ISSUE THREAD

**Issue by ImanX** [iBotPeaches/Apktool#1678]
Hello Guys,
I decompiled a apk and change packageid and dirs 
app install & run as well but not working native method.
error is : 
`W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.wazex.ResManager.InitResManagerNTV() (tried Java_com_wazex_ResManager_InitResManagerNTV and Java_com_wazex_ResManager_InitResManagerNTV__)
`Thank for your helps

**Comment by iBotPeaches** [comment]
Unfortunately there is not enough details to go on here. Please follow the issue template in the future. 

Reverse engineering and rebuilding applications is becoming increasingly more difficult so just having one error line from the logcat is not enough.
