### ISSUE TITLE
Fix for Parsedroid vulnerability

### ISSUE THREAD

**Issue by waqarrashid33** [iBotPeaches/Apktool#1696]
I am not sure if this is already patched, some simple searches shows nothing so I will open a ticket.

Here are details of this vulnerability:
https://research.checkpoint.com/parsedroid-targeting-android-development-research-community/

They also released video demonstration, which can be seen here

<div align="center">
  <a href="https://www.youtube.com/watch?v=w8Lg8ptpVpQ"><img src="https://img.youtube.com/vi/w8Lg8ptpVpQ/0.jpg" alt="ImageXT"></a>
</div>

**Comment by iBotPeaches** [comment]
> we contacted APKTool developer and IDE companies and are pleased to report that they all fixed the security issues and released updated and improved versions of their products.

Per the last sentence of the article. Yes it has been fixed. While I wished they had put that line in the beginning, they didn't.
