### ISSUE TITLE
Manifest not compile

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#1699]
### Information
1. **Apktool Version (`apktool -2.3.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

Hello, i decode apk with new option,
`apktool.jar d -s -r --force-manifest test.apk`

and after change manifest and build with command
`apktool.jar b D:\\test`

app build success, manifest not compile,
how can i compile manifest ?

**Comment by iBotPeaches** [comment]
There is no support to individually compile/build an AndroidManifest.xml file. You can currently decode it (as-is), but you cannot build just that file. 

This would be a feature request, which might not be possible as resources would be in the compiled state and thus not able to be read the resources needed for building a manifest file. Let me look into it.

**Comment by iBotPeaches** [comment]
Not possible without some changes to the codebase. Moving to Feature Request

**Comment by viniciusmarangoni** [comment]
I have this use case too. Will be nice if this feature be implemented.

**Comment by charlessimonyi** [comment]
it's very nice if this feature be implemented, most of the time wo only want to add android:debuggable="true" in to <application> label

**Comment by charlessimonyi** [comment]
it's very nice if this feature be implemented, most of the time wo only want to add android:debuggable="true" in to <application> label

**Comment by charlessimonyi** [comment]
it's very nice if this feature be implemented, most of the time wo only want to add android:debuggable="true" in to "application" label

**Comment by charlessimonyi** [comment]
it's very nice if this feature be implemented, most of the time we only want to add android:debuggable="true" in to "application" label

**Comment by lkdevil** [comment]
Any progress ? @iBotPeaches

**Comment by iBotPeaches** [comment]
@lkdevil Sorry no progress. Bugs tend to get priority over features and I have about 150 of them.

**Comment by iBotPeaches** [comment]
This is not possible and won't be. Apktool needs to decode resources, otherwise we will have resourceIds everywhere and that won't work. Sorry.

Closing.
