### ISSUE TITLE
Add human readable errors like in smali.jar

### ISSUE THREAD

**Issue by sorgelig** [iBotPeaches/Apktool#17]
I see apktool still doesn't provide good readable compilation errors. Instead it just crashes the same way as long time ago. 

i'm not sure which version of smali/baksmali code you use, but smali v1.3.2 already provides good error reporting. For example missing names of labels - which is very helpful if you change a lot of code.

Please add error reporting in apktool.

**Comment by iBotPeaches** [comment]
fixed at some point in 2.0 development.
