### ISSUE TITLE
Modified framework-res.apk causing bootloop

### ISSUE THREAD

**Issue by furiousbuilder** [iBotPeaches/Apktool#1700]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Rom (Omnirom, Android 8.1, Oneplus5)

### Stacktrace/Logcat
Not able to get a logcat as the device doesn't boot. After modifying framework-res.apk's bools.xml to set UseRoundIcons to true, the device is stuck in a bootloop.

### Steps to Reproduce
1. Extract Framework from rom,
2. Install it via apktool 2.3.1 (tried without install too),
3. Decompile it,
4. Set UseRoundIcons to true in bools.xml,
5. Recompile,
6. Let the APK like that or include AndroidManifest+META-INF or Replace resources.arsc in stock Framework or Re-Sign it

As you can see, I tried quite everything I saw over the Internet in the step 6 to get a correct framework-res.apk, without success.

### Framework/APK
Original framework is attached here.
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/1591894/framework-res.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? I tried both, with and with signing
3. Are you using the latest apktool version? Yes, 2.3.1

Thanks for your help.

**Comment by iBotPeaches** [comment]
Its hard for me to debug an issue without a log.

While I do have a OnePlus 5T, that is my daily driver, so I cannot afford to do the testing needed here to unravel and test this issue. I would give this a read - https://android.stackexchange.com/questions/26463/debugging-bootloop-get-an-information-log-without-adb-can-an-emulator-help

Perhaps this can help obtain some information that we can use to look into this.

**Comment by VincentJoshuaET** [comment]
@furiousbuilder So have you found a solution for this? I also run OmniROM 8.1 but on a OnePlus 3T.

**Comment by franckamayou** [comment]
I also have the same issue on LineageOS 15.1 (Android 8.1) ROM on LG G6.

**Comment by iBotPeaches** [comment]
Closing due to details requested not provided in months.

**Comment by rmoravcik** [comment]
Hi all,

I'm having the same problem. I tied  to modify framework-res.apk, but as soon as I upload a modified apk to my watches, they will end up in bootloop.

I'm using version 2.3.3 of apktool and these commands to repack apk:

```
java -jar /usr/local/bin/apktool.jar d -f -s -o temp framework-res.apk
java -jar /usr/local/bin/apktool.jar b -c temp
```

I noticed one more think and I don't know if it can cause the problem. If I have a look to list of files of original apk, res/raw-* directories doesn't contain a letter 'r' before region code. Repacking will add that 'r'.

```
morgan@morgan:~/bootloop$ unzip -l framework-res.apk | grep CN
      962  2017-04-27 17:25   res/raw-zh-CN/incognito_mode_start_page.html
      654  2017-04-27 17:25   res/raw-zh-CN/loaderror.html
      927  2017-04-27 17:25   res/raw-zh-CN/nodomain.html
morgan@morgan:~/bootloop$ unzip -l temp/dist/framework-res.apk | grep CN
      927  2018-08-29 23:12   res/raw-zh-rCN/nodomain.html
      654  2018-08-29 23:12   res/raw-zh-rCN/loaderror.html
      962  2018-08-29 23:12   res/raw-zh-rCN/incognito_mode_start_page.html
morgan@morgan:~/bootloop$ 
```
Any one got any ides? Thank you.
