### ISSUE TITLE
Impossible to recompile settings.apk in MIUI 9 Oreo for Xiaomi Mi 6 (Sagit)

### ISSUE THREAD

**Issue by MrRainesUser** [iBotPeaches/Apktool#1702]
### Information
1. **Apktool Version (`2.3.1`)** -
2. **Operating System (Ubuntu 16.4, and Windows 10)** -
3. **APK From? (Official Stock ROM Oreo 7.12.28 for Xiaomi MI6)** -

### Stacktrace/Logcat

> [03.01.2018 10:13:37] I: **************************************************
> [03.01.2018 10:13:37] I: Java version: 1.8.0_151
> [03.01.2018 10:13:37] I: OS name: Linux
> [03.01.2018 10:13:37] I: OS version: 4.10.0-28-generic
> [03.01.2018 10:13:37] I: OS arch: 64 bit
> [03.01.2018 10:13:37] I: Home directory: /home/epicrom/jbart/
> [03.01.2018 10:13:37] I: 
> [03.01.2018 10:13:37] I: 
> [03.01.2018 10:13:37] I: ******** Installing frameworks ********
> [03.01.2018 10:13:37] I: Using apktool_2.3.1.jar
> [03.01.2018 10:13:37] I: I: Decoding Shared Library (androidhwext), pkgId: 15
> [03.01.2018 10:13:38] I: I: Framework installed to: /home/epicrom/jbart/data/frameworks/16.apk
> [03.01.2018 10:13:41] I: I: Framework installed to: /home/epicrom/jbart/data/frameworks/1.apk
> [03.01.2018 10:13:41] I: I: Decoding Shared Library (miui), pkgId: 16
> [03.01.2018 10:13:42] I: I: Framework installed to: /home/epicrom/jbart/data/frameworks/17.apk
> [03.01.2018 10:13:42] I: I: Decoding Shared Library (miui), pkgId: 16
> [03.01.2018 10:13:42] I: I: Framework installed to: /home/epicrom/jbart/data/frameworks/18.apk
> [03.01.2018 10:13:42] I: **** Decompiling Settings.apk ****
> [03.01.2018 10:13:43] I: I: Using Apktool 2.3.1 on Settings.apk
> [03.01.2018 10:13:43] I: I: Loading resource table...
> [03.01.2018 10:13:47] I: I: Decoding AndroidManifest.xml with resources...
> [03.01.2018 10:13:47] I: I: Loading resource table from file: /home/epicrom/jbart/data/frameworks/1.apk
> [03.01.2018 10:13:49] I: I: Loading resource table from file: /home/epicrom/jbart/data/frameworks/16.apk
> [03.01.2018 10:13:49] I: I: Decoding Shared Library (androidhwext), pkgId: 15
> [03.01.2018 10:13:49] I: I: Regular manifest package...
> [03.01.2018 10:13:50] I: I: Decoding file-resources...
> [03.01.2018 10:13:52] I: I: Loading resource table from file: /home/epicrom/jbart/data/frameworks/17.apk
> [03.01.2018 10:13:52] I: I: Decoding Shared Library (miui), pkgId: 16
> [03.01.2018 10:13:52] W: S: Could not decode file, replacing by FALSE value: layout/auto_disable_screenbuttons_checkbox
> [03.01.2018 10:13:54] W: S: Could not decode file, replacing by FALSE value: xml/smartcover_mode_settings
> [03.01.2018 10:13:55] I: I: Decoding values */* XMLs...
> [03.01.2018 10:13:56] I: I: Loading resource table from file: /home/epicrom/jbart/data/frameworks/18.apk
> [03.01.2018 10:13:56] I: I: Decoding Shared Library (miui), pkgId: 16
> [03.01.2018 10:13:58] I: I: Baksmaling classes.dex...
> [03.01.2018 10:14:03] I: I: Copying assets and libs...
> [03.01.2018 10:14:03] I: I: Copying unknown files...
> [03.01.2018 10:14:03] I: I: Copying original files...
> [03.01.2018 10:14:03] I: ******** Decompiling finished ********
> [03.01.2018 10:14:04] I: Time elapsed: 0h 0m 26s 755ms

> [03.01.2018 10:14:39] I: ******** Compiling file started ********
> [03.01.2018 10:14:40] I: **** Compiling Settings.apk ****
> [03.01.2018 10:14:40] I: I: Using Apktool 2.3.1
> [03.01.2018 10:14:40] I: I: Smaling smali folder into classes.dex...
> [03.01.2018 10:14:57] I: I: Building resources...
> [03.01.2018 10:15:23] W: W: /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/res/values/layouts.xml:3: error: Resource entry auto_disable_screenbuttons_checkbox is already defined.
> [03.01.2018 10:15:23] W: W: res/layout/auto_disable_screenbuttons_checkbox:0: Originally defined here.
> [03.01.2018 10:15:23] W: W: 
> [03.01.2018 10:15:23] W: W: /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/res/values/xmls.xml:3: error: Resource entry smartcover_mode_settings is already defined.
> [03.01.2018 10:15:23] W: W: res/xml/smartcover_mode_settings:0: Originally defined here.
> [03.01.2018 10:15:23] W: W: 
> [03.01.2018 10:15:23] W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1268042294908937170.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1519398718130382893.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_assist, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, webp, -0, arsc, -I, /home/epicrom/jbart/data/frameworks/1.apk, -I, /home/epicrom/jbart/data/frameworks/16.apk, -I, /home/epicrom/jbart/data/frameworks/17.apk, -I, /home/epicrom/jbart/data/frameworks/18.apk, -S, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
> [03.01.2018 10:15:23] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
> [03.01.2018 10:15:23] W: 	at brut.androlib.Androlib.buildResources(Androlib.java:426)
> [03.01.2018 10:15:23] W: 	at brut.androlib.Androlib.build(Androlib.java:305)
> [03.01.2018 10:15:23] W: 	at brut.androlib.Androlib.build(Androlib.java:270)
> [03.01.2018 10:15:23] W: 	at brut.apktool.Main.cmdBuild(Main.java:227)
> [03.01.2018 10:15:23] W: 	at brut.apktool.Main.main(Main.java:75)
> [03.01.2018 10:15:23] W: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1268042294908937170.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1519398718130382893.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_assist, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, webp, -0, arsc, -I, /home/epicrom/jbart/data/frameworks/1.apk, -I, /home/epicrom/jbart/data/frameworks/16.apk, -I, /home/epicrom/jbart/data/frameworks/17.apk, -I, /home/epicrom/jbart/data/frameworks/18.apk, -S, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
> [03.01.2018 10:15:23] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
> [03.01.2018 10:15:23] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
> [03.01.2018 10:15:23] W: 	... 5 more
> [03.01.2018 10:15:23] W: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1268042294908937170.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1519398718130382893.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_assist, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, webp, -0, arsc, -I, /home/epicrom/jbart/data/frameworks/1.apk, -I, /home/epicrom/jbart/data/frameworks/16.apk, -I, /home/epicrom/jbart/data/frameworks/17.apk, -I, /home/epicrom/jbart/data/frameworks/18.apk, -S, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
> [03.01.2018 10:15:23] W: 	at brut.util.OS.exec(OS.java:95)
> [03.01.2018 10:15:23] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
> [03.01.2018 10:15:23] W: 	... 6 more
> [03.01.2018 10:15:23] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -jar, /home/epicrom/jbart/data/tools/lib/apktool_2.3.1.jar, b, /home/epicrom/jbart/projects/Settings.apk.bzprj/decompiled/Settings.apk, -f, -c, -p, /home/epicrom/jbart/data/frameworks, -o, /home/epicrom/jbart/projects/Settings.apk.bzprj/compiled/Settings.apk]
> [03.01.2018 10:15:23] I: Time elapsed: 0h 0m 44s 295ms

### Steps to Reproduce
`1. apktool 2.3.1 in latest Jbart
2. decompile settings and decompile fine (creating FALSE XMLS in res/values/layouts and res/values/xmls)
3.- because of THIS FALSE xmls (smartcover xml, that apktool can't decodify) later it is impossible to recompile (even if we don't change anything of the ORIGINAL apk).`

### Frameworks
[framework-single.zip](https://github.com/iBotPeaches/Apktool/files/1599821/framework-single.zip)

[frameworks.zip](https://github.com/iBotPeaches/Apktool/files/1599824/frameworks.zip)

### APK

[Settings.apk.zip](https://github.com/iBotPeaches/Apktool/files/1599819/Settings.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
YES
2. If you are trying to install a modified apk, did you resign it?
This is not the case.
3. Are you using the latest apktool version?
YES, 2.3.1

**Comment by iBotPeaches** [comment]
Once again, another ugly application by an OEM full of mistakes.

```
➜  Bug1702 aapt d xmltree Settings.apk res/xml/smartcover_mode_settings    
W/ResourceType(10459): Bad XML block: header size 28024 or total size 1702240364 is larger than data size 369
ERROR: Resource res/xml/smartcover_mode_settings is corrupt
```

`res/xml/smartcover_mode_settings` is missing the `.xml` suffix and not even in AXML form in the compiled application. So it fails a decode, because its already human readable XML and inserts a `false` record.

This is exactly what happens with the other file. This is not a bug in Apktool and its not Apktool's job to repair completely messed up applications. Deal with those resources manually and everything will work out.

```
➜  Bug1702 apktool b Settings                                          
I: Using Apktool 2.3.1-18143c-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'debug_log' has no default translation.
W: warning: string 'dirac_control' has no default translation.
W: warning: string 'dirac_mode_earbuds' has no default translation.
W: warning: string 'dirac_mode_general' has no default translation.
W: warning: string 'dirac_mode_general_earbuds' has no default translation.
W: warning: string 'dirac_mode_general_inear' has no default translation.
W: warning: string 'dirac_mode_in_ear' has no default translation.
W: warning: string 'dirac_mode_off' has no default translation.
W: warning: string 'dirac_mode_piston_1' has no default translation.
W: warning: string 'dirac_mode_piston_100' has no default translation.
W: warning: string 'dirac_mode_piston_2' has no default translation.
W: warning: string 'dirac_mode_piston_youth' has no default translation.
W: warning: string 'edge_touch_volume' has no default translation.
W: warning: string 'fingerprint_apply_to_tittle' has no default translation.
W: warning: string 'location_access_off' has no default translation.
W: warning: string 'location_access_on' has no default translation.
W: warning: string 'master_clear_summary' has no default translation.
W: warning: string 'music_dirac_mode_piston' has no default translation.
W: warning: string 'screen_monochrome_mode_range_title' has no default translation.
W: warning: string 'search_imei_information_title' has no default translation.
W: warning: string 'sim_pin_attempts' has no default translation.
W: warning: string 'sim_pin_disable_failed' has no default translation.
W: warning: string 'sim_pin_disabled' has no default translation.
W: warning: string 'sim_pin_enable_failed' has no default translation.
W: warning: string 'sim_pin_enabled' has no default translation.
W: warning: string 'wifi_scan_notify_text_location_off' has no default translation.
W: warning: string 'wifi_scan_notify_text_location_on' has no default translation.
W: W/ResourceType(11548): DynamicRefTable(0x10): No mapping for build-time package ID 0x10.
W: W/ResourceType(11548): e[0x01] -> 0x01
W: W/ResourceType(11548): e[0x7f] -> 0x7f
W: E/ResourceType(11548): Failed resolving ResTable_map name at 1840 with ident 0x100b0014
W: warning: Package not found for resource #1001001a
W: W/ResourceType(11548): DynamicRefTable(0x10): No mapping for build-time package ID 0x10.
W: W/ResourceType(11548): e[0x01] -> 0x01
W: W/ResourceType(11548): e[0x7f] -> 0x7f
W: E/ResourceType(11548): Failed resolving ResTable_map name at 3360 with ident 0x100b000f
W: warning: Package not found for resource #1001004f
W: W/ResourceType(11548): Attempt to retrieve bag 0x1001004f which is invalid or in a cycle.
W: warning: Package not found for resource #1001004f
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1702 
```
