### ISSUE TITLE
unable to install framework-res.apk on Windows 10

### ISSUE THREAD

**Issue by newbreedsoftware** [iBotPeaches/Apktool#1705]
when trying to run 'apktool if framework-res.apk' I receive the following output. I am using Windows 10 Home x64 and I have launched Command Prompt as Admin. Apktool.jar and apktool.bat are both in my C:\Windows directory and I am able to decompile apks using 'apktool d apk.apk'.
```
C:\Windows>apktool if framework-res.apk
S: WARNING: Could not write to (C:\Users\Tyler\AppData\Local\apktool\framework), using C:\Users\Tyler\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Framework installed to: C:\Users\Tyler\AppData\Local\Temp\1.apk
```

**Comment by bovirus** [comment]
@newbreedsoftware 

I believe that is not an apktool problem but a folder eprmission in your installation.

Check that you have the admin right.
Choose another folder

**Comment by newbreedsoftware** [comment]
if i am running command prompt under admin isnt that the same?

**Comment by bovirus** [comment]
Depend also by the pernisison on the folder.

Try to use Android MultiTool

https://forum.xda-developers.com/showthread.php?t=2326604

decompress it under C;\

Copy your apk in C:\AndroidMultiTool\Files
Copy your apk in C:\AndroidMultiTool\Framework-Files

Open a dos prompt

Go in C:\AndroidMultiTool and run AMT.BAT

Select 1 to install framework-res,.apk
Select 2 to select apk
Select 3 to decompress apk
Select 4 to compress apk
Select 5 to sign apk

**Comment by iBotPeaches** [comment]
This is a support issue. Not a bug. As said above you can do quite a few steps to resolve this.

I recommend using the `--frame-path [folder]` parameter and describing the folder you want the framework resources to reside.

**Comment by zoanthropy** [comment]
I have the same problem even running as an admin.

**Comment by DubKF** [comment]
I think the fix on windows is easy, even without the `--frame-path [folder]` option. I just had to create the non existing directory `c:\Users\[username]\AppData\Local\apktool\framework` where [username] is your username. Once it was there, installing the framework used the folder correctly, which makes me feel the installation procedure or apktool.bat could just verify the directory existence and create it in case it's  missing.

**Comment by rahulcracker** [comment]
S: WARNING: Could not write to (C:\Users\rahul17.singh\AppData\Local\apktool\framework), using C:\Users\RAHUL1~1.SIN\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\RAHUL1~1.SIN\AppData\Local\Temp\1.apk


during time of decompile and bind m getting this error but i m able to bind apk but it not working in my phone please let me know how to fix this issue

**Comment by Gargo** [comment]
I have the same problem
