### ISSUE TITLE
Android Application (apk) showing black screen after re-packing the same using apktool.

### ISSUE THREAD

**Issue by tohaidar2005** [iBotPeaches/Apktool#1706]
Hi,

There is some problem with apk, after repacking the same apk with apktool it is showing black screen but same was working fine before using apktool.

I also observed that problem get resolved once enabled **hardware acceleration** . So i think there is some issue with apktool. Please look into and let me know if you have any solution for this issue.

please find the application from this link,
https://www.dropbox.com/s/3n6nldynppnbp1b/Camera2Video.apk?dl=0

Regards,
Haidar

**Comment by iBotPeaches** [comment]
Why does enabling hardware acceleration fix the problem? Was the application originally using hardware acceleration and during the apktool process that attribute got removed?

**Comment by tohaidar2005** [comment]
No, hardware acceleration was not defined originally. I have attached original apk in my first post.

**Comment by AbandonedCart** [comment]
I recently encountered the same issue with two Unity games I was recompiling to add notch support. Out of 10 games, only two included `android:hardwareAccelerated="false"` and those two were the only ones to ask for permissions and then display a black screen with no further progress.

**Comment by iBotPeaches** [comment]
Not sure here and just random toggling attributes is not what I want to patch into Apktool.

I don't have time anymore to decode/rebuild/sign/install apps and pull stacktraces.

Sorry, closing.
