### ISSUE TITLE
Error: Unable to rebuild apk with apktool(2)(sorry)

### ISSUE THREAD

**Issue by ProsAnon** [iBotPeaches/Apktool#1708]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Linux,Kali
3. **APK From? (Playstore, ROM, Other)** - Downloaded from internet.

### Stacktrace/Logcat

```
Include stacktrace here
```
Using APK template: Whatsappo.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[] Creating signing key and keystore..
[] Decompiling original APK..
[] Decompiling payload APK..
[] Locating hook point..
[] Adding payload as package com.whatsapp.zumvr
[] Loading /tmp/d20180110-6408-1ej4cd4/original/smali/com/whatsapp/AppShell.smali and injecting payload..
[] Poisoning the manifest with meterpreter permissions..
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[*] Rebuilding Whatsappo.apk with meterpreter injection as /tmp/d20180110-6408-1ej4cd4/output.apk
Error: Unable to rebuild apk with apktool
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

It's the WhatsApp apk I used this time.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? I started with msfvenom -x[etc]
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes, I do.

**Comment by iBotPeaches** [comment]
Sorry man, you just aren't understanding :(

This tool is crashing, because apktool is not rebuilding. However, this application is not giving me ANYTHING to work with.

```
 Error: Unable to rebuild apk with apktool
```

Tells me literally nothing. At all. 

Thanks for following the issue template this time, but the outcome is the same. We don't know why apktool is crashing and this tool is not explaining it. Read a few other open bugs here to get an idea what I'm looking for.

**Comment by ProsAnon** [comment]
I get this log using fatrat

No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10092 bytes
Saved as: /root/Desktop/TheFatRat/temp/payload.apk
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
	for: CN=Android Debug, O=Android, C=US
[Storing /root/Desktop/TheFatRat/temp/debug.keystore]

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /root/Desktop/TheFatRat/temp/debug.keystore -destkeystore /root/Desktop/TheFatRat/temp/debug.keystore -deststoretype pkcs12".

Sorry for bothering but I don't know where to ask, yesterday it worked fine..

**Comment by CunningLogic** [comment]
Adding on to the fact taht your not really giving us any info, you are also asking for help backdooring whats app. I highly doubt you will get that help here.

**Comment by ProsAnon** [comment]
I don't need help to backdoor Whatsapp man, it could be any other apk, but please tell me what info can I give you if this is the only error message I get?

**Comment by AshkanRafiee** [comment]
here you can solve the problem as i answered this question on stackoverflow:
[Link To The Answer On Stack Over Flow](https://stackoverflow.com/questions/52433758/unable-to-rebuild-apk-with-apktool-kali-linux/52545982#52545982)

**Comment by azamet90** [comment]
> Sorry man, you just aren't understanding :(
> 
> This tool is crashing, because apktool is not rebuilding. However, this application is not giving me ANYTHING to work with.
> 
> ```
>  Error: Unable to rebuild apk with apktool
> ```
> 
> Tells me literally nothing. At all.
> 
> Thanks for following the issue template this time, but the outcome is the same. We don't know why apktool is crashing and this tool is not explaining it. Read a few other open bugs here to get an idea what I'm looking for.

i did check aaaaaaaaaaall the topics started with the same title like this one you always asking one question after you get the answer you stop helping this is not helping this is just talking useless :dagger: 
do you want to help us? you see everybody have the same error ...
