### ISSUE TITLE
Help / Feature Request :  Any way to add resources to an existing app?

### ISSUE THREAD

**Issue by ezra100** [iBotPeaches/Apktool#1717]
Hi,
I'm using the latest Apktool and I'm trying to take an existing app and add a new activity to it. In order to produce the smali files and the resources I created a new app with the new activity and and compiled it, the only problem is the mapping of the new resources to the new smali files.
Will Apktool include the new resources if I recompile the decompiled app? And if yes, how would I know what would be the id of the new resource? And is there any way to tell Apktool to link the new resource to some location in the smali file?
Thanks,
Ezra

**Comment by iBotPeaches** [comment]
You are working in the decompiled state, so you need to explicitly generate a resource ID, abiding by the rules of that and use `public.xml` to maintain that ID for the resource(s) in question. Failure to do so will have `aapt` generate its own, which means (if you tried to reference in smali) will fail miserably.

This is still a question, with no real feature request so closing. Forums, chats, xda is a better place for this.
