### ISSUE TITLE
Encountered typeIdOffset not 0? This is your report.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#1728]
Hi there,

Apktool has intentionally output this error message because we need to find an application in the wild, like the application that sent you to this report.

Please attach the apk / email me (ibotpeaches (at) gmail (dot) c0m) so we can fix this issue.

**Comment by iBotPeaches** [comment]
This warning has been merged into master - https://github.com/iBotPeaches/Apktool/pull/1690. Next release will have it.

**Comment by iBotPeaches** [comment]
Going to close this, I still get notification, but one less bug.

**Comment by Elmehdioub** [comment]
> Going to close this, I still get notification, but one less bug.

You like to keep close issues with no fix, what a wonderful developer.

**Comment by Schoemiees666** [comment]
Did I do something wrong or is there something that I can go and fix
assistentce will be appreciated
Let me know

**Comment by REAndroid** [comment]
Hello,
I was researching same for purpose of "type id offset" I couldn't find enough resources thus I made my assumption as:
 `type-id = typeIdOffset + typeIdOnSpecHeader`. Then I generated three apks(using my tool) with typeIdOffset = 0, 1, 2 and tested on two devices API-16 (4.3)  &  API-28 (9.0) 

Here is my results:

|typeIdOffset | API-16 | API-28|
|--------|--------|--------|
|0 | OK | OK|
|1 | OK | fail to load strings|
|2 | OK | fail to load all resources|

I am guessing that  typeIdOffset is abandoned by android after some version.

[type-id-offset-apks.zip](https://github.com/iBotPeaches/Apktool/files/14010694/type-id-offset.zip)

**Comment by iBotPeaches** [comment]
very interesting - thanks @REAndroid. Guessing the various newer iterations of packing resources became a more optimized approach than type offsetting which was probably part of the sparse era of optimization.

**Comment by bzdnagao** [comment]
“What does this project look like after it starts? I see this（> Configure project :
Building SNAPSHOT (no .git folder found)
fatal: No names found, cannot describe anything.
） when I run it in IDEA, does it have any impact?”

**Comment by iBotPeaches** [comment]
> “What does this project look like after it starts? I see this（> Configure project : Building SNAPSHOT (no .git folder found) fatal: No names found, cannot describe anything. ） when I run it in IDEA, does it have any impact?”

This looks to have nothing to do with typeIdOffset - I don't understand? What is the relevance to this thread?

**Comment by iBotPeaches** [comment]
@REAndroid - Styled strings are the bane of my existence. The spec lies, apps lie, nothing makes sense. 

 * #3588 
 * #2890
 
 In terms of what you are looking for though for compilation - I don't know. I just have to build something to handle disassembly and let aapt2 do the heavy lifting again. Our [StyledString](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StyledString.java) class has all the details.
