### ISSUE TITLE
Changing minSdkVersion of Loxone Smart Home doesn't work

### ISSUE THREAD

**Issue by pietercardoen** [iBotPeaches/Apktool#1729]
### Information
1. **Apktool Version (`apktool -version`)** - v2.3.1
2. **Operating System (Mac, Linux, Windows)** - Linux Ubuntu 16.04 LTS
3. **APK From? (Playstore, ROM, Other)** - Loxone Smart Home v9.1.1 (2017.11.14)

### Stacktrace/Logcat
No
```
No stacktrace
```

### Steps to Reproduce
1. `apktool d Loxone...apk `
2 `Adapt minSdkVersion of 19 to 17 (kitkat to jellybean)`
3. `apktool b Loxone...apk`
4 `If you put the apk on the device, it installs correctly but if I start the application, it gets stuck at the splash screen.`

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/loxone-smart-home/com.loxone.kerberos

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No, cannot as my android device is version 4.2 (jellybean). It's a wall tablet.
2. If you are trying to install a modified apk, did you resign it?
Yes I signed the app with uber-apk-signer before putting it on the device.
3. Are you using the latest apktool version?
Yes, I just downloaded it

**Comment by iBotPeaches** [comment]
```
➜  Bug1729 cat smart/apktool.yml| grep 'minSdkVersion'
  minSdkVersion: '17'

➜  dist aapt d xmltree smart.apk AndroidManifest.xml | grep 'minSdk' 
        A: android:minSdkVersion(0x0101020c)=(type 0x10)0x11

```

Hex 0x11 = Decimal 17

The application built with the new `minSdkVersion` so I'd say we need more details of the stacktrace / adb logcat.
