### ISSUE TITLE
Repacking Facebook causes missing "/r" directory even when using apktool -r -s

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1739]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1, and top-of-tree as of 3/3/2018.
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64
3. **APK From? (Playstore, ROM, Other)** - Play store (well, apkmirror)

Hey dude. I love apktool (especially for facebook patching) and I'm trying to unpack and repack the most recent Facebook for Android application and I'm running into some issues. The application seems to unpack and repack without errors (I am using apktool -r -s). Interestingly, the resulting APK is about 10MB smaller than stock (50MB vs 60MB). When installed, the repacked application is missing an icon (and shows up in the app drawer a default Android icon, which seems a bit strange, but makes me think of resource-related issues). The application force-closes shortly after launch, crashing with a NULL pointer exception while trying to call getWidth() on something (presumably again, due to resource-related issues). I have tried top-of-tree apktool (as of 34a2d0) as well as 2.3.1, with the same results.

It seems that there is a top-level directory called "r" in the stock APK file, which is not being treated as an "unknown" directory during the repack process (even though I have passed -r to apktool to avoid handling resources). A very crude workaround seems to be the following, but I imagine this is not the right solution for the problem.
--- a/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
+++ b/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
@@ -778,7 +778,7 @@ public class Androlib {
     private final static String[] APK_MANIFEST_FILENAMES = new String[] {
             "AndroidManifest.xml" };
     private final static String[] APK_STANDARD_ALL_FILENAMES = new String[] {
-            "classes.dex", "AndroidManifest.xml", "resources.arsc", "res", "r", "R",
+            "classes.dex", "AndroidManifest.xml", "resources.arsc", "res",
             "lib", "libs", "assets", "META-INF", "kotlin" };
     // Taken from AOSP's frameworks/base/tools/aapt/Package.cpp
     private final static Pattern NO_COMPRESS_PATTERN = Pattern.compile("\\.(" +

Here's my complete console log, if that helps:
me@machine:~/repo$ ./apktool/apktool d fb.apk -s -r -o test                                                                                                     
I: Using Apktool 2.3.2-34a2d0-SNAPSHOT on fb.apk                                                                                                                                         
I: Copying raw resources...                                                                                                                                                              
I: Copying raw classes.dex file...                                                                                                                                                       
I: Copying assets and libs...                                                                                                                                                            
I: Copying unknown files...                                                                                                                                                              
I: Copying original files...                                                                                                                                                             

me@machine:~/repo$ ./apktool/apktool b test -o repacked.apk                                                                                     
I: Using Apktool 2.3.2-34a2d0-SNAPSHOT                                                                                                                                                   
I: Copying test classes.dex file...                                                                                                                                                      
I: Checking whether resources has changed...                                                                                                                                             
I: Copying raw resources...                                                                                                                                                              
I: Copying libs... (/lib)                                                                                                                                                                
I: Copying libs... (/kotlin)                                                                                                                                                             
I: Building apk file...                                                                                                                                                                  
I: Copying unknown files/dir...                                                                                                                                                          

me@machine:~/repo$ jarsigner -keystore <keystore path> repacked.apk <key name>
me@machine:~/repo$ adb install repacked.apk
(Success)

### Stacktrace/Logcat
(Basically, a missing resource?)
03-03 01:07:49.498  8160  8160 E AppStateLoggerExceptionHandler: java.lang.RuntimeException: Unable to instantiate application com.facebook.katana.app.FacebookApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.katana/com.facebook.katana.app.FacebookSplashScreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
03-03 01:07:49.498  8160  8160 E AppStateLoggerExceptionHandler: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:989)
03-03 01:07:49.498  8160  8160 E AppStateLoggerExceptionHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)

### Steps to Reproduce
0. Grab https://www.apkmirror.com/apk/facebook-2/facebook/facebook-161-0-0-35-93-release/facebook-161-0-0-35-93-2-android-apk-download/
1. `/apktool/apktool d fb.apk -s -r -o test'
2. `./apktool/apktool b test -o repacked.apk`
3. Sign and install repacked.apk

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-161-0-0-35-93-release/facebook-161-0-0-35-93-2-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes. This is a strict unpack/repack operation without any modifications in between.
2. If you are trying to install a modified apk, did you resign it?
Yes.
3. Are you using the latest apktool version?
Yes.

Thanks for your time!

**Comment by iBotPeaches** [comment]
Just to keep myself organized, also moving this one into the latest facebook report.

Duplicate #1719
