### ISSUE TITLE
Copy all unknown files to resulting apk.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#174]
Original [issue 63](https://code.google.com/p/android-apktool/issues/detail?id=63) created by liudas.survila on 2010-06-23T06:53:16.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. dowload &quot;Are you smarter than a 5th Grader.apk&quot;
> 2. apktool decode &quot;Are you smarter than a 5th Grader.apk&quot; out

<b>What is the expected output? What do you see instead?</b>
In out folder there should be that /data folder, which is in the original pack. And of course, when you try to run built package, you get NullPointerException, because those required files are not found.

<b>What version of the product are you using? On what operating system?</b>
Tried with 1.3.1 and 1.2.0 versions. Windows XP.

<b>Please provide any additional information below.</b>
If I manually put those files into the out folder, 
apktool build out test.apk
just ignores them and won't put them into built package.

If I manually put those files into the built package, install it, I get this errors in LogCat:
...
06-23 06:08:01.410: ERROR/AndroidRuntime(308): Uncaught handler: thread main exiting due to uncaught exception
06-23 06:08:01.430: ERROR/AndroidRuntime(308): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.capcomcanada.fifthGrader2009/com.capcomcanada.fifthGrader2009.FifthGrader2009}: java.lang.NullPointerException
...

**Comment by KK-Designs** [comment]
HOw would you fix this?
