### ISSUE TITLE
APK failed to run properly after repacking

### ISSUE THREAD

**Issue by fridaExplorer** [iBotPeaches/Apktool#1748]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.1
2. **Operating System (Mac, Linux, Windows)** - Linux ubuntu 16.04 (64bit)
3. **APK From? (Playstore, ROM, Other)** - Playstore (https://play.google.com/store/apps/details?id=com.mobike.mobikeapp)
4. Ran on Google Nexus 5 Android version 5.0

### Stacktrace/Logcat (A)
W: /home/wmy/test/mobike/com.mobike.mobikeapp_6.9.1/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4829650832084630303.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 1681, --version-name, 6.9.1, --no-version-vectors, -F, /tmp/APKTOOL2382939767726851041.tmp, -0, arsc, -0, res/raw/livenessmodel, -0, res/raw/model, -0, dgc, -0, jar, -0, assets/channel, -0, bks, -0, arsc, -I, /home/wmy/.local/share/apktool/framework/1.apk, -S, /home/wmy/test/mobike/com.mobike.mobikeapp_6.9.1/res, -M, /home/wmy/test/mobike/com.mobike.mobikeapp_6.9.1/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)

### Stacktrace/Logcat (B)
E/Tinker.TinkerUncaughtExceptionHandler( 7226): uncaughtException:Unable to create application com.secneo.apkwrapper.ApplicationWrapper: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mobike.android.app.AndroidApplication.getPackageName()' on a null object reference
W/Tinker.TinkerUncaughtExceptionHandler( 7226): tinker is not loaded
E/Tinker.UncaughtHandler( 7226): catch exception when loading tinker:java.lang.RuntimeException: Unable to create application com.secneo.apkwrapper.ApplicationWrapper: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mobike.android.app.AndroidApplication.getPackageName()' on a null object reference
E/Tinker.UncaughtHandler( 7226): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
E/Tinker.UncaughtHandler( 7226): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E/Tinker.UncaughtHandler( 7226): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
E/Tinker.UncaughtHandler( 7226): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Tinker.UncaughtHandler( 7226): 	at android.os.Looper.loop(Looper.java:135)
E/Tinker.UncaughtHandler( 7226): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/Tinker.UncaughtHandler( 7226): 	at java.lang.reflect.Method.invoke(Native Method)
E/Tinker.UncaughtHandler( 7226): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/Tinker.UncaughtHandler( 7226): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/Tinker.UncaughtHandler( 7226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/Tinker.UncaughtHandler( 7226): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mobike.android.app.AndroidApplication.getPackageName()' on a null object reference
E/Tinker.UncaughtHandler( 7226): 	at com.mobike.android.d.a.b(SourceFile:17)
E/Tinker.UncaughtHandler( 7226): 	at com.mobike.android.app.AndroidApplication.onCreate(SourceFile:76)
E/Tinker.UncaughtHandler( 7226): 	at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate(SourceFile:189)
E/Tinker.UncaughtHandler( 7226): 	at com.secneo.apkwrapper.ApplicationWrapper.onCreate(ApplicationTemplate.java:47)
E/Tinker.UncaughtHandler( 7226): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
E/Tinker.UncaughtHandler( 7226): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
E/Tinker.UncaughtHandler( 7226): 	... 9 more
E/AndroidRuntime( 7226): FATAL EXCEPTION: main

### Steps to Reproduce
1. Initially, I tried apktool d and apktool b. However, error reported as shown in Logcat (A)
2. Then I tried apktool d --no-res and apktool b. I succeeded to repackage without error
3. Then signed the apk and installed the apk
4. However, when I launched the apk, the error as shown in Logcat (B) 

### APK
https://play.google.com/store/apps/details?id=com.mobike.mobikeapp

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
```
➜  1748 apktool d com.mobike.mobikeapp_1681.apk -s -f
I: Using Apktool 2.3.2-7903ec-SNAPSHOT on com.mobike.mobikeapp_1681.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1748 apktool b com.mobike.mobikeapp_1681
I: Using Apktool 2.3.2-7903ec-SNAPSHOT
I: Copying com.mobike.mobikeapp_1681 classes.dex file...
I: Copying com.mobike.mobikeapp_1681 classes2.dex file...
I: Copying com.mobike.mobikeapp_1681 classes3.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'instabug_str_record_audio' has no default translation.
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
➜  1748 
```

Could not duplicate

**Comment by vladsol** [comment]
The specified application is protected by Secneo.
An error (after packaging) will occur if you edit any of the files in the APK.
