### ISSUE TITLE
Why Ask tool generates smali_classes2 and smali_classes3 folders? 

### ISSUE THREAD

**Issue by SafwatHassan** [iBotPeaches/Apktool#1757]
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.1
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 16.04.3
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

simple apktool d *.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
I cannot upload the APK

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes and I tried even 2.2.2 and I still have the same weired output. I wonder what is the smali_classes2 and smali_classes3 folders

**Comment by iBotPeaches** [comment]
This isn't a support forum. This is a bug tracker.

If you have `classes3.dex`, you get `smali_classes3` folder. It is for multi-dex applications

**Comment by SafwatHassan** [comment]
Thanks a lot I will mark it as resolved, I could not find any contact email and the documentation did not mention the smali_classes2 folder so I thought that there is something wrong.

Anyway, thanks a lot for your reply.
