### ISSUE TITLE
Parsing Error on install with rebuilt .apk 

### ISSUE THREAD

**Issue by kevinm34232** [iBotPeaches/Apktool#1759]
I have an app working on that when rebuilding, apktool does not include the META-INF folder or the Kotlin folder from original .apk. In the past copying these folders over to the compiled .apk and then signing has worked, but in this latest version does not work and gives parsing error on install of app. Any ideas?

### Information
1. **Apktool Version (`apktool -2.3.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by ibuprophen1** [comment]
Grab an apk signing app and use it to sign your app... 

For example, the following 2 are decent ones that are specific to signing apk/zip files. 

https://play.google.com/store/apps/details?id=com.haibison.apksigner 

https://play.google.com/store/apps/details?id=com.albayrakbilisim.apkimza

I have those two in my device for when I need to use them (which is very seldom but, handy). 

Just a suggestion/recommendation... :-)

**Comment by kevinm34232** [comment]
Hi I am signing the file first, but getting that error when copying a couple missing folders from the original apk. Are there any difference in the signing apps?

**Comment by iBotPeaches** [comment]
The kotlin error is a duplicate, set to release soon.

https://github.com/iBotPeaches/Apktool/issues/1703
