### ISSUE TITLE
A Quick Clarification Needed... 

### ISSUE THREAD

**Issue by ibuprophen1** [iBotPeaches/Apktool#1762]
I was hoping to get a quick clarification from @iBotPeaches... 

Simply put... 

If an app was decompiled and recompiled using the v2.3.1, would that affect the app Decompile and Recompile using any of the previous versions? 

I just wanted to know about a modified apps using the recent version Apktool and its backwards compatibility using an older version of Apktool. 

I hope that I had asked/explained this okay via text... :-) 

~Ibuprophen

**Comment by iBotPeaches** [comment]
Not in my knowledge with v2.3.1. Versions have bugs decoding, some versions have bugs building. Thats why its always recommended to decode with the same version you are building it.

This is why I discourage and hate "AIO" tools that decode with one version and build with another.
