### ISSUE TITLE
美可发型APP反编译失败

### ISSUE THREAD

**Issue by lwugang** [iBotPeaches/Apktool#1767]
美可发型APP反编译失败
获取不到smali

**Comment by ibuprophen1** [comment]
Just to be clear... 

Translation of:
"美可发型APP反编译失败" 

Roughly to:
"Mei-hairstyle app failed to compile" 

Translation of:
"美可发型APP反编译
失败获取不到smali" 

Roughly to:
"Mei-hairstyles app failed to get Smali" 

I kind of understand what you're stating but, It really needs to be much more clear and in English. 

I would hate to see your assistance based upon the possibility of miscommunication... 

Thank you very much for your understanding! :-) 


~Ibuprophen

**Comment by iBotPeaches** [comment]
Thanks for the translation, but even in English there isn't enough information here to do anything with. @lwugang Thats why we keep the issue template to collect information :)

谢谢
