### ISSUE TITLE
Missing drawables in Play Console 8.2.005 APK are referenced as APKTOOL_DUMMY after decompiling

### ISSUE THREAD

**Issue by davide1293** [iBotPeaches/Apktool#1773]
### Informations
1. Apktool version: 2.3.2
2. Operating System: Windows
3. APK From: either Playstore or APKMirror

### Steps to Reproduce
 `apktool.jar d playconsole8.2.apk `

### APK

https://www.apkmirror.com/apk/google-inc/google-play-developer-console/google-play-developer-console-8-2-005-release/google-play-console-8-2-005-android-apk-download/

### Description

This is probably due to something new in this APK by Google. Sharing it as it might be interesting to look at. 
drawable-xhdpi-v4, drawable-xxhdpi-v4, drawable-xxxhdpi-v4 and other folders seem to be missing from res/ in the original APK. The size has in fact dropped by almost 2.4 MB from the previous APK. 
After decompiling, layouts point to APKTOOL_DUMMY values. An example can be seen here: https://imgur.com/a/S9uk2

This is the content of res/values/drawables.xml: https://hastebin.com/sanavosomo.scala

Using systrace to try and track down some of the missing drawables returns paths that though can't be seen in the APK, as they include the missing folders: 

- res/drawable-xxhdpi-v4/quantum_ic_clear_white_24.png
- res/drawable-xxhdpi-v4/ic_star_color.png
- res/drawable-xxhdpi-v4/ic_star_grey.png

Thanks for reading!

**Comment by kswOok** [comment]
i met this problem ,too

**Comment by iBotPeaches** [comment]
As you've seen with your research, there is nothing Apktool can do here. The reference resource does not exist for Apktool to find. To allow the application to work, apktool substitutes a dummy resource in place for that resourceId. That is the boolean false attributes you see.

I believe this is a "no-fix", there is nothing Apktool can do here.
