### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.cli 

### ISSUE THREAD

**Issue by filipematos95** [iBotPeaches/Apktool#1777]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.2
2. **Operating System (Mac, Linux, Windows)** - Mac OS X 10.13.2

I am trying to run apktool through the command line but I just get: 
"Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;
	at brut.apktool.Main._Options(Main.java:287)
	at brut.apktool.Main.main(Main.java:47)"

The same happens if I don't use the wrapper and use java -jar apktook.jar

**Comment by iBotPeaches** [comment]
Can't duplicate.
