### ISSUE TITLE
PUBG mobile decompile - recompile (Stuck on logo)

### ISSUE THREAD

**Issue by WarrenHood** [iBotPeaches/Apktool#1781]
Hi. I used APKtool 2.3.3 in a Kali chroot running on an armv7 aosp 7.1.2 ROM.

I successfully decompiled and recompiled pubg mobile (without making any changes)... Signed it(jarsigner), zip-aligned it(zipalign -f -v 4 pubgm.apk pubgmmod.apk)... It installs but it gets stuck on the tencent logo(usually when an app enters full screen you can swipe down to view status bar... Well the status bar doesn't come down so it means the game is frozen I think)...

Any idea what could be wrong?

**Comment by iBotPeaches** [comment]
Usually in this instance, its helpful to get the real error that is reported from phone. This can be discovered via `adb logcat` while the application is installing and running.

My guess is an application as big/popular as PUBG Mobile probably has anti-tamper code inside and that is probably what you are running up against. If you provide that logcat, we can take another look and open this up.
