### ISSUE TITLE
Exeption in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ozoromo** [iBotPeaches/Apktool#1790]
### Information
Apktool Version (2.3.2-dirty)
Operating System (Linux) 
APK From(Playstore)

Steps to Reproduce
1. `apktool d <someapk.apk> `
2. `apktool b <someapk>`

APK
Spaceflight simulator  (my test app in this case but dosent work with any)

when i try to recompile i get the error "Exeption in thread "main" java.lang.NoSuchMethod: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer"
please help i need to finish this till the end of the week

**Comment by iBotPeaches** [comment]
I don't duplicate this. Have you tried a non-dirty release? Perhaps your release was built incorrectly.
