### ISSUE TITLE
new issue 

### ISSUE THREAD

**Issue by sac23** [iBotPeaches/Apktool#1792]
compiled apktool from source u can decompile but cant recompile here is error

brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [C:\Users\sac\AppData\Local\Temp\BAT_temp\brut_util_Jar_872098322233231128.tmp, p, —forced-package-id, 1, —min-sdk-version, 26, —target-sdk-version, 26, —version-code, 26, —version-name, 8.0.0, —no-version-vectors, -F, C:\Users\sac\AppData\Local\Temp\BAT_temp\APKTOOL8770275689377228556.tmp, -x, -0, arsc, -0, png, -0, res/

ican decompile with 2.3.2
and recompile with 2.3.4
but issue just wanted to put out there thanks

**Comment by iBotPeaches** [comment]
There is not enough information here to go on. If you follow the issue template, we can see if there is anything we can do.
