### ISSUE TITLE
Excuse me, how to use apktool.jar in Android Studio ?

### ISSUE THREAD

**Issue by HaydenHu** [iBotPeaches/Apktool#1793]
### Information
1. apktool-2.3.3
2. android
3. android studio
I want to make an application similar to apkEditor. run in android os.
Is this the same as the common jar import Android Studio?
and if it is the same, how to call the decompile function after the import, what is the specific use method?

**Comment by raziel23x** [comment]
This is not a support line for programming this is for errors with the app itself not how to package it in a app as this program is not designed to work in a android environment and require other things to happen and if there is any resources use google to find them

**Comment by iBotPeaches** [comment]
As mentioned above, this is for bug reports not vague requests for support.
