### ISSUE TITLE
ZipAlign error

### ISSUE THREAD

**Issue by techker** [iBotPeaches/Apktool#1799]
### Information
1. **Apktool Version (`apktool -version`)** - 1.50 2.3.3
2. **Operating System (Mac, Linux, Windows)** -w10
3. **APK From? (Playstore, ROM, Other)** - playstore

### Stacktrace/Logcat

Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-p] [-v] [-z] <align> infile.zip outfile.zip
       zipalign -c [-p] [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -p: memory page alignment for stored shared object files
  -v: verbose output
  -z: recompress using Zopfli
```

**Comment by iBotPeaches** [comment]
Not sure what you are reporting here. Zipalign is a process run after you sign the application. Apktool has nothing to do with the signing or zipalign process.

Closing.
