### ISSUE TITLE
weird class in the app

### ISSUE THREAD

**Issue by b-e-e** [iBotPeaches/Apktool#1801]
### Information
1. Apktool v2.3.3
2. Windows
3. APK from local pc

### Stacktrace/Logcat

```
[Critical] <SSL_Security> SSL Connection Checking:
           URLs that are NOT under SSL (Total:1):
               http://ca.bitstar.org/
                   => Lcom/appanalyzerseed/b;-><clinit>()V
                   => Lcom/appanalyzerseed/a;-><clinit>()V
```

### Steps to Reproduce
1. Did an APK scanning with `apktool.jar ` and got this class detected, but I didn't find any of its usage in my project files, how did apktool get this? and how can I find it in my project please?

**Comment by iBotPeaches** [comment]
Can't duplicate this. Based on that stacktrace, seems you are looking at the wrong package. This is apktool, not "appanalyzer"

**Comment by b-e-e** [comment]
hi, please recognize your own report pattern, the Stacktrace is obtained from the report generated from `apktool.jar`, and the weird class `Lcom/appanalyzerseed/a;-><clinit>()V` was scanned and found by `apktool.jar` which I couldn't find it anywhere in my project, wonder how `apktool.jar` get it.
