### ISSUE TITLE
abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android' error

### ISSUE THREAD

**Issue by hanyelmehy** [iBotPeaches/Apktool#1802]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.3
2. **Operating System (Mac, Linux, Windows)** -  Windows 7
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat
\res\layout-v26\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?yesy
3. Are you using the latest apktool version?yes

**Comment by jus4me2cu** [comment]
I need it to work

**Comment by iBotPeaches** [comment]
This is not an issue. This is an outdated framework. Searching for "keyboardNavigationCluster" in this repo results in 15 duplicates - https://github.com/iBotPeaches/Apktool/search?q=keyboardNavigationCluster&type=Issues

Make sure to run `apktool empty-framework-dir` as instructed when upgrading.
