### ISSUE TITLE
dot in folder name crashes apktool

### ISSUE THREAD

**Issue by ulises2k** [iBotPeaches/Apktool#1804]
### Information
1. Apktool 2.3.3
2. Windows
3. PlayStore

### Steps to Reproduce
c:\svm>"java.exe" -jar "C:\svm\tools\apktool\apktool_2.3.3.jar" b "c:\TEMP\kodiak\Android_nextel.apk_28_05_2018-12_21_43\"

I: Using Apktool 2.3.3
brut.directory.DirectoryException: java.io.FileNotFoundException: c:\TEMP\kodiak\Android_nextel.apk_28_05_2018-12_21_43" (El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos)

The problem is the name of directory. if name is ".apk"
if you eliminate the dot (".") in directory "Android_nextel.apk_28_05_2018-12_21_43" the problem is fixed

**Comment by iBotPeaches** [comment]
Tested on both windows and unix. Just made decoded directories the package name, so "foo.bar.baz" and had no issue.
