### ISSUE TITLE
Can't recompile OnePlus 6's Oxygen OS 5.1.5 framework-res

### ISSUE THREAD

**Issue by baadnewz** [iBotPeaches/Apktool#1805]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3 and 2.3.4-21fbe5-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Stock Stable Oxygen OS 5.1.5 for OnePlus 6

### Stacktrace/Logcat
Not able to build the apk back but here are the build logs for both versions:
[apktool-2.3.3-stable-build-error.txt](https://github.com/iBotPeaches/Apktool/files/2046934/apktool-2.3.3-stable-build-error.txt)
[apktool-2.3.4-21fbe5-SNAPSHOT-build-error.txt](https://github.com/iBotPeaches/Apktool/files/2046936/apktool-2.3.4-21fbe5-SNAPSHOT-build-error.txt)

### Steps to Reproduce
1. just decompile framework-res.apk and build it back.

P.S.
I tried using apktool 2.3.0 and another apktool bundled in batchapktool: [apktool_2.3.4.zip](https://github.com/iBotPeaches/Apktool/files/2046948/apktool_2.3.4.zip)

and while the framework-res builds fine (just missing translation warnings, i get bootloop. here is the logcat for it:
[log.zip](https://github.com/iBotPeaches/Apktool/files/2046951/log.zip)

### Frameworks
[oneplus-framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2046921/oneplus-framework-res.zip)

### APK
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2046887/framework-res.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes
2. If you are trying to install a modified apk, did you resign it? tried with original signature, and resigning it
3. Are you using the latest apktool version? yes, and multiple other versions, as explained above

**Comment by iBotPeaches** [comment]
Looks like you encountered some signature checks. Apktool can't do much about this. See this ticket for more details: #1519
