### ISSUE TITLE
execAndReturn in OS.java fails to collect command output.

### ISSUE THREAD

**Issue by sunshouxiang** [iBotPeaches/Apktool#1809]
### Information
1. **Apktool Version (2.3.3)** -
2. **Operating System (Linux)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Cause

Although you used process.waitFor() to wait for termination of child process, you did not wait for the termination of collector thread. This results in collector.get returns incorrect text as the output of child process might not be collected completely at the point. executor.shutdown and executor.awaitTermination should be used to fix the problem.

**Comment by iBotPeaches** [comment]
Thanks for the report/tip. Would you like to submit a PR to correct this behavior?

**Comment by sunshouxiang** [comment]
It seems I do not have permission to create a branch for PR, so please refer to the patch output below.

*** 15,34 ****
--- 15,35 ----
   *  limitations under the License.
   */
  package brut.util;
  
  import brut.common.BrutException;
  import java.io.*;
  import java.util.Arrays;
  import java.util.concurrent.ExecutorService;
  import java.util.concurrent.Executors;
  import java.util.logging.Logger;
+ import java.util.concurrent.TimeUnit;
  
  import org.apache.commons.io.IOUtils;
  
  /**
   * @author Ryszard Wiśniewski <brut.alll@gmail.com>
   */
  public class OS {
  
      private static final Logger LOGGER = Logger.getLogger("");
  
***************
*** 106,125 ****
--- 107,136 ----
          ExecutorService executor = Executors.newCachedThreadPool();
          try {
              ProcessBuilder builder = new ProcessBuilder(cmd);
              builder.redirectErrorStream(true);
  
              Process process = builder.start();
              StreamCollector collector = new StreamCollector(process.getInputStream());
              executor.execute(collector);
  
              process.waitFor();
+             try {
+                 if (!executor.awaitTermination(15, TimeUnit.SECONDS)) {
+                     executor.shutdownNow();
+                     if (!executor.awaitTermination(5, TimeUnit.SECONDS))
+                         System.err.println("Stream collector did not terminate.");
+                 }
+             } catch (InterruptedException ie) {
+                 executor.shutdownNow();
+                 Thread.currentThread().interrupt();
+             }
              return collector.get();
          } catch (IOException | InterruptedException e) {
              return null;
          }
      }
  
      public static File createTempDirectory() throws BrutException {
          try {
              File tmp = File.createTempFile("BRUT", null);
              tmp.deleteOnExit();

**Comment by sunshouxiang** [comment]
It seems I do not have permission to create a branch for PR, so please refer to the patch output below.

`*** 15,34 ****
--- 15,35 ----
   *  limitations under the License.
   */
  package brut.util;
  
  import brut.common.BrutException;
  import java.io.*;
  import java.util.Arrays;
  import java.util.concurrent.ExecutorService;
  import java.util.concurrent.Executors;
  import java.util.logging.Logger;
+ import java.util.concurrent.TimeUnit;
  
  import org.apache.commons.io.IOUtils;
  
  /**
   * @author Ryszard Wiśniewski <brut.alll@gmail.com>
   */
  public class OS {
  
      private static final Logger LOGGER = Logger.getLogger("");
  
***************
*** 106,125 ****
--- 107,136 ----
          ExecutorService executor = Executors.newCachedThreadPool();
          try {
              ProcessBuilder builder = new ProcessBuilder(cmd);
              builder.redirectErrorStream(true);
  
              Process process = builder.start();
              StreamCollector collector = new StreamCollector(process.getInputStream());
              executor.execute(collector);
  
              process.waitFor();
+             try {
+                 if (!executor.awaitTermination(15, TimeUnit.SECONDS)) {
+                     executor.shutdownNow();
+                     if (!executor.awaitTermination(5, TimeUnit.SECONDS))
+                         System.err.println("Stream collector did not terminate.");
+                 }
+             } catch (InterruptedException ie) {
+                 executor.shutdownNow();
+                 Thread.currentThread().interrupt();
+             }
              return collector.get();
          } catch (IOException | InterruptedException e) {
              return null;
          }
      }
  
      public static File createTempDirectory() throws BrutException {
          try {
              File tmp = File.createTempFile("BRUT", null);
              tmp.deleteOnExit();
`

**Comment by sunshouxiang** [comment]
It seems I do not have permission to create a branch for PR, so please refer to the patch output below.

	***************
	*** 14,35 ****
	--- 14,36 ----
	   *  See the License for the specific language governing permissions and
	   *  limitations under the License.
	   */
	  package brut.util;
	  
	  import brut.common.BrutException;
	  import java.io.*;
	  import java.util.Arrays;
	  import java.util.concurrent.ExecutorService;
	  import java.util.concurrent.Executors;
	  import java.util.logging.Logger;
	+ import java.util.concurrent.TimeUnit;
	  
	  import org.apache.commons.io.IOUtils;
	  
	  /**
	   * @author Ryszard Wiśniewski <brut.alll@gmail.com>
	   */
	  public class OS {
	  
	      private static final Logger LOGGER = Logger.getLogger("");
	  
	      public static void rmdir(File dir) throws BrutException {
	***************
	*** 105,126 ****
	--- 106,137 ----
	      public static String execAndReturn(String[] cmd) {
	          ExecutorService executor = Executors.newCachedThreadPool();
	          try {
	              ProcessBuilder builder = new ProcessBuilder(cmd);
	              builder.redirectErrorStream(true);
	  
	              Process process = builder.start();
	              StreamCollector collector = new StreamCollector(process.getInputStream());
	              executor.execute(collector);
	  
	              process.waitFor();
	+             try {
	+                 if (!executor.awaitTermination(15, TimeUnit.SECONDS)) {
	+                     executor.shutdownNow();
	+                     if (!executor.awaitTermination(5, TimeUnit.SECONDS))
	+                         System.err.println("Stream collector did not terminate.");
	+                 }
	+             } catch (InterruptedException ie) {
	+                 executor.shutdownNow();
	+                 Thread.currentThread().interrupt();
	+             }
	              return collector.get();
	          } catch (IOException | InterruptedException e) {
	              return null;
	          }
	      }
	  
	      public static File createTempDirectory() throws BrutException {
	          try {
	              File tmp = File.createTempFile("BRUT", null);
	              tmp.deleteOnExit();
	              if (!tmp.delete()) {

**Comment by sunshouxiang** [comment]
It seems I do not have permission to create a branch for PR, so please refer to the patch output below.

	***************
	*** 14,35 ****
	--- 14,36 ----
	  package brut.util;
	  
	  import brut.common.BrutException;
	  import java.io.*;
	  import java.util.Arrays;
	  import java.util.concurrent.ExecutorService;
	  import java.util.concurrent.Executors;
	  import java.util.logging.Logger;
	+ import java.util.concurrent.TimeUnit;
	  
	  import org.apache.commons.io.IOUtils;
	  
	  /**
	   * @author Ryszard Wiśniewski <brut.alll@gmail.com>
	   */
	  public class OS {
	  
	      private static final Logger LOGGER = Logger.getLogger("");
	  
	      public static void rmdir(File dir) throws BrutException {
	***************
	*** 105,126 ****
	--- 106,132 ----
	      public static String execAndReturn(String[] cmd) {
	          ExecutorService executor = Executors.newCachedThreadPool();
	          try {
	              ProcessBuilder builder = new ProcessBuilder(cmd);
	              builder.redirectErrorStream(true);
	  
	              Process process = builder.start();
	              StreamCollector collector = new StreamCollector(process.getInputStream());
	              executor.execute(collector);
	  
	              process.waitFor();
	+             if (!executor.awaitTermination(15, TimeUnit.SECONDS)) {
	+                 executor.shutdownNow();
	+                 if (!executor.awaitTermination(5, TimeUnit.SECONDS))
	+                     System.err.println("Stream collector did not terminate.");
	+             }
	              return collector.get();
	          } catch (IOException | InterruptedException e) {
	              return null;
	          }
	      }

**Comment by iBotPeaches** [comment]
@sunshouxiang thank you! I will take a look. In the future, you usually just "fork" the project, so you own the repo and can make whatever branch, then make a pull request from your branch and repo to this project.

**Comment by iBotPeaches** [comment]
Merged into the codebase. Thanks again, sorry for the delay.
