### ISSUE TITLE
Can't decompile apk file

### ISSUE THREAD

**Issue by leo150** [iBotPeaches/Apktool#1813]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore -> APK Extractor (from OnePlus 3)

### Stacktrace/Logcat

```
I: Using Apktool 2.3.3 on file.apk
I: Loading resource table...
W: Multiple types detected!  ignored!
...
W: Multiple types detected!  ignored!
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/user/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResFlagsAttr$FlagItem.getValue(ResFlagsAttr.java:158)
	at brut.androlib.res.data.value.ResFlagsAttr.serializeBody(ResFlagsAttr.java:83)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:697)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
```

### Steps to Reproduce
1. `apktool -f d file.apk`
or
1. `apktool -f -p ./frameworks d file.apk`
frameworks dir contains all stuff from _Frameworks_ part

### Frameworks
`/system/framework`:
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/2086857/framework-res.apk.zip) 
[oneplus-framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/2086861/oneplus-framework-res.apk.zip)

All content: 
<details><summary>Spoiler</summary>
  OnePlusCamera.apk
QPerformance.jar
QtiTelephonyServicelibrary.jar
WfdCommon.jar
am.jar
android.hardware.light-V2.0-java.jar
android.hidl.base-V1.0-java.jar
android.hidl.manager-V1.0-java.jar
android.test.runner.jar
apache-xml.jar
appwidget.jar
arm
arm64
audiosphere.jar
bmgr.jar
bouncycastle.jar
btmultisimlibrary.jar
bu.jar
cneapiclient.jar
com.android.future.usb.accessory.jar
com.android.location.provider.jar
com.android.media.remotedisplay.jar
com.android.mediadrm.signer.jar
com.android.nfc_extras.jar
com.google.android.maps.jar
com.google.android.media.effects.jar
com.google.widevine.software.drm.jar
com.nxp.nfc.jar
com.qti.dpmframework.jar
com.qti.location.sdk.jar
com.qti.snapdragon.sdk.display.jar
com.quicinc.cne.api-V1.0-java.jar
com.quicinc.cne.jar
conscrypt.jar
content.jar
core-libart.jar
core-oj.jar
dpm.jar
dpmapi.jar
embmslibrary.jar
embryo.jar
ethernet-service.jar
ext.jar
framework-res.apk
framework.jar
ime.jar
ims-common.jar
input.jar
izat.xt.srv.jar
javax.obex.jar
legacy-test.jar
locksettings.jar
media_cmd.jar
monkey.jar
oat
oem-services.jar
okhttp.jar
oneplus-framework-res.apk
oneplus_sdk_utils.jar
oneplus_sdk_wrapper.jar
org.apache.http.legacy.boot.jar
org.simalliance.openmobileapi.jar
pm.jar
qcnvitems.jar
qcom.fmradio.jar
qcrilhook.jar
qmapbridge.jar
qti-telephony-common.jar
rcs_service_aidl.jar
rcs_service_api.jar
requestsync.jar
services.jar
sm.jar
svc.jar
tcmclient.jar
tcmiface.jar
telecom.jar
telephony-common.jar
telephony-ext.jar
uiautomator.jar
uimlpalibrary.jar
vendor.qti.hardware.fingerprint-V1.0-java.jar
voip-common.jar
vr.jar
wapicertstore.jar
wifi-service.jar
wm.jar
</details>

`/system/priv-app` content:
<details>
  <summary>Spoiler</summary>
  BackupRestoreConfirmation
BlockedNumberProvider
CNEService
CalendarProvider
CallLogBackup
CarrierConfig
ConfigUpdater
Contacts
ContactsProvider
CtsShimPrivPrebuilt
DefaultContainerService
Dialer
DiracAudioControlService
DivesIconPack
DocumentsUI
DownloadProvider
EmergencyInfo
ExternalStorageProvider
FusedLocation
GmsCore
GoogleBackupTransport
GoogleExtServices
GoogleFeedback
GoogleOneTimeInitializer
GooglePackageInstaller
GooglePartnerSetup
GoogleServicesFramework
IFAAService
InputDevices
ManagedProvisioning
MediaProvider
MmsService
MtpDocumentsProvider
O2DefaultIconPack
OPAod
OPAppCategoryProvider
OPAppLocker
OPCellBroadcastReceiver
OPDeviceManager
OPDeviceManagerProvider
OPFaceUnlock
OPInCallUI
OPMms
OPNetworkSetting
OPSettingsProvider
OPSimContacts
OPSystemUI
OPWifiApSettings
OnePlusCamera
OnePlusCameraService
OnePlusGallery
OnePlusWizard
Phonesky
ProxyHandler
RifonIconPack
Settings
SetupWizard
SharedStorageBackup
Shell
SmartcardService
StatementService
StorageManager
Tag
TeleService
Telecom
TelephonyProvider
Velvet
VpnDialogs
WallpaperCropper
com.qualcomm.location
dpmserviceapp
qcrilmsgtunnel
</details>

### APK
[file.apk.zip](https://github.com/iBotPeaches/Apktool/files/2086866/file.apk.zip)

How could I fix this issue? Thanks

**Comment by ibuprophen1** [comment]
@leo150, it looks like you only received Warnings and not Errors. 

Don't get me wrong but, I've received Warnings "W: " before and hadn't had any issues. 

I've seldom had any issues when it came to Warnings but, it's not impossible either. 


~Ibuprophen

**Comment by leo150** [comment]
@ibuprophen1 so you haven't got any NullPointerException? 

I've started from fresh - downloaded apk file from the original post, stored frameworks to "framework" folder, run `apktool -f -p ./frameworks d file.apk` and got the same log with the exception.

Maybe I could provide more info about my setup? If it would help

Thank you for response

**Comment by ibuprophen1** [comment]
@leo150, you should try performing a Github search regarding that error within these issues as follows... 

https://github.com/iBotPeaches/Apktool/issues?utf8=%E2%9C%93&q=is%3Aissue+NullPointerException+ 

This will provide you with a list of all the Open and Closed issues here that references "NullPointerException" and though not all of them applies but, you just may see 1 or more that are similar/same as yours. 

Those could either reflect an issue that iBotPeaches knows about or something that may resolve your issue. 

I believe that one or both of the following issues may have some information that will help you out with resolving this in some way. 

https://github.com/iBotPeaches/Apktool/issues/1647 

https://github.com/iBotPeaches/Apktool/issues/1741 

I wish you the best of luck and maybe iBotPeaches will pop in to provide further guidance. 


~Ibuprophen

**Comment by leo150** [comment]
@ibuprophen1 thank you for the response. I'll check it and reopen my issue if have new questions.
