### ISSUE TITLE
Maven integration

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#182]
Original [issue 71](https://code.google.com/p/android-apktool/issues/detail?id=71) created by Brut.alll on 2010-06-25T19:25:59.000Z:

> For now apktool is built using some custom, unix script. In addition it consists of 15 subprojects in 15 git repos ;-) 5 my libs and 10 dependencies - I didn't want to include them as jars, because then apktool would weight 20MB instead of 1MB.

I must open source all my projects and let Maven build rest of libs or include them as jars. Then use ProGuard to shrink unused bits.

Then I will be ready to open source this project. For now it would be hard to even fetch it ;-)

**Comment by jaredrummler** [comment]
Bump... what happened? Are there any plans to add apktool to maven central?

**Comment by iBotPeaches** [comment]
I have no current plans to add apktool to maven central.
