### ISSUE TITLE
No resource identifier found for attribute 'layout_maxHeight' in package 'android'

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [iBotPeaches/Apktool#1820]
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
W: warning: string 'pref_huge' has no default translation.
W: warning: string 'pref_large' has no default translation.
W: warning: string 'uv_number_of_subscribers_format' has no default translation.
W: /home/lakeba13/workspace/Apktool-master/debug/app_release/res/layout-v16/status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_maxHeight' in package 'android'
W: 
W: /home/lakeba13/workspace/Apktool-master/debug/app_release/res/layout-v16/status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_minHeight' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3525939126724182342.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 588, --version-name, 2.0.10-build-588-play, --no-version-vectors, -F, /tmp/APKTOOL6033102945594229224.tmp, -0, arsc, -I, /home/lakeba13/workspace/Apktool-master/framework/1.apk, -S, /home/lakeba13/workspace/Apktool-master/debug/app_release/res, -M, /home/lakeba13/workspace/Apktool-master/debug/app_release/AndroidManifest.xml]
```

### Steps to Reproduce
1. ` apktool d Poweramp.apk`
2. ` apktool b Poweramp.apk`

### APK
[Poweramp.apk.zip](https://github.com/iBotPeaches/Apktool/files/2104888/Poweramp.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by TamilanPeriyasamy** [comment]
I changed 

> status_controls_big.xml

 tag for 
 xmlns:internal="http://schemas.android.com/apk/**prv/res/android**   
 to
 xmlns:internal="http://schemas.android.com/apk**/lib/com.maxmpz.audioplayer**

**Comment by TamilanPeriyasamy** [comment]
Reference link : https://stackoverflow.com/questions/28827602/no-resource-identifier-found-for-attribute-in-package-com-app

**Comment by iBotPeaches** [comment]
Thanks for the fix, seems to be another namespace issue. I'm tracking this in #1361
