### ISSUE TITLE
linux java shell cmd 执行127

### ISSUE THREAD

**Issue by sheep0704** [iBotPeaches/Apktool#1825]
### Information
1. **Apktool Version (`apktool -version`)** - V2.3.3
2. **Operating System (Mac, Linux, Windows)** - LINUX
3. **APK From? (Playstore, ROM, Other)** - LIST

 
------------------------------------------
V2.3.3 Linux is error---> java shell cmd : runtime error code -- 127 
V2.3.3 is error，but v2.3.2 This version can be used(Linux)

**Comment by sheep0704** [comment]
V2.3.2 There is no sound in this version.
So use this version.V2.3.3.
V2.3.3 Linux is error---> java shell cmd : runtime error code -- 127

**Comment by iBotPeaches** [comment]
I don't understand what this is reporting. There is no sound in apktool at all.
