### ISSUE TITLE
the contents in the Androidmanifest of Chrome Apk v65.0.xxx doesn't extracted correctly.

### ISSUE THREAD

**Issue by jalhaja** [iBotPeaches/Apktool#1830]
### Information
1. **Apktool Version (`apktool -version`)** - **2.3.3**
2. **Operating System (Mac, Linux, Windows)** - **Windows**
3. **APK From? (Playstore, ROM, Other)** - **Chrome.apk** v65.0.3325.109

### Stacktrace/Logcat

I tried to decode the Androidmanifest.xml of Chrome.apk v65.0.3325.109. 
But the decoded Androidmanifest.xml looks wrong.
```
For example, from the Chrome.apk android:versionName="64.0.3282.137"
the code "android:" is extracted correctly.
<uses-feature **android:**glEsVersion="0x00020000" />

But from the Chrome.apk android:versionName="64.0.3282.137"
the code "android:" is not extracted correctly. but substituted as "n1:"
<uses-feature **n1:**glEsVersion="0x00020000"/>
```
for that reason, the contents in the Androidmanifest of Chrome Apk doesn't extracted correctly.

### Steps to Reproduce
C:\>apktool d -o c:Chrome -f Chrome.apk
I: Using Apktool 2.3.3 on Chrome.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\user\AppData\Local\apktool\framework), using C:\Users\user\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\user\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
```
➜  Bug1830 aapt d xmltree chrome.apk AndroidManifest.xml
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x13d1b6b4
    A: android:versionName(0x0101021c)="65.0.3325.109" (Raw: "65.0.3325.109")
    A: package="com.android.chrome" (Raw: "com.android.chrome")
    A: platformBuildVersionCode=(type 0x10)0x1b
    A: platformBuildVersionName="8.1.0" (Raw: "8.1.0")
    E: uses-sdk (line=3)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
    E: uses-feature (line=5)
      A: android:glEsVersion(0x01010281)=(type 0x11)0x20000
```

Decoded

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.android.chrome" platformBuildVersionCode="27" platformBuildVersionName="8.1.0">
    <uses-feature android:glEsVersion="0x00020000"/>
```

Can't seem to duplicate.
