### ISSUE TITLE
aapt version could not be identified

### ISSUE THREAD

**Issue by diksha3** [iBotPeaches/Apktool#1832]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

Using the latest version of apktool, and for aapt version "Android Asset Packaging Tool, v0.2-2679779", while compiling the app back it gives error : aapt version could not be identified

The same aapt version worked correctly with apktools v 2.3.1

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by sasuke1999** [comment]
Thanks,I'll try it

**Comment by iBotPeaches** [comment]
Could not duplicate this.

That version string correctly identifies as aapt1. As proof, I added a test for it: https://github.com/iBotPeaches/Apktool/commit/eecfc18c825f49b1ecebcbb949f0fe7dfaf4dfee

**Comment by diksha3** [comment]
Thanks for the update. This works intermittently, sometimes it goes through and returns 1 (as expected), but sometimes randomly it returns "aapt version could not be identified" and shows version number as empty string. We are always using the same aapt file, so not able to figure out why is the behavior different.

Please let us know why this could happen or if you have seen any such issues before?

**Comment by diksha3** [comment]
Also, we would like to know : Are there any specific migration instructions from apktool 2.3.1 to apktool 2.3.3? We didn't get any migration instructions in the release notes, so just upgraded the jar file. After upgrade things have not been smooth. So, please let us know if we are going wrong some where?

This is really important for us. We will really appreciate if you could help us with this. Please help how could we solve this?

**Comment by iBotPeaches** [comment]
> This works intermittently, sometimes it goes through and returns 1 (as expected), but sometimes randomly it returns "aapt version could not be identified" and shows version number as empty string. We are always using the same aapt file, so not able to figure out why is the behavior different.

Sounds like something is blocking the execution of the aapt binary, thus Apktool cannot read the version information. 

> Are there any specific migration instructions from apktool 2.3.1 to apktool 2.3.3?

Nope. Framework was updated in 2.3.2, which is as easy as `apktool empty-framework-dir`

 > Please help how could we solve this?
Attach the aapt binary you are using? There is no reproducible bug here for me to even investigate.

**Comment by diksha3** [comment]
Thanks for the update. Attaching the aapt binary we are using.
[aapt.zip](https://github.com/iBotPeaches/Apktool/files/2160177/aapt.zip)

**Comment by iBotPeaches** [comment]
You mentioned you were using mac, but unless I'm mistaken you sent a unix binary. Does the issue appear on mac and unix?

**Comment by diksha3** [comment]
Yes, mostly issue is replicable on unix system.

**Comment by iBotPeaches** [comment]
This aapt binary has a shared dependency, the builds we release from apktool are statically linked. That may be a problem. Either way, this is not bug in the tool.

```
➜  aapt ldd ./aapt
	linux-gate.so.1 =>  (0xf7f0a000)
	libc++.so => not found
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf7df1000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7dec000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7dcf000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xf7db3000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7d5e000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7d41000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7b8b000)
	/lib/ld-linux.so.2 (0xf7f0c000)
```
