### ISSUE TITLE
Could not find related smali files

### ISSUE THREAD

**Issue by lisabrauns** [iBotPeaches/Apktool#1833]
### Information
1. **Apktool Version (`2.3.3`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
>I: Using Apktool 2.3.3 on facebook.-104.0.0.17.71.apk
>I: Loading resource table...
>I: Decoding AndroidManifest.xml with resources...
>I: Loading resource table from file: C:\Users\lisa\AppData\Local\apktool\framework\1.apk
>I: Regular manifest package...
>I: Decoding file-resources...
>I: Decoding values */* XMLs...
>I: Baksmaling classes.dex...
>I: Copying assets and libs...
>I: Copying unknown files...
>I: Copying original files...
```

I successfully decompile facebook, but I can't find any smali files about Activity, such as FacebookLoginActivity.

If I hook the class com.facebook.katana.dbl.activity.FacebookLoginActivity, it is successful, but I can't find any source code. What is the reason? Can you give me some advice?

**Comment by iBotPeaches** [comment]
Pretty sure Facebook is obfuscated, so you won't find human readable names like that. Activities maybe, but outside of those won't be readable.
