### ISSUE TITLE
Which aapt branch does apktool use?

### ISSUE THREAD

**Issue by pangqingyuan1991** [iBotPeaches/Apktool#1836]
Hi, 
I want to compile aapt myself, but your project has so many branch that I don't know which is the stable one. Can you tell me?

I have another problem.When I recompile a app without external aapt, it costs 15 seconds. But when I specify external aapt, it costs 60 seconds. I have checked that it hangs after  aapt calling. aapt process has exited. Then apktool hangs about 40 seconds.

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - any
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Don't pay attention to the branches, while I'm attempting to follow version numbers to branch names, it is becoming too difficult to do that while maintaining aapt2 and aapt1. Just look for the specific tag or commit on frameworks/base.

Those tags/commits are labeled here - https://github.com/iBotPeaches/Apktool/blob/master/INTERNAL.md#first-we-need-the-aosp-source
