### ISSUE TITLE
Apktool x decompiling issue on Instagram.apk

### ISSUE THREAD

**Issue by harshkuttu** [iBotPeaches/Apktool#1839]
### Information
1. **Apktool Version (`apktool-x 7.2.2a arm64)** -
2. **Operating System (Android)
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```WARNING: linker: Warning: unable to normalize ""
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
I: Using Apktool 2.2.2-Black on Instagram.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /data/data/per.pqy.apktool/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
.Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?
Yes.

**Comment by ibuprophen1** [comment]
@harshkuttu, "Apktool X" and "Apktool 2.2.2-Black" is not an @iBotPeaches development department that I'm aware of.

**Comment by iBotPeaches** [comment]
There is a another build of Apktool, somewhere out there made by the guys at "Slimrom". They need a special build due to adding "black" qualifiers into Android. If my memory is right, they re-used IDs that a future version of AOSP used, thus we couldn't use those fixes.

v2.2.2 was released on - 2017.01.23, so pretty old. Without an application and an old build, not much I can do here.

Please try a newer version and I can re-open if this issue persists.

**Comment by ibuprophen1** [comment]
@iBotPeaches, there is a free Android App called "Apktool X" that Isn't available on the Play Store and is a free app. 

If your curious about it and, would like a copy of it to examine, i would be more than happy to provide you with a link (here or via email) then please let me know. 

Personally, I had tried it out a few times and it's not that bad at all but, I've always preferred doing Apktool specific tasks via the PC myself. 


~Ibuprophen

**Comment by iBotPeaches** [comment]
I have over 100 bugs by myself to fix, I'd rather just ignore Apktool X because I don't what it is and its not official. Too many bugs to go searching for more online :)

**Comment by ibuprophen1** [comment]
Not a problem at all My Friend! 

Understood and please let me know if you need anything looked into. I'm very good at researching things and am familiar with the Metadata system as well. 

Thank you for your developments! :-) 


~Ibuprophen 
xda-developers RC

**Comment by dongfangxunlei** [comment]
I don't think apktool X is a original project. The package name per.pqy.apktool is first used by me. I guess the guy who develops apktool X doesn't know how to cross compile openjdk and aapt for android, so he has to reuse my package id  ^_^ .
