### ISSUE TITLE
No resource identifier found for attribute 'compileSdkVersion' in package 'android'

### ISSUE THREAD

**Issue by LevizX** [iBotPeaches/Apktool#1852]
### Information issue #1842
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Any
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Steps to Reproduce
1. `apktool ` d then b

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid&hl=en_AU
apkpure.com has a copy of an older version 3.26.0 that has the same problem.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by ibuprophen1** [comment]
@LevizX, I'm not sure if it's a typo but, you had listed Apktool **v2.3.4** and the last version was **v2.3.3**.


~Ibuprophen

**Comment by LevizX** [comment]
@ibuprophen1 no, the latest release is 2.3.3

**Comment by ibuprophen1** [comment]
@LevizX, That is exactly what i had pointed out...

You reported:

**"Apktool Version (apktool -version) - 2.3.4"**

Just an FYI as, a developer myself, if an individual reports an issue and is unable to provide correct information as well as the logs via Attachment or Text, then the issue can potentially be viewed as inacurate in one or more ways.

I was just being helpful and your response reflects something else... LOL! :1234: 

I wish you the best of luck! :+1: 


~Ibuprophen

**Comment by LevizX** [comment]
@ibprophen1 no, my report was accurate, I was using the latest version. You are not being helpful at all by assuming it's not and I made a mistake.

That reveals a lot about you, sir.

**Comment by iBotPeaches** [comment]
I could not replicate this on my local copy (v2.3.4 - dev)

```
➜  Bug1852 apktool d droid.apk 
I: Using Apktool 2.3.4-92bec5-SNAPSHOT on droid.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1852 apktool b droid
I: Using Apktool 2.3.4-92bec5-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  Bug1852 
```

Ensure you have the latest framework file using `apktool empty-framework-dir`. Not sure what happened here with replies back n forth. As long as you put a version number, that works for me. I can tell if the version number is an unreleased dev version or public release.

**Comment by lijun0326** [comment]
i have same issue, and i solve it with `apktool empty-framework-dir`
