### ISSUE TITLE
Add an option to ignore layout files that can't be decoded instead of failing completely

### ISSUE THREAD

**Issue by StevenArzt** [iBotPeaches/Apktool#1855]
### Information
1. **Apktool Version (`apktool -version`)** - master branch on Github
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Huawei Phone

### Problem description
I have an APK file that uses a custom framework on a Huawei phone. Normally, you'd have to download the custom framework from the phone. That would give you a 2.apk to place in APKTool's framework directory and all would be fine. However, I need a generic solution that rather skips a resource file it can't decode, but that keeps on going for all other files. At the moment, the CantFindFrameworkResException unfortunately stops the complete decoding process instead of just skipping the current file. Can we have a command line switch that tells APKTool to continue with the next resource file, instead of aborting?

I'd basically like to catch the exception and carry on with the next element in the loop in brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258). I'd be happy to open a merge request with such an option. Would that be ok for you?

### Stacktrace/Logcat
```
Launched: Caused by: brut.androlib.err.CantFindFrameworkResException
Launched: 	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:779)
Launched: 	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:116)
Launched: 	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
Launched: 	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
Launched: 	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
Launched: 	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
Launched: 	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:48)
Launched: 	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:46)
Launched: 	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:47)
Launched: 	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:385)
Launched: 	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
Launched: 	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
Launched: 	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
Launched: 	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
Launched: 	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
Launched: 	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
Launched: 	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:135)
Launched: 	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
Launched: 	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
Launched: 	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
Launched: 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
```

### Steps to Reproduce
1. `apktool ` on APK file that uses a custom framework

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
> I'd basically like to catch the exception and carry on with the next element in the loop in brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258). I'd be happy to open a merge request with such an option. Would that be ok for you?

So just skip an entire resource file if it contains attributes/resources we cannot identify? Seems like it would hardly be a decoded application. It would be full of holes/missing files/attributes.

What is the use-case?

**Comment by StevenArzt** [comment]
We have a server-based analysis tool that accepts APK files from remote users and conducts static analysis on them. If we can't get some resources, we might not be able to give the user all the in-depth information we would like to. Still, the tool can be useful, because we might still gain some insight into the app for which we don't need that particular layout file. If we can't do anything with the APK, we can't give the user any results.

The hacky solution would be to detect the exception and then re-start APKTool with layout file decoding disabled altogether. We would then go on without any layout file, disable some of our features, and still be somewhat useful.

**Comment by iBotPeaches** [comment]
In the case, the situation may be better to just send a bogus ResSpec back the caller. This would be, of course, a configurable flag but allow the decode process to complete. The application would not be rebuildable, but files would survive just massively modified with bogus attributes.

**Comment by StevenArzt** [comment]
That sounds reasonable. What is the best way to proceed? Shall I give it a try and open a merge request once I have something that I can share?

**Comment by iBotPeaches** [comment]
Sure, no harm in giving it a shot. I'm a bit behind and need to get: https://github.com/iBotPeaches/Apktool/pull/1849 merged, then I can look into this.

**Comment by iBotPeaches** [comment]
I actually did this as part of obfuscation with other files. It now makes dummy resources. I don't have an application here to double check, so just going to close it, but I believe it may resolve this.
