### ISSUE TITLE
Apktool loses api level in resource folder names

### ISSUE THREAD

**Issue by Hull9k** [iBotPeaches/Apktool#1858]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Ubuntu Linux 16.04
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat

08-02 00:21:17.490960 I PackageManager: /system/framework/framework-res.apk changed; collecting certs
08-02 00:21:17.675579 E hal9k   : java.lang.SecurityException: **File res/drawable-hdpi-v4/ic_print_error.png in manifest does not exist**
08-02 00:21:17.675939 W PackageManager: Failed to scan /system/framework/framework-res.apk: Failed to collect certificates from /system/framework/framework-res.apk

### Steps to Reproduce
1. apktool d framework-res.apk
2. apktool b -c framework-res

### APK
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2250538/framework-res.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes. But i need original signature.
3. Are you using the latest apktool version? Yes. I tried 2.3.4_0702 with the same result.
This problem does not exist while working with framework-res.apk from the same devices with Nougat and Marshmallow.

Screenshot:
![2018-08-01_21-05-35](https://user-images.githubusercontent.com/24497487/43540164-9f6ee31e-95cf-11e8-9499-eafe3a6969e5.png)

**Comment by Hull9k** [comment]
Screenshot
![2018-08-01_21-05-35](https://user-images.githubusercontent.com/24497487/43539915-f280887e-95ce-11e8-8d5d-b092dfdc13f3.png)

**Comment by iBotPeaches** [comment]
So there are a few tickets about this, what happens is a disconnect between what is reported in the resource and what is represented in the filesystem. There is no easy fix for this. You can see the research began here: https://github.com/iBotPeaches/Apktool/issues/1761#issuecomment-379309998

So closing this as a duplicate.
