### ISSUE TITLE
Issue Regarding New Dependencies Within the META-INF Directory... 

### ISSUE THREAD

**Issue by ibuprophen1** [iBotPeaches/Apktool#1860]
This is an odd issue for me since I've never personally experienced this specific one before. 

{The version of the Apktool is v2.3.3} 

This issue is regarding the following app (and version):

https://www.apkmirror.com/apk/spectrum/spectrum-tv/spectrum-tv-6-16-0-669318-release-release/

This is a challenge to explain and I'll do my best and clarify anything if needed. 

This issue is regarding the specific directory labeled "META-INF". 

This directory originally has 26 Files and 1 directory with 1 file within it. 

When you decompile the app, this results in the META-INF to be removed. As you already know that when the app is recompiled, and then signed, the signing process creates a META-INF directory again with the 3 files as needed. 

This is the issue in question... 

The app will decompile, compile and be signed without any errors, warnings, etc... 

Besides the obvious 3 files (when signed), the app now has only the 3 files within the META-INF file when it originally had the 26 files and 1 directory with 1 file. 

Finally, the app will even install without an issue but, with those now missing files within the META-INF directory, the app will immediately crash because it cannot locate certain files that was previously within the META-INF directory. 

I hope that I had explained this okay via text @iBotPeaches.... 👍 

~Ibuprophen

**Comment by ibuprophen1** [comment]
@

**Comment by ibuprophen1** [comment]
I just wanted to a

**Comment by ibuprophen1** [comment]
I just wanted to add something @iBotPeaches... 

The Kotlin Support seems to be fine. From what I can see, the Kotlin directory is still there. 

It's just funny how there's still no errors to provide since I've received none from Decompiling and Recompiling that reflects them both as being Successful . 

It's only the META-INF Directory that isn't handled if additional files and directories are located within it besides the typical 3 when the apk file has been signed. 

I just wanted to update you with this information/clarification as well. 

Thank you very much! 👍


~Ibuprophen

**Comment by iBotPeaches** [comment]
```
      772  00-00-1980 00:00   META-INF/CERT.RSA
    82265  00-00-1980 00:00   META-INF/CERT.SF
    82222  00-00-1980 00:00   META-INF/MANIFEST.MF
        6  00-00-1980 00:00   META-INF/android.arch.core_runtime.version
        6  00-00-1980 00:00   META-INF/android.arch.lifecycle_livedata-core.version
        6  00-00-1980 00:00   META-INF/android.arch.lifecycle_runtime.version
        6  00-00-1980 00:00   META-INF/android.arch.lifecycle_viewmodel.version
        7  00-00-1980 00:00   META-INF/com.android.support_animated-vector-drawable.version
        7  00-00-1980 00:00   META-INF/com.android.support_appcompat-v7.version
        7  00-00-1980 00:00   META-INF/com.android.support_support-compat.version
        7  00-00-1980 00:00   META-INF/com.android.support_support-core-ui.version
        ...
```

I assume you mean these additional files shoved into `META-INF` folder. The `--copy-original` option can be used on rebuild to include these.

**Comment by ibuprophen1** [comment]
Thank you very much @iBotPeaches! 

I knew that I was missing something... LMAO! 



~Ibuprophen

**Comment by ibuprophen1** [comment]
@iBotPeaches, quick question... 

After decompiling the app, using the method that you had outlined, is there a way to sign the apk (after its been recompiled) without "everything" being wiped from the META-INF Directory? 

It's pretty much a common practice, for the handful of mediums that I use/have used, to wipe clean the META-INF Directory when signing an apk (instead of just removing and creating the 3 files). 

If this issue needs to be reopened/created, please advise so. 

Thank you very much My Friend! :-) 


~Ibuprophen
