### ISSUE TITLE
need help to add new layout file and access it from smali

### ISSUE THREAD

**Issue by infahash** [iBotPeaches/Apktool#1861]
I have a question. searched on google. but no help. so I ask it here.

I have decompiled apk using apktool and I need to add new activity to it. everything is right on smali code side. but I faced to a problem when adding layout file. so I add my complete process below.

1. copied the layout xml file to res/layout folder (activity_mymain.xml).
2. added `activity_mymain` to the res/xml/public.xml as given below.

```
</resources>
    .
    .
    <public type="xml" name="widget_info" id="0x7f130016" />

    <public type="layout" name="activity_mymain" id="0x7f130017" />
</resources>
```

incremented 1 to last `id` value in `public.xml`

but when I try to build the apk again i't give me the following error

>..... \res\values\public.xml:8340: error: Public resource layout/activity_mymain has conflicting type codes for its public identifiers (0xb vs 0x13).

I try to build it like below.
* `apktool b modded_apk`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and also
* `apktool b modded_apk -f`

**Comment by iBotPeaches** [comment]
Need to do some more research my friend :)

This is a bug tracker, so don't have the time to sit down and write a detailed explanation, but resourceIds are generally

```
0xPPTTEEEE
```
P = PackageId
T = TypeId
E = EntryId

You can't copy a resourceId from an `xml` type, then use a `layout` type again it. That is the error you are getting.

**Comment by infahash** [comment]
> Need to do some more research my friend :)

> This is a bug tracker, so don't have the time to sit down and write a detailed explanation, but resourceIds are generally

I know about it. so I have added

> I have a question. searched on google. but no help. so I ask it here.

to the top of my post.

Anyway, really thanks for you answer. before this I loaded my layout file by `getResources ().getIdentifier()` method.

but after read your answer I able to done it through xml instead programmatical way.
It helped me a lot.

**Thanks!** again
