### ISSUE TITLE
"aapt version could not be identified"  while recompiling the apk

### ISSUE THREAD

**Issue by memphise** [iBotPeaches/Apktool#1863]
### Information
1. **Apktool Version (`apktool -version`)** - apktool 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** -  Other 

### Stacktrace/Logcat

```
admin@VM-202-86 home]# "java" -jar "/data/godsdk/GodSDKLinuxTools_v2.3.3/apktool_2.3.3.jar" -q b -a /data/godsdk/GodSDKLinuxTools_v2.3.3/aapt --frame-path "/data/godsdk/GodSDKWorkSpace/36/2/204/apktooltmp" -f -o "/data/godsdk/GodSDKWorkSpace/36/2/204/tempRecompileApk/36_204_nosig.apk" "/data/godsdk/GodSDKWorkSpace/36/2/204/decompile"
aapt version could not be identified: 

```

### Steps to Reproduce

i get the aapt(Linux version) from apktool 2.3.3.jar, i opened the apktool2.3.3.jar by winrar and got the aapt and aapt2 

when I tried to recompile the apk with the "-a " commond to load the aapt(inside apktool 2.3.3.jar), the error happened.

But it could successed when i used apktool 2.2.1 and the aapt inside the apktool2.2.1 jar

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
The aapt builds (aapt2/aapt1) on Linux are extensively tested with the automated test suite. This is additionally done with Mac.

Windows has no automated test, so I always manually do the QA check. Do you have the aapt binary you used? This `/data/godsdk/GodSDKLinuxTools_v2.3.3/aapt` file must be invalid as it could not be read for the aapt version.

**Comment by memphise** [comment]
Sorry，too busy last two days.

I worked on Linux，the aapt and aapt2 is in the prebuilt folder of “apktool_2.3.3.jar”
![prebuilt](https://user-images.githubusercontent.com/19729379/43935345-0ac3c85c-9c86-11e8-85d4-434fd7da1ef8.png)
I uploaded  the aapt binary that I used below 
[aapt.zip](https://github.com/iBotPeaches/Apktool/files/2276366/aapt.zip)
