### ISSUE TITLE
Suggest ignore  dex,smalli,resource

### ISSUE THREAD

**Issue by qssq** [iBotPeaches/Apktool#1868]
### Suggest

Hope to develop such a feature ignoring the specified DEX file, if I only modify dex1 then other files should not be decompressed other dex, which can speed up.

Or ignore a resource file. If the resource file is incorrect, you should ignore the non-operation and specify a file or folder.

**Comment by iBotPeaches** [comment]
Marked as feature request. Ability to specific dex in a multi-dex application to decode.

**Comment by iBotPeaches** [comment]
We now use `--only-main-classes` to only decode those in root with `classes#.dex`. Marking as done. The resource filter is not feasible nor do I see myself taking that on.
