### ISSUE TITLE
regression: Apktool fails to decode APK with CHUNK_NULL_TYPE String block  

### ISSUE THREAD

**Issue by atn1969** [iBotPeaches/Apktool#1876]
[452_Alibaba_com_B2B_Trade_App_v4.18.2.apk.zip](https://github.com/iBotPeaches/Apktool/files/2290102/452_Alibaba_com_B2B_Trade_App_v4.18.2.apk.zip)

### Information

Commit b7b449eaa (Connor Tumbleson  2017-12-13 13:16:48 -0500)  has changed a line in brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
from 
- reader.skipCheckChunkTypeInt(CHUNK_STRINGPOOL_TYPE, CHUNK_NULL_TYPE);
to
+        reader.skipCheckInt(CHUNK_STRINGPOOL_TYPE);

which causes failures in apk extraction. This is a problem in latest master and and latest release. 
Android Studio is able to decompile resources. Please find the attached APK file to reproduce (the APK is zip-ed). 
(the reader.skipCheckInt() reads CHUNK_NULL_TYPE in the given APK on this point) 

If the above two lines are reversed, apktool handles the apk well, but I am not 100% sure what is the cause of this change and would like you to check this line. Please reverse the changes on that line if possible. 

1. **Apktool Version (`apktool -version`)** - v2.3.3 and master branch
2. **Operating System (Mac, Linux, Windows)** -   Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore: 

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
Yes

Regards, Attila

**Comment by iBotPeaches** [comment]
This change was intention. The previous iteration allowed 2 values at that specific instance. It was some hacky situation, but after I discovered `TypeIdOffset`, I realized it was that value.

I'd rather not revert this, so thanks for the application and I'll take a look.

**Comment by atn1969** [comment]
Ok, thanks, i will also try to analise TypeIdOffset a bit more. There may be a better solution  for this problem.
