### ISSUE TITLE
Failed to collect certificates of MtkSystemUI.apk

### ISSUE THREAD

**Issue by ismaeldm95** [iBotPeaches/Apktool#1879]
Hi, 

I'm having trouble with the signature of MtkSystemUI.apk. Tried to rebuild with same certificate (-c) and also pasting the META-INF and AndroidManifiest.xml into apk but once rebooted, PackageManager checks the certificates and doesn't start the app. I can only get it to work if I  decompile with -r and rebuild with -c, but I need to edit the resources too.

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Mac 10.13.4
3. **APK From? (Playstore, ROM, Other)** - MtkSystemUI.apk and framework-res from 8.1 Oreo firmware

### Stacktrace/Logcat

```

Failed to scan /system/priv-app/MtkSystemUI: Failed to collect certificates from /system/priv-app/MtkSystemUI/MtkSystemUI.apk

```

### Steps to Reproduce

1. `adb pull /system/priv-app/MtkSystemUI/ `
2. `adb pull /system/framework/framework-res.apk `
3. `apktool if framework-res.apk  `
4. `apktool if MtkSystemUI/MtkSystemUI.apk  `
5. `apktool d MtkSystemUI.apk  `
6.  replace change pip_dismiss_scrim.9.png 
7. `apktool b MtkSystemUI.apk  `
8. `Unzip generated .apk, paste META-INF and AndroidManifest.xml from original .apk, zip and change extention  `
9. `adb push MtkSystemUI.apk /system/priv-app/MtkSystemUI/ ` 
10. `adb reboot` 

### Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes, with -c and manually
3. Are you using the latest apktool version? yes

**Comment by cosmicdan** [comment]
Did you ever figure this out? Would really hate to have to re-sign an entire ROM...

**Comment by ismaeldm95** [comment]
> Did you ever figure this out? Would really hate to have to re-sign an entire ROM...

We ended up using apkMultiTool and it worked. We could modify the xml files and rebuild the apk with the same signature.

**Comment by cosmicdan** [comment]
Yeah not long after asking about it, I just found out that you need to repack the APK file manually since APKTool doesn't include some essential files that are in the original APK. It's a known issue that "-c" doesn't actually do anything for later Android versions, I saw iBotPeaches talking about it in another issue.

**Comment by iBotPeaches** [comment]
This just looks like stronger Android (nullifying -c) and just anti-tamper. Closing.
