### ISSUE TITLE
Some App's doen't communicate with "google" after re-compiling it with aktptool

### ISSUE THREAD

**Issue by RoseDeSable** [iBotPeaches/Apktool#1887]
### Information
1. **Apktool Version (2.3.3)** -
2. **Operating System ( Linux)** -
3. **APK From? (Google Appstore)** -

### Stacktrace/Logcat

A nice day at all,
   some apps show a strange behaviour after re-compiling. An example is the German's App "katwarn". To exclude other problems because of own modifications I de-compiled and re-compiled the original app. The test on my Samsung tablet shows me, that the re-compiled app doesn't contact the servers of google. In the attachment you see the blue block with the traffic of the original app and the the red block with the traffic of the re-compiled app. In the last you find no connect to google. 
  Could it be, that apktool have a problem with the interpretation of characters, so that the url is deformed and the request cannot go out ? 

![traffic](https://user-images.githubusercontent.com/42828799/44833315-02306800-ac2e-11e8-9bcc-502890ec3cac.JPG)

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
What probably happened is you triggered some tamper detection, thus failed validation so the request never went out, then again - just a guess.

You'll have to dig on this, as very broad topic at hand. Feel free to open another ticket if you track down what went wrong.

**Comment by RoseDeSable** [comment]
Thanks,
 in the directory of the location service for "Google" I see in the file "./smali/com/google/android/gms/common/e.smali" the tamper-detection with the following debugging message:

 const-string v3, "Signature not valid. ....
