### ISSUE TITLE
Align aapt/aapt2 codebases

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#1889]
Attempt to use the `android-9.0.0_r3` tag and apply both our aapt1/aapt2 patches to the codebase and build every binary -_-

Will make long-term easier. API28 made some fixes for aapt1.

**Comment by dongfangxunlei** [comment]
Great! Can you also build for android platform? I don't want to download the large aosp source any more.
I think above 95% devices uses arm64 and x86_64, the other can be ignored.

**Comment by iBotPeaches** [comment]
@dongfangxunlei Yes, I will build the Android builds. 
 * Release 2.3.4 - Support for Android Pie
 * Release 2.4.0 - Add support for Android platform

**Comment by iBotPeaches** [comment]
Aligning my codebases (updating them) is proving to be difficult due to the inclusion of the Manifest properties:
 * `compileSdkVersion`
 * `compileSdkVersionCodename`

These break the tests massively because old applications don't have these attributes, then rebuilt applications do. If we remove this feature, then new applications decoded will have the attributes stripped. 

Removing these two attributes from being injected will make the tests easier, but unsure of the outcome of this.
