### ISSUE TITLE
Throws error if I edit the manifest file

### ISSUE THREAD

**Issue by souravndp** [iBotPeaches/Apktool#1896]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.1
2. **Operating System (Mac, Linux, Windows)** -Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### What I am trying to do
1. I need to MITM https requests through fiddler/burp but due to android N limitation, I need to specify the app to honor user installed certificates. So, I need to add a file in `res/xml` and change the manifest file to point to the file. (https://blog.ropnop.com/configuring-burp-suite-with-android-nougat/)
2. I decoded and rebuilt without changing anything and it worked but as soon as I changed the manifest, it threw errors.

![image](https://user-images.githubusercontent.com/652191/45241563-89569d80-b30a-11e8-959d-c8ae1234588f.png)

### APK
https://drive.google.com/open?id=1bAU35Z6uRDX603aueTCfNOazMVsQgVXS

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes. If I don't change anything, the build process is successful

**Comment by souravndp** [comment]
sorry. syntax mistake. I am trying to check if any more errors are there from my end. I will reopen it later if I need help. closing now.

**Comment by ibuprophen1** [comment]
Also @souravndp, Apktool is now at v2.3.4 and your report reflects v2.3.1... 


~Ibuprophen
