### ISSUE TITLE
32 bit OS detected. No 32 bit binaries available. (defaulting to $PATH binary)--- 

### ISSUE THREAD

**Issue by sayanD15728** [iBotPeaches/Apktool#1897]
apktool b (dir) -o output.apk
I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: aapt: brut.common.BrutException: 32 bit OS detected. No 32 bit binaries available. (defaulting to $PATH binary)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [aapt, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 27, --version-code, 145, --version-name, 11.4.1, --no-version-vectors, -F, /tmp/APKTOOL10457475416347065996.tmp, -0, png, -0, arsc, -I, /tmp/1.apk, -S, /usr/local/bin/ucmini/res, -M, /usr/local/bin/ucmini/AndroidManifest.xml]
W: aapt: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory

**Comment by iBotPeaches** [comment]
Exactly as stated. 32bit is no longer supported. Please use a 64bit OS
