### ISSUE TITLE
apktool rebuilding errors when it encountered unicode characters in xml files

### ISSUE THREAD

**Issue by localacct** [iBotPeaches/Apktool#1899]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Error parsing XML: not well-formed (invalid token)
```

### Steps to Reproduce
1. `apktool b <apk folder>`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes

2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?
Yes

### Additional details
This is due to unicode characters being used in the names of the classes, methods etc. When apktool encountered these characters, the error occurs and the rebuilding stopped. The xml files are located in the /res/layout/ subfolder. I tried different ways of encoding the unicode characters

- &#....;
- &#x....; 
- \u....
- \xxxx

but none of these worked. I read from earlier issues that this might have been resolved, but I am still encountering them now. Any advice is appreciated.

**Comment by localacct** [comment]
Just to add on to the issue, for example in one of the xml files under /res/layout, there is such a configuration (<o.ﯧ android:textAppearance="?actionMenuTextAppearance" .... />

As seen, the second character is a unicode character and this caused an error when apktool tries to parse the xml file

**Comment by iBotPeaches** [comment]
Thanks for the details. I am going to organize this with a similar ticket with appears to be some sort of packer for breaking resource names.

Merging with #1576
