### ISSUE TITLE
Conflicting Information and Clarification... 

### ISSUE THREAD

**Issue by ibuprophen1** [iBotPeaches/Apktool#1901]
Hello There @iBotPeaches! :-) 

I just noticed that the following link... 

https://ibotpeaches.github.io/Apktool/

... Shows that one of the requirements is "Java 7 (JRE 1.7)". 

Though, the following link... 

https://ibotpeaches.github.io/Apktool/install/

... Shows the requirement of at least "Java 1.8". 

I've seen similar conflicts on a few other areas and was wondering if you were aware of this. 

I know that you're busy with other items on your agenda and I only pointed this out as a friendly "Heads Up" my friend. 

On a separate note, i'm also wondering about any requirements for the JDK that includes JRE instead of outlining JRE only. 

I may be wrong about this part but, I just wanted to be sure if there were any added benefits to using the JRE over the stand alone JDK. 

Thank you very much for your time and understanding with this! :-) 

~Ibuprophen

**Comment by iBotPeaches** [comment]
To build Apktool, you need Java 8 now (JDK).
To run Apktool, you need at least Java 7 (JRE). I am debating with the upcoming release whether to also move the JRE requirement to 8.

**Comment by iBotPeaches** [comment]
Java is moving too frequent these days. The next release will stay at JRE7, so docs are right.

**Comment by ibuprophen1** [comment]
I really appreciate your taking the time @iBotPeaches to address this minor question since I do you have more pertinent items on your agenda. 

Keep up the GREAT work My Friend! 🍻👍


~Ibuprophen

**Comment by saurabhsharma786** [comment]
sudo update-alternatives --config java
use this cmd to change the default version of java choose number 2 in most probably case java 8 will be on number 2
that's it.
