### ISSUE TITLE
force-manifest

### ISSUE THREAD

**Issue by 0x454447415244** [iBotPeaches/Apktool#1902]
Hello,

Is it possible to recompile if we set both flags --force-manifest and --no-res ? I tried it but it doesn't work. The manifest file will be considered as corrupted and the package won't install.

The thing is that I need to perform some changes to the manifest file without decompiling the resources (which is problematic most of the times), then rebuild the package.

It seems that the build feature does not recompile the manifest file when --no-res flag was used during unpack. The manifest file will be in ascii form after recompile.

Any solution? Thanks.

**Comment by iBotPeaches** [comment]
Confirmed duplicate as said above.
