### ISSUE TITLE
Issue building SystemUI with appt2

### ISSUE THREAD

**Issue by LeeDroid-** [iBotPeaches/Apktool#1903]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM

Initial Issue:

Build failed with:

I: Building resources...
W: C:\Users\linux\Kitchen\Mod\SystemUI\res\values\ids.xml:4: error: <item> inner element must either be a resource reference or empty.

This was fixed by changing all entries in /values/ids.xml as follows:

From:
    item type="id" name="accessibility_button">false</item

To:
    item type="id" name="accessibility_button"></item

Second issue:

W: brut_util_Jar_5387892945670873.tmp F 09-21 11:28:51   232  1620 PrivateAttributeMover.cpp:84] Check failed: priv_attr_type->entries.empty()
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 3): [C:\Users\linux\AppData\Loca
l\Temp\brut_util_Jar_5387892945670873.tmp, link, -o, C:\Users\linux\AppData\Local\Temp\APKTOOL8820944096532585835.tmp, -
-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-auto-
version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -0, arsc, -0, res/drawable-400dpi-v4/co

### Steps to Reproduce
1. apktool --use-aap2 b SystemUI

**Comment by ibuprophen1** [comment]
You stated that you used Apktool v2.4.0 but, the most recent version is v2.3.4. 


~Ibuprophen

**Comment by LeeDroid-** [comment]
> You stated that you used Apktool v2.4.0 but, the most recent version is v2.3.4.
> 
> ~Ibuprophen

Brain fail corrected

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/commit/5a54b472d19b5a366d2a996a6150e1a47248d903 fixed.
