### ISSUE TITLE
No errors, just does not produce a working APK file

### ISSUE THREAD

**Issue by bullgates** [iBotPeaches/Apktool#1904]
### Information
1. **Apktool Version (`apktool -version`)** - tried with some versions until 2.3.4, none worked
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat
```
I'm trying to change some graphics for my ROM, but when installed in the ROM, it does not boot at all, since the APK is essential, I could not get it.
```

### Steps to Reproduce
logfiles:
decompile: https://mega.nz/#!PP5UHIBA!pzstklS9bR3Gl9zvlwgsi7-KoLmsX6F1l1G0zUUPzAg
recompile: https://mega.nz/#!beoAyKQB!3gS8ynMK6YmMG6YfYaQ8ntOODH0N6hksOsnL5TryZBw
I use Batch Apktool that makes it easy to do it without failing, I send you bellow the decompile and recompile logs. What is strange is that in the recompile log there are these strange warnings:
W: fakeLogOpen(/dev/log_system, O_WRONLY) failed
W: fakeLogOpen(/dev/log_crash, O_WRONLY) failed
W: fakeLogOpen(/dev/log_security, O_WRONLY) failed
W: fakeLogOpen(/dev/log_system, O_WRONLY) failed
W: fakeLogOpen(/dev/log_crash, O_WRONLY) failed
W: fakeLogOpen(/dev/log_security, O_WRONLY) failed
W: fakeLogOpen(/dev/log_system, O_WRONLY) failed
W: fakeLogOpen(/dev/log_crash, O_WRONLY) failed
W: fakeLogOpen(/dev/log_security, O_WRONLY) failed 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
https://mega.nz/#!fX5AmaBb!P4N1Q-qiFFK2abR8X3Eade212tzJwQlW3VtKO3sOecs

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://mega.nz/#!6CpWRQaD!LO87fXh1w9MeUNDDPashX9qsy-gIrX60IMQFuTRhO3I

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by bursoft-git** [comment]
> I use Batch Apktool that makes it easy to do it without failing, I send you bellow the decompile and recompile logs.
...
Build in EXPERT mode         : YES

Why are you using Expert mode? This mode can be used in rare cases, but in most cases you do not need to enable it.
This mode affects the structure of the APK, and it makes no sense to write bug reports here if the APK does not work.
Before writing a bug report be sure to turn off the expert mode.

**Comment by bursoft-git** [comment]
And use Batch ApkTool 3.7.2, I released it the day before yesterday)

**Comment by bullgates** [comment]
Hi @bursoft-git - sorry only in the last test and the logs are from it, but it applies to all the modes I've tried. On that specific app I can't make it work, if I use other tvsettings apps from other ROMS all of them work, only that one doesn't. I need that one because it allows Reboot into Recovery mode.

**Comment by iBotPeaches** [comment]
> it does not boot at all, since the APK is essential, I could not get it

This means the application probably has an error in the logcat. Look up outputting logcat, usually with adb - `adb logcat`, then copy the exception that happens when trying to launch the application. Attach that log here so we can dig into the real error.

**Comment by bullgates** [comment]
I guess this should be the part of the error:
```
09-28 00:56:44.310 E/AndroidRuntime(9513): FATAL EXCEPTION: main
09-28 00:56:44.310 E/AndroidRuntime(9513): Process: com.android.tv.settings, PID: 9513
09-28 00:56:44.310 E/AndroidRuntime(9513): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.android.tv.settings/com.android.tv.settings.system.PowerKeyActivity}: java.lang.ClassNotFoundException: Didn't find class "com.android.tv.settings.system.PowerKeyActivity" on path: DexPathList[[zip file "/system/priv-app/TvSettings/TvSettings.apk"],nativeLibraryDirectories=[/system/priv-app/TvSettings/lib/arm64, /system/priv-app/TvSettings/TvSettings.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2568)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.os.Looper.loop(Looper.java:154)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at java.lang.reflect.Method.invoke(Native Method)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
09-28 00:56:44.310 E/AndroidRuntime(9513): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tv.settings.system.PowerKeyActivity" on path: DexPathList[[zip file "/system/priv-app/TvSettings/TvSettings.apk"],nativeLibraryDirectories=[/system/priv-app/TvSettings/lib/arm64, /system/priv-app/TvSettings/TvSettings.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
09-28 00:56:44.310 E/AndroidRuntime(9513): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
```
Thanks!

**Comment by iBotPeaches** [comment]
Sorry a few years has passed here. I'm not sure, new versions have come out and I have no way to really triage or look at this. Part of a backlog cleanup. Closing.
