### ISSUE TITLE
Better generation of public.xml file.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#191]
Original [issue 80](https://code.google.com/p/android-apktool/issues/detail?id=80) created by Brut.alll on 2010-07-28T11:17:51.000Z:

> We could scan application code for res ids and then divide public.xml into 3 parts, preceded by comments for apktool users:
- real public resources - don't touch this!
- resources found in the code - you probably don't want to modify this.
- others - they are commented out by default, so you could remove resources without problems.

If you decode apk with -s switch, then maybe there should be a switch to generate public.xml fully (divide into above groups) or treat all non-public resources as &quot;maybe they are in the code&quot; - similarly to current solution.

If you decode apk without classes.dex file, then by default apktool will assume, that it's pure-res, so it will treat all resources as &quot;others&quot; group - they will be commented out. But there should be a switch to treat them as &quot;maybe they are in the code&quot; group.

**Comment by iBotPeaches** [comment]
Closing as this is not feasible, the goal is to remove `public.xml` (per #244) not enhance it.

**Comment by Lanchon** [comment]
> resources found in the code - you probably don't want to modify this.

IMHO this is impossible. obfuscators can replace constants with code that produces the desired IDs. so how would one go about this?

**Comment by iBotPeaches** [comment]
> > resources found in the code - you probably don't want to modify this.
> 
> IMHO this is impossible. obfuscators can replace constants with code that produces the desired IDs. so how would one go about this?

Probably why I closed it. The rewriting of resIds from dynamic code would for sure make this impossible.
