### ISSUE TITLE
Option to list available frameworks [Feature request]

### ISSUE THREAD

**Issue by knieradkiewicz** [iBotPeaches/Apktool#1913]
### Information
1. **Apktool Version 2.3.4** 

### Steps to Reproduce
1. `apktool --advanced`
It looks like there is no way to list available frameworks. 

### Feature
Since the framework files location can change, we should not rely on the implementation specific file location. It would be nice to have a feature in Apktool that allows to list installed frameworks, so when tooling around it, we could check if the desired framework is already available without need to 'reinstalling' it. This could work like this:

`apktool --list-frameworks`
`1 system`
`2 framework_custom_tag`
`3 some_random_chineese_fw`

**Comment by iBotPeaches** [comment]
Thanks for request. Seems simple enough, I'll see about getting this in v2.4.0

**Comment by iBotPeaches** [comment]
```
➜  Apktool apktool list-frameworks
I: 1.apk
I: 1-1859.apk
I: 1-1906.apk
➜  Apktool apktool empty-framework-dir --force
I: Removing 1.apk framework file...
I: Removing 1-1859.apk framework file...
I: Removing 1-1906.apk framework file...
➜  Apktool apktool list-frameworks            
➜  Apktool 
```

Will be fixed after https://github.com/iBotPeaches/Apktool/pull/2445 merged
