### ISSUE TITLE
compile log to file

### ISSUE THREAD

**Issue by Persona78** [iBotPeaches/Apktool#1929]
Hi!

It´s possibel to add a switch to print full log to file?

Im with a issue on compiling but cmd window doesn´t show the full log and i can´t see where is the error.

apktool is updated.

I try this but still don´t print the full log:
java -Xms1024M -Xmx1024M -jar "%~dp0\apktool.jar" %1 %2 %3 %4 %5 %6 %7 %8 %9"" >> log.txt

Thanks

**Comment by iBotPeaches** [comment]
You may use verbosity (`-v`) and pipe the output for stdout/stderr using regular tools. Not aware of the specifics on Windows, but this isn't a bug report.
