### ISSUE TITLE
There was a problem parsing your package

### ISSUE THREAD

**Issue by brianholle** [iBotPeaches/Apktool#1936]
### Information
1. **Apktool Version (`apktool -version`)** - Latest
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

I was attempting to decompile this APK to poke around and learn about the internal workings. After compiling I ran into some issues when reinstalling the app. I can not seem to determine if there is an issue with the way that I am decompiling the apk. I have used -R to prevent "Could not decode file, replacing by FALSE value" warnings that I get otherwise.

Could there be issues decompiling/recompiling because this is a facebook app that uses AndResGuard (discussed here: https://github.com/iBotPeaches/Apktool/issues/1719)? I do not seem to get any errors recompiling, so i figured this may not be the case. 

### Steps to Reproduce
1. apktool d "Lasso.apk" -r -o LassoDecompiled
2. apktool b LassoDecompiled -o recompiled.apk
3. https://github.com/appium/sign I used this repo to sign the application
4. Install on android: "There was a problem parsing the package."

### APK
Original apk attached
https://drive.google.com/file/d/1CnC5k74lgMOo8tQE-NVt5eecbbUyfcV6/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by ibuprophen1** [comment]
So your trying to decompile an app that reflects the inability to decode something and you used the -r -o to prevent the decoding of asset file it cannot. 

Take a look at the following link that reflects command functions for accomplishing this... 

https://ibotpeaches.github.io/Apktool/documentation/

... You may want to check out the "--no-assets" for preventing the decoding/copying of unknown asset files and also the "--copy-original" (I think that's the correct one) for keeping the apps original signature as well. 

Good Luck! :-) 


~Ibuprophen

**Comment by ikhwanreza** [comment]
> So your trying to decompile an app that reflects the inability to decode something and you used the -r -o to prevent the decoding of asset file it cannot.
> 
> Take a look at the following link that reflects command functions for accomplishing this...
> 
> https://ibotpeaches.github.io/Apktool/documentation/
> 
> ... You may want to check out the "--no-assets" for preventing the decoding/copying of unknown asset files and also the "--copy-original" (I think that's the correct one) for keeping the apps original signature as well.
> 
> Good Luck! :-)
> 
> ~Ibuprophen

how to use --copy-original command? is that in terminal?

**Comment by iBotPeaches** [comment]
> Sorry, the file you have requested does not exist.


Sorry I dropped ball. Took 2-3 years to get to this and no file. I'm sure you probably aren't waiting on a fix this long. Closing.
