### ISSUE TITLE
deletepls!..

### ISSUE THREAD

**Issue by brckhan88** [iBotPeaches/Apktool#1937]
delete pls

**Comment by ibuprophen1** [comment]
This looks like its the same/similar to a number of other 9.png/9-png issues that's been reported and is well known by @iBotPeaches. 

The following link will provide you with a search result with "Open" issues that has "9.png" and "framework" within the results. 

https://github.com/iBotPeaches/Apktool/issues?q=9.png+framework+is%3Aopen+9.png+framework

I hope it helps out in some way... :-) 


~Ibuprophen
