### ISSUE TITLE
Cannot decompile framework and systemUI on Huawei P20

### ISSUE THREAD

**Issue by arkadym** [iBotPeaches/Apktool#1939]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4 (tried earlier, also not work)
2. **Operating System (Mac, Linux, Windows)** - Windows 10 , latest
3. **APK From? (Playstore, ROM, Other)** - Huawei P20 stock 8.1.0.154 (C10)

### Stacktrace/Logcat
find logs by link
https://www.mediafire.com/folder/tyd2jszmvjvxv/

### Steps to Reproduce
1. apktool if -t P20_154 framework-res-hwext.apk
2. apktool if -t P20_154 framework-res.apk
3. apktool d -s -t P20_154 -o framework-res framework-res.apk
4. apktool d -s -t P20_154 -o SystemUI SystemUI.apk

### Frameworks
see by link above
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes, cannot decompile
2. If you are trying to install a modified apk, did you resign it? -
3. Are you using the latest apktool version? yes

**Comment by arkadym** [comment]
I would agree if apktool introduce "ignore error" switch, i just need to see structure of resources and its names. Not so important to compile it back, it would be enough to create overlays , just need to know resource names and see the images.

**Comment by iBotPeaches** [comment]
Apktool already has an "ignore" switch, it was built for unknown resources called - `--keep-broken-res` or `-k`. I haven't investigated if this is the same issue.

**Comment by arkady-marchenko** [comment]
@iBotPeaches did you check the logs, because there is NRE crash, so -k switch may not help, will try it today later.

**Comment by arkadym** [comment]
Tested it just now - apktool crashes with NRE error (see logs) independ of use -k switch

**Comment by dcionline** [comment]
emui was always broken, you can do nothing, or you find a fix for it,

**Comment by arkady-marchenko** [comment]
@dcionline yes, i understand that. But currently it is an apktool issue, because NRE means there is logic issue in codes. As result i have no unpacked resources even use -k switch.

**Comment by ehsanismail** [comment]
Keyboard mouse console cant working

**Comment by iBotPeaches** [comment]
Huawei is doing something weird. We need a plugin system. Its in roadmap - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#qualifier-plugin-system
