### ISSUE TITLE
An doc about using apktool like api,not jar file

### ISSUE THREAD

**Issue by wawo00** [iBotPeaches/Apktool#1940]
would you mind showing developers how to use apktool as api,you know there are many people use this tool to analyse apks in server,we dont need an jar file to use and we want to use api .Although we learn the whole code about apktool,we sincerely hope  you guys can provide a doc to developer to show how to use apktool like useing api

**Comment by ApatheticsAnonymous** [comment]
Have you looked into using Androguard? It may better suite your use case.

**Comment by wawo00** [comment]
i will try it, it is so helpful to me,thanks so much!!

**Comment by iBotPeaches** [comment]
We don't have any documentation for using Apktool in a library environment. I'll mark this as a feature request.

**Comment by iBotPeaches** [comment]
This is in roadmap now - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#library-system
