### ISSUE TITLE
Settings app is gone after compile Settings.apk

### ISSUE THREAD

**Issue by p3lflf** [iBotPeaches/Apktool#1944]
Hi, I have a problem here which need your help. I used Apktool decompiling Settings.apk to translate string.xml file. The process went completely well. But when I push it in System/priv-app and reboot device, the Setting app is gone. I've experienced this with different ROMs on my device. Can you please fix ? I would really appriciate this.
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM AOSP Android 9.0 https://download.pixelexperience.org/oneplus3/

### Stacktrace/Logcat

960  1975 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10008000 cmp=com.android.settings/.Settings$UsbDetailsActivity} from uid 1000

### Steps to Reproduce
1. apktool if framework-res.apk -t oneplus

2. apktool d -s Settings.apk -t oneplus
I: Using Apktool 2.3.4 on Settings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\AppData\Local\apktool\framework\1-oneplus.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

3. apktool b -c Settings -t oneplus
I: Using Apktool 2.3.4
I: Copying Settings classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy META-INF...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...

### APK & Frameworks
https://drive.google.com/file/d/1XLLquDMfGh1fKIllnncXJD1_vwW-ve0_/view

**Comment by iBotPeaches** [comment]
Doesn't appear to be a bug. You can't easily modify apks and push them into the system. Android is getting more and more secure and blocking that. Look at the logcat to determine the real cause.
