### ISSUE TITLE
Upload to google, error returned "Invalid value for: Expected a signed long, got '[806]' (class java.lang.String)">

### ISSUE THREAD

**Issue by mrakob** [iBotPeaches/Apktool#1947]
### Information
bash-3.2$ ./apktool.sh --version
2.3.4
Mac
Apk from playstore.

### Steps to Reproduce
./apktool.sh d 805.apk
Edit 805/apktool.yml
versionInfo:
    versionCode: '805' change to '806'
./apktool.sh b 805 -o 805_new.apk
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore upload_test.keystore 805_new.apk upload_test
zipalign 4 805_new.apk 805_new.signed.apk

and upload to googlestore.
HttpError 400 when requesting https://www.googleapis.com/androidpublisher/v3/applications/com.upload.test/edits/01392608794099527898/tracks/alpha?alt=json returned "Invalid value for: Expected a signed long, got '[806]' (class java.lang.String)">

I tried change in 805/apktool.yml 
versionCode: '806' to 806
and at the same problem.

May be problem converting data from apktool.yml to apk?

How change version build?

**Comment by iBotPeaches** [comment]
Just tested changing a version number and dumping my xmltree of the manifest and it has the same type. So not sure I can duplicate this.
