### ISSUE TITLE
2.3.4 apktool b -  Error: No resource found

### ISSUE THREAD

**Issue by 0pLuS0** [iBotPeaches/Apktool#1965]
Specs
OnePlus 5T
OxygenOS 5.1.7 - Oreo 8.1.0

I'm trying to change some settings in the Settings.apk for OxygenOS in res/values xml files...

If I just run only;
 apktool d Settings.apk
 apktool b Settings

I get mass amounts of messages; ```Error: No resource found```

I'm no pro here, but I read somewhere that someone mentioned before decompiling an apk, you need to put the framework-res.apk in like .local/share/apktool/framework with this cmd;

```apktool if framework-res.apk```

So then I see a 1.apk in that /path, but then when I decompile any .apk many of them also add in their own 1.apk to this /path.

Also before decompiling Settings.apk I removed any 1.apk there might of been in .local/share/apktool/framework

So I tried this, I no longer received any error messages, but when I boot the ROM with this new Settings.apk, well let's just say the ROM is a mess, nothing but a blank screen.

So if I don't make any changes and only run ``` apktool d & apktool b``` why am I getting all these error messages and I can't compile this?

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - ROM

### Steps to Reproduce
1. apktool d Settings.apk

I: Using Apktool 2.3.4 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (com.oneplus), pkgId: 5
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/foo/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

```apktool b Setting```

I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:45: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.SwitchPreference'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3874: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3879: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3898: error: Error: No resource found that matches the given name: attr 'android:enableSubtitle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3899: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3900: error: Error: No resource found that matches the given name: attr 'android:showRelative'.

```Those were only a small amount of the Error messages, there were a lot more...```

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
```The framework-res.apk is to big to post here, I uploaded it to Zippyshare, please download from there!```

https://www17.zippyshare.com/v/TSD29bMw/file.html

```Here is oneplus-framework-res.apk```

[oneplus-framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/2717601/oneplus-framework-res.apk.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.
```The apk is to big to post here, I uploaded it to Zippyshare, please download from there!```

https://www84.zippyshare.com/v/fpri1xEl/file.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Can't get past the Errors.
3. Are you using the latest apktool version? Yes

**Comment by 0pLuS0** [comment]
```SORRY``` I see now after posting this, my issue also seems to be this ```attr``` bug? Which is posted here; https://github.com/iBotPeaches/Apktool/issues/1955

~ pts/0 foo ~/Build/apktool >./apktool b Settings      
I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:45: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.SwitchPreference'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3874: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3879: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3898: error: Error: No resource found that matches the given name: attr 'android:enableSubtitle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3899: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:3900: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4084: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragmentList.Material'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4092: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragment'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4103: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceActivity'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4110: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragment.Material'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4111: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragment'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4117: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.SwitchPreference'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4204: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4267: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Information'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4363: error: Error: No resource found that matches the given name: attr 'android:enableSubtitle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4364: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4365: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4368: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4369: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4372: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4375: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4376: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4379: error: Error: No resource found that matches the given name: attr 'android:enableSubtitle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4380: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4381: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4423: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4424: error: Error: No resource found that matches the given name: attr 'android:preferenceActivityStyle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4446: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4447: error: Error: No resource found that matches the given name: attr 'android:preferenceActivityStyle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4470: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4471: error: Error: No resource found that matches the given name: attr 'android:preferenceActivityStyle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4493: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4494: error: Error: No resource found that matches the given name: attr 'android:preferenceActivityStyle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4587: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4588: error: Error: No resource found that matches the given name: attr 'android:pointerIconWait'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4589: error: Error: No resource found that matches the given name: attr 'android:pointerIconZoomIn'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4590: error: Error: No resource found that matches the given name: attr 'android:popupPromptView'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4591: error: Error: No resource found that matches the given name: attr 'android:position'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4592: error: Error: No resource found that matches the given name: attr 'android:preferenceActivityStyle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4608: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/ActiveWallpaperSettings'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4610: error: Error: No resource found that matches the given name: attr 'android:legacyLayout'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4657: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Material.Light.Dialog.FixedSize'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4666: error: Error: No resource found that matches the given name: attr 'android:enableSubtitle'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4667: error: Error: No resource found that matches the given name: attr 'android:primary'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4668: error: Error: No resource found that matches the given name: attr 'android:showRelative'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4684: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/ActiveWallpaperSettings'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4686: error: Error: No resource found that matches the given name: attr 'android:legacyLayout'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4716: error: Error: No resource found that matches the given name: attr 'android:lightY'.
W: 
W: /home/foo/Build/apktool/Settings/res/values/styles.xml:4722: error: Error: No resource found that matches the given name: attr 'android:primary'.
W:

**Comment by 0pLuS0** [comment]
@gss200610 well for starters -b  doesn't work for me, but I can run it as;

```apktool b Settings -a ./aapt``` but it doesn't help.

I also tried all the apktool versions...

**Comment by 0pLuS0** [comment]
@gss200610 well for starters -b  doesn't work for me, but I can run it as;

```apktool b Settings -a ./aapt``` but it doesn't help.

I also tried all the apktool versions...

@iBotPeaches shows this attr as a bug; https://github.com/iBotPeaches/Apktool/issues/1955

I don't suppose there's any alternatives to apktool to use, until this gets resolved? I also don't want to use the Android Studio...

I really need to compile this... 

Is it possible to decompile with apktool and then use aapt to package it back up?

I thought when there is problems with bad resources this will look past them and build it anyways?

```apktool b -c --keep-broken-res Settings``` this doesn't do anything... 

Thanks

```P.S. This is a working APK from OnePlus, they just managed to screw it up somehow but it works, all I want to do is make some simple changes to a few of the values/xml files. Isn't there a way to just get apktool to compile and ignore errors? If not this would be a really great option/feature to add in. There should  be no reason to not allow an apk to be compiled back when we know it's good.```

**Comment by 0pLuS0** [comment]
OK I managed to make progress and compile and have the OS boot with the new Settings.apk.

However, not sure why, but I can't seem to use the new Settings.apk that is in dist.

Instead I have to add the resources into the original apk.

apktool if framework-res.apk
apktool d Settings.apk
Make changes 
apktool b Settings.apk
Take resources.arsc from build directory
zip resources.arsc into the original Settings.apk
zip Settings.apk resources.arsc

Hope this helps anyone else having problems.

**Comment by iBotPeaches** [comment]
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/1955
