### ISSUE TITLE
Error occurred while disassembling class Landroid.support.multiex.MultiDex$V19; - skipping class

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#1967]
### Information
1. **Apktool Version (`apktool -version`)** 2.3.4
2. **Operating System (Mac, Linux, Windows)** Win10
3. **APK From? (Playstore, ROM, Other)** PlayStore

### Stacktrace/Logcat
The log is too long so here is text file
[batchlog.txt](https://github.com/iBotPeaches/Apktool/files/2719574/batchlog.txt)

### Steps to Reproduce
1. `apktool d (path of apk) `

### APK
Sure https://play.google.com/store/apps/details?id=com.superplanet.videogameguardians

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Sorry for the delay. These errors look upstream with smali related to Pie.

https://github.com/JesusFreke/smali/issues/621

Looks like you reported it yourself - https://github.com/JesusFreke/smali/issues/687

**Comment by ale5000-git** [comment]
It got fixed upstream.

**Comment by iBotPeaches** [comment]
> It got fixed upstream.

Thanks. I missed this. Looks like it was in v2.4.0/2.4.1.
