### ISSUE TITLE
apktool.yml doNotCompress file's extend name error 

### ISSUE THREAD

**Issue by covsno** [iBotPeaches/Apktool#1971]
### Information
1. **Apktool Version (`v2.3.4`)** -
2. **Operating System ( Windows)** -
3. **APK From? ( Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
![qq 20190103122425](https://user-images.githubusercontent.com/46336647/50623602-83886600-0f52-11e9-8abf-c9f30212d9ca.png)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
I don't understand this report. It seems like there is an apk at `assets/com.my.apk` which won't be compressed. That is working as intended.
