### ISSUE TITLE
Why apktool is not returning androidmanifest.xml?

### ISSUE THREAD

**Issue by agrawalsmart7** [iBotPeaches/Apktool#1982]
Hi, 

I didn't understand why I didn't get the androidmanifest.xml file? I use this command `apktool d file.apk`

Now the interesting thing is when I rename apk to zip and then extract it then I can see that there is an andoidmanifest.xml file available.

I don't understand why?

**Comment by iBotPeaches** [comment]
Not sure. There isn't enough information here to go on. Please remember this a bug tracker, not a support forum.

Apktool has plenty of automated tests to ensure that the `AndroidManifest.xml` is decoded, so I don't think this is an issue in Apktool.
