### ISSUE TITLE
apktool decode hangs indefinitely if ava.awt.headless is not set to true 

### ISSUE THREAD

**Issue by discoaaron** [iBotPeaches/Apktool#1997]
### Information
1. **Apktool Version** -
 - 2.3.3 and 2.3.4

2. **Operating System** -
Mac Sierra and High Sierra

3. **APK From?** -
Development apk - generated via Unity

### Steps to Reproduce
1. Using iMac or macbook pro as 'build server'
2  build job containing apktool steps is triggered remotely
3. biuld reaches the stage `apktool decode master.apk -f -o /extracted-binary`
4. build hangs indefinitely
5. ssh onto server - nothing to see
6. screen share (or physically log on) to the server
7. Notice java 'app' is present in dock (representing running apktool process), which dissapears within seconds of logging on.
8. Inspect build job - apktool decode is completed successfully, job continues as normal

**Solution**
Set an environment variable JAVA_TOOL_OPTIONS=-Djava.awt.headless=true
This suppresses the need for java.awt to use UI process.
Issue is no longer present 

Is there a reason for apktool to use java.awt? 
If so is there a reason the apktool jar isn't pre configured to run in headless mode?

This flag also stops the apktool process from stealing context away from whatever you happen to be doing while a script, including apktool is steps, is running in the background on a local dev machine. (soo frustrating!) 

Curious to hear your response even though I have a working solution.

Thanks!
Aaron

**Comment by iBotPeaches** [comment]
Hi there,

Our helper script for osx already has this line - https://github.com/iBotPeaches/Apktool/blob/master/scripts/osx/apktool#L77

> Is there a reason for apktool to use java.awt?
We need it for 9patch image deswizzling

>  If so is there a reason the apktool jar isn't pre configured to run in headless mode?
The scripts are configured to do that

I'm checking if a direct add to the Main will also works, attached below PR building.
