### ISSUE TITLE
Simple decode/build fails. W: ERROR: 9-patch image

### ISSUE THREAD

**Issue by cburns4563** [iBotPeaches/Apktool#2001]
Basic decode / build fails.

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - apkmirror.com

### Stacktrace/Logcat

I: Building resources...
W: ERROR: 9-patch image /Users/crb/gd/wyze/patchapp/wyze/res/drawable-xxhdpi/light_bg_circle_white2.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.

```
Include stacktrace here
```
Not sure how to get apktool to produce a stacktrace on an error.

### Steps to Reproduce
1. `apktool ` d wyze.apk
2. `apktool` b wyze

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
http://www.sonic.net/~crb/wyze.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yes

Thanks!

**Comment by iBotPeaches** [comment]
Looks like 9patch processing is different between aapt1/aapt2 (yay)

This works fine in aapt2, but fails with aapt1

```
➜  Bug2001 apktool b wyze --use-aapt2
I: Using Apktool 2.4.0-f997e0-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2327: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2328: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2329: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2330: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2331: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug2001/wyze/res/values/public.xml:2332: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  Bug2001 
```

(Ignore the warnings)

**Comment by cburns4563** [comment]
Cool! Thank you very much!
