### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by csetanmayjain** [iBotPeaches/Apktool#2004]
### Information
1. **Apktool Version (`apktool -version`)** - 2.0.2
2. **Operating System (Mac, Linux, Windows)** - Linux (Ubuntu 16.04)
3. **APK From? (Playstore, ROM, Other)** - Playstore

Can anyone describe in detail how to run & how to decompile apk?
Thanks

**Comment by iBotPeaches** [comment]
```
apktool d app.apk
apktool b app
```

This is a bug tracker, not for support.
