### ISSUE TITLE
Admob ads is not showing on repacked apk

### ISSUE THREAD

**Issue by leonard354** [iBotPeaches/Apktool#2010]
### Information
1. **Apktool Version (2.3.4)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes I have
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

Repacked APK, without changing anything, only decomple and recompile, ads is not showing
[Sticker Builder_rebuilt.zip](https://github.com/iBotPeaches/Apktool/files/2851930/Sticker.Builder_rebuilt.zip)

Original APK
[Sticker Builder _original.zip](https://github.com/iBotPeaches/Apktool/files/2851940/Sticker.Builder._original.zip)

**Comment by ibuprophen1** [comment]
I had found that the "Sticker Builder_rebuilt" is missing all the additional files and folders that was originally placed in the `META-INF` folder.

You will need to use the `--copy-original` option on rebuild to include these additional files & folders in this case.

May @iBotPeaches could clarify/correct this if needed. 

Good Luck! :-) 


~Ibuprophen

**Comment by leonard354** [comment]
Hello thanks for quick responding,
I've retried with original META-INF folder
the admob still not showing, 
I hope you can advice me to make it work

[Sticker Builder _rebuilt2.zip](https://github.com/iBotPeaches/Apktool/files/2854607/Sticker.Builder._rebuilt2.zip)


Thanks in advance

**Comment by ibuprophen1** [comment]
@leonard354, What exactly are you trying to accomplish? 


~Ibuprophen

**Comment by leonard354** [comment]
Hello, I want repacked apk will show admob ads just like the original apk

Regards

Leonard

**Comment by iBotPeaches** [comment]
Can you do some investigative research on this?

Take the original application - decode it (A) - rebuild it - decode it (B)

Now you have
A) - Application decoded once
B) - Application decoded via Apktool, rebuilt with Apktool, then decoded again

Compare A - B in a diff editor (MeldDiff). Look for changes. This should help isolate any issues that might explain why Admobs are not showing.

Alternatively, please use `adb logcat` while the application is running. Perhaps `AdMob` will dump some information in there about why it isn't showing. It could be tamper protection.

**Comment by 0shiraz123** [comment]
Hi WhatsUp.
I have the same issue..I'm using apk easy tool. When I flag classes.dex and resources.rcs( d -f -k -m -r -s -o) with keeping original signature it works but when i remove either one flag of these two it won't sign and of course it would also not install..Please help really need help!

**Comment by iBotPeaches** [comment]
Closing as no response from issuer and unrelated to this issue comments.
