### ISSUE TITLE
Apktool repackage apk error 9-patch image malformed.

### ISSUE THREAD

**Issue by jkryanchou** [iBotPeaches/Apktool#2013]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - MacOSX
3. **APK From? (Playstore, ROM, Other)** - https://ibotpeaches.github.io/Apktool/

### Stacktrace/Logcat

```
I: Building resources...
W: ERROR: 9-patch image /Users/base-unzip/res/drawable-xxhdpi/bg_story_dialog_count.9.png malformed.
W:        No marked region found along edge.
W:        Found along top edge.
W: ERROR: Failure processing PNG image /Users/base-unzip/res/drawable-xxhdpi/bg_story_dialog_count.9.png
...
```

### Steps to Reproduce
1. `apktool d base.apk  -o base-unzip` 
2. `apktool b base-unzip  -o unsigned.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.dropbox.com/s/4nqfsjphnm9n2lh/base.apk?dl=1

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? Yes 2.3.4

**Comment by jkryanchou** [comment]
@iBotPeaches Could you help me try out this apk? I have searched for a while on the solution, but get nothing works. While 9-patch image fixed. other exceptions would occur.

1. Try apktool repackage with `--use-aapt2` 
`apktool b base-unzip -o base-unsigned.apk --use-aapt2` it raised

```
W: /Users/base-unzip/res/values/ids.xml:10: error: <item> inner element must either be a resource reference or empty.
W: /Users/base-unzip/res/values/ids.xml:11: error: <item> inner element must either be a resource reference or empty.
W: /Users/base-unzip/res/values/ids.xml:12: error: <item> inner element must either be a resource reference or empty.
W: /Users/base-unzip/res/values/ids.xml:13: error: <item> inner element must either be a resource reference or empty.
... ...
```
And I remove `false` value from xml element. and rebuild with command above. It raised other exceptions. 

```
W: /Users/base-unzip/res/values/public.xml:1261: error: resource 'drawable/$audio_state_loading_blue_light__0' has invalid entry name '$audio_state_loading_blue_light__0'. Invalid character '$audio_state_loading_blue_light__0'.
W: /Users/base-unzip/res/values/public.xml:1262: error: resource 'drawable/$audio_state_loading_blue_light__0' has invalid entry name '$audio_state_loading_blue_light__0'. Invalid character '$audio_state_loading_blue_light__0'.
... ...
```

I wonder whether I use apktool repackage in right way.

**Comment by IgorEisberg** [comment]
Already have a solution for this committed, you can rebuild apktool yourself with this change, until it gets merged. AAPT2 is not needed.
[132a370](url)

**Comment by jkryanchou** [comment]
@IgorEisberg OK, Got it. I will try it later.

**Comment by iBotPeaches** [comment]
```
➜  2013 apktool d base.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2013 apktool b base
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2013 
```

v2.5.0 has this fixed. Both for the `$` issue and the wrong dummy resources (false).
