### ISSUE TITLE
Ignore smali that contains file name that exceeded +255 char.

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#2023]
There are smalis with over 255 char names gets created on each folders. This cause errors because NTFS can only support max 255 char i guess.

Can you make it ignore those smalis or auto rename to simple names?

![image](https://user-images.githubusercontent.com/45212341/53580860-cc3c5400-3b7c-11e9-95c7-a759aefb931c.png)

### Information
1. **Apktool Version (`apktool -version`)** 2.3.4 
2. **Operating System (Mac, Linux, Windows)** Win10
3. **APK From? (Playstore, ROM, Other)** Playstore

### Stacktrace/Logcat
[new 1.txt](https://github.com/iBotPeaches/Apktool/files/2915848/new.1.txt)

### Steps to Reproduce
1. `apktool d`

### APK
 https://apkpure.com/goddess-kiss/com.flerogames.GK/download/61-APK?from=versions%2Fversion

### Questions to ask before submission
3. Are you using the latest apktool version? Yes

**Comment by libDataso** [comment]
Same problem on Blank City https://play.google.com/store/apps/details?id=com.flerogames.aos.espher. Even worse, dexes are too much splitted and there are 4 scramble names smalis each folders. Is there gonna be fixed?

**Comment by 241d2** [comment]
Lol even worse.
That game you showed is the same company that made this kind of weird protection

**Comment by iBotPeaches** [comment]
Yeah we need a remap table for those OS that have such a small path length. I'm tracking this at #1460. So closing as duplicate.
