### ISSUE TITLE
Decompile -> Compile Apps for target SDK 28 crashes after start

### ISSUE THREAD

**Issue by susameca** [iBotPeaches/Apktool#2025]
### Information
1. **Apktool Version (`apktool -version`)** - Latest from github compiled
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. Using APK easy tool simply decompile and compile and signing with no changes. App don't run on devices.

### Frameworks
No Framework

### APK
https://mega.nz/#!GEQDAaKA!fFzh3UhTjlXTuf_LvXmVI4Sz9hkH-NQVLxRfmcnwDeY
Old version ( Working Compiled ) -> https://mega.nz/#!TNwxlCZS!BcF6lAYqBtWuAKth7JHg9MKeeC5MOLKRRmGAxSFQGvY
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - Yes
3. Are you using the latest apktool version? - Yes

Previous versions of the App was for target SDK 25 and the compiling was working. After this version the target SDK is 28 and after decompiling and compiling it again with no changes the app is crashing after it's opened. Is the issue in the apktool or the app itself?

**Comment by iBotPeaches** [comment]
Since my time is so limited now - I can't really run apps on devices and extract stacktraces and triage. That lies on you (the reporter). If you can meet me with those details we can investigate further to see if its a resource packed improperly, etc.

Closing.
