### ISSUE TITLE
Build failed with 'com.github.hierynomus.license' not found

### ISSUE THREAD

**Issue by WanderMax** [iBotPeaches/Apktool#2035]
When I build via git bash, it pops error as below:

$ ./gradlew
Starting a Gradle Daemon (subsequent builds will befaster)

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\apktool\Apktool_github\build.gradle' line: 29

* What went wrong:
Plugin [id: 'com.github.hierynomus.license', version: '0.14.0'] was not found in  any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.hierynomus.
license:com.github.hierynomus.license.gradle.plugin:0.14.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.
                                                                                                         
* Get more help at https://help.gradle.org

**Comment by iBotPeaches** [comment]
```
➜  Apktool git:(master) ./gradlew build shadowJar proguard --refresh-dependencies

> Configure project :
Building SNAPSHOT (master): cc194d

BUILD SUCCESSFUL in 17s
20 actionable tasks: 4 executed, 16 up-to-date
➜  Apktool git:(master) 
```
Couldn't replicate this and I even cleared my dependency cache.
