### ISSUE TITLE
Build form source in alpine

### ISSUE THREAD

**Issue by Hax4us** [iBotPeaches/Apktool#2039]
Hey I want to build apktool in alpine Linux and I tried simple steps of builds but no success here is error 
`brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_5653805714696976669.tmp, p, --forced-package-id, 127, --no-version-vectors, -F, /tmp/APKTOOL8123756799712552897.tmp, -0, arsc, -0, arsc, -S, /tmp/BRUT9115121395262158929.tmp/issue1594-new/res, -M, /tmp/BRUT9115121395262158929.tmp/issue1594-new/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
`

Is it trying to execute prebuilt binaries like aapt or aapt2 ?

**Comment by iBotPeaches** [comment]
It indeed uses the prebuilt binaries to test functionality. I just cleaned my install on unix and built it with no errors, so can't replicate this.

**Comment by Hax4us** [comment]
ohh now i got it..it means i will have to recompile aapt in alpine because alpine has musl instead of glibc
