### ISSUE TITLE
Decompiled Folder Structures

### ISSUE THREAD

**Issue by mkvGuy** [iBotPeaches/Apktool#2040]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Win10
3. **APK From? (Playstore, ROM, Other)** - https://ibotpeaches.github.io/Apktool/

When I use the tool, the folder structures are changed and the recompiled apk no longer works.  is there a way to keep the folder structures intact  during the process?

The only way to keep the folder structures is not to decompile anything, which defeats the purpose

Please fix

Thanx
### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Not enough details to go on here. The tool maintains folder structure with tests to prove this.

**Comment by mkvGuy** [comment]
I included a zip file that includes the actual folder structure within the res folder and the folder structure in the same folder after using apktool.  Unfortunatly the apk is proprietary and can't upload it.  the folder structure is only changed when I do a full decompile and decode
