### ISSUE TITLE
brut.common.BrutException: could not exec (exit code = 1): 

### ISSUE THREAD

**Issue by bensh** [iBotPeaches/Apktool#2043]
### Information
1. 2.4.0
2. Windows 10
3. Badoo

### Stacktrace/Logcat

```
W: fakeLogOpen(/dev/log_crash) failed
W: fakeLogOpen(/dev/log_crash) failed
W: fakeLogOpen(/dev/log_stats) failed
W: fakeLogOpen(/dev/log_stats) failed
W: D:\com.badoo.mobile_5.107.0(1850)\apktool\res\values\public.xml:57: error: Public symbol array/debug_referrers declared here is not defined.
W: D:\output\com.badoo.mobile_5.107.0(1850)\apktool\res\values\public.xml:58: error: Public symbol array/payedFeaturesPreloader declared here is not defined.
W: D:\output\com.badoo.mobile_5.107.0(1850)\apktool\res\values\public.xml:59: error: Public symbol array/pnb_rainbowColours declared here is not defined.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\bensh\AppData\Local\Temp\brut_util_Jar_8375843589490336878.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 26, --version-code, 1850, --version-name, 5.107.0, --no-version-vectors, -F, C:\Users\bensh\AppData\Local\Temp\APKTOOL2482320189570918491.tmp
```

### Steps to Reproduce
1. `apktool b /apktool/ -o badoo_new.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.badoo.mobile&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a didn't build
3. Are you using the latest apktool version? yes

**Comment by dohn** [comment]
Same problem here. For some reason an error is thrown pointing to \res\values\public.xml file for every line  where a Public symbol array is declared.

**Comment by dohn** [comment]
The APK app that generates errors is Apk Analyzer 2.6.3 at
https://play.google.com/store/apps/details?id=sk.styk.martin.apkanalyzer&hl=ro

**Comment by bensh** [comment]
I have also tried the 
`apktool empty-framework-dir --force`

and still errors

**Comment by iBotPeaches** [comment]
Not sure what output this is:

```
W: fakeLogOpen(/dev/log_crash) failed
W: fakeLogOpen(/dev/log_crash) failed
W: fakeLogOpen(/dev/log_stats) failed
W: fakeLogOpen(/dev/log_stats) failed
```

Apktool does not do that. So closing.
