### ISSUE TITLE
Android Q recompile issue

### ISSUE THREAD

**Issue by Tulsadiver** [iBotPeaches/Apktool#2045]
### Information
This is more of an FYI as I know this is brand new and not an official firmware yet.
1. **Apktool Version (`apktool -version-2.4.0`)** -
2. **Operating System ( Windows)** -
3. **APK From? (Stock)** -

### Stacktrace/Logcat
I: Using Apktool 2.4.0
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Q"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at brut.androlib.res.AndrolibResources.mapSdkShorthandToVersion(AndrolibResources.java:637)
        at brut.androlib.res.AndrolibResources.getMinSdkVersionFromAndroidCodename(AndrolibResources.java:618)
        at brut.androlib.Androlib.build(Androlib.java:290)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:247)
        at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. `apktool b SystemUIGoogle

### Frameworks
See below

### APK
https://www.androidfilehost.com/?fid=1395089523397917544

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
You have to at least fix the one bad .9png file before there is even a chance for this to recompile.
2. If you are trying to install a modified apk, did you resign it?
No
3. Are you using the latest apktool version?
Yes, and tried others as well

**Comment by memphise** [comment]
the same error,  may I ask when will apktool support android Q？

**Comment by Tulsadiver** [comment]
I also found an error in how array.xml was decoded.  It appears as styles instead of string arrays and without values.

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="animator_duration_scale_entries" />
    <style name="animator_duration_scale_values" />
    <style name="app_process_limit_entries" />
    <style name="app_process_limit_values" />
    <style name="battery_labels" />
    <style name="battery_options" />
    <style name="batterymeter_bolt_points" />
    <style name="batterymeter_color_levels" />
    <style name="batterymeter_color_values" />
    <style name="batterymeter_plus_points" />
    <style name="bluetooth_a2dp_codec_bits_per_sample_summaries" />
    <style name="bluetooth_a2dp_codec_bits_per_sample_titles" />
    <style name="bluetooth_a2dp_codec_bits_per_sample_values" />
    <style name="bluetooth_a2dp_codec_channel_mode_summaries" />
    <style name="bluetooth_a2dp_codec_channel_mode_titles" />
    <style name="bluetooth_a2dp_codec_channel_mode_values" />
    <style name="bluetooth_a2dp_codec_ldac_playback_quality_summaries" />
    <style name="bluetooth_a2dp_codec_ldac_playback_quality_titles" />
    <style name="bluetooth_a2dp_codec_ldac_playback_quality_values" />
    <style name="bluetooth_a2dp_codec_sample_rate_summaries" />
    <style name="bluetooth_a2dp_codec_sample_rate_titles" />
    <style name="bluetooth_a2dp_codec_sample_rate_values" />
    <style name="bluetooth_a2dp_codec_summaries" />
    <style name="bluetooth_a2dp_codec_titles" />
    <style name="bluetooth_a2dp_codec_values" />
    <style name="bluetooth_audio_active_device_summaries" />
    <style name="bluetooth_avrcp_version_values" />
    <style name="bluetooth_avrcp_versions" />
    <style name="bt_hci_snoop_log_entries" />
    <style name="bt_hci_snoop_log_values" />
    <style name="clock_options" />
    <style name="color_mode_descriptions" />
    <style name="color_mode_ids" />
    <style name="color_mode_names" />
    <style name="config_cameraLaunchGestureVibePattern" />
    <style name="config_doze_brightness_sensor_to_brightness" />
    <style name="config_doze_brightness_sensor_to_scrim_opacity" />
    <style name="config_notification_snooze_times" />
    <style name="config_pluginWhitelist" />
    <style name="config_systemUIServiceComponents" />
    <style name="config_systemUIServiceComponentsPerUser" />
    <style name="debug_hw_overdraw_entries" />
    <style name="debug_hw_overdraw_values" />
    <style name="elmyra_blocking_system_keys" />
    <style name="elmyra_lower_threshold" />
    <style name="elmyra_slope_sensitivity" />
    <style name="elmyra_time_window" />
    <style name="elmyra_upper_threshold" />
    <style name="enable_opengl_traces_entries" />
    <style name="enable_opengl_traces_values" />
    <style name="hdcp_checking_summaries" />
    <style name="hdcp_checking_titles" />
    <style name="hdcp_checking_values" />
    <style name="lockscreen_num_pad_klondike" />
    <style name="nav_bar_button_values" />
    <style name="nav_bar_buttons" />
    <style name="nav_bar_layouts" />
    <style name="nav_bar_layouts_values" />
    <style name="overlay_display_devices_entries" />
    <style name="overlay_display_devices_values" />
    <style name="recents_onboarding_blacklisted_packages" />
    <style name="select_logd_size_lowram_titles" />
    <style name="select_logd_size_summaries" />
    <style name="select_logd_size_titles" />
    <style name="select_logd_size_values" />
    <style name="select_logpersist_summaries" />
    <style name="select_logpersist_titles" />
    <style name="select_logpersist_values" />
    <style name="show_non_rect_clip_entries" />
    <style name="show_non_rect_clip_values" />
    <style name="simulate_color_space_entries" />
    <style name="simulate_color_space_values" />
    <style name="track_frame_time_entries" />
    <style name="track_frame_time_values" />
    <style name="transition_animation_scale_entries" />
    <style name="transition_animation_scale_values" />
    <style name="tts_demo_string_langs" />
    <style name="tts_demo_strings" />
    <style name="tts_rate_entries" />
    <style name="tts_rate_values" />
    <style name="tv_pip_settings_class_name" />
    <style name="type_clock_hours" />
    <style name="type_clock_minutes" />
    <style name="usb_configuration_titles" />
    <style name="usb_configuration_values" />
    <style name="wifi_status" />
    <style name="wifi_status_with_ssid" />
    <style name="window_animation_scale_entries" />
    <style name="window_animation_scale_values" />
</resources>

**Comment by iBotPeaches** [comment]
The original error here is quite easy to fix and I'll do that real quick, its just a mapping between "Q" -> 10,000.

The other comments in here are not related and been hidden.

**Comment by Tulsadiver** [comment]
Thank you, sir!
