### ISSUE TITLE
WARNING: Could not write to (...), using /tmp instead

### ISSUE THREAD

**Issue by neworld** [iBotPeaches/Apktool#2048]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux (from ArchLinux AUR packages)

### Steps to Reproduce
1. Install `apktool` on new PC (or delete `~/.local/share/apktool/framework`)
2. Run any decompilation, like `apktool d app.apk`

### Expectation

Any local folder and files should be created if missing like other programs.

### Fix warning by yourself

```
mkdir -p ~/.local/share/apktool/framework
```

**Comment by iBotPeaches** [comment]
How the hell did this not break tests, this is maddening.

Thanks for finding this.

**Comment by neworld** [comment]
Thanks for fixing!

**Comment by Lanchon** [comment]
cool, came here to report this. thanks!! :)

**Comment by andrewodri** [comment]
Came to report... Stayed to ask if it might be possible to get this bundled into a patch release 🙏

(And of course say thanks for all the great work maintaining this package!)

**Comment by aldk98** [comment]
For me on Ubuntu 18.04, this issue still exist even after giving full permission (777)  to apktool and apktool.jar.

I gave full permission to the created directory to fix the warning.

Not exactly best practice, but it worked.
