### ISSUE TITLE
Successfully recompiled app with no changes but partially working only

### ISSUE THREAD

**Issue by chaitut715** [iBotPeaches/Apktool#2052]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** -Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logical
```
apktool d Gruveo.apk --frame-path /Users/chaitanya/devspace/mobile/xda/modtool
I: Using Apktool 2.4.0 on Gruveo.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/chaitanya/devspace/mobile/xda/modtool/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

apktool b Gruveo -o Gruveo.test.apk --frame-path /Users/chaitanya/devspace/mobile/xda/modtool
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```
### Steps to Reproduce
```
1. apktool d Gruveo.apk --frame-path /Users/chaitanya/devspace/mobile/xda/modtool
2. apktool b Gruveo -o Gruveo.test.apk --frame-path /Users/chaitanya/devspace/mobile/xda/modtool
3. Sign
4. adb install Gruveo.test.apk
5. App opening successfully but you can't call
```
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://apkpure.com/gruveo-magic-call-link/com.gruveo.gruveo_android

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by oscar0812** [comment]
Any updates on this? I'm having the same issue. I decompile and compile (with no changes) and the app stays on the splash screen. I've signed the app and tried running decompiling and compiling with -r.

**Comment by iBotPeaches** [comment]
Would need `adb logcat` to triage. I don't unfortunately have time in this space to download apks, install them, triage them and more. 

Sorry.
