### ISSUE TITLE
New apps with android:appCategory set in AndroidManifest.xml fail to build

### ISSUE THREAD

**Issue by nmagit** [iBotPeaches/Apktool#2055]
new apps with android:appCategory ( for Android O ) set in AndroidManifest.xml fail to build
if android:appCategory field is deleted apk build ok .
 I think is ok to delete that field if not using O

[https://developer.android.com/reference/android/R.attr.html#appCategory](url)

error: 
No resource identifier found for attribute 'appCategory' in package 'android'
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

**Comment by ibuprophen1** [comment]
How are you reflecting Oreo within the AndroidManifest.xml file and are you also making these changes within the apktool.yml file as well. 

I'm not asking how for myself (as I already know thi) but, I'm asking what you did yourself to see if It's correct and, hopefully, to help you out as well. 


~Ibuprophen

**Comment by iBotPeaches** [comment]
I can't replicate this. Attached commit adds that property to both our aapt1/aapt2 tests. I imagine this is related to some framework issue. Ensure you are using the latest framework.

```
apktool empty-framework-dir
```
may be of use.
