### ISSUE TITLE
Errors occurred while decompiling APK

### ISSUE THREAD

**Issue by coolsasuke** [iBotPeaches/Apktool#2060]
### Information
1. **Apktool Version (`2.4.0`)
2. **Operating System (`Windows`)
3. **APK From? (`Playstore`)

App seems to be obfuscated. However this error below keep showing up when i try to decompile the apk. Link for the app is below the post. Please help me out. Thanks in advance!

```
I: Using Apktool 2.4.0 on llm.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\**\AppData\Local\Temp\1.apk
I: Regular manifest package...
[Fatal Error] :2:93: Attribute "android:" was already specified for element "manifest".
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
        at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:704)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
```
### APK
If this APK can be freely shared, please upload/attach a link to it.

https://play.google.com/store/apps/details?id=hk.gogovan.GoGoDriver

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? -
3. Are you using the latest apktool version? Yes

**Comment by ibuprophen1** [comment]
This looks like a few things going on in a cascading way regarding the Chinese/Hong Kong Characters. 

It took me a little while to to locate since it's only available within a specific region... 

[hk.gogovan.GoGoDriver-5.19.2.apk.zip](https://github.com/iBotPeaches/Apktool/files/3077951/hk.gogovan.GoGoDriver-5.19.2.apk.zip)

I had attached a copy of the Apk that I had to zip up to upload. 

Good Luck! 


~Ibuprophen

**Comment by coolsasuke** [comment]
Hi @ibuprophen1, thanks for replying. As for what you can see from the app, it consists tons of Chinese characters, but other than that, is the apk seem somehow obfuscated? I am actually new to apk editing and would like to try unpinning SSL cert myself but could not proceed due to the error occured as shown above. I would appreciate it if anyone can show me the right path to remove cert pinning for majority of the apps out there. Thank you! :)

**Comment by marco709394** [comment]
@coolsasuke hey I may have found a solution on your particular interested apk, would u mind email me by liarc740@gmail.com ?

**Comment by marco709394** [comment]
@coolsasuke hey bro, email me
