### ISSUE TITLE
Question Regarding BundleTool Implementation... 

### ISSUE THREAD

**Issue by ibuprophen1** [iBotPeaches/Apktool#2065]
@iBotPeaches, I was just wondering if you had any plans for implementing the following BundleTool (jar) within the Apktool? 

https://github.com/google/bundletool

Thanks a bunch! :-) 

~Ibuprophen

**Comment by iBotPeaches** [comment]
Not currently on my focus. It seems pretty specialized and Apktool doesn't need any of those features. By the time apktool has an application, it already has done those steps.
