### ISSUE TITLE
version 2.4 Unknown problem

### ISSUE THREAD

**Issue by sheep0704** [iBotPeaches/Apktool#2073]
**Information**
Apktool Version (apktool -version) - 2.4.0
Operating System (Mac, Linux, Windows) - Windows
APK From? (Playstore, ROM, Other) - Site

**Stacktrace/Logcat**
* JAVA Decompiler -  Search 

**Exception:**
An unhandled exception occurred.Press "abort" to terminate the  program.
"Retry" to exit the program normally and "Ignore" to try to continue.

Versions below 2.4 will not appear .

**Comment by ibuprophen1** [comment]
This looks like a "Software Specific" issue that's using @iBotPeaches Apktool based upon the information you had provided (little to none). 

It does look familiar to the current issue experienced on the APK Easy Tool software by @evildog1 (also being addressed by evildog1 as well). 


~Ibuprophen

**Comment by iBotPeaches** [comment]
Yeah no idea what this report means. Apologies, but nothing I can do about this.
