### ISSUE TITLE
Please rename class, method, variable ...

### ISSUE THREAD

**Issue by ngochoanqb** [iBotPeaches/Apktool#2076]
Please change the name to:
Class: a => C00001a; b => C00002b ...
Method: a => m0001a; b => m0003b ...
Variable: a => f0001a, b => f0001b ...
Because in a class there are many "a" namesake methods so it is easy to confuse and compile errors. The variables are the same, especially the variable "i". It will be duplicated if there is a "for" loop inside.
The classes located in the java directory should be put inside p000.
JADX has done very well in this recent update.
Please follow.

**Comment by iBotPeaches** [comment]
We will not be doing this, we only parse what baksmali returns.
