### ISSUE TITLE
String values are changed to Scientific format

### ISSUE THREAD

**Issue by prabhu-bsft** [iBotPeaches/Apktool#2077]
### Information
1. **Apktool Version (`apktool -version`)** - v2.4.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** -Other

### Steps to Reproduce
1. Have a "meta-data" tag in AndroidManifest 
e:g &lt;meta-data android:name="com.apktool.testapp.apikey" android:value="5eef3a239418297932023ee003c2952bce414"/&gt;

2. Decompile the generated APK (apktool d file.apk)

3. Update the value of <meta-data> to a different value
&lt;meta-data android:name="com.apktool.testapp.apikey" android:value="9986016551"/&gt;

4. Build the APK using apktool (apktool b file.apk)

5. Decompile the APK using apktool and open the AndroidManifest.xml. The value 9986016551 is changed to 9.9860163E9.
&lt;meta-data android:name="com.apktool.testapp.apikey" android:value="9.9860163E9"/&gt;

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes in this case there is no issues.
3. Are you using the latest apktool version? Yes, v2.4.0 Beta

**Comment by iBotPeaches** [comment]
Nothing Apktool can do about this. You are putting an integer over the bounds. There are some tricks around this like using - `\ ` into the prefix to force it as a String.

Take a look at this old ticket for reference - https://github.com/iBotPeaches/Apktool/issues/767
