### ISSUE TITLE
Error C:\Python27\ was unexpected at this time

### ISSUE THREAD

**Issue by dzhenway** [iBotPeaches/Apktool#2078]
### Information
1. **Apktool Version (`apktool -version`)** - s.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Pro 64
3. **APK From? (Playstore, ROM, Other)** - APK Pure

### Steps to Reproduce
1. C:\Users\xxx>apktool -version
C:\Python27\ was unexpected at this time.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Apktool has no Python, so not sure what is report is about.

**Comment by kzu** [comment]
Heya, given #1488 , this one, and the one I'm getting (`\Microsoft was unexpected at this time.`), I suspect there might be an issue in the way some `%PATH%` envvar parsing is done somewhere (perhaps in `apktool` itself? maybe some dependency of yours?). Given three exact instances (counting my case) of the same weird error with something apparently totally unrelated, but all involving some path, I'd say https://github.com/iBotPeaches/Apktool/issues/1488#issuecomment-508882386 was onto something...
