### ISSUE TITLE
invalid flag 

### ISSUE THREAD

**Issue by DarthDanAmesh** [iBotPeaches/Apktool#2079]
### Information
1. **Apktool Version  2.4.0
2. **Operating System - GNU/Linux

### Issue while running 'apktool' on Kali:
javac: invalid flag: -Xmx512M

### When executing the apktool with or without the options e.g 'apktool d' i get an error:
$ apktool 
javac: invalid flag: -Xmx512M
Usage: javac <options> <source files>
use -help for a list of possible options

**Comment by iBotPeaches** [comment]
`javac` should not be getting those flags. That is reserved for `java`. This is not a bug in our scripts, so must be a configuration issue on your end.
