### ISSUE TITLE
the source can't be build with jdk11 on win10

### ISSUE THREAD

**Issue by eriklu** [iBotPeaches/Apktool#2086]
when I build the source on win10-x64 with jdk-11.0.2, I encounter the issue below.

can't find reference java.long.Object and other base java class.

T think the reason is that jdk-11 not install a jre directory in the JAVA_HOME directory , then the build script can't find rt.jar.

**Comment by ibuprophen1** [comment]
The JDK doesn't install the JRE. The JRE is a separate java software. 

https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html


~Ibuprophen

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by iBotPeaches** [comment]
Looks like this started around JDK9 where they changed away from `jt.jar` - https://sourceforge.net/p/proguard/bugs/551/

Since it looks like JDK9 is EOL and JDK10 is about to be, just need to fix this for 9+ and I'm sure it'll fix 11.
