### ISSUE TITLE
May I Get A Copy Of Your Prebuild AAPT Version Source Code?

### ISSUE THREAD

**Issue by eriklu** [iBotPeaches/Apktool#2087]
The Apk is obfuscated and the decompiled resouce xml contains 3-byte utf-8 char as the xml element name. The official aapt source code don't support this kind of xml file(myabe it's not allowed in XML standard). 
 I found the aapt use a EXPAT as its XML parser. The function utf8_isName3 in xmltoc.c file is used to determine the 3 byte char is a allowed as a name.
I try to modify the aapt source code, build my aapt and replace the prebuild aapt in apktool.jar but I enconter a problom:
    W: ERROR: Unknown option '--forced-package-id'
I don't find this option in aapt souce code.

Maybe you modify the aapt code:
I run the  command: aapt.exe v
the output is:
Android Asset Packaging Tool, v0.2-eng.ibotpe.20190216.092407

I try to patch the prebuild appt.exe, I found the utf8_isName3 function is inline into a big function and I can't patch easily and avoid crash.

maybe I can't get a copy of your source and build my version.

Of course  I will  appreciate you deeply if you can offer the support this kind xml file.

below is the snippet of xml file :
<?xml version="1.0" encoding="utf-8"?>
<o.ʰ android:paddingLeft="@dimen/component_padding" android:paddingTop="@dimen/component_padding" android:paddingBottom="@dimen/component_padding" android:layout_width="fill_parent" android:layout_height="wrap_content"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">
    <o.ڒ android:id="@id/subheader_name" android:layout_marginRight="@dimen/component_padding" android:text="@string/name" app:layout_constraintLeft_toLeftOf="parent" app:layout_constraintRight_toRightOf="parent" app:layout_constraintTop_toTopOf="parent" style="@style/SubHeader.Secondary.Top" />
    ......
</o.ʰ>

the complete file is attached.
[track_screen_edit_inner.zip](https://github.com/iBotPeaches/Apktool/files/3239411/track_screen_edit_inner.zip)

Thanks your GREAT work again.

**Comment by iBotPeaches** [comment]
It is right here - https://github.com/iBotPeaches/platform_frameworks_base, branch `apktool_9.0.0`.

May you share the patch for the utf8 name?
