### ISSUE TITLE
android namespace conflict

### ISSUE THREAD

**Issue by mgood7123** [iBotPeaches/Apktool#2093]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - none

`android.util.TypedValue`, `android.util.AttributeSet`, and `android.content.res.XmlResourceParser` conflicts with the ones located in AOSP SDK api's

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
This is intentional, but I did notice we wiped the copyright on the AOSP files which is a big no-no. So I'll leave this open to fix that and instruct our copyright script to ignore that namespace.

**Comment by mgood7123** [comment]
> This is intentional, but I did notice we wiped the copyright on the AOSP files which is a big no-no. So I'll leave this open to fix that and instruct our copyright script to ignore that namespace.

why intentional?

**Comment by iBotPeaches** [comment]
> > This is intentional, but I did notice we wiped the copyright on the AOSP files which is a big no-no. So I'll leave this open to fix that and instruct our copyright script to ignore that namespace.
> 
> why intentional?

Because we did not write that code. It came from AOSP, so match the namespace. Unfortunately as I said - my copyright code wiped the copyright on those.

**Comment by iBotPeaches** [comment]
Fixed the copyright headers on 3rd party files, thanks for the catch!
