### ISSUE TITLE
could not decode file

### ISSUE THREAD

**Issue by colorlight** [iBotPeaches/Apktool#2094]
I have some problems when deocding the WeChat app with latest version apktool
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore 
### Stacktrace/Logcat

```
S: Could not decode file, replacing by FALSE value: layout/lucky_prepare_ui2.xml
S: Could not decode file, replacing by FALSE value: drawable/sight_pre_view_drawable_click.xml
S: Could not decode file, replacing by FALSE value: drawable/game_level_bg.xml
S: Could not decode file, replacing by FALSE value: drawable/app_brand_profile_header_divider.xml
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/luckymoneysnsreadlogo.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/page_down_dark_xxhdpi.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/face_rect_string_horizontal.png
S: Could not decode file, replacing by FALSE value: drawable/fav_search_pic_selector.xml
```

### Steps to Reproduce
1. `apktool d weixin704.apk `

### APK
apk link on the google drive
https://drive.google.com/open?id=1GxzL6SetClJzrLFBceF_TOy12Nlk9p50

**Comment by iBotPeaches** [comment]
Not sure in short. Long running bug. Always seems to affect tencent/qq apps.

See #1427, #1423, #1499, #2235

Closing as duplicate.
