### ISSUE TITLE
how to compile apt prebuilt binaries

### ISSUE THREAD

**Issue by mgood7123** [iBotPeaches/Apktool#2096]
how can i recompile the https://github.com/iBotPeaches/platform_frameworks_base for producing the aapt/aapt2 binaries?, as the ones from https://github.com/thejunkjon/android-tools do not have the '--forced-package-id' option available

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/blob/master/INTERNAL.md#building-aapt-binaries
