### ISSUE TITLE
An odd request 

### ISSUE THREAD

**Issue by Lanchon** [iBotPeaches/Apktool#2107]
hi Connor,

i'm making some tools to mod android apps. they use apktool to disassemble resources (thanks!). but they operate at a higher level of abstraction, allowing complex stuff like, say, adding android libraries (code + resources) to the build. under the hood they work by hooking the android gradle build system, which means that app packing is done directly via the sdk AAPT2 binary and not though "apktool build ...".

but this fails for malformed resources, which is one reason you had to patch AAPT2. and my solution is to reuse your patched AAPT2 binaries for the build (thanks yet again! :) ).

so here is my request:

my tools extract the patched AAPT2 binaries from apktool on demand (because the user supplies their chosen version of apktool). please, if at all possible, don't needlessly change the directories and file names of these binaries within apktool in the future, so as to not break my tools. (ie:  the prebuilt directory in the apktool jar.)

thank you very much!

**Comment by iBotPeaches** [comment]
Wasn't needless, had to cut down directory size in order to work on Windows and TravisCI due to length. I would recommend a mapping table for Apktool versions, as internal file locations isn't exactly a public API.

If I don't have to, I'll prevent moving those again.

**Comment by Lanchon** [comment]
thanks! the extractor doesn't know the version of apktool it is working on. i can handle past changes by looking into the zip, don't worry. as for the future...

> If I don't have to, I'll prevent moving those again.

that would be perfect, thanks!!
