### ISSUE TITLE
jarsigner: java.lang.SecurityException: SHA-256 digest error for resources.arsc

### ISSUE THREAD

**Issue by abrala** [iBotPeaches/Apktool#2110]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat
Systemui doesn't load on startup
```
jarsigner: java.lang.SecurityException: SHA-256 digest error for resources.arsc
```

### Steps to Reproduce
1. apktool d *.apk
2. Do modifications (res/values/strings)
3. apktool b -c *
4. jarsigner -verify -verbose new.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
Files framework-res and systemui: https://mega.nz/#!JL4gxSLQ!0bRdP29V88BZQL58k1mREScrY8RFqcvtRvRtCHzfenY
### APK
If this APK can be freely shared, please upload/attach a link to it.
Above
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - Keeping original signature
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
`-c` is scheduled for deprecation for this reason. Getting more difficult to re-use existing signatures
