### ISSUE TITLE
error: No resource identifier found for attribute 'foregroundServiceType' in package 'android'

### ISSUE THREAD

**Issue by megapro17** [iBotPeaches/Apktool#2124]
### Information
1. 2.4.0
2. Windows
3. Playstore

### Stacktrace/Logcat

```
W: AndroidManifest.xml:136: error: No resource identifier found for attribute 'foregroundServiceType' in package 'android'
```

This problem appears when I try to build apk, without any modifications
I tried `apktool empty-framework-dir --force`, no luck

**Comment by matthuisman** [comment]
I get something similar when the AndroidManifest.xml has android:isSplitRequired="true" in it

**Comment by iBotPeaches** [comment]
Might be a new property that requires a framework. Due to no issue template, there is not enough information for me to triage this.

Please ensure you follow the issue template. You are welcome to submit another report.

**Comment by ifengchao** [comment]
Get the same error  AndroidManifest.xml:17: error: No resource identifier found for attribute 'isSplitRequired' in package 'android'

**Comment by sajadshokri** [comment]
https://developer.android.com/reference/android/R.attr.html#isSplitRequired
