### ISSUE TITLE
64-bit version of apktool ?

### ISSUE THREAD

**Issue by hieu291** [iBotPeaches/Apktool#2125]
How to adding 64bit version to apktool ? 
GooglePlay just send a annoucent about 64bit version .. And Apktool can decompile and recompile 64bit version of app ? 

### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Apktool includes 64bit tools when needed and does not touch shared objects which normally might be different based on the bitness. Closing.

**Comment by icmacdonald** [comment]
I've also run into this problem. build using apktool but get

This release is not compliant with the Google Play 64-bit requirement.
The following APKs or app bundles are available to 64-bit devices, but they only have 32-bit native code: [17002]
Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code that it needs. This avoids increasing the overall size of your app.

Then read this: https://developer.android.com/google/play/requirements/64-bit#build-with-64-bit

But don't find a gradle.build file?

**Comment by iBotPeaches** [comment]
@icmacdonald - That doesn't really make sense. Apktool just disassembles applications - it cannot add 64bit support, nor can really you. That happens at original build time.
