### ISSUE TITLE
Multiple annotations of type Ldalvik/annotation/EnclosingClass

### ISSUE THREAD

**Issue by u8-xiaohei** [iBotPeaches/Apktool#2152]
Information
Apktool Version (apktool -version) - 2.4.0
Operating System (Mac, Linux, Windows) -Windows 7
APK From? (Playstore, ROM, Other) - exported from AndroidStudio 3.4

1、I used [apktool d] to decompile the apk with the latest version(2.4.0)
2、then use baksmali-2.2.6.jar to convert a dex file to smali format. and merged into the smali folder.
3、then use [apktool b] to rebuild the apk, but had the following error:

```
ERROR::Au 16, 2019 1:12:40  brut.androlib.Androlib build

INFO: Using Apktool 2.4.0

Au 16, 2019 1:12:40  brut.androlib.Androlib buildSourcesSmali

INFO: Smaling smali folder into classes.dex...


ERROR::..\..\temp\workspace\game1\meizusingle48\decompile\smali\com\meizu\gamesdk\update\d$a.smali[15,0] Multiple annotations of type Ldalvik/annotation/EnclosingClass;

Could not smali file: com/meizu/gamesdk/update/d$a.smali
```

**The content of the d$a.smali file  is :**

```
.class public final Lcom/meizu/gamesdk/update/d$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/meizu/gamesdk/update/d;
.end annotation

.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/meizu/gamesdk/update/c;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x609
    name = "a"
.end annotation


# instance fields
.field final synthetic a:Landroid/content/Context;

.field final synthetic b:Lcom/meizu/gamesdk/update/c$a;

.field final synthetic c:Lcom/meizu/gamesdk/update/d;


# direct methods
.method constructor <init>(Lcom/meizu/gamesdk/update/d;Landroid/content/Context;Lcom/meizu/gamesdk/update/c$a;)V
    .registers 4

    .line 51
    iput-object p1, p0, Lcom/meizu/gamesdk/update/d$a;->c:Lcom/meizu/gamesdk/update/d;

    iput-object p2, p0, Lcom/meizu/gamesdk/update/d$a;->a:Landroid/content/Context;

    iput-object p3, p0, Lcom/meizu/gamesdk/update/d$a;->b:Lcom/meizu/gamesdk/update/c$a;

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

```

There are two 

> .annotation system Ldalvik/annotation/EnclosingClass;

of the class ?   

Thanks!!!

**Comment by u8-xiaohei** [comment]
> Information
> Apktool Version (apktool -version) - 2.4.0
> Operating System (Mac, Linux, Windows) -Windows 7
> APK From? (Playstore, ROM, Other) - exported from AndroidStudio 3.4
> 
> 1、I used [apktool d] to decompile the apk with the latest version(2.4.0)
> 2、then use baksmali-2.2.6.jar to convert a dex file to smali format. and merged into the smali folder.
> 3、then use [apktool b] to rebuild the apk, but had the following error:
> 
> ```
> ERROR::Au 16, 2019 1:12:40  brut.androlib.Androlib build
> 
> INFO: Using Apktool 2.4.0
> 
> Au 16, 2019 1:12:40  brut.androlib.Androlib buildSourcesSmali
> 
> INFO: Smaling smali folder into classes.dex...
> 
> 
> ERROR::..\..\temp\workspace\game1\meizusingle48\decompile\smali\com\meizu\gamesdk\update\d$a.smali[15,0] Multiple annotations of type Ldalvik/annotation/EnclosingClass;
> 
> Could not smali file: com/meizu/gamesdk/update/d$a.smali
> ```
> 
> **The content of the d$a.smali file is :**
> 
> ```
> .class public final Lcom/meizu/gamesdk/update/d$a;
> .super Ljava/lang/Object;
> .source "SourceFile"
> 
> 
> # annotations
> .annotation system Ldalvik/annotation/EnclosingClass;
>     value = Lcom/meizu/gamesdk/update/d;
> .end annotation
> 
> .annotation system Ldalvik/annotation/EnclosingClass;
>     value = Lcom/meizu/gamesdk/update/c;
> .end annotation
> 
> .annotation system Ldalvik/annotation/InnerClass;
>     accessFlags = 0x609
>     name = "a"
> .end annotation
> 
> 
> # instance fields
> .field final synthetic a:Landroid/content/Context;
> 
> .field final synthetic b:Lcom/meizu/gamesdk/update/c$a;
> 
> .field final synthetic c:Lcom/meizu/gamesdk/update/d;
> 
> 
> # direct methods
> .method constructor <init>(Lcom/meizu/gamesdk/update/d;Landroid/content/Context;Lcom/meizu/gamesdk/update/c$a;)V
>     .registers 4
> 
>     .line 51
>     iput-object p1, p0, Lcom/meizu/gamesdk/update/d$a;->c:Lcom/meizu/gamesdk/update/d;
> 
>     iput-object p2, p0, Lcom/meizu/gamesdk/update/d$a;->a:Landroid/content/Context;
> 
>     iput-object p3, p0, Lcom/meizu/gamesdk/update/d$a;->b:Lcom/meizu/gamesdk/update/c$a;
> 
>     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
> 
>     return-void
> .end method
> ```
> 
> There are two
> 
> > .annotation system Ldalvik/annotation/EnclosingClass;
> 
> of the class ?
> 
> Thanks!!!

Just test it， and  I found if I build jar with dx.jar all work fine. 
but if I build jar with d8.jar, and then convert the dex to smali with baksmali， the smali file will has duplicated annotations.

The correct smali file with the dex file generated by dx.jar is :

```
.class public final Lcom/meizu/gamesdk/update/d$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/meizu/gamesdk/update/d;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x609
    name = "a"
.end annotation


# instance fields
.field final synthetic a:Landroid/content/Context;

.field final synthetic b:Lcom/meizu/gamesdk/update/c$a;

.field final synthetic c:Lcom/meizu/gamesdk/update/d;


# direct methods
.method constructor <init>(Lcom/meizu/gamesdk/update/d;Landroid/content/Context;Lcom/meizu/gamesdk/update/c$a;)V
    .registers 4

    .prologue
    .line 51
    iput-object p1, p0, Lcom/meizu/gamesdk/update/d$a;->c:Lcom/meizu/gamesdk/update/d;

    iput-object p2, p0, Lcom/meizu/gamesdk/update/d$a;->a:Landroid/content/Context;

    iput-object p3, p0, Lcom/meizu/gamesdk/update/d$a;->b:Lcom/meizu/gamesdk/update/c$a;

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
```

**Comment by iBotPeaches** [comment]
It looks like you have already spotted smali which handles this portion of the project. I will mark this as 3rd party and link to it - https://github.com/JesusFreke/smali/issues/707

I can't speak to this as outside my knowledge set.

**Comment by iBotPeaches** [comment]
JF closed the smali ticket with:

> This honestly sounds like a bug with d8. It's not valid for a java class to have multiple annotations of the same type.

So closing downstream here as well.
