### ISSUE TITLE
apktool is removing -v(number) from some folders in "res" folder

### ISSUE THREAD

**Issue by lyndmi** [iBotPeaches/Apktool#2154]
### Information
1. **Apktool Version (`apktool -version`)** 2.4.0
2. **Operating System (Mac, Linux, Windows)** Windows 10
3. **APK From? (Playstore, ROM, Other)** Playstore

### Stacktrace/Logcat

```
PS E:\Apktool> java -jar apktool_2.4.0.jar d  E:\Downloads\BlackVue_v2.94_apkpure.com.apk
I: Using Apktool 2.4.0 on BlackVue_v2.94_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\admin\AppData\Local\apktool\framework), using C:\Users\admin\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\admin\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
PS E:\Apktool>
```

### Steps to Reproduce
1. `apktool d `

### Frameworks
None

### APK
https://apkpure.com/blackvue/comb.blackvuec

### Description
Why apktool is removing -v(number) from some folders in "res" folder? what is the point?

APK file:
![image](https://user-images.githubusercontent.com/24647715/63227826-14166c80-c1eb-11e9-926c-fd117e679951.png)

Decompiled APK:
![image](https://user-images.githubusercontent.com/24647715/63227829-2395b580-c1eb-11e9-944b-7ac1f1cfcfef.png)

This make me lot difficult to work with unsigned APK since I only copy modified files to unsigned APK to use with VirtualXposed and disabled signature on firmware
Is there a way to prevent it and keep all original?

**Comment by iBotPeaches** [comment]
Unfortunately this is not possible to resolve at present time. See https://github.com/iBotPeaches/Apktool/issues/1761#issuecomment-379309998 for details.

**Comment by lyndmi** [comment]
Ok well I found other way to deal with this
