### ISSUE TITLE
Can i do login via facebook ?

### ISSUE THREAD

**Issue by nttps** [iBotPeaches/Apktool#2155]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
-
Include stacktrace here
-

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

It works for build new .apk but its cannot to login via facebook. what can i do something for this ?

ps. this app can login via google , facebook , phone number. but it works only phone number

**Comment by Surendrajat** [comment]
Do you mean you can't log into fb & google in newly build apk? If yes, then yeah it's the **signature verification problem** **not related to apktool**. I can confirm it about google as I modified apps and I couldn't sign into google account, ex: TrueCaller, DriveSync etc.

**Comment by iBotPeaches** [comment]
This is a combination of some form of anti-tamper code. Apktool has no way in present form to know about this and work around it. Closing.
