### ISSUE TITLE
Is there any plan to support Android App Bundle?

### ISSUE THREAD

**Issue by xiao-xing-yun** [iBotPeaches/Apktool#2156]
Though it is obviously not a bug report, but just a wonder. For my personal project, ApkTool barely works because it is not compatible with AAB(Android App Bundle). Do you have any upcoming plan to take a glance at this?

Rex

**Comment by Ibuprophen** [comment]
I had asked this not to long ago on https://github.com/iBotPeaches/Apktool/issues/2065 and @iBotPeaches had provided an answer there. 

Just an FYI... 


~Ibuprophen

**Comment by xiao-xing-yun** [comment]
@Ibuprophen Oh, thanks for your friendly reminder 👍

**Comment by Chandu1233** [comment]
Hi @Ibuprophen, @xiao-xing-yun hope you are doing good.

I am also looking for a tool to unpackage the app bundles, instrument and package back like how we do with APK using apktool. did you guys find any alternative solution for that.

I appreciate your help!

Thanks in Advance.

**Comment by jgmGit** [comment]
@Chandu1233  @Ibuprophen @xiao-xing-yun  did some one find a way to do this ? i am also looking for some tool to extract the aab file, change some contents and build it back.
