### ISSUE TITLE
Feature request - build app with -b omit debug info

### ISSUE THREAD

**Issue by makstrix** [iBotPeaches/Apktool#2160]
It would be great to have a possibility to decompile app normally and then build with -b, omit debug info while building.

**Comment by makstrix** [comment]
@Ibuprophen I mean --no-debug-info

**Comment by iBotPeaches** [comment]
I don't see this as a possibility. No debug information only happens at the time of disassemble. I'm not aware of any flag to control this during the smali (build) stage.

This sounds like a feature-request for smali itself. https://github.com/JesusFreke/smali
