### ISSUE TITLE
cant decompile app 

### ISSUE THREAD

**Issue by anonforjustice** [iBotPeaches/Apktool#2163]
### Information
1. latest
2. windows
3. playstore

### Stacktrace/Logcat

```
W: null
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:73)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:315)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)

```

### Steps to Reproduce
1. `apktool d aaaa.apk

### Questions to ask before submission
yes
cant decompile 
yes

**Comment by anonforjustice** [comment]
seen similiar issues but havent found solution anywhere please help.....

**Comment by iBotPeaches** [comment]
Probably will need an APK to investigate this further. The crash looks too low level to guess at this point.

Will re-open if APK provided.

**Comment by anonforjustice** [comment]
> Probably will need an APK to investigate this further. The crash looks too low level to guess at this point.
> 
> Will re-open if APK provided.

whatsapp

**Comment by Ibuprophen** [comment]
@anonforjustice, are you referring to the following app? 

https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/ 

There's a few Apps that the `WhatsApp Inc.` released. 

For example, if you go to the following link... 

https://www.apkmirror.com/apk/whatsapp-inc/

... and then scroll down to the `All WhatsApp Inc. apps` category, you'll notice 3 different apps there. 

@iBotPeaches really needs to know the specific App (& it's version) as well as an attached txt file containing the logs that has/includes the information regarding the errors and such. 

What you had reported is basically information that's `Generic` in nature without nothing to go with in figuring out what's going on. 

This is not a lecture at all My Friend... 

This is only informational to help you know the 'very basics` of reporting an issue. 

Good Luck! :-) 


~Ibuprophen

**Comment by anonforjustice** [comment]
> @anonforjustice, are you referring to the following app?
> 
> https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/
> 
> There's a few Apps that the `WhatsApp Inc.` released.
> 
> For example, if you go to the following link...
> 
> https://www.apkmirror.com/apk/whatsapp-inc/
> 
> ... and then scroll down to the `All WhatsApp Inc. apps` category, you'll notice 3 different apps there.
> 
> @iBotPeaches really needs to know the specific App (& it's version) as well as an attached txt file containing the logs that has/includes the information regarding the errors and such.
> 
> What you had reported is basically information that's `Generic` in nature without nothing to go with in figuring out what's going on.
> 
> This is not a lecture at all My Friend...
> 
> This is only informational to help you know the 'very basics` of reporting an issue.
> 
> In addition, if you perform a quick search for `WhatsApp` as reflected on the following link...
> 
> https://github.com/iBotPeaches/Apktool/issues?q=whatsapp
> 
> ... You'll be able to locate other issues that may/might reflect the same/similar issue(s) as what your experiencing (via topic, OP information as well as the directions too) .
> 
> The issue #2036 is just one example that was listed on the above search results.
> 
> Good Luck! :-)
> 
> ~Ibuprophen

sorry , i'm new here and thank you for response,  i'm referring "whatsapp messenger" latest version and any variant , as you said i tried seeing old reports/issues but haven't found solution... :(

**Comment by josue7754** [comment]
> > @anonforjustice , ¿te refieres a la siguiente aplicación?
> > https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/
> > Hay algunas aplicaciones que se `WhatsApp Inc.`lanzaron.
> > Por ejemplo, si vas al siguiente enlace ...
> > https://www.apkmirror.com/apk/whatsapp-inc/
> > ... y luego desplácese hacia abajo hasta la `All WhatsApp Inc. apps`categoría, verá 3 aplicaciones diferentes allí.
> > @iBotPeaches realmente necesita conocer la aplicación específica (y su versión), así como un archivo txt adjunto que contenga los registros que tengan / incluyan la información sobre los errores y demás.
> > Lo que ha informado es básicamente información que está `Generic`en la naturaleza, sin nada que ver con lo que está sucediendo.
> > Esto no es una conferencia en absoluto Mi amigo ...
> > Esto es solo informativo para ayudarlo a conocer los "aspectos básicos" de informar un problema.
> > Además, si realiza una búsqueda rápida `WhatsApp`como se refleja en el siguiente enlace ...
> > https://github.com/iBotPeaches/Apktool/issues?q=whatsapp
> > ... Podrá localizar otros problemas que pueden / podrían reflejar los mismos problemas similares a los que está experimentando (a través del tema, la información de OP y las instrucciones también).
> > El problema [# 2036](https://github.com/iBotPeaches/Apktool/issues/2036) es solo un ejemplo que se enumeró en los resultados de búsqueda anteriores.
> > ¡Buena suerte! :-)
> > ~ Ibuprophen
> 
> lo siento, soy nuevo aquí y gracias por la respuesta, logré descompilar la aplicación con éxito

Como hiciste para descompilar la apk?

**Comment by touficbatache** [comment]
@iBotPeaches Same thing happening on my end, here's [the apk](https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=1891643&forcebaseapk).
