### ISSUE TITLE
** declared here is not defined.

### ISSUE THREAD

**Issue by jayce211** [iBotPeaches/Apktool#2164]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore/Other
4. Java version - 10

### Steps to Reproduce
1. apktool  d xxx.apk
2. apktool b xxx.apk

### APK
It happens to multiple apk files from playstore and downloaded from websites.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

I have noticed that some apk files I get something similar to the following:

bgfinder\res\values\public.xml:1175: error: Public symbol ^attr-private/yearStyle declared here is not defined.

But then other apk files compile just fine. Is this an issue with certain apk files? Is there a way to fix this? It happens even if I don't change anything. But then if I go into that file I can clearly see it is declared there.

If I use apktool -r d xxx.apk and apktool b xxx.apk everything builds okay. But does me no good since then I can't edit the files.

**Comment by jayce211** [comment]
It appears that any apk I try this on that has the ^attr-private fails. So it must be something to do with that. I looked through here a lot but didn't find any fix, so maybe it will be fixed in a later version?

**Comment by iBotPeaches** [comment]
Sorry for the delay. This is indeed a known issue and tracked here: https://github.com/iBotPeaches/Apktool/issues/1668

Closing as duplicate.
