### ISSUE TITLE
What does dirty build mean?

### ISSUE THREAD

**Issue by thebunnyrules** [iBotPeaches/Apktool#2166]
Sorry, I feel bad wasting your time with a question like this but I tried to google it and didn't find anything. 

I built apktool from source and when I ran it says apktool dirty. What does that mean? Is it just because it's unofficial or is it because I did something wrong in the build, something is missing?

**Comment by Ibuprophen** [comment]
A dirty build... That's a good question! :-) 

Hopefully someone will correct me if I'm wrong and/or elaborate further. 

It's something I understand but, am challenged to define (personally). 

A dirty build is something that's unfinished in nature with commits that are not applied. 

As opposed to Snapshots... Snapshots are builds with the commits applied to it. Kinda like an incomplete build (aka... What's done so for). 

I try to avoid Dirty builds as their unfinished/unpolished. If I wanted to try what's done so far (before an official build was compiled), I'd compile a Snapshot. 

I apologize for the broken definition. Hopefully @iBotPeaches can elaborate much better than I can. :-P 


~Ibuprophen

**Comment by thebunnyrules** [comment]
Thanks! I will avoid it too. How do avoid it? You do git checkout of a complete version when building?
null

**Comment by thebunnyrules** [comment]
Got it:
```
git checkout tags/v2.4.0
```

**Comment by Ibuprophen** [comment]
Update: I did locate a Dirty Build answer from iBotPeaches on https://github.com/iBotPeaches/Apktool/issues/2114. 


~Ibuprophen
