### ISSUE TITLE
apktool can't change imageview

### ISSUE THREAD

**Issue by ajater** [iBotPeaches/Apktool#2170]
### Information
1. **Apktool Version (`apktool -version`)** -  2.4.0
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** - other

when I change an old image with new one after decombiling and then build the apk 
the image doesn't change after I run the app in my phone it only view the old image

any help will be appreciated

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
This doesn't look related to Apktool. Closing.
