### ISSUE TITLE
No resource identifier found for attribute 'windowLayoutInDisplayCutoutMode' in package 'android'

### ISSUE THREAD

**Issue by david8557** [iBotPeaches/Apktool#2171]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
### Steps to Reproduce
1. Decompile apk
2. Recompile APK

### APK
APK Link: https://www78.zippyshare.com/v/y11Q3m2c/file.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by Beery1** [comment]
升级你的android.jar包试试

**Comment by iBotPeaches** [comment]
> File has expired and does not exist anymore on this server

---

That attribute was added in API 27 - https://developer.android.com/reference/android/R.attr#windowLayoutInDisplayCutoutMode so you'll need to update framework files.
