### ISSUE TITLE
Rebuilt APK installs, but immediately crashes when launched

### ISSUE THREAD

**Issue by Nun-z** [iBotPeaches/Apktool#2178]
### Information
1. **Apktool Version (2.4.0)** -
2. **Operating System (Windows)** -
3. **APK From? (Daimengplay.com)** -

### Stacktrace/Logcat

```

```

### Steps to Reproduce
1. Download APK from website.
2. apktool.jar d damonps2.apk
3. apktool.jar b damonps2 -o newApk.apk
4. Sign newAPK with APK_Signer or another tool.
5. Install newAPK to Android device.
6. Attempt to launch the newly installed app named DamonPS2.
7.  Note that the app immediately crashes.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

Not applicable. 

### APK
If this APK can be freely shared, please upload/attach a link to it.

http://daimengplay.com/DamonPS2-cn-direct-release-v86-2.0-201903111021_20_jiagu_sign.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? I didn't make any changes, but I did resign it.
3. Are you using the latest apktool version? This is on the newest release (not built from code).

**Comment by posti85** [comment]
I'm facing the same issue with other apk. It does work when with Apktool 2.3.4 I decompile and then compile it. But it doesn't when I do it with Apktool 2.4.0: the apk crashes when I enter the home screen.

**Comment by Nun-z** [comment]
I can't even get it to compile with 2.3.4.  It crashes with an error.

**Comment by posti85** [comment]
I've to mention that I got the APK decompiled/compiled working with Apktool 2.3.4 because I didn't decompile the resources (`-r` option). Now I have tested with 2.4.0 without decompile the resources too and it worked. Something wrong is going on with the resources in my apk. But it didn't matter in my case because I only wanted to edit some smali files.

**Comment by Nun-z** [comment]
Still not working for me even with that option enabled.  I guess some APKs are not good candidates for apktool, or there's some other setting I need to enable.

**Comment by iBotPeaches** [comment]
Apologies for delay. I don't see the stacktrace any/or logcat. My gut is after a year+ either - you don't have it nor care anymore about this particular issue.

I'm closing since I don't have the time to install applications on my device and trigger crashes, etc.
