### ISSUE TITLE
W: invalid resource directory name: /home/app/res navigation

### ISSUE THREAD

**Issue by bphown** [iBotPeaches/Apktool#2179]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -APK4Fun.com

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /home/cn.xender-4.6.5.Prime@APK4Fun.com/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2579970741782324855.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 28, --version-code, 614, --version-name, 4.6.5.Prime, --no-version-vectors, -F, /tmp/APKTOOL6433846982661292999.tmp, -0, arsc, -0, log, -0, assets/web/css/all_2019_08_14_06_06_52.css.wl, -0, ogg, -0, mp3, -0, arsc, -I, framework/1.apk, -S, /home/cn.xender-4.6.5.Prime@APK4Fun.com/res, -M, /home//cn.xender-4.6.5.Prime@APK4Fun.com/AndroidManifest.xml]

```

### Steps to Reproduce
1. `apktool d cn.xender-4.6.5.Prime.apk`
2. `apktool b cn.xender-4.6.5.Prime`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment]
Looks like a space in there and that isn't valid.

**Comment by ahmadii** [comment]
I have the same problem.
what is the solution?

**Comment by tahsin1373** [comment]
> I have the same problem.
> what is the solution?

you can see #1811 and #2219 .
