### ISSUE TITLE
How do i build my app with 64-bit support

### ISSUE THREAD

**Issue by Meptinity** [iBotPeaches/Apktool#2183]
So i recently tried to upload an update of "my" game ([](https://play.google.com/store/apps/details?id=com.galaxy1036.glreborn))  to Google Play but i got an error that said that my game doesnt meet the 64-bit requirement. So i tried to find a solution on Google and i found out that i have to add something like this to my build.gradle:
`android {
   defaultConfig {
       ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
// ...`
But the only problem is that there obviously is no build.gradle file since i decompiled the original game using apktool. But how do i add 64-bit support then? Adding a "arm64-v8a" folder to my lib folder for example just makes the game crash immediately so there is no other way rather than defining ndk.abiFilters.

**Comment by Ibuprophen** [comment]
You cannot just add 64-bit compatibility to an app that doesn't have it already present within it. 

The 64-bit architecture is very different from the 32-bit. This would require the app to be developed (via its source code) with a whole new coding for the 64-bit architecture. 

This is something that requires the work of the original developer for the app to do. 

Sorry for the bad news... :-( 


~Ibuprophen

**Comment by Meptinity** [comment]
> You cannot just add 64-bit compatibility to an app that doesn't have it already present within it.
> 
> The 64-bit architecture is very different from the 32-bit. This would require the app to be developed (via its source code) with a whole new coding for the 64-bit architecture.
> 
> This is something that requires the work of the original developer for the app to do.
> 
> Sorry for the bad news... :-(
> 
> ~Ibuprophen

A man that sucks! Thank you for your help.
