### ISSUE TITLE
Apktool b changes big number into decimal value in the AndroidManifest

### ISSUE THREAD

**Issue by psandytang** [iBotPeaches/Apktool#2185]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Mac 10.14.6
3. **APK From? (Playstore, ROM, Other)** - Other

The Apktool could not properly translate big value back to its original value, but instead changes over to decimal number

Ex:
Here is my source entry in AndroidManifest.xml
`<meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value=" 327843153895302" />`

After I do Apktool d follow by ApkTool b, this meta-data field changes to
`<meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="1469388288.000000" />`

### Steps to Reproduce
Have an APK with some large value in the AndroidManifest.xml file
1. `apktool d --no-src --output ./tmp --frame-path ./frame -f universal.apk `
2. `apktool b --frame-path ./frame --output test.apk ./tmp`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? I am resigning it
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Android is getting strict. Large integer values in meta-data in the manifest are not allowed anymore. You can try some tricks like forcing it to a string with like "/ ", but Apktool won't do this automatically as it is hacky.

Closing as Android newer limitation in build tools.
