### ISSUE TITLE
Apk zip recompiling store vs deflate

### ISSUE THREAD

**Issue by jututt** [iBotPeaches/Apktool#2190]
how apk zip recompiling is handled?

I found .png and .jpg archived with deflate, which there's no need of (being those filetypes already de facto compressed), while resources.arsc as store, which on the other hand could deflate nicely.

Some deflated packed .pngs are even slighty bigger than original, due to compression overhead.

**Comment by iBotPeaches** [comment]
Looks like you are looking for this block of code - https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java#L164

Compression or not is the source of plenty of problems and a variety of pain points and discussions around the tracker.

**Comment by jututt** [comment]
just edited apktool.yml - do not compress section and added - png
