### ISSUE TITLE
brut.common.RootUnknownFileException: Absolute Unknown Files is not allowed

### ISSUE THREAD

**Issue by Ac3n34d-X** [iBotPeaches/Apktool#2201]
### Information
1. **Apktool Version (`apktool -version`)** - Latest 2.4
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

![image](https://user-images.githubusercontent.com/25218652/67433832-6e80de80-f61b-11e9-866b-2c33098422fc.png)
I get that error while trying to rebuild an apk that was disassembled with apktool

**Comment by iBotPeaches** [comment]
I would need the APK to investigate this further. This is a security protection to prevent extracting from overwriting files in crucial places, so files that are explicit with a root path like that are denied - and for good reason. You wouldn't want a file in root called "deviceinsight-collector". It may be intended for root of application, but need APK to investigate.

Marking as waiting on issuer.

**Comment by Ac3n34d-X** [comment]
https://www.apkmonk.com/download-app/com.schwab.mobile/4_com.schwab.mobile_2019-10-07.apk/
Here's a download link to the app

**Comment by Ac3n34d-X** [comment]
https://www.apkmonk.com/download-app/com.schwab.mobile/4_com.schwab.mobile_2019-10-07.apk/
Here's a download link to the app

**Comment by iBotPeaches** [comment]
I replicate. The root issue is useless. We normalize the path so anything in `/root` would just become `root` in the root of the application. Will fix that up.

**Comment by iBotPeaches** [comment]
Tempted to close as no-fix. I attempted a PR, but it won't work because windows.

```
➜  2201 unzip -l com.schwab.mobile_2019-10-07.apk 
Archive:  com.schwab.mobile_2019-10-07.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
      536  1969-12-31 19:00   /deviceinsight-collector-javascript-6.6.0-0.pom
    66648  1980-00-00 00:00   AndroidManifest.xml
     1456  1980-00-00 00:00   META-INF/CERT.RSA
   399994  1980-00-00 00:00   META-INF/CERT.SF
```

This is just a bad apk. It has a root reference.

**Comment by iBotPeaches** [comment]
```
➜  2201 apktool d com.schwab.mobile_2019-10-07.apk -f
I: Using Apktool 2.5.1-d1c006-SNAPSHOT on com.schwab.mobile_2019-10-07.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
W: Skipping file /deviceinsight-collector-javascript-6.6.0-0.pom (Absolute Unknown Files is not allowed)
I: Copying original files...
➜  2201 
```

PR up for above.
