### ISSUE TITLE
Impossible to Recompile apk - without any changes....

### ISSUE THREAD

**Issue by baptistapedro** [iBotPeaches/Apktool#2203]
https://dpaste.de/Ocof/raw

Why is that, any idea how to fix?

**Comment by iBotPeaches** [comment]
The first error is a resource used, but not defined. Apktool might be at fault here, but not enough detail to tell. The other issue is more than likely an outdated framework.

Either way, pasting a stacktrace here and destroying the issue template is not the proper way :(

Closing for not enough details.
