### ISSUE TITLE
Fatal Error when reCompiling

### ISSUE THREAD

**Issue by baptistapedro** [iBotPeaches/Apktool#2205]
I did `apktool -r d my.apk` to decompile my APK
and without changing anything I tried to compile it immediately with
`apktool b my/`

I get this error:
```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
[Fatal Error] :1:1: O conte·do nπo Θ permitido no pr≤logo.
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
```

What is this fatal error about, also there's any way to improve the errors with a more verbose mode?

**Comment by iBotPeaches** [comment]
You can use `-v` for verbose. Without the issue template and little details - not much I can do here.

**Comment by baptistapedro** [comment]
Even with -v I dont see anything relevant about the errors.
The apk im trying to recompile is Telegram - https://www.apkmirror.com/apk/telegram-fz-llc/telegram/telegram-5-10-0-release/      - open the link, fetch the first variant.

Just decompile it and try recompile again please.
