### ISSUE TITLE
Help me please i am facing issue during recompile via apktool

### ISSUE THREAD

**Issue by masoomdil** [iBotPeaches/Apktool#2207]
### Information
1. **Apktool Version (`apktool -version`)** - apktool 2.4
2. **Operating System (Mac, Linux, Windows)** - windows 10 64 bit
3. **APK From? (Playstore, ROM, Other)** - apkpure

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes without changing i did D is good but B through exception 
2. If you are trying to install a modified apk, did you resign it? i am unable o make new apk so resign is later work 
3. Are you using the latest apktool version?yes

Here is my error i am getting
"
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\masoom\AppData\Local\Temp\brut_util_Jar_4871362612027629458.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\masoom\AppData\Local\Temp\APKTOOL1430620329845602728.tmp, -0, arsc, -0, PNG, -0, res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, jpg, -0, gif, -0, arsc, -I, C:\Users\masoom\AppData\Local\apktool\framework\1.apk, -S, C:\Users\masoom\Desktop\again\masoom\res, -M, C:\Users\masoom\Desktop\again\masoom\AndroidManifest.xml]
"

**Comment by Ticklefish** [comment]
When you get an error message, it's worth looking at what it actually says. A lot of the time the error message tells you what's wrong.

In this case you're getting an exit code "**1073741515**". A little bit of Googling gives you the answer: you need to uninstall 32 bit Java from your PC. Apktool 2.4.0 needs 64 bit Java _only_.

**Comment by iBotPeaches** [comment]
This will be resolved in next release. The binaries for 32bit windows were bugged.
