### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by JimDunn1234** [iBotPeaches/Apktool#2208]
Seems only 2.3.4 can compile some apks.  I don't know if your dev build has fixed any of this but thought I would share the link where you can read yourself of numerous issues causing users to use 2.3.4 instead.
 https://forum.xda-developers.com/android/software-hacking/tool-apk-easy-tool-v1-02-windows-gui-t3333960/page59

**Comment by iBotPeaches** [comment]
I read it. Folks just tend to be running build vs build until it works. With how much time and changes are between releases that doesn't really help me. Detailed bug reports and triage does.

Closing.
