### ISSUE TITLE
decompile and recompile apk without any changes stopped working

### ISSUE THREAD

**Issue by jameshxxx** [iBotPeaches/Apktool#2209]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore-phone-arm64-v8a-android 6.0

### Stacktrace/Logcat
unfortunately stopped error
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
apktool d BHIM.apk
apktool b BHIM
java -jar signapk.jar certificate.pem key.pk8 BHIM.apk BHIM-signed.apk
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
![ds](https://user-images.githubusercontent.com/25865406/67673845-0a567580-f9a1-11e9-9ae6-996639db7020.png)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?yes
3. Are you using the latest apktool version?yes

------------
its very interesting without any changes. i am getting error.

i am try many apk file. i am getting this type.
the error comes in apk whos depend size on mobile in google play store.
![size](https://user-images.githubusercontent.com/25865406/67674296-1989f300-f9a2-11e9-8139-901c1c4f640a.png)

without any  changes apk running fine. but when i unpack and pack again.
and run it. then i getting error.
if apk have fixed size on google play store then working fine.
i think there are any  framework or other issue. please explain and help me
and test this apps on real mobile. because its need sim card.

**Comment by mikesew1320** [comment]
It also happened on my device with latest Apktool X 8.2.2

decompiler successfully but when I recompile it it says finished but I can't get the recompiled app of modded apk

**Comment by iBotPeaches** [comment]
> and run it. then i getting error.

It would help to know that error via `adb logcat` or something. Not enough information here to triage. Sorry for delay and closing.
