### ISSUE TITLE
Null Pointer exception in APKTool when decoding One Plus Zen Mode apk

### ISSUE THREAD

**Issue by TabLand** [iBotPeaches/Apktool#2213]
### Information
1. **Apktool Version (`apktool -version`)** -
>> Apktool 2.2.1
2. **Operating System (Mac, Linux, Windows)** -

```
ijtaba@ijtaba-SATELLITE-L50-B:~/Documents/zen_mode$ uname -ar
Linux ijtaba-SATELLITE-L50-B 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

3. **APK From? (Playstore, ROM, Other)** -
>> https://www.apkmirror.com/apk/oneplus-ltd/zen-mode/zen-mode-1-2-0-release/
>> The version I most likely need to edit is installed on my One Plus 5 device as part of the core Oxygen OS 9.0.9 build (Android version 9), Zen Mode v1.4.0. I will pull this apk via adb and update this ticket in the next few days. Not sure if I'm allowed to share the apk for now.

### Stacktrace/Logcat
```

ijtaba@ijtaba-SATELLITE-L50-B:~/Documents/zen_mode$ apktool d com.oneplus.brickmode.apk 
I: Using Apktool 2.2.1 on com.oneplus.brickmode.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ijtaba/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
>> "apktool d com.oneplus.brickmode.apk"

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
>> Will dive into this later. I plan on looking into this issue personally during November 2019, so happy for this issue ticket to be left unassigned or assigned to me. 
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
>>Yes
2. If you are trying to install a modified apk, did you resign it?
>> Didn't get this far
3. Are you using the latest apktool version?
>> Yes

**Comment by iBotPeaches** [comment]
I can't replicate this on the upcoming 2.5.0 release.
```
➜  2213 apktool d com.oneplus.brickmode_1.2.0-20_minAPI29\(nodpi\)_apkmirror.com.apk
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on com.oneplus.brickmode_1.2.0-20_minAPI29(nodpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2213
➜  2213 apktool b com.oneplus.brickmode_1.2.0-20_minAPI29\(nodpi\)_apkmirror.com
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2213 
```

Marking as resolved.
