### ISSUE TITLE
Facebook rebuild not working event when using --no-ress --no-src

### ISSUE THREAD

**Issue by bphown** [iBotPeaches/Apktool#2214]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - apkmirror.com

### Stacktrace/Logcat

Decode:
```
I: Using Apktool 2.4.0 on com.facebook.katana_242.0.0.36.119-176141837.apk
I: Copying raw resources...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

```
Rebuild:
```
I: Using Apktool 2.4.0
I: Copying com.facebook.katana_242.0.0.36.119-176141837 classes.dex file...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. `apktool d --no-res --no-src --frame-path framework com.facebook.katana_242.0.0.36.119-176141837.apk`
2. `apktool b --frame-path framework com.facebook.katana_242.0.0.36.119-176141837 -o facebook-unsigned.apk`
3. Try to install the app. I tried and it is not working.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No changes made, just decode and rebuild with --no-res and --no-src .
3. Are you using the latest apktool version? Yes

**Comment by bphown** [comment]
It seems it happens on applications that are using AndResGuard. The weird thing is that it happens even when using --no-res --no-src options.

**Comment by iBotPeaches** [comment]
Those stacktraces have no errors. If something is happening on the device, you'll need a logcat (`adb logcat`) of the crash to investigate further.

**Comment by bphown** [comment]
The problem is that it have not errors on stacktraces! Try to install the app. I tried and it is not working.

**Comment by mhashim6** [comment]
@iBotPeaches Same here, this is the error when launching the apk

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.home.splash.SplashActivity}: android.content.res.Resources$NotFoundException: Drawable com.gojek.app:drawable/2131231058 with resource ID #0x7f080152
```

I'm using `--no-res` but it still shows
```
I: Copying raw resources...
```
when I decode the apk.

**Comment by iBotPeaches** [comment]
@mhashim6 - This thread is 3 years old and is about Facebook. I don't see how your response is all related to this. I'm going to lock this to prevent further replies and notifications to others about an unrelated problem.
