### ISSUE TITLE
Encountered small uint that is out of range at offset 0x38 for apktool 2.3.4

### ISSUE THREAD

**Issue by conio001** [iBotPeaches/Apktool#2215]
### Information
1. **Apktool Version (`apktool -version`)** -
2.3.4

2. **Operating System (Mac, Linux, Windows)** -
mac

3. **APK From? (Playstore, ROM, Other)** -
Other, it's a normal app

### Stacktrace/Logcat
```
apktool decode /home/admin/data/channelftgame/10000054/202487_3.8.3.8_1572841782242/com.pkwan.op.opensdk_AND0117_HHW_13_1.7.0.202487_2019-11-03-00-04-42.apk -f --output /home/admin/data/channeltmp/5dbfa9366777ad9aa5f63886/apk
[decode, /home/admin/data/channelftgame/10000054/202487_3.8.3.8_1572841782242/com.pkwan.op.opensdk_AND0117_HHW_13_1.7.0.202487_2019-11-03-00-04-42.apk, -f, --output, /home/admin/data/channeltmp/5dbfa9366777ad9aa5f63886/apk, -a, /home/admin/app/conf/biz/packres/tools/aapt/28.0.0/linux/aapt, -p, /home/admin/data/]
CommandUtil:[java -jar, /home/admin/app/conf/biz/packres/tools/apktool_2.3.4.jar, decode, /home/admin/data/channelftgame/10000054/202487_3.8.3.8_1572841782242/com.pkwan.op.opensdk_AND0117_HHW_13_1.7.0.202487_2019-11-03-00-04-42.apk, -f, --output, /home/admin/data/channeltmp/5dbfa9366777ad9aa5f63886/apk, -a, /home/admin/app/conf/biz/packres/tools/aapt/28.0.0/linux/aapt, -p, /home/admin/data/]
CommandUtil[1]:java -jar /home/admin/app/conf/biz/packres/tools/apktool_2.3.4.jar decode /home/admin/data/channelftgame/10000054/202487_3.8.3.8_1572841782242/com.pkwan.op.opensdk_AND0117_HHW_13_1.7.0.202487_2019-11-03-00-04-42.apk -f --output /home/admin/data/channeltmp/5dbfa9366777ad9aa5f63886/apk -a /home/admin/app/conf/biz/packres/tools/aapt/28.0.0/linux/aapt -p /home/admin/data/ 
命令执行输出:I: Using Apktool 2.3.4 on com.pkwan.op.opensdk_AND0117_HHW_13_1.7.0.202487_2019-11-03-00-04-42.apk
命令执行输出:I: Loading resource table...
命令执行输出:I: Decoding AndroidManifest.xml with resources...
命令执行输出:I: Loading resource table from file: /home/admin/data/1.apk
命令执行输出:I: Regular manifest package...
命令执行输出:I: Decoding file-resources...
命令执行输出:I: Decoding values */* XMLs...
命令执行输出:I: Baksmaling classes.dex...
命令执行输出:I: Baksmaling classes2.dex...
命令执行输出:I: Baksmaling assets/A3AEECD8.dex...
【warn】命令执行失败:Exception in thread "main" org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x38
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:81)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:100)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.ZipDexContainer$ZipDexFile.<init>(ZipDexContainer.java:151)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.ZipDexContainer.loadEntry(ZipDexContainer.java:193)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.ZipDexContainer.getEntry(ZipDexContainer.java:120)
【warn】命令执行失败:	at org.jf.dexlib2.dexbacked.ZipDexContainer.getEntry(ZipDexContainer.java:58)
【warn】命令执行失败:	at org.jf.dexlib2.DexFileFactory$DexEntryFinder.findEntry(DexFileFactory.java:382)
【warn】命令执行失败:	at org.jf.dexlib2.DexFileFactory.loadDexEntry(DexFileFactory.java:186)
【warn】命令执行失败:	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:72)
【warn】命令执行失败:	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:38)
【warn】命令执行失败:	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
【warn】命令执行失败:	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:163)
【warn】命令执行失败:	at brut.apktool.Main.cmdDecode(Main.java:164)
【warn】命令执行失败:	at brut.apktool.Main.main(Main.java:73)
【warn】命令执行失败:
【warn】命令执行失败，result:1
【warn】命令执行失败，result:1
【warn】命令执行失败, code:1
     【Exception】java.lang.RuntimeException: apktool 解包执行失败: 1    
cn.flysdk.pack.task.DecompileTask.run(DecompileTask.java:69)    
cn.flysdk.pack.task.Task.exec(Task.java:94)    
cn.flysdk.pack.Packer.executeTasks(Packer.java:289)    
cn.flysdk.pack.Packer.doPack(Packer.java:104)    
cn.flysdk.pack.Packer.pack(Packer.java:83)    
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    
java.lang.reflect.Method.invoke(Method.java:498)    
cn.flysdk.pkg.module.game.helper.ChannelGamePackageInfoProcess.invokePackTool(ChannelGamePackageInfoProcess.java:370)    
cn.flysdk.pkg.module.game.helper.ChannelGamePackageInfoProcess.doExecute(ChannelGamePackageInfoProcess.java:101)    
cn.flysdk.pkg.module.game.task.ChannelGamePackageTask.run(ChannelGamePackageTask.java:45)    
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)    
java.util.concurrent.FutureTask.run(FutureTask.java:266)    
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)    
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)    
java.lang.Thread.run(Thread.java:882)
```
### Steps to Reproduce
1. the apk has a invalid dex file in assets folder. When I decode use apktool, it causes exception above.

I also found there maybe a mistake for modification in this commit, and add a comment for it, could you check if it's right?
https://github.com/iBotPeaches/Apktool/commit/76a940628f7a34aeed02ea228d42fc5a6d1d7356

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

no, it's not from OEM ROM

### APK
If this APK can be freely shared, please upload/attach a link to it.
It's very big, I can't share with it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes

2. If you are trying to install a modified apk, did you resign it?

3. Are you using the latest apktool version? 
no, we use 2.3.4

**Comment by iBotPeaches** [comment]
So its picking a dex outside of root, which is intentionally filled with bad opcodes, thus throwing warnings. Apktool shouldn't crash out on warnings, but this looks like some 3rd party tool using Apktool.

I can't find the report about the greedy dex finder, so I'll leave this one open for now.

**Comment by conio001** [comment]
> So its picking a dex outside of root, which is intentionally filled with bad opcodes, thus throwing warnings. Apktool shouldn't crash out on warnings, but this looks like some 3rd party tool using Apktool.
> 
> I can't find the report about the greedy dex finder, so I'll leave this one open for now.

Thanks for your reply, I update the comment for this commit(https://github.com/iBotPeaches/Apktool/commit/76a940628f7a34aeed02ea228d42fc5a6d1d7356), And described more clear now, you can check it, If have any question you could ask me here.

**Comment by realityJie** [comment]
如果你没有必要反编译assets/A3AEECD8.dex的话，你可以使用`apktool d --only-main-classes apkfile`进行反编译操作。但是添加这个`--only-main-classes `时会报错，可以看这里[#2225](https://github.com/iBotPeaches/Apktool/pull/2225)

**Comment by candyguy242** [comment]
楼主好~遇到了同样的问题，官方还没有更新，有没有已经更新后打好的jar可用呢？

**Comment by Ibuprophen** [comment]
> 如果你没有必要反编译assets/A3AEECD8.dex的话，你可以使用`apktool d --only-main-classes apkfile`进行反编译操作。但是添加这个`--only-main-classes `时会报错，可以看这里[#2225](https://github.com/iBotPeaches/Apktool/pull/2225)


{TRANSLATED FROM CHINESE BELOW}

If you don't need to decompile `assets/A3AEECD8.dex`, you can use `apktool d --only-main-classes apkfile` to decompile. 

But adding this `--only-main-classes ` will give an error, you can see here [#2225] (https://github.com/iBotPeaches/Apktool/pull/2225). 


> 楼主好~遇到了同样的问题，官方还没有更新，有没有已经更新后打好的jar可用呢？能否贴个网盘链接？谢谢~


{TRANSLATED FROM CHINESE BELOW}

The landlord is good~ I have encountered the same problem, the official has not been updated.

Is there a jar that has been updated and is available? Can you post a web link? Thank you~


~Ibuprophen

**Comment by conio001** [comment]
> 如果你没有必要反编译assets/A3AEECD8.dex的话，你可以使用`apktool d --only-main-classes apkfile`进行反编译操作。但是添加这个`--only-main-classes `时会报错，可以看这里[#2225](https://github.com/iBotPeaches/Apktool/pull/2225)

Thanks, this is helpful, I shall follow the latest release version of apktool

**Comment by xuboyu** [comment]
At present, apktool in version 2.4.0 still cannot use the command line "- only main classes". Do I have to wait until the new version to use the command line?

**Comment by iBotPeaches** [comment]
v2.4.1 has `--only-main-classes` which should resolve this. Marking as closed.
