### ISSUE TITLE
FEATURE REQUEST : Can you add support for splited apks (.apks) please? 

### ISSUE THREAD

**Issue by Mikesew1320** [iBotPeaches/Apktool#2218]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Android
3. **APK From? (Playstore, ROM, Other)** - xda

Can you add support for splited apks (.apks), I can't decomple, sign or zipalign them using your tool.

And also a way to convert those splited apks into standalone android package (.apk).

Kirlifs tool is out but it's not available for public. 

Is it possible to add support for them?

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by Ibuprophen** [comment]
I had previously asked about this within https://github.com/iBotPeaches/Apktool/issues/2065 and @iBotPeaches had provided an answer there. 

Just an FYI... 


~Ibuprophen

**Comment by mikesew1320** [comment]
Nothing helpful is written there

**Comment by mikesew1320** [comment]
Nothing helpful is written there

**Comment by Ibuprophen** [comment]
@iBotPeaches had stated "Not currently on my focus. It seems pretty specialized and Apktool doesn't need any of those features. By the time apktool has an application, it already has done those steps.". 

The ".apks" is called an App Bundle (aka Split Apps) and is created by the Google Bundletool. 

The repository that's specific to this is located at https://github.com/google/bundletool and is a type of compressed apk files that's unique upon themselves. 

Good Luck! :-) 

~Ibuprophen

**Comment by mikesew1320** [comment]
@Ibuprophen Can i contact u in pm using social media u are active on it please?

**Comment by AndnixSH** [comment]
I think I had meet the issue with decompiling/compiling split apk
Only a method that you baksmali/smali .dex and put it in apk file using Winrar/7zip worked perfectly

Currently you can merge split apk into single apk manually https://platinmods.com/threads/how-to-turn-a-split-apk-into-a-normal-non-split-apk.76683/

**Comment by MrIkso** [comment]
@AndnixSH  or, using special plugin 
http://4pda.ru/forum/index.php?showtopic=557858&view=findpost&p=79891516

**Comment by iBotPeaches** [comment]
I still don't see what Apktool can do with splits. Apktool would have to evolve into some "upload the splits here and we will combine them". That does not seem like Apktool's responsibility.

We have enough bugs that building in features to re-merge splits doesn't make much sense in my opinion. Am I misunderstanding?

**Comment by Ibuprophen** [comment]
@iBotPeaches, I'm not sure what's going on with this specific issue being reported, but I don't personally feel that this is an "Apktool" issue in on itself. 

The apks bundle is basically one or more apk files compressed using the ".apks" file extension. 

The apk files within it has a base/primary apk with one or more additional apk files that only has specific items applicable to the device that (so far from what I've found) primarily consists of what would be located within the "res" directory (ie... Language(s), DPI(s), etc...). 

As briefly as possible... What needs to happen is to extract/decompress the Apk files from the apks and use Apktool to decompile the base apk and the remaining one (or more) to implement them into one apk file. Then use the Apktool to recompile the base apk back into one. 

It's a challenge for me as i've tried my best to explain the above okay via text... :-O 

I hope this was helpful for someone. :-) 


~Ibuprophen

**Comment by iBotPeaches** [comment]
I'm going to track a different ticket for split apks. This one didn't really have anything concrete in it, but the feature request. We now have a crash/apk/concrete details.

Closing as duplicate for - https://github.com/iBotPeaches/Apktool/issues/2283

**Comment by muelli** [comment]
I think I would like to merge the split APKs into single monolithic universal APK that I can transport and install easily. Unfortunately, apktool doesn't seem to be capable of doing that :(

**Comment by iBotPeaches** [comment]
If only "merge the split APKs into a single monolithic universal APK" was so easy :)
