### ISSUE TITLE
Android Auto fail to run after recompiling

### ISSUE THREAD

**Issue by tomasz-grobelny** [iBotPeaches/Apktool#2221]
Decompiling+compiling succeeds, but later application cannot be run (closes right away).

### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1-6d2878-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - apkmirror.com

### Steps to Reproduce
```

E:\tmp>java -Xmx1024m -jar "C:\Program Files\APK Easy Tool\Apktool\apktool-cli-all.jar" d -f -k -m -o "E:\tmp\1-Decompiled APKs\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com" "E:\tmp\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk"
I: Using Apktool 2.4.1-6d2878-SNAPSHOT on com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Tomasz\AppData\Local\apktool\framework\1.apk
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

E:\tmp>java -Xmx1024m -jar "C:\Program Files\APK Easy Tool\Apktool\apktool-cli-all.jar" b -o "E:\tmp\2-Recompiled APKs\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk" "E:\tmp\1-Decompiled APKs\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com"
I: Using Apktool 2.4.1-6d2878-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...

E:\tmp>java -Xmx1024m -jar "C:\Program Files\APK Easy Tool\Resources\ApkSigner.jar" sign  --key "C:\Program Files\APK Easy Tool\Resources\apkeasytool.pk8" --cert "C:\Program Files\APK Easy Tool\Resources\apkeasytool.pem" --out "E:\tmp\2-Recompiled APKs\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk" "E:\tmp\2-Recompiled APKs\com.google.android.projection.gearhead_4.7.593823-release-47593823_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk"

E:\tmp>java -Xmx1024m -jar "C:\Program Files\APK Easy Tool\Apktool\apktool-cli-all.jar" -version
2.4.1-6d2878-SNAPSHOT
```
### Frameworks
Nothing specific.

### APK
Need to get manually from apkmirror.com by searching android auto, version 4.7.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Do you have a logcat of the crash on the device? It may be anti-tamper or something bugged with resources. `adb logcat` will show you this during crash.

**Comment by JimDunn1234** [comment]
I successfully compiled the above apk if I do not decode resources.arsc.  Seems to be something in the resource folder that is breaking the compile.

**Comment by Ibuprophen** [comment]
@JimDunn1234, I've seen that one before (though not very often) and it's something to do with the Apk checking the Play Store for its authenticity upon launching. 

I'm not sure how to bypass this myself since I've rarely ever seen this message and, when I looked into it, I ended up scrapping it as that Apk (personally) wasn't worth the time and effort. 


~Ibuprophen

**Comment by tomasz-grobelny** [comment]
After some investigation I found that apktool has nothing to do with the failure here - the application fails just after re-signing (no decompilation phase). I found one place where the app checks for signatures and tried to modify it, but then it still does request to some content provider (content://com.google.android.gms.phenotype/...) which fails if the app signature is different. Seems I need to follow a different path with my reverse engineering task :-)
