### ISSUE TITLE
Checking whether sources has changed...BUG

### ISSUE THREAD

**Issue by xmhwws** [iBotPeaches/Apktool#2222]
Apktool 2.4.1-dirty
windows10 professional x64
apk has 3 dex

In a directory, compile smali into apk with Apktool.
Then, move all the files in the smali_classes3 folder to the smali_classes2 folder, without making any changes to smali, delete the smali_classes3 folder. The purpose of this approach is to change the 3 dex of apk to 2 dex.
Call the same command line (because the folder has not changed), compile smali into apk with Apktool. Will output 3 "Checking whether sources have changed...", and the generated apk is still 3 dex files.
Change the folder to a directory and compile smali into apk with Apktool. The generated apk is the 2 dex files I want.

I think this should be a bug in the inspection mechanism.

**Comment by iBotPeaches** [comment]
Apktool isn't' very smart, it just uses regex to locate folders with `"smali_#". You might have an old binary which would not be cleared.

I would try with `-f` and ensure you only have two smali folders.
