### ISSUE TITLE
Auto purge public.xml from not defined references

### ISSUE THREAD

**Issue by jututt** [iBotPeaches/Apktool#2228]
Can you add the option as per title?
Many times I want to strip apk from foreign languages, some may contain specific .xml resources that are not present in main layout, but are referenced in public.xml. App will work fine without them, but will not recompile unless manually removing broken references from public.xml first.

**Comment by iBotPeaches** [comment]
I'm not sure the feasibility of this - Apktool doesn't have a system in place to iterate resources in that manner. It would require loading all files into memory, then re-iterating and doing logic to strip what is unwanted. I think the large backlog of bugs have priority over this feature request - sorry!

**Comment by iBotPeaches** [comment]
Apktool has no method to do this, I don't see this happening. Closing. Even a roadmap item is a stretch as we don't have the memory/code-structure to remember what would be needed to do this.
