### ISSUE TITLE
0_APKTOOL_DUPLICATENAME_0x7f120006 - aapt2 not supported.

### ISSUE THREAD

**Issue by JimDunn1234** [iBotPeaches/Apktool#2229]
### Information
1. **Apktool Version (`apktool -version`)** - apktool-2.4.1-17ad91
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Pro
3. **APK From? (Playstore, ROM, Other)** - https://www.livenettv.sc

Here is one of many examples within the decompiled apk file:
**All xml files are affected...**
0_APKTOOL_DUPLICATENAME_0x7f0d0003.xml:2: error: No resource identifier found for attribute 'divider' in package 'com.lnt.androidnettv'

### Steps to Reproduce
Normal decompile settings
No modification done.
Normal compiling settings.
Compiling fails.

### APK
https://www.livenettv.sc

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Cannot get that far.  Compiling fails.
3. Are you using the latest apktool version? Yes

**Comment by budifiveplus** [comment]
Yes

**Comment by iBotPeaches** [comment]
This is an unfortunate side affect to increasing obfuscation to the resource level. If you wipe the human readable aspect of a key/value pair, Apktool has nothing to reverse until human readable.

This makes building quite complicated and it won't "just work". I do see an issue that the aapt2 version of this auto-generated resource names were invalid.

```
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/values-bg/strings.xml:37: error: resource 'string/0_APKTOOL_DUPLICATENAME_0x7f110037' has invalid entry name '0_APKTOOL_DUPLICATENAME_0x7f110037'. Invalid character '0_APKTOOL_DUPLICATENAME_0x7f110037'.
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/values-bg/strings.xml: error: file failed to compile.
```

So I'll use this ticket for that bug.

**Comment by iBotPeaches** [comment]
I replicate. Adding bug.

**Comment by MrIkso** [comment]
Use [this](https://github.com/MrIkso/sdk-tools/commit/9b30dd6889edacaca1d31608ad8e6117d1888d74) fix to sloved this bug on aapt2
it is correct to disable the validation of resource names, attributes and others. And don't do [it](https://github.com/iBotPeaches/platform_frameworks_base/commit/4b2e8f9c6898f0169ed8435261c9929165b6d23f)

**Comment by iBotPeaches** [comment]
> Use [this](https://github.com/MrIkso/sdk-tools/commit/9b30dd6889edacaca1d31608ad8e6117d1888d74) fix to sloved this bug on aapt2
> it is correct to disable the validation of resource names, attributes and others. And don't do [it](https://github.com/iBotPeaches/platform_frameworks_base/commit/4b2e8f9c6898f0169ed8435261c9929165b6d23f)

Would it be safer to rename our temporary names to match the criteria? Patches to aapt2 scare me since we have to make them all the time it changes.

**Comment by MrIkso** [comment]
> Would it be safer to rename our temporary names to match the criteria? Patches to aapt2 scare me since we have to make them all the time it changes.

maybe so, I thought about the fact that apktool decompiled resources to closer to the original, without $, 0 and other, which should not be in the original resources. Then no patches are needed.

**Comment by iBotPeaches** [comment]
> > Would it be safer to rename our temporary names to match the criteria? Patches to aapt2 scare me since we have to make them all the time it changes.
> 
> maybe so, I thought about the fact that apktool decompiled resources to closer to the original, without $, 0 and other, which should not be in the original resources. Then no patches are needed.

Reading the code it looks like it has to start with an alphabet character instead of numeric. I'll investigate why these IDs are starting with 0.

**Comment by MrIkso** [comment]
All resources names starting with q. Resources encrypted. 
Yes,  aapt2 don't like name start with number.

**Comment by iBotPeaches** [comment]
Hmm rebuilt with a new pattern and still no go. I'll investigate later. Hectic Monday.

```
I: Building resources...
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/animator-v21/0.xml:4: error: attribute state_collapsed (aka com.lnt.androidnettv:state_collapsed) not found.
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/animator-v21/0.xml:4: error: attribute state_collapsible (aka com.lnt.androidnettv:state_collapsible) not found.
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/color/APKTOOL_DUPLICATE_color_0x7f060002.xml:4: error: attribute alpha (aka com.lnt.androidnettv:alpha) not found.
W: /home/ibotpeaches/Downloads/Apktool/2229/LiveNetTV_4.7_Release/res/color/APKTOOL_DUPLICATE_color_0x7f060003.xml:4: error: attribute alpha (aka com.lnt.androidnettv:alpha) not found.
```

**Comment by iBotPeaches** [comment]
draft PR attached. Still doesn't rebuild, but I believe the name of the attribute is now valid.
