### ISSUE TITLE
apktool failed to decode and pack the weixin.apk without changing anything

### ISSUE THREAD

**Issue by liucongvg** [iBotPeaches/Apktool#2235]
### Information
1. **latest release version 2.4.0** -
2. **Linux** -
3. **APK From? Other** -

### Stacktrace/Logcat
java -jar apktool_2.4.0.jar d weixin.apk -o weixin -f
......
I: Using Apktool 2.4.0 on weixin.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/liucong/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable/talk_ui_default_background.xml
S: Could not decode file, replacing by FALSE value: layout/app_brand_add_shortcut_permission_dialog_content_layout.xml
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/newyearhongbao_number9.png
S: Could not decode file, replacing by FALSE value: drawable/lucky_money_emoji_add_btn.xml
S: Could not decode file, replacing by FALSE value: layout/fts_game_item.xml
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/pay_edu_illustration2.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/game_center_home_gift.png
......
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mall_order_money_payu_icon.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/sns_lucky_money_money_icon_in_feeds.png
S: Could not decode file, replacing by FALSE value: layout/notification_template_part_chronometer.xml
S: Could not decode file, replacing by FALSE value: drawable/my_trackpoint_bg.xml
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

java -jar apktool_2.4.0.jar b weixin -o weixin_packed.apk
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'ghm' has no default translation.
W: warning: string 'ghn' has no default translation.
W: warning: string 'gho' has no default translation.
W: warning: string 'ghp' has no default translation.
W: warning: string 'ghq' has no default translation.
W: warning: string 'ghr' has no default translation.
......
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:3: error: No resource identifier found for attribute 'title' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:4: error: No resource identifier found for attribute 'title' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:4: error: No resource identifier found for attribute 'key' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:4: error: No resource identifier found for attribute 'layout' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:5: error: No resource identifier found for attribute 'title' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:5: error: No resource identifier found for attribute 'key' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:5: error: No resource identifier found for attribute 'layout' in package 'com.tencent.mm'
W: 
W: /home/liucong/temp/weixin/res/xml/ct.xml:6: error: No resource identifier found for attribute 'title' in package 'com.tencent.mm'

the full output of apktool is attached with following two files:
[decode.log](https://github.com/iBotPeaches/Apktool/files/3873315/decode.log)
[pack.log](https://github.com/iBotPeaches/Apktool/files/3873319/pack.log)

```
Include stacktrace here
```

### Steps to Reproduce
java -jar apktool_2.4.0.jar d weixin.apk -o weixin -f
java -jar apktool_2.4.0.jar b weixin -o weixin_packed.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
Because the apk file is too large, I have to split it up.
[weixin.004.zip](https://github.com/iBotPeaches/Apktool/files/3873354/weixin.004.zip)
[weixin.005.zip](https://github.com/iBotPeaches/Apktool/files/3873355/weixin.005.zip)
[weixin.006.zip](https://github.com/iBotPeaches/Apktool/files/3873356/weixin.006.zip)
[weixin.007.zip](https://github.com/iBotPeaches/Apktool/files/3873357/weixin.007.zip)
[weixin.008.zip](https://github.com/iBotPeaches/Apktool/files/3873358/weixin.008.zip)
[weixin.009.zip](https://github.com/iBotPeaches/Apktool/files/3873359/weixin.009.zip)
[weixin.010.zip](https://github.com/iBotPeaches/Apktool/files/3873360/weixin.010.zip)
[weixin.011.zip](https://github.com/iBotPeaches/Apktool/files/3873361/weixin.011.zip)
[weixin.001.zip](https://github.com/iBotPeaches/Apktool/files/3873362/weixin.001.zip)
[weixin.002.zip](https://github.com/iBotPeaches/Apktool/files/3873363/weixin.002.zip)
[weixin.003.zip](https://github.com/iBotPeaches/Apktool/files/3873364/weixin.003.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Another tencent app - sorry.

Long running bug. Always seems to affect tencent/qq apps.

See #1427, #1423, #1499, #2235, #2422

Closing as duplicate.
