### ISSUE TITLE
Automatic adding .local and .param?

### ISSUE THREAD

**Issue by phuongnd08** [iBotPeaches/Apktool#2238]
### Information
1. **Apktool Version (`apktool -version`)** - Not important
2. **Operating System (Mac, Linux, Windows)** - Not important
3. **APK From? (Playstore, ROM, Other)** - Not important

### This is a feature request
When compile using smali source code without .param and .local, it's impossible to use the IDE Variables window to inspect method parameters and locals variable.

Apktool can includes the capability to auto inject .param and .local to bytecode - given they are missing. This way local variables and parameters are exposed to debugger via names similar to smali internal reference:  v1, v2, p1, p2...

**Comment by iBotPeaches** [comment]
I thought this was enabled by default (with debug flags) and disabled optionally via

```
 -b,--no-debug-info       don't write out debug info (.local, .param, .line, etc.)
```

**Comment by phuongnd08** [comment]
I guess the default is to not strip out debug info. Here what I ask is automatically inject of debug info. By default IDE (like IntelliJ) won't allow use to inspect variable / params unless .param and .local present.

**Comment by phuongnd08** [comment]
The process happened in real life:
java => compiled byte code => debugging information (.param, .line, .local) stripped => release to app store => download => apktool decompile => apktool build.

As you can see, by the time apktool build, all debugging information is gone. Automatic injection of basic debug info make it possible to examine the method registers while it's running.

**Comment by iBotPeaches** [comment]
Sorry for delay.

I am not understanding. I decode an application. 

```
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/aweme/sticker/data/NormalTrackTimeStamp.smali:    .locals 1
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/aweme/sticker/data/NormalTrackTimeStamp.smali:    .locals 1
```

I see locals.

```
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/trill/language/api/LanguageApi.smali:    .param p2    # Ljava/lang/String;
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/trill/language/api/LanguageApi.smali:    .end param
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/trill/language/api/LanguageApi.smali:    .param p3    # I
com.zhiliaoapp.musically_apps.evozi.com/smali_classes6/com/ss/android/ugc/trill/language/api/LanguageApi.smali:    .end param
```

I see params.

If I decode with `-b` it goes away. So I'm going to close this as not reproducible.

**Comment by phuongnd08** [comment]
@iBotPeaches You are decode an app that come with debug information. Not all app comes with debug information. This is why I was asking to automatically re-generate debugging information for them, just so we can inspect variable in jdb
