### ISSUE TITLE
declare-styleable：Does not exist after Decompilation

### ISSUE THREAD

**Issue by XUEFENGZ** [iBotPeaches/Apktool#2241]
### Information
1. **Apktool Version -2.4.0
2. **Operating System- Windows
3. **APK From? - Other 
Does not exist after Decompilation declare-styleable。Apktool  After Decompilation Use Gradle or Ant Build Unable to generate R.styleable...
Can support attrs.xml existence declare-styleable?

**Comment by Ticklefish** [comment]
You need to provide a lot more information than this for people to be able to help you.

**Comment by iBotPeaches** [comment]
Not sure what is being reported here.

**Comment by iBotPeaches** [comment]
Though after more backlog work. It looks related to this: https://github.com/iBotPeaches/Apktool/issues/1217
