### ISSUE TITLE
Easy APKTOOL Keep Orginal Signature Mean ?

### ISSUE THREAD

**Issue by iTMaster228** [iBotPeaches/Apktool#2242]
I want to know about Option " **Keep Orginal Signature**"

For example I have my own app when i decompile my app and compile it with that option 
that,
 mean my app will have same signature like my existing app even without keystore ?

**Comment by Ibuprophen** [comment]
Simply go to the following link... 

https://ibotpeaches.github.io/Apktool/documentation/

... And scroll down to the following 2 topics:

1) `There is no META-INF dir in resulting apk. Is this ok?`that provides a good explanation. 

2) `Parameter Changes` has a sub bullet that begins with `original =` which also provides an additional explanation as well. 

I hope this was helpful for you. :-) 


~Ibuprophen

**Comment by iTMaster228** [comment]
Thanks But i just want to know the compile apk have original  signature  or not?

**Comment by Ticklefish** [comment]
If you use the option "--copy-original" when compiling your APK, it will copy the original signature.

This is mentioned in the topics mentioned above in the apktool documentation..

> **There is no META-INF dir in resulting apk. Is this ok?**

> Yes. **META-INF** contains apk signatures. After modifying the apk it is no longer signed. You can use **-c / --copy-original** to retain these signatures. However, using **-c** uses the original **AndroidManifest.xml** file, so changes to it will be lost.

**Comment by iBotPeaches** [comment]
Yeah, TLDR - We copy the `META-INF` and the correlated `AndroidManifest.xml` which in the older days would allow the application to verify (in strange circumstances). 

As Android evolved and package signature types evolved, this no longer worked. Its set for deprecation.
