### ISSUE TITLE
Recompile Settings.apk MIUI 11

### ISSUE THREAD

**Issue by nurfaizfy19** [iBotPeaches/Apktool#2243]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Linux Ubuntu 18
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: W/ResourceType( 4963): DynamicRefTable(0x10): No mapping for build-time package ID 0x10.
W: W/ResourceType( 4963): e[0x01] -> 0x01
W: W/ResourceType( 4963): e[0x7f] -> 0x7f
W: E/ResourceType( 4963): Failed resolving ResTable_map name at 2300 with ident 0x100b0015
W: warning: Package not found for resource #1001001a
W: W/ResourceType( 4963): DynamicRefTable(0x10): No mapping for build-time package ID 0x10.
W: W/ResourceType( 4963): e[0x01] -> 0x01
W: W/ResourceType( 4963): e[0x7f] -> 0x7f
W: E/ResourceType( 4963): Failed resolving ResTable_map name at 3820 with ident 0x100b0010
W: warning: Package not found for resource #1001004f
W: W/ResourceType( 4963): Attempt to retrieve bag 0x1001004f which is invalid or in a cycle.
W: warning: Package not found for resource #1001004f
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy META-INF...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. `apktool if framework-res.apk`
2. `apktool if miui.apk`
3. `apktool if framework-ext-res.apk`
4. `apktool if miuisystem.apk`
5. `apktool d Settings.apk`
6. `apktool b Settings -c -o Settings-new.apk`

### Frameworks
1. `framework-res.apk` from /system/framework
2. `framework-ext-res.apk` from /system/framework/framework-ext-res
3. `miui.apk` from /system/app/miui
4. `miuisystem.apk` from /system/app/miuisystem
[All framework](https://www.dropbox.com/s/iy3drzyf78jc2ad/framework.zip?dl=0)

### APK
`Settings.apk` from /system/priv-app/Settings
[Settings.apk](https://www.dropbox.com/s/f0id6ooeo68nh9q/Settings.zip?dl=0)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes, with -c option
3. Are you using the latest apktool version? Yes, for now the latest version is 2.4.1

Maybe this issue has been asked many times, but I still have not found a solution, I have tried various ways of reporting related issues but there were no results. I didn't change AndroidManifest.xml, I used the original file using -c option. When reproducing another APK there is no error and works normally when pushed to the system.

**Comment by Ticklefish** [comment]
I had a go at this and this was the result:

> Installed Framework File(s)
> 
> framework-res.apk [1.apk]
> Settings.apk [127.apk]
> miui.apk [16.apk]
> framework-ext-res.apk [17.apk]
> miuisystem.apk [18.apk]
> 
> (java -Xmx1024m -jar user_files\APKTOOL\apktool_2.4.1.jar d --force-manifest     --only-main-classes -f -p _WorkArea1\Frameworks _WorkArea1\_in\Settings.apk -o _WorkArea1\_working\Settings.apk) 
> 
> I: Using Apktool 2.4.1 on Settings.apk
> I: Loading resource table...
> I: Decoding Shared Library (miui), pkgId: 16
> I: Decoding Shared Library (android.miui), pkgId: 17
> I: Decoding Shared Library (miui.system), pkgId: 18
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: _WorkArea1\Frameworks\1.apk
> I: Loading resource table from file: _WorkArea1\Frameworks\16.apk
> I: Regular manifest package...
> I: Decoding file-resources...
> I: Loading resource table from file: _WorkArea1\Frameworks\17.apk
> I: Decoding Shared Library (miui), pkgId: 16
> I: Decoding values */* XMLs...
> I: Loading resource table from file: _WorkArea1\Frameworks\18.apk
> I: Decoding Shared Library (miui), pkgId: 16
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
>  

No problem recompiling.

> (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all --use-aapt2 -p _WorkArea1\Frameworks _WorkArea1\_working\Settings.apk -o _WorkArea1\_out\Settings.apk) 
> 
> -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> I: Using Apktool 2.4.1
> I: Smaling smali folder into classes.dex...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Building resources...
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\arrays.xml:1729: error: invalid value for type 'array'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\arrays.xml:1866: error: invalid value for type 'array'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\arrays.xml:1867: error: invalid value for type 'array'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\arrays.xml:2716: error: invalid value for type 'array'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\arrays.xml: error: file failed to compile.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\layouts.xml:26: error: invalid value for type 'layout'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\layouts.xml: error: file failed to compile.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2585: error: resource 'drawable/$ic_color_inversion__0' has invalid entry name '$ic_color_inversion__0'. Invalid character '$ic_color_inversion__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2586: error: resource 'drawable/$ic_color_inversion__1' has invalid entry name '$ic_color_inversion__1'. Invalid character '$ic_color_inversion__1'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2587: error: resource 'drawable/$ic_daltonizer__0' has invalid entry name '$ic_daltonizer__0'. Invalid character '$ic_daltonizer__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2588: error: resource 'drawable/$ic_daltonizer__1' has invalid entry name '$ic_daltonizer__1'. Invalid character '$ic_daltonizer__1'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2589: error: resource 'drawable/$ic_my_device__0' has invalid entry name '$ic_my_device__0'. Invalid character '$ic_my_device__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2590: error: resource 'drawable/$scan_output_01__0' has invalid entry name '$scan_output_01__0'. Invalid character '$scan_output_01__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2591: error: resource 'drawable/$scan_output_01__1' has invalid entry name '$scan_output_01__1'. Invalid character '$scan_output_01__1'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2592: error: resource 'drawable/$scan_output_02__0' has invalid entry name '$scan_output_02__0'. Invalid character '$scan_output_02__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2593: error: resource 'drawable/$scan_output_02__1' has invalid entry name '$scan_output_02__1'. Invalid character '$scan_output_02__1'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2594: error: resource 'drawable/$scan_output_03__0' has invalid entry name '$scan_output_03__0'. Invalid character '$scan_output_03__0'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2595: error: resource 'drawable/$scan_output_03__1' has invalid entry name '$scan_output_03__1'. Invalid character '$scan_output_03__1'.
> W: C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res\values\public.xml:2596: error: resource 'drawable/$scan_output_04__0' has invalid entry name '$scan_output_04__0'. Invalid character '$scan_output_04__0'.
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Me\AppData\Local\Temp\brut_util_Jar_4720482240407337991.tmp, compile, --dir, C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\res, --legacy, -o, C:\TickleMyAndroid\_WorkArea1\_working\Settings.apk\build\resources.zip]
> 

So this file can't recompile because of issues with two XML files, which is normally fairly easy to sort out. But also there's an issue with drawables having invalid characters in their names. '$' isn't a valid character in Android filenames. This is an issue with the way the rom has been constructed.
You could try renaming those files to something valid, which might get the APK to compile, but you could have problems actually running it.

**Comment by iBotPeaches** [comment]
Sorry for the delay, but MIUI has strived from the path of AOSP and has highly modified build tools. For this it is no longer supported.

A grandfathered ticket remains from 2016 here - https://github.com/iBotPeaches/Apktool/issues/1178
