### ISSUE TITLE
Could not smali file EventLogListFragment.smali

### ISSUE THREAD

**Issue by beshoo** [iBotPeaches/Apktool#2247]
### Information
1. **Apktool Version (`v2.4.0`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
I:\android-system>apktool b -o I:\android-system\instagram-patched62-adb-new.apk I:\android-system\instagram-patched62-adb
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
instagram-patched62-adb\smali_assets\devoptions\devoptions2\com\instagram\analytics\eventlog\EventLogListFragment.smali[18,16] Class Lcom/instagram/analytics/eventlog/EventLogListFragment; has already been interned
Could not smali file: devoptions/devoptions2/com/instagram/analytics/eventlog/EventLogListFragment.smali

```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
YES
2. If you are trying to install a modified apk, did you resign it?
I can not be build it 
3. Are you using the latest apktool version? YES

Dear support
I have a modified version of an old Instagram app to study how Instagram works.
I can extract the file , no problem
but when i want to build it i got the :
```

instagram-patched62-adb\smali_assets\devoptions\devoptions2\com\instagram\analytics\eventlog\EventLogListFragment.smali[18,16] Class Lcom/instagram/analytics/eventlog/EventLogListFragment; has already been interned
Could not smali file: devoptions/devoptions2/com/instagram/analytics/eventlog/EventLogListFragment.smali
```

I know that there is 2 classes in the same name but how can i solve this since i did not even change anything!

**Comment by Ticklefish** [comment]
This is just a guess but it's worth trying apktool 2.4.1 with the "--only-main-classes" decode option. That might help.

It's always a good idea to use the most current apktool anyway.

**Comment by iBotPeaches** [comment]
Normally this is an indicator that you have duplicated classes as you saw. I thought Android verifier would reject a dex with duplicate classes, so this may be a secondary dex.

I would start with an official Instagram APK, because something called "instagram-patched62-adb-new.apk" does not seem official.

I don't think Apktool is at fault here and the crash is smali, which you can find a related issue here: https://github.com/JesusFreke/smali/issues/529

**Comment by beshoo** [comment]
--only-main-classes Solve the problem

**Comment by AndnixSH** [comment]
Been looking for this solution for long time
--only-main-classes prevented it from creating smali_assets/assets.dex
