### ISSUE TITLE
AndResGuard

### ISSUE THREAD

**Issue by JimDunn1234** [iBotPeaches/Apktool#2248]
Any plans for apktool to decompile and compile AndResGuard open source protection correctly?  I have noticed it is focused on making apktool useless.  More apks are using it and apktool is not useful on these apks.  I understand this is a tit for tat game but apktool is losing the game or not playing it.  Thought I would ask if support for AndResGuard removal has been dropped.

**Comment by iBotPeaches** [comment]
Hi,

AndResGuard is built by the WeChat team, which is a smart group of individuals. I am but one person. They can leverage Apktool open source nature to determine the best way to neutralize it, in addition (unless changed). They use Apktool to apply AndResGuard changes on a binary APK.

This does not work in the reverse as the targets are different. For example, AndResGuard target is to make the application as obfuscated as possible while still allowing it to work on the host device.

This means you can make some shortcuts, things that are simply required when doing what Apktool needs to do, which is disassemble the application into human readable sources so we can pipe it through build tools against to get a binary. 

If AndResGuard removes the resource name, we have no choice but to give the asset that renamed name during disassembly, no issue there.

However, what if you set the key to the same thing? Does Android care? No. Does Apktool care when decoding? Yes. These are the cat and mouse game that goes on.

Support hasn't been dropped, but only focus at this time is ensuring disassembly works. Allowing rebuild is not something I have time allocated for.
