### ISSUE TITLE
Application not launching after building showing only white screen

### ISSUE THREAD

**Issue by Porter007** [iBotPeaches/Apktool#2254]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - windows
3. **APK From? (Playstore, ROM, Other)** - Apkpure(Other)

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. apktool d app.apk
2. apktool b app
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/garena-free-fire-android-il/com.dts.freefireth/download/2019111643-APK?from=variants%2Fversion

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by Porter007** [comment]
Please Look into it ASAP

**Comment by iBotPeaches** [comment]
Generally if an application has issues during launch, you'll need to examine the logcat. If you get a snippet of that crash, we can examine.

However, not enough information here to do anything else.
