### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by xmhwws** [iBotPeaches/Apktool#2255]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.2-dirty
2. **Operating System (Mac, Linux, Window)** -Window

I have 2 suggestions:

1. When the number of dex file methods exceeds 65535, apktool will fail to compile.
So, when apktool recompiles, can it automatically detect the number of methods, exceeding 65535, split the smali folder into 2 subfolders, and then compile again?

2. apktool will automatically decompile all dex files in the apk, including dex files in other folders such as assets.
Can apktool add a command line parameter without decompiling the dex files in other folders such as assets?

**Comment by Ticklefish** [comment]
There's a parameter for only decompiling the dex files in the root of the APK in 2.4.1. Use "--only-main-classes".

**Comment by xmhwws** [comment]
> There's a parameter for only decompiling the dex files in the root of the APK in 2.4.1. Use "--only-main-classes".

Thank you, you are right.

**Comment by iBotPeaches** [comment]
1) This would require some work rewriting files to new packages which is pretty out of scope of Apktool main purpose. It might be able to be done directly via dexlib with some work.

2) As mentioned above, this is a feature in the new `--only-main-classes` parameter
