### ISSUE TITLE
YouTube 14.50.53 xxhdpi apk does not recompile correctly

### ISSUE THREAD

**Issue by KevinX8** [iBotPeaches/Apktool#2264]
### Information
1. **Apktool Version (`apktool -version`)** - v2.4.1-c20659-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - WIndows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

``` Logcat of App
12-27 13:00:57.670: E/system_server(1903): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.676: E/system_server(1903): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.676: E/system_server(1903): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.677: E/system_server(1903): Invalid ID 0x00000000.
12-27 13:00:57.688: E/SurfaceFlinger(1671): ro.sf.lcd_density must be defined as a build property
12-27 13:00:57.693: E/vndksupport(3255): Could not load /vendor/lib/egl/libGLES_emulation.so from sphal namespace: dlopen failed: library "/vendor/lib/egl/libGLES_emulation.so" not found.
12-27 13:00:57.694: E/libEGL(3255): load_driver(/vendor/lib/egl/libGLES_emulation.so): unknown
12-27 13:00:57.692: E/android.youtub(3255): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.709: E/system_server(1903): Failed to find parent 0x7f1400e6 of bag 0x7f1403d9.
12-27 13:00:57.715: E/system_server(1903): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.715: E/system_server(1903): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.720: E/android.youtub(3255): Failed to find parent 0x7f1400e8 of bag 0x7f1403dc.
12-27 13:00:57.738: E/android.youtub(3255): Failed to find parent 0x7f1400e6 of bag 0x7f1403d9.
12-27 13:00:57.795: E/AndroidRuntime(3255): FATAL EXCEPTION: main
12-27 13:00:57.795: E/AndroidRuntime(3255): Process: com.google.android.youtube, PID: 3255
12-27 13:00:57.795: E/AndroidRuntime(3255): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity}: android.view.InflateException: Binary XML file line #4 in com.google.android.youtube:layout/youtube_controls_overlay: Binary XML file line #4 in com.google.android.youtube:layout/youtube_controls_overlay: Error inflating class android.widget.ImageView
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.os.Looper.loop(Looper.java:214)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.main(ActivityThread.java:7116)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at java.lang.reflect.Method.invoke(Native Method)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
12-27 13:00:57.795: E/AndroidRuntime(3255): Caused by: android.view.InflateException: Binary XML file line #4 in com.google.android.youtube:layout/youtube_controls_overlay: Binary XML file line #4 in com.google.android.youtube:layout/youtube_controls_overlay: Error inflating class android.widget.ImageView
12-27 13:00:57.795: E/AndroidRuntime(3255): Caused by: android.view.InflateException: Binary XML file line #4 in com.google.android.youtube:layout/youtube_controls_overlay: Error inflating class android.widget.ImageView
12-27 13:00:57.795: E/AndroidRuntime(3255): Caused by: java.lang.reflect.InvocationTargetException
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.createView(LayoutInflater.java:869)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.createView(LayoutInflater.java:791)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:945)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:965)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:976)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:697)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:549)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at iyr.x(PG:193)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at iyr.i(PG:107)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at iyg.get(PG:1)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at ixq.a(PG:6)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at iyr.w(PG:106)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at iyr.<init>(PG:11)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at dtl.aV(PG:4969)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at dtl.pF(PG:1710)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at dtl.it(PG:1240)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at dtl.a(PG:5608)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at mub.n(PG:40)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at efz.onCreate(PG:39)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at mvj.onCreate(PG:7)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at mub.onCreate(PG:181)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.Activity.performCreate(Activity.java:7698)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.Activity.performCreate(Activity.java:7687)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.os.Looper.loop(Looper.java:214)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.app.ActivityThread.main(ActivityThread.java:7116)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at java.lang.reflect.Method.invoke(Native Method)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
12-27 13:00:57.795: E/AndroidRuntime(3255): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040591 a=-1}
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.widget.ImageView.<init>(ImageView.java:206)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.widget.ImageView.<init>(ImageView.java:187)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	at android.widget.ImageView.<init>(ImageView.java:183)
12-27 13:00:57.795: E/AndroidRuntime(3255): 	... 43 more
12-27 13:00:57.940: E/eglCodecCommon(1903): glUtilsParamSize: unknow param 0x000082da
12-27 13:00:57.940: E/eglCodecCommon(1903): glUtilsParamSize: unknow param 0x000082da

```

### Steps to Reproduce
1. Decompile xxhdpi.apk with apktool (Youtube 14.50.53)
2. Recompile with apktool without any other changes
3. Resign apk and install with other resigned apks on device using SAI
If the apk is just resigned without decompiling and recompiling the above crash doesn't occur

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.°
https://apkfab.com/youtube/com.google.android.youtube

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes The issue occurs even with 0 changes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by KevinX8** [comment]
I should add that the xmls the error refers to seem to have no issues so this error is indeeded very perplexing

**Comment by MrDodojo** [comment]
Hmm, that's indeed an error it seems

**Comment by X1nto** [comment]
Yeah, YouTube refuses to recompile. did they add any security layers to apk or what is happening lol?

**Comment by Ticklefish** [comment]
I can't try it on an Android device (I haven't got one right now and Santa didn't give me one for some reason) but I was able to recompile that APK without any trouble at all. 
The recompiled APK is available here: [https://www.mediafire.com/file/vmaz36oov70csqq/YouTube_v14.50.53_recompiled.apk/file](url)
Give it a try and see if it works.

**Comment by X1nto** [comment]
> I can't try it on an Android device (I haven't got one right now and Santa didn't give me one for some reason) but I was able to recompile that APK without any trouble at all.
> The recompiled APK is available here: [https://www.mediafire.com/file/vmaz36oov70csqq/YouTube_v14.50.53_recompiled.apk/file](url)
> Give it a try and see if it works.

The problem is that it reconciles, but doesn't want to run at all. I don't really know what's the problem, but as @KevinX8 said, it refuses to start up.

**Comment by KevinX8** [comment]
> I can't try it on an Android device (I haven't got one right now and Santa didn't give me one for some reason) but I was able to recompile that APK without any trouble at all.
> The recompiled APK is available here: [https://www.mediafire.com/file/vmaz36oov70csqq/YouTube_v14.50.53_recompiled.apk/file](url)
> Give it a try and see if it works.

The issue isn't that it doesn't recompile but that the recompiling causes the files to change in an unintended way causing the app to crash on startup (logcat included in original post) and that's what I meant by "correctly". I am unsure of what apktool does to the apk that causes it to crash on startup as the logcat refers to an XML that has no obvious issues in it and seems to match decompilations of previous versions of the app that do not crash (eg. 14.41.xx)

**Comment by Ticklefish** [comment]
Hmm. I see your point. And the one I uploaded has the same problem?

**Comment by KevinX8** [comment]
> Hmm. I see your point. And the one I uploaded has the same problem?

Uh I just checked out your file and what you actually uploaded was an xapk/apks not an apk, and the apk files inside are not touched, maybe I should have expanded the instructions a little. Basically YouTube is now a split apk so you have to extract the xapk first (using 7zip or whatever you want) and then decompile the apks inside (the issue lies in the apk named com.google.android.youtube.apk aka the base apk) then after you have done the changes you wanted or in this case no changes you sign each apk with the same signature. Then you install the files loose using Split Apk Installer or rebundle them using bundletool. This process works for other split apk apps just fine. So if you want to replicate the issue you have to recompile the base apk with apktool and then sign all the apks inside with the same signature.

**Comment by TrianguloY** [comment]
Put in my two cents for someone with more time to check:

This is one of those cases where the useful exception is at the bottom of the stacktrace:
> ```
> Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040591 a=-1}
>  	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
>  	at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
>  	at android.widget.ImageView.<init>(ImageView.java:206)
>  	at android.widget.ImageView.<init>(ImageView.java:187)
>  	at android.widget.ImageView.<init>(ImageView.java:183)
>  	... 43 more
> ```

This shows that the issue is the attribute value _?ytOverlayBackgroundMedium_, not the xml file.

A quick google search of that exception suggests this is something with missing attribute values, but all solutions refer to adding elements to the code. Perhaps finding and adding the missing elements works as a workaround, but not as a final fix.

**Comment by Ticklefish** [comment]
> > Hmm. I see your point. And the one I uploaded has the same problem?
> 
> Uh I just checked out your file and what you actually uploaded was an xapk/apks not an apk, and the apk files inside are not touched, maybe I should have expanded the instructions a little. Basically YouTube is now a split apk so you have to extract the xapk first (using 7zip or whatever you want) and then decompile the apks inside (the issue lies in the apk named com.google.android.youtube.apk aka the base apk) then after you have done the changes you wanted or in this case no changes you sign each apk with the same signature. Then you install the files loose using Split Apk Installer or rebundle them using bundletool. This process works for other split apk apps just fine. So if you want to replicate the issue you have to recompile the base apk with apktool and then sign all the apks inside with the same signature.

Oh, it's an APKS. I know about these but I haven't had any practical experience with them, so I can't really help here. Sorry.

By the way, I took a look at bundletool. There doesn't seem to be any way to bundle a collection of APK files. All I can find was instructions to bundle an AAB made by Android Studio. What command are you using to rebundle them?

**Comment by KevinX8** [comment]
> > > Hmm. I see your point. And the one I uploaded has the same problem?
> > 
> > 
> > Uh I just checked out your file and what you actually uploaded was an xapk/apks not an apk, and the apk files inside are not touched, maybe I should have expanded the instructions a little. Basically YouTube is now a split apk so you have to extract the xapk first (using 7zip or whatever you want) and then decompile the apks inside (the issue lies in the apk named com.google.android.youtube.apk aka the base apk) then after you have done the changes you wanted or in this case no changes you sign each apk with the same signature. Then you install the files loose using Split Apk Installer or rebundle them using bundletool. This process works for other split apk apps just fine. So if you want to replicate the issue you have to recompile the base apk with apktool and then sign all the apks inside with the same signature.
> 
> Oh, it's an APKS. I know about these but I haven't had any practical experience with them, so I can't really help here. Sorry.
> 
> By the way, I took a look at bundletool. There doesn't seem to be any way to bundle a collection of APK files. All I can find was instructions to bundle an AAB made by Android Studio. What command are you using to rebundle them?

Oh sorry I assumed bundletool could create them from loose apk, personally I've just been zipping them up and using https://github.com/Aefyr/SAI to install them, technically speaking a .apks file is just a zip file containing the apk files https://fileinfo.com/extension/apks , so making a zip with the apk and renaming it to .apks should work with tools other than SAI aswell.

**Comment by Ticklefish** [comment]
Interesting. I'm going to try something with the original shared OP. I can't guarantee it'll work. Like I said, APKS's are new to me, but I have an idea.. I'll update this post in a few minutes..

**Comment by KevinX8** [comment]
> I've extracted all the files from the APK shared in the OP, decompiled all the resulting APK files (with a "**framework-res.apk**" from Android 10 AOSP installed), recompiled them with aapt (aapt2 gives errors) and zipped the new APK's in a new file. I also added the PNG and JSON file from the original APK.
> All the files in this ZIP file are at STORE levels of compression to match the original APK.
> 
> Lastly I renamed the ZIP as an APK and also made a copy as an APKS just to see what happens. These two files are here: [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apk/file](url) and [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apks/file](url)
> 
> I'm not saying these will definitely work or anything like that. This is very much an experiment. But could somebody please try them out and let me know if they work or not? You'll probably need to copy and paste the links.

Did you sign each individual APK file with the same signature? Or it still needs to be signed? Also renaming an apks as apk won't let you install it with package installer you'll still need to use adb/bundletool or SAI to install it. The OP links to an xapk which is almost the same as apks but is slightly customised by apkfab for their own purposes, it seems the usual bloat free apk mirror sites such as apkmirror still lack support for apks.

**Comment by Ticklefish** [comment]
> > I've extracted all the files from the APK shared in the OP, decompiled all the resulting APK files (with a "**framework-res.apk**" from Android 10 AOSP installed), recompiled them with aapt (aapt2 gives errors) and zipped the new APK's in a new file. I also added the PNG and JSON file from the original APK.
> > All the files in this ZIP file are at STORE levels of compression to match the original APK.
> > Lastly I renamed the ZIP as an APK and also made a copy as an APKS just to see what happens. These two files are here: [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apk/file](url) and [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apks/file](url)
> > I'm not saying these will definitely work or anything like that. This is very much an experiment. But could somebody please try them out and let me know if they work or not? You'll probably need to copy and paste the links.
> 
> Did you sign each individual APK file with the same signature? Or it still needs to be signed? Also renaming an apks as apk won't let you install it with package installer you'll still need to use adb/bundletool or SAI to install it. The OP links to an xapk which is almost the same as apks but is slightly customised by apkfab for their own purposes, it seems the usual bloat free apk mirror sites such as apkmirror still lack support for apks.

I used the original signature. No changes, just decompiled and recompiled. I can certainly try with a new key if it the file doesn't install.

**Comment by KevinX8** [comment]
> > > I've extracted all the files from the APK shared in the OP, decompiled all the resulting APK files (with a "**framework-res.apk**" from Android 10 AOSP installed), recompiled them with aapt (aapt2 gives errors) and zipped the new APK's in a new file. I also added the PNG and JSON file from the original APK.
> > > All the files in this ZIP file are at STORE levels of compression to match the original APK.
> > > Lastly I renamed the ZIP as an APK and also made a copy as an APKS just to see what happens. These two files are here: [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apk/file](url) and [https://www.mediafire.com/file/121stpk7jg7dpzc/YouTube_Test_001.apks/file](url)
> > > I'm not saying these will definitely work or anything like that. This is very much an experiment. But could somebody please try them out and let me know if they work or not? You'll probably need to copy and paste the links.
> > 
> > 
> > Did you sign each individual APK file with the same signature? Or it still needs to be signed? Also renaming an apks as apk won't let you install it with package installer you'll still need to use adb/bundletool or SAI to install it. The OP links to an xapk which is almost the same as apks but is slightly customised by apkfab for their own purposes, it seems the usual bloat free apk mirror sites such as apkmirror still lack support for apks.
> 
> I used the original signature. No changes, just decompiled and recompiled. I can certainly try with a new key if it the file doesn't install.

Just an FYI, -c won't work with split apks, luckily SAI has a resign apks feature tho :D

**Comment by Ticklefish** [comment]
Always good to learn something new. :)

**Comment by KevinX8** [comment]
After some heavy analysis we figured out that the issue is not the base apk but actually the xxhdp apk, when that gets decoded and recompiled it causes the error to occur.

**Comment by KevinX8** [comment]
issue is related to #2218 , closing as it's basically a duplicate
