### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by datbig** [iBotPeaches/Apktool#2266]
I encountered this error during the Recompile. Please help me find the problem!
![Screenshot (2)](https://user-images.githubusercontent.com/20509800/71577499-f822c000-2b26-11ea-8e96-d1996f24d22a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/20509800/71577605-649dbf00-2b27-11ea-8d89-14a137af6e3a.png)

**Comment by Ticklefish** [comment]
Your error is saying that there are two files with the same filename in your drawable-xxxhdpi folder: stat_sys_data_connected_4.5gg.png and stat_sys_data_connected_4.5g_dim.png.

I know they have different extensions but they have the same filename, which you can't do in Android. 

To fix this, you can rename one of these but you'll need to do some detective work and change any reference to that file in the rest of the APK. I'm nerdy enough to enjoy doing that sort of thing but it's a long tedious you probably don't want to get involved in.
So I'd suggest just deleting the second file and seeing what happens. 

This won't brick your phone or anything. The worst that will happen is that the new APK won't install. Or, if it does, your data connection might not work properly. 
As long as you've made a backup you'll be fine.

**Comment by iBotPeaches** [comment]
This might be a bug due to the strangeness of compound extensions. I think APK will be needed here to investigate further.

**Comment by datbig** [comment]
> This might be a bug due to the strangeness of compound extensions. I think APK will be needed here to investigate further.
Đây là 2 tệp của tôi, xin hãy xem giúp tôi!
https://drive.google.com/drive/folders/1tL5_LNm9BGwBMJbeKVfCuoJvjqC7Jag7?usp=sharing

**Comment by Ticklefish** [comment]
![screenshot](https://user-images.githubusercontent.com/18163767/71812980-64924780-3070-11ea-9d50-6dc3ce894dba.PNG)

I wonder if those files have the wrong filename. Maybe they're supposed to be "**stat_sys_data_connected_4_5g_dim.png**" and "**stat_sys_data_connected_4_5gg.png**" instead. 
This would match the other files in the folder and it would mean the APK would compile after the entries in "**public.xml**" have been changed. 

I tried this but then got some resource errors. You provided one framework file - "**lge-res.apk**". You'll need two. I'm pretty sure LG roms still have "**framework-res.apk"" files in them. Make sure you install that as well when decompiling your file. Then, if you make those changes, your file should recompile.

Hopefully..

**Comment by iBotPeaches** [comment]
As mentioned above there is some strangeness with filenames. All in all, I don't think Apktool is at fault and doing some backlog cleaning.

Closing.
