### ISSUE TITLE
Questions, copy activity between apks

### ISSUE THREAD

**Issue by beshoo** [iBotPeaches/Apktool#2267]
Dear all, Happy New year everyone.
I know this is not related questions to the apktool  but i am sure it will be useful for others.

Lets say i have android studio project, and i want to copy an activity form it to another apk.

What i did to achieve this:
Mimic same directory structure of the target apk in the android studio.
Build the apk
APKTOOL d the apk.
Copy the activity page.
Copy the activity resource filed.
Now the problem.
I have to find all activity resource ids in the public.xml, then copy them to the target.

Update the hex values of each resource to match target pool values in the target apk by adding +1 to the latest hex value.

Then update the activity smali pages with the new hix values. And adding the activity layout hext to the public.xml

Update ids.xml with all new ids we have. And some time the attr.xml

It is a nightmare, specially if you want to do this each time you add a new resource.

But at the end of the day, it works on the targeted apk with out any problems.

The questions, is there any automat way to do this? It is nightmare to do thats steps each time.

I am sorry to adk non related questions, but this place full of professional people.

Thanks again.
Best wishes for all of you.

**Comment by iBotPeaches** [comment]
You just described the process. Anything can be automated once you understand it manually. Those automated steps won't be in Apktool, but you could write that in the language of your choice as a little script or something more complicated.

Thanks for the detailed guide/information.

**Comment by beshoo** [comment]
@iBotPeaches Thank you for your kindly reply
Yes I did that script and it help, but it will be more elegant if APKTOOL when it detects missing ids but in public.xml. it will generate a new id and place it in the public.xml, and replace the wrong one form the smali file.

I think we have to provide the original public.xml to match the hex with the name ?
