### ISSUE TITLE
apktool error

### ISSUE THREAD

**Issue by canxx99** [iBotPeaches/Apktool#2270]
`Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
connected/smali/com/connected2/ozzy/c2m/MainActivity.smali[875,4] Invalid register: v22. Must be between v0 and v15, inclusive.
Could not smali file: com/connected2/ozzy/c2m/MainActivity.smali`

How to fix this

**Comment by Ticklefish** [comment]
You'll need to do some smali editing. There's a very handy guide to this here: [https://groups.google.com/forum/#!topic/apktool/Elvhn32HvJQ](url)

**Comment by iBotPeaches** [comment]
As mentioned above. Not sure how you got a register at 22, that is not valid.

**Comment by canxx99** [comment]
Sorry, I do not understand how to fix this error is caused

**Comment by canxx99** [comment]
some apk no problem some get this error

**Comment by canxx99** [comment]
msfvenom -x yükü. apk ..... Bu şekilde yaptığınızda hata yok Elle yaptığımda hata alıyorum

**Comment by Ticklefish** [comment]
> Sorry, I do not understand how to fix this error is caused

You have to look at the code and make changes to it. What changes those are I don't know - it depends on the specific code. 

I can't help any further with this one, you need to follow the link I provided and edit your smali.

**Comment by canxx99** [comment]
![Screenshot_20200106_131037](https://user-images.githubusercontent.com/52892904/71811513-f6587f80-3085-11ea-9fb1-56101882fa93.jpg)

directed me to a blank page

**Comment by canxx99** [comment]
I don't know where my smali file is

**Comment by Ticklefish** [comment]
You'll need to copy and paste the link. Github doesn't seem to like it if you click on links directly for some reason...

Your smali file is in the smali folder of your decompiled APK. The error message tells you which file it is. 

I'm not a smali expert so I can't help you any more with this, sorry. There really isn't a simple answer to this issue - it's a case of reading the code and making changes to it.

Best of luck!

**Comment by canxx99** [comment]
I fixed this problem, but I have another problem

`brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 453123, --version-name, 2.19.360, --no-version-vectors, -F, /tmp/APKTOOL11690018052326113866.tmp, -0, arsc, -0, png, -0, wav, -0, m4a, -0, mp4, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20200106-20606-1r9uood/original/res, -M, /tmp/d20200106-20606-1r9uood/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool`

**Comment by canxx99** [comment]
Is there a solution to this problem?

**Comment by J0kErF69** [comment]
> I fixed this problem, but I have another problem
> 
> `brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 453123, --version-name, 2.19.360, --no-version-vectors, -F, /tmp/APKTOOL11690018052326113866.tmp, -0, arsc, -0, png, -0, wav, -0, m4a, -0, mp4, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20200106-20606-1r9uood/original/res, -M, /tmp/d20200106-20606-1r9uood/original/AndroidManifest.xml] Error: Unable to rebuild apk with apktool`

can you show me the solution, I am facing this problem
