### ISSUE TITLE
rebuild apk can not login/link the google fit account

### ISSUE THREAD

**Issue by reliveinfire** [iBotPeaches/Apktool#2273]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Steps to Reproduce
1. apktool d base.apk
2. apktool b base -o mybuild.apk
3. sign and install the apk
4. open the application, the application needs to login/link google fit account, but the rebuild version can not login/link the google fit account.
I am not sure if i need to config something if the application needs to link google account.

**Comment by BMD4E** [comment]
Google login can't work if apk has been signed and signature is different than original. It is normal
You must keep APK unsigned with disabled signature check on rooted device to work.

https://platinmods.com/threads/how-to-install-an-unsigned-apk-root-lucky-patcher.43/

**Comment by reliveinfire** [comment]
> Google login can't work if apk has been signed and signature is different than original. It is normal
> You must keep APK unsigned with disabled signature check on rooted device to work.
> 
> https://platinmods.com/threads/how-to-install-an-unsigned-apk-root-lucky-patcher.43/
if i dont want to root my device.
is it possible to add my own  signature for the apk?
i find out that if apk needs google sign-in service, the developer have to uploda some SHA key.
So, i am thinking to register my keysotre and upload the SHA key.
and modify the google res/string_name google_api_key....etc (i dont know what else to modify)
does this work?

**Comment by iBotPeaches** [comment]
As mentioned above - Google login can detect malformed signatures in applications. There is nothing fortunately Apktool can do this.
