### ISSUE TITLE
AAPT bug: Unprefixed attribute values are not resolved to IDs

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#2274]
### Information
1. **Apktool Version:** 2.4.1
2. **Operating System:** Linux, Windows
3. **APK From:** Any APK

### Description
This is usually not an app-breaker, as Android seems to handle those string values itself and find the proper resource. However, certain apps depend on those attribute values and, understandably, expect them to be integers (resource IDs), so they use parseInt on them, which leads to a crash with the rebuilt APK. Even though it works alright for most apps, this can be considered as a bug, because all resource reference values are expected to be dereferenced when compiled.
Seems to be only affecting attributes without a namespace (i.e. "style", "layout").

### Screenshot
![ResRefValueBug](https://user-images.githubusercontent.com/8811086/72125755-6d399500-3372-11ea-879a-946421830dd8.png)

### Steps to Reproduce
Can be easily reproduced by making a blank APK with a single layout and a single style resource, example:
Define a style "MyStyle", no items needed.
Inside the layout put any kind of View and define a "style" attribute with the value "@style/MyStyle".
Compile and check the compiled XML file with a hex editor. The value was saved as a string instead of a resource ID.

**Comment by IgorEisberg** [comment]
The solution is to remove the "nameResId == 0" check here:
https://github.com/iBotPeaches/platform_frameworks_base/blob/apktool_9.0.0/tools/aapt/XMLNode.h#L84

Unprefixed attributes don't have a nameRedId, so this check tells the "flatten" procedure to force this attribute's value to be a string, even though the value type is already defined as REFERENCE.

**Comment by iBotPeaches** [comment]
Thanks @IgorEisberg  - https://github.com/iBotPeaches/platform_frameworks_base/commit/0a1db7e5baf5ba5e9cb5ad5c8aded344ce872a2c

**Comment by IgorEisberg** [comment]
Fixed by: https://github.com/iBotPeaches/platform_frameworks_base/pull/10
