### ISSUE TITLE
platform_frameworks_base error

### ISSUE THREAD

**Issue by jayce211** [iBotPeaches/Apktool#2281]
I am attempting Building the aapt1 (Legacy) binary from https://github.com/iBotPeaches/Apktool/blob/master/INTERNAL.md#first-we-need-the-aosp-source. But I am getting the following error, not sure where else to post this as I am following the instructions from apktool website. Has anyone seen this, it doesn't happen when I build it straight from the master without changing the files over. How do you fix it?

Steps to produce:
1. source build/envsetup.sh
2. lunch sdk-eng
3. make LOCAL_MULTILIB=64 USE_NINJA=false aapt

Error produced:

============================================
PLATFORM_VERSION_CODENAME=R
PLATFORM_VERSION=R
TARGET_PRODUCT=sdk
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.3.0-26-generic-x86_64-Ubuntu-18.04.3-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=AOSP.MASTER
OUT_DIR=out
============================================**
[100% 51/51] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: frameworks/base/Android.bp:658:22: unrecognized property "no_framework_libs"
error: frameworks/base/Android.bp:760:22: unrecognized property "no_framework_libs"
error: frameworks/base/Android.bp:859:22: unrecognized property "no_framework_libs"
error: frameworks/base/core/res/Android.bp:19:22: unrecognized property "no_framework_libs"
error: frameworks/base/proto/Android.bp:8:22: unrecognized property "no_framework_libs"
error: frameworks/base/test-mock/Android.bp:25:22: unrecognized property "no_framework_libs"
error: frameworks/base/libs/hwui/Android.bp:48:25: unrecognized property "product_variables.device_uses_hwc2"
error: frameworks/base/test-legacy/Android.bp:31:22: unrecognized property "no_framework_libs"
00:07:46 soong bootstrap failed with: exit status 1

**Comment by iBotPeaches** [comment]
I've never seen this before apologies. Building AOSP isn't easy and might be some better places than this tracker unforunately to find a solution.
