### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by elementarvodka** [iBotPeaches/Apktool#2282]
### Information
1. **Apktool Version = 2.4.1
2. **Operating System = Windows 10 64bit + Java 64Bit
3. **APK From? Other

I: Using Apktool 2.4.1
I: Copying C:\Users\Elementarvodka\AppData\Local\Temp\apk-editor-studio\apk\{80a9ec26-ffbc-4f7b-9906-a6d953903f0d} classes.dex file...
I: Copying C:\Users\Elementarvodka\AppData\Local\Temp\apk-editor-studio\apk\{80a9ec26-ffbc-4f7b-9906-a6d953903f0d} classes2.dex file...
I: Building resources...W: res\drawable-xxxhdpi\icon_22 (2).png: Invalid file name: must contain only [a-zA-Z0-9$_.]. Ignoring...
W: res\drawable-xxxhdpi\icon_22 (2).png: Invalid file name: must contain only [a-zA-Z0-9$_.]. Ignoring...
W: res\drawable-xxxhdpi\icon_22 (2).png: Invalid file name: must contain only [a-zA-Z0-9$_.]. Ignoring...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ELEMEN~1\AppData\Local\Temp\brut_util_Jar_2308381078335587559.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 28, --version-code, 454021, --version-name, 2.19.360, --no-version-vectors, -F, C:\Users\ELEMEN~1\AppData\Local\Temp\APKTOOL212154241242535661.tmp, -e, C:\Users\ELEMEN~1\AppData\Local\Temp\APKTOOL4009780531666491095.tmp, -0, arsc, -I, C:\Users\Elementarvodka\AppData\Local\apk-editor-studio\frameworks\1.apk, -S, C:\Users\Elementarvodka\AppData\Local\Temp\apk-editor-studio\apk\{80a9ec26-ffbc-4f7b-9906-a6d953903f0d}\res, -M, C:\Users\Elementarvodka\AppData\Local\Temp\apk-editor-studio\apk\{80a9ec26-ffbc-4f7b-9906-a6d953903f0d}\AndroidManifest.xml]

someone got a solution?

**Comment by Ticklefish** [comment]
Have you tried sorting out the invalid file name that's mentioned in the error message? That'd be my first suggestion.

You could try renaming every instance of "**icon_22 (2).png**" in your APK to "**icon_22_(2).png**" for example. You'll need to change it in public.xml as well.

**Comment by iBotPeaches** [comment]
I don't think parenthesis are allowed in resource names. Generally Android is requiring no symbols all lowercase, but Apktool for backward compatibility extends this to uppercase and even adds in `$` for old compatibility.

We can't just allow any character, because Android is indeed become more restrictive for resource names. 

So there is no bug here. The resource names are invalid that were presented.

**Comment by FYSong** [comment]
Excuse me, have you fix this issue, would you share the solution? Thanks
