### ISSUE TITLE
-

### ISSUE THREAD

**Issue by DeBerk** [iBotPeaches/Apktool#2283]
-

**Comment by nnelas** [comment]
Hi @DeBerk, unfortunately, TikTok uses resources obfuscation (like AndroResGuard), which means that apktool cannot compile/recompile since it uses AOSP framework APK to manage these operations and these resource IDs aren't found on AOSP.
If you only want to decompile Java (smali) code, you can always use flag --no-res and everything should work normally

**Comment by elis-k** [comment]
Any ways to get around Tik Tok SSL pinning guys?

**Comment by iBotPeaches** [comment]
I just recently closed a ticket that didn't have enough details for represented this stacktrace - https://github.com/iBotPeaches/Apktool/issues/2285

It appears as you noticed the split apks are making it difficult to decode and re-encode an application, probably due to that.

I'm not sure if we have a split ask issue yet. So I'm going to claim this one as it. So we can first research and answer the question.

---

Can the `base.apk` live on its own and all splits are just additional qualifiers? Or do you require a split in order to make a feasible package?

**Comment by vinhjaxt** [comment]
You can use option -r to not decompile resource.
When install split apk, using SAI (Split APK Installer)

**Comment by elis-k** [comment]
Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.

**Comment by limbodin** [comment]
> Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.

Hey, 
which emu and frida version you used?

thanks

**Comment by igorpyan** [comment]
There is similar case for `jp.naver.line.android` app (getting from PlayStore).
Environment: Ubuntu 20.04.1 LTS, apktool_2.4.1.jar

```
$ java -jar ~/temp/apktool_2.4.1.jar d jp.naver.line.android.apk -o src2 -s
I: Using Apktool 2.4.1 on jp.naver.line.android.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
```

But, for example, jadx does this job successfully:
```
$ jadx jp.naver.line.android.apk -d . -s
INFO  - loading ...
INFO  - processing ...
INFO  - done
```

**Comment by androidethiopia** [comment]
I successfully de-obfuscate de-compiled / recompiled , then merged the split apks for TikTok v17.8.4 with apktool and my own tool. Here is the link to download 
https://mega.nz/file/9vAmUTqK#zndOACdS7MIGl0VZgQKHawoSMj-E-6lTlwxA8TVI9hk

**Comment by iBotPeaches** [comment]
Classifying this ticket as the feature request for split apks. Not sure what Apktool is going to do it. Maybe just gracefully fail and request a merged application.

**Comment by xenud** [comment]
> Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.

Are you still working on it or have you given up? Maybe I have some news... and then I wanted to ask you something

**Comment by androidethiopia** [comment]
> > Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.
> 
> Are you still working on it or have you given up? Maybe I have some news... and then I wanted to ask you something

Yes, I managed to merge decompile/recompile  all versions of tiktok (17.6.4 - 18.4.7)

**Comment by Liquid44** [comment]
> > > Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.
> > 
> > 
> > Are you still working on it or have you given up? Maybe I have some news... and then I wanted to ask you something
> 
> Yes, I managed to merge decompile/recompile all versions of tiktok (17.6.4 - 18.4.7)

How may I ask? Using jadx or skipping resources?

**Comment by Ali666-jeo** [comment]
Sparkle Photo Effect & Pip Editor<a href="https://play.google.com/store/apps/details?id=masterlogix.photeditor.pipcamera.sparkeleffect"> Pip Editor</a> - Masterlogix best app to make your photo fully attractive and heart touching.
You can use four tools in this app with many effects like photo frames, overlays effects, twinkle effects, photo cropping, photo filters and photo borders in this best Photo Editor App - Pip Camera - Sparkle Effect (Blur)

**Comment by androidethiopia** [comment]
> > > > Just an update if anyone needs it, i managed to intercept traffic using frida. Android emulator & frida, worked great.
> > > 
> > > 
> > > Are you still working on it or have you given up? Maybe I have some news... and then I wanted to ask you something
> > 
> > 
> > Yes, I managed to merge decompile/recompile all versions of tiktok (17.6.4 - 18.4.7)
> 
> How may I ask? Using jadx or skipping resources?

I decompiled the resources also , i made my own code to reconstruct the obufuscated resource name. using both aapt and aapt2.

**Comment by sakibguy** [comment]
Thanks guys 

for your input and effort 
to make Tiktok decompile/recompile work.
