### ISSUE TITLE
Auto rename smalis with obfuscated names?

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#2284]
### Information
1. **Apktool Version**  2.4.1
2. **Operating System** Windows 10 x64
3. **APK From?** Other

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on lp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\quocd\AppData\Local\apktool\framework\1.apk
I: Renamed manifest package found! Replacing ru.YZHCKlfh.NMlYQHkce with ru.aaaaaaat.installer
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. `apktool d -o out in.apk`
2. `apktool b -o out in.apk`

### Frameworks
Not applicable

### APK
[lp.zip](https://github.com/iBotPeaches/Apktool/files/4103509/lp.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

### Comment
There is no problem decompiling and compiling and the app runs fine
Problem is some functionality are broken, app list not showing, buttons not working... and the app doesn't even crash
The app is obfuscated by renaming smali with illegal characters and symbols
Is it possible to auto rename to valid names like Jadx does automatically? Jadx does a good job recognizing names and showing source correctly

![image](https://user-images.githubusercontent.com/24647715/72993164-36915f00-3df5-11ea-8d72-560e8a8813e8.png)

This is what decompiled folder looks like

![image](https://user-images.githubusercontent.com/24647715/72993220-4f9a1000-3df5-11ea-8683-3b449d578d24.png)

**Comment by alitteration** [comment]
I have a similar issue, Have you got any luck with that?

**Comment by LGLTeam** [comment]
Not yet, i'm waiting for developer's response

**Comment by iBotPeaches** [comment]
Files are already renamed on smali side if they clash with known restrictions (normally on windows for files like COM).

I'm not sure how jdax using `j###` is anymore helpful than `'$13`. Either way, Apktool just leverages smali for this and I don't think you will get any traction with this idea. 

Closing.
