### ISSUE TITLE
apk crashed when i change the api from 26 to 28 apktool

### ISSUE THREAD

**Issue by elazzabimohamed** [iBotPeaches/Apktool#2286]
hi 
i have a apk api level 26 but when i change the api level to 28 from apk.uml  it crached when i try to test it

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to either link/upload the affected apk. Additionally try and provide any logcat and/or stacktrace possible.
