### ISSUE TITLE
Compile Error for Netfilx APK from Amazon store for Fire TV 4K stick

### ISSUE THREAD

**Issue by alitteration** [iBotPeaches/Apktool#2291]
### Information
1. **Apktool Version (`2.4.1`)** -
2. **Operating System (Windows and Linux)** -
3. **APK From? (Amazon Store)** -

### Stacktrace/Logcat
Windows log
```
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
[Fatal Error] :2:93: Attribute "android:" was already specified for element "manifest".
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout-v26\abc_screen_toolbar.xml:5: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout-v26\abc_screen_toolbar.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\abc_action_menu_item_layout.xml:2: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\abc_action_menu_item_layout.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_browse_fragment.xml:4: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_browse_fragment.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_details_fragment.xml:2: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_details_fragment.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedactions.xml:4: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedactions.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedactions_item.xml:4: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedactions_item.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedbuttonactions.xml:4: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedbuttonactions.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedstep_background.xml:2: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedstep_background.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedstep_fragment.xml:8: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_guidedstep_fragment.xml: error: file failed to compile.
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_image_card_view.xml:5: error: not well-formed (invalid token).
W: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res\layout\lb_image_card_view.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_5025868252552468858.tmp, compile, --dir, C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\res, --legacy, -o, C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\base-netflix\build\resources.zip]

```
Linux log
```
: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/abc_action_menu_item_layout.xml:2: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_browse_fragment.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_details_fragment.xml:2: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_guidedactions.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_guidedactions_item.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_guidedbuttonactions.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_guidedstep_background.xml:2: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_guidedstep_fragment.xml:8: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_image_card_view.xml:5: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_onboarding_fragment.xml:12: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_playback_transport_controls_row.xml:11: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_row_media_item.xml:6: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_shadow.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/lb_vertical_grid_fragment.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/main.xml:5: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res/layout/mr_controller_material_dialog_b.xml:18: error: Error parsing XML: not well-formed (invalid token)
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5014328195845033451.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 29, --version-code, 3231, --version-name, 7.1.0, --no-version-vectors, -F, /tmp/APKTOOL4475119709111461586.tmp, -e, /tmp/APKTOOL4008468087298199651.tmp, -0, arsc, -I, /home/hi/.local/share/apktool/framework/1.apk, -S, /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/res, -M, /mnt/hgfs/Downloads-2/com.netflix.ninja-1/xx/AndroidManifest.xml]
```
### Steps to Reproduce
Trying to compile the APK after decompiling it fails, I even tried to just decompile and re-compile it without editing anything but It still fails. I checked those xmls and there seems to be some "weird" characters in the XML tags.

### Frameworks
I tried apktool empty-framework-dir --force and that didn't help either, please try to just decompile and recompile and you will see what I mean.

### APK
https://www.mediafire.com/file/72nundn2id7g6zw/base.apk/file

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?      Yes
2. If you are trying to install a modified apk, did you resign it?        Yes
3. Are you using the latest apktool version?          Yes

**Comment by Ticklefish** [comment]
You're right, you do get some odd characters in some of the XML files. This is what is in the "**lb_browse_fragment.xml**" file:

> <?xml version="1.0" encoding="utf-8"?>
> <FrameLayout android:id="@id/browse_dummy" android:layout_width="fill_parent" android:layout_height="fill_parent"
>   xmlns:android="http://schemas.android.com/apk/res/android">
>     <o.ıɍ android:id="@id/browse_frame" android:focusable="true" android:focusableInTouchMode="true" android:descendantFocusability="afterDescendants" android:layout_width="fill_parent" android:layout_height="fill_parent">
>         <o.ıƗ android:id="@id/browse_container_dock" android:layout_width="fill_parent" android:layout_height="fill_parent">
>             <o.ɩɪ android:id="@id/scale_frame" android:layout_width="fill_parent" android:layout_height="fill_parent" />
>         </o.ıƗ>
>         <FrameLayout android:id="@id/browse_headers_dock" android:clipToPadding="false" android:layout_width="wrap_content" android:layout_height="fill_parent" android:paddingEnd="50.0dip" />
>     </o.ıɍ>
> </FrameLayout>

I'd be tempted to replace those with some legitimate XML tags but I'd be essentially guessing what those tags should be. There's no guarantee that would actually work.

This may be a deliberate move by the developer to stop people from modding the APK.

If you decompile without processing the "**resources.arsc**" file, this gets past this issue and the resulting files can recompile. But you will be limited in what you can modify.

**Comment by alitteration** [comment]
> You're right, you do get some odd characters in some of the XML files. This is what is in the "**lb_browse_fragment.xml**" file:
> 
> > <o.ıɍ android:id="@id/browse_frame" android:focusable="true" android:focusableInTouchMode="true" android:descendantFocusability="afterDescendants" android:layout_width="fill_parent" android:layout_height="fill_parent">
> > <o.ıƗ android:id="@id/browse_container_dock" android:layout_width="fill_parent" android:layout_height="fill_parent">
> > <o.ɩɪ android:id="@id/scale_frame" android:layout_width="fill_parent" android:layout_height="fill_parent" />
> > </o.ıƗ>
> > 
> > </o.ıɍ>
> 
> I'd be tempted to replace those with some legitimate XML tags but I'd be essentially guessing what those tags should be. There's no guarantee that would actually work.
> 
> This may be a deliberate move by the developer to stop people from modding the APK.
> 
> If you decompile without processing the "**resources.arsc**" file, this gets past this issue and the resulting files can recompile. But you will be limited in what you can modify.

Indeed that's what I've actually tried to do and I went through every single XML file and replaced them manually, and It successfully got compiled, and I was able to install it, but it crashes every time I try to run/load it.

Could there be any other way to do it without using the -r flag and be limited as you've said?

Thanks!

**Comment by AndnixSH** [comment]
Netflix APK is obfuscated in both xml and smali to prevent modifying.

![image](https://user-images.githubusercontent.com/40742924/83973032-fa622500-a8e3-11ea-8f8e-d44fa87e6dd3.png)

**Comment by iBotPeaches** [comment]
Going to chuck this up to a magic apk. The obfuscation is probably next level with DRM being involved. If we can isolate an issue inside of a large application to triage/fix. That would be simpler.

This ticket will really go nowhere without it. Just too large of a black box to even begin investigating. Closing.
