### ISSUE TITLE
Game won't load 100% after rebuild although i do not make any change.

### ISSUE THREAD

**Issue by mrcas** [iBotPeaches/Apktool#2294]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows 8.1
3. **APK From? (Playstore, ROM, Other)** - Playstore

### APK
https://play.google.com/store/apps/details?id=com.sonypicturestelevision.hoteltblast&hl=en

Step to repro:
1. apktool d hotel_transylvania_blast_puzzle_game_v1.6.2.apk
2. apktool b  "hotel_transylvania_blast_puzzle_game_v1.6.2" -o hotel_transylvania_blast_puzzle_game_v1.6.2_modmenu.apk

This error occurs because of error Androidmanifest.xml. I try to copy the original Androidmanifest.xml to the rebuild apk, it run normally.

**Comment by iBotPeaches** [comment]
Apktool builds unsigned applications. You can't decode and rebuild and expect it to just "work" without some extra effort. The reason it works with the original manifest is a trick that `-c` uses, but even that is moot in the new future of v2/v3 of signature schemes.

I don't see a bug here.
