### ISSUE TITLE
Unable to rebuild apk

### ISSUE THREAD

**Issue by xmhwws** [iBotPeaches/Apktool#2295]
### Information
1. **Apktool Version (`apktool -version`)** -
2.4.2-dirty

2. **Operating System (Mac, Linux, Windows)** -
Windows 10

apk link: https://drive.google.com/open?id=1PaqYoyqr36L5RTgzYDhR2Vi1skYgBmGj

When I decompile the apk and then recompile the apk, it reports the following error:
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:test\out\res\drawable-xxhdpi-v4\permission_huawei.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:test\out\res\drawable-xxhdpi-v4\permission_oppo.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:test\out\res\mipmap-xxhdpi-v4\ic_jiantu_bg_19.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:test\out\res\mipmap-xxhdpi-v4\ic_jiantu_bg_24.png

I checked the error files and found that they were actually in jpeg format, so I changed the file extension from png to jpeg. (I hope apktool doesn't care about the file suffix, just a reminder instead of terminating the compilation)
Recompile the apk, and it reports the error again:
W: D:test\out\res\layout\frg_new_home_page.xml:13: error: Error parsing XML: duplicate attribute
W:
W: D:test\out\res\layout-v17\frg_new_home_page.xml:13: error: Error parsing XML: duplicate attribute

I don't know how to solve this problem

**Comment by xmhwws** [comment]
The second apk link:https://drive.google.com/open?id=1Yn8MfdSvEdv1UaLUKfCUUzjKPpB1x0AA

When I decompile the apk and then recompile the apk, it reports the following error:
I: Building resources...
W: invalid resource directory name: D:\test222\out\res navigation

I try ‘--use-aapt2’ to decompile the apk and then recompile the apk, it reports the following error:
I: Building resources...
W: D:test222\out\res: error: failed to open directory: 系统找不到指定的文件。 (2).
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\hhhh\AppData\Local\Temp\brut_util_Jar_4987331602928935728.tmp, compile, --dir, D:test222\out\res, --legacy, -o, D:test222\out\build\resources.zip]

**Comment by iBotPeaches** [comment]
As you mentioned. It appears to be invalid images. They are jpegs and not pngs, leading to improper decoding. 

They are bad apks at the end of the day. It will take massaging to get them to work within Apktool, but I don't see a bug here. Maybe a feature enhancement to read magic header to determine true file-type, but that would increase decoding by a lot due to IO.

**Comment by xmhwws** [comment]
> The second apk link:https://drive.google.com/open?id=1Yn8MfdSvEdv1UaLUKfCUUzjKPpB1x0AA
> 
> When I decompile the apk and then recompile the apk, it reports the following error:
> I: Building resources...
> W: invalid resource directory name: D:\test222\out\res navigation
> 
> I try ‘--use-aapt2’ to decompile the apk and then recompile the apk, it reports the following error:
> I: Building resources...
> W: D:test222\out\res: error: failed to open directory: 系统找不到指定的文件。 (2).
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\hhhh\AppData\Local\Temp\brut_util_Jar_4987331602928935728.tmp, compile, --dir, D:test222\out\res, --legacy, -o, D:test222\out\build\resources.zip]

`res navigation` and `--use-aapt2` What are the two reasons for this? What is the solution?
