### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES or RUNTIME exception

### ISSUE THREAD

**Issue by Chandu1233** [iBotPeaches/Apktool#2298]
### Information
1. **Apktool Version (`2.0.1 `)** -
2. **Operating System (Mac)** -

### Steps to Reproduce

I decompile the APK with 

`apktool d kotlin_test.apk`

When I build the apk WITH OUT ‘-c’ option, the META-INF files are missing and causing RUN TIME exceptions as some files 3rd party libraries are missing. 

`apktool b kotlin_test`

If I use ‘-c’ option, META_INF files exists in the apk.  but after signing with ‘Jar signer’ and align the apk, I am getting INSTALL_PARSE_FAILED_NO_CERTIFICATES error.

`apktool b kotlin_test -c`

**Here is complete error message :**
Failed to collect certificates from /data/app/vmdl1855218170.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl1855218170.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?

Please Help

**Comment by iBotPeaches** [comment]
This is intended. Signatures are stripped by default as modifying an application (even just doing d/b) will change the application slightly. With signature schemes 2/3 this nullifies the signature and signature scheme 1 can only be abused in so many ways.

`-c` - is only helpful in older versions and kept around in a slow deprecation, I don't see a bug here.

**Comment by leao-nardo** [comment]
> This is intended. Signatures are stripped by default as modifying an application (even just doing d/b) will change the application slightly. With signature schemes 2/3 this nullifies the signature and signature scheme 1 can only be abused in so many ways.
> 
> `-c` - is only helpful in older versions and kept around in a slow deprecation, I don't see a bug here.

is there any option to keep it signed so after rebuild it can install and work normally ?
