### ISSUE TITLE
Question: Possible to use on Android app?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [iBotPeaches/Apktool#2304]
I'd like to ask if it's possible to use this tool within an Android, by calling functions of it, to parse APK files directly, and without decompressing them.

Reasons for asking this:
1. The framework of Android only offers a [single function for that](https://developer.android.com/reference/android/content/pm/PackageManager#getPackageArchiveInfo(java.lang.String,%20int)), allows to parse APK files via a file path.
2. It is impossible to parse split APK files using the framework (it fails)
3. Google pushes to use SAF API, which might mean we won't even be able to use file-path anymore, and only Uri and inputStream. I tried to use Android's framework while using SAF, but seems it failed to get the app-label and app-icon from the APK.
This means that for now, the only reliable way to parse APKs while using SAF is to copy the file to the app's paths, and then parse it there using the normal framework, which is bad for performance and storage.
4. The [only library for Android that I've found](https://github.com/hsiafan/apk-parser) which I can use to parse APK files allows to do it via file path too, and it has its own issues of parsing for some cases.

**Comment by iBotPeaches** [comment]
While possible, it isn't something this project will be supporting at this point in the time. There are millions of combinations of chipsets, firmware, mods and more than can be on a device. The maintenance and simple building nightmare to support it would be massive.

I wrote about this a small part in the v2.4.0 release notes here - https://connortumbleson.com/2019/03/03/apktool-v2-4-0-released/

**Comment by AndroidDeveloperLB** [comment]
How about only the APK parsing part?
Would this be ok?
Maybe you could split the library so that a part of it would be about parsing, and be usable for Android?
Please consider it. There is nobody to ask about it. Especially not Google
