### ISSUE TITLE
Install github app on the repo to be notified of new releases

### ISSUE THREAD

**Issue by neillfontes-sl** [iBotPeaches/Apktool#2309]
Hi all,

I would like to subscribe to this repo using the Slack/Github integration but I am getting an exception when I try to:

`/github subscribe iBotPeaches/Apktool`

I get the following:

```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You will need to ask the owner of the repository to install it for you. Give them this link.
```

This would help some people watching this repo and keeping up with the latest releases of the apktool which would imply changes on their side. 

One instance that works is:

`/github subscribe github/opensource.guide`

Best,

Neill

**Comment by iBotPeaches** [comment]
Sorry, I don't feel safe installing dependencies to this application for that purpose. It shouldn't been too hard for scripts like that to just read an RSS feed or something. It shouldn't need repo permissions.

Let me know if I misunderstood this and I can take another look.
