### ISSUE TITLE
Cannot rebuild a decompiled a whole new apk without any modification

### ISSUE THREAD

**Issue by simonkuang** [iBotPeaches/Apktool#2313]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Win10
3. **APK From? (Playstore, ROM, Other)** - a whole new project created by AS 3.6.1

### Stacktrace/Logcat

```
D:\temp\apktool-demo>D:\Program\apktool\apktool.bat d -f D:\temp\apktool-demo\app-debug.apk -o D:\temp\apktool-demo\uncompressed
I: Using Apktool 2.4.1 on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Administrator\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\temp\apktool-demo>D:\Program\apktool\apktool.bat b D:\temp\apktool-demo\uncompressed
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: D:\temp\apktool-demo\uncompressed\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_5814025292629102268.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL6771602854206042057.tmp, -e, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL8785829174415111368.tmp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, D:\temp\apktool-demo\uncompressed\res, -M, D:\temp\apktool-demo\uncompressed\AndroidManifest.xml]
```

### Steps to Reproduce
1. Open *Android Studio 3.6.1*, create a whole new project, `android.targetSdkVersion` within 27/28/29;
2. Build APK immediately without any modification.
3. Using apktool to decompile the apk and rebuild it.

### Frameworks
not related

### APK
[app-debug.apk](https://send.firefox.com/download/71e45ae274a27cc8/#T66kJWkDeN-zAQubOa__0A)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? *Yes*
2. If you are trying to install a modified apk, did you resign it? *not related*
3. Are you using the latest apktool version? *Yes*

**Comment by guominfang** [comment]
你是用了新特性navigation，估计apktool 目前还不支持navigation这个目录的合并

**Comment by simonkuang** [comment]
> 你是用了新特性navigation，估计apktool 目前还不支持navigation这个目录的合并

Thank you for reminding me of the point. Yes, it's navigation. Using legacy libraries while creating projects, and apktool@2.4.1 works.

**Comment by Pa55w0rd** [comment]
> > 你是用了新特性navigation，估计apktool 目前还不支持navigation这个目录的合并
> 
> Thank you for reminding me of the point. Yes, it's navigation. Using legacy libraries while creating projects, and apktool@2.4.1 works.

我勾选了legacy Libraries，还是存在这个问题

**Comment by simonkuang** [comment]
> > > 你是用了新特性navigation，估计apktool 目前还不支持navigation这个目录的合并
> > 
> > 
> > Thank you for reminding me of the point. Yes, it's navigation. Using legacy libraries while creating projects, and apktool@2.4.1 works.
> 
> 我勾选了legacy Libraries，还是存在这个问题

Try to change `minSdkVersion` in build.gradle file to smaller number. e.g. 14. It works for me.

```
android {
  defaultConfig {
    minSdkVersion 14
  }
}
```
