### ISSUE TITLE
resource issue

### ISSUE THREAD

**Issue by reverser69** [iBotPeaches/Apktool#2314]
i cant use pull request?!?!
apk tool returns error why im trying to build but i just want to make the app debuggable
is there a way to decode then encode the manifest xml file only?!

**Comment by iBotPeaches** [comment]
> i cant use pull request?!?!
You need to submit a change to Apktool for that.

> is there a way to decode then encode the manifest xml file only?!
No, the manifest sometimes references resources from the `resources.arsc` file so that is not possible.
