### ISSUE TITLE
Error when decompiling: Error occurred while disassembling class Landroid.support.multiex.MultiDex$V14; - skipping class

### ISSUE THREAD

**Issue by yodo226** [iBotPeaches/Apktool#2316]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Home
3. **APK From? (Playstore, ROM, Other)** - APKPure: https://apkpure.com/evil-hunter-tycoon/com.superplanet.evilhunter

### Stacktrace/Logcat
https://pastebin.com/G4EG41qC
```
### Steps to Reproduce
1. `apktool d (apk path)`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
I don't think there is an issue here. That is a warning that baksmali is dropping/ignoring that class and it probably makes sense. Normally packers insert bad/busted dead classes into an application in an attempt to crash disassemblers. 

This is dead code so ignoring it is fine.

Reference: https://github.com/JesusFreke/smali/issues/562 &  https://github.com/JesusFreke/smali/issues/580
