### ISSUE TITLE
 Unable to access jarfile c:\Windows\apk\apktool_0.jar

### ISSUE THREAD

**Issue by todayisholiday1** [iBotPeaches/Apktool#2318]
When i try to run apktool its show me this error 
Error: Unable to access jarfile c:\Windows\apk\apktool_0.jar

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to either link/upload the affected apk. Additionally try and provide any logcat and/or stacktrace possible.

**Comment by GuillermoMartos** [comment]
@todayisholiday1 strange as sounds, If that mesagge comes from your apktool.jar file placed in C:/Windows, you can rename that file to apktool_0.jar. Once you did that, re run command apktool and you'll receive Error: Unable to access jarfile c:\Windows\apk\apktool_jar.jar . So, rename once again the same file as the error printed in console (apktool_jar.jar). Rerun apktool and it worked to me ://

**Comment by TinaF333** [comment]
> 

It helped. You are amazing!

**Comment by Adnaan-hacker** [comment]
> @todayisholiday1 strange as sounds, If that mesagge comes from your apktool.jar file placed in C:/Windows, you can rename that file to apktool_0.jar. Once you did that, re run command apktool and you'll receive Error: Unable to access jarfile c:\Windows\apk\apktool_jar.jar . So, rename once again the same file as the error printed in console (apktool_jar.jar). Rerun apktool and it worked to 
thank you very much broh is helpful for me
