### ISSUE TITLE
apktool

### ISSUE THREAD

**Issue by rertere** [iBotPeaches/Apktool#2320]
hey I'm using the newest version 2.34
and I'm using windows 10
and I got the apk from apk pure 

Decompiling APK file...

/c "java -Xmx1024m -jar "C:\Users\my pc\Desktop\modding games\apk easy tool\Apktool\apktool_2.3.4.jar" d -f -o "C:\Users\Andys stationär\Desktop\modding games\apk easy tool\1-Decompiled APKs\Critical Strike CS Counter Terrorist Online FPS_v9.23_apkpure.com" "C:\Users\Andys stationär\Downloads\Critical Strike CS Counter Terrorist Online FPS_v9.23_apkpure.com.apk""

this is the log

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to either link/upload the affected apk. Additionally try and provide any logcat and/or stacktrace possible.
