### ISSUE TITLE
when using -d and --use-aapt2 flags, debuggable="true" is not added to the manifest 

### ISSUE THREAD

**Issue by Comnir** [iBotPeaches/Apktool#2328]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - any APK. e.g., a new application in Android Studio, built with `./gradlew assembleDebug`

### Steps to Reproduce
1. `apktool d app.apk`
2. `apktool b --use-aapt2 -d app -o rebuilt.apk`
3. Analyze the APK in Android Studio (drag & drop) to view to AndroidManifest.xml of rebuilt.apk

### APK
[app.apk.zip](https://github.com/iBotPeaches/Apktool/files/4475484/app.apk.zip)

### More information
1. When using "-d" without "--use-aapt2", `debuggable="true"` is added as expected.
2. [aapt2 documentation](https://developer.android.com/studio/command-line/aapt2) doesn't mention a "debug mode", unlike [aapt](http://manpages.ubuntu.com/manpages/bionic/man1/aapt.1.html). 
3. In [an older issue](https://github.com/iBotPeaches/Apktool/issues/1621#issuecomment-332821090), it's mentioned APKTool removes the `debuggable` attribute and aapt should add it. Maybe when using aapt2, APKTool should add/verify it exists, instead of removing it?

**Comment by iBotPeaches** [comment]
Confirmed. Should be easy enough to just add/change the tag if it exists for aapt2, since aapt2 has no method to automatically do this.

**Comment by Comnir** [comment]
I made a [Pull request](https://github.com/iBotPeaches/Apktool/pull/2355/) for this issue. I'm not sure how to link them...

**Comment by Surendrajat** [comment]
@Comnir you write `Closes #2328` in PR description, that's all.
