### ISSUE TITLE
Can't Recompile any android app. Exit code 132

### ISSUE THREAD

**Issue by NarenderModi** [iBotPeaches/Apktool#2330]
### Information
1. **Apktool Version (`latest one 2.4.1)
2. **Operating System (Linux)
3. **APK From? (Any app from anywhere "Android app")

### Stacktrace/Logcat

kali@localhost:/$ apktool b virus1
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_15924582530676693049.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL11389677012534912681.tmp, -e, /tmp/APKTOOL14404947888819616738.tmp, -0, arsc, -I, /home/kali/.local/share/apktool/framework/1.apk, -S, /virus1/res, -M, /virus1/AndroidManifest.xml]nclude stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by NarenderModi** [comment]
![Screenshot_20200414-210738](https://user-images.githubusercontent.com/63146275/79677605-def66a00-8210-11ea-9e91-5461ca4217f0.png)
![Screenshot_20200418-100142](https://user-images.githubusercontent.com/63146275/79677608-e3bb1e00-8210-11ea-81bf-39ded82cdeeb.png)

**Comment by Yuliianto** [comment]
I got the same issue.
Please how can i fix this problem 

![Screenshot_2020-04-19-10-20-22-123_com termux](https://user-images.githubusercontent.com/36889461/79678597-72d33080-8227-11ea-84cd-7daccbd3d046.jpg)

**Comment by NarenderModi** [comment]
> I got the same issue.
> Please how can i fix this problem
> 
> ![Screenshot_2020-04-19-10-20-22-123_com termux](https://user-images.githubusercontent.com/36889461/79678597-72d33080-8227-11ea-84cd-7daccbd3d046.jpg)

**Comment by iBotPeaches** [comment]
Code 132 is either 32 bit incompatibilities or some missing image binary.

This is not a bug.

See - https://stackoverflow.com/questions/27715506/error-executing-aapt-return-code-132-problems

**Comment by NarenderModi** [comment]
I briefly describe you
I am using kali nethunter android 
I also try to shift from kali nethunter to ubuntu and parrot OS. But getting same error in all platform

now this is becoming common problem for android users as i discussed  with my friends..
They are getting same problem

Can you provide easy method or any video . So that we can solve this problem easily

**Comment by iBotPeaches** [comment]
> They are getting same problem

I doubt it. You aren't using plain apktool in your Ubuntu screenshot and the Android (mobile) has no official supported version for Apktool.

**Comment by NarenderModi** [comment]
> > They are getting same problem
> 
> I doubt it. You aren't using plain apktool in your Ubuntu screenshot and the Android (mobile) has no official supported version for Apktool.


No ,  Android device supports apktool  i have see many youtube video using apktool successfully

Please do check in your own android device (not emulator)

**Comment by whoiam1337** [comment]
@iBotPeaches 
I experienced the same thing, I can't recompile with exit code 132 on Kali Nethunter Android, but apktool run perfectly when recompile on Alpine Linux by using this aapt2.
this aapt2 compile with musl-libc, its possible to run this aapt2 on kali ?
sorry for my bad english

[This appt2](http://www.mediafire.com/file/emfkb7984fwc5xk/aapt2/file) 

$ file /usr/bin/aapt2
/usr/bin/aapt2: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, with debug_info, not stripped

>

**Comment by whoiam1337** [comment]
> Code 132 is either 32 bit incompatibilities or some missing image binary.
> 
> This is not a bug.
> 
> See - https://stackoverflow.com/questions/27715506/error-executing-aapt-return-code-132-problems

@iBotPeaches 
I experienced the same thing, I can't recompile with exit code 132 on Kali Nethunter Android, but apktool run perfectly when recompile on Alpine Linux by using this aapt2.
this aapt2 compile with musl-libc, its possible to run this aapt2 on kali ?
sorry for my bad english

[This aapt2](http://www.mediafire.com/file/emfkb7984fwc5xk/aapt2/file) 

$ file /usr/bin/aapt2
/usr/bin/aapt2: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, with debug_info, not stripped

**Comment by NarenderModi** [comment]
@whoiam1337 
I tried this aapt2 but got the same error

**Comment by canxx99** [comment]
I have been dealing with this problem for a long time and I found a solution to this problem apktool. I have arranged to run on Android (nethunter vs.), you can use this jar file and forward it to those who have experienced this problem (fix exit code = 132)

[apktool.jar](https://bahrulmedid.tk/wp-content/uploads/2020/07/apktool.jar)

@phhusson 
@NarenderModi 
@whoiam1337 
@Yuliianto 
@iBotPeaches

**Comment by iBotPeaches** [comment]
Hey @canxx99 , I'm going to remove your post. I shy away from sharing binaries due to security reasons. You are welcome to share source changes or even upstream them, but we won't share binaries due to the possible security implications.

**Comment by canxx99** [comment]
As a solution to this problem, I shared a jar file, but it was removed for security reasons.
I shared the file on my own page.
![Screenshot_20200722_024609](https://user-images.githubusercontent.com/52892904/88120141-ec820e00-cbca-11ea-9706-ee439cd4b473.jpg)
@NarenderModi 
@whoiam1337 
@Yuliianto

**Comment by Yuliianto** [comment]
So hos to solve this issue?

**Comment by giacomoferretti** [comment]
@Yuliianto you'll need to have ARM binaries for aapt and aapt2.

It seems that @canxx99 already compiled them and built the apktool.jar so you can download his version, at your own risk. That's the only difference between his version and the official version (we are talking about 2.4.0).

**Comment by Yuliianto** [comment]
@giacomoferretti it's still not got same problem
![IMG_20200809_090450](https://user-images.githubusercontent.com/36889461/89723378-93fe9d80-da1f-11ea-99f6-7e4bc5788555.jpg)

**Comment by canxx99** [comment]
@Yuliianto As stated verbally, this is not an error. Aapt does not work for arm64 architecture. You have to use the jar in my tank. I recompiled it and made it aapt arm64 compatible.
https://github.com/canxx99/apktool

**Comment by mertbeet** [comment]
i have the same problem.  I am using apktool 2.5.0, what should I do? @iBotPeaches 
![Screenshot_20201228-211124](https://user-images.githubusercontent.com/76702155/103234690-57412d80-4951-11eb-839e-ba1e916b8913.png)

**Comment by iBotPeaches** [comment]
@mertbeet - We don't officially support running Apktool on a device. Sorry.

**Comment by canxx99** [comment]
@mertbeet The jar I compiled for Android devices works, you can download it from my repository, but it only works with apktool 2.4.0. (but it is not an Official version, it is your responsibility to use the jar file)

**Comment by mertbeet** [comment]
> @mertbeet The jar I compiled for Android devices works, you can download it from my repository, but it only works with apktool 2.4.0. (but it is not an Official version, it is your responsibility to use the jar file)

Thank you.  I guess I need to use 2.5.0 for A11 apks, for best experience.  Can you use your solution with the apktool developer?

**Comment by canxx99** [comment]
@mertbeet I tried it for you bro and it worked but I don't know if it works for all apk files, you can try. I tried it in an apk file for this and it worked. How can I send this to you
![Screenshot_20201228_222453](https://user-images.githubusercontent.com/52892904/103238370-8f4d6e00-495b-11eb-9edf-76ccbb3642d7.jpg)

**Comment by harsh858** [comment]
Hi canxx99

Can you please help to upload apktool.jar for arm64 compatible for latest version ( apktool_2.5.0.jar) on your repository.

Also if possible can you please share method how can I create apktool.jar with aapt amr64 compatible by myself.

Thanks,
Harsh

**Comment by madhu9418** [comment]
@canxx99  please help me bro, I followed a article to install apktool in my kali linux android, and i'm getting the same iasue. I don't have a proper idea about .jar file, what's it? How can I fix the issue please tell me

**Comment by Sssoms2004** [comment]
> Code 132 is either 32 bit incompatibilities or some missing image binary.
> 
> This is not a bug.
> 
> See - https://stackoverflow.com/questions/27715506/error-executing-aapt-return-code-132-problems

I have the same issue , and I can't deal with it almost for 2 months , I'm a real beginner in using linux , may you help me with this issue so I can go back on the track.

![Screenshot_20220225-145029_Termux](https://user-images.githubusercontent.com/99367836/155723697-79515e31-96b5-4191-b72a-e90477fcb0a2.jpg)

I tried really hard to bind a payload with all sorts of apk but still got the error while building resources 
Error: Unable to rebuild apk with apktool

**Comment by msckd** [comment]
> As a solution to this problem, I shared a jar file, but it was removed for security reasons.
> I shared the file on my own page.
> ![Screenshot_20200722_024609](https://user-images.githubusercontent.com/52892904/88120141-ec820e00-cbca-11ea-9706-ee439cd4b473.jpg)
> @NarenderModi 
> @whoiam1337 
> @Yuliianto 

Hi cannx, 
Can you please make the new version apktool 2.8.1 for arm 64. If you don't mind can you share the method for making the jar compatible with arm64 devices

**Comment by Majid-mir** [comment]
apktool b fb --use-aapt2 -o facebook
I: Using Apktool 2.9.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_74382191716788448782765084059949260080.tmp, compile, --dir, /home/kali/Downloads/fb/res, --legacy, -o, /home/kali/Downloads/fb/build/resources.zip]
 
I am using kali linux on android and i cant find any solution plz help me to fix this issue
