### ISSUE TITLE
apktool adds android:compileSdkVersion="23" android:compileSdkVersionCodename="6.0-2438415" 

### ISSUE THREAD

**Issue by mollaxx1** [iBotPeaches/Apktool#2331]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1.  the latest
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. apktool d xxx.apk
2. apktool b xxx -o yyy.apk

for every apk i tried , apktool always adds ( android:compileSdkVersion="23" android:compileSdkVersionCodename="6.0-2438415" ) to the <manifest> tag in AndroidManifest.xml .

even when i change it or delete it , the built apk always comes with the same ( android:compileSdkVersion="23" android:compileSdkVersionCodename="6.0-2438415" ) 

after some research i found these exact api numbers in 1.apk located in apktool/framework/1.apk

i tried some older versions , but always the same problem

is it normal ? or should i add some args to the commands

thanks

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by Ticklefish** [comment]
I don't think this is a problem. It's been mentioned before (https://github.com/iBotPeaches/Apktool/issues/1909) but, if I understand correctly, it's nothing you need to worry about. As long as your recompiled file installs and runs, then it's all good.

**Comment by iBotPeaches** [comment]
This is intentional. If the value cannot be pulled from existing manifest files (to persist with no change), we fallback to the framework files (1.apk) as these are required build time properties now.

Closing.

**Comment by karpiyon** [comment]
This is strange as i specifically specify `android:compileSdkVersion="20"` but after apktool b... it turn is to "23".
I suspect that version 23 may block app permissions.
