### ISSUE TITLE
probably a permission problem, I need to debug this

### ISSUE THREAD

**Issue by adrianTNT** [iBotPeaches/Apktool#2335]
I am using `2.4.1` on Centos 7, I need to unpack the file to detect just SDK version and file version.

I am trying with this command:
```
java -jar '/www/example.com/apktool/apktool_2.4.1.jar' decode '/www/example.com/test.apk' -f -o '/www/example.com/temp'
```
If I run it in console directly it unpacks correctly.
But I need to run it from web site (with php `exec`) when user makes an upload, and in browser it always fails at this point:

```
I: Using Apktool 2.4.1 on lip.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...

// !!! FROM WEB SITE IT STOPS HERE !!! 

// and only files are:
    ./res
    ./AndroidManifest.xml
```

I tried forcing the directories to be writable, the problem seems to be somewhere else, maybe at that point after decoding the XML files, the apktool tries to use other scripts and programs that cannot run from web server environment ? 

Anything else I can try to debug this ?

**Comment by adrianTNT** [comment]
I was able to fix this and properly unpack all files by specifying framework path when running cmd (with php `exec`) from web server: 

`--frame-path = /www/example.com/temp`

I understand that initially it failed from web server (apache) because the default framework path `$HOME/.local/share/apktool/framework`  is owned by root and apache cannot read/write there. 
Even if specified path is an empty folder, the framework file `1.apk` is created there.
Maybe someone can clarify if this is OK.

**Comment by iBotPeaches** [comment]
>  understand that initially it failed from web server (apache) because the default framework path $HOME/.local/share/apktool/framework is owned by root and apache cannot read/write there.

Then don't run apktool as root :)
