### ISSUE TITLE
Is there a way to count the referenced method?

### ISSUE THREAD

**Issue by mkfcoffee** [iBotPeaches/Apktool#2336]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.1
2. **Operating System (Mac, Linux, Windows)** -Mac
3. **APK From? (Playstore, ROM, Other)** -Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Hello, I want to check if the number of dex methods exceeds 64k before rebuilding apk.
I can use ‘grep -o -r" .end method "smali | wc -l’ to get the number of defined methods, but I do n’t know how to get the referenced methods, please give me an idea
Thanks!

**Comment by iBotPeaches** [comment]
You'll find Stack is quite stacked for this type of question - https://stackoverflow.com/a/17098651/455008

Not really bug report material :)

**Comment by mkfcoffee** [comment]
Thanks.I have studied this stack before.
Because I insert other smali files in the smali or smali_classesN folder,  the number of methods will exceed 64k(if  
```
exec 'smali -o classes.dex'  and 'dexdump -f classes.dex' ->
E/libdex  ( 6227): ERROR: Bad magic number (0x00 00 00 00)
ERROR: Failed structural verification of 'classes.dex'  
```),
but I want to build the apk once, so I want to explore the way of other count referenced methods from the smali format file.
