### ISSUE TITLE
Parsing error in apktool built apk

### ISSUE THREAD

**Issue by Karansa-code** [iBotPeaches/Apktool#2337]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.1
2. **Operating System (Mac, Linux, Windows)** -Kali Linux
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. I decompile apk using ### ### ### apktool
apktool d facebookre.apk
then I build it using 
apktool b facebookre
I got the following error of parsing failed:-
The error code-`

failed to install facebookre.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1227099210.tmp/base.apk: Attempt to get length of null array]

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?Yes
2. If you are trying to install a modified apk, did you resign it?Yes
3. Are you using the latest apktool version?Yes

**Comment by MrIkso** [comment]
Sign Apk

**Comment by evildog1** [comment]
Yup, APK needs to be signed

**Comment by giacomoferretti** [comment]
You need to sign the APK, as told by others. I think this issue can be closed.

**Comment by unme112222** [comment]
well, above comment solve my issue and i found more details apk files on this website: https://apkever.com

**Comment by iBotPeaches** [comment]
Closing as mentioned 3x above. Signatures were stripped.
