### ISSUE TITLE
Could not smali file: o/ɪε.smali

### ISSUE THREAD

**Issue by yazinsai** [iBotPeaches/Apktool#2340]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
~/Desktop/target> apktool -r d target.apk 
I: Using Apktool 2.4.1 on target.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
~/Desktop/target> apktool b target/ target-clone.apk
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
target/smali_classes2/o/ɪε.smali[450,0] missing EOF at 'Lo/ɪε;'
Could not smali file: o/ɪε.smali
```

### Steps to Reproduce
1. `apktool -r d target.apk`
2. `apktool b target/ target-clone.apk`

### APK
Link [here](https://send.firefox.com/download/f35368b4fb515144/#xxD8Fe2QWeHm7oThnNeI7g) (Expires after 50 downloads or 7d 0h 0m)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by MrIkso** [comment]
Your smali file is broken, correct it, line number position is indicated

**Comment by yazinsai** [comment]
"My smali file" was extracted using apktool

**Comment by Surendrajat** [comment]
It seems like this one: JesusFreke/smali#353. Try using `[bak]smali.jar` directly on the apk.

**Comment by iBotPeaches** [comment]
I'm sorry I was late as the file is expired. This comes up every now and again and it is never reproducible, usually hinting at some bug during disassembly or just bad apk.

Sorry about that, I don't have anything more helpful than the link to smali above.
