### ISSUE TITLE
Split apk decompilation error

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2341]
### Information
1. **Apktool Version** - 2.4.1
2. **Operating System** - Windows
3. **APK From?** - for example, combined from parts https://apk.support/download-app-ru/com.garmin.android.apps.connectmobile/1588057200_vs-4.30

https://ru.files.fm/u/f5ckhbew

after decompilation, the apk part is lost, you can see the rebuilding apk

![Screenshot_1](https://user-images.githubusercontent.com/36408873/80753673-2fc56700-8b1d-11ea-93c3-66f20f7a1fb8.png)
_after recompilation:_

![Screenshot_2](https://user-images.githubusercontent.com/36408873/80753428-c80f1c00-8b1c-11ea-9f7b-25e79beab62e.png)
used BatchApktool + plugin https://4pda.ru/forum/dl/post/19526276/AntiSplit-G2_2020-04-25.zip

**Comment by MrIkso** [comment]
Apktool don't support multiple package in resources.arsc

**Comment by iBotPeaches** [comment]
Split apks and resource packages with more than 1 default package are not supported. Apktool is currently hardcoded to pull only package.

You are looking for this feature request - https://github.com/iBotPeaches/Apktool/issues/2218

**Comment by Ratul-Learner** [comment]
> ### Information
> 1. **Apktool Version** - 2.4.1
> 2. **Operating System** - Windows
> 3. **APK From?** - for example, combined from parts https://apk.support/download-app-ru/com.garmin.android.apps.connectmobile/1588057200_vs-4.30
> 
> https://ru.files.fm/u/f5ckhbew
> 
> after decompilation, the apk part is lost, you can see the rebuilding apk
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/36408873/80753673-2fc56700-8b1d-11ea-93c3-66f20f7a1fb8.png)
> _after recompilation:_
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/36408873/80753428-c80f1c00-8b1c-11ea-9f7b-25e79beab62e.png)
> used BatchApktool + plugin https://4pda.ru/forum/dl/post/19526276/AntiSplit-G2_2020-04-25.zip

can you please share this BatchApktool + plugin. The link is not valid anymore.

**Comment by pashamcr** [comment]
@Ratul-Learner 
Link works for users registered on 4pda, I did not take this into account when I provided the link. It is clear that no one is going to register there, since the forum is Russian-speaking and there will be problems with registration and login, based on the impossibility of reading the captcha. I can provide a link to a newer version, but that won't change anything: issue closed.
