### ISSUE TITLE
sign apk failed

### ISSUE THREAD

**Issue by thetrubonbon15** [iBotPeaches/Apktool#2342]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat
4/30/2020 2:21:08 PM
Signing APK file...

/c "java -Xmx1024m -jar "C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\Resources\ApkSigner.jar" sign  --key "C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\Resources\apkeasytool.pk8" --cert "C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\Resources\apkeasytool.pem" --out "C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\2-Recompiled APKs\2020-04-30T20-42-16.011Z_3.apk" "C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\2-Recompiled APKs\2020-04-30T20-42-16.011Z_3.apk""

Exception in thread "main" java.io.FileNotFoundException: C:\Users\Nathan\Downloads\APK Easy Tool v1.56 Portable\2-Recompiled APKs\2020-04-30T20-42-16.011Z_3.apk (The system cannot find the file specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:169)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:340)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by MrIkso** [comment]
File  not found, write about error author Apk Easy Tool. Apktool doesn't sign apk

**Comment by iBotPeaches** [comment]
As mentioned above. Apktool has no tool or knowledge about signing an apk. Looks like your search/bug/issue is meant for something else.

Sorry about that!
