### ISSUE TITLE
Can't compile WhatsApp put decompile is working fine

### ISSUE THREAD

**Issue by samchuc** [iBotPeaches/Apktool#2345]
1. Apktool 2.4.0 / 2.4.1
2. Windows 8.1 / x64
3. Apk from Whatsapp or FmWhatsapp the same issue exactly
4. I upgrade Java to (Java 8 Update 251 (64-bit)
and .Net Framework the latest version
5. Tried to compile manualy without "Apk easy tool" I mean via CMD commands but the same issue happened

I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741701): [C:\Users\win\AppData\Local\Temp\brut_util_Jar_4836831593701926583.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 453516, --version-name, 2.20.141, --no-version-vectors, -F, C:\Users\win\AppData\Local\Temp\APKTOOL661295634345412125.tmp, -e, C:\Users\win\AppData\Local\Temp\APKTOOL6969226482992284800.tmp, -0, arsc, -I, C:\Users\win\AppData\Local\apktool\framework\1.apk, -S, C:\Users\win\Downloads\Compressed\APK Easy Tool v1.57 beta-1 portable\1-Decompiled APKs\WhatsApp\res, -M, C:\Users\win\Downloads\Compressed\APK Easy Tool v1.57 beta-1 portable\1-Decompiled APKs\WhatsApp\AndroidManifest.xml]

**And this log via manual compile**

C:\Users\win\Desktop\Apktool>apktool if WhatsApp.apk
I: Framework installed to: C:\Users\win\AppData\Local\apktool\framework\127.apk

C:\Users\win\Desktop\Apktool>apktool d WhatsApp.apk
I: Using Apktool 2.4.1 on WhatsApp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\win\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\win\Desktop\Apktool>apktool b WhatsApp
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741701)
-min-sdk-version, 15, --target-sdk-version, 29, --version-code, 453516, --version-name, 2.20.141, --
\AppData\Local\Temp\APKTOOL3562687187904428009.tmp, -0, arsc, -I, C:\Users\win\AppData\Local\apktool
pp\AndroidManifest.xml]

C:\Users\win\Desktop\Apktool>****

**Comment by Baikan4ik** [comment]
Similar with WeChat 7.0.14. Recompiling without changes throw similar exception.

2.4.1, MacOS 10.15, frameworks 10.0, 9.0 tried (1, 127)

**Comment by Baikan4ik** [comment]
Now test recompile WhatsApp and got success with it and install.
1. apktool 2.4.1
2. macOS 10.15.4
3. WhatsApp Messenger 2.20.148 beta from APKMirror
4. jdk 14

**Comment by iBotPeaches** [comment]
The original issue here looks to be related to Windows and the environment. I had never seen that error before, but one quick search points to

```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741701)
```

[1] https://answers.microsoft.com/en-us/windows/forum/all/error-1073741701/e5822dac-01c7-42f4-bfa5-b8d6385be667
[2] https://stackoverflow.com/q/11648621/455008

Closing as looks related to environment, not tool. It looks related to x84 vs x64
