### ISSUE TITLE
Can't recompile WeChat

### ISSUE THREAD

**Issue by Baikan4ik** [iBotPeaches/Apktool#2347]
Trying to recompile without any changes and got error

1. apktool 2.4.1
2. macOS 10.15.4
3. WeChat 7.0.14 from APKMirror
4. jdk 14
5. framework-res, system-ui framework from Android 10 (Samsung Note10)

MacBook-Pro:Apktool user$ apktool b WeChat_7.0.14
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0n.xml:15: error: No resource identifier found for attribute 'iconColor' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0o.xml:9: error: No resource identifier found for attribute 'off_color' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0o.xml:9: error: No resource identifier found for attribute 'off_text' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0o.xml:9: error: No resource identifier found for attribute 'on_color' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0o.xml:9: error: No resource identifier found for attribute 'on_text' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/layout/a0o.xml:9: error: No resource identifier found for attribute 'slide_color' in package 'com.tencent.mm'

.................
many many similar warnings about "no resource identificator found"
.................

W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/color/ba.xml:4: error: No resource identifier found for attribute 'alpha' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/color/bb.xml:4: error: No resource identifier found for attribute 'alpha' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/color/bb.xml:5: error: No resource identifier found for attribute 'alpha' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/color/bb.xml:6: error: No resource identifier found for attribute 'alpha' in package 'com.tencent.mm'
W: 
W: /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res/color/kz.xml:4: error: No resource identifier found for attribute 'alpha' in package 'com.tencent.mm'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/87/vvv7ksp92hd8vb59yfh8_18m0000gn/T/brut_util_Jar_7819996029830032376.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 1660, --version-name, 7.0.14, --no-version-vectors, -F, /var/folders/87/vvv7ksp92hd8vb59yfh8_18m0000gn/T/APKTOOL18076548198383055332.tmp, -e, /var/folders/87/vvv7ksp92hd8vb59yfh8_18m0000gn/T/APKTOOL17192895143944556835.tmp, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/res, -M, /Users/user/Documents/Work/Android/Apktool/WeChat_7.0.14/AndroidManifest.xml]

[WeChat 7.0.14 Apkmirror](https://www.apkmirror.com/apk/wechat-tencent/wechat/wechat-7-0-14-release/wechat-7-0-14-3-android-apk-download/)

**Comment by MrIkso** [comment]
This apk used not stand attributes from xml

**Comment by iBotPeaches** [comment]
Looks related to obfuscation and AndResGuard or some iteration of it.

We have #2094, #1828 and #1423 which are related. So closing this one as a duplicate.
