### ISSUE TITLE
The app fails to start, NoClassDefFoundError exception, no changes made (only decoded and re-built)

### ISSUE THREAD

**Issue by MaciejGorczyca** [iBotPeaches/Apktool#2348]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.2-83a459-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

[logcat_goodie.txt](https://github.com/iBotPeaches/Apktool/files/4598575/logcat_goodie.txt)

### Steps to Reproduce
1. apktool d -r "Goodie.apk" -o goodie
(running with -rs to copy both sources and resources results in the same error)
2. apktool b goodie
3. java -jar apksigner.jar -a "goodie/dist/Goodie.apk"
4. adb install -r "goodie/dist/Goodie-aligned-debugSigned.apk"

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://drive.google.com/file/d/1k1ucwo47HemDEYFwp92GgjP7Mhc1WSc5/view

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

The exception thrown is java.lang.NoClassDefFoundError. There are tons of weird files containing whitespaces and placed under "unknown" as well as output .apk being 44608 KB unsigned and 44867 KB signed vs 42893 KB original.

I tried to decode and rebuild another app and successfully did that - the rebuilt app was working fine, so the PC environment is not the issue. Only the apk mentioned above doesn't seem to work properly.

**Comment by iBotPeaches** [comment]
I would recommend doing a diff report between original application (zip list) and then a decoded and rebuilt application. That will narrow the search down to something that may be missing.

ClassDefFound errors though point more to the source than some random resource file (unless that file is used).

I don't have much time right now due to pandemic, so if you can do that investigation. That will help me. Thanks!

**Comment by iBotPeaches** [comment]
Closing as 1 month passed with no comment. Feel free to add this research when able and I can re-visit. Thanks!
