### ISSUE TITLE
Edit manifest without decoding resources

### ISSUE THREAD

**Issue by samdelong** [iBotPeaches/Apktool#2358]
Not a bug, but a feature request
Since apktool seems to have issues with some APKs rebuilding the resource files (#1880)
I think a valuable feature would be able to decode and build just the AndroidManifest files.
For example, if one wanted to add an activity or permissions to an APK, they could edit the manifest to include an additional activity tag, which I don't believe would require a full resource decoding

**Comment by aress31** [comment]
If possible I would be happy to see such features implemented too.

**Comment by iBotPeaches** [comment]
Sorry this is not possible in all situations. Most manifests have resources referenced from outside, so the only way to disassembly properly is to follow those references which thus require a disassembly of the resources.

Closing as not possible.

**Comment by samdelong** [comment]
Would it be possible to decode the manifest leaving reference ID's, and then reencode? Similar to `androguard` works. It seems to do a good job of decoding manifests

**Comment by iBotPeaches** [comment]
> Would it be possible to decode the manifest leaving reference ID's, and then reencode? Similar to `androguard` works. It seems to do a good job of decoding manifests

No sorry, it is not something Apktool will pursue. You are welcome to fork and add this logic.

**Comment by samdelong** [comment]
Could you point me to where the manifest/resource decoding logic is currently in the repo? Thanks!
