### ISSUE TITLE
Getting an error in code 132

### ISSUE THREAD

**Issue by kevzy** [iBotPeaches/Apktool#2359]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Yes I'm using the latest version 
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_8640735696783938834.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 1052, --version-name, 1.052-release, --no-version-vectors, -F, /tmp/APKTOOL15311988096029413287.tmp, -e, /tmp/APKTOOL18067859562610415105.tmp, -0, arsc, -I, /home/kingkevzy/.local/share/apktool/framework/1.apk, -S, /home/kingkevzy/j/res, -M, /home/kingkevzy/j/AndroidManifest.xml]

**Comment by Ticklefish** [comment]
Exit code 132 means there's an issue with aapt (which is inside apktool) crunching some of the PNG files in your APK on a 32 bit system. [https://stackoverflow.com/questions/27715506/error-executing-aapt-return-code-132-problems](url)

You can fix this by opening every single PNG file in an image editor and saving them (which could take a while) or try recompiling with the --no-crunch option.

**Comment by kevzy** [comment]
> Exit code 132 means there's an issue with aapt (which is inside apktool) crunching some of the PNG files in your APK on a 32 bit system. [https://stackoverflow.com/questions/27715506/error-executing-aapt-return-code-132-problems](url)
> 
> You can fix this by opening every single PNG file in an image editor and saving them (which could take a while) or try recompiling with the --no-crunch option.

I'm using Kali Linux on userland...it was working well... But after some days it stopped and begun showing the code 132 error

**Comment by iBotPeaches** [comment]
I mean as you mentioned, it was working, then it wasn't. So this really points at environment. If you stumble upon anything that leads you to believe Apktool is at fault, feel free to put some comments so we can triage this further. 

I'm not replicating on my kali or ubuntu box.
