### ISSUE TITLE
#1717

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#2361]
Hi iBotPeaches,
Maybe you could explain your answer to this in a bit more detail:
Help / Feature Request : Any way to add resources to an existing app? #1717

How to do this? Links? etc?
 explicitly generate a resource ID, abiding by the rules of that and use public.xml to maintain that ID for the resource(s) in question.

**Comment by Ticklefish** [comment]
I'm not quite sure what it is that you're trying to find out. The issue you linked to talked about adding new resources to an existing APK and referencing those in the smali.

If you add a new resources to a decompiled APK then, when you recompile, public.xml will be updated with hexadecimal references to those resources. Those references can then be used in the smali.
There's a good example of this sort of thing here: https://forum.xda-developers.com/showthread.php?t=1484578&page=4 (copy and paste the link - I can't get links to work properly in github for some reason..)

XDA is a great place for learning about modding Android. If you have any further questions that aren't about using apktool itself, you should look there.

**Comment by iBotPeaches** [comment]
With the bug tracker being as large and behind times, unforunately can't really hold a support dialog here. As mentioned above, XDA has plenty of threads and one quick Google search led me to - https://stackoverflow.com/q/52742731/455008

Which basically explains the procedure in detail

1. Find last resource id in type you are interested in
2. Increase by 1 (remember it is hex, so go back to decimal +1 then back to hex if you can't work in base 16)
3. Add that resource to the `R${type}.smali` file
4. Use that resource id in the source file for what you are trying to do.
