### ISSUE TITLE
Error: No resource found that matches the given name - even when nothing changed

### ISSUE THREAD

**Issue by gjf** [iBotPeaches/Apktool#2362]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.2-ecbcfb-SNAPSHOT and 2.4.1 (latest)
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

### Steps to Reproduce
1. `apktool  d "dialer.apk"`
1. `apktool  b "dialer"`

### APK
https://www49.zippyshare.com/v/6NpJSIhv/file.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

The file cannot be recompiled even without changing anything.

```
$ apktool b "dialer"
I: Using Apktool 2.4.2-ecbcfb-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: E:\Android\APKTool\dialer\res\values\styles.xml:3702: error: Error: No resource found that matches the given name: attr '@android:bool/config_wifi_batched_scan_supported'.
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SR\AppData\Local\Temp\brut_util_Jar_18499504029323786395140859842951620675.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 29, --version-code, 108, --version-name, 2.0.8, --no-version-vectors, -F, C:\Users\SR\AppData\Local\Temp\APKTOOL7664654455738667981.tmp, -e, C:\Users\SR\AppData\Local\Temp\APKTOOL7184235670795751802.tmp, -0, arsc, -I, C:\Users\SR\AppData\Local\apktool\framework\1.apk, -S, E:\Android\APKTool\dialer\res, -M, E:\Android\APKTool\dialer\AndroidManifest.xml]``

**Comment by Ticklefish** [comment]
It looks like you haven't any installed any framework/resource files before decompiling your APK. Try installing framework-res.apk first, then decompile and recompile your file.

**Comment by gjf** [comment]
> It looks like you haven't any installed any framework/resource files before decompiling your APK. Try installing framework-res.apk first, then decompile and recompile your file.

[https://ibotpeaches.github.io/Apktool/documentation/](url)
Apktool comes with an internal framework like mentioned above. This file is copied to $HOME/apktool/framework/1.apk during use.

So what I have to install?

**Comment by Ticklefish** [comment]
Interesting. I did some Googling on 'android:checkMarkGravity' and it does cause problems with modding APK's. This isn't an apktool issue - this is a deliberate move by Google. Have a look here: https://issuetracker.google.com/issues/37047629#comment7

To quote Google: 

> The attribute is not public and hence not available to use by applications. The attribute can change or disappear and that's why applications using it won't compile.

It might be worth deleting that attribute from the XML and trying to recompile. This should work but you might notice a checkbox in a difference place when you run the app. Not an ideal solution but try it and see what happens.

**Comment by iBotPeaches** [comment]
Thanks for the research @Ticklefish - I think that about settles it. Some attributes cannot become public and a by-product of Apktool keeping constant resource ids is making resources public (see `public.xml`)

This is required because there is no 100% way to rewrite resource ids at the source level, even assuming you wrote a 100% solution for dexlib2, imagine apps that do the following:
 * Download auxiliary dex files at runtimes
 * Apps that avoid app store updates by download files at runtime to power
 * Anything that is not automated through dexlib2

There is no real good solution for this at this time. See this: https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#automatic-remapping-of-resourceid
