### ISSUE TITLE
Invalid sdkInfo value in apktool.yml

### ISSUE THREAD

**Issue by qminds** [iBotPeaches/Apktool#2368]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

### APK
https://drive.google.com/file/d/1TpWgjy5O3BU5SEcYokkoYiP3GziVLKpd/view?usp=sharing

### Problem
After decoding the attached APK, the `sdkInfo` property in `apktool.yml` file is set to `null`.
However, both `AndroidManifest.xml` and `aapt dump badging` show proper values.

**Comment by Ticklefish** [comment]
Interesting. That shouldn't stop the APK from working though. According to Google:


> **android:versionCode**
> An internal version number. This number is used only to determine whether one version is more recent than another, with higher numbers indicating more recent versions. This is not the version number shown to users; that number is set by the versionName attribute.
> The value must be set as an integer, such as "100". You can define it however you want, as long as each successive version has a higher number. For example, it could be a build number. Or you could translate a version number in "x.y" format to an integer by encoding the "x" and "y" separately in the lower and upper 16 bits. Or you could simply increase the number by one each time a new version is released.
> **android:versionName**
> The version number shown to users. This attribute can be set as a raw string or as a reference to a string resource. The string has no other purpose than to be displayed to users. The versionCode attribute holds the significant version number used internally.

The app will use whatever detail is in the Manifest so the discrepancy in the YML file shouldn't cause any issues. 

Obviously let us know if that's not the case.

**Comment by qminds** [comment]
Oops, I was thinking about totally different thing while creating this issue.
Sorry, my bad.

The `versionCode` and `versionName` values seem to be fine, **what I really meant is the `sdkInfo` value**.
I edited the original message, check it out.

**Comment by Ticklefish** [comment]
Don't worry, I've been there before. I once spent ages writing a long reply to somebody's post, with screenshots and links and everything, before deleting the whole lot because I read the post and was talking about completely the wrong problem..

This issue matches a one from a few years ago: [https://github.com/iBotPeaches/Apktool/issues/1327](url)

Are you editing the Manifest at all? If so you can set the relevant attributes to whatever you need. If you're not, just rebuild with the --copy-original option to reuse the original Manifest file.

This is a curious issue but shouldn't actually cause any problems.

**Comment by iBotPeaches** [comment]
Thanks, this is because there is a new param `compileSdkVersion` added into `uses-sdk`. The system nulls out all if it encounters bad data.

I'll do some tests and push up a fix.

**Comment by iBotPeaches** [comment]
It looks like with latest aapt/aapt2 I don't see this property used, so unsure what part of compile time it is used for. Must be some support library/gradle checks.

I've made a note to check again when I finish up newest binaries, but this doesn't appear to have a flag at aapt2/aapt1 level. PR linked above.
