### ISSUE TITLE
AAPT rebuilds statically link Windows C runtimes

### ISSUE THREAD

**Issue by codylund** [iBotPeaches/Apktool#2373]
### Information
1. v2.4.1
2. Windows

### Issue
Following [this pull request](https://github.com/iBotPeaches/platform_frameworks_base/pull/9) made against the `iBotPeaches/platform_frameworks_base` fork, it seems the Windows AAPT executables shipped with APKTool statically link Windows C runtime libraries. This was flagged as a security issue by internal tooling at my company. Windows C runtime libraries are OS components and should not be statically linked.

I have not investigated far enough to determine whether static linking applies to transitive dependencies or if one of the statically linked libraries is statically linking a CRT library itself. Perhaps someone with more Windows C++ experience can provide some insight here.

**Comment by iBotPeaches** [comment]
I statically link them because relying on shared libraries has been (pardon my language) a shit show. Bug reports constantly of missing things. Granted these mainly fall on unix, but that has been the reasoning.

**Comment by iBotPeaches** [comment]
Closing as intended to be static.
