### ISSUE TITLE
Manifest not reencoding (corrupt XML binary file?) causing error signing/installing

### ISSUE THREAD

**Issue by mnlsrv** [iBotPeaches/Apktool#2374]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - macOS
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

Decoding with -rs --force-manifest
```
I: Using Apktool 2.4.1 on 67f32da161bc63a8ac5a07c1df819e63.apk
I: Copying raw resources...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/aptmas/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Copying raw classes.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes5.dex file...
I: Copying raw classes6.dex file...
I: Copying raw classes4.dex file...
I: Copying raw classes2.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

Encoding without flags
```
I: Using Apktool 2.4.1
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes.dex file...
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes3.dex file...
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes2.dex file...
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes6.dex file...
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes5.dex file...
I: Copying 67f32da161bc63a8ac5a07c1df819e63 classes4.dex file...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

ApkSigner
```
Exception in thread "main" com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported platform version. Use --min-sdk-version to override
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:372)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:123)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:84)
Caused by: com.android.apksig.apk.MinSdkVersionException: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
	at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:384)
	at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:857)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:260)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:193)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:366)
	... 2 more
Caused by: com.android.apksig.internal.apk.AndroidBinXmlParser$XmlParserException: No XML chunk in file
	at com.android.apksig.internal.apk.AndroidBinXmlParser.<init>(AndroidBinXmlParser.java:101)
	at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:345)
	... 6 more
```

Installation
```
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1094509404.tmp/base.apk: Corrupt XML binary file
```

### Steps to Reproduce
1. Use apktool to decode APK with -rs --force-manifest (no error) - log above
2. Use apktool to encode APK without any changes (no error) - log above
3. Try to sign/install APK and get the errors above

I have also tried to do it without flags but while it decodes correctly, when it's building it'll show errors related to "No resource identifier found for attribute" eventually failing for: 
```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/nf/t6_29zc50pb_lw5ww_p74rym0000gp/T/brut_util_Jar_6758575029498112036.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 28, --version-code, 4226, --version-name, 1.9.13c, --no-version-vectors, -F, /var/folders/nf/t6_29zc50pb_lw5ww_p74rym0000gp/T/APKTOOL6277513217225256484.tmp, -e, /var/folders/nf/t6_29zc50pb_lw5ww_p74rym0000gp/T/APKTOOL7421589631204875490.tmp, -0, arsc, -I, /Users/x/Library/apktool/framework/1.apk, -S, /Users/x/Desktop/!/apktools/67f32da161bc63a8ac5a07c1df819e63/res, -M, /Users/x/Desktop/!/apktools/67f32da161bc63a8ac5a07c1df819e63/AndroidManifest.xml]
```

By looking inside the APK I have noticed the AndroidManifest.xml isn't getting reencoded even if it builds successfully, so perhaps this is why the apksigner complains about malformed XML?

**Comment by Fire30** [comment]
I am also experiencing this exact problem.

**Comment by mqueiroz1995** [comment]
I was having the same issue.

Was able to solve it by passing the `--force-all` flag when rebuilding the apk using apktool: `aptool b my-app-dir --force-all`

**Comment by natelastname** [comment]
I'm having this bug as well.

> I was having the same issue.
> 
> Was able to solve it by passing the `--force-all` flag when rebuilding the apk using apktool: `aptool b my-app-dir --force-all`

 That solution did not work for me.

**Comment by iBotPeaches** [comment]
Not sure. I added support for API 29 (Q) and API 30 (R) and API 31 (S) which are used as those codename values which I imagine ApkSigner cannot handle.

This was a recent change that happened around version M, because it crashed Apktool as well until we wrote code to automatically remap those (ie Q -> 29). That has not been happening with anything after Q as we haven't had an update in almost a year.

If this commit doesn't solve it - https://github.com/iBotPeaches/Apktool/commit/3101a05ef6fb315391da5dfcf0771ea7dc73a3ca, then its a bug in ApkSigner and thus not Apktool.

**Comment by natelastname** [comment]
> Not sure. I added support for API 29 (Q) and API 30 (R) and API 31 (S) which are used as those codename values which I imagine ApkSigner cannot handle.
>
> This was a recent change that happened around version M, because it crashed Apktool as well until we wrote code to automatically remap those (ie Q -> 29). That has not been happening with anything after Q as we haven't had an update in almost a year.
> 
> If this commit doesn't solve it - [3101a05](https://github.com/iBotPeaches/Apktool/commit/3101a05ef6fb315391da5dfcf0771ea7dc73a3ca), then its a bug in ApkSigner and thus not Apktool.

I tried building the repo and reproducing this bug running apktool from the jar file. Unfortunately, it was not fixed. 

My understanding of the problem is that the AndroidManifest.xml is not converted back to AXML by apktool when building after a decompile with `--force-manifest`. This can be confirmed by unzipping the corrupted APK and checking AndroidManifest.xml. 

Does that change your opinion about this issue? Thank you and sorry if I'm misunderstanding the scope of apktool.

**Comment by auermich93** [comment]
This issue is still present. I am using apktool as a library and actually need only the AndroidManifest.xml decoded, thus my decoding procedure looks as follows:
```

            ApkDecoder decoder = new ApkDecoder(apkPath);

            // apktool -o
            decoder.setOutDir(new File(outputDir));

            // apkool -s
            decoder.setDecodeSources(ApkDecoder.DECODE_SOURCES_NONE);

            // only decode manifest
            decoder.setDecodeResources(ApkDecoder.DECODE_RESOURCES_NONE);
            decoder.setForceDecodeManifest(ApkDecoder.FORCE_DECODE_MANIFEST_FULL);

            // apktool -f
            decoder.setForceDelete(true);

            decoder.decode();
```
After some modifications to the APK, I build the APK as follows:

```
        ApkOptions apkOptions = new ApkOptions();
        apkOptions.verbose = true;
        // seems to be the suggested flag --force-all but this doesn't resolve the issue
        apkOptions.forceBuildAll = true;

        new Androlib(apkOptions).build(new ExtFile(new File(decodedAPKPath)), outputFile);
```

I end up with the 'Corrupt XML binary file' issue when trying to install the APK via adb install (signing works!). If I enable full decoding of resources, everything works. Just for completeness, when I run apktool d on the newly generated APK the following output is produced:

```
I: Using Apktool 2.4.1 on com.asus.filemanager.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:148)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:154)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:162)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Caused by: java.io.IOException: Expected: 0x00080003 or 0x00080001, got: 0x6d783f3c
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:854)
        at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:102)
        at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:112)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        ... 7 more
```

**Comment by auermich93** [comment]
@iBotPeaches: If I get it right, one cannot re-encode the AndroidManifest without having the decoded resources? This is at least the requirement of aapt AFAIK.

**Comment by sergei66666** [comment]
It is sad, but issue still here.

**Comment by 0x5ECF4ULT** [comment]
Issue also persists here (`apktool 2.5.0`). Passing `--force-all` doesn't change a thing. App can't be resigned or installed. @auermich93 could you please share a link to where you got that from? If @iBotPeaches won't fix it, I'll try to give it a shot or at least find a workaround.

**Comment by fgroupindonesia** [comment]
omg... i was experiencing the same problems....

**Comment by helengray** [comment]
omg... i was experiencing the same problems....

**Comment by iBotPeaches** [comment]
Sorry this ticket is so old and everyone says "same problem", but in my decade of experience here. Rarely do people have the same error. They just see a closely related exception and merge them together.

I have no idea what is being reported or not anymore. The comments are a different stacktrace than original issue. So this ticket is not on my radar.

**Comment by githubnemo** [comment]
I can confirm OP's report and also, kind of, what @auermich93 wrote.
Extracting an APK with the `-r` flag and then rebuilding it yields an APK that has an invalid `AndroidManifest.xml` and cannot be installed, yielding

    INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse .../base.apk: Corrupt XML binary file

For unpacking I use the latest release of apktool:

    apktool d -r --force-manifest -o foo foo.apk

For building I use

    apktool b foo

The apk I am unpacking has weird resources so if I omit `-r` in the decoding step the building fails which is why I skip the resource unpacking.
