### ISSUE TITLE
Some installation error

### ISSUE THREAD

**Issue by Hedreon** [iBotPeaches/Apktool#2377]
Whenever I try doing "apktool" in cmd, it'd just say "The system cannot find the path specified" when I just created a folder on desktop named "apktool", then named the jar to "apktool.jar".

Also tried putting both of these in C:\Windows and making it as a system variable. guess what? IT STILL SHOWS "The system cannot find the path specified"

HELP

**Comment by iBotPeaches** [comment]
If you are suffering with PATH variables in using helper files. I would recommend just using `java -jar apktool.jar` instead. Sorry this tracker is for bugs. So I'm closing this.

**Comment by Hedreon** [comment]
ok
