### ISSUE TITLE
ids.xml parsing issue

### ISSUE THREAD

**Issue by lavatechdev** [iBotPeaches/Apktool#2379]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
example res/values/ids.xml from v2.4.1
<item type="id" name="accessibility_custom_action_0" />

example res/values/ids.xml from v2.3.4
<item type="id" name="accessibility_custom_action_0">false</item>
```

### Steps to Reproduce
1. `decompile the apk with apktool v2.4.1 `
2. `decompile the apk with apktool v2.3.4 to different directory`
3. `Compare the res/values/ids.xml files`

After building the apk using apktool v2.4.1 some of the functionality of the app stopped working, and the app started to crash. I have realised that the ids.xml file is a bit different and decided to replace it with the file which I got as a result of decompilation app using apktool 2.3.4. 
After building the app everything works fine so I believe there is some problem with parsing this file.

**Comment by iBotPeaches** [comment]
> AAPT2 only allows ids in the form of:
> <item type=id" name="my_id/>
> <item type=id" name="my_id></item>
> <item type=id" name="my_id>@id/other_id</item> 
> You probably have some other text in your inner xml element.

https://issuetracker.google.com/issues/80475496

From the codebase.

```
        // Android does not allow values (false) for ids.xml anymore
        // https://issuetracker.google.com/issues/80475496
        // But it decodes as a ResBoolean, which makes no sense. So force it to empty
        if (type.equalsIgnoreCase("id") && !body.isEmpty()) {
            body = "";
        }
```

This is intentional. Use aapt2.
