### ISSUE TITLE
Can't Successfully Decompile Play Store Version 21

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#2382]
### Information
1. **Apktool Version (`apktool -version`)** - Latest build from source
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -
ApkMirror

### Stacktrace/Logcat
Decompile occurred without error but file names are all 0_resource_name_obfuscated etc,.xml
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-21-1-29-release/google-play-store-21-1-29-16-0-pr-322700992-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
I can't replicate this.

```
➜  2382 apktool d 2382.apk 
I: Using Apktool 2.4.2-b4493a-SNAPSHOT on 2382.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2382 
```

Sorry!

**Comment by Phone-Guru** [comment]
I think you missed the point. I also don't get errors  but the files are not named or decompiled correctly.

**Comment by iBotPeaches** [comment]
> I think you missed the point. I also don't get errors but the files are not named or decompiled correctly.

Can you investigate what you are expecting a file to be called and what you are getting? Likewise for what is decoded incorrectly vs what you expect?

**Comment by Phone-Guru** [comment]
Decompile occurred without error but file names are all 0_resource_name_obfuscated etc,.xml

**Comment by iBotPeaches** [comment]
> Decompile occurred without error but file names are all 0_resource_name_obfuscated etc,.xml

Seems intentional. They stripped human readable names. If the names are obfuscated then where do you find the real ones?
