### ISSUE TITLE
Invalid or corrupt jarfile fatty-client.jar

### ISSUE THREAD

**Issue by Ashokmurugan48** [iBotPeaches/Apktool#2383]
I got this error "Invalid or corrupt jarfile fatty-client.jar" while executing apktool compiled .jar file

root@kali:~# apktool d fatty-client1.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty on fatty-client1.jar
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
root@kali:~# ls
fatty-client1.jar  fatty-client1.jar.out
root@kali:~# cd fatty-client1.jar.out/
root@kali:~/fatty-client1.jar.out# ls
apktool.yml  META-INF  original  unknown
root@kali:~/fatty-client1.jar.out# cd ..
root@kali:~# apktool b fatty-client1.jar.out -o fc.jar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty
W: Could not find sources
W: Could not find resources
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
root@kali:~y# ls
fatty-client1.jar  fatty-client1.jar.out  fc.jar
root@kali:~# chmod +x fc.jar
root@kali:~# ls -al fc.jar 
-rwxr-xr-x 1 root root 14564635 Jul 30 13:51 fc.jar
root@kali:~# java -jar fc.jar
Error: Invalid or corrupt jarfile fc.jar

please help me to solve this problem

**Comment by giacomoferretti** [comment]
We don't have your file, so we cannot help you.

**Comment by Ashokmurugan48** [comment]
[fatty-client.jar.zip](https://github.com/iBotPeaches/Apktool/files/5011911/fatty-client.jar.zip)
This is my jar file.
Rename this file fatty-client.jar.zip to fatty-client.jar

**Comment by giacomoferretti** [comment]
Correct me if I'm wrong, but I don't think you can use Apktool on this JAR.
This tool was made for Android apps and not for simple JAR files.

If your end goal is to simply extract the files, use the `jar` command or any other zip extraction tool like 7zip.

If your end goal is to modify/patch the jar, you should extract and modify the class files using other tools. Search for "Java Bytecode Editor" or "Java Class Editor" or something like this.

**Comment by iBotPeaches** [comment]
Yeah Apktool is meant for Android applications - not generic Java jar files. While it might decode - it won't be usable.
