### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exe

### ISSUE THREAD

**Issue by linyia01** [iBotPeaches/Apktool#2395]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.1
2. **Operating System (Mac, Linux, Windows)** - windows
3. **APK From? (Playstore, ROM, Other)** - github 

### Stacktrace/Logcat
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\xml\z.xml:36: error: No resource identifier found for attribute 'labCharNumSingleLine' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\drawable\a6a.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\drawable\a6c.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\drawable\a6c.xml:31: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\drawable\a6h.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\drawable\a6j.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\color\uy.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\color\v6.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\Program Files\jdk-11.0.8\bin\dfcf_892\res\color\vb.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
[brut.androlib.AndrolibException: brut.common.BrutException: could not exe](url)c (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_1309050391066134863.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 8009002, --version-name, 8.9.2, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL12014445178569112284.tmp, -e, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL13095149802263050025.tmp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, D:\Program Files\jdk-11.0.8\bin\dfcf_892\res, -M, D:\Program Files\jdk-11.0.8\bin\dfcf_892\AndroidManifest.xml]

W: D:\apk\dfcf_892\res\drawable\a6c.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\drawable\a6c.xml:31: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\drawable\a6h.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\drawable\a6j.xml:6: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\color\uy.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\color\v6.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
W: D:\apk\dfcf_892\res\color\vb.xml:4: error: No resource identifier found for attribute 'key_disable' in package 'com.eastmoney.android.berlin'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_913805722ersion, 14, --target-sdk-version, 26, --version-code, 8009002, --version-name, 8.9.2, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKT-0, 7z, -0, png, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifcle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, METANF/com.android.support_design.version, -0, META-INF/com.android.support_gridlayout-v7.version, -0, META-INF/com.android.support_recyclerview-v7.version,  -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_rt_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -wav, -0, ogg, -0, m4a, -0, arsc, -I, frameword\1.apk, -S, D:\apk\dfcf_892\res, -M, D:\apk\dfcf_892\AndroidManifest.xml]

```
Include stacktrace here
```
apk dowload addr :http://p.gdown.baidu.com/5d0bee45cb66205e23326747bf1d704787112680ee47999d346c175ddd4b176b38c613349d3db5335659ace5372e848d7b213c3fcdfcc090ffd578f9dbf171b3391f6578e224a95d8e8bc846b51b73e4c870356c6ca3b4fec31ccf7bba21f6d392bf077060579405c58f29b5df2eeb1110f6ab62ebfc3d59f2aa11f6459b69a089fd7382d681dfa485983f1c31d38024c46528832d9cf438d25b930b928e94a87217909751f6f115769152cb619540b42c8b3a8eb485418ac03c5aef132fecd11a0963cb9920aa5e1cb6ae4e453aa903
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://github.com/iBotPeaches/Apktool/releases/tag/v2.4.1

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by MrIkso** [comment]
Decrypt resources first before modifying with apktool.

**Comment by iBotPeaches** [comment]
Rebuilding this stuff is increasingly difficult with all the tools/features to make returning to semi-human readable code more difficult.

Apktool decodes this fine

```
➜  2395 apktool d 001a51ce3c54bc20009d8f0431879a3b.apk 
I: Using Apktool 2.4.2-b4493a-SNAPSHOT on 001a51ce3c54bc20009d8f0431879a3b.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2395 
```

At this point, I think that is fine. Rebuilding will take some manual work to correct what we cannot automate.
