### ISSUE TITLE
Not support Android 11

### ISSUE THREAD

**Issue by ADroidCoder** [iBotPeaches/Apktool#2397]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.1
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -Other

The  queries tag in android11 is not supported. You must use the latest aapt2 (30.0.0) version. The latest apktool version does not support the latest aapt2.

If you specify the latest version of AAPT2, it is possible for the command to be too long to execute. The AAPT in apkTool handles the problem of command length through the -e parameter

**Comment by giacomoferretti** [comment]
Could you provide some examples to reproduce the issue? Thanks 😊

**Comment by MrIkso** [comment]
Not compiled AndroidManifest.xml with new attributes?

**Comment by ADroidCoder** [comment]
> Could you provide some examples to reproduce the issue? Thanks

![Uploading image.png…]()


> Not compiled AndroidManifest.xml with new attributes?

yes 

https://developer.android.google.cn/preview/privacy/package-visibility#all-apps

**Comment by iBotPeaches** [comment]
I need to remake aapt/aapt2 binaries, but mac isn't playing nice and I think tis time to make aapt2 default and freeze aapt fixes. I have some work to do.

**Comment by luscff99** [comment]
![Screenshot_20200914-001856.png](https://user-images.githubusercontent.com/70997343/93040332-29451100-f620-11ea-8180-280e9c6d9cd9.png)
Can someone help me?

**Comment by codylund** [comment]
Any progress on pulling in the AAPT2 updates? Also curious if there is an ETA for an official ApkTool release with Android 11 support.

**Comment by iBotPeaches** [comment]
> Any progress on pulling in the AAPT2 updates? Also curious if there is an ETA for an official ApkTool release with Android 11 support.

Mac isn't building still. I might have to vm an older version with exactly what aosp wants.

**Comment by iBotPeaches** [comment]
The newest binaries are now on master. Closing as they have been updated.
