### ISSUE TITLE
Recompile doesn't work , if  I modify Manifest or any resource

### ISSUE THREAD

**Issue by sshuvro58** [iBotPeaches/Apktool#2399]
Recompile doesn't work , if  I modify Manifest or any resource

Here is how I decomplie it 

**apktool d -f -r zoomroom.5.1.35624.0822.apk**

If I recompile it 
**apktool b  zoomroom.5.1.35624.0822**

I get the following error 

**brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):**

However , If I do not change anything , it works fine

I have also included -**-use-aapt2** , I get the same error

### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/zoom-rooms/us.zoom.zrc

**Comment by MrIkso** [comment]
Send full log please

**Comment by sshuvro58** [comment]
> Send full log please

apktool b zoomroom.5.1.35624.0822
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/paranoid/Downloads/new_try/zoomroom.5.1.35624.0822/res/layout-v22/pzr_binding_login_fragment.xml:10: error: No resource identifier found for attribute 'screenReaderFocusable' in package 'android'
W: 
W: /home/paranoid/Downloads/new_try/zoomroom.5.1.35624.0822/res/layout-v22/zm_zr_conf_toolbar.xml:20: error: No resource identifier found for attribute 'screenReaderFocusable' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_8414531028194679346.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 21, --version-name, 5.1.35624.0822, --no-version-vectors, -F, /tmp/APKTOOL1382623739461020781.tmp, -e, /tmp/APKTOOL18029152062007404445.tmp, -0, arsc, -I, /home/paranoid/.local/share/apktool/framework/1.apk, -S, /home/paranoid/Downloads/new_try/zoomroom.5.1.35624.0822/res, -M, /home/paranoid/Downloads/new_try/zoomroom.5.1.35624.0822/AndroidManifest.xml]

**Comment by giacomoferretti** [comment]
Have to you tried to empty your framework dir using `apktool empty-framework-dir`? Maybe your framework is not updated.

Otherwise you can decode and build using the `-p .` parameter to specify the current folder as your framework dir.

**Comment by iBotPeaches** [comment]
Added new Android 11 resources here - https://github.com/iBotPeaches/Apktool/commit/22fdee4d2e6fbcc9b3923d9b5ed5b984696ce55f - will be in next release.
