### ISSUE TITLE
Apktool does not allow me to view the content of the apk files in Termux

### ISSUE THREAD

**Issue by AdrMXR** [iBotPeaches/Apktool#2403]
### Information
1. **Apktool Version (`2.3.4`)**
2. **Operating System (`Termux`)** -
3. **APK From? (`Apk msfvenom`)** -

When I unzip the apk apparently everything is done correctly, but when trying to see for example the AndroidManifest.xml file it appears like this

```
^K^@^@4^K^@^@b^K^@^@�^K^@^@�^K^@^@�^K^@^@^K^@v^@e^@r^@s^@i^@o^@n^@C^@o^@d^@e^@^@$
^@m^@i^@n^@S^@d^@k^@V^@e^@r^@s^@i^@o^@n^@^@^@^P^@t^@a^@r^@g^@e^@t^@S^@d^@k^@V^@e^@r^@$
^@.^@M^@a^@i^@n^@A^@c^@t^@i^@v^@i^@t^@y^@^@^@
^@i^@n^@t^@e^@n^@t^@-^@f^@i^@l^@t^@e^@r^@^@^@^F^@a^@c^@t^@i^@o^@n^@^@^@^Z^@a^@n^@d^@r$
^@m^@e^@t^@a^@s^@p^@l^@o^@i^@t^@^@^@^_^@a^@n^@d^@r^@o^@i^@d^@.^@i^@n^@t^@e^@n^@t^@.^@$
^@^@^@^K^@^@^@^B^A^P^@�^@^@^@^B^@^@^@��������^P^@^@^@^T^@^T^@^E^@^@^@^@^@^@^@^K^@^@^@$
^@^@^@^R^@^@^@^H^@^@^C^R^@^@^@����^N^@^@^@^S^@^@^@^H^@^@^P
^@^@^@����^O^@^@^@^T^@^@^@^H^@^@^C^T^@^@^@^B^A^P^@L^@^@^@^D^@^@^@��������^U^@^@^@^T^@$
^@^@^@^K^@^@^@^C^@^@^@����^H^@^@^P^Q^@^@^@^C^A^P^@^X^@^@^@^D^@^@^@��������^U^@^@^@^B^$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^[^@^@^@^H^@^@^C^[^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^K^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^^^@^@^@^H^@^@^C^^^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^N^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@^K^@^@^@
```

I've tried other versions of apktool but I can't get good results, and something I've noticed is that in Termux it doesn't unzip all the folders, when doing it in my kali linux it unzips a folder called res, and when doing it in termux this folder doesn't appear when unzipping the apk.

**Comment by iBotPeaches** [comment]
Not sure what is being asked here. You disassemble the application to help convert AXML -> XML. You don't ever unzip an application.

Take a read at the docs :)

This isn't a bug.

**Comment by AdrMXR** [comment]
`$ apktool d prueba.apk
I: Using Apktool 2.3.4 on prueba.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
$ cd prueba
$ cat AndroidManifest.xml
E04Rv�������8<N���*L��p�b��\��,b��H�    :      Nl       �       �       �       �       *
6
H
`
�
�

 4
  b
   �
    �
     �

      versionCode
minSdkVersiontargetSdkVersionnamelabelthemehostschemexportedandroid*http://schemas.android.com/apk/res/androidpackageplatformBuildVersionCodeplatformBuildVersionNammanifest1.0com.metasploit.stage102.3.uses-sdkuses-permissionndroid.permission.INTERNET$android.permission.ACCESS_WIFI_STATE$android.permission.CHANGE_WIFI_STATE'android.permission.ACCESS_NETWORK_STATE)android.permission.ACCESS_COARSE_LOCATION'android.permission.ACCESS_FINE_LOCATION#android.permission.READ_PHONE_STATEndroid.permission.SEND_SMSandroid.permission.RECEIVE_SMSandroid.permission.RECORD_AUDIOandroid.permission.CALL_PHONE android.permission.READ_CONTACTS!android.permission.WRITE_CONTACTS!android.permission.WRITE_SETTINGSandroid.permission.CAMERAndroid.permission.READ_SMS)android.permission.WRITE_EXTERNAL_STORAGE)android.permission.RECEIVE_BOOT_COMPLETED android.permission.SET_WALLPAPER android.permission.READ_CALL_LOG!android.permission.WRITE_CALL_LOGandroid.permission.WAKE_LOCK
  uses-featureandroid.hardware.camera!android.hardware.camera.autofocusndroid.hardware.microphone
intent-filteractionandroid.intent.action.MAIcategory android.intent.category.LAUNCHERdatamy_host
metasploitandroid.intent.category.DEFAULT!android.intent.category.BROWSABLEandroid.intent.action.VIEreceiverMainBroadcastReceiver.MainBroadcastReceiver$android.intent.action.BOOT_COMPLETEDservice
   .MainService0
                p('����

���������
         ����
����       ����
���L��������
            ����

�����������8��������
                   ��������8��������
                                   ����������������
 ��������8      ��������
                        ��������8
��������

��������8
         ��������

                ��������8
                         ��������

��������                        ��������8
��������8��������
                ��������8��������
                                  ��������8��������
   !��������8��������
                     "��������8��������
                                       #��������8��������
          ��������8��������
                           $��������8��������
                                             %��������8��������
               &��������8��������
                                 '��������8��������
   (��������8��������
                     )��������8��������
                                       *��������8�������
        +�������8��������
                         ,��������8��������-
                                            .��������-8��������-
                /��������-8 ��������-
                                     0 ��������-8"��������1
           ���`#��������2
                         ���U
                             ����
                                3$$��������48%��������5
       6%��������58&��������7
                             8&��������7'��������4$(��������4L)��������9
                       ;
                        :)��������98*��������7
                                              <*��������78+��������7
                    =+��������78,��������5
                                          >,��������5-��������4.��������2L/��������?
                                    @
                                     A$0��������481��������5
            B1��������52��������43��������?L5��������C
      D
        �������5��������C6��������18��������8����

$`

**Comment by AdrMXR** [comment]
$ apktool d prueba.apk
 I: Using Apktool 2.3.4 on prueba.apk
 I: Copying raw resources...
 I: Baksmaling classes.dex...
 I: Copying assets and libs... 
 I: Copying unknown files... 
 I: Copying original files...
 $ cd prueba 
 $ cat AndroidManifest.xml 

```
^K^@^@4^K^@^@b^K^@^@�^K^@^@�^K^@^@�^K^@^@^K^@v^@e^@r^@s^@i^@o^@n^@C^@o^@d^@e^@^@$
^@m^@i^@n^@S^@d^@k^@V^@e^@r^@s^@i^@o^@n^@^@^@^P^@t^@a^@r^@g^@e^@t^@S^@d^@k^@V^@e^@r^@$
^@.^@M^@a^@i^@n^@A^@c^@t^@i^@v^@i^@t^@y^@^@^@
^@i^@n^@t^@e^@n^@t^@-^@f^@i^@l^@t^@e^@r^@^@^@^F^@a^@c^@t^@i^@o^@n^@^@^@^Z^@a^@n^@d^@r$
^@m^@e^@t^@a^@s^@p^@l^@o^@i^@t^@^@^@^_^@a^@n^@d^@r^@o^@i^@d^@.^@i^@n^@t^@e^@n^@t^@.^@$
^@^@^@^K^@^@^@^B^A^P^@�^@^@^@^B^@^@^@��������^P^@^@^@^T^@^T^@^E^@^@^@^@^@^@^@^K^@^@^@$
^@^@^@^R^@^@^@^H^@^@^C^R^@^@^@����^N^@^@^@^S^@^@^@^H^@^@^P
^@^@^@����^O^@^@^@^T^@^@^@^H^@^@^C^T^@^@^@^B^A^P^@L^@^@^@^D^@^@^@��������^U^@^@^@^T^@$
^@^@^@^K^@^@^@^C^@^@^@����^H^@^@^P^Q^@^@^@^C^A^P^@^X^@^@^@^D^@^@^@��������^U^@^@^@^B^$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^[^@^@^@^H^@^@^C^[^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^K^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^^^@^@^@^H^@^@^C^^^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^N^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@^K^@^@^@
 
```

**Comment by AdrMXR** [comment]
I am performing this procedure with an apk generated with msfvenom
