### ISSUE TITLE
Apktool error

### ISSUE THREAD

**Issue by umeshhamal-cpu** [iBotPeaches/Apktool#2407]
root@kali:/usr/share# apktool b /sdcard/malicious/lite
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_2285372021417925437.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 28, --version-code, 244869092, --version-name, 216.0.0.10.121, --no-version-vectors, -F, /tmp/APKTOOL6438902344247228489.tmp, -e, /tmp/APKTOOL335927903907616092.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /sdcard/malicious/lite/res, -M, /sdcard/malicious/lite/AndroidManifest.xml]
W: /tmp/brut_util_Jar_2285372021417925437.tmp: 1: ELF: not found
W: /tmp/brut_util_Jar_2285372021417925437.tmp: 1: Syntax error: end of file unexpected (expecting ")")
This problem occurs when i try to recompile the apk file?

**Comment by giacomoferretti** [comment]
Can you share your APK with us?

**Comment by umeshhamal-cpu** [comment]
Yaah why not

**Comment by umeshhamal-cpu** [comment]
I am using facebook lite from apkpure

**Comment by umeshhamal-cpu** [comment]
> Can you share your APK with us?

Yaah why not i am using facebook lite from apkpure😕
->Apktool decompile the apk but can't recompile the file of the apk!!![Screenshot_2020-09-20-16-13-24-994_com.offsec.nhterm.jpg](https://user-images.githubusercontent.com/71560050/93709521-6186ab00-fb5c-11ea-9f08-3f9df22e0d6b.jpg)

**Comment by umeshhamal-cpu** [comment]
> > Can you share your APK with us?
> 
> Yaah why not i am using facebook lite from apkpure😕
> ->Apktool decompile the apk but can't recompile the file of the apk!!![Screenshot_2020-09-20-16-13-24-994_com.offsec.nhterm.jpg](https://user-images.githubusercontent.com/71560050/93709521-6186ab00-fb5c-11ea-9f08-3f9df22e0d6b.jpg)

![Screenshot_2020-09-20-16-13-30-140_com.offsec.nhterm.jpg](https://user-images.githubusercontent.com/71560050/93709527-719e8a80-fb5c-11ea-8aa5-01cb61c22841.jpg)

**Comment by umeshhamal-cpu** [comment]
Yaah why not, i am using facebook lite from apkpure😕
->Apktool decompile the apk but can't recompile the file of the apk!!

![Screenshot_2020-09-20-16-13-24-994_com.offsec.nhterm.jpg](https://user-images.githubusercontent.com/71560050/93709574-dce85c80-fb5c-11ea-9adc-2d8f29808362.jpg)


![Screenshot_2020-09-20-16-13-30-140_com.offsec.nhterm.jpg](https://user-images.githubusercontent.com/71560050/93709582-e5409780-fb5c-11ea-92c0-4cb6ef11d375.jpg)

**Comment by iBotPeaches** [comment]
```
W: /tmp/brut_util_Jar_2285372021417925437.tmp: 1: �ELF: not found
W: /tmp/brut_util_Jar_2285372021417925437.tmp: 1: Syntax error: end of file unexpected (expecting ")")
```

Whatever arch/cpu/bitness you are on is not supported. Give me an output of `lscpu` on that.

**Comment by umeshhamal-cpu** [comment]
@iBotPeaches 
root@kali:/sdcard/ApkEditor# lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1401.0000
CPU min MHz:         960.0000
BogoMIPS:            38.40
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

**Comment by EthecRaz** [comment]
my problem is EXactly same

**Comment by bruneo32** [comment]
Same problem here, and similar lscpu output

**Comment by ChrisTheCoolHut** [comment]
We were able to get apktool running and working on an aarch64 system by using QEMU userspace emulation and binfmt support:
https://wiki.debian.org/QemuUserEmulation
```
sudo apt install binfmt-support qemu-user-static
```

**Comment by dr1408** [comment]
I have same problem any fix ?

**Comment by iBotPeaches** [comment]
> I have same problem any fix ?

There looks to be many workarounds in this thread. Did you try those?

To help further debug - may I have output of `java -XshowSettings:properties -version` ? Need to see arch/bitness.

**Comment by dr1408** [comment]
I only tried to empty framework directory didn't work I am on nethunter  Kali armhf my phone is armv8l


Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = UTF-8
    file.separator = /
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path =
    java.class.version = 55.0
    java.home = /usr/lib/jvm/java-11-openjdk-armhf
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib
        /usr/lib/arm-linux-gnueabihf/jni
        /lib/arm-linux-gnueabihf
        /usr/lib/arm-linux-gnueabihf
        /usr/lib/jni
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 11.0.20-ea+7-post-Debian-1
    java.specification.maintenance.version = 2
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 11
    java.vendor = Debian
    java.vendor.url = https://tracker.debian.org/openjdk-11
    java.vendor.url.bug = https://bugs.debian.org/openjdk-11
    java.version = 11.0.20-ea
    java.version.date = 2023-07-18
    java.vm.info = mixed mode
    java.vm.name = OpenJDK Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 11
    java.vm.vendor = Debian
    java.vm.version = 11.0.20-ea+7-post-Debian-1
    jdk.debug = release
    line.separator = \n
    os.arch = arm
    os.name = Linux
    os.version = 4.19.191-25884040-abA137FXXS3CWL2
    path.separator = :
    sun.arch.abi =
    sun.arch.data.model = 32
    sun.boot.library.path = /usr/lib/jvm/java-11-openjdk-armhf/lib
    sun.cpu.endian = little
    sun.cpu.isalist =
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /
    user.home = /root
    user.language = en
    user.name = root
    user.timezone =

openjdk version "11.0.20-ea" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20-ea+7-post-Debian-1)
OpenJDK Server VM (build 11.0.20-ea+7-post-Debian-1, mixed m
