### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by kalmen26** [iBotPeaches/Apktool#2409]
### Information
I am wanting to recompile the settings.apk from a mediatek and I can't, already install the framework-res.apk metdiatek-res.apk qphone-res.apk

### Stacktrace/Logcat
C:\Users\kalel\Desktop\original system>apktool b Settings
I: Using Apktool 2.4.1
I: Copying Settings classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_0.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_1.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_10.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_11.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_12.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_13.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_14.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_2.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_3.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_4.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_5.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_6.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_7.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_8.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_9.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lockscreen_default_preview.png
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\kalel\AppData\Local\Temp\brut_util_Jar_8134239982566092549.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0-1560838724, --no-version-vectors, -F, C:\Users\kalel\AppData\Local\Temp\APKTOOL919114506552426166.tmp, -e, C:\Users\kalel\AppData\Local\Temp\APKTOOL4524820509356638168.tmp, -0, arsc, -I, C:\Users\kalel\AppData\Local\apktool\framework\1.apk, -S, C:\Users\kalel\Desktop\original system\Settings\res, -M, C:\Users\kalel\Desktop\original system\Settings\AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
```
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image C:\Users\kalel\Desktop\original system\Settings\res\drawable-hdpi-v4\lock_anim_9.png
```

Looks like you have some bad images. Not sure what Apktool can do about that. Build systems get stricter, maybe the original build system didn't care about that. The Apktool one does.

**Comment by kalmen26** [comment]
C:\Users\kalel\Desktop\original system>apktool b Settings
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\kalel\Desktop\original system\Settings\res\values\public.xml:383: error: Public symbol drawable/lockscreen_default_preview declared here is not defined.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\kalel\AppData\Local\Temp\brut_util_Jar_358760540989192684.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0-1560838724, --no-version-vectors, -F, C:\Users\kalel\AppData\Local\Temp\APKTOOL1030532081337026247.tmp, -e, C:\Users\kalel\AppData\Local\Temp\APKTOOL524033182136468157.tmp, -0, arsc, -I, C:\Users\kalel\AppData\Local\apktool\framework\1.apk, -S, C:\Users\kalel\Desktop\original system\Settings\res, -M, C:\Users\kalel\Desktop\original system\Settings\AndroidManifest.xml]

**Comment by AndnixSH** [comment]
I used Photoshop to re-save the image and it fixed the PNG error
