### ISSUE TITLE
After recompile, the smali file name was wrong, which cause NoClassDefFoundError

### ISSUE THREAD

**Issue by winterbest** [iBotPeaches/Apktool#2411]
### Information
1. 2.4.1
2. Linux
3. ROM

![image](https://user-images.githubusercontent.com/2382425/94153586-88701480-feaf-11ea-9f04-8724a896be09.png)
the com/tygrm/sdk/core/TYRSDK exists in smali_classes2 before recompile, but it moved to smali_classes2_classes3

before recompile:
![image](https://user-images.githubusercontent.com/2382425/94154068-18ae5980-feb0-11ea-94d2-f527cb537a98.png)

after recompile:
![image](https://user-images.githubusercontent.com/2382425/94154149-2bc12980-feb0-11ea-99a7-17f61a38f439.png)

**Comment by iBotPeaches** [comment]
Hmm. It should not make `smali_classes2_classes3` that looks wrong. How did you get that folder? Did that happen after rebuilding/decoding the prebuilt binary?

**Comment by iBotPeaches** [comment]
I wrote a test-case for this and pushed it up to test all 3 platforms. If that passes, then I'll merge that as I can't replicate. If the tests fail, then I guess we have a problem to investigate.
