### ISSUE TITLE
Apktooling Progress Bar

### ISSUE THREAD

**Issue by d0n473ll0** [iBotPeaches/Apktool#2413]
Hi!
Why apktool don't have progress bar option? Do you have plans to create option for showing reverse engineering progress? That would be very useful!

Thanks in advance!

**Comment by iBotPeaches** [comment]
It doesn't because not many cli based tools provide progress bars as they are difficult to do. How would we even know an accurate representation? You have to read the file more and more to learn about more respecs. 

Not something I'm currently exploring. Thanks for the suggestion though.
