### ISSUE TITLE
Help me fix this problem

### ISSUE THREAD

**Issue by kakathic** [iBotPeaches/Apktool#2415]
![Screenshot_2020-10-03-11-10-20-444_bin mt plus](https://user-images.githubusercontent.com/28665018/94982973-1e1f3a00-0569-11eb-97c6-15d12d16f820.png)

I want to ask for a fix without losing -v4 and some folders.

Thanks for reading this message
Thank you for creating apktool

**Comment by iBotPeaches** [comment]
This isn't easy. It was attempted and broke many apps then it fixed. See: https://github.com/iBotPeaches/Apktool/issues/1272#issuecomment-379345005
