### ISSUE TITLE
Cannot install apktool

### ISSUE THREAD

**Issue by derodevil** [iBotPeaches/Apktool#2416]
1. Apktool Version: 2.4.1
2. Operating System: Windows

I cannot execute apktool from console where I set the path in Environment Variables. I have followed the install instruction. I also have setup java home directory in Environment Variables. Pointing directly to java file C:\Program Files\Java\jdk-14.0.1\bin\java.exe or using java home variable %JAVA_HOME%\bin\java.exe in apktool.bat and run as administrator has no effect.
![Image 1](https://user-images.githubusercontent.com/4223012/95289020-00691200-0894-11eb-9496-d23f62d6d3a8.jpg)

**Comment by joklek** [comment]
What do you mean by "install", what is your end goal? As I see it you can successfully run apktool, as seen in your last command. 

Additional question, why did you put apktool to your windows directory?

**Comment by derodevil** [comment]
I should run `apktool --version` instead of `java -jar C:\Windows\apktool.jar --version`. Using `java -jar etc` is not recognized in [objection](https://github.com/sensepost/objection) when running command `objection patchapk -s file.apk`.
I put apktool in Windows directory as this [instruction](https://ibotpeaches.github.io/Apktool/install/)

**Comment by iBotPeaches** [comment]
> Additional question, why did you put apktool to your windows directory?

Probably to follow a helpful step to make a helper file so you don't need to use `java -jar`.

Either way - this isn't a bug and instead just configuration issues.

**Comment by derodevil** [comment]
> Probably to follow a helpful step to make a helper file so you don't need to use `java -jar`.
What kind of helper file do you mean? Do you have an example to do so?

> Either way - this isn't a bug and instead just configuration issues.
What configuration. What should I do with it?

**Comment by joklek** [comment]
I have limited knowledge of windows and etc., but if I understand what you want, you can create a bat file with this as contents

```bat
@echo off
java -jar "%~dp0apktool.jar"
```

and then move it and apktool.jar to a new directory like `C:\Program Files (x86)\apktool`

Then add this directory path via System Properties > Environment variables.. > System Variables, find Path, click edit and add `C:\Program Files (x86)\apktool` and save
