### ISSUE TITLE
invalid resource directory name: ./res navigation - APK rebuild fails

### ISSUE THREAD

**Issue by S-trace** [iBotPeaches/Apktool#2417]
### Information
1. **Apktool Version (`apktool -version`)** - master (a2a7940)
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
```
I: Using Apktool 2.4.2-a2a794-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /tmp/auth/./res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_43501640436306506734061535743344441292.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 29, --version-code, 202058793, --version-name, 6.2009.5879, --no-version-vectors, -F, /tmp/APKTOOL7411794995348549440.tmp, -e, /tmp/APKTOOL16937902228744416879.tmp, -0, arsc, -I, /home/s-trace/.local/share/apktool/framework/1.apk, -S, /tmp/auth/./res, -M, /tmp/auth/./AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool  d auth.apk`
2. `cd auth`
3. `apktool  b`

### Frameworks
No OEM frameworks.

### APK
https://play.google.com/store/apps/details?id=com.azure.authenticator

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes, it failed.
2. If you are trying to install a modified apk, did you resign it? - APK rebuild fails.
3. Are you using the latest apktool version? - yes, bleeding edge.

**Comment by S-trace** [comment]
UPD:
`apktool b --use-aapt2` allows to rebuild the APK, but gives some non-fatal warnings like this:
```
W: /tmp/auth/./res/values/public.xml:2246: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
```

Also tried to use https://github.com/iBotPeaches/Apktool/tree/issue-2369 to unpack and rebuild the APK - warnings are still there.

**Comment by iBotPeaches** [comment]
I can't replicate this sorry. I even wrote tests to confirm - https://github.com/iBotPeaches/Apktool/pull/2370/files.
