### ISSUE TITLE
Rebuilded APK is Broken when used -force-manifest.

### ISSUE THREAD

**Issue by viliyam2811** [iBotPeaches/Apktool#2418]
### Information
1. **Apktool Version (v2.4.0-dirty)** -
2. **Operating System (Linux - Termux Ubuntu Rootsfs)** -
3. **APK From? (Any)** -

### Steps to Reproduce
1. apktool d -s -r -force-manifest myapp.apk
2. apktool b myapp

Rebuiding Success But APK is broken everytime.

### APK
Included any APKs

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - No
3. Are you using the latest apktool version? - Its up-to-date on Ubuntu20 aacrh64. apktool v2.4.0-dirty

**Comment by rubenanagua** [comment]
This is not expected to be possible at this time, as the decompiled resources are required to recompile the AndroidManifest.xml file. So, `-r`/`--no-res` and `--force-manifest` aren't compatible if you'd like to rebuild the app (see #1699).

The only thing that could be done is changing up the documentation to note that this flag is intended for analytic purposes only (as is the case with `--match-original`), and that using this with `--no-res` prevents rebuild.

**Comment by iBotPeaches** [comment]
As mentioned above. This property is for analysis and not intended to be used for recompilation as you'll need hooks to resources to properly rebuild the manifest.

Slipped in commit to update docs to mention this - https://github.com/iBotPeaches/Apktool/commit/d9572e534461434b73a94b8821e415df91c16856

Closing as docs updated.
