### ISSUE TITLE
Usage of empty namespaces in AndroidManifest.xml

### ISSUE THREAD

**Issue by bagipro** [iBotPeaches/Apktool#2420]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Steps to Reproduce
`apktool d com.xoom.android.app.apk`

### APK
https://drive.google.com/file/d/1N9p7Jdt153UIrWJvsG_Knwr0-FIdJS45/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? +
2. If you are trying to install a modified apk, did you resign it? +
3. Are you using the latest apktool version? +

The whole `AndroidManifest.xml` looks like so
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" compileSdkVersion="29" compileSdkVersionCodename="10" package="com.xoom.android.app" platformBuildVersionCode="29" platformBuildVersionName="10" versionName="8.0.1">
    <uses-permission name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission name="android.permission.INTERNET"/>
    <uses-permission name="android.permission.VIBRATE"/>
    <uses-permission name="android.permission.WAKE_LOCK"/>
    <uses-permission name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission name="android.permission.CAMERA"/>
    <uses-feature name="android.hardware.camera" required="false"/>
    <uses-feature name="android.hardware.camera.autofocus" required="false"/>
    <uses-feature name="android.hardware.camera.flash" required="false"/>
    <permission name="com.xoom.android.app.permission.C2D_MESSAGE" protectionLevel="signature"/>
```

So all attributes don't contain `android` namespace

**Comment by iBotPeaches** [comment]
Not sure what you are reporting here. Just looks like a bunch of permissions to me.

**Comment by bagipro** [comment]
Hey @iBotPeaches 
All of the attributes should be declared in `android:` namespace like so
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="29" android:compileSdkVersionCodename="10" package="com.xoom.android.app" platformBuildVersionCode="29" platformBuildVersionName="10" android:versionName="8.0.1">
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
```

**Comment by iBotPeaches** [comment]
Did this change recently? Since apktool normally doesn't kill/forget about namespaces on properties. Or is it expected going forward with newer Android's that android properties are always namespaced.

**Comment by bagipro** [comment]
@iBotPeaches 
Nope, it's a kind of obfuscation that truncates namespace values

**Comment by iBotPeaches** [comment]
I replicate. Adding Bug.

**Comment by pashamcr** [comment]
@bagipro in your apk manifest, there was no 'android: name' from the beginning.
It's easy to check with aapt / aapt2. For the purity of the experiment, aapt2 took from android sdk:
```
# aapt2.exe dump permissions com.xoom.android.app.apk
package: com.xoom.android.app
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.CAMERA'
permission: com.xoom.android.app.permission.C2D_MESSAGE
uses-permission: name='com.xoom.android.app.permission.C2D_MESSAGE'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
```

**Comment by pashamcr** [comment]
@bagipro is not an apktool error, the manifest of your apk is initially corrupted, here are screenshots of a normal manifest from an arbitrary apk and a manifest from your apk open in android studio:
![Snap51](https://user-images.githubusercontent.com/36408873/100653849-e520fd00-3340-11eb-8090-a4316895d60d.png)
![Snap61](https://user-images.githubusercontent.com/36408873/100654052-2f09e300-3341-11eb-8e2c-55ad44f21e2d.png)

**Comment by bagipro** [comment]
@iBotPeaches 
This APK can be installed and used on a device (originally this is an apks file, so you should install it directly from Google Play or use split APK install apps), how it can be incorrect?

**Comment by iBotPeaches** [comment]
> @iBotPeaches
> This APK can be installed and used on a device (originally this is an apks file, so you should install it directly from Google Play or use split APK install apps), how it can be incorrect?

I didn't post that. I don't agree with @pashamcr - this looks like a bug to me.

**Comment by pashamcr** [comment]
@bagipro take a look at the screenshot, I hope you trust the program from android developers more than my words, as you can see - android studio was also unable to digest this manifest

**Comment by iBotPeaches** [comment]
This was fixed today in this PR: https://github.com/iBotPeaches/Apktool/commit/cd275ff48baed0fd84220e72ea62c98d1eeaac72

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="29" android:compileSdkVersionCodename="10" package="com.xoom.android.app" platformBuildVersionCode="29" platformBuildVersionName="10">
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
```

I see namespaces now. You are still far from assembly due to undecoded values being in a raw format that aapt2 cannot understand. I'm still debating that resolution in this ticket: https://github.com/iBotPeaches/Apktool/issues/1407

Where we either remove them or figure out some nomenclature of unknown values that aapt can understand.
