### ISSUE TITLE
Error Occurred While Disassembling Class

### ISSUE THREAD

**Issue by jmrapp1** [iBotPeaches/Apktool#2425]
### Information
1. **Apktool Version (`apktool -version`)** - `v2.4.1`
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other: https://fortnite.com/android (need to download via android device)

### Stacktrace/Logcat
```
Error occurred while disassembling class Lq.࡫; - skipping class
java.io.IOException: Illegal byte sequence
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:142)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce
1. `apktool d Fortnite_base.apk`

### APK
If this APK can be freely shared, please upload/attach a link to it.
Direct Download: https://www.dropbox.com/s/mycq4z43qz2at7j/Fortnite_base.apk?dl=0

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Not trying to build
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
I'm not sure how charsets/allowable characters work on Mac, but it looks like there are some disallowed characters. Since this is smali (3rd party dependency). I'm not sure if the proper path is to even remap or what.

Point being, I don't experience this on Linux.

```
➜  2425 apktool d Fortnite_base.apk 
I: Using Apktool 2.4.2-987220-SNAPSHOT on Fortnite_base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2425 
```

I fear this environment related based on allowable characters. Short term - I'd use Linux. If you want to chase further - I'd explore the smali project - https://github.com/JesusFreke/smali
