### ISSUE TITLE
 Consider adding back the --debug flag

### ISSUE THREAD

**Issue by natelastname** [iBotPeaches/Apktool#2426]
I don't think there is any tool out there which has an equivalent functionality.

The problem with intelliJ is that I don't think it is designed for reverse engineering APKs when you don't have the source code. Setting up a project from an APK with no source code is very difficult in intelliJ. Personally, I couldn't get this to work after spending a day on it. I suspect that it isn't possible.

**Comment by natelastname** [comment]
I suppose this is probably possible to do with aapt2, but aapt2 is highly difficult to use.

**Comment by iBotPeaches** [comment]
Debug has run its course and won't make a return. It was a feature that was great in the early times, but keeping it stable and actually supported is a nightmare.

We are talking about a feature that just injected special line items into a file to trick an IDE into 1) thinking it was a real code snippet and 2) that it could be debugged.

That was massively broken between the active IDEs and was a constant struggle to get it to work with every update. On the flip side, the smali project iteration is an actual plugin which grants much more flexibility and thus the preferred solution.
