### ISSUE TITLE
decode and build still create application crash/restart

### ISSUE THREAD

**Issue by labba** [iBotPeaches/Apktool#2427]
### Information
application name: puffin tv 
1. version 2.4.1
2. windows 10 x64
3. playstore / apk mirror

### Steps to Reproduce
1. apktool.bat -r d Regular.puffinTV_8.4.0.42136.apk -o puf
    no modification where done.
2. apktool.bat b puf -o puf_patch.apk
3. signing with my own certificate

running the puffin TV in android TV OS v9. after ~10-15 sec the application restart it self.

### APK
https://www.apkmirror.com/apk/cloudmosa-inc/puffin-tv-fast-web-browser-android-tv/puffin-tv-fast-web-browser-android-tv-8-4-0-42136-release/puffin-tv-browser-android-tv-8-4-0-42136-3-android-apk-download/download/

**Comment by iBotPeaches** [comment]
Would need the `adb logcat` to triage. I don't have the time to run applications and pull stacktraces or install them. I'll re-open if that is provided.

Sorry!
