### ISSUE TITLE
Is there a way to against  res guard tools now or future?

### ISSUE THREAD

**Issue by Efaker** [iBotPeaches/Apktool#2428]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.2/2.4.1
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** -weichat tiktok

- ### Is there a way to against against resguard tools now or future?
- ### Let it develop all the time... All apk will be occupied by the enemy!
- ### What can we do?

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
> Is there a way to against against resguard tools now or future?

Time, Money and Knowledge

> Let it develop all the time... All apk will be occupied by the enemy!

> What can we do?
ResGuard is open source much like Apktool. You could research it and figure out how it works and patch Apktool to handle it.

--

Either way - not a bug. Sorry!
