### ISSUE TITLE
XML resource invalid format

### ISSUE THREAD

**Issue by bagipro** [iBotPeaches/Apktool#2432]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Steps to Reproduce
1. `apktool d --no-src app.apk`
2. Open `res/xml/empty.xml`

The file wasn't decoded and shown as binary

### APK
https://www.apkmirror.com/apk/applisto/app-cloner/app-cloner-2-8-2-release/app-cloner-2-8-2-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
The file is not valid AXML (`res/xml/empty.xml`) so it cannot be decoded to human readable XML.

```
java.io.IOException: Expected: 0x00080003 or 0x00080001, got: 0x02fc8004
```

The header magic isn't right. Closing.
