### ISSUE TITLE
Accel World vs. Sword Art Online: Millennium Twilight can't open the .APK files!!! HELP!!! 

### ISSUE THREAD

**Issue by QBASpriteFinder** [iBotPeaches/Apktool#2433]
No matter what I seem to do I can't seem to open the .APK files in this game! Is there any to extract the .APK file from this game so that I can get the 2D Sprites!?

**Comment by AndnixSH** [comment]
Those games are not Android game.
I must assume some game assets extension are .APK. you need to research more and maybe ask the Playstation or PC modding community
