### ISSUE TITLE
Unable to decode and rebuild PlayStation App

### ISSUE THREAD

**Issue by Gubbins** [iBotPeaches/Apktool#2446]
### Information
1. **Apktool Version** -2.4.1
2. **Operating System** - Linux & Windows
3. **APK From?** - Playstore, & Other (links below)

### Stacktrace/Logcat
Following a simple decode & build the new apk can be signed and installed but when run it fails with:
```
java.lang.IllegalArgumentException: Missing argument
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
	at com.sony.sie.metropolis.secure.a.a(Cryptor.java:6)
	at com.sony.sie.metropolis.secure.b.a(SecureResource.java:7)
	at com.sony.sie.metropolis.MainApplication.b(MainApplication.java:2)
	at com.sony.sie.metropolis.MainApplication$b.run(MainApplication.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

### Steps to Reproduce
Simply decode and build, and the new apk fails as above:
1. `apktool d PSApp-20.9.5.apk`
2. `apktool b PSApp-20.9.5`

This has been tested on both Linux and Windows, running AdoptOpenJDK 15.0.1.

### Frameworks
None

### APK
* https://play.google.com/store/apps/details?id=com.scee.psxandroid
* https://apkpure.com/playstation-app/com.scee.psxandroid

### Issue observed
See Stacktrace above. There are some embedded assembly files and the Java code seems to be unable to call them in the version as rebuilt by apktool.

Unzipping and comparing the two apks the content seems to be quite different. I can provide file listings or anything else that may be useful.

**Comment by iBotPeaches** [comment]
This looks to be some form of anti-tamper. Nothing that Apktool can solve automatically. It will take some investigation to figure this out and even then, Apktool can't automate it.

That stacktrace points to some secure libraries which reach out to things. Sorry I can't help anymore, but I have to understand when an issue is outside the realm of a bug and just more anti-tamper mechanisms.

Closing.

**Comment by Gubbins** [comment]
Thanks for considering this @iBotPeaches.

A bit more information: The stack trace is from a piece of Java code which can't seem to call an embedded assembly in the rebuilt apk.

I agree, the app is probably using some kind of anti-tamper logic. Might be interesting to look at sometime but it could well be lots of effort for little reward.

**Comment by crackyou** [comment]
> Thanks for considering this @iBotPeaches.
> 
> A bit more information: The stack trace is from a piece of Java code which can't seem to call an embedded assembly in the rebuilt apk.
> 
> I agree, the app is probably using some kind of anti-tamper logic. Might be interesting to look at sometime but it could well be lots of effort for little reward.

Hello, have you found a solution?
