### ISSUE TITLE
Create simple resource deoubfuscator

### ISSUE THREAD

**Issue by MrIkso** [iBotPeaches/Apktool#2447]
As you can see now, many applications have encrypted resources. There are a lot of issues with different errors, but with the same problem - application resources are encrypted. We must fight this. You can try to create a resource deobfuscator that will restore the original resource structure and resource table.

**Comment by iBotPeaches** [comment]
> You can try to create a resource deobfuscator that will restore the original resource structure and resource table.

Don't most of them destroy the original name of the resource? Since Android just needs the resourceId. So how much can we even restore? We'd need dummy attributes.

**Comment by MrIkso** [comment]
@iBotPeaches the original names have been destroyed anyway, so it makes no sense to do something with them when they start with the same character, or what Unicode character is used.  It is necessary to restore the name of all resources depending on the type.  For example string_1, color_1, drawable_1 and so on.  This should fix all compilation errors.  But also, there are many problems when decompiling such resources.  That's why you should try to make a deobfuscator.

**Comment by iBotPeaches** [comment]
> @iBotPeaches the original names have been destroyed anyway, so it makes no sense to do something with them when they start with the same character, or what Unicode character is used. It is necessary to restore the name of all resources depending on the type. For example string_1, color_1, drawable_1 and so on. This should fix all compilation errors. But also, there are many problems when decompiling such resources. That's why you should try to make a deobfuscator.

Easier said than done :)

**Comment by MrIkso** [comment]
I started working on this partially. There are many problems, the application can be buildet, but whether it will work is a question. Parsing resource.arsc is very far from ideal and this vulnerability was using to breaking decompiling with apktool. First  steps it is [fixing](https://github.com/iBotPeaches/Apktool/issues/2422#issuecomment-739550862) bad attributes in package

**Comment by MrIkso** [comment]
In order not to make the war on defense even stronger, I will abandon this idea. For personal purposes, you can do this, but not for public
