### ISSUE TITLE
apktool: can't find apktool.jar

### ISSUE THREAD

**Issue by emirbyte** [iBotPeaches/Apktool#2457]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

yes.
there is no problem with the apk
no im using 2.4.1 but i cant even upgrade it i did apt remove apktool; apt install apktool but it didnt change anything. when i did apt remove apktool i checked it again to see if apktool is remved or not and typed apktool and it gave me the same error 'apktool: can't find apktool.jar'
please help me

**Comment by Surendrajat** [comment]
This means that this debian/ubuntu repository for apktool has not been updated yet. It's always a good idea to download the latest version from [github releases](https://github.com/iBotPeaches/Apktool/releases/latest) and follow [this guide](https://ibotpeaches.github.io/Apktool/install/) after removing the old apktool.

**Comment by iBotPeaches** [comment]
As mentioned above. I have no involvement with packaging systems. You'll want to grab the binary and follow our guide or wait for the packages to be updated.

Closing as support.

**Comment by ashimraj000** [comment]
I am also getting the same error in my kali linux machine

**Comment by iBotPeaches** [comment]
@ashimraj000 - you have an issue then unrelated to Apktool. Failing to launch apktool does not mean a bug for Apktool.

I'm locking this as well, since it was 3+ years old.
