### ISSUE TITLE
[BUG]decompiling it gives you Blacklist or Whitelist everywhere in smali in framework jars

### ISSUE THREAD

**Issue by sac23** [iBotPeaches/Apktool#2460]
### Information
1. **2.5** -
2. **Windows 10** -
3. **framework.jar from android 2.5** -

### Stacktrace/Logcat
C:\Users\sac23\Desktop>apktool d -b framework.jar
I: Using Apktool 2.5.0 on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

```

### Steps to Reproduce
1. `apktool d -b framework.jar `

### Frameworks
Samsung android 2.5

### APK
http://www.mediafire.com/file/rqayopj9oxq127x/framework.jar/file

decompiling it gives you Blacklist or Whitelist everywhere in smali please can u fix this issue thanks

it work perfect in 2.4.1

i think issue is in this class HiddenApiRestriction.class sir thank u

**Comment by shuajinanhai** [comment]
我能提个建议吗，因为apktool.jar也可以用在安卓手机上，我觉得您构建aapt时候也可以顺便构建安卓版的aapt

**Comment by sac23** [comment]
> 我能提个建议吗，因为apktool.jar也可以用在安卓手机上，我觉得您构建aapt时候也可以顺便构建安卓版的aapt

I don't know how to build it sir so I just wanted to let @iBotPeaches know this issue thank u very much

**Comment by sac23** [comment]
I can build apktool from source but I just tried 2.5.1 and still the same thanks for your help

**Comment by iBotPeaches** [comment]
Got error
```
➜  2460 apktool b framework.jar.out 
I: Using Apktool 2.5.1-d1c006-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
framework.jar.out/smali/android/R$attr.smali[3070,27] Hidden API restrictions are only supported on api 29 and above.
framework.jar.out/smali/android/R$attr.smali[3071,12] mismatched tree node: I_ORDERED_METHOD_ITEMS expecting I_FIELDS
Could not smali file: android/R$attr.smali
➜  2460
```

Since this is a far file with no resources, we cannot detect API version. So please pass it - 
```
➜  2460 apktool b framework.jar.out --api-level 29
I: Using Apktool 2.5.1-d1c006-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
W: Could not find resources
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2460 
```

Then it works fine. Closing.
