### ISSUE TITLE
invalid resource directory name: C:\Apk\AndroidKiller\projects\测试res_navigation\Project\res navigation

### ISSUE THREAD

**Issue by shuajinanhai** [iBotPeaches/Apktool#2466]
>I: Using Apktool 2.5.1-dirty
>I: Smaling smali folder into classes.dex...
>I: Smaling smali_classes2 folder into classes2.dex...
>I: Smaling smali_classes3 folder into classes3.dex...
>I: Smaling smali_classes4 folder into classes4.dex...
>I: Smaling smali_classes5 folder into classes5.dex...
>I: Smaling smali_classes6 folder into classes6.dex...
>I: Building resources...
>W: invalid resource directory name: C:\Apk\AndroidKiller\projects\测试res_navigation\Project\res navigation
> 28, --version-code, 31, --version-name, 1.17.0, --no-version-vectors, -F, C:\Users\wang\AppData\Local\Temp\APKTOOL7399277258113642455.tmp, -e, C:\Users\wang\AppData\Local\Temp\APKTOOL4911556236618947426.tmp, -0, arsc, -I, C:\Users\wang\AppData\Local\apkto 28, --version-code, 31, --version-name, 1.17.0, --no-version-vectors, -F, C:\Users\wang\AppData\Local\Temp\APKTOOL7399277258113642455.tmp, -e, C:\Users\wang\AppData\Local\Temp\APKTOOL4911556236618947426.tmp, -0, arsc, -I, C:\Users\wang\AppData\Local\apktool\framework\1.apk, -S, C:\Apk\AndroidKiller\projects\测试res_navigation\Project\res, -M, C:\Apk\AndroidKiller\projects\测试res_navigation\Project\AndroidManifest.xml]
APK 编译失败，无法继续下一步签名!

**Comment by iBotPeaches** [comment]
Use `--use-aapt2`.

**Comment by shuajinanhai** [comment]
>I: Smaling smali_classes5 folder into classes5.dex...
>I: Smaling smali_classes6 folder into classes6.dex...
>I: Building resources...
>W: unknown option '--forced-package-id'.
>W: 
>W: aapt2 [subcommand] [options] files...
>W: 
>W: Subcommands:
>W:  compile                                           Compiles resources to be linked into an apk.
>W:  link                                              Links resources into an apk.
>W:  dump                                              
>W:  diff                                              Prints the differences in resources of two apks.
>W:  optimize                                          Preforms resource optimizations on an apk.
>W:  convert                                           Converts an apk between binary and proto formats.
>W:  version                                           Prints the version of aapt.
>W:  daemon                                            Runs aapt in daemon mode. Each subsequent line is a single parameter to the
>W:                                                    command. The end of an invocation is signaled by providing an empty line.
>W: 
>W: Options:
>W:  -h                                                Displays this help menu
>brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\wang\AppData\Local\Temp\brut_util_Jar_71165821917343342393488484539239191886.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 28, --version-code, 31, --version-name, 1.17.0, --no-version-vectors, -F, C:\Users\wang\AppData\Local\Temp\APKTOOL8776729425399538637.tmp, -e, C:\Users\wang\AppData\Local\Temp\APKTOOL2185914170194419374.tmp, -0, arsc, -I, C:\Users\wang\AppData\Local\apktool\framework\1.apk, -S, C:\Apk\AndroidKiller\projects\测试res_navigation\Project\res, -M, C:\Apk\AndroidKiller\projects\测试res_navigation\Project\AndroidManifest.xml]
APK 编译失败，无法继续下一步签名!

**Comment by shuajinanhai** [comment]
I try try...
