### ISSUE TITLE
please build aapt for android

### ISSUE THREAD

**Issue by shuajinanhai** [iBotPeaches/Apktool#2470]
can you build aapt and aapt2 for android, so let a lot of Apps can Decompile and Build on android mobile phone， like MT管理器，and Apktool and mobile idea app, they need aapt to analytic apk
能否顺带编译出 aapt 和 aapt2 给安卓手机上用，这样很多app就可以直接在安卓手机上进行反编译和回编译了，就像MT管理器，手机版apktool，和idea手机版，这些都是需要aapt来解析应用

就是能否顺便编译出 arm、 arm64的aapt（aapt64）和aapt2（aapt2 _64）

**Comment by iBotPeaches** [comment]
Sorry no.

**Comment by hhhaiai** [comment]
@shuajinanhai @iBotPeaches  here has one plan.
https://github.com/JonForShort/android-tools

**Comment by TimScriptov** [comment]
@shuajinanhai https://github.com/rendiix/termux-aapt
