### ISSUE TITLE
Framework-res.apk - Emui 5 Huawei/Honor

### ISSUE THREAD

**Issue by 2Duky** [iBotPeaches/Apktool#2474]
Hello im not able to decompile Framework-res.apk or any other system apps of Huawei and Honor..
I did read that Huawei and Honor devices was not supported, but it was topics from 2017-2018.
I have installed last version of APKtool.

Logs etc:
Invalid config flags detected. Dropping resources: string-ERR5
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xE7030000.
and
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x010400aa string/needPuk, config=[DEFAULT]
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)

Can you please confirm me it still does not work with Huawei/Honor devices???
Is there any way how to decompile and recompile Emui 5 framework-res.apk???

I have Honor Note 8 and i have not any replacement for this device and this
amazing huge super amoled display. My battery is dead and i found battery to replace in China, but
i cant wait 2 months for delivery, so i bought battery for Honor Note 10, which is same dimension,
parameters, connector, except capacity which is 4900mAh indead of 4400mAh in my phone.
This caused that my phone wont to charge battery, i need at least temporary fix until i get original battery.
Thanks for your help!!!

**Comment by iBotPeaches** [comment]
> I did read that Huawei and Honor devices was not supported, but it was topics from 2017-2018.

Sadly still valid.

> Is there any way how to decompile and recompile Emui 5 framework-res.apk???

Build a plugin system so we can change qualifiers per OEM. See roadmap item - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#qualifier-plugin-system
