### ISSUE TITLE
[BLOCKER - 2.5.1] AAPT not usable on macOS

### ISSUE THREAD

**Issue by kotori2** [iBotPeaches/Apktool#2477]
### Information
1. **Apktool Version (`apktool -version`)** 2.5.0
2. **Operating System (Mac, Linux, Windows)** macOS 11.1
3. **APK From? (Playstore, ROM, Other)** Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: dyld: Library not loaded: @rpath/libc++.dylib
W:   Referenced from: /var/folders/5l/f30qm99143n7lf9dd1_pb5v40000gn/T/brut_util_Jar_22487465168643078285790281712635730641.tmp
W:   Reason: image not found
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/5l/f30qm99143n7lf9dd1_pb5v40000gn/T/brut_util_Jar_22487465168643078285790281712635730641.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 29, --version-code, 308001336, --version-name, 8.0.1, --no-version-vectors, -F, /var/folders/5l/f30qm99143n7lf9dd1_pb5v40000gn/T/APKTOOL3306739641509490829.tmp, -e, /var/folders/5l/f30qm99143n7lf9dd1_pb5v40000gn/T/APKTOOL2214957322552063658.tmp, -0, arsc, -I, /Users/kotori0/Library/apktool/framework/1.apk, -S, /[REDACTED]/input/res, -M, /[REDACTED]/input/AndroidManifest.xml]
```

### Steps to Reproduce
1. decompile anything with `apktool d xxx.apk`
2. recompile with `java -jar apktool.jar b xxx -o out.apk`

### Frameworks
N/A

### APK
Not related, can reproduce with any apk.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? yes

`libc++.dylib` is actually not exist. I have Xcode and command line tools installed. 
Also found [this](https://developer.apple.com/forums/thread/652999) on Apple forum so I'm not sure if it's an Apple's bug. 
```
% ls /usr/lib
charset.alias			libpython2.7.dylib
cron				libstdc++.6.dylib
dsc_extractor.bundle		libstdc++.dylib
dtrace				log
dyld				pam
groff				php
libLeaksAtExit.dylib		pkgconfig
libMTLCapture.dylib		python2.7
libffi-trampolines.dylib	rpcsvc
libgmalloc.dylib		ruby
libhunspell-1.2.0.dylib		sasl2
libhunspell-1.2.dylib		sqlite3
libiodbc.2.dylib		swift
libiodbc.dylib			system
libiodbcinst.2.dylib		updaters
libiodbcinst.dylib		xpc
libobjc-trampolines.dylib	zsh
libpython.dylib
```
Also I tried to execute `aapt_64` and got same result
```
% ./aapt_64
dyld: Library not loaded: @rpath/libc++.dylib
  Referenced from: /Users/kotori0/code/PLC801/apktool/prebuilt/macosx/./aapt_64
  Reason: image not found
zsh: abort      ./aapt_64
```
While aapt2 seems working.

**Comment by iBotPeaches** [comment]
May you run `otool -L aapt_64` and `otool -L aapt2_64` against those two files and attach output?

**Comment by kotori2** [comment]
```
% otool -L aapt_64
aapt_64:
	@rpath/libc++.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
% otool -L aapt2_64
aapt2_64:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

**Comment by kotori2** [comment]
Just for reference, a normal binary compiled by myself will looks like this:
```
xxx:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
```
However `/usr/lib/libc++.1.dylib` doesn't even exist as well on my machine as well, but this binary actually works. I think it's some Apple magic?

**Comment by iBotPeaches** [comment]
Looks like I can't rebuild mac at this time, so this will have to wait. HTTP/2 is causing some major issues for me.

> RPC failed: HTTP 499 curl 16 Error in HTTP2 framing layer

https://github.com/curl/curl/issues/3750 https://github.com/curl/curl/issues/4267

Possibly related.

**Comment by iBotPeaches** [comment]
This is the last ticket before 2.5.1 is sliced and still having troubles building Mac binary. They are making this very tough to build platform/build tools on Mac.

**Comment by iBotPeaches** [comment]
Hmm still not static. Re-opening.

**Comment by iBotPeaches** [comment]
Okay confirmed new binaries are static.

```
➜  macosx git:(aapt1-static-mac) otool -L *
aapt2_64:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
aapt_64:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
➜  macosx git:(aapt1-static-mac) 
```
