### ISSUE TITLE
[BUG] apktool not working in kali amd_64 , unable to Re-build apk.

### ISSUE THREAD

**Issue by just-hack** [iBotPeaches/Apktool#2478]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1-dirty
2. **Operating System (Mac, Linux, Windows)** - linux
3. **APK From? (Playstore, ROM, Other)** - flappybird from apkmirror.com
4. Dear sir, apktool has been not working in kali linux from past two days, kindly solve this issue sir. i have attached  below the error i got in building apk , its simple apk flappy bird which earlier was suppose to build now while recompiling it throwback this error also i have attach some more info you would need to solve the issue. eagerly waiting for you to solve this issue
5. The error i got in building
6. kali@kali:~$ apktool b -f -r com.dotgears.flappybird-1.3-4-minAPI8/
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty
I: Smaling smali folder into classes.dex...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [aapt, p, --min-sdk-version, 8, --target-sdk-version, 15, --version-code, 4, --version-name, 1.3, --no-version-vectors, -F, /tmp/APKTOOL2362264044049074793.tmp, -0, resources.arsc, -0, png, -0, ogg, -0, arsc, -I, /home/kali/.local/share/apktool/framework/1.apk, -S, /home/kali/com.dotgears.flappybird-1.3-4-minAPI8/res, -M, /home/kali/com.dotgears.flappybird-1.3-4-minAPI8/AndroidManifest.xml]
W: aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libbacktrace.so.0: undefined symbol: _ZN11unwindstack12ElfInterfaceD2Ev

![Screenshot 2020-12-17 01:10:15](https://user-images.githubusercontent.com/69382688/102451125-e96a3d00-4005-11eb-80ac-9b311f1344cb.png)

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? -- Yes still not working 
2. If you are trying to install a modified apk, did you resign it? -- apk has not build
3. Are you using the latest apktool version? -- 2.4.1

**Comment by iBotPeaches** [comment]
This looks identical to https://github.com/iBotPeaches/Apktool/issues/2479

I don't have anything to do with the kali distribution.

**Comment by just-hack** [comment]
Sir is there any lib or dependicies wich apktool need to perform?? Because in old system it doesn't throw any error, I this error just pop up on new system please can u help??
