### ISSUE TITLE
[BUG]Apktool unable to rebuild apk

### ISSUE THREAD

**Issue by Bhaviktutorials** [iBotPeaches/Apktool#2479]
### Information
1. **Apktool 2.4.1-dirty Version** -
2. **Operating System Linux(kali linux 2020.4) latest** -
3. **game apk [Flappy Bird](https://www.apkmirror.com/apk/gears-studios/flappy-bird/flappy-bird-1-3-release/flappy-bird-1-3-android-apk-download/)** -

![Screenshot 2020-12-17 20:30:07](https://user-images.githubusercontent.com/64035221/102504514-f3904800-40a6-11eb-94b8-4636e4c0c19f.png)

### Stacktrace/Logcat

```
┌──(toor㉿kali)-[~/Desktop]
└─$ apktool b new                                                      1 ⨯
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [aapt, p, --min-sdk-version, 8, --target-sdk-version, 15, --version-code, 4, --version-name, 1.3, --no-version-vectors, -F, /tmp/APKTOOL5100030591731871744.tmp, -0, resources.arsc, -0, png, -0, ogg, -0, arsc, -I, /home/toor/.local/share/apktool/framework/1.apk, -S, /home/toor/Desktop/new/res, -M, /home/toor/Desktop/new/AndroidManifest.xml]
W: aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libbacktrace.so.0: undefined symbol: _ZN11unwindstack12ElfInterfaceD2Ev
                                                                          
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Not sure here. I can't replicate this on my linux builds, albeit not kali.

I assume kali is doing something in in their custom 2.4.1-dirty build, I don't know who handles packaging/maintaining and I sure don't know how to begin to contribute to that.

Sorry!
