### ISSUE TITLE
[BUG] Failed Build apktool, Rebuild any apk [exit code = -1073741795]

### ISSUE THREAD

**Issue by MSalah02** [iBotPeaches/Apktool#2480]
### Information
1. **Apktool Version (`apktool -version`)** -[ 2.5.0, 2.5.1-6d4e50-SNAPSHOT,Apktool 2.5.1-e25c0f-SNAPSHOT]
2. **Operating System (Mac, Linux, Windows)** -windows 10 20h2(19042.685) x64 , AMD Athlon(tm) II X2 B24 Processor
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\JZT\AppData\Local\Temp\brut_util_Jar_29891305500900886043695334746966348946.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 29, --version-code, 50700, --version-name, 5.7, --no-version-vectors, -F, C:\Users\JZT\AppData\Local\Temp\APKTOOL8737544248359709303.tmp, -e, C:\Users\JZT\AppData\Local\Temp\APKTOOL1976923015154099185.tmp, -0, arsc, -I, C:\Users\JZT\AppData\Local\apktool\framework\1.apk, -S, E:\JZT_2.6.2\2-DEC\Mr Bullet 5.7.apk\res, -M, E:\JZT_2.6.2\2-DEC\Mr Bullet 5.7.apk\AndroidManifest.xml]
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Failed Rebuild any apk giving exit code = -1073741795

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes, same issue
2. If you are trying to install a modified apk, did you resign it? can't rebuild
3. Are you using the latest apktool version?yes [ 2.5.0, 2.5.1-6d4e50-SNAPSHOT,Apktool 2.5.1-e25c0f-SNAPSHOT]
The test.zip includes the failed building apktool .
[test.zip](https://github.com/iBotPeaches/Apktool/files/5711497/test.zip)
only Apktool v2.4.2-a2a794-SNAPSHOT (13septemper2020) works with this version of windows (20H2), all other versions works with previous versions of windows 10 x64 with no problem.

**Comment by iBotPeaches** [comment]
I can't replicate this. Our windows tests are passing and so is my machine. 

Sorry!
