### ISSUE TITLE
Rebuilding this APK fails to install on android

### ISSUE THREAD

**Issue by blinkok** [iBotPeaches/Apktool#2482]
Versions: 2.5.0 and 2.4.0
Unpacking and rebuilding this .apk and trying to install on android produces the following error;
"The package appears to be corrupt"
Note: Renamed .apk to .zip to upload
[phone.zip](https://github.com/iBotPeaches/Apktool/files/5722385/phone.zip)

**Comment by Surendrajat** [comment]
@blinkok Did you sign this apk before installing it?

**Comment by blinkok** [comment]
Ok, i'm fairly new to this.
I downloaded and installed this directly, not through the play store. Do i need to sign it?
If so how do i do that?
Thanks you very much for your help

**Comment by Surendrajat** [comment]
@blinkok I'm talking about the apk you rebuilt using apktool. You need to sign it before installing. One easy way to do it is by using https://github.com/patrickfav/uber-apk-signer.
Also, you could use https://github.com/Surendrajat/APKLab which uses apktool and uber-apk-signer under-the-hood (Disclaimer: I'm the author of it).

**Comment by blinkok** [comment]
Ok thanks. I will try that

**Comment by iBotPeaches** [comment]
Looks like the signature was removed and not restored as mentioned above. Closing as support.

**Comment by blinkok** [comment]
Do you know if there is a simple, windows based signer that doesn't require downloading the android sdk?
Like this android app https://play.google.com/store/apps/details?id=com.haibison.apksigner

**Comment by FaolanX** [comment]
> Do you know if there is a simple, windows based signer that doesn't require downloading the android sdk?
> Like this android app https://play.google.com/store/apps/details?id=com.haibison.apksigner

APK Easy Tool

**Comment by blinkok** [comment]
Thank you
