### ISSUE TITLE
[BUG] apktool decode problem with 2.5.0

### ISSUE THREAD

**Issue by NgoHuy** [iBotPeaches/Apktool#2483]
### Information
1. **Apktool Version (`apktool -version`)** -
2.5.0
2. **Operating System (Mac, Linux, Windows)** -
Arch Linux
3. **APK From? (Playstore, ROM, Other)** -
Playstore
### Stacktrace/Logcat

```
W: /home/user/com.fastacash.tcb-bF0c5qBrYwkE5fiQyRJ60Q==/base/res/values/layouts.xml:3: error: Found tag layo
ut where item is expected                                                                                                           
W:                                                                                                                                  
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_27525427689490841424
581261023464337030.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 29, --version-code, 2020121617, --
version-name, 1.2.0.4, --no-version-vectors, -F, /tmp/APKTOOL10491740517983424782.tmp, -e, /tmp/APKTOOL1304907069421335968.tmp, -0, 
arsc, -I, /home/user/.local/share/apktool/framework/1.apk, -S, /home/user/com.fastacash.tcb-bF0c5qBrYwkE5fi
QyRJ60Q==/base/res, -M, /user/com.fastacash.tcb-bF0c5qBrYwkE5fiQyRJ60Q==/base/AndroidManifest.xml
```

### Steps to Reproduce
1. apktool d base.apk
2. In version: 2.4.1 the xml was decoded as
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item type="layout" name="APKTOOL_DUMMY_78">false</item>
</resources>
```

But in the new 2.5.0 version
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <layout name="APKTOOL_DUMMY_78" />
</resources>
```

and it occured error when I rebuilt it.
If I use -r flag when decode with new version, I built it successfully, but cannot install.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
yes

**Comment by iBotPeaches** [comment]
This is intentional and the change was required by the changing restrictions in aapt2. Give it a shot with aapt2 (--use--aapt2)
