### ISSUE TITLE
i want to recompile the manifest.xml only without changing resource.

### ISSUE THREAD

**Issue by whitehat9090** [iBotPeaches/Apktool#2486]
hello
i want to recompile the manifest.xml only without changing resource.
is it possible?
help me!

**Comment by aniruddha-ga** [comment]
Search about aapt2 
which is used to decompile and recompile xml files

**Comment by iBotPeaches** [comment]
> is it possible?

No. We need resources to properly decode the manifest.

**Comment by whitehat9090** [comment]
> Search about aapt2
> which is used to decompile and recompile xml files

Can you tell me the method how to encoding the manifest only by using aapt2?
Thank you
