### ISSUE TITLE
Some APKs can't be recompiled how to fix showing APKTOOL_DUPLICATE

### ISSUE THREAD

**Issue by aniruddha-ga** [iBotPeaches/Apktool#2487]
Here is log

C:\Users\user\Desktop\Apk edits>java -Xmx4096m -jar apktool-cli-all.jar b AppCloner.apk-decompiled --use-aapt2
I: Using Apktool 2.5.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060001.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060001.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060002.xml:1: error: syntax error.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060002.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060003.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060003.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060005.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060005.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060006.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060006.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060008.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060008.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060009.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f060009.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000a.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000a.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000b.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000b.xml: error: file failed to compile.
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000c.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res\color\APKTOOL_DUPLICATE_color_0x7f06000c.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_69585806908182260031629134279194287701.tmp, compile, --dir, C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\res, --legacy, -o, C:\Users\user\Desktop\Apk edits\AppCloner.apk-decompiled\build\resources.zip]

**Comment by iBotPeaches** [comment]
Those resources have the same name, so when we decode it we make a string of a random name. Not sure why it is failing there though, I don't see any reserved characters.

Without apk - not much I can do here. Happy holidays.

**Comment by aniruddha-ga** [comment]
If you need apks which shows these errors [here](https://apkcombo.com/np%E7%AE%A1%E7%90%86%E5%99%A8/player.normal.np/download/apk)   [you can download](https://applisto.com/appcloner/download/AppCloner-2.9.3-20122015.apk)
