### ISSUE TITLE
[BUG] apktool starting bug on cmd

### ISSUE THREAD

**Issue by skgotjd** [iBotPeaches/Apktool#2489]
![1](https://user-images.githubusercontent.com/76676003/103191370-1678f280-4918-11eb-9e27-283704e7e187.png)
![2](https://user-images.githubusercontent.com/76676003/103191372-17aa1f80-4918-11eb-8a1c-8ccdbab804c0.png)
![3](https://user-images.githubusercontent.com/76676003/103191374-17aa1f80-4918-11eb-81b6-6a123bf71765.png)
![4](https://user-images.githubusercontent.com/76676003/103191418-432d0a00-4918-11eb-9b50-d21f9c77173c.png)

I was trying to run apktool on cmd, but error message keeps coming up
i placed apktool.bat apktool.jar on C:\Windows, and added path then typed apktool on cmd, then cmd says
The filename, directory name, or volume label syntax is incorrect
I've been looking for this answer for 2days but couldn't find anything..
help me plz...[](url)

**Comment by pashamcr** [comment]
@skgotjd why you have a crossed out "W" in your paths, there must be a ''\\", most likely this is a Windows system error

**Comment by iBotPeaches** [comment]
Yeah not sure what all those W paths are, but that doesn't look valid to me. This isn't a bug, but support.
