### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fagex** [iBotPeaches/Apktool#2493]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.1
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat
...
fakeLogOpen(/dev/log_stats) failed

```
Include stacktrace here
```

### Steps to Reproduce
1. java.exe -jar apktool2.4.1.jar b -o  a.apk c:\a_decompile

This happens when multiple commands are running at the same time

**Comment by iBotPeaches** [comment]
I can't replicate this.
