### ISSUE TITLE
[BUG] App crashes after de- and recompiling with no changes when resources are decompiled

### ISSUE THREAD

**Issue by Autissima** [iBotPeaches/Apktool#2494]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
C:\Users\##\Desktop\ApkExtraction\NEW AD ATTEMPT>apktool d --no-src AD.apk
I: Using Apktool 2.5.0 on AD.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\##\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\##\Desktop\ApkExtraction\NEW AD ATTEMPT>apktool b --no-src AD
I: Using Apktool 2.5.0
I: Copying AD classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. Decompile the apk
2. Recompile
3. Install
4. Run

Here is what ADB showed me, I filtered by the process ID
https://paste.ee/p/gL2G6

If I used apktool d --no-res it worked.

I don't want to be annoying, I'm very sorry if this is not apktool at fault, but I am all out of ideas, and seeing as not decompiling the resources works...

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://drive.google.com/file/d/1HjTYIm-m5p0rsNYGgOOddvQ2rfOptNbr/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - Yes
3. Are you using the latest apktool version? - Yes

**Comment by pashamcr** [comment]
@Autissima try replacing `&lt;` with `<` in all res/values​​*/plurals.xml

**Comment by Autissima** [comment]
Oh god, thank you very much you're a lifesaver.

Just wondering, did I do something wrong when decompiling or was the `<` on part of apktool?
