### ISSUE TITLE
apk no installed

### ISSUE THREAD

**Issue by kalmen26** [iBotPeaches/Apktool#2497]
### Information
1. **Apktool Version (`apktool -2.5.0`)** -
2. **Operating System (Windows)** -
3. **APK From? (other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Hello

I am modifying the apps of a Chinese android mtk, I managed to do it with several apps and everything turned out fine,

now as soon as I want to modify contacts.apk decompile and compile and sign everything perfect, when installing the apk, I get an app not installed, even without modifying anything, just decompile and compile and I get the same error

Could it be that it has to do with unknown folder that appears when I decompile this apk? because with others it doesn't happen like that.

**Comment by kalmen26** [comment]
> ### Information
> 1. **Apktool Version (`apktool -2.5.0`)** -
> 2. **Operating System (Windows)** -
> 3. **APK From? (other)** -
> 
> ### Stacktrace/Logcat
> ```
> Include stacktrace here
> ```
> 
> ### Steps to Reproduce
> 1. `apktool `
> 
> ### Frameworks
> If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
> (`.apks` that live in `/system/framework` or `/system/priv-app`)
> 
> ### APK
> If this APK can be freely shared, please upload/attach a link to it.
> 
> ### Questions to ask before submission
> 1. Have you tried `apktool d`, `apktool b` without changing anything?
> 2. If you are trying to install a modified apk, did you resign it?
> 3. Are you using the latest apktool version?
> 
> Hello
> 
> I am modifying the apps of a Chinese android mtk, I managed to do it with several apps and everything turned out fine,
> 
> now as soon as I want to modify contacts.apk decompile and compile and sign everything perfect, when installing the apk, I get an app not installed, even without modifying anything, just decompile and compile and I get the same error
> 
> Could it be that it has to do with unknown folder that appears when I decompile this apk? because with others it doesn't happen like that.

**Comment by pashamcr** [comment]
@kalmen26 how is this question related to apktool? You tell apktool worked perfectly. This can be seen from the log that you "provided" ;->

**Comment by iBotPeaches** [comment]
> Could it be that it has to do with unknown folder that appears when I decompile this apk? because with others it doesn't happen like that.

Well you are entering the world of reverse-engineering and not only that, but recompilation with running on a host device. Who knows what the issue could be. I do know there is not enough to go on here though and borders the line between support and bug.

Closing.

**Comment by kalmen26** [comment]
no, I tell you that if I install the app without decompiling, everything is fine,
but if I decompile and compile again, although I don't modify anything, the app doesn't work,
it means that the problem comes when decompiling and compiling

**Comment by pashamcr** [comment]
@kalmen26 I tell you again: apktool is not to blame for the fact that you do not understand the essence of recompiling system applications, system apk from the firmware must retain the original signature, this is achieved by other tools.

**Comment by kalmen26** [comment]
I had to find out and they told me I can fix it this way apktool -c
Does it bother you a lot to help others and say this solution?
