### ISSUE TITLE
[BUG] Baksmaling framework.jar fails since Apktool 2.5.0

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#2499]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0 and 2.5.1-snapshot
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64, Debian 10
3. **APK From? (Playstore, ROM, Other)** - Android 11 ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.5.0 on framework.jar
I: Baksmaling classes.dex...


Error occurred while disassembling class Landroid.Manifest$permission_group; - skipping class


Error occurred while disassembling class Landroid.R$animator; - skipping class


Error occurred while disassembling class Landroid.Manifest$permission; - skipping class


Error occurred while disassembling class Landroid.R$anim; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.jf.dexlib2.HiddenApiRestriction.getAllFlags(HiddenApiRestriction.java:111)
	at org.jf.dexlib2.dexbacked.DexBackedField.getHiddenApiRestrictions(DexBackedField.java:141)
	at org.jf.baksmali.Adaptors.FieldDefinition.writeTo(FieldDefinition.java:65)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeStaticFields(ClassDefinition.java:207)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:110)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

...
```
(extremely long to include here)

### Steps to Reproduce
Just try to decompile the linked untouched framework.jar from an Android 11 ROM with Apktool 2.5.0, you'll get some amusing, long output full of errors.
The thing is, it works fine with any Apktool prior to 2.5.0.
I also tried a framework.jar from an Android 10 ROM, that one works fine, so it's just Android 11 where the issue happens.

### Sample
https://drive.google.com/file/d/14aRh2J93GO1SgNcpQPXph9nRiftKRb2K/view

**Comment by MrIkso** [comment]
Yes, issues created on smali project
https://github.com/JesusFreke/smali/issues/798 but, not fixed.

**Comment by iBotPeaches** [comment]
Upstream issue. Marking with smail.

**Comment by IgorEisberg** [comment]
Yup, rolling back the dependencies seems to solve this for now.
```
baksmali: 'org.smali:baksmali:2.3.4',
smali: 'org.smali:smali:2.3.4',
```

**Comment by iBotPeaches** [comment]
```
➜  2499 apktool d framework.jar 
I: Using Apktool 2.5.1-71f547-SNAPSHOT on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2499 
➜  2499 apktool b framework.jar.out 
I: Using Apktool 2.5.1-71f547-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
framework.jar.out/smali/android/R$array.smali[35,27] Hidden API restrictions are only supported on api 29 and above.
framework.jar.out/smali/android/R$array.smali[36,4] mismatched tree node: I_LOCALS expecting I_FIELDS
Could not smali file: android/R$array.smali
➜  2499 apktool b framework.jar.out --api-level 29
I: Using Apktool 2.5.1-71f547-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
W: Could not find resources
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2499 
```

Looks like you'll need to specify api version since we couldn't automatically determine it. Marking as resolved in upcoming build.

**Comment by behind80** [comment]
> ```
> ➜  2499 apktool d framework.jar 
> I: Using Apktool 2.5.1-71f547-SNAPSHOT on framework.jar
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Baksmaling classes3.dex...
> I: Baksmaling classes4.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> ➜  2499 
> ➜  2499 apktool b framework.jar.out 
> I: Using Apktool 2.5.1-71f547-SNAPSHOT
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> framework.jar.out/smali/android/R$array.smali[35,27] Hidden API restrictions are only supported on api 29 and above.
> framework.jar.out/smali/android/R$array.smali[36,4] mismatched tree node: I_LOCALS expecting I_FIELDS
> Could not smali file: android/R$array.smali
> ➜  2499 apktool b framework.jar.out --api-level 29
> I: Using Apktool 2.5.1-71f547-SNAPSHOT
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes3 folder into classes3.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes4 folder into classes4.dex...
> W: Could not find resources
> I: Building apk file...
> I: Copying unknown files/dir...
> I: Built apk...
> ➜  2499 
> ```
> 
> Looks like you'll need to specify api version since we couldn't automatically determine it. Marking as resolved in upcoming build.

java -jar smali-2.5.2.jar a -a 29 -o classes3.dex out3
