### ISSUE TITLE
Error in multiple substitutions check...

### ISSUE THREAD

**Issue by BurgerZ** [iBotPeaches/Apktool#25]
Hi!
Try to decompile and compile back these apks (Phone.apk and PIM.apk) from LeWa OS:
http://www.mediafire.com/?hnmexasxme2tg6y

1. Phone.apk
 
\Phone\res\values-zh-rTW\strings.xml:202: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?

There is a single "%" symbol in that line (like 78%). Apktool 1.4.2 can handle it without errors.

2. PIM.apk

\PIM\res\layout\act_edit.xml:8: error: Error: No resource found that matches the given name (at 'background' with value '@*android:drawable/item_background_holo_dark_left').
etc.

Again, new apktool can't handle some xmls. 1.4.2 version recompiles this apk w/o errors.

**Comment by iBotPeaches** [comment]
Closing before merge of GoogleCode issues.
