### ISSUE TITLE
[BUG] Using `\` in AndroidManifest.xml, data could be tampered with

### ISSUE THREAD

**Issue by LiarrDev** [iBotPeaches/Apktool#2500]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1 and 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64
3. **APK From? (Playstore, ROM, Other)** - Other

### Steps to Reproduce
1. `apktool b xxx.apk`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? Yes.
3. Are you using the latest apktool version? Yes.

### Issue

I wanna use a backslash `\` in AndroidManifest.xml like so

```XML
<meta-data
    android:name="data_name"
    android:value="\1234567890123456789" />
```

However, after I built apk file it tampered with the data like so

```XML
<meta-data
    android:name="data_name"
    android:value="\ 234567890123456789" />
```

**Comment by iBotPeaches** [comment]
This is intentional to trick Android into treating it as a string, vs overflow as an int. I don't see changing this.
