### ISSUE TITLE
[FEAT] Make apk builds reproducible

### ISSUE THREAD

**Issue by mimi89999** [iBotPeaches/Apktool#2502]
Hello,
If I run `apktool b` twice on the same machine with the same source code, the resulting apks will be different. I think that it would benefit greatly some of apktool users if the resulting apk were the same. I started inspecting the apk and the first difference I noticed is that `last modified date` of entries in the apk is always set to the current time of the build. Android apks have the date set to a fixed value that does not depend on the date of the build.

**Comment by iBotPeaches** [comment]
> would benefit greatly some of apktool users if the resulting apk were the same.

If it was that easy, but that is not the case. We have to use tools like aapt/smali/baksmali/aapt2 which will not generate the same file over n over. 

Closing for the feature request, which is already being tracked here - https://github.com/iBotPeaches/Apktool/issues/2143

**Comment by mimi89999** [comment]
While the other issue is similar, it's not the same.
> Okay, I did some investigation and we could probably do this by recording the LastModified time of files during read, then re-set them back to that value after writing zip file.

I don't care about the original date. You can use the same values Android tools are using or even choose an arbitrary one for apktool. With that approach there would also be issues when a new file is added.

This issue is also about any other things that might case nondeterminism.

**Comment by r6680jc** [comment]
@iBotPeaches 
What about this:
https://github.com/KittyHawkCorp/stripzip
Maybe you can incorporate this to apktool?
