### ISSUE TITLE
[BUG] invalid package ID 0x01. Must be in the range 0x7f-0xff..

### ISSUE THREAD

**Issue by dumle11** [iBotPeaches/Apktool#2503]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Same on all 3, tested on Windows, Linux and Mac
3. **APK From? (Playstore, ROM, Other)** - Stock ROM for Alldocube iPlay 30

### Stacktrace/Logcat

```
root@dMe:/mnt/e# java -jar apktool_2.5.0.jar d framework-res.apk --use-aapt2
I: Using Apktool 2.5.0 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

root@dMe:/mnt/e# java -jar apktool_2.5.0.jar b framework-res --use-aapt2
I: Using Apktool 2.5.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: error: invalid package ID 0x01. Must be in the range 0x7f-0xff..
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1733501279999439899848001132792844792.tmp, link, -o, /tmp/APKTOOL9797823588068534639.tmp, --package-id, 1, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 29, --version-name, 10, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -x, -e, /tmp/APKTOOL1126151149898017191.tmp, -0, arsc, --manifest, /mnt/e/framework-res/AndroidManifest.xml, /mnt/e/framework-res/build/resources.zip]
```

### Steps to Reproduce
1. `java -jar apktool_2.5.0.jar if framework-res.apk`
2. `java -jar apktool_2.5.0.jar if mediatek-res.apk`
3. `java -jar apktool_2.5.0.jar d framework-res.apk --use-aapt2`
4. `java -jar apktool_2.5.0.jar b framework-res --use-aapt2`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/5880272/framework-res.zip)
[mediatek-res.zip](https://github.com/iBotPeaches/Apktool/files/5880274/mediatek-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Not sure what is going on there. You don't have the proper aapt2 patch - You can see clearly in my version of aapt2 we ignore this at this diff - https://github.com/iBotPeaches/platform_frameworks_base/blob/master/tools/aapt2/cmd/Link.cpp#L2263

```
➜  2503 apktool d framework-res.apk 
I: Using Apktool 2.5.1-d1c006-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2503 apktool b framework-res --use-aapt2
I: Using Apktool 2.5.1-d1c006-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warn: invalid package ID 0x01. Must be in the range 0x7f-0xff. Ignoring....
```

Now I did add new binaries after 2.5.0 here - https://github.com/iBotPeaches/Apktool/commit/d1c006b260f79c56b07566402f8f8c5607ff734d, so I'm going to mark this as already resolved in upcoming 2.5.1 release.

**Comment by dumle11** [comment]
Thanks for the reply. I have tried apktool 2.5.1 from master and from `d1c006b`. It now skips this check, but fails on the next part:
```
C:\Users\dMe\Desktop\Apktool\brut.apktool\apktool-cli\build\libs>java -jar apktool-cli-all.jar d E:\framework-res.apk
I: Using Apktool 2.5.1-d1c006-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\dMe\Desktop\Apktool\brut.apktool\apktool-cli\build\libs>java -jar apktool-cli-all.jar b framework-res --use-aapt2
I: Using Apktool 2.5.1-d1c006-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warn: invalid package ID 0x01. Must be in the range 0x7f-0xff. Ignoring....
W: brut_util_Jar_32370141877314231238117774743100399466.tmp F 01-30 14:19:33  9636  5304 PrivateAttributeMover.cpp:84] Check failed: priv_attr_type->entries.empty()
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073740791): [C:\Users\dMe\AppData\Local\Temp\brut_util_Jar_32370141877314231238117774743100399466.tmp, link, -o, C:\Users\dMe\AppData\Local\Temp\APKTOOL3508680140808951272.tmp, --package-id, 1, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 29, --version-name, 10, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -x, -e, C:\Users\dMe\AppData\Local\Temp\APKTOOL2945910705051605782.tmp, -0, arsc, --manifest, C:\Users\dMe\Desktop\Apktool\brut.apktool\apktool-cli\build\libs\framework-res\AndroidManifest.xml, C:\Users\dMe\Desktop\Apktool\brut.apktool\apktool-cli\build\libs\framework-res\build\resources.zip]
```

After doing some research, I found this issue https://github.com/iBotPeaches/Apktool/issues/1668 which seems to be the same problem, if I am not mistaken? Sorry for re-opening this issue, but wasn't sure if I should open up a new one. Do I have to rebuild aapt2 with some changes, for it to treat private attributes differently?

**Comment by iBotPeaches** [comment]
I'll take another look.

**Comment by pashamcr** [comment]
@dumle11 why are you using the old build d1c006 3 Dec 2020?
The patch that fixes the problem `Check failed: priv_attr_type->entries.empty()` published 4 Dec 2020 [https://github.com/iBotPeaches/platform_frameworks_base/commit/dab7c3e0f7c499d7eb0c850dd937191d017fe379](https://github.com/iBotPeaches/platform_frameworks_base/commit/dab7c3e0f7c499d7eb0c850dd937191d017fe379) .
Are you doing this on purpose?

**Comment by dumle11** [comment]
> 
> 
> @dumle11 why are you using the old build d1c006 3 Dec 2020?
> The patch that fixes the problem `Check failed: priv_attr_type->entries.empty()` published 4 Dec 2020 [iBotPeaches/platform_frameworks_base@dab7c3e](https://github.com/iBotPeaches/platform_frameworks_base/commit/dab7c3e0f7c499d7eb0c850dd937191d017fe379) .

That would require me to re-build aapt2 binaries? I am building apktool from source and it includes pre-build binaries that don't have this patch. Is this correct?

**Comment by pashamcr** [comment]
@dumle11
Yes, you're right, aapt2 is still used without this patch.

**Comment by dumle11** [comment]
@pashamcr first of all, sorry for taking so long to reply. Didn't have time for the past 2 days and started downloading AOSP yesterday, but didn't finish. 

I have tested the binaries you have provided and now I can confirm I can successfully rebuild the framework-res. Thanks a milion for your help and have a nice week guys!

**Comment by RDPCoder** [comment]
> @pashamcr first of all, sorry for taking so long to reply. Didn't have time for the past 2 days and started downloading AOSP yesterday, but didn't finish.
> 
> I have tested the binaries you have provided and now I can confirm I can successfully rebuild the framework-res. Thanks a milion for your help and have a nice week guys!

I also have the same situation as you, although I used the latest version of apktool (2.6.1), but the problem still occurs, can you provide me with the binary file that solves this problem
