### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by johnjacob10** [iBotPeaches/Apktool#2504]
[The issue template mentioned on https://ibotpeaches.github.io/Apktool/contribute/ does not link, so I could not use it].
**Information**
**Apktool Version**: 2.5.0
**Operating System**: Tried Centos 7 and Ubuntu 20.04.
**APK From?**: OpenGapps (Google Play Store APK)

I consistently get this error just rebuilding the APK without making any changes. I tried several versions of apktool, and hit the same issue each time. I've attached a script that downloads the APK and reproduces the issue.

**Stacktrace/Logcat**
```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_22331353039922968304304641883857725150.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 82371110, --version-name, 23.7.11-21 [0] [PR] 352600257, --no-version-vectors, -F, /tmp/APKTOOL7682094809676514826.tmp, -e, /tmp/APKTOOL6496528476982564118.tmp, -0, arsc, -I, /home/johnjaco/.local/share/apktool/framework/1.apk, -S, /tmp/apktoolFfN8/Phonesky/./res, -M, /tmp/apktoolFfN8/Phonesky/./AndroidManifest.xml]
```

**Steps to Reproduce**
1. Decompile the APK with apktool d.
2. Recompile the APK with apktool b.
Here is a script to reproduce the issue. It uses wget to download the APK.
```
#!/bin/bash
TMPDIR=`mktemp -d apktoolXXXX` || exit 1
pushd "${TMPDIR}"
wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar || exit 1
mkdir zipdir
pushd zipdir
wget https://netactuate.dl.sourceforge.net/project/opengapps/arm64/20210127/open_gapps-arm64-10.0-pico-20210127.zip || exit 1
unzip open_gapps-arm64-10.0-pico-20210127.zip
tar -xvf Core/vending-arm.tar.lz -C .
mv vending-arm/nodpi/priv-app/Phonesky/Phonesky.apk ../
popd
rm -rf zipdir
java -jar apktool_2.5.0.jar d Phonesky.apk
pushd Phonesky
java -jar ../apktool_2.5.0.jar b .
popd
popd
rm -rf ${TMPDIR}
```

**Frameworks**
N/A

**APK**
Google Play Store APK extracted from OpenGapps.

**Questions to ask before submission**
1. Have you tried apktool d, apktool b without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? yes

**Comment by MarcusXavierr** [comment]
I've this same issue using ubuntu 18.04. I don't know how to solve this

**Comment by iBotPeaches** [comment]
There is not really an error with your crash, just that aapt failed to work. Try executing it on your own - does it work? 

I don't really have anything to go on here, sorry.

---

> [The issue template mentioned on https://ibotpeaches.github.io/Apktool/contribute/ does not link, so I could not use it].

fixed thanks - https://github.com/iBotPeaches/Apktool/commit/d2fa4049fa6fd5637ed0943a59252ea35cb00fa8

**Comment by liuyewang** [comment]
I've this same issue using ubuntu 18.04. I don't know how to solve this
