### ISSUE TITLE
Question: How to preserve APK Signatures

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#2505]
The APK I am playing with requires a login. When I use my login details they are rejected with error 401, not authenticated.
I think this is due to having re-signed the APK with jarsigner.
I realise this is probably a stupid question, but is there any way of preserving the original signatures and using them to re-sign the apktool generated apk? I suppose this should be impossible!!!!!

Where are these signatures held and what form do they take? Does apktool see them?

**Comment by iBotPeaches** [comment]
https://source.android.com/security/apksigning/v3

Nothing that can be done. Especially if you are modifying the app. The entire point of signature blocks is to prevent what you are describing. 

If you own your own OS you can relax these rules, but if the Playstore is involved with SafetyNet - good luck.

**Comment by beaumontk** [comment]
What I thought. Pity! Thanks a lot
