### ISSUE TITLE
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)

### ISSUE THREAD

**Issue by ajaygm18** [iBotPeaches/Apktool#2506]
### Information
1. **Apktool Version (`apktool -2.4.1 dirty`)** -
2. **Operating System (,KALI Linux)** -
3. **APK From? (https://apkpure.com/open-camera/net.sourceforge.opencamera)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool b camera`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

apk downloaded from apkpure

https://apkpure.com/open-camera/net.sourceforge.opencamera

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes 

apktool d
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Input file (d) was not found or was not readable.

apktool b 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty
brut.directory.PathNotExist: apktool.yml

2. If you are trying to install a modified apk, did you resign it? i dont know what this question is i just decompile an apk there is no error when i compile it i get a huge error.
3. Are you using the latest apktool version?yes

I am very sorry about poor quality of information i am new to linux github etc etc i use kali linux latest version 64bit i recently installed apktool by  sudo apt install apktool  then i downloaded this apk https://apkpure.com/open-camera/net.sourceforge.opencamera and renamed it as camera.apk

┌──(user㉿DESKTOP-ABCDEF)-[~/Downloads]
└─$ apktool d -f camera.apk -o camera
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty on camera.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ajaygm/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

decompile was successful without any error

┌──(user㉿DESKTOP-ABCDEF)-[~/Downloads]
└─$ apktool b camera     
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 28, --version-code, 77, --version-name, 1.48.1, --no-version-vectors, -F, /tmp/APKTOOL8877238161894022460.tmp, -0, resources.arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_livedata.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.legacy_legacy-support-v4.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.media_media.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, png, -0, ogg, -0, arsc, -I, /home/ajaygm/.local/share/apktool/framework/1.apk, -S, /home/ajaygm/Downloads/camera/res, -M, /home/user/Downloads/camera/AndroidManifest.xml]
W: aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libbacktrace.so.0: undefined symbol: _ZN11unwindstack12ElfInterfaceD2Ev

compiling gave me this huge error 
please help me

**Comment by iBotPeaches** [comment]
Looks like you have some environment issues. If aapt/aapt2 can't unpack themselves you can point to a binary with `-a`. The other errors look like you have a bugged setup - https://superuser.com/q/1614228/230883

**Comment by hajho3in** [comment]
This problem has occurred to me as well. I think you have not fully installed Java

**Comment by gleison1986CEO** [comment]
SOLUTION
apktool d -f -r apkfilename.apk
apktool b -f -r apkpath -o apk.apk
