### ISSUE TITLE
Decompile app, recompile without any changes and app does not function (tracker/ad blocker Knox based)

### ISSUE THREAD

**Issue by decodering22** [iBotPeaches/Apktool#2510]
Information
1. **Apktool Version (`apktool -version`)** - 2.50 Latest
2. **Operating System (Mac, Linux, Windows)** - Windows 7 / 10
3. **APK From? (Playstore, ROM, Other)** - APK Extracted from Phone (paid app Samsung Store)

### Steps to Reproduce
Used apktool.jar command prompt initially and it did not work. Switched to the GUI version using all the possible options and check boxes, the result was the same. No changes made to the code at all, just a decompile and compile test to see if it installs and operates. The app Disconnect Pro has not been updated in over a year, would like to just add some additional hosts to block new trackers. It installs on the phone, but when attempting to activate the firewall it gives an error. This is a Samsung Knox based tracker firewall blocker app with no support from developer on updates. 

I suspect it is just not possible to decompile this app and recompile it due to possible signature issues or knox license. 

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://uploadking.net/jut4p1ce903g.html (Someone else uploaded this, not me)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes - also using self sign option
3. Are you using the latest apktool version? Yes

**Comment by decodering22** [comment]
I should add if I decompile and compile the app without making any changes at all using all the different options the file size is always different than the original apk file. I could never get it to compile and be the same exact file size for what it is worth.

**Comment by iBotPeaches** [comment]
> I suspect it is just not possible to decompile this app and recompile it due to possible signature issues or knox license.

You could be very well right.


> I could never get it to compile and be the same exact file size for what it is worth.

This is expected in a way. You are disassembling dex files and reassembling, taking apart resources and rebuilding with aapt. We can't make a perfect match.

Not really much I can do without a logcat. Sorry!

**Comment by decodering22** [comment]
no problem thanks
