### ISSUE TITLE
EXIT CODE 132

### ISSUE THREAD

**Issue by WhiteShadow8500** [iBotPeaches/Apktool#2511]
i decompiled an apk 
added some permissions to the Android Manifest file and now i can't recompile it

>apktool b original
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_7226994482578096387.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 943162003, --version-name, 1.16.20.03, --no-version-vectors, -F, /tmp/APKTOOL1215886867251210619.tmp, -e, /tmp/APKTOOL5663040769882163903.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/home/original/res, -M, /data/data/com.termux/files/home/original/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
I think 132 is like an invalid instruction set, so nothing Apktool is at fault for here. Something is wrong with your configuration. Possible you are on 32bit bit, or a mobile device (ARM) with binaries that aren't compatible.

Either way - not enough detail to go on here. Closing.

**Comment by AndnixSH** [comment]
`/data/data/com.termux/...`
I see you are using Termux app. It is likely not supported
