### ISSUE TITLE
Why does this Application try to make a remote access to a server?

### ISSUE THREAD

**Issue by Accesslet** [iBotPeaches/Apktool#2512]
Your application makes a remote access request to a server host which specifically mentions evildog1, it does it in the background - WITHOUT the permission of the user. It makes use of remote capability in Windows 10, WITHOUT the authorization of the owner.

I'm warning you, you better stop such activities otherwise I'm going to have to contact a few security researchers, @evildog1 can you explain?

There's background activity going on and it significantly slows down the user's PC, hogging up memory. I'm reporting both of you to Github.

**Comment by iBotPeaches** [comment]
Wat.

Apktool does not.

**Comment by AndnixSH** [comment]
I assume you are using APK Easy Tool. This is probably update check, nothing more than that. I'm been using it for years without any malcious activity

You may have downloaded the software from the untrusted site then, it's your fault
