### ISSUE TITLE
[BUG] No resource identifier found for attribute 'compileSdkVersion', 'compileSdkVersionCodename' and 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by cxzero** [iBotPeaches/Apktool#2525]
### Information
1. **Apktool Version (2.5.0 - latest)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore)** -

### Stacktrace

```
I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: <path>/AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'
W: 
W: <path>/AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W: 
W: <path>/AndroidManifest.xml:9: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_126272989248580721871975574579406538573.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 28, --version-code, 17, --version-name, 2.1.1, --no-version-vectors, -F, /tmp/APKTOOL10528381163881527046.tmp, -e, /tmp/APKTOOL8575927873567580966.tmp, -0, arsc, -I, <home>/.local/share/apktool/framework/1.apk, -S, <path>/res, -M, <path>/AndroidManifest.xml]

```

### Steps to Reproduce
1. `$ java -jar apktool_2.5.0.jar d file.apk`
2. `$ java -jar apktool_2.5.0.jar b file -o file2.apk`
3. Stacktrace above

Have tried `apktool empty-framework-dir --force` but error still happens.

**Comment by cxzero** [comment]
Just to notice, after decompiling apk and searching in `file/AndroidManifest.xml` for the attributes mentioned:

> <?xml version="1.0" encoding="utf-8" standalone="no"?>
> <manifest **android:compileSdkVersion="28" android:compileSdkVersionCodename="9"** package="<package_name>" platformBuildVersionCode="17" platformBuildVersionName="2.1.1" (...)>
> (...)
>     <application **android:appComponentFactory="android.support.v4.app.CoreComponentFactory"** android:name="<application_name>" (...)

I tried removing these attributes and then recompile apk file again (step 2) and it succeed:
```
I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

Are these attributes not recognized by apktool when recompiling? Or perhaps there is another explanation?
Thanks.

**Comment by iBotPeaches** [comment]
> Are these attributes not recognized by apktool when recompiling? Or perhaps there is another explanation?

I would say the framework is out of date, but you already ran that. So not sure.

I don't really have enough details to go further than an educated guess. Sorry!

**Comment by cpw999cn** [comment]
I encountered the same issue. My apk was built by cordova. I had to remove these attributes manually. I hope apktool can update to fix this issue.
