### ISSUE TITLE
[FEAT] Provide documentation to use apktool.jar in JVM Project

### ISSUE THREAD

**Issue by mddanishansari** [iBotPeaches/Apktool#2529]
**Problem description**

It would be really nice if someone can provide the documentation on how to use apkktol.jar file as a library in JVM Projects

**Comment by iBotPeaches** [comment]
Perhaps to make this easier its time for Maven/JitPack. Let me think.

**Comment by iBotPeaches** [comment]
Not doing JitPack, but will publish to Maven Central. I have a ticket in progress for getting approval. First official release to it will be 2.5.1 - https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-65449

**Comment by theapache64** [comment]
@iBotPeaches Do we have a documentation file?

**Comment by mddanishansari** [comment]
Thanks @iBotPeaches for publishing it on Maven, but it would be nice if you could provide a simple documentation on it's usage

**Comment by iBotPeaches** [comment]
```
ApkDecoder apkDecoder = new ApkDecoder();
```

:)

**Comment by iBotPeaches** [comment]
More seriously. It won't exist till 2.5.1 is released.
