### ISSUE TITLE
apktool

### ISSUE THREAD

**Issue by Bigyan00** [iBotPeaches/Apktool#2533]
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libandroidfw.so.0: undefined symbol: _Z11OpenArchivePKcPPv
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [aapt, p, --min-sdk-version, 26, --target-sdk-version, 29, --version-code, 276987824, --version-name, 241.0.0.7.119, --no-version-vectors, -F, /tmp/APKTOOL16298719725642562010.tmp, -0, assets/app_modules/contents/shared5.json, -0, assets/lib/libs.spk.xz, -0, assets/secondary-program-dex-jars/store-0.dex.spk.xz, -0, png, -0, r/c.png, -0, ogg, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20210310-88487-w025vg/original/res, -M, /tmp/d20210310-88487-w025vg/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool

i cannot solve this issue please help thank you!

**Comment by iBotPeaches** [comment]
This looks like an environment issue. Aapt binaries are statically linked so you don't need to depend on shared binaries, but I can't tell what version you are using since that portion was stripped.

None of our automated tests on all 3 platforms can replicate this, so closing.
