### ISSUE TITLE
How to change package name?

### ISSUE THREAD

**Issue by qminds** [iBotPeaches/Apktool#2538]
Hi @iBotPeaches,

Is there any up-to-date guide on how to change a package name? I see that Apktool doesn't support this feature out of the box, however, maybe there are some standard steps for doing this by editing the unpacked APK resources. For example, you described the process [here](https://github.com/iBotPeaches/Apktool/issues/1088#issuecomment-158753029), however it seems to be outdated:

> If you want to blanket change the package name you will have to:
> 
> 1. Change the `apktool.yml` (like you did)
> 2. Update the `AndroidManifest.xml` package name to the new value.
> 3. Manually update the `smali` from (`old/foo/bar` to `new/foo/bar`) in terms of the directories
> 4. Find and replace ALL `*.smali` files with the old package name `Lold/foo/bar` and replace with `Lnew/foo/bar`.

Thereby I have several questions I would like to ask regarding your post:

- I didn't find any `cur_package` and `orig_package` references in the source code.
Does this mean that the step 1 should be omitted?
- Newer Apktool versions produce the `unknown/` directory.
Its structure is similar to the `smali/` directory.
Considering this, do I also need to update its catalog structure as in step 3?
- If I decode the resources, do I also need to replace occurrences in the underlying `*.xml` files as in step 4?

Kindest regards,
Peter

**Comment by iBotPeaches** [comment]
> Is there any up-to-date guide on how to change a package name? 

I haven't had to do this in a few years so nothing from my side that is up to date. 

---

> I didn't find any cur_package and orig_package references in the source code.

Not sure how - unless you have no source. Not sure what Kotlin does in this situation with namespaces.


> Newer Apktool versions produce the unknown/ directory.

Unknown won't have any source files (java) that are disassembled to have to correct a namespace. So not in my knowledge.

> If I decode the resources, do I also need to replace occurrences in the underlying *.xml files as in step 4?

Probably not unless its a resource with full path to a specific java reference.
