### ISSUE TITLE
[Question] Static Field Values

### ISSUE THREAD

**Issue by timea-techgirl** [iBotPeaches/Apktool#2543]
**Is your feature request related to a problem? Please describe.**
When I decompile and compile the same apk and compare with a diff tool, some smali files have static field values removed. Can this be fixed?
![image](https://user-images.githubusercontent.com/7058205/112707183-62afe080-8ecf-11eb-9cc0-94c4dba37621.png)

**Describe the solution you'd like**
There must be no changes between the same apk files after recompilation and decompilation

**Comment by iBotPeaches** [comment]
Thanks for report.

I couldn't replicate this. I even wrote a test to double check if was platform related. I get the values on each disassemble. Linked PR of adding into test suite.

Closing.
