### ISSUE TITLE
[BUG] build crash error

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#2544]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1 and 2.5.0
2. **Operating System (Mac, Linux, Windows)** - W7
3. **APK From? (Playstore, ROM, Other)** - Built from https://github.com/mozilla-mobile/fenix (kotlin)

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool ` see error message below
2. Works fine when D with -r

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by beaumontk** [comment]
C:\kb\java_myApps\android\fenix_debug>"C:\Program Files\Java\jre1.8.0_181\bin\ja
va.exe" -Xmx512m -jar C:\kb\apktool_2.3.4\apktool_2.5.0.jar --verbose -f b C:\kb
\java_myApps\android\fenix_debug\fenix -o C:\kb\java_myApps\android\fenix_debug\
KB_fenix.apk
Mar 27, 2021 9:25:02 AM brut.androlib.Androlib build
INFO: Using Apktool 2.5.0
Mar 27, 2021 9:25:02 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali folder into classes.dex...
Mar 27, 2021 9:25:19 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes2 folder into classes2.dex...
Mar 27, 2021 9:25:20 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes3 folder into classes3.dex...
Mar 27, 2021 9:25:35 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes4 folder into classes4.dex...
Mar 27, 2021 9:25:37 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes5 folder into classes5.dex...
Mar 27, 2021 9:25:38 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes6 folder into classes6.dex...
Mar 27, 2021 9:25:39 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali_classes7 folder into classes7.dex...
Mar 27, 2021 9:25:44 AM brut.androlib.Androlib buildResourcesFull
INFO: Building resources...
Mar 27, 2021 9:25:45 AM java.util.logging.LogManager$RootLogger log
WARNING: invalid resource directory name: C:\kb\java_myApps\android\fenix_debug\
fenix\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit
 code = 1): [C:\Users\kb\AppData\Local\Temp\brut_util_Jar_5975345006075767285729
4990753331045974.tmp, p, -v, --forced-package-id, 127, --min-sdk-version, 21, --
target-sdk-version, 30, --version-code, 1, --version-name, 1.0.2113, --no-versio
n-vectors, -F, C:\Users\kb\AppData\Local\Temp\APKTOOL1258103115761568386.tmp, -e
, C:\Users\kb\AppData\Local\Temp\APKTOOL7111063102129013078.tmp, -0, arsc, -I, C
:\Users\kb\AppData\Local\apktool\framework\1.apk, -S, C:\kb\java_myApps\android\
fenix_debug\fenix\res, -M, C:\kb\java_myApps\android\fenix_debug\fenix\AndroidMa
nifest.xml]

C:\kb\java_myApps\android\fenix_debug>

**Comment by iBotPeaches** [comment]
You'll want to use `--use-aapt2` during rebuild.

**Comment by beaumontk** [comment]
"You'll want to use --use-aapt2 during rebuild"
apk now builds with this solution, but when run it 
[log_01d_for_apktool.txt](https://github.com/iBotPeaches/Apktool/files/6243983/log_01d_for_apktool.txt)
fails with this!
java.lang.Error: LeakCanary in non-debuggable build
