### ISSUE TITLE
[BUG] incomplete decoding of strings with emoji

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2546]
### Information
1. **Apktool Version - `apktool -2.5.1-dirty-smal [0a7b843]`**
2. **Operating System** - Windows
3. **APK From? (Other)** - https://drive.google.com/file/d/1eGthl-8tZw2ppJKr9jPLJdII-1R3-6qr/view?usp=sharing

### Steps to Reproduce
After decompilation, look at res\values\strings.xml line 1935, 1937:
```
    <string name="FontSizePreviewLine1">Do you know what time it is?</string>
    <string name="FontSizePreviewLine2">😎</string>
    <string name="FontSizePreviewName">Bob Harris</string>
    <string name="FontSizePreviewReply">👋</string>
    <string name="FontType">Font Type</string>
```
this is not correct, 
it should be:
```
    <string name="FontSizePreviewLine1">Do you know what time it is?</string>
    <string name="FontSizePreviewLine2">It's morning in Tokyo 😎</string>
    <string name="FontSizePreviewName">Bob Harris</string>
    <string name="FontSizePreviewReply">Good morning! 👋</string>
    <string name="FontType">Font Type</string>
```

**Comment by iBotPeaches** [comment]
Confirmed

**Comment by Comnir** [comment]
I missed this case in #2299 - when there's some text before a surrogate pair, the decoding retry is done with a wrapped buffer that starts at the bytes which failed to be decoded with UTF-8.

I'm preparing a fix for it.

By the way, the file in the drive is not accessible (Access Denied), but this issue is easily reproducible.

**Comment by pashamcr** [comment]
> By the way, the file in the drive is not accessible (Access Denied), but this issue is easily reproducible.

Forgot to open access.

Thanks for the fix, it works now.
