### ISSUE TITLE
[FEAT] Decompile AndroidManifest.xml even if --no-res option is set

### ISSUE THREAD

**Issue by jpstotz** [iBotPeaches/Apktool#2547]
A lot of apks have resources that make problems decompiling using apktool. Therefore to my experience for most APKs it is required to decompile them using the `--no-res` option. 

Using this option however has the disadvantage that the `AndroidManifest.xml` is also not decompiled. In my case 99% of all "resource" modifications are related to the `AndroidManifest.xml`.

**Describe the solution you'd like**
Technically `AndroidManifest.xml` may be an "XML resource" but from an app perspective it is the central configuration file. It should not be considered as "resource" instead it is an own type thus be handled separately. 

Therefore it should be excluded from the option `--no-res` and always be decompiled.
If it is necessary to not decompile `AndroidManifest.xml` an own option should be added.

**Comment by iBotPeaches** [comment]
Sorry not possible. Manifest references files that require the resources to understand the references. Apktool will not accept leaving raw resourceIds in the files like other tools operate so this won't be done.

Thanks for the report.
