### ISSUE TITLE
[BUG] APK recompilation without changes fails

### ISSUE THREAD

**Issue by Luffitys** [iBotPeaches/Apktool#2550]
### Information
1. **Apktool Version (`apktool -version`)** - Compiled from the latest source
2. **Operating System (Mac, Linux, Windows)** - Windows 10 20H2 19042.906
3. **APK From? (Playstore, ROM, Other)** - From ROM: MIUI (umi 21.3.31 cn Beta)

### Stacktrace/Logcat

```
java -jar Tools\APKTool\apktool.jar b --output ..\MiuiGallery_APK\MiuiGallery_.apk ..\MiuiGallery_APK  -p Tools\APKTool\Frameworks
I: Using Apktool 2.5.1-baf8bb-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: Failed to generate resource table for split ''
W: C:\Users\Luffitys\Downloads\Porting-Tools\Porting-Tools\..\MiuiGallery_APK\res\values\dimens.xml:3450: error: Error: String types not allowed (at 'APKTOOL_DUMMY_242' with value '').
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Luffitys\AppData\Local\Temp\brut_util_Jar_86514711303219238359035965874581013338.tmp, p, --forced-package-id, 127, --version-code, 266832, --version-name, 2.2.18.16, --no-version-vectors, -F, C:\Users\Luffitys\AppData\Local\Temp\APKTOOL8898803618868309521.tmp, -e, C:\Users\Luffitys\AppData\Local\Temp\APKTOOL5615666844594734149.tmp, -0, arsc, -I, Tools\APKTool\Frameworks\1.apk, -I, Tools\APKTool\Frameworks\16.apk, -I, Tools\APKTool\Frameworks\18.apk, -S, C:\Users\Luffitys\Downloads\Porting-Tools\Porting-Tools\..\MiuiGallery_APK\res, -M, C:\Users\Luffitys\Downloads\Porting-Tools\Porting-Tools\..\MiuiGallery_APK\AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool d MiuiGallery.apk -p frameworks`
2. `apktool b MiuiGallery -p frameworks`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
https://drive.google.com/drive/folders/1HIaPML57LhBRHuzcVolmKfzCLUhpbNY7?usp=sharing

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://drive.google.com/drive/folders/1HIaPML57LhBRHuzcVolmKfzCLUhpbNY7?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - /
3. Are you using the latest apktool version? - Yes

Decompiling and recompiling results in an error caused by a bad dimens.xml. Removing the dummy lines from dimens.xml and public.xml results in a successful recompilation, however I don't know if it breaks APK functionality.

**Comment by Luffitys** [comment]
Duplicate of #2501 #2462

**Comment by iBotPeaches** [comment]
Thanks, as mentioned above. Duplicates in a few tickets.
