### ISSUE TITLE
[BUG] priv_attr_type->entries.empty()

### ISSUE THREAD

**Issue by Jayce-2177** [iBotPeaches/Apktool#2552]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

W: brut_util_Jar_23533296909129517383743332448576131951.tmp F 04-08 14:47:26  3368 16596 PrivateAttributeMover.cpp:84] Check failed: priv_attr_type->entries.empty()
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073740791): [C:\Users\public\AppData\Local\Temp\brut_util_Jar_23533296909129517383743332448576131951.tmp, link, -o, C:\Users\public\AppData\Local\Temp\APKTOOL3689597971853373488.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 1617174631, --version-name, 1003.7.3.1617174631, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\public\AppData\Local\Temp\APKTOOL1433445854708616387.tmp, -0, arsc, -I, C:\Users\public\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\public\Desktop\apk_tool\lyft_\AndroidManifest.xml, C:\Users\public\Desktop\apk_tool\lyft_\build\resources.zip]

### Steps to Reproduce
1. apktool d lyft_.apk
2. (fix error for colors.xml:632: error: invalid color by changing to a correct color)
3. apktool b --use-aapt2 lyft_

I have also tried it without aapt2, but that gives so many more errors, same issue that has gone back to 2017 for ^attr-privates files.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.lyft.android.driver

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Thanks for report. Tis a known issue that'll be resolved in next release.

https://github.com/iBotPeaches/Apktool/issues/2503
