### ISSUE TITLE
[FEAT]aapt for arm with $ problem

### ISSUE THREAD

**Issue by xpchero** [iBotPeaches/Apktool#2556]
hello, I recompile aapt and aapt2 for arm,  and use apktool with new aapt2 to build apk in arm machine, and I find the problems below
` error: resource 'drawable/$ic_launcher_foreground__0' has invalid entry name '$ic_launcher_foreground__0'. Invalid character '$ic_launcher_foreground__0'.`
I see you have already solve this support $ problem, how? and can you put your aapt code in github

**Comment by iBotPeaches** [comment]
> I see you have already solve this support $ problem, how? and can you put your aapt code in github

https://github.com/iBotPeaches/platform_frameworks_base
