### ISSUE TITLE
apk crashes when opening it after decompiling and compiling. Has a Runtime Exception

### ISSUE THREAD

**Issue by matran** [iBotPeaches/Apktool#2559]
I got the following error after decompiling without making any changes then compile. it installed successful but crashes after opening.
IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.

**Comment by iBotPeaches** [comment]
You'll want to dump an `adb logcat` to get more information here. It would help point at the exact issue if Apktool did not re-create the application perfectly.

**Comment by matran** [comment]
this is result of adb logcat:

04-25 17:34:38.381  8625  8625 E ResourceType: Style contains key with bad entry: 0x0101056c
04-25 17:34:38.381  8625  8625 E ResourceType: Style contains key with bad entry: 0x0101056d
04-25 17:34:38.384  8625  8625 E ResourceType: Style contains key with bad entry: 0x0101056c
04-25 17:34:38.384  8625  8625 E ResourceType: Style contains key with bad entry: 0x0101056d
04-25 17:34:38.497  8625  8625 D AndroidRuntime: Shutting down VM
04-25 17:34:39.663  1759  1759 E JobServiceContext: Time-out while trying to bind f7f9de3 #u0a72/256390133 com.safaricom.mysafaricom/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService, dropping.
04-25 17:34:43.017  8625  8630 I art     : Do partial code cache collection, code=60KB, data=51KB
04-25 17:34:43.018  8625  8630 I art     : After code cache collection, code=59KB, data=50KB
04-25 17:34:43.018  8625  8630 I art     : Increasing code cache capacity to 256KB
04-25 17:34:43.187  8625  8691 I FA      : Tag Manager is not found and thus will not be used
04-25 17:34:43.233  8625  8625 D AndroidRuntime: procName from cmdline: com.safaricom.mysafaricom
04-25 17:34:43.233  8625  8625 E AndroidRuntime: in writeCrashedAppName, pkgName :com.safaricom.mysafaricom
04-25 17:34:43.233  8625  8625 D AndroidRuntime: file written successfully with content: com.safaricom.mysafaricom StringBuffer : ;com.safaricom.mysafaricom
04-25 17:34:43.234  8625  8625 E AndroidRuntime: FATAL EXCEPTION: main
04-25 17:34:43.234  8625  8625 E AndroidRuntime: Process: com.safaricom.mysafaricom, PID: 8625
04-25 17:34:43.234  8625  8625 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.safaricom.mysafaricom/com.safaricom.mysafaricom.ui.main.MainActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6138)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
04-25 17:34:43.234  8625  8625 E AndroidRuntime: Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.setLastBaselineToBottomHeight.RemoteActionCompatParcelizer(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.setSupportBackgroundTintMode.read(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver$MediaMetadataCompat.write(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable.write(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable.setChecked(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable.MediaBrowserCompat$CustomActionResultReceiver(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.PlaybackStateCompat$CustomAction.onCreate(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at o.zzakl.onCreate(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at com.safaricom.mysafaricom.ui.main.Hilt_MainActivity.onCreate(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at com.safaricom.mysafaricom.ui.main.MainActivity.onCreate(Unknown Source)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6787)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1148)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
04-25 17:34:43.234  8625  8625 E AndroidRuntime:        ... 9 more
04-25 17:34:43.234  8625  8625 I Process : Sending signal. PID: 8625 SIG: 9
04-25 17:34:43.234  1950  2027 D BstCommandProcessor-Application: Application crash has been observed.
04-25 17:34:43.246  1950  8707 W BstCommandProcessor-Application: in sendHttpRequest, requestType is of CRASH_APP type but one of the requiredInfo is NULL, crashedApp = BstCrashedAppInfo{pkgName:com.safaricom.mysafaricom versionName:1.4.0 versionCode:10487}
04-25 17:34:43.297  1759  2727 I ActivityManager: Process com.safaricom.mysafaricom (pid 8625) has died
04-25 17:34:43.297  1759  2727 D ActivityManager: cleanUpApplicationRecord -- 8625
04-25 17:34:43.305  1759  2727 D ActivityManager: TopActivityInfo, pkgName: com.safaricom.mysafaricom activityName: com.safaricom.mysafaricom/.ui.main.MainActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
04-25 17:34:43.307  1759  2727 D ActivityManager: Sending app launch intent for appName: MySafaricom pkgName: com.safaricom.mysafaricom
04-25 17:34:43.314  1759  2727 I ActivityManager: Start proc 8709:com.safaricom.mysafaricom/u0a72 for activity com.safaricom.mysafaricom/.ui.main.MainActivity
04-25 17:34:43.320  1759  8708 D ActivityManager: Sending TopActivity Info
04-25 17:34:43.329  8709  8709 W art     : Unexpected CPU variant for X86 using defaults: x86
04-25 17:34:43.341  1759  1987 D WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
04-25 17:34:43.705  8725  8725 W dex2oat : Unexpected CPU variant for X86 using defaults: x86
04-25 17:34:43.705  8725  8725 W dex2oat : Mismatch between dex2oat instruction set features (ISA: X86 Feature string: smp,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt) and those of dex2oat executable (ISA: X86 Feature string: smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt) for the command line:
04-25 17:34:43.705  8725  8725 W dex2oat : /system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=verify-at-runtime --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/data/com.safaricom.mysafaricom/code_cache/.  ​​   --oat-fd=29 --oat-location=/data/data/com.safaricom.mysafaricom/code_cache/.     --compiler-filter=speed
04-25 17:34:43.705  8725  8725 I dex2oat : /system/bin/dex2oat --compiler-filter=verify-at-runtime --dex-file=/data/data/com.safaricom.mysafaricom/code_cache/.  ​​   --oat-fd=29 --oat-location=/data/data/com.safaricom.mysafaricom/code_cache/.     --compiler-filter=speed
04-25 17:34:43.824  8725  8725 I dex2oat : dex2oat took 119.539ms (threads: 2) arena alloc=525KB (537680B) java alloc=32KB (33072B) native alloc=955KB (978816B) free=1604KB (1642624B)
04-25 17:34:46.077  8728  8728 W dex2oat : Unexpected CPU variant for X86 using defaults: x86
04-25 17:34:46.077  8728  8728 W dex2oat : Mismatch between dex2oat instruction set features (ISA: X86 Feature string: smp,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt) and those of dex2oat executable (ISA: X86 Feature string: smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt) for the command line:
04-25 17:34:46.077  8728  8728 W dex2oat : /system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=verify-at-runtime --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/data/com.safaricom.mysafaricom/code_cache/.      --oat-fd=29 --oat-location=/data/data/com.safaricom.mysafaricom/code_cache/.    --compiler-filter=speed
04-25 17:34:46.077  8728  8728 I dex2oat : /system/bin/dex2oat --compiler-filter=verify-at-runtime --dex-file=/data/data/com.safaricom.mysafaricom/code_cache/.      --oat-fd=29 --oat-location=/data/data/com.safaricom.mysafaricom/code_cache/.    --compiler-filter=speed

**Comment by AbdulrhmanBeatz** [comment]
@matran Did you solve it? I have the same issue
