### ISSUE TITLE
[BUG] Decode / Rebuild with resources but forcing Manifest generates a corrupted manifest

### ISSUE THREAD

**Issue by WriteCodeEveryday** [iBotPeaches/Apktool#2563]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore app.

### Stacktrace/Logcat

```
source:
        WINDOWS_PATH\Downloads\APP\input\dist
zipalign location: BUILT_IN
        WINDOWS_PATH\AppData\Local\Temp\uapksigner-6703512978887330326\win-zipalign_29_0_2.exe5694106514128335700.tmp
keystore:
        [0] 4f8d1573 WINDOWS_PATH\.android\debug.keystore (DEBUG_ANDROID_FOLDER)

01. input.apk
could not verify input\dist\input.apk: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
Run with '--debug' parameter to get additional information.

WINDOWS_PATH\Downloads\APP>java -jar uber-apk-signer-1.2.1.jar -a input/dist/input.apk --debug
source:
        WINDOWS_PATH\Downloads\APP\input\dist
zipalign location: BUILT_IN
        WINDOWS_PATH\AppData\Local\Temp\uapksigner-4589679579064892126\win-zipalign_29_0_2.exe5075036392118256076.tmp
keystore:
        [0] 4f8d1573 WINDOWS_PATH\.android\debug.keystore (DEBUG_ANDROID_FOLDER)

01. input.apk
could not verify input\dist\input.apk: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
java.lang.IllegalStateException: could not verify input\dist\input.apk: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
        at at.favre.tools.apksigner.SignTool.verifySign(SignTool.java:398)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:119)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)
Caused by: com.android.apksig.apk.MinSdkVersionException: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
        at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:384)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:180)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:126)
        at at.favre.tools.apksigner.signing.AndroidApkSignerVerify.verify(AndroidApkSignerVerify.java:38)
        at at.favre.tools.apksigner.SignTool.verifySign(SignTool.java:334)
        ... 3 more
Caused by: com.android.apksig.internal.apk.AndroidBinXmlParser$XmlParserException: No XML chunk in file
        at com.android.apksig.internal.apk.AndroidBinXmlParser.<init>(AndroidBinXmlParser.java:101)
        at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:345)
        ... 7 more

Cmd history for debugging purpose:
-----------------------
```

### Steps to Reproduce
1. `java -jar apktool_2.5.0.jar d -r --force-manifest input.apk`
2. `java -jar apktool_2.5.0.jar b input`
3. `java -jar uber-apk-signer-1.2.1.jar -a input/dist/input.apk`

### Frameworks
Not a framework app. Playstore app.

### APK
I don't think it's the APK itself, I might try with another one.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? This is the thing I'm doing
2. If you are trying to install a modified apk, did you resign it? This is where the problem is happening.
3. Are you using the latest apktool version? Yes.

**I do not expect a solution here, every other configuration was able to be signed (but was broken due to undecodable resources) so I was trying just to modify the manifest to be able to take backups from the app.**

**Comment by WriteCodeEveryday** [comment]
Superseeded by #2564

**Comment by WriteCodeEveryday** [comment]
Actually, I think this might not be caused by the other issue.

**Comment by iBotPeaches** [comment]
I don't believe this is an issue. `--force-manifest` is used in situation where you want to statically analyze an application but always want the Manifest without the additional time of decoding every single resource.

It takes shortcuts which probably leads to the inability to rebuild. I've put in a commit into the docs to make this more clear - https://github.com/iBotPeaches/Apktool/commit/55a32ccb8e8a202baac0eae975991c65595cc449

Closing as I don't believe there is an issue here, just a misunderstanding of the flags.

**Comment by iBotPeaches** [comment]
> Oh, that makes perfect sense @iBotPeaches. What is the recommended way if you just want to do a quick Manifest tweak with a quick smali file change without unbundling resources (apktool has some issues with this specific APK)?
> 
> Without --force-manifest, -r will generate a binary blob that can't be edited.

There isn't unforunately. We need resources to properly decode a manifest to make editable.

**Comment by WriteCodeEveryday** [comment]
Okay, thanks for everything... Apktool is probably the coolest thing I've seen on this side of the mobile space (JDAX-GUI comes in at a close second). I can probably just make smali changes and be happy (was really hoping to enable backups out of all things).

What are the odds we could get a -b flag for just enabling backups when building? I know adb is deprecating it but Android 9 still supports it.
