### ISSUE TITLE
[BUG] Decoding / Rebuild without any changes fails to run on device

### ISSUE THREAD

**Issue by WriteCodeEveryday** [iBotPeaches/Apktool#2564]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore app.

### Stacktrace/Logcat

No stacktrace, just fails to launch on device.

### Steps to Reproduce

1. java -jar apktool_2.5.0.jar d -r -s input.apk
2. java -jar apktool_2.5.0.jar b input
3. java -jar uber-apk-signer-1.2.1.jar -a input/dist/input.apk
4. adb deploy APK into phone

### Frameworks
Not a ROM APK.

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
Have you tried apktool d, apktool b without changing anything? This is the thing I'm doing
If you are trying to install a modified apk, did you resign it? This is where the problem is happening.
Are you using the latest apktool version? Yes.

**Comment by WriteCodeEveryday** [comment]
Here's the original APK.
[input.apk.zip](https://github.com/iBotPeaches/Apktool/files/6445771/input.apk.zip)

Here's the debug signed APK.
[input-aligned-debugSigned.apk.zip](https://github.com/iBotPeaches/Apktool/files/6445770/input-aligned-debugSigned.apk.zip)

**Comment by iBotPeaches** [comment]
> No stacktrace, just fails to launch on device.

There will always be something in the `adb logcat` about what this failure may be. Failure to install is probably a signing issue, but either way. If you can get the logcat snippet of the failure I can take another look.

Closing.

**Comment by WriteCodeEveryday** [comment]
@iBotPeaches thanks for the help, logcat shows it as an `java.lang.UnsatisfiedLinkError` on `libflyby_jni.so`
