### ISSUE TITLE
[BUG]when try to buil it thinks that b is the path

### ISSUE THREAD

**Issue by leao-nardo** [iBotPeaches/Apktool#2565]
### Information
1. **Apktool Version (`apktool -version`)** -2.5
2. **Operating System (Mac, Linux, Windows)** -Windows jdk 16 and jre 1.8
3. **APK From? (Playstore, ROM, Other)** -  tested from Playstore and Other all the same

decode works but when try to build gives this error. it thinks that b (command to build ) is the path , writing build give the same error
### Stacktrace/Logcat

brut.directory.DirectoryException: java.nio.file.NoSuchFileException: b
or
brut.directory.DirectoryException: java.nio.file.NoSuchFileException: build

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
2. apktool.bat apktool b "folder"

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? its what im doing and give this error in 2-3 apps
2. If you are trying to install a modified apk, did you resign it?not modified
3. Are you using the latest apktool version?yes 2.5

**Comment by leao-nardo** [comment]
oh nevermind.
 i just got it running. i was trying things for more than hour .
the thing is when i was decoding i was writing like that
`apktool.bat apktool b "folder"
`
because only writing apktool was not working. i think what may have explain is that i was using only the jre not the jdk . now after installing the jdk i tested writing only `apktool b "folder"` and it work and builds the apk.

so for anyone wondering if you use apktool only to decode things seems it can work with jre , but to build need jdk.

also  java_home is not being found im my system . it says
`java_home : The term 'java_home' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ java_home
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (java_home:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

maybe its not in the path because i still didnt restarted pc after installing jdk .
i also made some changes to the bat file to make it work without having  java_home in path. and to work with jre or jdk. ithink it makes it more resilient. im putting  the bat here in case anyone want just del the .txt on the end to use
[apktool.bat.txt](https://github.com/iBotPeaches/Apktool/files/6446662/apktool.bat.txt)

**Comment by iBotPeaches** [comment]
Your issue was combining both the helper script and the apktool binary. So `apktool.bat apktool is executing apktool and sending the command (apktool) to it. Leading to this issues.

You'll need the JRE for using, the JDK for building.
