### ISSUE TITLE
[BUG] Decoding / Rebuild without any changes fails to run on device (with logs)

### ISSUE THREAD

**Issue by WriteCodeEveryday** [iBotPeaches/Apktool#2566]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore app.

### Stacktrace/Logcat

`
05-08 08:03:52.176  1800  1841 I ActivityManager: Start proc 23433:com.input.apk/u0a357 for activity {com.input.apk/com.input.apk.LauncherActivity}
05-08 08:03:52.186 23433 23433 E com.input.apk: Not starting debugger since process cannot load the jdwp agent.
05-08 08:03:52.186  1800  1834 V WindowManager: Changing focus from Window{4050b4b u0 com.blackberry.blackberrylauncher/com.blackberry.blackberrylauncher.MainActivity} to null displayId=0
05-08 08:03:52.204 10145 10203 D MCLOG   : [MC_TriggerHelper] PauseResumeTrigger
05-08 08:03:52.205  1800  4256 W ActivityTaskManager: Request to remove task ignored for non-existent task 74
05-08 08:03:52.215  1800  1834 I WindowManager:   SURFACE show Surface(name=Splash Screen com.input.apk)/@0xa46f61c on display:0: Splash Screen com.input.apk
05-08 08:03:52.218 23433 23433 W ActivityThread: Application com.input.apk is waiting for the debugger on port 8100...
05-08 08:03:52.220   752  2481 I netd    : firewallSetUidRule(2, 10357, 1) <0.08ms>
05-08 08:03:52.221 10145 10145 D MCLOG   : [MC_Service] onStartcommand()
05-08 08:03:52.228 23433 23433 I com.input.apk: The ClassLoaderContext is a special shared library.
05-08 08:03:52.245  1800  1831 V WindowManager: Changing focus from null to Window{6069e77 u0 Waiting For Debugger: com.input.apk} displayId=0
05-08 08:03:52.251  1800  1831 V WindowManager: Changing focus from Window{6069e77 u0 Waiting For Debugger: com.input.apk} to null displayId=0
05-08 08:03:52.289 23433 23433 I FirebaseInitProvider: FirebaseApp initialization successful
05-08 08:03:52.306 23433 23433 I CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
05-08 08:03:52.317 23433 23433 V com.input.apk: start
05-08 08:03:52.318 23433 23457 I FA      : App measurement is starting up, version: 18102
05-08 08:03:52.318 23433 23457 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-08 08:03:52.319 23433 23457 I FA      : To enable faster debug mode event logging run:
05-08 08:03:52.319 23433 23457 I FA      :   adb shell setprop debug.firebase.analytics.app com.input.apk
05-08 08:03:52.357 23433 23433 E CrashlyticsNdk: libcrashlytics could not be loaded. This APK may not have been compiled for this device's architecture. NDK crashes will not be reported to Crashlytics:
05-08 08:03:52.357 23433 23433 E CrashlyticsNdk: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.input.apk-Tbg5RW0NrzPl-QeRxtKjPA==/base.apk"],nativeLibraryDirectories=[/data/app/com.input.apk-Tbg5RW0NrzPl-QeRxtKjPA==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libcrashlytics.so"
05-08 08:03:52.361 23433 23433 I CrashlyticsCore: Initializing Crashlytics Core 2.7.0.33
05-08 08:03:52.389 23433 23433 D NetworkSecurityConfig: Using Network Security Config from resource input_sdk_network_security_config debugBuild: false
05-08 08:03:52.409 23433 23433 D AndroidRuntime: Shutting down VM
05-08 08:03:52.411 23433 23433 E AndroidRuntime: FATAL EXCEPTION: main
05-08 08:03:52.411 23433 23433 E AndroidRuntime: Process: com.input.apk, PID: 23433
05-08 08:03:52.411 23433 23433 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.input.apk-Tbg5RW0NrzPl-QeRxtKjPA==/base.apk"],nativeLibraryDirectories=[/data/app/com.input.apk-Tbg5RW0NrzPl-QeRxtKjPA==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflyby_jni.so"
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1667)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at com.target.common.TargetCore.<clinit>(TargetCore.java:58)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at com.target.aircam.Flyby.start(Flyby.java:7)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at com.target.aircam.FlybyApplication.onCreate(FlybyApplication.java:228)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.app.ActivityThread.access$1400(ActivityThread.java:232)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2014)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7604)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-08 08:03:52.411 23433 23433 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
05-08 08:03:52.520  4322  4495 D OpenGLRenderer: endAllActiveAnimators on 0x7b1ac79c00 (ImageView) with handle 0x7b8080f760
`

Looks like it's a LinkError with some static libs.

### Steps to Reproduce

1. java -jar apktool_2.5.0.jar d -r -s input.apk
2. java -jar apktool_2.5.0.jar b input
3. java -jar uber-apk-signer-1.2.1.jar -a input/dist/input.apk
4. adb deploy APK into phone

### Frameworks
Not a ROM APK.

### APK
APK is attached to #2564.

### Questions to ask before submission
Have you tried apktool d, apktool b without changing anything? This is the thing I'm doing
If you are trying to install a modified apk, did you resign it? This is where the problem is happening.
Are you using the latest apktool version? Yes.

This is just a reopening of #2564 but with appropriate `logcat` logs (thanks @iBotPeaches for telling me where to look)

**Comment by iBotPeaches** [comment]
I'm not seeing any shared objects in the application so that would explain why its crashing.

Not sure Apktool is at fault or can do anything here. The crash is legitimate and from the application provided in #2564 I don't see any objects myself.

Closing.

**Comment by WriteCodeEveryday** [comment]
The APK works as installed by Play Store so decompiling and recompiling should work, are this kind of native libraries not supported?

**Comment by iBotPeaches** [comment]
You are missing a part of the application again. Maybe its split and architectures are downloaded in another.
