### ISSUE TITLE
[BUG] Broken smali files with very long filenames prevents compiling

### ISSUE THREAD

**Issue by Toshiba1127** [iBotPeaches/Apktool#2567]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
Decompile
[log.txt](https://github.com/iBotPeaches/Apktool/files/6460980/log.txt)

Compile
```
I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
..\1-Decompiled APKs\goddess-kiss-o-v-e_1.13.11\smali_classes2\com\jOmqCQCRagOZkz9M4kZIRZl9Fxl5CPgAiIpDsMBJfy8n5UbKYUR32SQNh7e1PlkF0SGuJvUCewtBVxJEQI2dP9C0DGBSniGBdAsKBjHeuFK64gYmSZbWgbn0l8ds65c1bVWtUHxjXuh04TjRPsGjAQ648aGF7HfW1iskEE75aQngoMCvMc2m.smali[31,0] mismatched input '' expecting END_METHOD_DIRECTIVE
Could not smali file: com/jOmqCQCRagOZkz9M4kZIRZl9Fxl5CPgAiIpDsMBJfy8n5UbKYUR32SQNh7e1PlkF0SGuJvUCewtBVxJEQI2dP9C0DGBSniGBdAsKBjHeuFK64gYmSZbWgbn0l8ds65c1bVWtUHxjXuh04TjRPsGjAQ648aGF7HfW1iskEE75aQngoMCvMc2m.smali```
```

### Steps to Reproduce
1. `apktool d`
2. `apktool b`

### Frameworks
N/A

### APK
https://apkcombo.com/apk-downloader/?device=&arches=armeabi-v7a&sdkInt=&sa=1&lang=en&dpi=480&q=com.flerogames.aos.ove

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes, after running my script to remove all long files
3. Are you using the latest apktool version? Yes

### Description
The dex is manipulated so it can contains smali files with long filenames and apktool would decompile them as an incomplete or broken smali. I have ran my own script to remove all those files that are longer then I can compile

Can you possible to make it ignore long filenames so it doesn't write to disk?

**Comment by MrIkso** [comment]
>Operating System (Mac, Linux, Windows) - Windows
@Toshiba1127 See [this](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later)

**Comment by Toshiba1127** [comment]
@MrIkso ok, it was already set to 1. I changed to 0, but long file are still being created and prevent compiling.
I can use my script till then.
Thought it could be implemented to apktool to ignore long files

**Comment by iBotPeaches** [comment]
> @MrIkso ok, it was already set to 1. I changed to 0, but long file are still being created and prevent compiling.

Long files are being prevented because of OS errors or Apktool errors? Have you redone the disassemble with a larger path length variable?

**Comment by Toshiba1127** [comment]
@iBotPeaches no, they are preventing compiling, decompiling is fine with bunch of errors. I have to remove them all with my script manually . I was just asking if it could be implemented so the long files are not created at the decompile process to solve the problem

**Comment by iBotPeaches** [comment]
> Can you possible to make it ignore long filenames so it doesn't write to disk?

I think if that responsibility exists it would be a flag/configuration on baksmali side. I'm not noticing an issue here though, baksmali is properly skipping these

```
Error occurred while disassembling class Lorg.fmod.muCnVJkIJdP0X3MAn08X69Uljfq78mOaV3CFtyHYTtfxW4l9oSP1o6RBjkvEbeTJwFV39vOPjxkjfsJSj0d1JiGcIogjw1aTNgXr4Q7lrUjBlZz54VcIqjEEmqdn4KPOwpUmXDw87KoxYbu7x8TFHmZghNVRF7l670SGf2uugnY4ewRXdAqy; - skipping class
org.jf.util.ExceptionWithContext: The last instruction in method Lorg/fmod/muCnVJkIJdP0X3MAn08X69Uljfq78mOaV3CFtyHYTtfxW4l9oSP1o6RBjkvEbeTJwFV39vOPjxkjfsJSj0d1JiGcIogjw1aTNgXr4Q7lrUjBlZz54VcIqjEEmqdn4KPOwpUmXDw87KoxYbu7x8TFHmZghNVRF7l670SGf2uugnY4ewRXdAqy;->lk15RoNp7WQa6o3yqh2PAdm0el7LJMN9J9atzJfUh78K1TK5ZzNjEEwfLR7loGkhoN12xPtqIuzBEpLwqE70QihGURELoWlVVoybUJOmSaIuoivdEteS7jUqHyHYbGmOFpVGe5989Ceq7cAnxGAHSwqRWWIYedJYnrwXBRiI3hkjkyJiPXf1()I is truncated
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:99)
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
	at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:423)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:777)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:260)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:217)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:86)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:324)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:115)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:161)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error while processing method Lorg/fmod/muCnVJkIJdP0X3MAn08X69Uljfq78mOaV3CFtyHYTtfxW4l9oSP1o6RBjkvEbeTJwFV39vOPjxkjfsJSj0d1JiGcIogjw1aTNgXr4Q7lrUjBlZz54VcIqjEEmqdn4KPOwpUmXDw87KoxYbu7x8TFHmZghNVRF7l670SGf2uugnY4ewRXdAqy;->lk15RoNp7WQa6o3yqh2PAdm0el7LJMN9J9atzJfUh78K1TK5ZzNjEEwfLR7loGkhoN12xPtqIuzBEpLwqE70QihGURELoWlVVoybUJOmSaIuoivdEteS7jUqHyHYbGmOFpVGe5989Ceq7cAnxGAHSwqRWWIYedJYnrwXBRiI3hkjkyJiPXf1()I

I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2567
```

Then rebuild goes through.

```
➜  2567 apktool b goddess-kiss-o-v-e_1.13.11
I: Using Apktool 2.5.1-45c91e-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2567 
```

Closing.

**Comment by Toshiba1127** [comment]
Well you are using Linux, I am using Windows
That's not a problem then, I will continue to do manually
