### ISSUE TITLE
[BUG] Help brut.androlib.AndrolibException: brut.common.BrutException: could not exec

### ISSUE THREAD

**Issue by xCoder2006** [iBotPeaches/Apktool#2569]
C:\apktool>java -jar apktool.jar d -s ZManager.apk
I: Using Apktool 2.5.0 on ZManager.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Administrator\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

-------------------------------------------------------------
C:\apktool>java -jar apktool.jar b ZManager
I: Using Apktool 2.5.0
I: Copying ZManager classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: C:\apktool\ZManager\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_6056326136963374352984646966881597554.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL9008110848660019548.tmp, -e, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL1837319759591197647.tmp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, C:\apktool\ZManager\res, -M, C:\apktool\ZManager\AndroidManifest.xml]

**Comment by xCoder2006** [comment]
files :
http://www.alwakir.net/s/ZManager_1.0.6.apk

Thx

**Comment by aniruddha-ga** [comment]
same error

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_86053453154494034012677861671757041409.tmp, link, -o, C:\Users\user\AppData\Local\Temp\APKTOOL8488913214533974297.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 20201013, --version-name, 2.8.7, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\user\AppData\Local\Temp\APKTOOL7480297929712414571.tmp, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\user\Desktop\Apk-edits\Apks\NPmanager_2.8.7.apk-decompiled\AndroidManifest.xml, C:\Users\user\Desktop\Apk-edits\Apks\NPmanager_2.8.7.apk-decompiled\build\resources.zip]

**Comment by iBotPeaches** [comment]
Please build using `--use-aapt2`

```
➜  2569 apktool d ZManager_1.0.6.apk 
I: Using Apktool 2.5.1-45c91e-SNAPSHOT on ZManager_1.0.6.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2569 apktool b ZManager_1.0.6 --use-aapt2
I: Using Apktool 2.5.1-45c91e-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2569 
```

Closing.
