### ISSUE TITLE
java.io.FileNotFoundException: \original\build\apk\classes.dex (Operation did not complete successfully because the file contains a virus or potentially unwanted software)

### ISSUE THREAD

**Issue by PranshuBasak** [iBotPeaches/Apktool#2571]
java.io.FileNotFoundException: \original\build\apk\classes.dex (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
this is a error i am catching when compiling a appk file , i have edited smali file and also added a new smali file to it , but i have followed same instructions from a video class , they can ran it successfully but only i am getting this error , the lecture is 2 years old so they are probably using older apktool , 
i am using the latest version of it , can anyone help

**Comment by iBotPeaches** [comment]
Sounds like you need to relax your virus protection if you are messing with suspect application.

As the error suggests. Not sure what you expect Apktool to do here if your virus protection is interfering. Closing.
