### ISSUE TITLE
[BUG]The Assets folder in the assets folder is not recognized

### ISSUE THREAD

**Issue by TorrentialNight** [iBotPeaches/Apktool#2574]
### Information
1.Apktool Version (apktool -version) - Using Apktool 2.5.0
2.Operating System (Mac, Linux, Windows) - Windows
3.APK From? (Playstore, ROM, Other) - Other

### Stacktrace/Logcat

Include stacktrace here
There is an Assets folder under the assets folder in APK package. Using apktool to package cannot recognize the assets folder
Before packing
![befor](https://user-images.githubusercontent.com/49176737/119318344-bfe7c880-bcab-11eb-8cf5-89a1f2af3bc5.png)
After packing
![after](https://user-images.githubusercontent.com/49176737/119318770-456b7880-bcac-11eb-9cd8-4db24d8103b2.png)

The Asstest folder package under assets folder is removed during the packaging process of apktool

**Comment by iBotPeaches** [comment]
I put up a failing test for this. It passes on linux, but fails on mac/windows. So must have something to do with our normalization. Either way - I confirm this strange issue.

https://github.com/iBotPeaches/Apktool/pull/2575

**Comment by TorrentialNight** [comment]
![1](https://user-images.githubusercontent.com/49176737/120980861-9ea5d280-c7a9-11eb-8a2c-23561bbd5e3d.png)
I have modified the source code as shown in the figure and it can work normally. This is the code on the old version of apktool

**Comment by iBotPeaches** [comment]
> ![1](https://user-images.githubusercontent.com/49176737/120980861-9ea5d280-c7a9-11eb-8a2c-23561bbd5e3d.png)
> I have modified the source code as shown in the figure and it can work normally. This is the code on the old version of apktool

I'm struggling to understand how changing the core functionality of Apktool, breaking aapt2 completely will resolve this problem. In the future, PRs for changes are always accepted so the test suite can run on all platforms.

I'm reopening, because the bug is still here.

**Comment by IgorEisberg** [comment]
I couldn't replicate this on Windows, is there any sample APK to work with?

**Comment by MikuAuahDark** [comment]
Hello, I don't see this issue in APKTool 2.6.1. I have "assets" folder inside "assets" and they're packaged correctly by APKTool.
![gambar](https://user-images.githubusercontent.com/7500438/170925279-4ea2b19c-d903-4291-ae91-b29a8bfd4159.png)

![gambar](https://user-images.githubusercontent.com/7500438/170925341-6406f362-0e80-4eab-8284-cc6b3be6e694.png)

**Comment by iBotPeaches** [comment]
I struggle with this ticket to understand the replication steps. I put up my own and it passed, iterated it a few times and it still passed.

So closing - https://github.com/iBotPeaches/Apktool/commit/2b8121584624f0a1b1602992a48fcdbf60c0347d
