### ISSUE TITLE
Control of zip compression

### ISSUE THREAD

**Issue by RenateUSB** [iBotPeaches/Apktool#2578]
A round trip of a jar on 2.5.0 leaves some dexes compressed and some not.

Please make it consistent and controllable by a flag.

    C:\>unzip /l framework.jar
           9932136  classes.dex
           9560032  classes2.dex
           8346312  classes3.dex

    C:\>apktool d framework.jar -o fwmod
    ...
    C:\>apktool b fwmod -o fwmod.jar -api 29
    ...

    C:\>unzip /l fwmod.jar
              10005860  classes.dex
     3720723   9639452  classes2.dex
     3477572   8399696  classes3.dex

For extra credit, why does it rebuild unmodified source? Why does it break the jar?

**Comment by iBotPeaches** [comment]
Couldn't replicate this. Both were deflated.

```
➜  2317 unzip -v -l base.apk | grep 'classes'        
 8362856  Defl:N  3135980  63% 2020-03-23 16:42 1485a4ec  classes2.dex
 2116204  Defl:N   787215  63% 2020-03-23 16:42 9c7fb051  classes3.dex
 8886860  Defl:N  3814079  57% 2020-03-23 16:42 8e5eab27  classes.dex
➜  2317 unzip -v -l base-rebuilt.apk | grep 'classes'
 8990884  Defl:N  3896569  57% 2020-11-28 15:29 2fad5bdb  classes.dex
 8511384  Defl:N  3231292  62% 2020-11-28 15:29 b87046c4  classes2.dex
 2139604  Defl:N   795952  63% 2020-11-28 15:29 98d6b902  classes3.dex
➜  2317 
```

> why does it rebuild unmodified source?

These are flags configurable.

> Why does it break the jar?

The logcat would explain that.
