### ISSUE TITLE
Round trip breaks framework.jar

### ISSUE THREAD

**Issue by RenateUSB** [iBotPeaches/Apktool#2579]
Using 2.5.0 round-tripping framework.jar breaks functionality in unknown way
This is a file with blacklist, I use -api 29

    C:\>dexdump classes.dex
    String 00000070  00013aca
    Type   0004eb98  00001b2f
    Proto  00055854  000031a5
    Field  0007ac10  000096da
    Method 000c62e0  0000f769
    Class  00141e28  000014b9
    Data   0016b548  0080d820

    C:\>dexdump classes.dex
    String 00000070  00013ac9
    Type   0004eb94  00001b2f
    Proto  00055850  000031a5
    Field  0007ac0c  000096da
    Method 000c62dc  0000f769
    Class  00141e24  000014b9
    Data   0016b544  0081f820

The right column is in item count, for data that's the same as bytes.

Data grew by 73,728 bytes

I'm having trouble with the upload, it's 28 MB.

**Comment by iBotPeaches** [comment]
Tis the nature of RE at times. Unfortunately nothing for me to work from here.

**Comment by RenateUSB** [comment]
This keeps on complaining "is not included in the list".

Here is a direct link
www.temblast.com/download/framework.jar

**Comment by RenateUSB** [comment]
Do you support greylist-q ? I think there could be a problem there.
