### ISSUE TITLE
[BUG] New font tag

### ISSUE THREAD

**Issue by Oizaro** [iBotPeaches/Apktool#2580]
### Information
1. **Apktool Version (`apktool -version`)**
- 2.5.0 Stable
2. **Operating System (Mac, Linux, Windows)**
- Windows
3. **APK From? (Playstore, ROM, Other)**
- www.apkmirror.com

### Stacktrace/Logcat
```
\com\res\font-v22\google_sans.xml:2: error: attribute android:fontProviderSystemFontFamily not found.

\com\res\font-v22\google_sans_medium.xml:2: error: attribute android:fontProviderSystemFontFamily not found.
```

### Steps to Reproduce
Unpack apk resources (without backsmaling) and repack it with AAPT2 and without any changes.

### APK
https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-4-29-50-release/youtube-music-stream-songs-music-videos-4-29-50-2-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
- Yes
2. If you are trying to install a modified apk, did you resign it?
- Yes
3. Are you using the latest apktool version?
- Yes

**Comment by MrIkso** [comment]
It is attributes from android 12 (S). Use framework from android s

**Comment by Oizaro** [comment]
> It is attributes from android 12 (S). Use framework from android s

Yes, I already thought about it, the problem is that I don't know how to extract it from the rom (I don't have an Android 12 device).

**Comment by Oizaro** [comment]
> It is attributes from android 12 (S). Use framework from android s

Thanks, I just extracted the framwork apk from an android 12 beta rom and i confirm that using this it works.

**Comment by iBotPeaches** [comment]
Thanks, I'll do a pull of latest S beta and add it into the project.

**Comment by iBotPeaches** [comment]
Added S Beta 4 into apktool. 

https://github.com/iBotPeaches/Apktool/commit/9f8ddb1bb008951ade3df325737373bc634f8c2b#diff-abd62ab6f6ca9a254b74c36f45f74b3be879fe338beee56f48f0cc1dcf7c0094

Marking as done.
