### ISSUE TITLE
[FEAT] Single resource compiling

### ISSUE THREAD

**Issue by Oizaro** [iBotPeaches/Apktool#2581]
Hi.

My request is easy: a possibility to decompile/recompile just one exact resource instead of entire resources folders.

This increase the access speed to an already known resource.

**Comment by iBotPeaches** [comment]
I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.

**Comment by Oizaro** [comment]
> I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.

Actually i was wondering if there was a way to decode a single resource file already extracted from the apk, because not included in resources.arsc and accessible with a zip manager.

**Comment by iBotPeaches** [comment]
> > I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.
> 
> Actually i was wondering if there was a way to decode a single resource file already extracted from the apk, because not included in resources.arsc and accessible with a zip manager.

Still won't be supported. Those files are 90% of the time AXML and still need decoding to become human readable XML.

**Comment by Oizaro** [comment]
> > > I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.
> > 
> > 
> > Actually i was wondering if there was a way to decode a single resource file already extracted from the apk, because not included in resources.arsc and accessible with a zip manager.
> 
> Still won't be supported. Those files are 90% of the time AXML and still need decoding to become human readable XML.

So eventually this feature could be supported in future? Because I thought to this eventuality by just unzipping the YouTube Music apk (the one of the other bug report) and take this "unreadable xml".

**Comment by iBotPeaches** [comment]
> > > > I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.
> > > 
> > > 
> > > Actually i was wondering if there was a way to decode a single resource file already extracted from the apk, because not included in resources.arsc and accessible with a zip manager.
> > 
> > 
> > Still won't be supported. Those files are 90% of the time AXML and still need decoding to become human readable XML.
> 
> So eventually this feature could be supported in future? Because I thought to this eventuality by just unzipping the YouTube Music apk (the one of the other bug report) and take this "unreadable xml".

You can do that without Apktool. So no, I don't see this use case being supported directly within Apktool.

**Comment by Oizaro** [comment]
> > > > > I don't see this being supported. Many resources are simply not reachable without disassembling the `resources.arsc` so ad-hoc singular references would not speed up anything as we have to disassemble all to hit one.
> > > > 
> > > > 
> > > > Actually i was wondering if there was a way to decode a single resource file already extracted from the apk, because not included in resources.arsc and accessible with a zip manager.
> > > 
> > > 
> > > Still won't be supported. Those files are 90% of the time AXML and still need decoding to become human readable XML.
> > 
> > 
> > So eventually this feature could be supported in future? Because I thought to this eventuality by just unzipping the YouTube Music apk (the one of the other bug report) and take this "unreadable xml".
> 
> You can do that without Apktool. So no, I don't see this use case being supported directly within Apktool.

Where can I find something to decode them with?
