### ISSUE TITLE
App crashed after decompile and recompile without any changes

### ISSUE THREAD

**Issue by batssmasher** [iBotPeaches/Apktool#2583]
### Information
1. **Apktool Version (`apktool -version`)** -   2.5.0
2. **Operating System (Mac, Linux, Windows)** -  Win 10
3. **APK From? (Playstore, ROM, Other)** -  Playstore . NON ROM

### Stacktrace/Logcat

06-04 20:49:41.788  1799  1946 I ActivityManager: Start proc 18019:abc.efg.higcom/u0a349 for activity {abc.efg.higcom/com.store.android.ui.MainActivity} caller=com.miui.home
06-04 20:49:41.803 18019 18019 E .efg.abc: Not starting debugger since process cannot load the jdwp agent.
06-04 20:49:41.879 18019 18019 I .efg.abc: The ClassLoaderContext is a special shared library.
06-04 20:49:43.839   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: bindService is called for service : com.google.android.gms/.ads.identifier.service.AdvertisingIdService and for client abc.efg.higcom
06-04 20:49:43.840   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: total connections for client : abc.efg.higcomare :1
06-04 20:49:43.851 18019 18063 I FA      :   adb shell setprop debug.firebase.analytics.app abc.efg.higcom
06-04 20:49:43.927   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: bindService is called for service : com.google.android.gms/.measurement.service.MeasurementBrokerService and for client abc.efg.higcom
06-04 20:49:43.927   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: total connections for client : abc.efg.higcomare :2
06-04 20:49:43.953   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: bindService is called for service : com.google.android.gms/.gcm.PushMessagingRegistrarProxy and for client abc.efg.higcom
06-04 20:49:43.954   720   761 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service: total connections for client : abc.efg.higcomare :3
06-04 20:49:44.044  1799  6093 D PackageManager.DexOptimizer: Running dexopt on: /data/user/0/abc.efg.higcom/app_dx/Generated5819756368461140727.jar pkg=abc.efg.higcom isa=[arm64] reason=bg-dexopt dexoptFlags=boot_complete,public,secondary,storage_ce,enable_hidden_api_checks target-filter=quicken class-loader-context=PCL[];PCL[/data/app/abc.efg.higcom-UAIx4xrh7rd5KSuDQZhKbA==/base.apk]
06-04 20:49:44.045   968  3719 D installd: Getting dex paths for context PCL[];PCL[/data/app/abc.efg.higcom-UAIx4xrh7rd5KSuDQZhKbA==/base.apk]
06-04 20:49:44.086   968  3719 D installd: Processing secondary dex path /data/user/0/abc.efg.higcom/app_dx/Generated5819756368461140727.jar
06-04 20:49:44.089 18087 18087 I installd: installd cannot open oat file during dexopt/data/user/0/abc.efg.higcom/app_dx/oat/arm64/Generated5819756368461140727.odex: No such file or directory
06-04 20:49:44.089 18087 18087 I installd: installd cannot open vdex file during dexopt/data/user/0/abc.efg.higcom/app_dx/oat/arm64/Generated5819756368461140727.vdex: No such file or directory

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `   d to decompile and b to recompile uisng aapt and aapt2

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files --- NO 
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  yes 
2. If you are trying to install a modified apk, did you resign it?  yes i did 
3. Are you using the latest apktool version? yes . and i tried other old version also gave me same results

**Comment by batssmasher** [comment]
anyone can help ?

**Comment by iBotPeaches** [comment]
Based on the naming of generate OAT files. Looks like some sort of anti-tamper measure that produces files at runtime. So not sure anything Apktool can do here unless you find a mistake somewhere in decompilation.

**Comment by batssmasher** [comment]
Thanks for your reply . there is another line . can you please hint what is this mean ? Thanks 

06-06 14:51:28.231 19941 19941 D installd: Mismatched cache GID/mode at /data/user/0/abc.efg.higcom/app_dx/oat: found 10001/448 but expected 10001/601

what is Mismatched cache GID/mode ? does this check for signature ?
