### ISSUE TITLE
Release unstable builds?

### ISSUE THREAD

**Issue by AndnixSH** [iBotPeaches/Apktool#2586]
Is there any change you can release unstable builds every commit using https://nightly.link/ or something?
I'm not sure if this is automated build or not but i hope so, i have seen most repos are using it. this would be great to test unstable build quickly without having to compile myself, because my system can't handle buggy IntelliJ well

**Comment by iBotPeaches** [comment]
master builds will have artifacts on actions now

example: https://github.com/iBotPeaches/Apktool/actions/runs/931944733
commit: https://github.com/iBotPeaches/Apktool/commit/f5885a4763acec238d7297865713b2cf7464d399

**Comment by AndnixSH** [comment]
That's great, thanks!
