### ISSUE TITLE
[BUG]  Apps recompiling problem....

### ISSUE THREAD

**Issue by Anonymous2716** [iBotPeaches/Apktool#2590]
### Information
1. **Apktool Version (`apktool -2.5.0`)** -
2. **Operating System (Linux (nethunter Kali Linux android))** -
3. **APK From? (apkpure)** -
4. JDK 9

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Ans : yes 
![Screenshot_20210619-043547](https://user-images.githubusercontent.com/78570872/122622708-5ea0f280-d0bb-11eb-90d5-32c81a184815.png)

APK name **2go.apk**

Solution please.....

**Comment by iBotPeaches** [comment]
I don't see any error to work from here except the generic 132. Might be running 32bit binaries on a 64 bit machine, but that can't be since those 32 bit binaries are gone.

Not enough details to replicate so closing.
