### ISSUE TITLE
[BUG] Issues with resources.arsc modification

### ISSUE THREAD

**Issue by josephpat** [iBotPeaches/Apktool#2593]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** -  Windows
3. **APK From? (Playstore, ROM, Other)** -  Samsung OneUI 3.0

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
2. Decompile systemui.apk, modify any color under res\values\colors.xml and re-compile

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[s20-framework-res.zip](https://github.com/iBotPeaches/Apktool/files/6685319/s20-framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[s20-SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/6685316/s20-SystemUI.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Issue is noticed only if modification is made within res\values for e.g. colors.xml. Compilation is successful, but the file does not load in the ROM. The tray is missing. Tried using the method of replacing the modified resources.arsc in the original apk file but same issue.  It was also noticed that the ROM does not show icons of the apk if the resources.arsc file is modified. 
If changes are made in res\layout, this issue is not seen.
2. If you are trying to install a modified apk, did you resign it? tried signing, tried without signing, tried replacing resources.asrc in original apk
3. Are you using the latest apktool version? Yes, 2.5.0

**Comment by iBotPeaches** [comment]
These issues are never easy to track down. You'd have to follow the resource in the compiled state and compare it to the rebuilt compiled state with some of those available tools to check properties/etc.

I don't have this device/phone so chances of myself identifying the resource(s) having issues is next to zero. So I'm just going to close this as I don't see any movement happening here.
