### ISSUE TITLE
[BUG] APK decodes, but fails to build again

### ISSUE THREAD

**Issue by Diniboy1123** [iBotPeaches/Apktool#2607]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM

I wanted to modify the FM Radio app from my pixel experience rom. For that I grabbed the FM2.apk file and the whole /system/framework folder and ran `apktool d .\FM2.apk --frame-path .\framework -f`. Then tried to build it without any modifications to see if I can get back an apk, using `apktool b .\FM2 --frame-path .\framework` but I got the following error:

```
W: D:\Build\apktool\.\FM2\res\values\public.xml:43: error: Public symbol drawable/album_border_large.1 declared here is not defined.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Redacted\AppData\Local\Temp\brut_util_Jar_1884207553441732465510783059802433167.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 30, --version-code, 30, --version-name, 11, --no-version-vectors, -F, C:\Users\Redacted\AppData\Local\Temp\APKTOOL2207194698478310925.tmp, -e, C:\Users\Redacted\AppData\Local\Temp\APKTOOL8722985202636939215.tmp, -0, arsc, -I, .\framework\1.apk, -S, D:\Build\apktool\.\FM2\res, -M, D:\Build\apktool\.\FM2\AndroidManifest.xml]
```

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool d .\FM2.apk --frame-path .\framework -f`
2. `apktool b .\FM2 --frame-path .\framework`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

Find it in the apk folder.

### APK
If this APK can be freely shared, please upload/attach a link to it.

Both the framework and the apk can be found here: https://mega.nz/folder/aOp0HRyA#AseBI-5MWYrjzJ-EdvGSZA

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? not yet
3. Are you using the latest apktool version? yes

**Comment by Diniboy1123** [comment]
Actually deleting the line simply in public.xml fixed the issue as the resource is not used anywhere. Then the build succeeded. I am just wondering why would this happen?

**Comment by iBotPeaches** [comment]
```
➜  2607 apktool if framework-res.apk -t 2607
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-2607.apk
➜  2607 apktool d FM2.apk -t 2607
I: Using Apktool 2.5.1-d1e447-SNAPSHOT on FM2.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-2607.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2607 
➜  2607 apktool b FM2 --use-aapt2
I: Using Apktool 2.5.1-d1e447-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2607 
```

Looks to work fine in aapt2. My guess not compatible with aapt1.

**Comment by Diniboy1123** [comment]
Thanks for checking! The only way to get this version would be to self compile?

**Comment by iBotPeaches** [comment]
> Thanks for checking! The only way to get this version would be to self compile?

No, it was added years ago.
