### ISSUE TITLE
[BUG] [ERROR]

### ISSUE THREAD

**Issue by grim-cypher** [iBotPeaches/Apktool#2608]
**### _Unable to recompile apk without makes any changes_**

`$ apktool d Signal\ Private\ Messenger_v5.15.6_apkpure.com.apk 
I: Using Apktool 2.5.1-66b1c3-SNAPSHOT on Signal Private Messenger_v5.15.6_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/grim/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
                                                                                                                                                                        

└─$ apktool b Signal\ Private\ Messenger_v5.15.6_apkpure.com    
I: Using Apktool 2.5.1-66b1c3-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /home/grim/Desktop/project/android-reverse/Signal Private Messenger_v5.15.6_apkpure.com/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_75978546799141502315106885426555840503.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 87302, --version-name, 5.15.6, --no-version-vectors, -F, /tmp/APKTOOL17035197645978918592.tmp, -e, /tmp/APKTOOL1887947035379232494.tmp, -0, arsc, -I, /home/grim/.local/share/apktool/framework/1.apk, -S, /home/grim/Desktop/project/android-reverse/Signal Private Messenger_v5.15.6_apkpure.com/res, -M, /home/grim/Desktop/project/android-reverse/Signal Private Messenger_v5.15.6_apkpure.com/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
```
W: invalid resource directory name: /home/grim/Desktop/project/android-reverse/Signal Private Messenger_v5.15.6_apkpure.com/res navigation
```

You'll want to build with `--use-aapt2`

**Comment by grim-cypher** [comment]
how I can solve it or  anybody have any suggestion..

**Comment by iBotPeaches** [comment]
> how I can solve it or anybody have any suggestion..

I literally just told you. Use `--use-aapt2` on build.
