### ISSUE TITLE
[BUG] Manifest meta-data numeric string value can be reencoded with non-string type

### ISSUE THREAD

**Issue by codylund** [iBotPeaches/Apktool#2611]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows (but should impact all)
3. **APK From? (Playstore, ROM, Other)** - Test APK

### Steps to Reproduce
1. Add `<meta-data>` item with numeric string value in the AndroidManifest.xml of any APK using the workaround mentioned in [this StackOverflow thread](https://stackoverflow.com/questions/2154945/how-to-force-a-meta-data-value-to-type-string). E.g. `<meta-data name="int_as_string" value="\ 12345" />`. Build the apk.
2. Decompile the apk using `apktool d /path/to/apk`.

Expected: decoded meta-data item has numeric value prepended with "\ " to preserve as a string value when APK is rebuilt.
Actual: decoded AndroidManifest.xml has numeric value prepended with " ". When rebuilt, the space character is lost and the value is encoded as numeric value "12345".

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
Reproducible in any APK using the repro steps above.

**Comment by AndnixSH** [comment]
Try `value="\12345" />` or `value="\u00312345" />`

I heard the similar issue with Unity game https://forum.unity.com/threads/unity-application-id-must-be-a-numeric-value-please-verify-that-your-manifest-refers-to-the-correct.544070/

**Comment by iBotPeaches** [comment]
Resolved in https://github.com/iBotPeaches/Apktool/pull/2612
