### ISSUE TITLE
can't recompile a app

### ISSUE THREAD

**Issue by amun3t** [iBotPeaches/Apktool#2614]
`Compiling APK file...

/c "java -Xmx1024m -jar "C:\Program Files (x86)\APK Easy Tool\Apktool\apktool_2.4.1.jar" b -f -o "C:\Users\user\Documents\APK Easy Tool\2-Recompiled APKs\app.apk" "C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\app" "

I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: invalid resource directory name: C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\app\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_9142119573343019009.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 60202, --version-name, 6.2.2, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL8334978864975531318.tmp, -e, C:\Users\user\AppData\Local\Temp\APKTOOL4322585372626330892.tmp, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\app\res, -M, C:\Users\user\Documents\APK Easy Tool\1-Decompiled APKs\app\AndroidManifest.xml]`

**Comment by AndnixSH** [comment]
Try use aapt2 `--use-aapt2`

**Comment by iBotPeaches** [comment]
No application attached, but changes are with the `res navigation` warning. You'll need to rebuild with as @AndnixSH mentioned with aapt2.

Closing.
