### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amun3t** [iBotPeaches/Apktool#2616]
Some apps are unable to recompile after decompiled the app, one of them is anydesk. Are there any solution to solve it?

**Comment by AndnixSH** [comment]
You are not following issue template and not posting any logs, so i'm unable to give you proper answer
But most cases is anti-tampering protection. You need to look into it yourself because it is beyond the scope of apktool

**Comment by iBotPeaches** [comment]
As mentioned above. Not enough information to go on here.
