### ISSUE TITLE
I CAN'T GET RID OF THE OLDER VERSION

### ISSUE THREAD

**Issue by elsho7** [iBotPeaches/Apktool#2656]
When I installed apktool for the first time I have installed APKTOOL 2.4.3, recently, I downloaded APKTOOL 2.6 and followed steps as in the official site, yet, I seem not to be able to migrate the version. when I excute (apktool+ apktool.jar) It shows me that I am on version 2.6 but when I run command ( apktool -v) it shows me that I'm still on 2.4.3.
WHAT AM I DOING WRONG?

### Information
1. **Apktool Version (`2.4.3`)** -
2. **Operating System (Kali Linux)** -
3. **APK From? (Playstore, ROM, Other)** -

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?  trying to migrate from 2.4.3 to 2.6

**Comment by iBotPeaches** [comment]
Your helper script `apktool` may be pointing to an older version. You'll want to check what that file is loading and update that one.

Apktool has nothing to do with this, its just updating a binary jar.

**Comment by hwac121** [comment]
same issue. Completey uninstalled older version through synaptic, tried to install the new version following the instructions on the apktool website perfectly. Yet when I check version inn terminal it still shows the old version installed. Kali Linux...
