### ISSUE TITLE
Remove default values from variables after decompile

### ISSUE THREAD

**Issue by KarmaMod** [iBotPeaches/Apktool#2657]
Apktool usually left default values intact after decompile even from modded APK that was compiled from previous version but  worse because Apktool have added defaults values like false on all vartiables after compile (I noticed it has been resolved on 2.6.0)

But comparing APK is still a headache due to this, that caused comparision software show too many results. Can't apktool remove all default values from variables after decompile?

![image](https://user-images.githubusercontent.com/88159598/132677441-e5a63a5a-62ae-44ee-a265-1c8039fe128d.png)

**Comment by iBotPeaches** [comment]
I don't think smali had a single change in last release to how parameters are returned. Might have to dig on this.

**Comment by MrIkso** [comment]
I don't see any critical changes in the screenshot. As it was null or false, so it remained

**Comment by KarmaMod** [comment]
> I don't see any critical changes in the screenshot. As it was null or false, so it remained

But i can't compare the smali files because of this. It makes the results too many, making comparsion very hard

**Comment by KarmaMod** [comment]
I figure out I could replace all useless falses and nulls with blank using 010 editor, now the comparision results is much better. Process doesn't take long time
