### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LordArrin** [iBotPeaches/Apktool#2659]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 18.04
3. **APK From? (Playstore, ROM, Other)** - Play Market

### Stacktrace/Logcat

root@LordArrinUb:/home/user# java -jar apktool.jar d phone.apk
I: Using Apktool 2.6.0 on phone.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
root@LordArrinUb:/home/user# java -jar apktool.jar b phone -o /2
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/user/phone/res/font/google_sans.xml:2: error: No resource identifier found for attribute 'fontProviderSystemFontFamily' in package 'android'
W: 
W: /home/user/phone/res/font/google_sans_medium.xml:2: error: No resource identifier found for attribute 'fontProviderSystemFontFamily' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_84631905993871771874607954362567483684.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 30, --version-code, 7902879, --version-name, 70.0.394259711-publicbeta-go, --no-version-vectors, -F, /tmp/APKTOOL14352751364921173936.tmp, -e, /tmp/APKTOOL18083494990155721198.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/user/phone/res, -M, /home/user/phone/AndroidManifest.xml]

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://play.google.com/store/apps/details?id=com.google.android.dialer

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Just decompile without changes
2. If you are trying to install a modified apk, did you resign it?
No
3. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment]
Apologies, I somehow missed this ticket entirely so now its a few months later.

I pulled down the latest dialer apk and ran it through the unreleased 2.6.2 and all seems to be working.

```
➜  2659 apktool d com.google.android.dialer_6201989_apps.evozi.com.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-df3b9f-SNAPSHOT on com.google.android.dialer_6201989_apps.evozi.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Skipping staged alias stagedId (1fe0000) finalId: 1020055
I: Skipping staged alias stagedId (1fe0001) finalId: 1020056
I: Skipping staged alias stagedId (1fe0002) finalId: 1020057
I: Skipping staged alias stagedId (1ff0000) finalId: 101064c
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2659 apktool b com.google.android.dialer_6201989_apps.evozi.com --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-df3b9f-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: brut_util_Jar_12365391204773459448461866639168218665.tmp W 03-21 07:38:38 242340 242340 LoadedArsc.cpp:711] Unknown chunk type '200'.
I: Copying libs... (/lib)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2659 
```

So I'm closing, unsure which ticket might have resolved this, but apologies again for missing this.

**Comment by LordArrin** [comment]
Okay) But when we see 2.6.2?)
