### ISSUE TITLE
[BUG] decompile and compile apk but doesn't install

### ISSUE THREAD

**Issue by MH140000** [iBotPeaches/Apktool#2661]
### Information
1. **Apktool Version (`apktool -version`)** -
2.6
2. **Operating System (Mac, Linux, Windows)** -
windows
3. **APK From? (Playstore, ROM, Other)** -
other
### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. apktool d test.apk
2. apktool b test

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://cdn.down-apk.com/dk.bearware.gui/TeamTalk_5.8.1_apkcombo.com.apk?ecp=ZGsuYmVhcndhcmUuZ3VpLzUuOC4xLzEwNi4xYjM5NDU2MDk3ZjBlZjQ2MWI5MjhmN2UzZmU3YTAyZmM0NWQ2ZmQ3LmFwaw==&iat=1631904668&sig=0414b906a0768603c9b1db8ca074af0c&size=150703993&from=cf&version=latest
or
https://apkcombo.com/teamtalk/dk.bearware.gui/download/apk
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes
i want edit teamtalk apk, but when i decompile and recompile it, i can not install. please fix!

**Comment by Minori100** [comment]
i have this error too with Amino.apk

**Comment by orv11** [comment]
i have this error too with Amino.apk

**Comment by MH140000** [comment]
I need edit teamtalk apk. Please help

در تاریخ شنبه 18 سپتامبر 2021،‏ 0:17 Minori100 ***@***.***>
نوشت:

**Comment by MH140000** [comment]
Hi. The problem is the software signature. I bypassed the signature verification with other software and the problem was solved.

**Comment by iBotPeaches** [comment]
> i want edit teamtalk apk, but when i decompile and recompile it, i can not install. please fix!

Not seeing any details here, but it seems its signature related. So closing.
