### ISSUE TITLE
[BUG] Tag <provider> missing required attribute name.

### ISSUE THREAD

**Issue by AndnixSH** [iBotPeaches/Apktool#2663]
### Information
1. **Apktool Version (`apktool -version`)** - Apktool 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
PS R:\> java -jar apktool_2.6.0.jar d "R:\Soul Land Reloaded_1.1.6_apkcombo.com.apk"
I: Using Apktool 2.6.0 on Soul Land Reloaded_1.1.6_apkcombo.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\x\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling assets/audience_network.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
PS R:\> java -jar apktool_2.6.0.jar b "R:\Soul Land Reloaded_1.1.6_apkcombo.com"
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: R:\Soul Land Reloaded_1.1.6_apkcombo.com\AndroidManifest.xml:11: Tag <provider> missing required attribute name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\x\AppData\Local\Temp\brut_util_Jar_432334194602934730918786219380466270.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 16, --version-name, 1.1.6, --no-version-vectors, -F, C:\Users\x\AppData\Local\Temp\APKTOOL1205792922906901530.tmp, -e, C:\Users\x\AppData\Local\Temp\APKTOOL3303192295385742710.tmp, -0, arsc, -I, C:\Users\x\AppData\Local\apktool\framework\1.apk, -S, R:\Soul Land Reloaded_1.1.6_apkcombo.com\res, -M, R:\Soul Land Reloaded_1.1.6_apkcombo.com\AndroidManifest.xml]
PS R:\>
```

### Steps to Reproduce
1. `java -jar apktool_2.6.0.jar d`
2. `java -jar apktool_2.6.0.jar b`

### Frameworks
N/A

### APK
https://apkcombo.com/apk-downloader/?package=com.soullandrl.gp&device=default&arches=armeabi-v7a&sdkInt=default&format=apk&dpi=480&lang=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. Are you using the latest apktool version? Yes

**Comment by eladkarako** [comment]
not 100% sure it is a bug with APKTool or the way aapt decodes the binary AndroidManifest.xml.

I've got few APKs that were built for SDK30,  
and have this issue as well.

Both <code>aapt d xmltree com.package.apk AndroidManifest.xml</code>,  
and AXMLPrinter2.jar from <a href="https://code.google.com/archive/p/android4me/downloads">https://code.google.com/archive/p/android4me/downloads</a> have the same result, with <a href="https://developer.android.com/guide/topics/manifest/provider-element"><code>provider</code></a> floats outside of <code>application</code>..  :/ 

There might be a need to employ <a href="https://developer.android.com/studio/command-line/aapt2">aapt2</a> in both decoding and building process now,  
maybe the XML-binary format has changed in some way.

<hr/>

you can still try to build the APK using <code>b</code> and <code>--use-aapt2</code>.
it most likely will finish without showing you any errors, but you might not get a working APK.

I usually keep using aapt(1), manually fixing some of the XML errors (duplications, invalid values, and such),  
and when it reaches that provider error you've got I switch to building with <code>--use-aapt2</code>.

<hr/>

I know there is a <a href="https://developer.android.com/studio/command-line/apkanalyzer">apkanalyzer</a> that is part of the Android building tools you get when you install Android Studio,  
but I haven't figured out how to make it portable to suggest including it in APKTool, it got a lot of dependencies! 
 
<hr/>
I know there is a (closed) issues for asking to migrate to aapt2 
https://github.com/iBotPeaches/Apktool/issues/1689 
but there isn't seems to be any progress in there,  
so if you still don't get a working APK I'm afraid you have little to do,  
other than look in apkmirror or similar sites for an older build (preferably one that targets a SDK lower than 29),  
those seems to still work with APKTool.

**Comment by AndnixSH** [comment]
Again, just removing:
```
    <queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider"/>
    </queries>
```
lets you compile. No issue with the app so far

But apparently, the dev fixed it so it become
```
    <queries>
        <package android:name="com.facebook.katana"/>
    </queries>
```
and it's now compileable without any fix.
I think i will close this issue

**Comment by kyze8439690** [comment]
Manually add android:name="xxx" in <provider /> will bypass this error, everything still works.
