### ISSUE TITLE
Modifying Settings app causes Bootloop/App disappears

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#2665]
###Information

First of all, I have all the necessary components;

I'm trying to modify my Settings app, with framework-res.apk added as the framework required. I don't have any framework installed either. I don't have any problem decompiling and building, I also sign the Settings.apk with "Uber Apk Signer", I have tried my own signature as well, but Uber seemed way more efficient. Problem is, when install Settings.apk, it either causes Bootloops or the Settings app disappeares from launcher.

Android 9/Samsung Port Rom

### Steps to Reproduce

1. apktool if framework-res.apk
2. apktool d settings.apk
3. apktool b settings
4. java -jar Uber.jar --apks Settings.apk
5. Installation causes Bootloop/App disappeares.

### Frameworks

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/7232089/framework-res.zip)

### APK

 ( I CANNOT ADD IT BECAUSE GITHUB DOES NOT ALLOW ME [is not included in the list.])

###Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? Yes.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment]
Do you happen to have an `adb logcat` of the exact failure during installation? It has some extra info

**Comment by Voidbuilt** [comment]
> Do you happen to have an `adb logcat` of the exact failure during installation? It has some extra info

Because its a System app (and furthermore being Settings app) I can't install it through Package Installer. I used Lucky Patcher 
to install the Apk as System app with almost every possible different ways, manually replaced it on "system/priv-app", it either disappeared or caused Bootloop. So I'm not sure exactly where to take the Logcat to be honest.

**Comment by mariodantas** [comment]
Have exactly the same problem with Settings app API29, but I noticed that apktool (when decompile APK) builds a different /res tree (i.e. "res/anim" and "res/anim-v21" in Original and only "res/anim" once decompiled)

**Comment by iBotPeaches** [comment]
Unfortunately never triaging this in a timely manner and the original poster deleting their account and no logcat with no Samsung device owned. I don't see this going anywhere. Closing.
