### ISSUE TITLE
apktool says "built apk" but no file is created...

### ISSUE THREAD

**Issue by DiegoRRR** [iBotPeaches/Apktool#2666]
Hello

apktool was still working yesterday, then for some reason today it does not work anymore.
I still use the very same commands and the very same folders.
Moreover, it does not show any error, it says "built apk", but the apk file is not created anymore...

_D:\sites\dom83\games\qui_mange_qui\app>apktool b source_apk
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
D:\sites\dom83\games\qui_mange_qui\app>_

I also looked in "C:\Users\<my user name>\AppData\Local\Temp" but there is nothing related to it there.

Any idea ? Or is this a bug ?

**Comment by Voidbuilt** [comment]
Have you looked at "D:\sites\dom83\games\qui_mange_qui\app\dist"? Built Apks located at "dist" folder under your decompile folder.

**Comment by DiegoRRR** [comment]
Yes, there is nothing else in \app\ than my "source_apk" folder.
No "dist" folder is created. I created one and tried again, but it stayed empty.

**Comment by iBotPeaches** [comment]
Not sure what to say. If that output appears, the file would be in `/dist` relative to the app directory. I don't see any other error that would say otherwise.

**Comment by DiegoRRR** [comment]
Why did you close ? My problem is not resolved.

**Comment by iBotPeaches** [comment]
> Why did you close ? My problem is not resolved.

Because I do not replicate the issue. There is not enough details here to prove an issue occurred and this is a bug tracker, not support.
