### ISSUE TITLE
[FEAT] Remove APKTOOL_DUMMY

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2683]
**Is your feature request related to a problem? Please describe.**
Apktool creates a lot of unnecessary APKTOOL_DUMMY, which means nothing but empty space, but in the output file they take up space as dead weight.

**Describe the solution you'd like**
Delete or comment out the code chunks that cause APKTOOL_DUMMY.

**Additional context**
For example, apk https://www.apkmirror.com/apk/google-inc/gboard/gboard-10-9-03-387080390-release/gboard-the-google-keyboard-10-9-03-387080390-lite_release-arm64-v8a-android-apk-download/
`aapt2 dump resources Gboard.apk > res.txt`
for three apks: original, re-compiled, and re-compiled using apktool without APKTOOL_DUMMY.
Compare logs res.txt which one is closer to the original? In addition, the output file size increases
: original 33.0 mb, output with APKTOOL_DUMMY 33.4 mb, without APKTOOL_DUMMY 33.1 mb
[res.txt](https://github.com/iBotPeaches/Apktool/files/7365855/res.txt)
[res_dummy.txt](https://github.com/iBotPeaches/Apktool/files/7365856/res_dummy.txt)
[res_nodummy.txt](https://github.com/iBotPeaches/Apktool/files/7365858/res_nodummy.txt)

**Comment by iBotPeaches** [comment]
We tried this [once](https://github.com/iBotPeaches/Apktool/pull/2463) and I was hesitant, maybe for 3.0. Marking as feature.

**Comment by Marrysmithgs** [comment]
I tried. Can you help me out in [Jolly APK](https://jollyapk.com/) site. I want to scrape apk from direct Play store.
