### ISSUE TITLE
[FEAT] multi-threaded rebuilds

### ISSUE THREAD

**Issue by spiralw** [iBotPeaches/Apktool#2685]
**Is your feature request related to a problem? Please describe.**

I am rebuilding a large project, and this takes some time (more than a minute). I have a pretty strong CPU, and it looks like apktool is only using a single CPU core, while there are many more unused.

**Describe the solution you'd like**

I would like to see apktool use multiple threads, preferably with a way to choose how many (defaulting to 1).

**Additional context**

![h](https://user-images.githubusercontent.com/64013111/138021249-dc27fc16-e8d4-45ee-88ad-68c8f967f43c.png)

**Comment by iBotPeaches** [comment]
I'll be honest. I don't have the knowledge to do this and it would additionally require correctly calling aapt/aapt2 in a threaded environment which I do not know if possible.

I'll throw it on the roadmap and close this.

https://github.com/iBotPeaches/Apktool/commit/fb140dcb3bb40b25cab17ad0e659915bc12b3792
