### ISSUE TITLE
[FEAT] Publish also apktool-cli

### ISSUE THREAD

**Issue by ThexXTURBOXx** [iBotPeaches/Apktool#2686]
**Is your feature request related to a problem? Please describe.**
Some projects, e.g. [BytecodeViewer](https://github.com/Konloch/bytecode-viewer) are using the `apktool-cli` module, which is not published yet.

**Describe the solution you'd like**
The `apktool-cli` module could be published in Maven Central as well.
I know, it doesn't really make sense to publish a CLI application, but some projects depend on this simple class and need to manually include it for now.

**Comment by iBotPeaches** [comment]
![apktool-cli-published](https://user-images.githubusercontent.com/611784/140734750-3f1db73d-2936-4dbe-bac7-70c63b64d514.png)

Next release (2.6.1) will have this. Tested it out and working on snapshot/staging.
