### ISSUE TITLE
[FEAT] zip ultra compression for apk

### ISSUE THREAD

**Issue by eladkarako** [iBotPeaches/Apktool#2688]
the build process is already zipping things up,  
but I need that better compression ration in some cases,  
so I often unzip and rezip with 7zip and this drag and drop script: https://gist.github.com/eladkarako/027a3aadd957538ed4a3053e190e9d80#file-cmd-windows-whole-folder-without-the-folder-itself-to-zip-using-7zip-multithreaded-maximum-compression-legacy-compatible-format-suitable-for-jar-and-apk-prevents-overwriting-by-a-mistake-cmd

I wish there was a way to plug an external tool for that part of the build (I.E. the "finish" step), that would accept some arguments, since there are not some many variations, the most important stuff is compatibility and compression ratio, so even making it somehow an internal command line switch (compression ratio of apk - store/normal/ultra) is probably sufficient.

**Comment by iBotPeaches** [comment]
I don't see Apktool doing anything like this. It would require major refactoring.
