### ISSUE TITLE
[BUG] Error copying file: res

### ISSUE THREAD

**Issue by Luffitys** [iBotPeaches/Apktool#2690]
### Information
1. **Apktool Version** - Latest binary from GitHub Actions
2. **Operating System** - Windows 11 22494.1000
3. **APK From?** - OEM (Xiaomi, MIUI)

### Stacktrace/Logcat

```
C:\Users\Luffitys\Downloads\Porting-Tools\Porting-Tools>java -jar apktool.jar b --no-crunch   --output MiuiCamera.apk MiuiCamera_DECOMPILED
I: Using Apktool 2.6.1-d29411-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: Error copying file: res
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. `apktool b`

### Frameworks
None required

### APK
The decompiled APK can be found here, just git clone it:
https://github.com/Luffitys/MiuiCamera-21.7.28_eu_venus-Mod

### Other Infos
Since res can't be fully copied, apps can't launch due to missing res files.
I never had issues on Windows 10 and early Windows 11 builds. Possibly Apktool is incompatible with newer Windows Insiders?
Sometimes, though rarely (can't get the log as I can't reproduce it) the compilation also fails at the "I: Building apk file..." part, saying the file is already in use by some other program, which is not the case since there are no running background programs.

**Comment by iBotPeaches** [comment]
> I never had issues on Windows 10 and early Windows 11 builds. Possibly Apktool is incompatible with newer Windows Insiders?

Not sure. Not seeing anything in your logs that indicate that. I also don't really see an adb logcat, so unsure what is wrong.
