### ISSUE TITLE
[BUG] Case-sensitivity issues on Windows

### ISSUE THREAD

**Issue by jpstotz** [iBotPeaches/Apktool#2697]
### Information
* **Apktool Version 2.6.0** -
* **Operating System Windows 10 64bit native (no WSL)** -
* * Java: Eclipse Adoptium OpenJDK 11

### Steps to Reproduce
* `apktool d --no-res --no-src <apk-filename>`
* Alternatively  `apktool d <apk-filename>`

If you decompile an APK on Windows which contains resource files or other entries that only differ in their file name case, apktool shows no warning indicating that the decompilation failed. In my opinion apktool should show a warning or error if it overwrites a file when extracting resources or other files (unless `-f` option is set). 

This would also be useful on Linux in case an file entry exists more than one time in the APK file (this should still be possible or does newer Android versions reject such APK files?).

**Comment by iBotPeaches** [comment]
Unfortunately a long time known issue.

https://github.com/iBotPeaches/Apktool/issues/1460

---

Android rejects files that attempt this in the APK. This was used for some injections attacks where the application was signed for `AndroidManifest.xml`, but `androidManifest.xml` could be in application and in some situations loaded over the other. This was way back in Gingerbread if memory is right.

**Comment by jpstotz** [comment]
@iBotPeaches This feature request was not about solving all the Windows problems but instead warning if a file is overwritten.
