### ISSUE TITLE
> Not seeing anything reported here. Closing.

### ISSUE THREAD

**Issue by gorwhh** [iBotPeaches/Apktool#2710]
> Not seeing anything reported here. Closing.
> 
> _Originally posted by @iBotPeaches in https://github.com/iBotPeaches/Apktool/issues/2704#issuecomment-980547767_

_Originally posted by @gorwhh in https://github.com/gorwhh/sherlock/issues/1#issuecomment-982799428_

**Comment by iBotPeaches** [comment]
What is this? Why did you spam me with like 8 emails of this? I don't even understand.
