### ISSUE TITLE
[BUG] Cannot recompile spotify apk with no edits

### ISSUE THREAD

**Issue by Liquidbone** [iBotPeaches/Apktool#2711]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - windows
3. **APK From? (Playstore, ROM, Other)** - playstore

### Stacktrace/Logcat

```
Include stacktrace here
C:\Users\16106\Desktop\apktool>apktool b spotify_base spotifytest.apk
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: C:\Users\16106\Desktop\apktool\spotify_base\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\16106\AppData\Local\Temp\brut_util_Jar_128038637624702607041705202138114026425.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 80223162, --version-name, 8.6.80.1014, --no-version-vectors, -F, C:\Users\16106\AppData\Local\Temp\APKTOOL16031928875362047192.tmp, -e, C:\Users\16106\AppData\Local\Temp\APKTOOL7545019742522558324.tmp, -0, arsc, -I, C:\Users\16106\AppData\Local\apktool\framework\1.apk, -S, C:\Users\16106\Desktop\apktool\spotify_base\res, -M, C:\Users\16106\Desktop\apktool\spotify_base\AndroidManifest.xml] 
```

### Steps to Reproduce
1. `apktool d`
2. `apktool b` 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? YES

**Comment by dschrempf** [comment]
I can confirm this error with a different apk.

**Comment by AndnixSH** [comment]
have you tried `--use-aapt2`? because `res navigation` error is usually caused by aapt 1

**Comment by dschrempf** [comment]
I don't see any documentaation about `--use-aapt2`. Is this flag used during decoding or building? Isn't the  new `aapt` used by default, or does `apktool` ship two versiond of `aapt`?

Thanks for your help!

**Comment by AndnixSH** [comment]
aapt 1 is used by default but old, and yes they ship two versions. The documentation is here https://ibotpeaches.github.io/Apktool/documentation/
While it is not clear, but the developer highly recommended to use aapt2 for better compatibility

**Comment by iBotPeaches** [comment]
Yes as mentioned above and sorry for delay. `--use-aapt2` will resolve this. It indeed is in docs under the rebuild category - https://ibotpeaches.github.io/Apktool/documentation/#rebuild
