### ISSUE TITLE
[BUG] error: No resource identifier found for attribute 'allowNativeHeapPointerTagging' in package 'android' when decompiling and rebuilding

### ISSUE THREAD

**Issue by JoeyRosicka** [iBotPeaches/Apktool#2712]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0 on app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/administrator/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling assets/audience_network.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/administrator/Downloads/app/AndroidManifest.xml:30: error: No resource identifier found for attribute 'allowNativeHeapPointerTagging' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/bd/dy0ydf6j2m76yg9pqs66xlkh0000gn/T/brut_util_Jar_20300348832377290397088723987002600988.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 7925, --version-name, 2.7.3, --no-version-vectors, -F, /var/folders/bd/dy0ydf6j2m76yg9pqs66xlkh0000gn/T/APKTOOL6231971702294544276.tmp, -e, /var/folders/bd/dy0ydf6j2m76yg9pqs66xlkh0000gn/T/APKTOOL3503922786815494529.tmp, -0, arsc, -I, /Users/administrator/Library/apktool/framework/1.apk, -S, /Users/administrator/Downloads/app/res, -M, /Users/administrator/Downloads/app/AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool d app.apk`
2. `apktool b app`

### APK
The APK cannot be shared publicly. 

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? Not trying to install a modified apk, just trying to decompile and rebuild.
3. Are you using the latest apktool version? Yes, 2.6.0.

The change we made to our app which triggered this issue was adding `android:allowNativeHeapPointerTagging="false"` to the main AndroidManifest before building. The build succeeds, but the decompile+rebuild fails. This is a Unity app.

**Comment by iBotPeaches** [comment]
Not much I can do sadly with the unable to share application, but I know this attribute (`allowNativeHeapPointerTagging`) was added in API30 and while we are currently broken supporting the latest API 31 Final, since this was added in 30. The internal framework should know exactly what that attribute is.

There is some bug https://github.com/iBotPeaches/Apktool/issues/2514 that I was digging into when an application has multiple packages inside 1 resspec and this leads the manifest parser to load/reference, this eerily seems familiar in a way but can't be quite sure.

Going to close, because I've referenced what I believe it might be and linked to a ticket it also might be.

**Comment by JoeyRosicka** [comment]
> Hello, have you been able to fix it the issue of app crashing with Targeted SDK 30? I am stuck at the same issue.

Oddly enough, I was able to avoid running into the issue when running on a different machine despite being on the same version of Apktool. I have not been able to get the time to look into why yet, but I'll reply here if I figure that out.

**Comment by JoeyRosicka** [comment]
> Hello, have you been able to fix it the issue of app crashing with Targeted SDK 30? I am stuck at the same issue.

@Original-Tasty I took another look at this and was able to find a solution. Here's what I did:

1. Update to the latest version of apktool with brew
2. Install API level 30 (or higher) of the Android SDK through Android Studio
3. Delete ~/Library/apktool/framework
4. Re-run apktool commands

I believe the issue was that the apk that got generated when running apktool needed to be regenerated after updating apktool and installing the proper version of the Android SDK.

**Comment by UCYT5040** [comment]
> > Hello, have you been able to fix it the issue of app crashing with Targeted SDK 30? I am stuck at the same issue.
> 
> @Original-Tasty I took another look at this and was able to find a solution. Here's what I did:
> 
>     1. Update to the latest version of apktool with brew
> 
>     2. Install API level 30 (or higher) of the Android SDK through Android Studio
> 
>     3. Delete ~/Library/apktool/framework
> 
>     4. Re-run apktool commands
> 
> 
> I believe the issue was that the apk that got generated when running apktool needed to be regenerated after updating apktool and installing the proper version of the Android SDK.

@JoeyRosicka I'm on windows, where is the apktool/framework directory?

**Comment by JoeyRosicka** [comment]
> @JoeyRosicka I'm on windows, where is the apktool/framework directory?

Unsure, since I'm only familiar with apktool on Mac

**Comment by GuillianSeed** [comment]
> > > Hello, have you been able to fix it the issue of app crashing with Targeted SDK 30? I am stuck at the same issue.
> > 
> > 
> > @Original-Tasty I took another look at this and was able to find a solution. Here's what I did:
> > ```
> > 1. Update to the latest version of apktool with brew
> > 
> > 2. Install API level 30 (or higher) of the Android SDK through Android Studio
> > 
> > 3. Delete ~/Library/apktool/framework
> > 
> > 4. Re-run apktool commands
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe the issue was that the apk that got generated when running apktool needed to be regenerated after updating apktool and installing the proper version of the Android SDK.
> 
> @JoeyRosicka I'm on windows, where is the apktool/framework directory?

Users\xxxx\AppData\Local\apktool\framework
