### ISSUE TITLE
@npmccallum In the case of official "Google Authenticator" app I'm using (3.1.1, iOS), it seems to ignore the label prefix, and only display Issuer when it is specified as a parameter.

### ISSUE THREAD

**Issue by gorwhh** [iBotPeaches/Apktool#2717]
@npmccallum In the case of official "Google Authenticator" app I'm using (3.1.1, iOS), it seems to ignore the label prefix, and only display Issuer when it is specified as a parameter.

_Originally posted by @rophy in https://github.com/freeotp/freeotp.github.io/pull/51#issuecomment-809862683_

**Comment by gorwhh** [comment]
> @npmccallum In the case of official "Google Authenticator" app I'm using (3.1.1, iOS), it seems to ignore the label prefix, and only display Issuer when it is specified as a parameter.
> 
> 
> 
> _Originally posted by @rophy in https://github.com/freeotp/freeotp.github.io/pull/51#issuecomment-809862683_

**Comment by iBotPeaches** [comment]
@gorwhh - Please stop. I don't know what you are doing, but its just making issues in Apktool for seemingly no reason.
