### ISSUE TITLE
modificare il package

### ISSUE THREAD

**Issue by 71frankray** [iBotPeaches/Apktool#2718]
Spero che qualcuno di Voi che siete esperti mi possiate aiutare, purtroppo con la mia età (77) ho dei limiti sono stato bravino a  realizzare alcune applicazioni di giochini matematici con app inventor, ma non riesco a modificare per come devono  essere per play store. Ho provato android studio, apk easy tool, ma non riesco ad eseguire correttamente come dovrei; per ultimo con apktool inserendo framework-re-apk mi da errore. E' possibile avere un tutorial dettagliato per poter eseguire la modifica con il mio windows 10
Francesco

**Comment by iBotPeaches** [comment]
I'm sorry. I'm not sure what is being reported here.
