### ISSUE TITLE
"error: attribute android:fontProviderSystemFontFamily not found" observed with apktool 2.6.0

### ISSUE THREAD

**Issue by swetasamasti2310** [iBotPeaches/Apktool#2720]
### Information
1. **Apktool Version (`apktool -version`)** - apktool_2.6.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
activity_main.xml:30: error: attribute android:fontProviderSystemFontFamily not found.
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
I added this attribute during a framework update prior to 2.6.0. So I think you just need to ensure frameworks are up to date.

You can use `apktool empty-framework-dir` if you wish to automate that.
