### ISSUE TITLE
[BUG] error: resource 'attr/unused_res_a' has a conflicting value for configuration

### ISSUE THREAD

**Issue by playscforever** [iBotPeaches/Apktool#2723]
### Information
1. **Apktool Version  2.6.0 ** -
2. **Operating System  Mac ** -
3. **APK From ** - [target_apk](https://ip45959535.out.azhimalayanvh.com/fs08/2021/12/28/6/123_707a8358c1ae8bf433342ee328192707.apk?yingid=wdj_web&fname=%E7%88%B1%E5%A5%87%E8%89%BA%E6%9E%81%E9%80%9F%E7%89%88&productid=2011&pos=wdj_web%2Fdetail_normal_dl%2F0&appid=8129199&packageid=801043273&apprd=8129199&iconUrl=http%3A%2F%2Fandroid-artworks.25pp.com%2Ffs08%2F2021%2F12%2F29%2F3%2F110_678b285053b9bc6c5e53b25fd6db97ed_con.png&pkg=com.qiyi.video.lite&did=27b067798a57b18a3f8871d7ba38db17&vcode=116&md5=28ae5ca25fec0f6de67bb12a18b0ea49&ali_redirect_domain=alissl.ucdl.pp.uc.cn&ali_redirect_ex_ftag=4b787dff1b4617d8eeed2f32826e1bef9025f4bd35fb8605&ali_redirect_ex_tmining_ts=1640944652&ali_redirect_ex_tmining_expire=3600&ali_redirect_ex_hot=100)

### Stacktrace/Logcat
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/zhangjin.yan/playground/jisu/res/values/^attr-privates.xml:3: error: resource 'attr/unused_res_a' has a conflicting value for configuration ().
W: /Users/zhangjin.yan/playground/jisu/res/values/attrs.xml:3: note: originally defined here.
W: /Users/zhangjin.yan/playground/jisu/build/resources.zip@values_^attr-privates.arsc.flat: error: failed to merge resource table.
W: error: failed parsing input.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/brut_util_Jar_3036513281863069585863734696770035323.tmp, link, -o, /var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/APKTOOL1079813232718793348.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 116, --version-name, 1.12.5, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/APKTOOL4785362460886860538.tmp, -0, arsc, -I, /Users/zhangjin.yan/Library/apktool/framework/1.apk, --manifest, /Users/zhangjin.yan/playground/jisu/AndroidManifest.xml, /Users/zhangjin.yan/playground/jisu/build/resources.zip]
### Steps to Reproduce
1. apktool d jisu.apk
2. apktool b jisu/ -o new_jisu.apk --use-aapt2

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  yes
2. If you are trying to install a modified apk, did you resign it?  yes
3. Are you using the latest apktool version?  yes,include 2.6.0 2.4.1 2.5.0

**Comment by playscforever** [comment]
I tried to delete conflicting value (^attr-privates.xml:3). still error 


W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:66: error: resource attr/APKTOOL_DUMMY_72 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_72) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:69: error: resource attr/APKTOOL_DUMMY_72 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_72) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:166: error: resource attr/APKTOOL_DUMMY_87 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_87) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:186: error: resource attr/APKTOOL_DUMMY_87 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_87) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:251: error: resource attr/APKTOOL_DUMMY_87 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_87) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:274: error: resource attr/APKTOOL_DUMMY_1e0 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_1e0) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:275: error: resource attr/APKTOOL_DUMMY_1aa (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_1aa) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values-land/styles.xml:5: error: resource attr/APKTOOL_DUMMY_1e2 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_1e2) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values-land/styles.xml:6: error: resource attr/APKTOOL_DUMMY_1aa (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_1aa) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:280: error: resource attr/APKTOOL_DUMMY_1e2 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_1e2) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:311: error: resource attr/APKTOOL_DUMMY_4c (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_4c) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:370: error: resource attr/APKTOOL_DUMMY_5e (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_5e) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:372: error: resource attr/APKTOOL_DUMMY_5e (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_5e) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:510: error: resource attr/APKTOOL_DUMMY_8f (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_8f) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:586: error: resource attr/APKTOOL_DUMMY_8f (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_8f) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:603: error: resource attr/APKTOOL_DUMMY_8f (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_8f) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:621: error: resource attr/APKTOOL_DUMMY_71 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_71) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:622: error: resource attr/APKTOOL_DUMMY_72 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_72) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:623: error: resource attr/APKTOOL_DUMMY_85 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_85) not found.
W: /Users/zhangjin.yan/playground/jisu/res/values/styles.xml:629: error: resource attr/APKTOOL_DUMMY_71 (aka com.qiyi.video.lite:attr/APKTOOL_DUMMY_71) not found.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/brut_util_Jar_2363750580414972668666722714470413696.tmp, link, -o, /var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/APKTOOL116514100359995730.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 116, --version-name, 1.12.5, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /var/folders/_l/tjmh5lds0zv6c53rpjtmblnj_g_6k0/T/APKTOOL998442080482380443.tmp, -0, arsc, -I, /Users/zhangjin.yan/Library/apktool/framework/1.apk, --manifest, /Users/zhangjin.yan/playground/jisu/AndroidManifest.xml, /Users/zhangjin.yan/playground/jisu/build/resources.zip]

**Comment by playscforever** [comment]
@iBotPeaches please help

**Comment by iBotPeaches** [comment]
Apologies. Application is not downloadable for me so unable to dig into this. Closing.
