### ISSUE TITLE
[BUG][Windows] Files having reserved Windows names will not decompile

### ISSUE THREAD

**Issue by Mino260806** [iBotPeaches/Apktool#2728]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Amin\Documents\APK Easy Tool\1-Decompiled APKs\brevent\res\values\public.xml:2262: error: Public symbol mipmap/con declared here is not defined.
```

### Steps to Reproduce
1. [Required] Use a Windows computer 
2. `apktool d app.apk`
3. `apktool b app`
**Further investigation**
4. rename `app.apk` to `app.zip`
5. open `app.zip` with any program you want
6. navigate to `res/mipmap-*/` (open all mipmap folders)
7. notice a file named `con.png` (or `con.xml` if you open `mipmap-anydpi-v26`)
![image](https://user-images.githubusercontent.com/53614199/147856212-e5a69872-1762-4ff5-8181-893f2f6c4087.png)
8. now go back to the decompiled `app` folder
9. navigate to `res/mipmap-*/` (open all mipmap folders)
10. notice all these folders are empty

## Why does this bug happen ?
In Windows computers, there are some reserved file names which you can never name a file with them. See [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

![image](https://user-images.githubusercontent.com/53614199/147855942-3a54fc2f-dd8e-40c9-93d3-83d24fecc7b2.png)

But the same doesn't apply for other operating systems, something which makes us face a big problem: if an apk file has been compiled on an operating system other than windows (e.g linux), they can name their files with some reserved names. That's the issue you will face after decompiling this apk because `con` in this example is part of the reserved windows file names.

### Possible solution
Introduce an ignorable character: when unzipping the apk, if a file is part of the reserved Windows names, add some kind of symbolic character at the start or the end of it or else Windows will prevent you from extracting that file. Also maybe print a warning.

### APK
https://apkpure.com/brevent/me.piebridge.brevent

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  **Yes**
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? **Yes**

**Comment by iBotPeaches** [comment]
Thanks for the detailed report, unforunately we've known about this issue and have not made any progress on it in years. 

https://github.com/iBotPeaches/Apktool/issues/1460

So marking as duplicate and closing.
