### ISSUE TITLE
[BUG] Unchanged decompile-compile failed

### ISSUE THREAD

**Issue by j-kaltes** [iBotPeaches/Apktool#2732]
### Information
1. **Apktool Version (`apktool -version`)** -
v2.6.0
2. **Operating System (Mac, Linux, Windows)** 
Linux
3. **APK From? (Playstore, ROM, Other)** -
Google Play, German
### Stacktrace/Logcat
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /n/ojka/src/android/libre3-de-decomp4/com.freestylelibre3.app.de/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_11310612877348730778962283601146973460.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 30, --version-code, 9092, --version-name, 3.3.0, --no-version-vectors, -F, /tmp/APKTOOL207593853469472841.tmp, -e, /tmp/APKTOOL9049972941892586565.tmp, -0, arsc, -I, /home/jka/.local/share/apktool/framework/1.apk, -S, /n/ojka/src/android/libre3-de-decomp4/com.freestylelibre3.app.de/res, -M, /n/ojka/src/android/libre3-de-decomp4/com.freestylelibre3.app.de/AndroidManifest.xml]

### Steps to Reproduce
apktool d ../com.freestylelibre3.app.de.apk 
apktool b com.freestylelibre3.app.de     
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/freestyle-libre-3---de/com.freestylelibre3.app.de
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
You'll want to use aapt2. Then it should work.
