### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MartyK87** [iBotPeaches/Apktool#2733]
### Information
1. **Apktool Version (`apktool -version`)** - 1.59.2 Portable
2. **Operating System (Mac, Linux, Windows)** - Window 7 X64
3. **APK From? (Playstore, ROM, Other)** - Root Dir

### Stacktrace/Logcat
------------------------------------------
10/01/2022 2:45:13 PM

Checking for update...
A new version is available: 1.59.2
Reading APK...

Decompiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\Apktool\apktool_2.5.0.jar" d -f --only-main-classes -o "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer" "C:\Users\Admin\Desktop\Dialer.apk"

I: Using Apktool 2.5.0 on Dialer.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Decompile successful.
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\Apktool\apktool_2.5.0.jar" b -f -o "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_16754134773534522365664401554050099444.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 30, --version-code, 2900000, --version-name, 23.0, --no-version-vectors, -F, C:\Users\Admin\AppData\Local\Temp\APKTOOL391611265042964664.tmp, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL836379230181804754.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer\res, -M, C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer\AndroidManifest.xml]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\Apktool\apktool_2.5.0.jar" b -f -o "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_6712702851476459071937871750792044702.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 30, --version-code, 2900000, --version-name, 23.0, --no-version-vectors, -F, C:\Users\Admin\AppData\Local\Temp\APKTOOL5700307870198120813.tmp, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL5859914094813609224.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer\res, -M, C:\Users\Admin\Downloads\Compressed\APK+Easy+Tool+v1.59.1+Portable\1-Decompiled APKs\Dialer\AndroidManifest.xml]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------
------------------------------------------
10/01/2022 3:03:54 PM

Checking for update...
Reading APK...

Decompiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" d -f --only-main-classes -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" "C:\Users\Admin\Desktop\Dialer.apk"

I: Using Apktool 2.5.0 on Dialer.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Decompile successful.
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_70884627445974032007808016405379318424.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 30, --version-code, 2900000, --version-name, 23.0, --no-version-vectors, -F, C:\Users\Admin\AppData\Local\Temp\APKTOOL4966378391890093915.tmp, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL6375330522542729482.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, -M, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\AndroidManifest.xml]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Clearing framework cache...

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" empty-framework-dir --force "

I: Removing 1.apk framework file...

Framework cache cleared
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_30490552065334334786555677504953312639.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 30, --version-code, 2900000, --version-name, 23.0, --no-version-vectors, -F, C:\Users\Admin\AppData\Local\Temp\APKTOOL8852114130652103054.tmp, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL186625799078853231.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, -M, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\AndroidManifest.xml]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------
------------------------------------------
10/01/2022 3:27:57 PM

Reading APK...
Checking for update...

Decompiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" d -f -s --only-main-classes -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" "C:\Users\Admin\Desktop\Dialer.apk"

I: Using Apktool 2.5.0 on Dialer.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Decompile successful.
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_27963302772511394725462960480514897552.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------
------------------------------------------
10/01/2022 3:30:50 PM

Reading APK...
Checking for update...

Decompiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" d -f -s -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" "C:\Users\Admin\Desktop\Dialer.apk"

I: Using Apktool 2.5.0 on Dialer.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Decompile successful.
------------------------------------------

Clearing framework cache...

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" empty-framework-dir --force "

I: Removing 1.apk framework file...

Framework cache cleared
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_68431641581328878888543560468907881537.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------
------------------------------------------
10/01/2022 3:36:43 PM

Reading APK...
Checking for update...

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_32467573516843048481653133321600119668.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_89660949309852504768806939480863787416.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_81130173117749661632839412268375380627.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_85788708936547568647219510092080767864.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_24544769941801915146769135045392490802.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Clearing framework cache...

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" empty-framework-dir --force "

I: Removing 1.apk framework file...

Framework cache cleared
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_7888742665273213272609144311977188701.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_64176167194540168919192586678841237118.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------
------------------------------------------
10/01/2022 3:39:58 PM

Reading APK...
Checking for update...

Compiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\Apktool\apktool_2.5.0.jar" b -f --use-aapt2 -o "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\2-Recompiled APKs\Dialer.apk" "C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer" 

I: Using Apktool 2.5.0
I: Copying C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer classes.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_66894871299236749347372154184853098392.tmp, compile, --dir, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\res, --legacy, -o, C:\Users\Admin\Downloads\Compressed\APK Easy Tool v1.59.2 Portable\1-Decompiled APKs\Dialer\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
------------------------------------------

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
https://www.mediafire.com/file/dbvsbs8phx8zes1/Dialer.apk/file

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? I don't know how to
2. If you are trying to install a modified apk, did you resign it? Do I need to?
3. Are you using the latest apktool version? Yes
4. I am just trying to enable a native call recording feature on LineageOS 18 on  aGalaxy S5 and to say this is doing my head in is an under statement.

**Comment by iBotPeaches** [comment]
```
➜  2733 apktool d Dialer.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.0 on Dialer.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2733 apktool b Dialer --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2733 
```

Sorry I really struggled to understand what was being reported in this very very large submission, but I could not replicate anything given the application. So closing.
