### ISSUE TITLE
explain this error when building an app 

### ISSUE THREAD

**Issue by shivanshusinghthepython** [iBotPeaches/Apktool#2734]
┌──(root💀windows)-[~]
└─# apktool b /root/original                                                                                   
I: Using Apktool 2.5.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: First type is not attr!
W: A/        ( 3638): First type is not attr!
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL12466709397763945370.tmp, -0, resources.arsc, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/original/res, -M, /root/original/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
```
 I: Using Apktool 2.5.0-dirty
```
 
well its an old build and "dirty" so I didn't make it. So not sure I'm going to take a guess here, since I didn't produce it - I don't think I should support it.

**Comment by shivanshusinghthepython** [comment]
any help?? I am new to this ! Which version should I install and where I'll get that ?

**Comment by iBotPeaches** [comment]
> any help?? I am new to this ! Which version should I install and where I'll get that ?

https://ibotpeaches.github.io/Apktool/install/

**Comment by shivanshusinghthepython** [comment]
thanks
