### ISSUE TITLE
[BUG] temp file not being deleted when building

### ISSUE THREAD

**Issue by MFinkBK** [iBotPeaches/Apktool#2739]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - probably not relevant

### Steps to Reproduce
1. `apktool b -o out extractedFolder`
2. Monitor the %TEMP% folder; during build, two `APKTOOL{longnumber}.tmp` files are created, and one of the is removed again. The other stays there.

Note that this only occurs when (re-)building, not when decompiling an .apk. After digging a bit in the source, I suspect the following lines in `buildManifest()` to be the problem:

https://github.com/iBotPeaches/Apktool/blob/9bdf3855384414d5e1060bfef263bb0e5b07460a/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java#L548-L549

Here, the temporary file is being created and then deleted again (I guess to get the temp filename). Then the filename is used in a call to `aaptPackage()`, but afterwards it isn't deleted.

Note that `buildResourcesFull()` also creates a temp filename, but deletes the created file again in line 512, and that's the difference to `buildManifest()`:

https://github.com/iBotPeaches/Apktool/blob/9bdf3855384414d5e1060bfef263bb0e5b07460a/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java#L512

**Comment by iBotPeaches** [comment]
Thanks for the research, I'll use this research and dig around in a bit and see what I can find.

**Comment by iBotPeaches** [comment]
Thanks, found em. PR is up.

**Comment by MFinkBK** [comment]
I just tested with the apktool .jar file built from the GitHub Action (the build artifact .jar named `apktool-2.6.1-ddc4bb-SNAPSHOT-small.jar`, from the run https://github.com/iBotPeaches/Apktool/actions/runs/1707904289). Unfortunately the code change doesn't fix the bug (yet). I have no skills in Java debugging, but I checked out what's logged in SysInternal's Process Monitor tool when a build runs. I attached the CSV export of the relevant log lines, here: [apktool-procmon-logfile.csv](https://github.com/iBotPeaches/Apktool/files/7882085/apktool-procmon-logfile.csv)

The APKTOOL.tmp file that isn't being removed is opened several times using Win32 API CreateFile(), which it seems is used for reading, writing, getting attributes from a file and even for deleting. The last CreateFile() call that should remove the file gets a Sharing Violation, so my guess is that some object still has a handle on the file. And there's a CreateFile call that isn't matched with a CloseFile call that may be the reason. From trying to match the calls to the code in `buildResourcesFull()`, my guess is that it's the call to `new ExtFile()` in this line that keeps the temp file open:

https://github.com/iBotPeaches/Apktool/blob/9bdf3855384414d5e1060bfef263bb0e5b07460a/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java#L498

(I guess the GC at some point collects the object and closes the file, but the `apkFile.delete()` call happens earlier than that.

**Comment by iBotPeaches** [comment]
:(

Thanks will reopen.

**Comment by MFinkBK** [comment]
My guess is that something like that would help:

    ExtFile apkFileExt = new ExtFile(apkFile);
    Directory tmpDir = apkFileExt.getDirectory();
    apkFileExt.close();

I'm not quite sure if there's another way to do that in Java.

**Comment by iBotPeaches** [comment]
Okay, next PR has to be perfect. I've done a looped build/decode of 10 applications 20 times and I have no files in /tmp. Additionally, scripted the actual building of Apktool 20 times and no /tmp files.

**Comment by MFinkBK** [comment]
I'd like to test the PR, but unfortunately the GitHub action doesn't provide a built apktool.jar, only when merged to `master`...

**Comment by MFinkBK** [comment]
Works! I tested with `apktool-2.6.1-797fc3-SNAPSHOT-small.jar`. Thanks for the effort to fix this bug, and for making apktool in the first place!
