### ISSUE TITLE
I changed the component colors but then they come back

### ISSUE THREAD

**Issue by edilsonlsouza** [iBotPeaches/Apktool#2748]
**Information**

1. Apktool Version (apktool -version)  - 2.6.0
2. Operating System (Mac, Linux, Windows) - Mac

**Steps to Reproduce**

1. apktool d kinsta.apk
2. apktool b kinsta

**Problem**

I decompiled the app, tried to replace the ex colors (ex > #5a30d6 ), everything was fine when I recompiled it.

When entering the app via apk installation, the first time it opens with the changed colors, but soon after it is closed and opened again, it goes back to the old colors.

It only comes back if you clear the data and cache in "application info".

I'm a newbie, and I can't figure it out.

Can anyone help? Thanks!

![Captura de Tela 2022-01-24 às 06 12 08](https://user-images.githubusercontent.com/57968732/150754247-e7abfd80-3d65-4f66-a124-572745762d3d.png)
![Captura de Tela 2022-01-24 às 06 11 59](https://user-images.githubusercontent.com/57968732/150754225-dbb883e8-de83-4e91-b0dc-dc57ecd53a38.png)

**Comment by iBotPeaches** [comment]
Sorry, this just seems like a request for support to help here. It looks like some hybrid application, but since I don't see a bug with Apktool here - I'm going to close this.
