### ISSUE TITLE
[BUG] dot as delimiter in naming plurals breaks apktool b

### ISSUE THREAD

**Issue by xgear-public** [iBotPeaches/Apktool#2755]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - macOS 12.1
3. **APK From? (Playstore, ROM, Other)** - Doesn't matter, I faced with this issue with a specific game from Playstore, but it is reproducible on apk that is just generated from new project wizard from Android Studio (please check steps below).

### Steps to Reproduce
1. Open Android Studio and create default android project with empty activity (AS - File - New - New Project... ).
2. After new project created go to res -> values and create plurals.xml
3. In plurals.xml create plurals resource with the following name (**the key is to use dot as delimiter in naming**):
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <plurals name="naming.with.dots.someplural">
        <item quantity="other">Other</item>
        <item quantity="one">One</item>
    </plurals>
</resources>
```
4. Build debug apk.
5. take this apk and run `apktool d`, `apktool b` without changing anything, you should get something like
`app-debug/res/values/plurals.xml:7: error: Error retrieving parent for item: No resource found that matches the given name 'naming.with.dots'.`
'7' line number is not 3 because our plural goes after plural resource from material lib (so they were just merged) but it doesn't matter
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <plurals name="mtrl_badge_content_description"> <!--!!!!Merged from material lib!!!!-->
        <item quantity="other">%d new notifications</item>
        <item quantity="one">%d new notification</item>
    </plurals>
    <plurals name="naming.with.dots.someplural">
        <item quantity="other">Other</item>
        <item quantity="one">One</item>
    </plurals>
</resources>
```

This issue doesn't reproduce if you create a regular string resource with dots in the name as delimiter. I checked only plurals and string android resource types.

My guess is that this problem connected with android styles inheritance feature, but these policies shouldn't be applied on plurals resource type naming.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
- yes, that is the point of issue
2. If you are trying to install a modified apk, did you resign it? 
- can't build because of issue
3. Are you using the latest apktool version?
- yes

**Comment by pashamcr** [comment]
use aapt2
