### ISSUE TITLE
[BUG] Compiling AndroidManifest.xml error, Namespace for prefix 'tools' has not been declared

### ISSUE THREAD

**Issue by Tiger14n** [iBotPeaches/Apktool#2762]
### Information
1. **Apktool Version (`apktool 2.6.0`)** - 
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** - 

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Building resources...
I: Using aapt2 - setting 'debuggable' attribute to 'true' in AndroidManifest.xml
ERROR:  'Namespace for prefix 'tools' has not been declared.'

```

### Steps to Reproduce
1. `apktool d -f `
2. `Modifying AndroidManifest.xml`
3. `apktool b -d -f --use-aapt2`

Compiling fails after adding this to AndroidManifest.xml
```
<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    tools:node="remove">
 </provider>
```

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? ..
2. If you are trying to install a modified apk, did you resign it? ..
3. Are you using the latest apktool version? Yes

**Comment by pashamcr** [comment]
This is your [BUG]: you do not see the difference between the already prepared application manifest and the manifest (there may be several) of an application that has not yet been compiled, apktool does not build applications from source.
https://developer.android.com/studio/build/manage-manifests

**Comment by iBotPeaches** [comment]
As mentioned above by @pashamcr. Apktool does not have any of the pre-processed manifest tools like exist in Android Studio so this is unsupported behavior.
