### ISSUE TITLE
Multiple res

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2767]
**New version 2.6.1 supports multi package resources?** 

Do you also have a group/channel in Telegram?

**Comment by iBotPeaches** [comment]
> **New version 2.6.1 supports multi package resources?**

No, where did you see that? It is too difficult at the moment to patch.


> Do you also have a group/channel in Telegram?

Negative. Gitter and IRC exist, but honestly any form of real time communication for Apktool just doesn't really happen. Don't have the time.

**Comment by TimScriptov** [comment]
@iBotPeaches use getOnePackage(). Ignore others pkg
