### ISSUE TITLE
[BUG] failed to build apk

### ISSUE THREAD

**Issue by Anonymous2716** [iBotPeaches/Apktool#2772]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.2-dirty (built myself but prebuilt versions are behaving same.)
2. **Operating System (Mac, Linux, Windows)** - Android termux.
3. **APK From? (Playstore, ROM, Other)** - github

### Stacktrace/Logcat

```
❯ java -jar apktool-cli-all.jar b app-release -o o.apk -f -v
Mar 07, 2022 12:31:05 PM brut.androlib.Androlib build
INFO: Using Apktool 2.6.2-dirty
Mar 07, 2022 12:31:06 PM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali folder into classes.dex...
Mar 07, 2022 12:31:14 PM brut.androlib.Androlib buildResourcesFull
INFO: Building resources...
Mar 07, 2022 12:31:14 PM brut.util.OS$StreamForwarder run
WARNING: /data/data/com.termux/files/usr/tmp/brut_util_Jar_181455838141718945117501548740403071170.tmp[1]: ELF: not found
Mar 07, 2022 12:31:14 PM brut.util.OS$StreamForwarder run
WARNING: /data/data/com.termux/files/usr/tmp/brut_util_Jar_181455838141718945117501548740403071170.tmp[2]: syntax error: unexpected ')'
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_181455838141718945117501548740403071170.tmp, p, -v, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 31, --version-code, 94, --version-name, 5.9, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL16239476531781023972.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL9654494872194372393.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/home/app-release/res, -M, /data/data/com.termux/files/home/app-release/AndroidManifest.xml]
```

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://github.com/rkkr/simple-keyboard

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
4. If you are trying to install a modified apk, did you resign it? Couldn't build.
5. Are you using the latest apktool version? Yes

java -version
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)

Before I opened an issue but was closed bcs there was no useful info provided. If there is anything else I can submit let me know.

**Comment by iBotPeaches** [comment]
```
WARNING: /data/data/com.termux/files/usr/tmp/brut_util_Jar_181455838141718945117501548740403071170.tmp[1]: �ELF: not found
```

Sadly from this I can tell the application is running on Android. The native binaries in Apktool for aapt/aapt2 do not support the architectures needed for Android.

This is unsupported behavior.

**Comment by Anonymous2716** [comment]
Anyways I a tweak solved the issue for me  . BTW its an awesome tool.
