### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Attorelle** [iBotPeaches/Apktool#2774]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1 
2. **Operating System (Mac, Linux, Windows)** - Windows 11
3. **APK From? (Playstore, ROM, Other)** - Pixel's March Update

### Stacktrace/Logcat
https://pastebin.com/1XKfy4m9

### Steps to Reproduce
1. `apktool  -d framework-res.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/8203789/framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/8203789/framework-res.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? I trynna decompile framework-res from Pixel's (3a is my own) March Update
2. If you are trying to install a modified apk, did you resign it? I can't decompile apk lol
3. Are you using the latest apktool version? Yup

**Comment by iBotPeaches** [comment]
Yep, discovered with the newer SDK applications. Tracking in this issue - https://github.com/iBotPeaches/Apktool/issues/2740

Thanks for the report.
