### ISSUE TITLE
[FEAT] SDK_S_V2

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2776]
@iBotPeaches
https://github.com/iBotPeaches/Apktool/blob/adc9425a9aca24fc4a6878a3bbd3d15e909cbed0/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java#L540
sync:
https://android.googlesource.com/platform/frameworks/base/+/6aa3b2c86dcc8dc72b03c69e2ff3133baae4f10b%5E%21/#F2
https://android.googlesource.com/platform/ndk/+/master/meta/platforms.json

**Comment by iBotPeaches** [comment]
thanks, resolved.
