### ISSUE TITLE
[BUG] recompiling framework-res.apk: BrutException: could not exec

### ISSUE THREAD

**Issue by MichaelZ4714** [iBotPeaches/Apktool#2777]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Ubuntu, JRE 1.8
3. **APK From? (Playstore, ROM, Other)** - ROM LineageOS 17.1

### Stacktrace/Logcat

```
michael@Michael-NB:~$ java -Xmx1G -jar apktool.jar d framework-res.apk
I: Using Apktool 2.6.1 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
michael@Michael-NB:~$ rm framework-res.apk
michael@Michael-NB:~$ java -Xmx1G -jar apktool.jar b -f framework-res
I: Using Apktool 2.6.1
W: Could not find sources
I: Building resources...
W: /home/michael/framework-res/res/values/styles.xml:1186: error: Resource entry Theme.Holo already has bag item textEditSuggestionItemLayout.
W: /home/michael/framework-res/res/values/styles.xml:1185: Originally defined here.
W:
W: /home/michael/framework-res/res/values/styles.xml:1263: error: Resource entry Theme.Holo already has bag item preferenceFrameLayoutStyle.
W: /home/michael/framework-res/res/values/styles.xml:1262: Originally defined here.
W:
W: /home/michael/framework-res/res/values/styles.xml:1272: error: Resource entry Theme.Holo already has bag item textEditSuggestionContainerLayout.
W: /home/michael/framework-res/res/values/styles.xml:1271: Originally defined here.
W:
W: /home/michael/framework-res/res/values/styles.xml:1274: error: Resource entry Theme.Holo already has bag item textEditSuggestionHighlightStyle.
W: /home/michael/framework-res/res/values/styles.xml:1273: Originally defined here.
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_43386357171912751674315810965939010057.tmp, p, --forced-package-id, 1, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 29, --version-name, 10, --no-version-vectors, -F, /tmp/APKTOOL3843393482111694310.tmp, -x, -e, /tmp/APKTOOL6614178133780900354.tmp, -0, arsc, -S, /home/michael/framework-res/res, -M, /home/michael/framework-res/AndroidManifest.xml]
michael@Michael-NB:~$

```

### Steps to Reproduce
1. `apktool ` d framework-res.apk
2. `apktool ` b -f framework-res

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://zoellner.selfhost.de/public/Android/framework-res.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
    yes
3. Are you using the latest apktool version?
    yes

### Reason for decompile/compile
I want to change res/xml/config_webview_packages.xml in framework-res.apk. Bromite Webview uses the new package name org.bromite.webview instead of  com.android.webview as before in earlier releases. The Magisk module WebviewManager only works on one of my two devices, so I want to adopt the resource file for the other device. Any other possibility than modifying framework-res.apk?

**Comment by iBotPeaches** [comment]
```
➜  2777 apktool d framework-res.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.1-ddc4bb-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2777 apktool b framework-res --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.1-ddc4bb-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warn: invalid package ID 0x01. Must be in the range 0x7f-0xff. Ignoring....
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2777 
```

I can't seem to replicate using aapt2.

**Comment by MichaelZ4714** [comment]
Dear Connor,
have many thanks for showing me the switch --use-aapt2. Probably this switch could be mentioned in the program builtin help and in the documentation page https://ibotpeaches.github.io/Apktool/documentation/ ? But I'm not sure if I would have recognized the importance of that switch as a noob...
Many Greetings
Michael

**Comment by BlackMesa123** [comment]
> Mind updating a new issue with a sample? These are unrelated issues

My fault, I used the GitHub search feature and should've commented in #2503 instead
