### ISSUE TITLE
In Android 12 , Decompiled apk error - There was a problem while parsing the package

### ISSUE THREAD

**Issue by sahilkundu** [iBotPeaches/Apktool#2779]
**Information
Apktool Version (apktool -version) - Latest
Operating System (Mac, Linux, Windows) - Kali Linux (Debian)**
I was attempting to decompile this APK(attached modified.apk as well as original.apk) but not change simply Decompile and Recompile (**NOTE :- WITHOUT ANY CHANGE**) and when i trying to install this, I am facing a errror "There was a problem while parsing the package".
No error during decompile and recompile the apk file as shown in images attached.
![IMG_20220313_081950](https://user-images.githubusercontent.com/71582663/158043063-856adf1c-7439-4645-a708-eea36b07c843.jpg)
![Screenshot_2022-03-13-08-23-37-082_com google android packageinstaller](https://user-images.githubusercontent.com/71582663/158043070-e3d4b83d-f54a-4a04-8dbf-a89e95d55b6d.jpg)
Orighinal apk : https://drive.google.com/file/d/19i2jE6TOXh0vXO2MH_MnzDoJ3c5v9yAi/view?usp=sharing
Modified apk (**simply without changing ,only decompile and recompile, signed**):-  https://drive.google.com/file/d/1OTUW1BJ3A7kyiKAcB5xCnPC9OJboHp6W/view?usp=sharing

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly.

You'll want to pull ADB logs during installation as it will have this real crash reason.

**Comment by iBotPeaches** [comment]
Closing for no response.
