### ISSUE TITLE
Facing problem while binding Payloads (recompile)

### ISSUE THREAD

**Issue by Prince01github** [iBotPeaches/Apktool#2782]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Nethunter
3. **APK From? (Playstore, ROM, Other)** -FbLite.apk from apkpure
### Stacktrace/Logcat

```

```
Using APK template: /sdcard/fb.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.gjvak
[*] Loading /tmp/d20220314-29626-1xsp3wf/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20220314-29626-1xsp3wf/output.apk
[-] I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_69221135822979910956479523302603090470.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 31, --version-code, 354975467, --version-name, 293.0.0.9.114, --no-version-vectors, -F, /tmp/APKTOOL5540271027132335925.tmp, -e, /tmp/APKTOOL3082563400059542143.tmp, -0, arsc, -I, /home/kali/.local/share/apktool/framework/1.apk, -S, /tmp/d20220314-29626-1xsp3wf/original/res, -M, /tmp/d20220314-29626-1xsp3wf/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment]
Status code 132 is commonly an architecture issue when running the native binaries. It could be 32 vs 64 bit as well.

Closing.
