### ISSUE TITLE
[BUG] Can't recompile app. "Could not smali file"

### ISSUE THREAD

**Issue by besendorf** [iBotPeaches/Apktool#2784]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - https://appmaker.greatfire.org/

 ### Error Message
```
$ apktool d de.fefe.blog.apk
I: Using Apktool 2.6.0 on de.fefe.blog.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/user/.local/share/apktool/framework/1.apk
I: Renamed manifest package found! Replacing de.fefe.blog with org.greatfire.freebrowser
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling assets.dex...
I: Baksmaling classes2.dex...
I: Baksmaling assets/webapk7.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
[user@spreewald fefe_app]$ apktool b de.fefe.blog
de.fefe.blog/         de.fefe.blog.apk      de.fefe.blog.apk.zip
[user@spreewald fefe_app]$ apktool b de.fefe.blog
de.fefe.blog/         de.fefe.blog.apk      de.fefe.blog.apk.zip
[user@spreewald fefe_app]$ apktool b de.fefe.blog/
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
de.fefe.blog/smali_assets/webapk7/androidx/core/graphics/drawable/IconCompatParcelizer.smali[499,9] Class Landroidx/core/graphics/drawable/IconCompatParcelizer; has already been interned
Could not smali file: webapk7/androidx/core/graphics/drawable/IconCompatParcelizer.smali
```
### Steps to Reproduce
1. `apktool d`
2. `apktool b`

### APK
https://www.file-upload.net/download-14878350/de.fefe.blog.apk.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
3. If you are trying to install a modified apk, did you resign it? yes
4. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
You can use `--only-main-classes` during disassemble as the extra smali packages in /assets are attempting to be disassmbled.

After that, you'll hit two known issues

 - https://github.com/iBotPeaches/Apktool/issues/2514
 - https://github.com/iBotPeaches/Apktool/issues/2740

**Comment by iBotPeaches** [comment]
Yep as I mentioned there are other issues you'll encounter and I believe they are related to the two issues I linked.
