### ISSUE TITLE
No resource identifier found for attribute 'usesPermissionFlags' in package 'android'

### ISSUE THREAD

**Issue by shyche** [iBotPeaches/Apktool#2789]
### Information
1. **Apktool Version (`apktool -version`)** -Apktool 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Mac 11.4
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool ` 2.6.1
2.  AndroidManifest.xml add :  

`<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />`

### Frameworks
android 12 ,     /Android/sdk/build-tools/31.0.0

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
I: Using Apktool 2.6.1
I: Copying /Users/shyche/Projects/BuildProjects/TT/android/apk classes.dex file...
I: Copying /Users/shyche/Projects/BuildProjects/TT/android/apk classes2.dex file...
I: Building resources...
W: /Users/shyche/Projects/BuildProjects/TT/android/apk/AndroidManifest.xml:3: error: **No resource identifier found for attribute 'usesPermissionFlags' in package 'android'**

**Comment by maonanyue** [comment]
I have the same problem, when there is this following configuration  in AndroidManifest.xml  
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />

**Comment by maonanyue** [comment]
> I have the same problem, when there is this following configuration in AndroidManifest.xml `<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />`

Build apktool from sources solved the problem.

**Comment by iBotPeaches** [comment]
I couldn't replicate this on latest, so I'm pushing a test addition to catch this for regressions and closing.

**Comment by HexPandaa** [comment]
Unfortunately, it still happens for on `2.7.0`. (And building from source fails for some reason).

```bash
> apktool b target/
I: Using Apktool 2.7.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
W: /<redacted>/target/AndroidManifest.xml:6: error: No resource identifier found for attribute 'usesPermissionFlags' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_175040400618570929621914966860136298007.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 1400070, --version-name, 14.0.7, --no-version-vectors, -F, /tmp/APKTOOL6500584181806763095.tmp, -e, /tmp/APKTOOL13269563881160254236.tmp, -0, arsc, -I, /home/<redacted>/.local/share/apktool/framework/1.apk, -S, /<redacted>/target/res, -M, /<redacted>/target/AndroidManifest.xml]
```

**Comment by diyaps** [comment]
same issue.

> Unfortunately, it still happens for me on `2.7.0`. (And building from source fails for some reason).
> 
> ```shell
> > apktool b target/
> I: Using Apktool 2.7.0
> I: Smaling smali folder into classes.dex...
> I: Smaling smali_classes3 folder into classes3.dex...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Building resources...
> W: /<redacted>/target/AndroidManifest.xml:6: error: No resource identifier found for attribute 'usesPermissionFlags' in package 'android'
> W: 
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_175040400618570929621914966860136298007.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 1400070, --version-name, 14.0.7, --no-version-vectors, -F, /tmp/APKTOOL6500584181806763095.tmp, -e, /tmp/APKTOOL13269563881160254236.tmp, -0, arsc, -I, /home/<redacted>/.local/share/apktool/framework/1.apk, -S, /<redacted>/target/res, -M, /<redacted>/target/AndroidManifest.xml]
> ```

**Comment by Guruthegreat22** [comment]
I am also facing the same problem....if u found the solution please help me ..

**Comment by Guruthegreat22** [comment]
> same issue.
> 
> > Unfortunately, it still happens for me on `2.7.0`. (And building from source fails for some reason).
> > ```shell
> > > apktool b target/
> > I: Using Apktool 2.7.0
> > I: Smaling smali folder into classes.dex...
> > I: Smaling smali_classes3 folder into classes3.dex...
> > I: Smaling smali_classes2 folder into classes2.dex...
> > I: Building resources...
> > W: /<redacted>/target/AndroidManifest.xml:6: error: No resource identifier found for attribute 'usesPermissionFlags' in package 'android'
> > W: 
> > brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_175040400618570929621914966860136298007.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 1400070, --version-name, 14.0.7, --no-version-vectors, -F, /tmp/APKTOOL6500584181806763095.tmp, -e, /tmp/APKTOOL13269563881160254236.tmp, -0, arsc, -I, /home/<redacted>/.local/share/apktool/framework/1.apk, -S, /<redacted>/target/res, -M, /<redacted>/target/AndroidManifest.xml]
> > ```

Please help me out

**Comment by diyaps** [comment]
> > same issue.
> > > Unfortunately, it still happens for me on `2.7.0`. (And building from source fails for some reason).
> > > ```shell
> > > > apktool b target/
> > > I: Using Apktool 2.7.0
> > > I: Smaling smali folder into classes.dex...
> > > I: Smaling smali_classes3 folder into classes3.dex...
> > > I: Smaling smali_classes2 folder into classes2.dex...
> > > I: Building resources...
> > > W: /<redacted>/target/AndroidManifest.xml:6: error: No resource identifier found for attribute 'usesPermissionFlags' in package 'android'
> > > W: 
> > > brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_175040400618570929621914966860136298007.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 1400070, --version-name, 14.0.7, --no-version-vectors, -F, /tmp/APKTOOL6500584181806763095.tmp, -e, /tmp/APKTOOL13269563881160254236.tmp, -0, arsc, -I, /home/<redacted>/.local/share/apktool/framework/1.apk, -S, /<redacted>/target/res, -M, /<redacted>/target/AndroidManifest.xml]
> > > ```
> 
> Please help me out

hi, you can try to delete framework caches and build it again.
