### ISSUE TITLE
[FEAT] Decompile localeapks_zipped resources

### ISSUE THREAD

**Issue by BlackMesa123** [iBotPeaches/Apktool#2798]
**Is your feature request related to a problem? Please describe.**
In their SecSettings apk for Android 12 (don't know if the same occurs in AOSP or for other vendors), Samsung seems to have moved their localized strings resources inside their assets resources under the "localeapks_zipped" folder. The folder contains a list of .7z files with inside an apk (they seem to be RRO's actually) for each locale.

**Describe the solution you'd like**
Repacking every file as-it-is again once it has been modified is probably difficult to achieve, so the best solution imho is to simply decompile every .apk in the folder and add the new resources in the current decompiled apk environment.

**Additional context**
It seems to not apply only to the SecSettings apk. By checking in their S22 firmware (S901BXXU1AVA8) I found that this way of handling translated strings is also used in apps such as Secure Folder, Privacy Dashboard, SoundAlive and more.

![1](https://user-images.githubusercontent.com/13062958/163556592-384278c0-d81e-4e19-a597-478a0f57964c.png)

![2](https://user-images.githubusercontent.com/13062958/163556597-7cf5a7f8-42f9-488e-8299-210234088ed9.png)

**Comment by iBotPeaches** [comment]
Is this a documented AOSP feature somewhere or a customized iteration by Samsung? I can't find any docs on this format you describe.

**Comment by BlackMesa123** [comment]
> Is this a documented AOSP feature somewhere or a customized iteration by Samsung? I can't find any docs on this format you describe.

If you're talking about this localeapks_zipped folder, I'm pretty sure it's a custom implementation made by Samsung, even though I couldn't find any reference to this in system frameworks (I probably didn't look at it correctly, I've been busy with other stuff). Regarding RRO's, I'm talking about overlays apk, they are documented by Google [(here)](https://source.android.com/devices/architecture/rros)

**Comment by BlackMesa123** [comment]
Nvm just found it, it's a system app made by samsung called "Locale Overlay Manager", here's the apk in case you want to take a look

[LocaleOverlayManager.zip](https://github.com/iBotPeaches/Apktool/files/8645252/LocaleOverlayManager.zip)

**Comment by iBotPeaches** [comment]
I struggle supporting just the arsc/axml/9png formats. I don't think I'll take on another. Thanks for the idea though, but I am going to close.
