### ISSUE TITLE
 The /tmp directory uses noexec and cannot be compiled successfully

### ISSUE THREAD

**Issue by zhangbo8418** [iBotPeaches/Apktool#2801]
**Is your feature request related to a problem? Please describe.**
 The /tmp directory uses noexec and cannot be compiled successfully

**Describe the solution you'd like**
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_17348329290619558056131118810208084008.tmp

**Additional context**
Can you customize this tmp directory？

**Comment by iBotPeaches** [comment]
You can use `-a` and deliver a location to a valid aapt binary. You can even download the same aapt binaries Apktool uses here - https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt
