### ISSUE TITLE
apktool fails to exec

### ISSUE THREAD

**Issue by Rootman55** [iBotPeaches/Apktool#2808]
hi mate,let me begin by saying i love your work.Im aware that and apoligise that this  query may be in the wrong place please bear with me.i have sucessfully managed to get L3MON to run on my laptop i386 arch have been trying for weeks to get it running on my phone armhf arch i have been reading online and came across a user asking why thay could not run apktool in nethunter (android) where you reply that this is not possible as to ARM not being currently compatible. Just about to give up and came across this video on youtube https://youtu.be/h7BRL0azRl8 where someone is running an andoid emulator and manages to create the apk without java  or any apktool errors.. i already have openjdk 8 jre installed like in the video but continuous  errors.Im reaching out to you rather than anyone else on this as i know you have the knowledge. Thanks for your time pal i  have included my email tjmoses765@gmail.com.

**Comment by iBotPeaches** [comment]
> Im reaching out to you rather than anyone else on this as i know you have the knowledge. 

Thanks for reaching out, but sadly running Apktool on Android itself is not supported. Any platform/tutorial doing so is on your own risk/path. I can't begin to officially support or debug issues on that platform.
