### ISSUE TITLE
[BUG] SHA-256 checksums of original + recompiled dex files do not match, even without modifications. is this normal?

### ISSUE THREAD

**Issue by GamerGirlandCo** [iBotPeaches/Apktool#2812]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool d --no-res`
2. `apktool b --use-aapt2`

### Frameworks
N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://play.google.com/store/apps/details?id=com.drakeet.purewriter

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
Yes.
2. If you are trying to install a modified apk, did you resign it?
i didn't modify it, but i did resign it.
3. Are you using the latest apktool version?
No.

**Comment by iBotPeaches** [comment]
> SHA-256 checksums of original + recompiled dex files do not match, even without modifications. is this normal?

Yes.
