### ISSUE TITLE
[BUG] Failed to parsing, Android 12

### ISSUE THREAD

**Issue by ibratabian17** [iBotPeaches/Apktool#2814]
### Information
1. **Apktool Version 2.6.1***
2. **Operating System Windows** -
3. **APK From? APKPURE** -

### Stacktrace/Logcat

```
05-18 20:46:11.422 24576 25200 W PackageParsing: Unknown element under <application>: enable-feature at /storage/emulated/0/Just Dance Now_v4.8.0_apkpure.com.apk Binary XML file line #132
05-18 20:46:11.422 24576 25200 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-18 20:46:13.729 24576 25221 W PackageParsing: Unknown element under <application>: enable-feature at /storage/emulated/0/Just Dance Now_v4.8.0_apkpure.com.apk Binary XML file line #132
05-18 20:46:13.729 24576 25221 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-18 20:46:26.006 24576 25271 W PackageParsing: Unknown element under <application>: enable-feature at /storage/emulated/0/Just Dance Now_v4.8.0_apkpure.com.apk Binary XML file line #132
05-18 20:46:26.006 24576 25271 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-18 20:47:14.022  3152 25343 W NetworkScheduler: Error inserting flex_time=3444000 job_id=-1 period=6889000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=221514000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1652881634020 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]
05-18 20:47:17.960  1697 10484 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package4137437621302766592.apk flg=0x10000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (has extras)} from uid 10161
05-18 20:47:18.027 12247 12247 W PackageInstaller: Parse error when parsing manifest. Discontinuing installation
```

### Steps to Reproduce
1. `apktool d "Just..." `
2. `apktool b "Just..."`

### APK
https://apkpure.com/id/just-dance-now/com.ubisoft.dance.JustDance/download/184-APK

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
3. If you are trying to install a modified apk, did you resign it? No
4. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
All the logs above look like warnings, but I see the PackageInstaller parse error. Am I missing the true error line?

Not seeing anything to go on.

**Comment by ibratabian17** [comment]
looks like I cut the log too much

**Comment by ibratabian17** [comment]
@iBotPeaches 

`05-24 14:41:41.854 10863 10946 W PackageParsing: Unknown element under <application>: enable-feature at /storage/emulated/0/Just Dance Now_v5.4.3_apkpure.com.apk Binary XML file line #132
05-24 14:41:41.854 10863 10946 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-24 14:41:44.113 10863 10976 W PackageParsing: Unknown element under <application>: enable-feature at /storage/emulated/0/Just Dance Now_v5.4.3_apkpure.com.apk Binary XML file line #132
05-24 14:41:44.114 10863 10976 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-24 14:41:46.589  1772  4399 I ActivityTaskManager: START u0 {act=android.intent.action.INSTALL_PACKAGE dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package2003290099668005007.apk flg=0x10000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (has extras)} from uid 10161
05-24 14:41:46.652 10997 10997 W PackageParsing: Unknown element under <application>: enable-feature at /data/user_de/0/com.google.android.packageinstaller/no_backup/package2003290099668005007.apk Binary XML file line #132
05-24 14:41:46.653 10997 10997 I PackageParsing: com.ubisoft.dance.JustDance: compat added android.permission.OTHER_SENSORS
05-24 14:41:46.653 10997 10997 W PackageInstaller: Parse error when parsing manifest. Discontinuing installation`

**Comment by iBotPeaches** [comment]
Sorry for delay @ibratabian17. I don't see anything to work from in these logs.

**Comment by eladkarako** [comment]
works for me with:  

`--verbose decode -no-debug-info --force --force-manifest --output "project_just"`   
[log_last_decode.log](https://github.com/iBotPeaches/Apktool/files/9127883/log_last_decode.log)  

`--verbose build --force-all --no-crunch --use-aapt2 "project_just"`  
[log_last_build.log](https://github.com/iBotPeaches/Apktool/files/9127884/log_last_build.log)  

using `2022-07-10__2.6.2-7a2c0c-SNAPSHOT__smali_2.5.2__baksmali_2.5.2` (and [this](https://github.com/eladkarako/android) ).  

might be a long path or the fact that the folder has spaces in it, or a crunch issue.

**Comment by iBotPeaches** [comment]
Closing apologies. I don't see any way to make progress on this.
