### ISSUE TITLE
[BUG] when assets/ contain assets/, the file no copy to dir when call apktool b

### ISSUE THREAD

**Issue by moyy** [iBotPeaches/Apktool#2820]
### Information
1. Apktool Version 2.6.1
2. Operating System: Windows
3. APK From Android Studio

### Stacktrace/Logcat

None

### Steps to Reproduce

0, ready base.apk, which assets/ as follow

``` txt
assets/
    a/
        Assets/
        a.txt
```

##### 2, the base/ is ok, which contains as follow

``` txt
assets/
    a/
        Assets/
        a.txt
        b.txt
```

##### 3, java -jar -Duser.language=en apktool_2.6.1.jar -o base_1.apk b --use-aapt2 base

the base_1.apk also contain assets/a/Assets/a.txt, as zip decode as well

##### 4, java -jar -Duser.language=en apktool_2.6.1.jar -o base_1 d base_1.apk

now, the assets no contain  assets/a/Assets/a.txt and assets/a/Assets/b.txt

**Comment by iBotPeaches** [comment]
Yep this is an odd issue I remember well in our backlog, since I could not understand why it was isolated too Windows - https://github.com/iBotPeaches/Apktool/issues/2574
