### ISSUE TITLE
change color of whatsapp[BUG]

### ISSUE THREAD

**Issue by techwindow** [iBotPeaches/Apktool#2822]
### Information
1. apktool version: 2.6.1
2. system: Windows
3. apk source: Playstore

### Stacktrace/Logcat

C:\Users\Ritesh\Desktop\apktool>apktool b whatsapp
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: Failed to generate resource table for split ''
W: C:\Users\Ritesh\Desktop\apktool\whatsapp\res\values\colors.xml:947: error: Er
ror: No resource found that matches the given name (at 'primary' with value '@co
lor/#FFC0CB').
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit
 code = 1): [C:\Users\Ritesh\AppData\Local\Temp\brut_util_Jar_406260541639187749
14106323731981030975.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --
target-sdk-version, 30, --version-code, 221108004, --version-name, 2.22.11.8, --
no-version-vectors, -F, C:\Users\Ritesh\AppData\Local\Temp\APKTOOL17169761622675
90350.tmp, -e, C:\Users\Ritesh\AppData\Local\Temp\APKTOOL5964149478716822723.tmp
, -0, arsc, -I, C:\Users\Ritesh\AppData\Local\apktool\framework\1.apk, -S, C:\Us
ers\Ritesh\Desktop\apktool\whatsapp\res, -M, C:\Users\Ritesh\Desktop\apktool\wha
tsapp\AndroidManifest.xml]

C:\Users\Ritesh\Desktop\apktool>
```

**Comment by iBotPeaches** [comment]
Apologies. Cannot confirm or investigate without some form of version/link/application.
