### ISSUE TITLE
Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by aditya936** [iBotPeaches/Apktool#2823]
![IMG_20220526_165249](https://user-images.githubusercontent.com/87860972/170479677-c5d8123e-499a-47d7-a3fe-074d0c791756.jpg)

when i was binding payload with metasploit the error shows that
32 bit support is deprecated.

pls help 🙏
thank u

**Comment by iBotPeaches** [comment]
There is a lot going on here. You can clearly using a mobile device, that is detected as 32 bit and using a tool that uses Apktool.

That is not supported. So closing.
