### ISSUE TITLE
[BUG]2.6.2 Exception in thread "main" brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by yyk802388** [iBotPeaches/Apktool#2826]
### Information
1. **Apktool Version (`apktool -version`)** -    2.6.2
2. **Operating System (Mac, Linux, Windows)** -  windows
3. **APK From? (Playstore, ROM, Other)** -https://www.lingshulian.com/s/14970d9e1cb3079b
 
>I: Using Apktool 2.6.2-dirty on 鍏嶈垂鐗?apk
>I: Loading resource table...
>Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
>	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
>	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:787)
>	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
>	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
>	at brut.androlib.Androlib.getResTable(Androlib.java:74)
>	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
>	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
>	at brut.apktool.Main.cmdDecode(Main.java:175)
>	at brut.apktool.Main.main(Main.java:79)
>Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000003
>	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:53)
>	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:387)
>	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:312)
>	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:288)
>	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:211)
>	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:132)
>	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
>	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
>	... 8 more
APK
Questions to ask before submission
Have you tried apktool d, apktool b without changing anything? yes
If you are trying to install a modified apk, did you resign it? no
Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Couldn't download this one, but its the same as https://github.com/iBotPeaches/Apktool/issues/2824, so closing as duplicate.

Thanks for the report.
