### ISSUE TITLE
[BUG] Error: attribute android:dataExtractionRules not found.( added on Android 12)

### ISSUE THREAD

**Issue by vramasam** [iBotPeaches/Apktool#2831]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - All
3. **APK From? (Playstore, ROM, Other)** - Any app having manifest of android:dataExtractionRules

### Stacktrace/Logcat
main | ApkUtils | E | Compiling apk encountered error. Apk : android12_wrapped_unAligned.apk orgId: 11111
W:  decompiled/AndroidManifest.xml:22: error: attribute android:dataExtractionRules not found.
W: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/9n/ml7l5x1d2rd8265wt65xtp9w0000gn/T/brut_util_Jar_50447543674313789212727096658490737957.tmp, link, -o, /var/folders/9n/ml7l5x1d2rd8265wt65xtp9w0000gn/T/APKTOOL6900874008078349432.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 31, --version-code, 5, --version-name, 5.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /var/folders/9n/ml7l5x1d2rd8265wt65xtp9w0000gn/T/APKTOOL7404140993315444952.tmp, -0, arsc, -I, /Library/apktool/framework/1.apk, --manifest, decompiled/AndroidManifest.xml, AndroidStudioProjects/decompiled/build/resources.zip]
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

Add android:dataExtractionRules in the apk and try to recompile.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
3. If you are trying to install a modified apk, did you resign it? - Yes
4. Are you using the latest apktool version? - Yes

**Comment by iBotPeaches** [comment]
Sorry was working top to bottom and didn't realize this was the early report. Found an existing one I just triaged so closing this one for https://github.com/iBotPeaches/Apktool/issues/2834.
