### ISSUE TITLE
[BUG] Apktool renames assets to Assets

### ISSUE THREAD

**Issue by AndnixSH** [iBotPeaches/Apktool#2835]
### Information
1. **Apktool Version (`apktool -version`)** 2.6.1
2. **Operating System (Mac, Linux, Windows)** Windows 11
3. **APK From? (Playstore, ROM, Other)** Playstore

### Description
For some reason, apktool renames assets to Assets, because the game has another sub folder called Assets inside assets. It can cause issue with the game

Recompiled:
![image](https://user-images.githubusercontent.com/40742924/173839492-b85a1a87-c395-4aeb-9fb2-230374afc897.png)

Original: 
![image](https://user-images.githubusercontent.com/40742924/173839559-64fc174b-1e40-4843-bab2-ae9d6d6994b0.png)

### Stacktrace/Logcat
```
Decompile
I: Using Apktool 2.6.1 on Pokmon Shuffle Mobile_1.14.0_apkcombo.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Gaming\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Compile
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

### Steps to Reproduce
1. `apktool d`
2. `apktool b`

### Frameworks
N/A

### APK
https://apkcombo.com/pokemon-shuffle-mobile/jp.pokemon.poketoru/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
4. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Yeah this is an odd one I've been tracking. Merging into existing issue.

https://github.com/iBotPeaches/Apktool/issues/2574
