### ISSUE TITLE
[FEAT] Mention output path

### ISSUE THREAD

**Issue by reactormonk** [iBotPeaches/Apktool#2843]
**Is your feature request related to a problem? Please describe.**
Took me way too long to figure out the built apk goes to `dist/` of the unpacked apk by default.

**Describe the solution you'd like**
The current default output is as:
```
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```
Could be:
```
I: Built apk... (MyApk/dist/MyApk.apk)
```

**Comment by iBotPeaches** [comment]
Seems sane. Will mark as feature.
