### ISSUE TITLE
[BUG]Resources decompilation problem 

### ISSUE THREAD

**Issue by getcurl** [iBotPeaches/Apktool#2844]
Apktool 2.6.1 cannot decompile resources normally, and some apks can decompile normally but cannot compile back 
![Screenshot_2022-07-03-09-08-13-135_bin mt plus canary](https://user-images.githubusercontent.com/78637344/177020595-2393b493-01da-4184-8137-5d59828beb9a.jpg)
![Screenshot_2022-07-03-09-08-38-245_bin mt plus canary](https://user-images.githubusercontent.com/78637344/177020596-6d243124-5543-49ea-aea0-7e3fe5edc489.jpg)
![Screenshot_2022-07-03-09-09-19-483_bin mt plus canary](https://user-images.githubusercontent.com/78637344/177020599-dbd76eef-8366-4cbb-a903-382d7ad3a1a8.jpg)

**Comment by iBotPeaches** [comment]
Sorry - Apktool on device is not officially supported. So I do not wish to dig into what could be the cause here as it could be many things.
