### ISSUE TITLE
[BUG] Invalid register: v16. Must be between v0 and v15, inclusive.

### ISSUE THREAD

**Issue by eladkarako** [iBotPeaches/Apktool#2852]
I've `d` then `b`,  
and got a funky message.

<hr/>

### Information
1. **Apktool Version (`Apktool 2.6.2-7e71ad-SNAPSHOT`)** -
2. **Operating System (Windows)** -
3. **APK From? (build)** -

### Stacktrace/Logcat

```
Picked up JAVA_TOOL_OPTIONS: -XX:+UseLargePages -Dfile.encoding=UTF8 -Duser.language=en -Duser.country=US -Dspring.mvc.locale=en_US -Dspring.mvc.locale-resolver=fixed -Duser.timezone=UTC
Jul 14, 2022 9:41:27 PM brut.androlib.Androlib build
INFO: Using Apktool 2.6.2-7e71ad-SNAPSHOT
Jul 14, 2022 9:41:28 PM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali folder into classes.dex...
project_KeePassDroid_2_5_17_2_203\smali\androidx\constraintlayout\solver\widgets\ConstraintWidget.smali[1043,4] Invalid register: v16. Must be between v0 and v15, inclusive.
Could not smali file: androidx/constraintlayout/solver/widgets/ConstraintWidget.smali
```

this is a segment from the file, lines 1035-1051 for some context:  

```smali
    invoke-virtual {v5}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

    move-result v16

    if-eqz v13, :cond_1

    add-int/lit8 v5, v12, 0x1

    goto :goto_0

    :cond_1
    move v5, v12

    :goto_0
    if-eqz v16, :cond_2

    add-int/lit8 v5, v5, 0x1
```

file  
[ConstraintWidget.smali.txt](https://github.com/iBotPeaches/Apktool/files/9115747/ConstraintWidget.smali.txt)

and project  
[project_KeePassDroid_2_5_17_2_203_original.zip](https://github.com/iBotPeaches/Apktool/files/9115731/project_KeePassDroid_2_5_17_2_203_original.zip)

### Steps to Reproduce
1. `apktool --verbose decode --no-debug-info --force --force-manifest --output "project_KeePassDroid_2_5_17_2_203_original" "app-general-release.apk"`

2. `apktool --verbose build --force-all --no-crunch --use-aapt2 "project_KeePassDroid_2_5_17_2_203_original"`

### APK
https://github.com/bpellin/keepassdroid/releases/download/v2.5.17.2/app-general-release.apk

**Comment by auermich93** [comment]
I just took the APK from the link above, called `apktool d` and `apktool b` and it was working (version 2.6.1). But yeah, above error indicates that the registers are out of range for certain instructions. However, the code snippet from above seems legit. The register v16 is used in move-result and if-eqz, but both instructions support up to 256 registers (v0-v255) according to https://source.android.com/devices/tech/dalvik/dalvik-bytecode. It seems like the error is not related to the code snippet at all.
@eladkarako Did you modify the content of the smali files after decoding the APK?

**Comment by eladkarako** [comment]
> modify?

nope. I'll re-run stuff (recent build) and will update in few moment.

**Comment by eladkarako** [comment]
sorry, I've figured out the cause,  
please mark this as invalid.  

<hr/>

<details><summary>the cause:</summary>  

I did some automated smali editing with a tool I've built,  
https://github.com/eladkarako/smali_offliner__make_apk_offline__isconnect_to_zero  

which turned this:  

```txt
iget-wide v12, v5, Landroidx/constraintlayout/solver/Metrics;->nonresolvedWidgets:J

const-wide/16 v16, 0x1

add-long v12, v12, v16

iput-wide v12, v5, Landroidx/constraintlayout/solver/Metrics;->nonresolvedWidgets:J

:cond_0
invoke-virtual/range {p10 .. p10}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

move-result v12

invoke-virtual/range {p11 .. p11}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

move-result v13

iget-object v5, v0, Landroidx/constraintlayout/solver/widgets/ConstraintWidget;->mCenter:Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;

invoke-virtual {v5}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

move-result v16

if-eqz v13, :cond_1
```

to this:  

```txt
iget-wide v12, v5, Landroidx/constraintlayout/solver/Metrics;->nonresolvedWidgets:J

const-wide/16 v16, 0x1

add-long v12, v12, v16

iput-wide v12, v5, Landroidx/constraintlayout/solver/Metrics;->nonresolvedWidgets:J

:cond_0
invoke-virtual/range {p10 .. p10}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

####move-result v12

const/4 v12, 0x0

invoke-virtual/range {p11 .. p11}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

####move-result v13

const/4 v13, 0x0

iget-object v5, v0, Landroidx/constraintlayout/solver/widgets/ConstraintWidget;->mCenter:Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;

invoke-virtual {v5}, Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;->isConnected()Z

####move-result v16

const/4 v16, 0x0
```

I assume that since `v16` was previously defined as `const-wide/16 v16, 0x1` before,  
changing it with `const/4 v16, 0x0` broke something...  

not 100% sure.

<hr/>

this is just for reference:  

[log_last_decode.log](https://github.com/iBotPeaches/Apktool/files/9143065/log_last_decode.log)

[log_last_build.log](https://github.com/iBotPeaches/Apktool/files/9143066/log_last_build.log) (works)

after modification:  

[log_last_build.log](https://github.com/iBotPeaches/Apktool/files/9143121/log_last_build.log) (does work)

<hr/>

thanks for your help,  
please mark this as invalid.  

</details>
