### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by ZhangLijie** [iBotPeaches/Apktool#2860]
You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

**Comment by iBotPeaches** [comment]
I don't actually manage the Homebrew for Apktool. Never done it, so maybe I'll look into what that takes.

**Comment by iBotPeaches** [comment]
This doesn't look like Apktool issue, you just need at least 3.1.2 of brew.

**Comment by ZhangLijie** [comment]
thank your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2022年8月5日(星期五) 晚上10:14
收件人: ***@***.***&gt;; 
抄送: "张立杰 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iBotPeaches/Apktool] [FEAT] (Issue #2860)





 
I don't actually manage the Homebrew for Apktool. Never done it, so maybe I'll look into what that takes.
