### ISSUE TITLE
[BUG] apktool.bat %java_exe% error

### ISSUE THREAD

**Issue by InersIn** [iBotPeaches/Apktool#2862]
### Information
1. **Apktool Version (`v2.6.1`)** -
2. **Operating System (Windows 11)** -
3. **APK From? (Other)** -

### Steps to Reproduce
After following installation step from the official and try to run apktool.bat, it will say
```
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### Solving
Find this syntax `set java_exe="%JAVA_HOME%\bin\java.exe"` and remove double quote `set java_exe=%JAVA_HOME%\bin\java.exe`

**Comment by iBotPeaches** [comment]
Hmm. Worked on my side, will have to dig into it in more details.

**Comment by yousef-essa** [comment]
I can reproduce this issue as well! The given solution worked.

**Comment by eladkarako** [comment]
you can probably keep it as is  
and add this line below.  

```cmd
set java_exe=%java_exe:"=%
```

if there is a `"` it will remove it,  
otherwise it will just let it be.  

(but seriously,  
if you can run `java --version`,  
just run `java -jar apktool.jar` implicitly)

**Comment by iBotPeaches** [comment]
Was resolved here - https://github.com/iBotPeaches/Apktool/commit/63a8d092d891f0c261b3355a360ab4c1ad8790c4
