### ISSUE TITLE
[BUG] Unsigned Short Value

### ISSUE THREAD

**Issue by unfairDude** [iBotPeaches/Apktool#2867]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Hi, I get unsigned short value error.
I already checked all docs and seems error is related to dex methods exceeding the max limit.

You suggested to move files into new smali folder. 
Can you please explain better? I tried many times without success. The app just crash if I copy the MainActivity file into a new smali folder

**Comment by iBotPeaches** [comment]
> Can you please explain better? I tried many times without success. The app just crash if I copy the MainActivity file into a new smali folder

Yeah I imagine changing package names and more might not be intended. There is no easy answer for this. I recommend you try XDA or StackOverflow.

**Comment by unfairDude** [comment]
Error is caused by apktool for not reassembling dex with new classes
