### ISSUE TITLE
[BUG] Wrapper Script, %JAVA_HOME% not in double quotes 

### ISSUE THREAD

**Issue by Hypernovic** [iBotPeaches/Apktool#2874]
### Information
Wrapper script found in this installation Instruction provided on https://ibotpeaches.github.io/Apktool/install/ 
the `set java_exe="%JAVA_HOME%\bin\java.exe"` while running causes an error like
`'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.`

### Fix
enclosing the %JAVA_HOME% in double quotes can resolve this issue
 `set java_exe=""%JAVA_HOME%"\bin\java.exe"`

**Comment by iBotPeaches** [comment]
It was without double quotes, then it was and now we have bug reports in every which direction. I'm just going to revert all of this and leave it as it was - no fixing this if people have issues in both ways.

Closing for #2862

**Comment by Hypernovic** [comment]
Chill 😊
