### ISSUE TITLE
[BUG]How to disable zip64?

### ISSUE THREAD

**Issue by ludlbj** [iBotPeaches/Apktool#2876]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10

### Stacktrace/Logcat
I built a apk file using apktool 2.6.1, but it failed while I installed it on my phone, the error showed 'Not support ZIP64'. Then I viewed apk file through ultraedit, I found there were some flags like '50 4B 07 08', I had read apktool document but I didn't find disable zip64 option.
My question is how to disable zip64 when I build a apk file?
sample in apk file:
50 4B 07 08 F6 10 D1 87 06 8E 00 00 80 7C 03 00

**Comment by eladkarako** [comment]
same.  
worked around it by unzipping the apk,  
`cd` into the extracted folder, and  
`zip -0Dr "..\repacked.apk"  .`
with gnu zip.  
then I've used uber apk signer to align and sign it,  
only thing that worked for me..
([kit for Windows users](https://github.com/eladkarako/android)).

**Comment by iBotPeaches** [comment]
Java version either of you use? Must be a new default in ZipEntry/ZipFile/Zip*Stream

**Comment by eladkarako** [comment]
```txt
C:\Users\Elad>java -version

Picked up JAVA_TOOL_OPTIONS: --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -XX:+UseLargePages -Dfile.encoding=UTF8 -Duser.language=en -Ddeployment.security.SSLv2Hello=false -Ddeployment.security.SSLv3=false -Ddeployment.security.TLSv1=false -Ddeployment.security.TLSv1.1=false -Ddeployment.security.TLSv1.2=true -Ddeployment.security.TLSv1.3=false -Dhttps.protocols=TLSv1.2 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dhttp.keepalive=true -Dhttp.maxConnections=8

java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

<details><summary>note</summary>  

although it makes sense it is the JDK  
I've also tried other ways of packing the APK such as jar,  
WinZip (normal compatible mode), [7zip with Deflate and ZipCrypto](https://gist.github.com/eladkarako/027a3aadd957538ed4a3053e190e9d80#file-cmd-windows-whole-folder-without-the-folder-itself-to-zip-using-7zip-multithreaded-maximum-compression-legacy-compatible-format-suitable-for-jar-and-apk-prevents-overwriting-by-a-mistake-cmd) and even newer gnu zip build from the git for Windows repo. the only thing worked along with signing was a [zero compression, no folder name storing, with old gnu zip](https://github.com/eladkarako/android/blob/master/07__zip_%5Bany_folder%5D.cmd#L27) from http://gnuwin32.sourceforge.net/packages.html  

I'm not 100% sure why.  
perhaps it has something to do with the Android version,  
or packing under Windows.  

not very helpful,  
sorry.  

</details>

**Comment by iBotPeaches** [comment]
Sorry not replicating - closing.
