### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by horoidrom** [iBotPeaches/Apktool#2879]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - System_ui.apk form oneui core 4.1

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. apktool d system_ui.apk
2. systemui b system_ui

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

Apk couldnt parse

[framework-res (2).zip](https://github.com/iBotPeaches/Apktool/files/9524358/framework-res.2.zip)
[System_UI.zip](https://github.com/iBotPeaches/Apktool/files/9524359/System_UI.zip)

**Comment by iBotPeaches** [comment]
> Apk couldnt parse

Sorry for delay. Normally this has the real debug message in the `adb logcat` during the install. If you attach that I can take another look - closing for now.
