### ISSUE TITLE
[FEAT] Split APK support

### ISSUE THREAD

**Issue by DieHertz** [iBotPeaches/Apktool#2880]
Hi!

Thanks for your work, using apktool and it greatly simplifies researching apps :+1: 

Is Split APK support, specifically resolving `APKTOOL_DUMMY_` resource names, in scope of this project? Maybe I'm missing something and it's already there?
I wrote a small python script to go over split APK res XMLs and patch all the textual occurrences automatically, after that I started wondering if it should be somewhat integrated into **apktool** or released standalone.
My goal with this script was to merge everything back into `base.apk` and not have to install split APKs.

**Comment by Anonymous2716** [comment]
@DieHertz can you share your work,?

**Comment by DieHertz** [comment]
> @DieHertz can you share your work,? The Python script I mean.

I uploaded it to my GitHub page, you may need to tinker with `APK_DIRS` variable a bit for now.
I also think I know how to replace `BLACKLIST` with removing empty entries from *.xml files, but had no time to implement it yet.
https://github.com/DieHertz/split-apks-merger

**Comment by iBotPeaches** [comment]
There is not any support for split apks - Apktool would need an entire rewrite to be able to support the notion of split apks.

There has been a few of these requests, so I added it to the roadmap - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#split-apk-support
