### ISSUE TITLE
How to fix APK EASY TOOL compile failed error [BUG]

### ISSUE THREAD

**Issue by bilalben1** [iBotPeaches/Apktool#2894]
0

I hope you are doing well.

Please, could someone had the same problem with APK to help.

When I try to compile an apk with apk easy tool it says:

compline failed. Please read the log. brut.androlidexception: brut.common.brutexception: could not exec (exit code = 1)

Here is the log:

9/24/2022 10:33:46 PM Compiling APK file...

/c "java -Xmx1024m -jar "C:\Program Files (x86)\APK Easy Tool\Apktool\apktool_2.4.1.jar" b -f -o "C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\2-Recompiled APKs\Super Booster_v1.4.5_apkpure.com.apk" "C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com" "

I: Using Apktool 2.4.1 I: Smaling smali folder into classes.dex... I: Smaling smali_assets folder into assets.dex... I: Smaling smali_classes2 folder into classes2.dex... I: Building resources... W: Failed to generate resource table for split '' W: C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\res\values-v31\colors.xml:3: error: Error: Resource is not public. (at 'm3_ref_palette_dynamic_neutral0' with value '@android:color/Teal_800'). W: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Paradise\AppData\Local\Temp\brut_util_Jar_4146027090992357869.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 152, --version-name, 1.4.5, --no-version-vectors, -F, C:\Users\Paradise\AppData\Local\Temp\APKTOOL8603152315963059007.tmp, -e, C:\Users\Paradise\AppData\Local\Temp\APKTOOL619520021665201179.tmp, -0, arsc, -I, C:\Users\Paradise\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\res, -M, C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\AndroidManifest.xml]

Please read the FAQ and troubleshooting https://forum.xda-developers.com/showpost.php?p=65775601&postcount=2

9/24/2022 10:49:26 PM Compiling APK file...

/c "java -Xmx1024m -jar "C:\Program Files (x86)\APK Easy Tool\Apktool\apktool_2.4.1.jar" b -f -o "C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\2-Recompiled APKs\Super Booster_v1.4.5_apkpure.com.apk" "C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com" "

I: Using Apktool 2.4.1 I: Smaling smali folder into classes.dex... I: Smaling smali_assets folder into assets.dex... I: Smaling smali_classes2 folder into classes2.dex... I: Building resources... W: Failed to generate resource table for split '' W: C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\res\values-v31\colors.xml:3: error: Error: Resource is not public. (at 'm3_ref_palette_dynamic_neutral0' with value '@android:color/Teal_800'). W: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Paradise\AppData\Local\Temp\brut_util_Jar_2034057848650406278.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 30, --version-code, 152, --version-name, 1.4.5, --no-version-vectors, -F, C:\Users\Paradise\AppData\Local\Temp\APKTOOL5790991818223565995.tmp, -e, C:\Users\Paradise\AppData\Local\Temp\APKTOOL4833304238834064153.tmp, -0, arsc, -I, C:\Users\Paradise\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\res, -M, C:\Users\Paradise\OneDrive\Documents\APK Easy Tool\1-Decompiled APKs\Super Booster_v1.4.5_apkpure.com\AndroidManifest.xml]

Please read the FAQ and troubleshooting https://forum.xda-developers.com/showpost.php?p=65775601&postcount=2

What is the problem?

Best regards

**Comment by iBotPeaches** [comment]
Apktool will in situations be more strict than the original compilation. You can see with the private resources in use. You could trick it with `@*android`, but I don't want to make that a built in feature.

Either way, this isn't a bug nor a support forum.

**Comment by bilalben1** [comment]
Hi @iBotPeaches, thank you so much for your reply, I appreciate it.

Please, how can I trick it @*android? 

Note: I didn't make any changes in the APK file, such as the package name; I just decompiled the APK file and compiled it directly.

Best regards

**Comment by iBotPeaches** [comment]
See this - https://github.com/iBotPeaches/Apktool/pull/2650 and your note doesn't matter - the build system in Apktool is probably newer than the original build.

**Comment by bilalben1** [comment]
Thank you so much, I get the point.
