### ISSUE TITLE
[BUG] PathNotExist in apktool.yml, latest version from github releases.

### ISSUE THREAD

**Issue by emir4169** [iBotPeaches/Apktool#2902]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - androidoyun.club

### Stacktrace/Logcat
(i think thats what that means. came directly from my cmd. and only those about the thing)
```
I: Using Apktool 2.6.1
brut.directory.PathNotExist: apktool.yml
```

### Steps to Reproduce
1. `apktool -b (apk)`

### Frameworks
(nothing)

### APK
[If this APK can be freely shared, please upload/attach a link to it.](https://cloud.mail.ru/public/fv7D/eauPkM2Ny) (beta version of the apk from the website)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? (Not modified)
3. Are you using the latest apktool version? Yes

**Comment by emir4169** [comment]
congrats yall killed the link

**Comment by iBotPeaches** [comment]
Apologies for the delay. I don't think I can reproduce this as CI is still green.
