### ISSUE TITLE
[BUG] Apktool is not able to recompile A13 oplus-framework.jar

### ISSUE THREAD

**Issue by alibei** [iBotPeaches/Apktool#2903]
### Information
1. **Apktool Version (apktool -version)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
oplus-framework.jar.out/smali/org/simalliance/openmobileapi/service/ISmartcardService$Default.smali[21,27] Hidden API restrictions are only supported on api 29 and above.
oplus-framework.jar.out/smali/org/simalliance/openmobileapi/service/ISmartcardService$Default.smali[22,12] mismatched tree node: I_ORDERED_METHOD_ITEMS expecting I_FIELDS
Could not smali file: org/simalliance/openmobileapi/service/ISmartcardService$Default.smali
```

### Steps to Reproduce
1. `apktool  b oplus-framework.jar.out` and `apktool  b oplus-framework.jar.out --use-aapt2`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

[oplus-framework.zip](https://github.com/iBotPeaches/Apktool/files/9768242/oplus-framework.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
    YES
3. If you are trying to install a modified apk, did you resign it?
4. Are you using the latest apktool version?
    YES

**Comment by RenateUSB** [comment]
A .jar, like framework.jar has no AndroidManifest.xml You need to add `-api 29` to your apktool commands. Check apktool.yml for assumed minSdkVersion.

**Comment by alibei** [comment]
Thanks that worked
