### ISSUE TITLE
MultiRes

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2905]
Hi

I have an idea. And I tested it yesterday. Is it possible to add Kotlin code to the project through a pull request? Decompilation of multipacks works. The compilation is not yet complete. It will be necessary to resolve the issue with the compilation of multi packages, I think the BundleTool will help us combine several arsc

**Comment by TimScriptov** [comment]
![Screenshot_20221015-022707](https://user-images.githubusercontent.com/31324315/195971140-d15c1858-cde7-4f87-bbf6-268a4d9d989a.png)
![Screenshot_20221015-022713](https://user-images.githubusercontent.com/31324315/195971146-21a08ce7-c30d-4bd5-9e16-8dd69910e103.png)
![IMG_20221015_024511_328](https://user-images.githubusercontent.com/31324315/195971153-050f63b4-2899-4a99-a292-e338006a0e7a.jpg)

**Comment by iBotPeaches** [comment]
Sorry I'm not sure what you are suggesting or asking here. What does kotlin have to do with multi packaged arsc files?
