### ISSUE TITLE
[FEAT] Leave /res folder "as-is" (from Original APK) when decompiling

### ISSUE THREAD

**Issue by mariodantas** [iBotPeaches/Apktool#2907]
**Is your feature request related to a problem? Please describe.**
I noticed that when I decompile some apks, the /res folder sometimes have different contents from the Original APK /res folder

**Describe the solution you'd like**
A flag like **--res-structure-as-is** to decompile the /res folder structure **"as-is"**

**Additional context**

Original /res folder content

![Capture d’écran 2022-10-18 233333](https://user-images.githubusercontent.com/1496045/196549332-b9c1478a-084c-4163-9f78-2662a157fef7.jpg)

Decompiled /res folder content

![Capture d’écran 2022-10-18 233422](https://user-images.githubusercontent.com/1496045/196549352-78ac0c5e-2be4-4300-bd34-7efbf660af8f.jpg)

**Comment by iBotPeaches** [comment]
I understand this ask, but we've attempted this multiple times and it never works out.

See this: https://github.com/iBotPeaches/Apktool/issues/1761#issuecomment-379309998 and this https://github.com/iBotPeaches/Apktool/issues/1272#issuecomment-379345005

**Comment by mariodantas** [comment]
Thanks anyway for your clear answer
