### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nobiDebian** [iBotPeaches/Apktool#2921]
### Information
1. **Apktool Version (`2.6.1`)** -
2. **Operating System (Kali Nethunter)** -
3. **APK From? (ApkMonk Google Now Launcher)** -

### Stacktrace/Logcat

```
ng Apktool 2.6.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_12056327982085289713948779721590040704.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 19, --max-sdk-version, 25, --max-res-version, 25, --version-code, 104002, --version-name, 1.4.large, --no-version-vectors, -F, /tmp/APKTOOL2322373381550752404.tmp, -e, /tmp/APKTOOL545606803063370091.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /sdcard/Payloads/original/res, -M, /sdcard/Payloads/original/AndroidManifest.xml]
W: /tmp/brut_util_Jar_12056327982085289713948779721590040704.tmp: 1: ELF: not found
W: /tmp/brut_util_Jar_12056327982085289713948779721590040704.tmp: 1: Syntax error: end of file unexpected (expecting ")")
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? I didn't sign it because i cant recompile it check the traces, can you guys help me with this??
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
I believe Nethunter is the Android edition of Kali, which is not supported being Android.
