### ISSUE TITLE
[BUG] resources.arsc (and other files not meant to be compressed) is compressed in the built apk, which makes it unusable

### ISSUE THREAD

**Issue by SuperPou1** [iBotPeaches/Apktool#2922]
### Information
1. **Apktool Version** - 2.6.1
2. **Operating System** - Ubuntu 22.04
3. **APK From** - Playstore

### Stacktrace/Logcat

```
Performing Streamed Install
adb: failed to install pou.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]
```

### Steps to Reproduce
1. `decode and build apk with apktool`
2. `sign apk with apksigner`
3. `install app with adb`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://play.google.com/store/apps/details?id=me.pou.app
(installed on my phone and then extracted)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
4. If you are trying to install a modified apk, did you resign it?
yes
6. Are you using the latest apktool version?
yes
I also tried unzipping the built apk and zipping it without compressing resources.arsc, which worked but other files were compressed too, such as sound files, which made the app have no sound at all

**Comment by iBotPeaches** [comment]
```
➜  2922 unzip -l -v me.pou.app_232_apps.evozi.com.apk| grep 'resources.arsc'
 1366560  Stored  1366560   0% 1981-01-01 01:01 58800ff3  resources.arsc
➜  2922 apktool d me.pou.app_232_apps.evozi.com.apk 
I: Using Apktool 2.6.1 on me.pou.app_232_apps.evozi.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2922 apktool b me.pou.app_232_apps.evozi.com --use-aapt
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2922 unzip -l -v me.pou.app_232_apps.evozi.com/dist/me.pou.app_232_apps.evozi.com.apk| grep 'resources.arsc'
 1365740  Stored  1365740   0% 2022-11-05 07:41 d2b3cd0a  resources.arsc
➜  2922 
```

Looks stored to me. So can't replicate - closing.

**Comment by HMaker** [comment]
I have the same issue, the apk rebuilt by `apktool b ...` generates apk with compressed `resources.arsc` thus impossible to install on Android 11+.

**Comment by HMaker** [comment]
@iBotPeaches take a look at https://github.com/mathieures/convert-apk

**Comment by SuperPou1** [comment]
> ```
> ➜  2922 unzip -l -v me.pou.app_232_apps.evozi.com.apk| grep 'resources.arsc'
>  1366560  Stored  1366560   0% 1981-01-01 01:01 58800ff3  resources.arsc
> ➜  2922 apktool d me.pou.app_232_apps.evozi.com.apk 
> I: Using Apktool 2.6.1 on me.pou.app_232_apps.evozi.com.apk
> I: Loading resource table...
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
> I: Regular manifest package...
> I: Decoding file-resources...
> I: Decoding values */* XMLs...
> I: Baksmaling classes.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> I: Copying META-INF/services directory
> ➜  2922 apktool b me.pou.app_232_apps.evozi.com --use-aapt
> I: Using Apktool 2.6.1
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> I: Copying libs... (/kotlin)
> I: Copying libs... (/META-INF/services)
> I: Building apk file...
> I: Copying unknown files/dir...
> I: Built apk...
> ➜  2922 unzip -l -v me.pou.app_232_apps.evozi.com/dist/me.pou.app_232_apps.evozi.com.apk| grep 'resources.arsc'
>  1365740  Stored  1365740   0% 2022-11-05 07:41 d2b3cd0a  resources.arsc
> ➜  2922 
> ```
> 
> Looks stored to me. So can't replicate - closing.

From what I can see, the issue is inconsistent. Sometimes rebooting my pc makes the apk build normally. But most of the time it compresses the files not meant to be compressed.

**Comment by Reyuki-san** [comment]
How do you solve this problem? @SuperPou1

**Comment by Reyuki-san** [comment]
Ahh, solved. Just use zipalign.exe to address this issue.

**Comment by csjulo** [comment]
> Ahh, solved. Just use zipalign.exe to address this issue.

did you mean use zipalign after sign the apk ? @RealYukiSan

**Comment by RealYukiSan** [comment]
do zipalign first before sign the apk, see [this readme](https://github.com/RealYukiSan/ugh-java) as reference
hope it helps :)

**Comment by jcardus** [comment]
I got that issue too. zipalign didn't work for me. I solved it changing target sdk version to 29 in apktool.yml.

**Comment by bubby963** [comment]
> I got that issue too. zipalign didn't work for me. I solved it changing target sdk version to 29 in apktool.yml.

Thanks so much! This worked perfectly and would recommend for anyone else stuck with this

**Comment by j-kaltes** [comment]
I have the same problem. It arose after I unzipped an apk added some classes*.dex files and zipped it again. Thereafter I did apktool d to unpack it. When I thereafter use:
```bash
apktool    b    unpackeddir -o $UNALIGNED
zipalign -f -p 4 $UNALIGNED $ENDFILE
apksigner etc
```
I get the above error message when installing the apk:
```txt
adb: failed to install pou.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]
```
```bash
unzip -l -v again_patched.apk|grep resources.arsc
```
returns:
1127656  Defl:N   222606  80% 2026-01-29 22:11 35722818  resources.arsc

when I zipped with the -0 option, I could install after the same decode and build.

Creating the following in apktool.yml  also solved it:
```txt
doNotCompress:
- arsc
- jpg
- ogg
- png
- wav
- webp
```
