### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KK-Designs** [iBotPeaches/Apktool#2923]
### Information
1. **2.6.1** -
2. **Windows 11 Stable** -
3. **Other** -

### Stacktrace/Logcat

```
Do not know how to see errors on my emulator
```

### Steps to Reproduce
1. `apktool b path/to/folder`

All of the files in the com.something.appname are completely missing, causing app to crash on startup

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Sorry nothing for me to really go on here.
