### ISSUE TITLE
[BUG] - Whatsapp (since Version 2-22-23-15) cannot be decompiled properly

### ISSUE THREAD

**Issue by sickalot** [iBotPeaches/Apktool#2933]
### Information
1. Apktool Version - 2.6.1
2. Operating System - Windows
3. APK From? https://whatsapp-messenger.de.uptodown.com/android/download
4. APK From? https://play.google.com/store/apps/details?id=com.whatsapp&hl=de&gl=US
5. **Before** Version 2-22-23-15 decompiling worked
6. **Since** Version 2-22-23-15 this issue occurs

### Stacktrace/Logcat

```
Include stacktrace here
I: Using Apktool 2.6.1 on whatsapp-messenger-2-22-24-18.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\....\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: cr.xml
S: Could not decode file, replacing by FALSE value: cg8.xml
S: Could not decode file, replacing by FALSE value: ckr.xml
S: Could not decode file, replacing by FALSE value: bh5.png
S: Could not decode file, replacing by FALSE value: l0.png
S: Could not decode file, replacing by FALSE value: og.png
S: Could not decode file, replacing by FALSE value: vn.png
S: Could not decode file, replacing by FALSE value: lc.png
S: Could not decode file, replacing by FALSE value: b0r.png
S: Could not decode file, replacing by FALSE value: bbd.9.png
S: Could not decode file, replacing by FALSE value: lw.9.png
S: Could not decode file, replacing by FALSE value: 4e.png

[...]

S: Could not decode file, replacing by FALSE value: csr.xml
S: Could not decode file, replacing by FALSE value: b9q.png
S: Could not decode file, replacing by FALSE value: bzx.png
S: Could not decode file, replacing by FALSE value: b3f.png
S: Could not decode file, replacing by FALSE value: bay.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

### Steps to Reproduce
1.  java -jar apktool.jar d whatsapp-messenger-2-22-24-18.apk

### Frameworks
-

### APK
https://whatsapp-messenger.de.uptodown.com/android
https://play.google.com/store/apps/details?id=com.whatsapp&hl=de&gl=US

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes

2. If you are trying to install a modified apk, did you resign it?
I only try to decompile it

3. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment]
Hmm an `r` and `R` and `res`.

Didn't expect this. Let me think on this, I think I can patch this easily.

**Comment by sickalot** [comment]
Thank you
Sorry, I am not a developer, and I am not sure if I understood correctly. Is this fixed (Which version) or will this be fixed in a future version?

**Comment by iBotPeaches** [comment]
> Thank you Sorry, I am not a developer, and I am not sure if I understood correctly. Is this fixed (Which version) or will this be fixed in a future version?

2.6.2 - expected before end of year.

**Comment by iBotPeaches** [comment]
> I tried v.2.7.0 and had no errors. But I still have data like this below.
> 
> Is there anything I can do to avoid "Dummies"?

No, we need those resources because the human-readable name of the resource is missing so we make up our own.

**Comment by teamb58** [comment]
> > I tried v.2.7.0 and had no errors. But I still have data like this below.
> > Is there anything I can do to avoid "Dummies"?
> 
> No, we need those resources because the human-readable name of the resource is missing so we make up our own.

Hi @iBotPeaches ,
Question on similar lines. These dummy entries were not there is past versions. Now, when I try out the old apk file(which used to work previously), they also produce these dummy variables.

Problem is, it's becoming difficult to identify the actual resource it's pointing to while doing backtracking from smali files.

Taking reference from https://github.com/iBotPeaches/Apktool/issues/2970#issuecomment-1364518274, the [features](https://github.com/iBotPeaches/Apktool/issues/2970#issuecomment-1364518274) states something like `Additional features that can fix some Apktool errors, such as removing DUMMY_APKTOOL, clear framework before decompiling`. So, is there anything you could do with this issue please?

If I have misunderstood your statement, could you please elaborate on this issue?

Thanks.

**Comment by pan11-yen** [comment]
> ### Information
> 1. Apktool Version - 2.6.1
> 2. Operating System - Windows
> 3. APK From? https://whatsapp-messenger.de.uptodown.com/android/download
> 4. APK From? https://play.google.com/store/apps/details?id=com.whatsapp&hl=de&gl=US
> 5. **Before** Version 2-22-23-15 decompiling worked
> 6. **Since** Version 2-22-23-15 this issue occurs
> 
> ### Stacktrace/Logcat
> ```
> Include stacktrace here
> I: Using Apktool 2.6.1 on whatsapp-messenger-2-22-24-18.apk
> I: Loading resource table...
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: C:\Users\....\AppData\Local\apktool\framework\1.apk
> I: Regular manifest package...
> I: Decoding file-resources...
> S: Could not decode file, replacing by FALSE value: cr.xml
> S: Could not decode file, replacing by FALSE value: cg8.xml
> S: Could not decode file, replacing by FALSE value: ckr.xml
> S: Could not decode file, replacing by FALSE value: bh5.png
> S: Could not decode file, replacing by FALSE value: l0.png
> S: Could not decode file, replacing by FALSE value: og.png
> S: Could not decode file, replacing by FALSE value: vn.png
> S: Could not decode file, replacing by FALSE value: lc.png
> S: Could not decode file, replacing by FALSE value: b0r.png
> S: Could not decode file, replacing by FALSE value: bbd.9.png
> S: Could not decode file, replacing by FALSE value: lw.9.png
> S: Could not decode file, replacing by FALSE value: 4e.png
> 
> [...]
> 
> S: Could not decode file, replacing by FALSE value: csr.xml
> S: Could not decode file, replacing by FALSE value: b9q.png
> S: Could not decode file, replacing by FALSE value: bzx.png
> S: Could not decode file, replacing by FALSE value: b3f.png
> S: Could not decode file, replacing by FALSE value: bay.png
> I: Decoding values */* XMLs...
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Baksmaling classes3.dex...
> I: Baksmaling classes4.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> I: Copying META-INF/services directory
> 
> ### Steps to Reproduce
> 1.  java -jar apktool.jar d whatsapp-messenger-2-22-24-18.apk
> 
> ### Frameworks
> -
> 
> ### APK
> https://whatsapp-messenger.de.uptodown.com/android
> https://play.google.com/store/apps/details?id=com.whatsapp&hl=de&gl=US
> 
> ### Questions to ask before submission
> 1. Have you tried `apktool d`, `apktool b` without changing anything?
> Yes
> 
> 2. If you are trying to install a modified apk, did you resign it?
> I only try to decompile it
> 
> 3. Are you using the latest apktool version?
> Yes
> ```

[package.json](https://github.com/user-attachments/files/20916072/package.json)

**Comment by mangzmangz00-gif** [comment]
#2933+62 858-5509-7926

**Comment by rhisky48-beep** [comment]
+62858-4583-9143

**Comment by putrichika720-lang** [comment]
tolong ya bug wa :0895366730006
