### ISSUE TITLE
Question: Can smali filenames be different on windows systems? 

### ISSUE THREAD

**Issue by khskekec** [iBotPeaches/Apktool#2935]
Hi,

I am facing a weird problem actually. The filenames on may mac machine compared to the ones on a Windows machine after "apktool d" are slightly different.

Example:

Mac - > xLA.2.smali
Windows - >  xLA.smali

Could you explain the reason for this or provide a solution to produce equal filenames across different platforms?

Best regards

Selçuk

**Comment by iBotPeaches** [comment]
Smali remaps filenames for platform restrictions afaik. You can see here: https://github.com/JesusFreke/smali/blob/master/util/src/main/java/org/jf/util/ClassFileNameHandler.java

We have a backlog item to attempt the same - https://github.com/iBotPeaches/Apktool/issues/1460.

I do not have a solution in place to align these between platforms.

**Comment by khskekec** [comment]
This was fast 😅. Thank you!
