### ISSUE TITLE
[FEAT] Android 13 support

### ISSUE THREAD

**Issue by codylund** [iBotPeaches/Apktool#2938]
**Is your feature request related to a problem? Please describe.**
Possibly, if latest ApkTool version is not broadly compatible with APKs built with Android 13 build tools.

**Describe the solution you'd like**
Android 13 support from ApkTool. Historically, ApkTool has released updates for new Android versions. If the latest ApkTool version is not compatible with Android 13 build tools, I would like to see an ApkTool release that is compatible.

**Additional context**
N/A

**Comment by iBotPeaches** [comment]
API 33 (Android 13) is in the upcoming 2.6.2 release slated by end of year. It will bring this compatibility.
