### ISSUE TITLE
Solved the problem in linux based system. I've edited jar.

### ISSUE THREAD

**Issue by John-Irungu** [iBotPeaches/Apktool#2949]
Solved the problem in linux based system. I've edited jar.

ignore unnecessary line as its added by to to view commands of processbuilder.
![image](https://user-images.githubusercontent.com/65706226/181925582-d90f6aaf-a64f-4e0c-a422-43b5e1a1b8ee.png)

_Originally posted by @nikzdevz in https://github.com/iBotPeaches/Apktool/issues/1969#issuecomment-1200244673_
      

Please tell me how you edited your jar file

**Comment by iBotPeaches** [comment]
I don't see a problem or solution.

**Comment by John-Irungu** [comment]
I want to know how to solve the problem for building using apktool it
results in an error even after considering the answers posted it still
doesn't work

**Comment by Rawanrao29** [comment]
Where is the solution?

**Comment by Rawanrao29** [comment]
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: /home/blackhat/Vaim-RamSom/vaimpier/res/values/strings.xml:5: error: Apostrophe not preceded by \ (in You're being hacked!)
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL3649120788464392945.tmp, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/blackhat/Vaim-RamSom/vaimpier/res, -M, /home/blackhat/Vaim-RamSom/vaimpier/AndroidManifest.xml]
[!] Failed to signed APK's





Got this error

**Comment by iBotPeaches** [comment]
@Rawanrao29 - This issue looks unrelated. As the error suggests I would fix the apostrophe
