### ISSUE TITLE
[BUG] Getting tons of APK_DUPLICATE_color (or _dimen, _bool, etc) named values decompiling latest WhatsApp and Facebook

### ISSUE THREAD

**Issue by piereligio** [iBotPeaches/Apktool#2950]
### Information
1. **Apktool Version 2.6.2** -
2. **Operating System Windows** -
3. **APK From? Play Store** -

When I decompile new versions of WhatsApp and Facebook, even on 2.6.2 build of Apktool instead of useful names for the resources, I only geet "DUPLICATE" names or "(name removed)". Is there any hope of fix? Thanks in advance.

**Comment by iBotPeaches** [comment]
I don't think so. It sounds like the resource names are removed, so we have to make up resource names to make buildable.

**Comment by aniruddha-ga** [comment]
APKTOOL_DUPLICATE_color (recompiling error with no changes)

OS: windows 11
Apktool version: 2.9.0
Java: 17 

Apk link: https://appcloner.app/

Here is the log:

java -jar apktool_2.9.0.jar d --only-main-classes AppCloner-2.17.2-23101011.apk
I: Using Apktool 2.9.0 on AppCloner-2.17.2-23101011.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\user\AppData\Local\apktool\framework\1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying raw assets/dd/classes.dex file...
I: Copying raw assets/ftpserver/classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory


java -jar apktool_2.9.0.jar b AppCloner-2.17.2-23101011
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\12.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\12.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060001.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060001.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060002.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060002.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060003.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060003.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060007.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060007.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060008.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060008.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060009.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060009.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f06000a.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f06000a.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060011.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060011.xml: error: file failed to compile.
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060012.xml:1: error: not well-formed (invalid token).
W: C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res\color\APKTOOL_DUPLICATE_color_0x7f060012.xml: error: file failed to compile.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_171451079439363793285937832801349940141.tmp, compile, --dir, C:\Users\user\Downloads\AppCloner-2.17.2-23101011\res, --legacy, -o, C:\Users\user\Downloads\AppCloner-2.17.2-23101011\build\resources.zip]
