### ISSUE TITLE
[BUG] INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

### ISSUE THREAD

**Issue by wortel-za** [iBotPeaches/Apktool#2956]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.1
2. **Operating System (Mac, Linux, Windows)** -  Mac Ventura 13.0.1 
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
Failure 
[INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl52890294.tmp/base.apk (at Binary XML file line #60): 
<meta-data> requires an android:value or android:resource attribute]
this is line 60:
\<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@null"/>
android:resource="@null" is the reason

### Steps to Reproduce
1. `apktool ` -d
2.  `apktool ` -b
3. without any changes

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
lastest provide with 2.7.1

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=de.wetteronline.wetterapp

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
4. If you are trying to install a modified apk, did you resign it? not possible
5. Are you using the latest apktool version? yes

lastest version "with dummies" apktool-2.6.2-5d6c6c-smali.jar  works well

**Comment by iBotPeaches** [comment]
```
➜  2956 grep -i -r 'messaging.default_notification_icon' *
2.6.1/AndroidManifest.xml:        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification_general"/>
2.7.0/AndroidManifest.xml:        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification_general"/>
➜  2956
```

I don't see any null reference here. So then I compared rebuilt to original.

Rebuilt
```
➜  dist aapt2 dump xmltree 2956.apk --file AndroidManifest.xml | grep 'firebase'
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_icon" (Raw: "com.google.firebase.messaging.default_notification_icon")
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_color" (Raw: "com.google.firebase.messaging.default_notification_color")
```

Original
```
➜  2956 aapt2 dump xmltree 2956.apk --file AndroidManifest.xml | grep 'firebase'
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_icon" (Raw: "com.google.firebase.messaging.default_notification_icon")
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_color" (Raw: "com.google.firebase.messaging.default_notification_color")
```

So apologies - I don't see a difference between the versions you specified nor the behavior you mentioned. Closing.

**Comment by derMart** [comment]
Hey @iBotPeaches I have a very similar issue with: https://play.google.com/store/apps/details?id=co.feeld using apktool 2.9.1. Feeld is a split apk and is divided into 4 apks: `base.apk`, `split_config.$cpuarch`, `split_config.$langcode`, `split_config.xxxhdpi`.
They all decompile and recompile without error using apktool 2.9.1. Get the same error as OP when installing via `adb install multiple *.apk`. The culprit is also the default_notification_icon in `base.apk`. Here is the relevant part of decompiled manifest xml:
```
<application android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:extractNativeLibs="false" android:fullBackupContent="@xml/backup_rules" android:icon="@mipmap/ic_launcher" android:isSplitRequired="true" android:label="@string/app_name" android:name="co.feeld.MainApplication" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/BootTheme">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@null"/>
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/ic_launcher_background"/>
```

The reason you were not able to see a difference in your comment above (at least in the compiled .apk files) is that the value related to the `android:name` is printed not on the same, but the following line from `aapt2`, so you cannot use `grep` to see the null value.

Here is the relevant aapt2 output for the unmodified base.apk:
```
        A: http://schemas.android.com/apk/res/android:isSplitRequired(0x01010591)=true
          E: meta-data (line=142)
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.facebook.sdk.ApplicationId" (Raw: "com.facebook.sdk.ApplicationId")
            A: http://schemas.android.com/apk/res/android:value(0x01010024)=@0x7f1200c4
          E: meta-data (line=145)
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.facebook.sdk.ClientToken" (Raw: "com.facebook.sdk.ClientToken")
            A: http://schemas.android.com/apk/res/android:value(0x01010024)=@0x7f1200c5
          E: meta-data (line=148)
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_icon" (Raw: "com.google.firebase.messaging.default_notification_icon")
            A: http://schemas.android.com/apk/res/android:resource(0x01010025)=@0x7f080116
          E: meta-data (line=151)
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_color" (Raw: "com.google.firebase.messaging.default_notification_color")
            A: http://schemas.android.com/apk/res/android:resource(0x01010025)=@0x7f0600f1
```

and for the recompiled .apk by apktool 2.9.1:
```
          A: http://schemas.android.com/apk/res/android:isSplitRequired(0x01010591)=true
            E: meta-data (line=80)
              A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.facebook.sdk.ApplicationId" (Raw: "com.facebook.sdk.ApplicationId")
              A: http://schemas.android.com/apk/res/android:value(0x01010024)=@0x7f1200c4
            E: meta-data (line=81)
              A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.facebook.sdk.ClientToken" (Raw: "com.facebook.sdk.ClientToken")
              A: http://schemas.android.com/apk/res/android:value(0x01010024)=@0x7f1200c5
            E: meta-data (line=82)
              A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_icon" (Raw: "com.google.firebase.messaging.default_notification_icon")
              A: http://schemas.android.com/apk/res/android:resource(0x01010025)=@null
            E: meta-data (line=83)
              A: http://schemas.android.com/apk/res/android:name(0x01010003)="com.google.firebase.messaging.default_notification_color" (Raw: "com.google.firebase.messaging.default_notification_color")
              A: http://schemas.android.com/apk/res/android:resource(0x01010025)=@0x7f0600f1
```
where the `@null` is visible.

My first guess: Might this be related that we are dealing with split apks here? E.g. the resource id in `base.apk` is referncing to a resource which is defined in one of the other apks? But apktool only looks at individual apks and does not find the resource while decompiling so it just writes `@null`?
