### ISSUE TITLE
[BUG] A13 SystemUI crashing

### ISSUE THREAD

**Issue by amackpro** [iBotPeaches/Apktool#2961]
### Information
1.  Version used 2.7.0 as its supports A13
2.  tried windows / ubuntu both
3. Tried Pixel / OxygenOS / Motorola  Android 13 systemui's 

used this cmd to extract
apktool -r d SystemUI.apk

used  this cmd to rebuild
apktool -r b SystemUI --use-aapt2

got this error 

12-10 09:13:24.234  1763  1763 W PackageManager: Failed to parse /system_ext/priv-app/SystemUI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompres
sed and aligned on a 4-byte boundary

after that tried to zipalign and got this error 
12-10 09:29:05.893  7364 10489 W Role    : Cannot get ApplicationInfo for default holder: com.android.systemui
[log_t2.txt](https://github.com/iBotPeaches/Apktool/files/10199146/log_t2.txt)

**Comment by iBotPeaches** [comment]
```
➜  dist unzip -l -v xxx.apk| grep 'resources.arsc'
 5747248  Stored  5747248   0% 2022-06-20 07:49 5db292d4  resources.arsc
➜  dist 
```

The `resources.arsc` file is not compressed. Since I don't have an exact application to work from - closing.
