### ISSUE TITLE
[BUG] Can't change version code if --no-res was used

### ISSUE THREAD

**Issue by Andre8900** [iBotPeaches/Apktool#2965]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Steps to Reproduce
1. Decompile any apk without its resources: `apktool d <anyapk.apk> --no-res`
2. Change the version string or version code in apktool.yml
3. Recompile
4. Version code will not have changed in the output apk file

**Comment by iBotPeaches** [comment]
I believe this to be expected behavior. I'm not how else we could adapt the version files if we aren't disassembling them. Sure we are reading them, but if you explicitly used` --no-res` - we aren't rebuilding them.
