### ISSUE TITLE
[FEAT] - CLI Flag to optionally ignore SDK changes when recompiling.

### ISSUE THREAD

**Issue by Morsmalleo** [iBotPeaches/Apktool#2968]
## <div align="center"><ins>Optional CLI Flag to Ignore SDK changes when recompiling</ins></div>
when we decompile an `.apk` file and change the targeted SDK versions in the `AndroidManifest.xml` and `apktool.yml` files, these changes end up being eliminated because they revert back to their original version before the Recompiling Process is complete (i.e if we make changes to target `sdk 22` instead of `sdk 23`, the changes will revert back to `sdk 23` before the `.apk` file is recompiled) as stated in this [Metasploit Issue](https://github.com/rapid7/metasploit-framework/issues/16208#issuecomment-1050068753)

## <div align="center"><ins>**Describe the solution you'd like**</ins></div>
An option to ignore SDK changes made to the `manifest.xml` and `apktool.yml` files, if this is possible.

So something sort of like the example below;

```bash
java -jar apktool b "decompiled-apk" -o "recompiled.apk" -f --ignore-sdk
```

Not sure if this even doable or if there's an option for this already, I did research on it before posting this but I couldn't really find anything related.

**Comment by iBotPeaches** [comment]
There has been heavy debate about this over the years. I guess it makes sense to visit this again.

Closing for dupe as https://github.com/iBotPeaches/Apktool/issues/2030 this though so I can track in one place.
