### ISSUE TITLE
[BUG] Cannot install recompiled apk - there was a problem parsing the package

### ISSUE THREAD

**Issue by ArtikusHG** [iBotPeaches/Apktool#2970]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - F-Droid

### Steps to Reproduce
1. `apktool d orig.apk`
2. `apktool b orig`
3. Install the apk

### APK

https://f-droid.org/repo/us.spotco.fennec_dos_21081020.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes - same error message is shown before jarsign, after jarsign, and even after zipalign
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Could you run `adb logcat` during the install so you can see the actual error?

**Comment by ArtikusHG** [comment]
Using [APKToolGUI](https://github.com/AndnixSH/APKToolGUI) on Windows works fine when recompiling this app - that means that I am (still) doing something wrong on my end in Linux. I'm closing the issue since it seems it's not a problem with apktool.
