### ISSUE TITLE
Smali Compile Log

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2971]
Please add more information if an error occurred while compiling smali.

Class brut.androlib.mod.SmaliMod.java

**Comment by TimScriptov** [comment]
![Screenshot_20221225-152358_FastHub-RE_Debug](https://user-images.githubusercontent.com/31324315/209464390-905d8c91-f365-40a0-b1ea-41ea5cc1b5d8.png)

**Comment by iBotPeaches** [comment]
Not sure what is being reported here. Do you mind opening a pull request with an explanation of what you are intending to change and why?

**Comment by TimScriptov** [comment]
I'll try
