### ISSUE TITLE
[FEAT] Formal release of dexlib

### ISSUE THREAD

**Issue by mcsimons** [iBotPeaches/Apktool#2975]
**Is your feature request related to a problem?**
Request is for formal release of dexlib. Yes, this could lead to potential bugs for us, since smali and baksmali project was forked and we also pull in dexlib directly. We put our dexlib2 version ahead of apktool in classpath to ensure we load consistent classes. This might lead to bugs given the dexlib/smali changes apktool decided to build in won't get loaded in. 

**Describe the solution you'd like**
A formal release of dexlib.

**Comment by iBotPeaches** [comment]
Not following this - Yes I'd love for an official smali release for the newer changes, but thats in @JesusFreke hands. I just made a quick judgement call to use bleeding edge builds for some fixes.

So I don't think this is in Apktool's control.
