### ISSUE TITLE
[BUG] Not compatible with temurin-19.jdk

### ISSUE THREAD

**Issue by Drjacky** [iBotPeaches/Apktool#2976]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - macOS
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
➜  ~ apktool --version
/usr/local/bin/apktool: line 3: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java: No such file or directory
/usr/local/bin/apktool: line 3: exec: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java: cannot execute: No such file or directory
```

```
➜  ~ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Temurin-19.0.1+10 (build 19.0.1+10)
OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode, sharing)
```

**Comment by Drjacky** [comment]
Uninstall temurin 19 and installed Temurin 17 and it works!

**Comment by iBotPeaches** [comment]
Yeah technically right now Apktool only tests against

```
java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
```

This is getting challenging to support, as I increase the versions we exceeded the amount of allowable tests to run. So perhaps I need to drop the non-lts versions to support later ones.
