### ISSUE TITLE
[BUG] Resource decoding error "brut.androlib.AndrolibException: Config size < 28"

### ISSUE THREAD

**Issue by garbb** [iBotPeaches/Apktool#2978]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat
N/A; nothing is being run on android device. Only trying to decompile on windows.

### Steps to Reproduce
1. `apktool.bat d Sygic_v22.5.6-2158_b211220506_arm64-v8a_K_UserUpload.Net.apk`
```
I: Using Apktool 2.7.0 on Sygic_v22.5.6-2158_b211220506_arm64-v8a_K_UserUpload.Net.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Config size < 28
        at brut.androlib.res.decoder.ARSCDecoder.readConfigFlags(ARSCDecoder.java:414)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:268)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:133)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:85)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:51)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:780)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:74)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:251)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
```

### Frameworks
N/A; nothing is being run on android device. Only trying to decompile on windows.

### APK
    https://forum.mobilism.org/viewtopic.php?f=431&t=5095049
        link in the thread to the apk (Sygic_v22.5.6-2158_b211220506_arm64-v8a_K.apk): https://devuploads.com/p1pcf1ekn638

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
4. If you are trying to install a modified apk, did you resign it? I am not trying to install the apk. Only decompile it.
5. Are you using the latest apktool version? Yes

Other notes:
- Decompiling sources without decompiling resources works fine: (`apktool.bat -r d Sygic_v22.5.6-2158_b211220506_arm64-v8a_K_UserUpload.Net.apk`)
- If I open the .apk with archiving software like 7-zip it shows a strange structure: There are normal files `AndroidManifest.xml`, `classes.dex`, `resources.arsc` but additionally it has folders with the same `AndroidManifest.xml`, `classes.dex`, `resources.arsc` names. These folders appear to contain files which I would normally expect to see inside the `res` folder?

![image](https://user-images.githubusercontent.com/4453789/212497676-87010c7a-b214-41a7-97b4-8cfa9cb80211.png)
![image](https://user-images.githubusercontent.com/4453789/212497539-b24b3ad5-056e-4b11-a09d-44d8dece68de.png)
![image](https://user-images.githubusercontent.com/4453789/212497548-8ef0c0a6-75b4-4812-81fd-771bc5c44084.png)
![image](https://user-images.githubusercontent.com/4453789/212497556-fe3cd229-1b6b-465e-a756-64a8904edee1.png)
I suspect this apk might have been altered in some way to prevent modification?

**Comment by iBotPeaches** [comment]
Odd. aapt2 choking on it, but not aapt1 and of course apktool having an issue.

I've just never seen an application with a ResSpec under 28 bytes.

**Comment by iBotPeaches** [comment]
The application has a mix of qualifiers between very recent and very old, so my idea that it was stripped down to very old Android versions goes out the window.

I'm guessing if this is intentional - there is some method to compact/optimize each ResSpec based on available qualifiers. Given the first ResSpec is 16 bytes and the actual qualifier is `w700dp` - you could easily fit that in 16 bytes.

I'll mark as bug.

**Comment by iBotPeaches** [comment]
I've got a PR up for this supporting as low as an 8 byte config, but my fear is that this is a symptom of a different problem and not the real one, because we don't get to a usable/buildable application with it.

However, we do fix disassembly.

**Comment by shuajinanhai** [comment]
修复后，报这个bug
Exception in thread "main" java.lang.NullPointerException
>	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeNamespace(AXmlResourceParser.java:292)
>	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeName(AXmlResourceParser.java:339)
>	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeName(XmlPullParserDelegate.java:53)
>	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:89)
