### ISSUE TITLE
attr

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2983]
ApkTool:
?android:dropDownListViewStyle

Original:
?android:attr/dropDownListViewStyle

Example error:
Error: Attribute is not public. (at 'color' with value '?android:^attr-private/colorSurface').

Error: Attribute is not public. (at 'color' with value '?android:^attr-private/colorSurfaceVariant').

Error: Attribute is not public. (at 'color' with value '?android:^attr-private/colorSurfaceVariant').

APK:
Cool T Launcher 1.1
XDroid 13 Launcher 1.0

**Comment by iBotPeaches** [comment]
Do you have a small reproducer to investigate this? Not quite following how a private-attribute is losing the type.

**Comment by iBotPeaches** [comment]
I don't have an APK to test this, but I remade the attribute parser which should have a patch for prefix driven attributes. See this PR - https://github.com/iBotPeaches/Apktool/pull/3123

Closing.
