### ISSUE TITLE
[BUG] APKTOOL changes images in `/res/drawables`

### ISSUE THREAD

**Issue by Miepee** [iBotPeaches/Apktool#2984]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

When I decompress the APK, put new images into the /res/drawables folders, build the APK again, decompile(or unzip) the APK and then check the images, they suddenly have a new hash

### Steps to Reproduce
1. `apktool d AM2RWrapper.apk -o somewhere`
2. Replace the image in `/res/drawable/icon.png` with this one:
![8508930c-9d72-4253-abfc-771acbeb0a6c](https://user-images.githubusercontent.com/38186597/215074904-2b2e7d04-bf7d-4a01-8ecd-9aad3998caa7.png)

  The sha256 of it is `e546921191732a62346c9189f2d290e499f75d8c24ba2ef4d07dd4b4bf453363`
3. Build an apk from it via `apktool b somewhere`
4. Unzip `/res/drawable/icon.png` from `somewhere.apk` and check it's hash again (was in my case `f067234b313aaf097cb1771b1dcfba428b038d044763da77826b57026add0b9b`)

### APK
[AM2RWrapper.apk.zip](https://github.com/iBotPeaches/Apktool/files/10518357/AM2RWrapper.apk.zip)

For potentially easier viewing, I'll attach a few files here:
- Original image that was used:
![8508930c-9d72-4253-abfc-771acbeb0a6c](https://user-images.githubusercontent.com/38186597/215075671-5ead7bac-e92f-4bce-88a4-b061d3305fc0.png)
- The image that was produced after it:
![icon](https://user-images.githubusercontent.com/38186597/215075412-0ca11c77-acb1-44de-8655-e0014bf6c6a4.png)
- ImageMagick metadata of original image:
[old.txt](https://github.com/iBotPeaches/Apktool/files/10518341/old.txt)
- ImageMagick metadata of new image:
[new.txt](https://github.com/iBotPeaches/Apktool/files/10518343/new.txt)

**Comment by iBotPeaches** [comment]
Have you tried building with aapt2 and `-nc` (no crunch)?

That would disable the pre-processing aapt2 does to PNGs during compilation.

**Comment by Miepee** [comment]
I have not, will let you know once I do.

**Comment by Miepee** [comment]
That indeed worked properly.
Not that familiar, so couple questions:
- What's the difference between aapt1 and aapt2? Any (compatibility) issues I might find?
- Is this expected behaviour, and thus not actually a bug?

**Comment by iBotPeaches** [comment]
* Not sure - I believe aapt2 just ported functionality forward that aapt1 offered, so hopefully near 1/1.
* This is expected, but I could debate whether its default is opt-out instead of opt-in.

**Comment by Miepee** [comment]
FWIW, I only hit this behaviour, cause I wanted to confirm (via hashes) whether the images I used for icons actually got used. I don't know how often people want to check that though.

**Comment by iBotPeaches** [comment]
Sounds good - I'll leave as-is then in terms of the feature/toggle.
