### ISSUE TITLE
[FEAT]Enable / Disable Splits by ABI in Bundle

### ISSUE THREAD

**Issue by erastod** [iBotPeaches/Apktool#2985]
When making a AAB from a compiled apk using apktool, google always makes delivery method split by ABI, density etc, would be great to make an option to enable or disable this.
To make bundle work like a normal APK.

**Comment by iBotPeaches** [comment]
How are you making a bundle with apktool?

**Comment by iBotPeaches** [comment]
Closing - don't believe Apktool has anything to do with this.

**Comment by erastod** [comment]
> How are you making a bundle with apktool?

Use to decompile then use aapt2 and bundletool
