### ISSUE TITLE
[BUG] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by vramasam** [iBotPeaches/Apktool#2988]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - MAC
3. **APK From? (Playstore, ROM, Other)** - Other

Include stacktrace here
W: decompiled/res/values-v31/colors.xml:55: error: resource android:color/Indigo_800 is private.
W: decompiled/res/values-v31/colors.xml:56: error: resource android:color/Indigo_700 is private.
W: decompiled/res/values-v31/colors.xml:58: error: resource android:color/GM2_grey_800 is private.
W: decompiled/res/values-v31/colors.xml:59: error: resource android:color/Blue_800 is private.
W: decompiled/res/values-v31/colors.xml:60: error: resource android:color/Blue_700 is private.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/2c/9j01k89j2z7gxtl7b9zq9wdm0000gn/T/brut_util_Jar_53233627686968490744518893884762461872.tmp, link, -o, /var/folders/2c/9j01k89j2z7gxtl7b9zq9wdm0000gn/T/APKTOOL6500961329146201645.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 31, --version-code, 1, --version-name, 1.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /var/folders/2c/9j01k89j2z7gxtl7b9zq9wdm0000gn/T/APKTOOL1579233904283657180.tmp, -0, arsc, -I, apktool/framework/1.apk, --manifest, tempFiles/temp12879826019047041948828548095791/decompiled/AndroidManifest.xml, decompiled/build/resources.zip]

### Steps to Reproduce
Upgraded to 2.7.0 issue issue is happening. Same works fine with 2.6.1. 
Happening only with 2.7.0 not with 2.6.1 in MAC

**Comment by vramasam** [comment]
Working fine with Linux. Its happening only for MAC

**Comment by iBotPeaches** [comment]
Don't use mac then?

I don't see anything for me to work from here.
