### ISSUE TITLE
[BUG] AndroidManifest.xml mangles and removes attribute names when decoding apk

### ISSUE THREAD

**Issue by jonluca** [iBotPeaches/Apktool#2990]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7
2. **Operating System (Mac, Linux, Windows)** - Macos
3. **APK From? (Playstore, ROM, Other)** - playstore

The APK that is created from apktool mangles the properties in AndroidManifest.xml, seen here.
<img width="1188" alt="capture 2023-02-09 at 12 55 00 PM" src="https://user-images.githubusercontent.com/13029040/217937005-1823c1a1-7e25-4297-bd26-91454e4a218b.png">

jadx, on the other hand, is able to process these correctly.

<img width="1661" alt="capture 2023-02-09 at 12 55 17 PM" src="https://user-images.githubusercontent.com/13029040/217937056-e553c0cc-9970-4f53-88e9-9c173434671c.png">

Interestingly enough, android studio's `apkanalyzer` and `aapt2 xmltree` both fail here.

### Stacktrace/Logcat

```
I: Using Apktool 2.7.0 on chase.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/jonlucadecaro/Library/apktool/framework/1.apk
I: Regular manifest package...
[Fatal Error] :2:73: Attribute "android:" was already specified for element "manifest".
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Decoding process was successful
```

### Steps to Reproduce
1. `apktool d chase.apk -o chase --only-main-classes`

### APK

[Apk](https://mega.nz/file/tMNw1CBJ#eFWkHv4u7JbIdQvxA55mzakp6nrq-5E8kDlGCAKokOE)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yes

**Comment by charlie-maxrewards** [comment]
Exactly the same issue here, using the same apk as above.

**Comment by iBotPeaches** [comment]
Thanks for the report. This is already exists in our backlog as two different iterations.

 * https://github.com/iBotPeaches/Apktool/issues/2981
 * https://github.com/iBotPeaches/Apktool/issues/2972
 
 Closing for those.
