### ISSUE TITLE
[BUG] attribute 'android:name' in <service> tag must be a valid Java class name.

### ISSUE THREAD

**Issue by khskekec** [iBotPeaches/Apktool#2992]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Ubuntu Linux 22.10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
No stacktrace

### Steps to Reproduce
1. `apktool d specific.apk`

### Frameworks
No.

### APK
https://m.apkpure.com/de/dexcom-g7/com.dexcom.g7

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? -> Yes
3. If you are trying to install a modified apk, did you resign it? -> Yes
4. Are you using the latest apktool version? -> Yes

-------------------------------------------------------------
Hi,

i am just doing `apktool d x.apk` and `apktool b ./src -o x.apk --use-aapt2` without changing anything.
It results in following error message:

```
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /home/selcuk/Development/diakem/dexcom-g7-apk-patcher/dexcom-dev/AndroidManifest.xml:118: error: attribute 'android:name' in <service> tag must be a valid Java class name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_17111223174942836834772828358268041007.tmp, link, -o, /tmp/APKTOOL1736694331414508062.tmp, --package-id, 127, --min-sdk-version, 29, --target-sdk-version, 31, --version-code, 3906, --version-name, 1.4.0.3906, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL14278644911617600319.tmp, -0, arsc, -I, /home/selcuk/.local/share/apktool/framework/1.apk, --manifest, /home/selcuk/Development/diakem/dexcom-g7-apk-patcher/dexcom-dev/AndroidManifest.xml, /home/selcuk/Development/diakem/dexcom-g7-apk-patcher/dexcom-dev/build/resources.zip]
```

The AndroidManifest at line 118 looks like:

```
<service android:exported="false" android:isolatedProcess="true" android:name="kz.\u0871᫛" android:process=":zzwzdzmztzpzqzlzizszjzvzbzgzuzxzfzyzrzzwdwewtwpwqwowlwhwiwjwvwgwxwywkdzdwd"/>
```

Unfortunetaly i have no idea why the filename is looking that weird - is it obfuscation?! Is it fixable?

Kind regards

Selcuk

**Comment by khskekec** [comment]
A small update on this issue:

if skipping decompiling resources "-r" it builds at least but does not solve the initial problem.

**Comment by khskekec** [comment]
Any ideas?

**Comment by iBotPeaches** [comment]
As you discovered. This service has an odd name that limitations on older build tools probably ignored and/or was changed to ignore.

```
          E: service (line=0)
            A: http://schemas.android.com/apk/res/android:name(0x01010003)="kz.ࡱ᫛" (Raw: "kz.ࡱ᫛")
            A: http://schemas.android.com/apk/res/android:exported(0x01010010)="false" (Raw: "false")
            A: http://schemas.android.com/apk/res/android:process(0x01010011)=":zzwzdzmztzpzqzlzizszjzvzbzgzuzxzfzyzrzzwdwewtwpwqwowlwhwiwjwvwgwxwywkdzdwd" (Raw: ":zzwzdzmztzpzqzlzizszjzvzbzgzuzxzfzyzrzzwdwewtwpwqwowlwhwiwjwvwgwxwywkdzdwd")
            A: http://schemas.android.com/apk/res/android:isolatedProcess(0x010103a9)="true" (Raw: "true")
```

So I don't think there is anything for Apktool do here. It can't be a perfect bullet for every disassemble/rebuild. This is an easy enough think to remove/change.

**Comment by j-kaltes** [comment]
Renaming an odd name to something else will give problems when the odd name is also used in reflection or via the java native interface. 
As I understood it, apktool is not made to create new apps, but to patch existing apps, so it should be able to handle the particularities of existing apps.

**Comment by SantiiRepair** [comment]
Hey mate, did you get the solution?
