### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alp213432** [iBotPeaches/Apktool#2993]
Using APK template: app.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.example.beautifularts.gazvp
[*] Loading /tmp/d20230214-98983-43x80s/original/smali_classes8/com/example/beautifularts/MainActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20230214-98983-43x80s/output.apk
[-] I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: Failed to generate resource table for split ''
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:55: error: Error: Resource is not public. (at 'm3_ref_palette_dynamic_tertiary0' with value '@android:color/Indigo_800').
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_73852780583325853037843458758070160854.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL11153207113069217233.tmp, -e, /tmp/APKTOOL6297579892101869596.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20230214-98983-43x80s/original/res, -M, /tmp/d20230214-98983-43x80s/original/AndroidManifest.xml]
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[-] I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:55: error: resource android:color/Indigo_800 is private.
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:56: error: resource android:color/Indigo_700 is private.
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:58: error: resource android:color/GM2_grey_800 is private.
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:59: error: resource android:color/Blue_800 is private.
W: /tmp/d20230214-98983-43x80s/original/res/values-v31/colors.xml:60: error: resource android:color/Blue_700 is private.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_80860873033947684474811318566492355939.tmp, link, -o, /tmp/APKTOOL2231424565214846258.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 1, --version-name, 1.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /tmp/APKTOOL268824128837584009.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, --manifest, /tmp/d20230214-98983-43x80s/original/AndroidManifest.xml, /tmp/d20230214-98983-43x80s/original/build/resources.zip]
Error: Unable to rebuild apk with apktool

i get this error to continue carrying the load 

i am using kali linux

I am using apktool version 2.7.0

apk i use=https://www.mediafire.com/file/gzcpzfnnc0r7o3a/app-debug_%25288%2529.apk/file

the application is my application that I wrote from android studio
I tried apktool d
I tried apktool b

**Comment by iBotPeaches** [comment]
As those errors suggest - those resources are private and not meant to be directly referenced. You may trick it with `*@android` which allows private resources to be used, but this is the downside of rebuilding an application with a more stricter build process than (by age) then it originally went through.
