### ISSUE TITLE
[BUG] Can't recompil SamsungInCallUI

### ISSUE THREAD

**Issue by edzamber** [iBotPeaches/Apktool#2994]
### Information
1. **Apktool Version : apktool-2.7.1-0a3c75
2. **Operating System : Windows
3. **APK From? SamsungInCallUI.apk (oneUI 5.1)

### Stacktrace/Logcat

SamsungInCallUI.apk/AndroidManifest.xml:111: Tag <provider> missing required attribute name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [D:\Temp\BAT_temp\brut_util_Jar_68362449827842169708493136127671994910.tmp, p, --forced-package-id, 127, --min-sdk-version, 30, --target-sdk-version, 31, --version-code, 1410100012, --version-name, 14.1.01.12, --no-version-vectors, -F, D:\Temp\BAT_temp\APKTOOL9915442709169977474.tmp, -e, D:\Temp\BAT_temp\APKTOOL8101474889251789065.tmp, -0, arsc, -I, bin\framework\1.apk, -S, C:\BatchApkTool\_INPUT_APK\SamsungInCallUI\res, -M, C:\BatchApkTool\_INPUT_APK\SamsungInCallUI\AndroidManifest.xml]
[*] ---> Error recompiling "SamsungInCallUI5.1"

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes
[SamsungInCallUI.zip](https://github.com/iBotPeaches/Apktool/files/10747174/SamsungInCallUI.zip)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/10747184/framework-res.zip)

**Comment by iBotPeaches** [comment]
Odd. We've seen this is a few times and like 80% of the times its a more restricted aapt binary that is enforcing properties on elements that were originally not added on an older aapt/aapt2.

Will hold till I can check.

**Comment by edzamber** [comment]
Ok thanks 👍

**Comment by iBotPeaches** [comment]
Sorry I couldn't replicate this.

```
➜  2994 apktool if framework-res.apk -t 2994
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-2994.apk
➜  2994 apktool d SamsungInCallUI.apk -t 2994
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-875fea-SNAPSHOT on SamsungInCallUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-2994.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2994 apktool b SamsungInCallUI --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-875fea-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: SamsungInCallUI/dist/SamsungInCallUI.apk
➜  2994 
```
