### ISSUE TITLE
How to change stusbar color in settings apk 

### ISSUE THREAD

**Issue by abdo0123780073** [iBotPeaches/Apktool#2995]
Hello everyone 
How to set stusbar color Such as action bar color in settings apk android Nogat 7.1.2 
![1676580297011](https://user-images.githubusercontent.com/97976238/219759891-bdba22f1-3300-4164-a0df-046c215f62d6.png)
This style 
![sssss](https://user-images.githubusercontent.com/97976238/219760129-322ef8d8-d61a-4bed-94b2-477ac8d28739.PNG)
stusbar color is not working 
???

**Comment by iBotPeaches** [comment]
Sorry - this doesn't look like an issue report for Apktool.
