### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by gingercookies** [iBotPeaches/Apktool#2996]
**Info:**
1. Apktool version: 2.7.0
2. Operating environment: Ubuntu WSL in Windows
3. Apk from: Apkmirror
4. JRE version: openjdk version "11.0.17" 2022-10-18
                       OpenJDK Runtime Environment (build 11.0.17+8-post- 
                       Ubuntu-1ubuntu220.04)
                       OpenJDK 64-Bit Server VM (build 11.0.17+8-post- 
                       Ubuntu-1ubuntu220.04, mixed mode, sharing)

Included stacktrace: 

> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:6: error: Resource entry 0_resource_name_obfuscated already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:4: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:58: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04002d already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:57: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:66: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04002e already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:65: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:73: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04002f already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:72: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:83: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040036 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:82: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:92: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040038 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:91: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:101: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04003b already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:100: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:107: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04003e already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:106: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:115: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040042 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:114: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:128: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040049 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:127: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:145: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040054 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:144: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:153: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040055 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:152: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:166: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04005d already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:165: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:186: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040068 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:185: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:208: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040076 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:206: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:222: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040081 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:221: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:234: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040089 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:233: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:243: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04008e already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:242: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:252: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040093 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:251: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:269: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04009d already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:268: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:278: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f0400a3 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:277: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:333: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f0400d7 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:332: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:346: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f0400dd already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:345: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:389: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040103 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:388: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:411: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040113 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:410: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:507: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040164 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:506: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:511: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040165 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:510: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:515: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040166 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:514: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:519: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040167 already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:518: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:523: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f040168 already has bag item @null.
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_70436339054728327295054212047295539576.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 2064000040, --version-name, 3.2.4, --no-version-vectors, -F, /tmp/APKTOOL7531167273233986843.tmp, -e, /tmp/APKTOOL4678844530811369651.tmp, -0, arsc, -I, /home/cookies/.local/share/apktool/framework/1.apk, -S, /home/cookies/AdblockBrowser/res, -M, /home/cookies/AdblockBrowser/AndroidManifest.xml]
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:522: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:547: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f04017d already has bag item @null.
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:546: Originally defined here.
> W:
> W: /home/cookies/AdblockBrowser/res/values/attrs.xml:586: error: Resource entry APKTOOL_DUPLICATE_attr_0x7f0401a1 already has bag item @null.
> 

**Steps to Reproduce:**
- Using apktool decode an apk then rebuild without any parameters

_P/s: Using --force-all don't working at all but -r only working then i got a blob of binary AndroidManifest.xml that can't be edited. I want to edit the AndroidManifest to make the app debuggable/backupable to pull my own data out of it._

**Comment by iBotPeaches** [comment]
Thanks for the report - duplicate issue of this one - https://github.com/iBotPeaches/Apktool/issues/2836
