### ISSUE TITLE
Multiplatform

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#3019]
I propose to remove the platform-dependent code in the androlib library! And already in the shell itself, indicate where to get the binaries and the framework and for what architecture

Example use BuildOptions:
boolean useAapt2 = false:
String aaptPath = "";
String aapt2Path = "";

And when starting decompilation or compilation, specify the necessary paths in Main.java

**Comment by TimScriptov** [comment]
Everyone knows that ApkTool works on PC and Android, only there is no official support for Android

**Comment by TimScriptov** [comment]
It is not convenient to fork ApkTool and fix the code to fit your needs. Example: https://github.com/TimScriptov/Android-ApkTool-Library

**Comment by iBotPeaches** [comment]
I'm not sure I'm following. Are you saying we should have `apktool-cli` be responsible for platform detection and simply have `apktool-lib` work from passed in binaries?

**Comment by TimScriptov** [comment]
@iBotPeaches yeah. you got me right

**Comment by iBotPeaches** [comment]
@TimScriptov - To save you some time, if you take that route. Do you mind writing up a mini breakdown of planned changes?

Something like:
 * Move the aapt detection into util library
 * Introduce param for aapt paths into cli
 * Adjust lib to want aapt version and binary

**Comment by TimScriptov** [comment]
Well, you will need to look at the code and make a list of what needs to be changed. When it's ready I'll let you know

**Comment by iBotPeaches** [comment]
Going to close this. I'll take a look when I see a PR/comment. Thanks to some recent help - a lot of changes have been made in the aapt detection area.
