### ISSUE TITLE
[BUG] Apktool build failed due to 'could not exec (exit code = 1)' error while building resources

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [iBotPeaches/Apktool#3021]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
```
java -jar /storage/emulated/0/Download/apktool_2.7.0.jar b /data/data/com.termux/files/home/NodiaApp
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_162897778151517145021320538582536817390.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 31, --version-code, 20, --version-name, 3.4, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL9569148804810399008.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17202618306931521676.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/home/NodiaApp/res, -M, /data/data/com.termux/files/home/NodiaApp/AndroidManifest.xml]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_162897778151517145021320538582536817390.tmp[1]: ELF: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_162897778151517145021320538582536817390.tmp[714]: syntax error: unexpected '(' 
```

### Steps to Reproduce
1. `apktool d NodiaApp.apk`
2. Then `apktool b NodiaApp`

### Frameworks
I don't know

### APK
The link to the APK is https://drive.google.com/file/d/11ACLnGW9oi_Thn1L3L89gCvCo303Jupk/view?usp=drivesdk

OR,

https://play.google.com/store/apps/details?id=com.nodiaapp
### Video
https://drive.google.com/file/d/11H5VScrRScCiWHgcaj0WbOPuubAS4GIc/view?usp=drivesdk
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
It looks like you are executing it on Android. Which may work w/ alternative tools, but not officially. So closing this.
