### ISSUE TITLE
[BUG] brut.directory.PathNotExist: apktool.yml

### ISSUE THREAD

**Issue by DizzyJune** [iBotPeaches/Apktool#3028]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Oculus Quest Store

### Stacktrace/Logcat

```
I: Using Apktool 2.7.0
brut.directory.PathNotExist: apktool.yml
```

### Steps to Reproduce
1. `apktool d blaston.apk`
2. `apktool b blaston.apk blaston_new.apk ` (Not modifying any contents of the apk)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://drive.google.com/file/d/1T24jf2vY-XVQSpF4-knHW2TIc7wHmmmb/view?usp=share_link (I have to give google drive link bc its a vr app, and you need an acc to download it, its a free game tho)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? This is before install.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment]
You want to run `b` on the folder of the disassembled application, not the apk. That explains the error you are getting.
