### ISSUE TITLE
[BUG] The coding of Chinese characters in decompilation and decompilation.

### ISSUE THREAD

**Issue by SONGjiemo** [iBotPeaches/Apktool#3033]
### Information
1. Apktool Version (`apktool -version`):  2.7.0
2. Operating System (Mac, Linux, Windows): win11 22h2
3. Visual Studio Code   apklab

### Steps to Reproduce

The problem with decompiling APK.
Download size: 0.00 MB
Downloaded Infinity%
Download size: 0.00 MB
Downloaded Infinity%
----------------------------------------------------------------------------
Decoding 当贝桌面4.0.0 去广告版v2.apk into c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21
----------------------------------------------------------------------------
java -jar C:\Users\SONG\.apklab\apktool_2.7.0.jar d c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v2.apk -o c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21 --only-main-classes
I: Using Apktool 2.7.0 on ��������4.0.0 ȥ����v2.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\SONG\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Decoding process was successful
------------------------------------------------------------------------
Initializing c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21 as Git repository
------------------------------------------------------------------------
cd /d "c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21" && git init && git config core.safecrlf false && git add -A && git commit -q -m "Initial APKLab project" 
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Initializing Git process exited with code 1
![image](https://user-images.githubusercontent.com/46627639/226360400-e57835a5-d454-4068-8906-b12abc47736a.png)

After recompiling, there is a failure.
-----------------------------------------------------------
Rebuilding 当贝桌面4.0.0 去广告版v2.apk into 当贝桌面4.0.0 去广告版v21\dist
-----------------------------------------------------------
java -jar C:\Users\SONG\.apklab\apktool_2.7.0.jar b c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21 --use-aapt2
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: c:\Users\SONG\Downloads\当贝桌面4.0.0 去广告版v21\res: error: failed to open directory: 系统找不到指定的文件�? (2).
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SONG\AppData\Local\Temp\brut_util_Jar_172791153815051393034569223542023765311.tmp, compile, --dir, c:\Users\SONG\Downloads\��������4.0.0 ȥ����v21\res, --legacy, -o, c:\Users\SONG\Downloads\��������4.0.0 ȥ����v21\build\resources.zip]
Rebuilding process exited with code 1
![image](https://user-images.githubusercontent.com/46627639/226360530-3a168766-3f05-4028-b6f1-b0708e165c48.png)

**Comment by SONGjiemo** [comment]
> 有机会测试非窗户机器吗？好奇这是否与Windows上的字符集隔离。



> Have a chance to test a non-windows machine? Curious if this is isolated to charsets on Windows.

Sorry, I only have win system. 
Hopefully I can test what the problem is, but I don't think it's an isolated character set.

**Comment by Anonymous2716** [comment]
@SONGjiemo you can test in Windows Subsystem for Linux (WSL) I think.

**Comment by iBotPeaches** [comment]
Going to close for this issue - https://github.com/iBotPeaches/Apktool/issues/1460

It discusses character mapping on Windows.
