### ISSUE TITLE
[BUG] Build fail with android:enableOnBackInvokedCallback not found

### ISSUE THREAD

**Issue by oocast** [iBotPeaches/Apktool#3041]
### Information
1. **Apktool Version (`apktool -2.7.0`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
I: Using Apktool 2.7.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
W: D:\Investigation\Resign0413\Test\Decode2.7.0\AndroidManifest.xml:39: error: attribute android:enableOnBackInvokedCallback not found.
```

### Steps to Reproduce
1. get an apk whose AndroidManifest.xml contains [android:enableOnBackInvokedCallback](https://developer.android.com/guide/navigation/predictive-back-gesture#opt-predictive) attribute.
2. `apktool decode` to decode it
3. `apktool build` to rebuild it

### Other notes
`enableOnBackInvokedCallback` is an attribute introduced with Android SDK Version 33.
Tried to modify apktool.yml and make it `targetSdkVersion '33'`, but same error persists.

### APK
The APK cannot be shared

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes, same error happens at build-time

4. If you are trying to install a modified apk, did you resign it?
Not there yet. Apktool fails to rebuild.

5. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment]
It appears I never finished the internal framework upgrade. My last commit was to Preview 33.

https://github.com/iBotPeaches/Apktool/commit/057b35fcecb73f37aeced11a7d1ae560ebb687e1

**Comment by iBotPeaches** [comment]
Added `enableOnBackInvokedCallback` to test suite alongside API34 framework and appears to be working. PR above will close this shortly.
