### ISSUE TITLE
[FEAT] Improve BUG report template - add 4th characteristic - java version (java -version)

### ISSUE THREAD

**Issue by foxtrotdev** [iBotPeaches/Apktool#3049]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that the current bug report template does not include information about the Java version being used, which can be crucial in diagnosing and resolving issues related to Java-based applications. For example, when encountering an error while using the apktool, I found that different Java versions resulted in different outcomes. This lack of information in bug reports can lead to confusion and ineffective troubleshooting.

**Describe the solution you'd like**
I would like to suggest adding a 4th element to the bug report template that specifies the Java version being used. This will allow developers and support teams to quickly identify the Java version used and determine whether it is compatible with the software in question. By including this information, we can improve the accuracy and effectiveness of bug reporting, leading to faster and more efficient issue resolution.

**Additional context**
In my experience, having the Java version included in bug reports can greatly improve the troubleshooting process. For example, when I encountered an issue with apktool, I found that the Java version being used was a crucial factor in determining the root cause of the problem. Without this information, it would have been much more difficult to diagnose and resolve the issue. By including Java version information in bug reports, we can ensure that developers and support teams have all the information they need to quickly and effectively troubleshoot issues.

**Comment by iBotPeaches** [comment]
Seems sane. Will accept PR for it or add it next time I sit down to work on this project.
