### ISSUE TITLE
Move smali dependency to https://github.com/google/smali

### ISSUE THREAD

**Issue by sgjesse** [iBotPeaches/Apktool#3050]
Going forward the smali project will be maintained by Google in https://github.com/google/smali. Artifacts are released on [Google Maven](https://maven.google.com/web/index.html?q=smali).

Please note that the namespace was changed from `org.jf` to `com.android.tools.smali` ([PR](https://github.com/google/smali/pull/4)).

**Comment by iBotPeaches** [comment]
Okay thanks. I struggled to find a changelog of changes without manually peeking commits which is my only feedback.
