### ISSUE TITLE
I: Using Apktool 2.7.0 I: Smaling smali folder into classes.dex... I: Smaling smali_classes2 folder into classes2.dex... I: Smaling smali_classes3 folder into classes3.dex... I: Smaling smali_classes4 folder into classes4.dex... I: Building resources... W: Failed to generate resource table for split '' W: C:\Users\ss\OneDrive\Desktop\Apk Esay Tool\1-Decompiled APKs\com.whatsapp_2.23.9.19-230919004_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com_src\res\values-v31\colors.xml:27: error: Error: Resource is not public. (at 'color_7f060651' with value '@android:color/Indigo_700'). W:  brut.androlib.AndrolibException:

### ISSUE THREAD

**Issue by tejasnikumbh1432** [iBotPeaches/Apktool#3052]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
You were probably using a private resource, which newer build tools fail during compilation. You could trick it by doing `@*android:color/Indigo_700` if you want.

**Comment by tejasnikumbh1432** [comment]
Thanks bro

**Comment by tejasnikumbh1432** [comment]
All @*android ... Apply for all ?
