### ISSUE TITLE
[BUG] Cannot install a signed file due to a signature error.

### ISSUE THREAD

**Issue by creeper-0910** [iBotPeaches/Apktool#3053]
### Information
1. **Apktool Version: 2.7.0** -
2. **Operating System: Windows** -
3. **APK From?: Other** -
4. **Java Version: 17.0.3.1** -

### Steps to Reproduce
1. `java -jar apktool_2.7.0.jar d adguard.apk  --use-aapt2`
```
I: Using Apktool 2.7.0 on adguard.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
```
2. `java -jar apktool_2.7.0.jar b adguard -o adguard_2.apk   --use-aapt2`
```
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: adguard_2.apk
```
4. `apksigner sign --ks test.keystore -v --ks-key-alias TEST adguard_2.apk`
```
Signed
```
5. `apksigner verify -v -v4-signature-file adguard_2.apk.idsig adguard_2.apk`
```
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true
Verified using v3.1 scheme (APK Signature Scheme v3.1): false
Verified using v4 scheme (APK Signature Scheme v4): true
Verified for SourceStamp: false
Number of signers: 1
```

I decompiled AdGuard with Apktools and replaced and recompiled the translation files to see how the translations applied.
However, despite being signed, it could not be successfully installed due to a signature error. (Probably a problem with the file structure.)

### APK
You can download the latest version from the bottom of this site: https://adguard.com/ja/blog/adguard-v4-0-for-android-nightly.html

1. Have you tried `apktool d`, `apktool b` without changing anything?:Yes
2. If you are trying to install a modified apk, did you resign it?:Yes
3. Are you using the latest apktool version?:Yes

I decompiled AdGuard with Apktools and replaced and recompiled the translation files to see how the translations applied.
However, despite being signed, it could not be successfully installed due to a signature error. (Probably a problem with the file structure.)
I don't like AdGuard's translation and am just trying to apply my own translation of the xml.
Please understand that this is not intended to redistribute or unlock paid features.

**Comment by iBotPeaches** [comment]
Do you have a logcat during the install procedure that shows what is happening? Normally we'd see the exact validation failures for the signature scheme.

**Comment by creeper-0910** [comment]
[log.txt](https://github.com/iBotPeaches/Apktool/files/11366316/log.txt)
Sorry, I have the logs, but they are so voluminous that I could not check to see if there was an error...

**Comment by iBotPeaches** [comment]
some of the newer signature schemes really don't jive with zipalign. Over time you had to zipalign prior or after depending on the tool and signature scheme used.

I'll figure this response means you are set, so I'll resolve.
