### ISSUE TITLE
[BUG] Res not found

### ISSUE THREAD

**Issue by wjj1928** [iBotPeaches/Apktool#3057]
### Information
1. **Apktool Version (`apktool -version`) v2.7.0
2. **Operating System: Linux ubuntu
3. **APK From? Playstore YxxT
5. **Java Version 11.0.14

### Stacktrace/Logcat

```
Include stacktrace here
```
05-01 12:54:32.903 27280 27280 E AndroidRuntime: FATAL EXCEPTION: main
05-01 12:54:32.903 27280 27280 E AndroidRuntime: Process: com.xx.xx.YT, PID: 27280
05-01 12:54:32.903 27280 27280 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xx.YT/com.xx.xx..Shell_HomeActivity}: android.content.res.Resources$NotFoundException: Drawable com.xx.:drawable/quantum_launchscreen_yt with resource ID #0x7f080a79
05-01 12:54:32.903 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3477)
05-01 12:54:32.903 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)

### Steps to Reproduce
1. `apktool `d YT.apk
2. apktool b YT
3. sign apk
4. Install apk, run it get crash stack.

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
5. If you are trying to install a modified apk, did you resign it? Yes
6. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Sorry for delay - closing for existing - https://github.com/iBotPeaches/Apktool/issues/2849
