### ISSUE TITLE
No Split Apk Support?

### ISSUE THREAD

**Issue by StrafeYourself** [iBotPeaches/Apktool#3060]
Hello, the tool you have here works amazingly. but the only problem is that I realized it couldn't convert split apk's witch most android apps runoff these days witch is kind of sad for me since I am a archiver I have had to besought to other apps that do the job but overwrites the original signature causing it to not install. I just wish I had something that works fully! 😭

From

StrafeYourself

P.S keep up the amazing work! 👍

**Comment by iBotPeaches** [comment]
Sadly I'm under belief that apktool should work with `.apks` - its best left for other tools to meld/merge/combine splits to build a combined one.

For example like this project - https://forum.xda-developers.com/t/how-to-merge-splited-apk-files.4529011/

thanks btw, but I am going to close this as its not possible for apktool at the moment.
