### ISSUE TITLE
[BUG] Error while writing instruction at code offset 0x8

### ISSUE THREAD

**Issue by StillTogether** [iBotPeaches/Apktool#3061]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** -other
4. **Java Version (`java --version`)** -11

### Stacktrace/Logcat

Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x8 at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319) at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1042) ... 39 common frames omitted Caused by: org.jf.util.ExceptionWithContext: Item not found.: (J)Ljava/util/Date; at org.jf.dexlib2.writer.pool.BaseIndexPool.getItemIndex(BaseIndexPool.java:54) at org.jf.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:561) at org.jf.dexlib2.writer.InstructionWriter.getReference2Index(InstructionWriter.java:546) at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:429) at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1297) ... 40 common frames omitted

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Possible for APK to test replication?

**Comment by StillTogether** [comment]
> 

sorry, I can't provide APK. I also used local code integration Smali 2.24 and 2.4.0, and occurred the same issue.

**Comment by TimScriptov** [comment]
@StillTogether use smali 3.0.3

**Comment by StillTogether** [comment]
> @StillTogether use smali 3.0.3

Thanks very much for your advice!
But could you tell me the root cause? It is very strange.
Thanks again~

**Comment by StillTogether** [comment]
More information:
When I use 2.7.0  succeed, but when I use 2.6.0 still failed with below error:
`>java -jar apktool_2.6.0.jar d "test18.apk" -o D:\Defect\test18
I: Using Apktool 2.6.0 on test18.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000012
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000032
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000012
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000032
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\AppData\Local\apktool\framework\1.apk`

**Comment by iBotPeaches** [comment]
Going to close because w/ no APK I cannot confirm and since we updated the internal smali to 3.0.3 in upcoming release - thats my best resolution.

**Comment by StillTogether** [comment]
> Going to close because w/ no APK I cannot confirm and since we updated the internal smali to 3.0.3 in upcoming release - thats my best resolution.

Ok, thanks very much!
