### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by RenzoPH** [iBotPeaches/Apktool#3064]
I encountering this issue, while building a apk file in Android using ionic copacitor. Asking for your help. if these anyone are experiencing this issue also?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/runner/work/1/s/android/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:121: AAPT: error: attribute android:dataExtractionRules not found.

**Comment by iBotPeaches** [comment]
I think you are in wrong repo. What does Apktool have to do with building an application in Ionic?
