### ISSUE TITLE
[BUG] Apktool does not work on Aarch64 Linux - Aarch64 native support ???

### ISSUE THREAD

**Issue by Gary-Cod** [iBotPeaches/Apktool#3065]
Ubuntu - Aarch64

ub@ub:~/Downloads/Apks$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

ub@ub:~/Downloads/Apks$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)

ub@ub:~/Downloads/Apks$ java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)
ub@ub:~/Downloads/Apks$ 

ub@ub:~/Downloads/Apks$ apktool --version
2.7.0

ub@ub:~/Downloads/Apks$ apktool d My_App.apk 
I: Using Apktool 2.7.0 on My_App.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ub/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

ub@ub:~/Downloads/Apks$ apktool b My_App
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/brut_util_Jar_16298199573555603067879986396696396258.tmp: 1: ELF: not found
W: /tmp/brut_util_Jar_16298199573555603067879986396696396258.tmp: 714: Syntax error: "(" unexpected
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_16298199573555603067879986396696396258.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 8, --version-name, 2.1.0, --no-version-vectors, -F, /tmp/APKTOOL13516318335608557975.tmp, -e, /tmp/APKTOOL4384528196547386693.tmp, -0, arsc, -I, /home/ub/.local/share/apktool/framework/1.apk, -S, /home/ub/Downloads/Apks/My_App/res, -M, /home/ub/Downloads/Apks/My_App/AndroidManifest.xml]

--------------------------------------

I have tested multiple Aarch64/Arm64 Linux distro's but apktool doesn't work ??? 
I have also tested the repository "apktool_aarch64 version" provided by the distro's repository but they also not work
I tested the 5 different apks : 
- apks decompile & compile successfully on Ubuntu, Parrot, Kali - "x64" Linux
But
- apks does not compile successfully on Ubuntu, Parrot, Kali - "Aarch64 - Arm64" Linux

i don't know what is the problem ??

Can you please support native apktool for Aarch64 ??

**Comment by iBotPeaches** [comment]
> Can you please support native apktool for Aarch64 ??

Apologies its not on the roadmap. I'm not aware how to cross-compile AOSP for that support.
