### ISSUE TITLE
com.google.firebase.crashlytics

### ISSUE THREAD

**Issue by shuajinanhai** [iBotPeaches/Apktool#3075]
<string-array name="com.google.firebase.crashlytics.build_ids_arch">
        <item>aarch64</item>
        <item>aarch64</item>
        <item>arm</item>
        <item>arm</item>
        <item>x86</item>
        <item>x86</item>
        <item>x86_64</item>
        <item>x86_64</item>
    </string-array>
    <string-array name="com.google.firebase.crashlytics.build_ids_build_id">
        <item>df3f83af4e54f316c793c3655c4753a8851a234c</item>
        <item>610ce20f4f4d72c9ea90e8397cdc85fe10fcd437</item>
        <item>e6d72b82b07b8c2b8fae6bc6dd2ea5ab939ecc98</item>
        <item>661666c53d516d762f40dff934745ce2a7c45fc1</item>
        <item>9e7b05b95a7c8b01af855b3c4d7c001cf12fff0d</item>
        <item>c89e2423c977e66eb37780aadf11c30977477c21</item>
        <item>2545b538ce07dcf117084b3851ecc9fd0eadc7b9</item>
        <item>f8205160d3cd6498d85bfce20fca3aa5df92c155</item>
    </string-array>
    <string-array name="com.google.firebase.crashlytics.build_ids_lib">
        <item>libc++_shared.so</item>
        <item>libdinHunter.so</item>
        <item>libc++_shared.so</item>
        <item>libdinHunter.so</item>
        <item>libc++_shared.so</item>
        <item>libdinHunter.so</item>
        <item>libc++_shared.so</item>
        <item>libdinHunter.so</item>
    </string-array>

>W: C:\Apk\AndroidKiller\projects\test\Project\res\values\arrays.xml:21: error: Error retrieving parent for item: No resource found that matches the given name 'com.google.firebase.crashlytics'.
>W: 
>W: C:\Apk\AndroidKiller\projects\test\Project\res\values\arrays.xml:31: error: Error retrieving parent for item: No resource found that matches the given name 'com.google.firebase.crashlytics'.
>W: 
>W: C:\Apk\AndroidKiller\projects\test\Project\res\values\arrays.xml:41: error: Error retrieving parent for item: No resource found that matches the given name 'com.google.firebase.crashlytics'.

**Comment by iBotPeaches** [comment]
@shuajinanhai - Thanks for the report, but honestly - I don't know what to do with this amount of detail. You have an error and some sample array elements. The scope of this information isn't enough to work on - so I'm closing this.
