### ISSUE TITLE
[BUG]getCanonicalPath have bug on Windows

### ISSUE THREAD

**Issue by helengray** [iBotPeaches/Apktool#3077]
### Information
1. **Apktool Version (`apktool -version`)** -2.7.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -other
4. **Java Version (`java --version`)** -11

BrutIO.sanitizeUnknownFile(directory,entry)
->
entry = "ln.xml"
->
String canonicalEntryPath = new File(directory, entry).getCanonicalPath()
->
String fileName2 = canonicalEntryPath.substring(canonicalDirPath.length())
->
the fileName2 = "LN.xml" why??

fileName2 = "ln.xml" the true?
### Stacktrace/Logcat

sanitizeUnknownFile:90, BrutIO (brut.util)
copyToDir:91, DirUtil (brut.directory)
copyToDir:71, DirUtil (brut.directory)
copyToDir:198, AbstractDirectory (brut.directory)
copyToDir:87, DirUtil (brut.directory)
copyToDir:78, DirUtil (brut.directory)
copyToDir:203, AbstractDirectory (brut.directory)
decodeResourcesRaw:134, Androlib (brut.androlib)
decode:99, ApkDecoder (brut.androlib)
cmdDecode:175, Main (brut.apktool)
main:79, Main (brut.apktool)

### Steps to Reproduce
1. `apktool  d -r` 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?Y
2. If you are trying to install a modified apk, did you resign it?Y
3. Are you using the latest apktool version?Y

**Comment by iBotPeaches** [comment]
@helengray - I'm trying to follow this. Are you saying on Windows `getCanonicalPath` changes the casing of the parameter to be lowercase?

**Comment by helengray** [comment]
> @helengray - I'm trying to follow this. Are you saying on Windows `getCanonicalPath` changes the casing of the parameter to be lowercase?

to be uppercase

**Comment by helengray** [comment]
I see, because Windows is case insensitive, resulting in resource name conflicts

**Comment by iBotPeaches** [comment]
I see - this is a long standing issue related to handling of assets on case-insensitive filesystems.

Since I only work on mac/linux. I don't see myself personally working on this, so just setting your expectations fairly.

https://github.com/iBotPeaches/Apktool/issues/1460
