### ISSUE TITLE
Code metrics using MetricsReloaded plugin

### ISSUE THREAD

**Issue by dimitrios-ath** [iBotPeaches/Apktool#3078]
Hey everyone,

I calculated some code metrics using the **MetricsReloaded** plugin for a university project, and I thought it would be a good idea to **share** the results here. I **attached** two pdf files, one for **complexity metrics** and one for **Chidamber-Kemerer metrics**. The results that are highlighted in _red colour_ exceed the default value, and the results highlighted in _orange colour_ are relatively high.

Best regards,
Dimitris

[chidamber_kemerer_metrics.pdf](https://github.com/iBotPeaches/Apktool/files/11544639/chidamber_kemerer_metrics.pdf)
[complexity_metrics.pdf](https://github.com/iBotPeaches/Apktool/files/11544640/complexity_metrics.pdf)

**Comment by iBotPeaches** [comment]
thanks!

However, since I have almost 100 bugs/features. Code complexity is not something I am focusing at the moment. Only making tiny improvements in areas as I work in them.
