### ISSUE TITLE
[BUG]: Rebuilt apps fails to Install on Android 9 bcs of native lib extraction  failure.

### ISSUE THREAD

**Issue by Anonymous2716** [iBotPeaches/Apktool#3081]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - linux
3. **APK From? (Playstore, ROM, Other)** - multiple apps. From github / fdroid.
4. **Java Version (`java --version`)** - openjdk-17

### Stacktrace/Logcat

```
FAILED_TO_INSTALL_INVALID_APK Failed to extract native libraries res=-2 
```

### Steps to Reproduce
1. Install app after rebuilding. On Android 9.

### APK
1. https://f-droid.org/packages/org.dslul.openboard.inputmethod.latin
2. https://github.com/termux/termux-x11/actions/workflows/debug_build.yml

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes
2. If you are trying to install a modified apk, did you resign it? - yes
3. Are you using the latest apktool version? - yes

I currently don't have access to adb other than that I can provide any info you need.

Also on a recent issue I saw you are not aware of how to cross compile aapt for arm / aarch64 . then can you please provide the build instructions of how you build it for x86 or x86_64? Then the users like me can build on our own machines instead of setting up a few files , patch the jar to make it work? Or add to the project?

On Android termux provides aapt https://github.com/termux/termux-packages/tree/master/packages/aapt but that aapt doesn't work with  apktool. Everything else works. And for that I have to use apktool provided aapt. It is a good thing that its statically linked. Otherwise it would have been difficult to use on arm machines.

**Comment by iBotPeaches** [comment]
May you read through this? https://github.com/iBotPeaches/Apktool/issues/1626

I expect `extractNativeLibs` to play a part here.

To your 2nd question. Documentation for building is here: https://github.com/iBotPeaches/Apktool/blob/master/INTERNAL.md#building-aapt-binaries

**Comment by iBotPeaches** [comment]
aapt2 changes - https://github.com/iBotPeaches/platform_frameworks_base/commit/0a8449e0f0ab176bd83a05467d43766418b528b2

aapt1 changes - https://github.com/iBotPeaches/platform_frameworks_base/commit/8098abd6bb2cbbd090caa08f3aa52d687aa41601

**Comment by Anonymous2716** [comment]
Thanks again. Have a good day.
