### ISSUE TITLE
hello sir I've error here 

### ISSUE THREAD

**Issue by msb2couled** [iBotPeaches/Apktool#3083]
i had write this command (java -jar apktool_2.6.0.jar b Instagram -o instagram+.apk) 

and this output :

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
W: Unknown file type, ignoring: Instagram/smali/com/instagram/process/instagram/classfile_constants.h
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Downloads/Instagram/res/values/styles.xml:4946: error: Resource entry InThreadComposerTextArea already has bag item android:textColorHint.
W: /root/Downloads/Instagram/res/values/styles.xml:4945: Originally defined here.
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6121646879215962065605861403722695642.tmp, p, --forced-package-id, 127, --min-sdk-version, 28, --target-sdk-version, 33, --version-code, 368600618, --version-name, 286.0.0.0.13, --no-version-vectors, -F, /tmp/APKTOOL16554348156784272109.tmp, -e, /tmp/APKTOOL4272316386319044814.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/Instagram/res, -M, /root/Downloads/Instagram/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
`--use-aapt2` should resolve this during build.

**Comment by msb2couled** [comment]
sir, could you please write the command 
thank you.
