### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by f1refa11** [iBotPeaches/Apktool#3084]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux Debian 10
3. **APK From? (Playstore, ROM, Other)** - itch.io lol
4. **Java Version (`java --version`)** - openjdk 17.0.6

### Stacktrace/Logcat

```
I: Using Apktool 2.7.0                                                                                                I: Checking whether sources has changed...                                                                            I: Checking whether resources has changed...                                                                          I: Building resources...                                                                                              brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/firefall/.local/share/apktool/framework/1.apk (No such file or directory)
```

### Steps to Reproduce
1. `apktool d` in game directory :)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://kulplant.itch.io/flaming-flagon 😳

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
I don't think this is a bug. Somehow your system is deleting files while Apktool is working. It would have generated that file at the beginning (or crashed if it failed) before it got to that point.

**Comment by f1refa11** [comment]
When i checked the 1.apk file it turned to be a symlink. Any ideas how can i fix it?

**Comment by iBotPeaches** [comment]
delete the sym link, then run `apktool empty-framework-dir` and retry decode and build.

**Comment by f1refa11** [comment]
```
W: Can't empty framework directory, no file found at: /home/firefall/.local/share/apktool/framework/1.apk
```
😔
