### ISSUE TITLE
Hi sir, I've problem in apktool!, 

### ISSUE THREAD

**Issue by msb2couled** [iBotPeaches/Apktool#3086]
When I type the decryption command (apktool d myapp.apk), I see that it works!, but when I build the app.apk again, I see this output text
------------------------------------------------------------------------------------
apktool b Instagram_284.0.0.22.85_apkcombo.com instagramm.apk
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Downloads/Instagram_284.0.0.22.85_apkcombo.com/res/values/styles.xml:4889: error: Resource entry InThreadComposerTextArea already has bag item android:textColorHint.
W: /root/Downloads/Instagram_284.0.0.22.85_apkcombo.com/res/values/styles.xml:4888: Originally defined here.
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_83375448261205534491881469125076275974.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 368407127, --version-name, 284.0.0.22.85, --no-version-vectors, -F, /tmp/APKTOOL17272418834505311840.tmp, -e, /tmp/APKTOOL7569461893768925314.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/Instagram_284.0.0.22.85_apkcombo.com/res, -M, /root/Downloads/Instagram_284.0.0.22.85_apkcombo.com/AndroidManifest.xml]

how can i fix it ???

**Comment by iBotPeaches** [comment]
Sorry without the template followed. Not sure I can help here.

Looks like you could remove the duplicate item or try with aapt2.

**Comment by msb2couled** [comment]
apktool b --use-aapt2 Instagram_284.0.0.22.85_apkcombo.com -o instagram.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt2_64 (defaulting to $PATH binary)
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-h640dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-h640dp/layouts.xml: error: file failed to compile.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-land/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-land/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-land/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-land/layouts.xml: error: file failed to compile.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-sw600dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-sw600dp/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-sw600dp/layouts.xml: error: file failed to compile.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-v26/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values-v26/layouts.xml: error: file failed to compile.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:8: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:9: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:10: error: invalid value for type 'layout'. Expected a reference.
W: /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res/values/layouts.xml:11: error: invalid value for type 'layout'. Expected a reference.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt2, compile, --dir, /root/tools/Instagram_284.0.0.22.85_apkcombo.com/res, --legacy, -o, /root/tools/Instagram_284.0.0.22.85_apkcombo.com/build/resources.zip]


I don't know why any solution non works with me !! :(
