### ISSUE TITLE
hi I've error in apktool : Error: Unable to rebuild apk with apktool, what can i do ? 

### ISSUE THREAD

**Issue by msb2couled** [iBotPeaches/Apktool#3087]
I: Building resources...
W: /tmp/d20230603-50256-ykm2ky/original/res/values-h640dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-h640dp/layouts.xml: error: file failed to compile.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-land/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-land/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-land/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-land/layouts.xml: error: file failed to compile.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-sw600dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-sw600dp/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values-sw600dp/layouts.xml: error: file failed to compile.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:8: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:9: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:10: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:11: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:12: error: invalid value for type 'layout'. Expected a reference.
W: /tmp/d20230603-50256-ykm2ky/original/res/values/layouts.xml:13: error: invalid value for type 'layout'. Expected a reference.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_80615247207453448138784186474704019787.tmp, compile, --dir, /tmp/d20230603-50256-ykm2ky/original/res, --legacy, -o, /tmp/d20230603-50256-ykm2ky/original/build/resources.zip]
Error: Unable to rebuild apk with apktool

**Comment by iBotPeaches** [comment]
Sorry without template - not much I can do.
