### ISSUE TITLE
[FEAT] Suppress warnings

### ISSUE THREAD

**Issue by ferib** [iBotPeaches/Apktool#3089]
**Is your feature request related to a problem? Please describe.**
Non-critical warnings are being passed into my stderr and I don't see a way to suppress them. 

Would it be possible to add a CLI flag so only critical errors are outputted?

**Describe the solution you'd like**
Somehow suppress `LOGGER.warning` calls when a certain CLI flag is set.

**Additional context**
N/A

**Comment by ferib** [comment]
Bingo, `-q` is indeed in there https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L66

My bad but I couldn't see it in the help/usage 🙃, Thanks!

**Comment by iBotPeaches** [comment]
I felt it was too much text in the usage to repeat verbosity/quiet each time. It hides under the `-advance` toggle.

```
➜  ~ apktool -advance
Apktool v2.7.0 - a tool for reengineering Android apk files
with smali v2.5.2-403e9037 and baksmali v2.5.2-403e9037
Copyright 2010 Ryszard Wiśniewski <brut.alll@gmail.com>
Copyright 2010 Connor Tumbleson <connor.tumbleson@gmail.com>
Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)

usage: apktool [-q|--quiet OR -v|--verbose]
 -advance,--advanced   prints advance information.
 -version,--version    prints the version then exits
 ```
