### ISSUE TITLE
[BUG] Flutter app is impossible to rebuild

### ISSUE THREAD

**Issue by Insadem** [iBotPeaches/Apktool#3094]
### Steps to Reproduce
Decompile and recompile flutter app.
It will crash on launch and write this in logs: 
"java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found"
You don't have to change anything in code to prove that it doesn't work.
I had experience with changing apks before, but in this situation it's certainly related to flutter framework.

### Questions to ask before submission
1. Yes
2. Yes
3. Yes

**Comment by iBotPeaches** [comment]
Sorry - With that detail and no sample flutter app. I don't see this ticket going anywhere.
