### ISSUE TITLE
Better Support for Duplicate Entires in Complex Entries of resources.arsc File(s)

### ISSUE THREAD

**Issue by fmresearchnovak** [iBotPeaches/Apktool#3098]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when apktool fails to decode and then rebuild an app without any modifications.  I often see an error message of the format "brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)"
Example Run: [apktool_decode_and_build_bug.txt](https://github.com/iBotPeaches/Apktool/files/11849674/apktool_decode_and_build_bug.txt)
APK in question: [https://drive.google.com/file/d/1K21D0EoyUd-N65_ZvCtE5cEJxwQR_4gT/view?usp=sharing](https://drive.google.com/file/d/1K21D0EoyUd-N65_ZvCtE5cEJxwQR_4gT/view?usp=sharing)

**Describe the solution you'd like**
apktool should better handle duplicate resource items in the "complex" entries of resources.arsc file(s).

**Additional context**
I spent a good amount of time debugging the error to come to the conclusion that the problem is duplicate items in complex entries of the resources.arsc file(s).  I cloned and built the latest version of apktool from the github repo.  I modified the code and used the debugger in vscode to determine the error.  I think I know exactly what the problem is, and I can envision some possible fixes.  But I am unsure what fix would be best in the context of the rest of the project.  Please advise!

**Deep details**
The AndroidlibException is thrown when the target app is being rebuilt, but actually the problem originates when the app is being decoded.  For some reason, it appears that this specific app contains a duplicate of the attribute "textColorHint" within the "InThreadComposerTextArea" style in the file:  res/values/styles.xml

```
...
        <item name="updatableButtonStyle">@style/IgUpdatableButtonStyle.Night</item>
    </style>
    <style name="InThreadComposerTextArea">
        <item name="android:textColor">?textColorPrimary</item>
        <item name="android:textColorHint">?textColorTertiary</item>
        <item name="android:textColorHint">@color/igds_secondary_text</item>
        <item name="android:ellipsize">end</item>
...        
```

When apktool tries to rebuild the app it runs aapt (/tmp/brut_util_Jar_175556099043862357057969092782900861816.tmp), which fails due to the duplicate item.   ```LOGGER.warning()``` is called twice pointing out exactly these two lines (see my example run linked above).

Digging into the code I found that `ARSCDecoder.java` generates the `styles.xml` file and the various "items" in the "style" block are encoded as an array of DUO objects.  In this specific case they are created in the `readComplexEntry()` function so it is a ```Duo<Integer, ResScalarValue>[]```.  "android:textColorHint" apparently is resId 16842906.

On a related note, I found that my local `framework/1.apk` file also contains duplicate items in several different places within some *.arsc file(s).  I am a little more uncertain about the nature of these duplicates so I am not sure if my ideas on how to fix this bug would be compatible.

**Ideas on how to fix**
Idea 1 - Store only the first DUO instance with a given resId into the array *OR* store only the second DUO instance (overwriting the first).  This seem straightforward, but I am unsure if it is appropriate since the `count` (size of the array) seems to have been read from the resources.arsc file.  This is an array after all, suddenly having one less item in it might cause problems elsewhere?

Idea 2 - Implement the collection of DUO objects has a hashmap (or some type of Set).  Not sure how many other areas of the code would need to change to accommodate this.   Idea.  It's probably not worth the efficiency gain since there seems to be rarely more than 1000 items.  But, it is an elegant way to store a collection while handling duplicates.

Idea 3 - Present a more elaborate and explanatory error to the user ___at decode time___.

I am open to suggestions and input in order to craft a pull request that fixes this bug prudently :)  I would also be interested in conversing via video-chat if that seems productive to you.

**Comment by fmresearchnovak** [comment]
Yes!  I agree!  My first inclination was to try to read the original arsc file myself, extracted directly from the app.  But, it seems arsc is a binary format.  I spent some time trying to find documentation about the layout / expected form of the arsc file but I couldn't find anything useful (best thing I found: [https://juejin.cn/post/7072897327509274631](https://juejin.cn/post/7072897327509274631)).

I could use a third party tool to try to read it e.g., [https://github.com/google/android-arscblamer](https://github.com/google/android-arscblamer). Can I trust what such a tool shows me?  I'm afraid any tools I use will automatically remedy the duplicate entry thereby fooling me into thinking it's not actually there.  I feel pretty confident trusting the internals of apktool that the duplicate entry is actually there.

Anyway, ___do you have any documentation, resources, or suggestions for how to read the `resources.arsc` file?___

I tried building with aapt2: [apktool_decode_and_build_bug_aapt2.txt](https://github.com/iBotPeaches/Apktool/files/11857054/apktool_decode_and_build_bug_aapt2.txt)
The errors are different and the rebuild process still fails to complete.  I think this particular `instagram.apk` file was built / designed with the original aapt.  My understanding is that apps which require aapt2 will have a file `app-metadata.properties` that lists `androidGradlePluginVersion=3.x` or newer.  Is that not true?  This apk does not seem to have any such file.

 I will dig into it deeper into the aapt2 run next week to see if the same duplicate entry issue is still present. 


___Please let me know if you have any other thoughts or suggestions.___

Thank you! :)

**Comment by fmresearchnovak** [comment]
Any thoughts on the next step? @iBotPeaches 

I could dig deeper into the bug / code.

We could declare this bug / feature "closed as not planned"

If you  have time you could look at the `resources.arsc` file from this app and the `ARSCDecoder.java` code to gain some insight about the bug?

**Comment by iBotPeaches** [comment]
Not at this time. Haven't looked. I wanted to look at the outer resourceId of the array and step through the parsing to see if we introduced a duplicate or improperly parsed the item.

**Comment by iBotPeaches** [comment]
Did some initial investigation.

```xml
    <style name="InThreadComposerTextArea">
        <item name="android:textColor">?textColorPrimary</item>
        <item name="android:textColorHint">?textColorTertiary</item>
        <item name="android:textColorHint">@color/igds_secondary_text</item>
        <item name="android:ellipsize">end</item>
        <item name="android:background">@null</item>
        <item name="android:paddingTop">@dimen/account_discovery_bottom_gap</item>
        <item name="android:paddingBottom">@dimen/account_discovery_bottom_gap</item>
        <item name="android:hint">@null</item>
        <item name="android:maxLines">@integer/composer_max_lines</item>
        <item name="android:maxLength">@integer/max_message_length</item>
        <item name="android:popupBackground">?backgroundColorPrimary</item>
        <item name="android:inputType">textAutoCorrect|textCapSentences|textMultiLine</item>
        <item name="android:imeOptions">actionNone</item>
    </style>
```

So we decode 13 entries and do indeed have 13 items at time of writing entries, so the issue (if it exists) lies in the arsc decoding.

However, the arsc table doesn't lie. It says 13 entries. So Apktool isn't doing anything wrong from what I can see.

![Screenshot from 2023-07-08 15-54-03](https://github.com/iBotPeaches/Apktool/assets/611784/74101a68-33b2-4b10-acf7-195572458947)

**Comment by iBotPeaches** [comment]
Wrote a quick debug line to help detect duplicates and it happens 4 times in this application.

```
W: Multiple bag attributes declared for item with ID 0x01010374
W: Multiple bag attributes declared for item with ID 0x011200f1
W: Multiple bag attributes declared for item with ID 0x01120125
W: Multiple bag attributes declared for item with ID 0x01120126
```

However, since only 1 was detected by aapt and causing an issue. I'm starting to believe this is alright behavior and the true fix remains unknown.

**Comment by iBotPeaches** [comment]
Investigating this in detail though - I've discovered what path we take (aapt1/aapt2) are both existing bugs. So I'll take any additional research/help in those now that I've tracked this down to root issues and will close this one out.

* double bag item - https://github.com/iBotPeaches/Apktool/issues/1927
* same instagram issue with aapt2 rebuilds - https://github.com/iBotPeaches/Apktool/issues/2618

**Comment by fmresearchnovak** [comment]
Interestingly, three of the "multiple bag attributes" instances of the four you found in this application are from the framework/1.apk file.
