### ISSUE TITLE
[BUG] No resource identifier found for attribute <XY> in package <Z> / resource <XY> is private

### ISSUE THREAD

**Issue by auermich93** [iBotPeaches/Apktool#3099]
### Information
1. **Apktool Version (`apktool -version`)** -2.7.1
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** - FDroid
4. **Java Version (`java --version`)** - 15.0.2

### Steps to Reproduce
```
I: Using Apktool 2.7.1-25509a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
W: 
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
W: 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_47603965767365264417935590388649611689.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-version-vectors, -F, C:\Users\Michael\AppData\Local\Temp\APKTOOL7480544710484992623.tmp, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL18030168975414317148.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Michael\git\Apktool\de.baumann.browser\res, -M, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml]

```
With `--use-aapt2` flag:

```
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:3: error: resource android:color/Teal_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:4: error: resource android:color/Teal_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:5: error: resource android:color/Blue_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:6: error: resource android:color/Red_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:7: error: resource android:color/Red_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:8: error: resource android:color/Purple_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:9: error: resource android:color/Purple_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:10: error: resource android:color/Pink_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:11: error: resource android:color/Pink_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:12: error: resource android:color/Indigo_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:13: error: resource android:color/Indigo_700 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:14: error: resource android:color/GM2_grey_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:15: error: resource android:color/Blue_800 is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:16: error: resource android:color/background_cache_hint_selector_device_default is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:17: error: resource android:color/autofilled_highlight is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:18: error: resource android:color/accent_device_default is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:19: error: resource android:color/autofill_background_material_light is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:20: error: resource android:color/autofill_background_material_dark is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:21: error: resource android:color/accessibility_focus_highlight is private.
W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:22: error: resource android:color/accent_material_light is private.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_180767586932586388343457823441952700614.tmp, link, -o, C:\Users\Michael\AppData\Local\Temp\APKTOOL15515566146286065677.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL17552753562330406453.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml, C:\Users\Michael\git\Apktool\de.baumann.browser\build\resources.zip]
```

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://github.com/scoute-dich/browser/releases/download/v9.11/app-debug.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES.
3. If you are trying to install a modified apk, did you resign it? YES.
4. Are you using the latest apktool version? YES.

**Comment by Krowne** [comment]
> ### Information
> 1. **Apktool Version (`apktool -version`)** -2.7.1
> 2. **Operating System (Mac, Linux, Windows)** -Windows
> 3. **APK From? (Playstore, ROM, Other)** - FDroid
> 4. **Java Version (`java --version`)** - 15.0.2
> 
> ### Steps to Reproduce
> ```
> I: Using Apktool 2.7.1-25509a-SNAPSHOT
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> W: 
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> W: 
> brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_47603965767365264417935590388649611689.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-version-vectors, -F, C:\Users\Michael\AppData\Local\Temp\APKTOOL7480544710484992623.tmp, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL18030168975414317148.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Michael\git\Apktool\de.baumann.browser\res, -M, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml]
> ```
> 
> With `--use-aapt2` flag:
> 
> ```
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:3: error: resource android:color/Teal_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:4: error: resource android:color/Teal_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:5: error: resource android:color/Blue_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:6: error: resource android:color/Red_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:7: error: resource android:color/Red_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:8: error: resource android:color/Purple_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:9: error: resource android:color/Purple_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:10: error: resource android:color/Pink_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:11: error: resource android:color/Pink_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:12: error: resource android:color/Indigo_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:13: error: resource android:color/Indigo_700 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:14: error: resource android:color/GM2_grey_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:15: error: resource android:color/Blue_800 is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:16: error: resource android:color/background_cache_hint_selector_device_default is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:17: error: resource android:color/autofilled_highlight is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:18: error: resource android:color/accent_device_default is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:19: error: resource android:color/autofill_background_material_light is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:20: error: resource android:color/autofill_background_material_dark is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:21: error: resource android:color/accessibility_focus_highlight is private.
> W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:22: error: resource android:color/accent_material_light is private.
> brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_180767586932586388343457823441952700614.tmp, link, -o, C:\Users\Michael\AppData\Local\Temp\APKTOOL15515566146286065677.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL17552753562330406453.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml, C:\Users\Michael\git\Apktool\de.baumann.browser\build\resources.zip]
> ```
> 
> ### APK
> If this APK can be freely shared, please upload/attach a link to it. https://github.com/scoute-dich/browser/releases/download/v9.11/app-debug.apk
> 
> ### Questions to ask before submission
> 1. Have you tried `apktool d`, `apktool b` without changing anything? YES.
> 2. If you are trying to install a modified apk, did you resign it? YES.
> 3. Are you using the latest apktool version? YES.

With a framework-res.apk with SDK version 33, you won't have that problem.

**Comment by iBotPeaches** [comment]
Not an issue in upcoming release.

```
➜  3099 apktool d app-debug.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-48b71b-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes7.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3099 apktool b app-debug
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-48b71b-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
```

**Comment by auermich93** [comment]
@iBotPeaches I just tried it out with the latest apktool version (2.8.1) and it still fails. What I make wrong here?

**Comment by iBotPeaches** [comment]
I don't know?

I just cleared my frameworks and did a basic decode/build test.

**Comment by auermich93** [comment]
Must have been a corrupted frameworks dir. Thx.

**Comment by andreasc1** [comment]
> > ### Information
> > 
> > 1. **Apktool Version (`apktool -version`)** -2.7.1
> > 2. **Operating System (Mac, Linux, Windows)** -Windows
> > 3. **APK From? (Playstore, ROM, Other)** - FDroid
> > 4. **Java Version (`java --version`)** - 15.0.2
> > 
> > ### Steps to Reproduce
> > ```
> > I: Using Apktool 2.7.1-25509a-SNAPSHOT
> > I: Checking whether sources has changed...
> > I: Smaling smali folder into classes.dex...
> > I: Checking whether resources has changed...
> > I: Building resources...
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral12.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral17.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral22.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral24.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral4.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral6.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral87.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral92.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral94.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral96.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: No resource identifier found for attribute 'lStar' in package 'android'
> > W: 
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\color-v31\m3_ref_palette_dynamic_neutral98.xml:4: error: Error: Resource is not public. (at 'color' with value '@android:color/Purple_800').
> > W: 
> > brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_47603965767365264417935590388649611689.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-version-vectors, -F, C:\Users\Michael\AppData\Local\Temp\APKTOOL7480544710484992623.tmp, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL18030168975414317148.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Michael\git\Apktool\de.baumann.browser\res, -M, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With `--use-aapt2` flag:
> > ```
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:3: error: resource android:color/Teal_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:4: error: resource android:color/Teal_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:5: error: resource android:color/Blue_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:6: error: resource android:color/Red_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:7: error: resource android:color/Red_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:8: error: resource android:color/Purple_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:9: error: resource android:color/Purple_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:10: error: resource android:color/Pink_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:11: error: resource android:color/Pink_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:12: error: resource android:color/Indigo_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:13: error: resource android:color/Indigo_700 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:14: error: resource android:color/GM2_grey_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:15: error: resource android:color/Blue_800 is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:16: error: resource android:color/background_cache_hint_selector_device_default is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:17: error: resource android:color/autofilled_highlight is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:18: error: resource android:color/accent_device_default is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:19: error: resource android:color/autofill_background_material_light is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:20: error: resource android:color/autofill_background_material_dark is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:21: error: resource android:color/accessibility_focus_highlight is private.
> > W: C:\Users\Michael\git\Apktool\de.baumann.browser\res\values-v31\colors.xml:22: error: resource android:color/accent_material_light is private.
> > brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_180767586932586388343457823441952700614.tmp, link, -o, C:\Users\Michael\AppData\Local\Temp\APKTOOL15515566146286065677.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 139, --version-name, 9.11, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\Michael\AppData\Local\Temp\APKTOOL17552753562330406453.tmp, -0, arsc, -I, C:\Users\Michael\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\Michael\git\Apktool\de.baumann.browser\AndroidManifest.xml, C:\Users\Michael\git\Apktool\de.baumann.browser\build\resources.zip]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### APK
> > If this APK can be freely shared, please upload/attach a link to it. https://github.com/scoute-dich/browser/releases/download/v9.11/app-debug.apk
> > ### Questions to ask before submission
> > 
> > 1. Have you tried `apktool d`, `apktool b` without changing anything? YES.
> > 2. If you are trying to install a modified apk, did you resign it? YES.
> > 3. Are you using the latest apktool version? YES.
> 
> With a framework-res.apk with SDK version 33, you won't have that problem.

hi, can you provide the framework-res.apk with sdk 33 that you use?
