### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by zareiramin** [iBotPeaches/Apktool#3101]
Dear support,

Decoding app works but rebuild throws an error. see following information.

### Information
1. Apktool Version:2.7.0
2. Operating System: Windows 
3. PlayStore
4. Java Version:openjdk 17.0.6 2023-01-17

### Stacktrace/Logcat
```
apktool.jar b C:/Users/xxxx/Downloads/folder/dist/folder2 --use-aapt2
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: apkPath\res\values-v22\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-v22\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-v22\layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-v22\layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-v22\layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-v22\layouts.xml: error: file failed to compile.
W: apkPath\res\values-w270dp-h560dp\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-w270dp-h560dp\layouts.xml: error: file failed to compile.
W: apkPath\res\values-watch\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: apkPath\res\values-watch\layouts.xml: error: file failed to compile.
W: apkPath\res\values\animators.xml:3: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:4: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:5: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:6: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:7: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:8: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:9: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:10: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml:11: error: invalid value for type 'animator'. Expected a reference.
W: apkPath\res\values\animators.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\xxxxxx\AppData\Local\Temp\brut_util_Jar_122132795710864174037307552364248972273.tmp, compile, --dir, C:\Users\xxxxx\Downloads\folder\dist\folder2\res, --legacy, -o, C:\Users\xxxxxx\Downloads\folder\dist\folder2\build\resources.zip]
Process exited with code 1.
```

### Steps to Reproduce
1. apktool d app.apk
2. change application.xml 
3. apk b appnew --use-aapt2

### APK
app link from play store: https://play.google.com/store/apps/details?id=com.rh.ot.android
app direct link: https://www.rayanhamafza.com/Assets/11/RH_1297_1.5.1-pilot-rayanWebsite-release.apk?version=20230626083801
Would you please check it.

**Comment by iBotPeaches** [comment]
As mentioned above and in my own test - I could not replicate this.

```
➜  3101 apktool d 3101.apk -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-7a22af-SNAPSHOT on 3101.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3101 apktool b 3101 --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-7a22af-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 3101/dist/3101.apk
➜  3101 
```

**Comment by zareiramin** [comment]
> Your link to the direct app doesn't seem to be working for me. I got a copy of the APK here: https://apkcombo.com/downloader/#package=com.rh.ot.android (build 1297).
> 
> I was unable to reproduce the error. I'm not sure what the difference is but there are several I think. First, I'm using Ubuntu 20.04.6 LTS with openjdk 11.0.19 2023-04-18
> 
> Maybe if you setup a virtual machine like mine you can use apktool on this app. It works for me on my machine! :)
> 
> ```
> user@machine:~/tmp$ java --version
> openjdk 11.0.19 2023-04-18
> OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
> user@machine:~/tmp$ cat /etc/issue
> Ubuntu 20.04.6 LTS \n \l
> 
> user@machine:~/tmp$ apktool d rayan_hamafza.apk -o rayan_hamafza/
> I: Using Apktool 2.7.0 on rayan_hamafza.apk
> I: Loading resource table...
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: /home/ed/.local/share/apktool/framework/1.apk
> I: Regular manifest package...
> I: Decoding file-resources...
> W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
> W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
> I: Decoding values */* XMLs...
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> I: Copying META-INF/services directory
> user@machine:~/tmp$ apktool b rayan_hamafza/ -o rebuilt_rayan_hamafza.apk --use-aapt2
> I: Using Apktool 2.7.0
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> I: Copying libs... (/lib)
> I: Copying libs... (/kotlin)
> I: Copying libs... (/META-INF/services)
> I: Building apk file...
> I: Copying unknown files/dir...
> I: Built apk into: rebuilt_rayan_hamafza.apk
> user@machine:~/tmp$ ls -l rebuilt_rayan_hamafza.apk 
> -rw-rw-r-- 1 user user 8406258 Jun 27 10:37 rebuilt_rayan_hamafza.apk
> ```

Thank you @fmresearchnovak , Problem solved using ubuntu.
