### ISSUE TITLE
[BUG] I reported an error when building with the apktool B command, ple help me

### ISSUE THREAD

**Issue by Jerrywang77** [iBotPeaches/Apktool#3128]
### Information
1. **Apktool Version (`apktool -version`)** -2.7.0
2. **Operating System (Mac, Linux, Windows)** -mac
3. **APK From? (Playstore, ROM, Other)** - Development debug
4. **Java Version (`java --version`)**  "1.8.0_151"

### Stacktrace/Logcat
W: invalid resource directory name: /Users/jerry/jerryking/Jerry/GoveeHome/Util/Decompilation/file/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/td/zkkf43sx4zd2pp85pwz0795m0000gp/T/brut_util_Jar_19065783164599488865285493720240900239.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 580, --version-name, 5.8.00, --no-version-vectors, -F, /var/folders/td/zkkf43sx4zd2pp85pwz0795m0000gp/T/APKTOOL8242752269328417561.tmp, -e, /var/folders/td/zkkf43sx4zd2pp85pwz0795m0000gp/T/APKTOOL3250995606889694169.tmp, -0, arsc, -I, /Users/jerry/Library/apktool/framework/1.apk, -S, /Users/jerry/jerryking/Jerry/GoveeHome/Util/Decompilation/file/res, -M, /Users/jerry/jerryking/Jerry/GoveeHome/Util/Decompilation/file/AndroidManifest.xml]

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? y
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? y

**Comment by iBotPeaches** [comment]
Generally when you see that res/navigation error - it means the previous application was built using aapt2 and thus not compatible with building with aapt1.

So just add `--use-aapt2` during build command.
