### ISSUE TITLE
[BUG] .line instead of actual code

### ISSUE THREAD

**Issue by iiasceri** [iBotPeaches/Apktool#3142]
### Information
1. Latest apktool 2.7
2. MacOS on m1 pro
3. apk playstore
4. java 20 arm

### Stacktrace/Logcat
I: Using Apktool 2.7.0 on jwlibrary.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/nick/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

### Steps to Reproduce
1. `apktool d .apk`

    .line 58
    .line 59
    .line 60
    return-void
    .line 61
    .line 62
    .line 63
    .line 64
    .line 65
.end method

meanwhile apkeditor shows the real code instead of .line

**Comment by iBotPeaches** [comment]
Link to apk?

**Comment by iBotPeaches** [comment]
You can use `-b` for no debug lines. Don't see enough details to go on here.

**Comment by iiasceri** [comment]
Sorry that was it -b my mistake. Is there any docs for purpose of debug lines? So I can educate myself and not disturb you once again :).
