### ISSUE TITLE
Apk size reduce about 20M when just do decode then build

### ISSUE THREAD

**Issue by hellovigoss** [iBotPeaches/Apktool#3168]
* apktool version: 17.0.4
* operate system: mac
* java version: 17.0.4
I got apk size reduce when just run decode and build. Is there some params missing?
![WX20230718-201250@2x](https://github.com/iBotPeaches/Apktool/assets/590771/fdf0bc35-dbb4-4720-b910-534589293580)

**Comment by iBotPeaches** [comment]
Not from what I see. 

I do have a little FAQ for this - https://apktool.org/docs/faq#resulting-apk-file-is-much-smaller-than-original-what-is-wrong

Since I don't see any way to investigate further - I'm closing this.
