### ISSUE TITLE
Builds broken - July 19, 2023

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#3174]
Somehow builds are all failing, even old ones.

https://github.com/iBotPeaches/Apktool/actions/runs/5586823977/jobs/10238074452

```
brut.androlib.aapt1.SharedLibraryTest > isSharedResourceDecodingAndRebuildingWorking FAILED
    brut.androlib.exceptions.AndrolibException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at app//brut.androlib.res.Framework.installFramework(Framework.java:105)
        at app//brut.androlib.res.Framework.installFramework(Framework.java:49)
        at app//brut.androlib.aapt1.SharedLibraryTest.isSharedResourceDecodingAndRebuildingWorking(SharedLibraryTest.java:86)

        Caused by:
        java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
            at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1728)
            at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1261)
            at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1212)
            at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1667)
            at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1445)
            at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1407)
            at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
            at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
            at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
            at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
            at brut.androlib.res.Framework.installFramework(Framework.java:57)
            ... 2 more
```

**Comment by iBotPeaches** [comment]
Looks like JDK 11 & 17 failed

**Comment by iBotPeaches** [comment]
This is escaping me. I've got no idea at present. I've:

 * cleared ALL action caches
 * never replicated on my own mac/linux with SDK 8, 11 and 17
 * researched latest upgrade of: https://github.com/gradle/gradle-build-action/releases/tag/v2.6.1
 * researched latest upgrade of: https://github.com/gradle/gradle/releases/tag/v8.2.1
 * looked at recent container updates for actions: https://github.com/actions/runner-images/pulls?q=is%3Apr+is%3Aclosed
 * looked at recent jdk upgrades: https://www.oracle.com/java/technologies/javase/17all-relnotes.html
 
 Nothing is adding up

**Comment by evowizz** [comment]
I was able to reproduce the issue locally. It is indeed caused by JDK 17.0.8.

The following is mentioned [in the changelog](https://www.oracle.com/java/technologies/javase/17all-relnotes.html#JDK-8302483):
>Improved ZIP64 Extra Field Validation (JDK-8302483 (not public))
>
>java.util.zip.ZipFile has been updated to provide additional validation of ZIP64 extra fields when opening a ZIP file. This validation may be disabled by setting the system property jdk.util.zip.disableZip64ExtraFieldValidation to true.

The tests passed after using the system property within the test block in [build.gradle](https://github.com/iBotPeaches/Apktool/blob/3fdc06a46f56d674864f6e425b778f5dfb86f1f7/build.gradle#L144-L148):
```gradle
    test {
        systemProperty 'jdk.util.zip.disableZip64ExtraFieldValidation', 'true'

        testLogging {
            exceptionFormat = 'full'
        }
    }
```

Not sure what would be the next step from there. But I hope this helps!

**Comment by iBotPeaches** [comment]
thanks @evowizz - that is indeed it. Thanks for your tip/help

**Comment by jpstotz** [comment]
Just a note: calling `System.setProperty("jdk.util.zip.disableZip64ExtraFieldValidation", "true");` is useless, even if you call it in a `static { }` block in the main class:

The Java developers were so "intelligent" to check this property at load-time of `java.util.zip.ZipFile` and copy it's value into a private static field:

```
    private static final boolean disableZip64ExtraFieldValidation =
            GetBooleanAction.privilegedGetProperty("jdk.util.zip.disableZip64ExtraFieldValidation");
```
As the Java class loaders use ZIPFile class to load the Jar files from class path, ZipFile class is loaded long before any user created class respectively the main class is loaded. Therefore I don't see a way how a call to `System.setProperty("jdk.util.zip.disableZip64ExtraFieldValidation", "true");` will ever have any effect in a Java program. From my perspective the only way to set this property is from "outside", thus on the java command-line.

**Comment by iBotPeaches** [comment]
thanks @jpstotz. Here is the commit I tracked down when I was researching this. https://github.com/openjdk/jdk/commit/fff7e1ad00be07810bf948b8a6f94e83c435fa1f

**Comment by amir169** [comment]
> I was able to reproduce the issue locally. It is indeed caused by JDK 17.0.8.
> 
> The following is mentioned [in the changelog](https://www.oracle.com/java/technologies/javase/17all-relnotes.html#JDK-8302483):
> 
> > Improved ZIP64 Extra Field Validation (JDK-8302483 (not public))
> > java.util.zip.ZipFile has been updated to provide additional validation of ZIP64 extra fields when opening a ZIP file. This validation may be disabled by setting the system property jdk.util.zip.disableZip64ExtraFieldValidation to true.
> 
> The tests passed after using the system property within the test block in [build.gradle](https://github.com/iBotPeaches/Apktool/blob/3fdc06a46f56d674864f6e425b778f5dfb86f1f7/build.gradle#L144-L148):
> 
> ```groovy-gradle
>     test {
>         systemProperty 'jdk.util.zip.disableZip64ExtraFieldValidation', 'true'
> 
>         testLogging {
>             exceptionFormat = 'full'
>         }
>     }
> ```
> 
> Not sure what would be the next step from there. But I hope this helps!

I'm having the same problem in another project. My question is if it should be the way to solve the problem. I mean did they add an extra validation in new JDK for us to disable?

**Comment by jeromew** [comment]
> 
> This affects all users who directly execute aktool from command-line. For exemple if you execute apktool 2.8.1 on [library.apk](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/test/resources/aapt1/shared_libraries/library.apk)
> 
> ```
> java -jar apktool_2.8.1.jar d library.apk
> ```
> 
> You will still run into `ZipException: Invalid CEN header (invalid zip64 extra data field size)`. I would really like to know which OpenJDK developer is responsible for this nonsense...

I am not familiar with java but I thought it could be interesting for people hitting this issue on the command line to know that the following workaround works

`JAVA_TOOL_OPTIONS="-Djdk.util.zip.disableZip64ExtraFieldValidation=true" java -jar apktool_2.9.0.jar d  library.apk`
