### ISSUE TITLE
[BUG] Regression: Apktool tries to load unexpected framework packages

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#3181]
A new issue with 2.8.0 and 2.8.1-SNAPSHOT, whenever decompiling an APK, it now calls "getPackage" (and then "loadFrameworkPkg") on arbitrary IDs instead of just loading the framework packages the APK depends on.
Don't have much information about this, still investigating myself where those IDs are coming from, but here's a piece of logging I added to both 2.8.1-SNAPSHOT and 2.7.1-SNAPSHOT for an obvious demo:

(same APK, left is 2.8.1-SNAPSHOT, right is 2.7.1-SNAPSHOT)
![Apktool_2 8 0](https://github.com/iBotPeaches/Apktool/assets/8811086/d6181b2f-ed7d-4afa-a4bc-0a8f51aacab5)

**Comment by iBotPeaches** [comment]
cc @sv99 - might be related to recent refactors you did.

**Comment by IgorEisberg** [comment]
One important point to mention, those unexpected getPackage/loadFrameworkPkg calls are happening between multiple stages while there are none of those calls in 2.7.1. If the output is saved to a file, it's a whopping 1.35MB of junk:
[Apktool_2.8.1-SNAPSHOT.txt](https://github.com/iBotPeaches/Apktool/files/12111730/Apktool_2.8.1-SNAPSHOT.txt)
