### ISSUE TITLE
[BUG] 2.8.0 new bug,  2.7.0 is ok

### ISSUE THREAD

**Issue by shuajinanhai** [iBotPeaches/Apktool#3184]
### Information
1. **Apktool Version (`apktool -version`)** -2.8.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Playstore
4. **Java Version (`java --version`)** -jdk1.8.0_152

>I: Using Apktool 2.8.0
>Exception in thread "main" while parsing a block mapping
> in 'reader', line 2, column 1:
>    apkFileName: project.apk
>    ^
>expected <block end>, but found '-'
> in 'reader', line 3, column 1:
>    - resources.arsc
>    ^
>	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:665)
>	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:171)
>	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
>	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
>	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
>	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
>	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
>	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:190)
>	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
>	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
>	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
>	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
>	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:116)
>	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
>	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:155)
>	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
>	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470)
>	at brut.androlib.apk.ApkInfo.load(ApkInfo.java:164)
>	at brut.androlib.apk.ApkInfo.load(ApkInfo.java:172)
>	at brut.androlib.ApkBuilder.build(ApkBuilder.java:82)
>	at brut.apktool.Main.cmdBuild(Main.java:261)
>	at brut.apktool.Main.main(Main.java:90)

2.8.0 apktool.yml：
!!brut.androlib.apk.ApkInfo
apkFileName: project.apk
- resources.arsc
- assets/features_config.json
isFrameworkApk: false
mApkFileName: 警察大战僵尸.apk
mSdkInfo:
  minSdkVersion: '23'
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
resourcesAreCompressed: false
sharedLibrary: false
sparseResources: true

2.7.0 apktool.yml：
!!brut.androlib.meta.MetaInfo
apkFileName: project.apk
compressionType: false
doNotCompress:
- resources.arsc
- assets/features_config.json
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '22'
  targetSdkVersion: '33'
sharedLibrary: false
sparseResources: false

**Comment by iBotPeaches** [comment]
Yep unfortunately a regression occurred in 2.8.0. 2.8.1 will quickly follow, but this was detected already and being fixed in: https://github.com/iBotPeaches/Apktool/issues/3169
