### ISSUE TITLE
[BUG] smali_classes3/ae/w2.smali[652,4] Invalid register: v28. Must be between v0 and v15, inclusive.

### ISSUE THREAD

**Issue by iiasceri** [iBotPeaches/Apktool#3186]
Method decompiled by 2.8.0:
```smali
.method protected e2()V
    .locals 28

I just added this inside e2():
    invoke-virtual {p0, v8}, Lae/w2;->filter(Ljava/util/List;)Ljava/util/List;
    move-result-object v8
```
Why the apktool d -b .apk is allowed to use .locals 28
But if I want to use .locals 28 I can't ?

As soon as I remove this, it works:

```smali
    invoke-virtual {p0, v8}, Lae/w2;->filter(Ljava/util/List;)Ljava/util/List;
    move-result-object v8
```

**Comment by iBotPeaches** [comment]
Sorry this looks like you are on a journey of learning smali. I don't see a bug here nor enough details to work from.

The smali tag on StackOverflow https://stackoverflow.com/questions/tagged/smali is really good for these type of questions. You can't really copy in a line that is using parameter registers that I'm guessing are already in use. It causes that shift you have and probably errors.
