### ISSUE TITLE
[BUG]Windows 11 Support

### ISSUE THREAD

**Issue by RISHII-R-M** [iBotPeaches/Apktool#3231]
The Latest version is not supported in windows 11 but the older version 2.6.0 works fine it just says it did not find the jar file .

**Comment by iBotPeaches** [comment]
I believe that has be user error. It indeed works on Windows 11.

I don't see any details to go on any further.

**Comment by AndnixSH** [comment]
> I believe that has to be user error. It indeed works on Windows 11.

Can confirm that it works on Windows 11 for me too
