### ISSUE TITLE
[BUG] Non-latin (Cyrillic) characters in User folder name cause error reading framework APK

### ISSUE THREAD

**Issue by barnabwhy** [iBotPeaches/Apktool#3250]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - 1.8.0_341

### Stacktrace/Logcat

```
W: ziparchive W 08-02 16:29:59  9440  4480] Unable to open 'C:\Users\╤ыртр\AppData\Local\apktool\framework\1.apk': Illegal byte sequence
W: zipro W 08-02 16:29:59  9440  4480] Error opening archive C:\Users\╤ыртр\AppData\Local\apktool\framework\1.apk: I/O error
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes
2. If you are trying to install a modified apk, did you resign it?
N/A
3. Are you using the latest apktool version?
Yes

Additional info:
User account name is `Слава`, path gets malformed to show incorrectly where there were Cyrillic characters.
This is probably an issue reading some unicode string with incorrect encoding.

**Comment by iBotPeaches** [comment]
> This is probably an issue reading some unicode string with incorrect encoding.

Maybe? Could be a misconfiguration on host machine. Some report some flags they can pass to Java and it all works out. 

At the moment though I'm not really focusing Windows issues. Myself not having an active development machine - its not worth my time to blindly attempt fixes at these. I only make matters worse and lead to more submitted issues.

I've got a long standing issue for basically Windows support with characters it can't natively support, so I'll loop this in with it: https://github.com/iBotPeaches/Apktool/issues/1460

Open for any support if anyone wants to take a stab at a PR.
