### ISSUE TITLE
[BUG] CI Build is not uploaded

### ISSUE THREAD

**Issue by MicroCBer** [iBotPeaches/Apktool#3282]
https://github.com/iBotPeaches/Apktool/actions/runs/5890372773#:~:text=1%20warning-,Build%20apktool.jar,cli/build/libs/apktool%2D*%2Dsmall.jar.%20No%20artifacts%20will%20be%20uploaded.,-Build/Test%20(JDK

[Build apktool.jar](https://github.com/iBotPeaches/Apktool/actions/runs/5890372773/job/15975593292#step:5:13)
No files were found with the provided path: brut.apktool/apktool-cli/build/libs/apktool-*-small.jar. No artifacts will be uploaded.

**Comment by iBotPeaches** [comment]
Thanks. Guess a regression during kotlin rewrite.

**Comment by MicroCBer** [comment]
Yep, it still work before #3249

**Comment by iBotPeaches** [comment]
Guess I didn't fix it. Re-opening.

```
No files were found with the provided path: brut.apktool/apktool-cli/build/libs/apktool-*-SNAPSHOT.jar. No artifacts will be uploaded.
```

**Comment by iBotPeaches** [comment]
3rd times a charm. Sorry about that.
