### ISSUE TITLE
[BUG]Failed to Compile due to incorrect decompilation

### ISSUE THREAD

**Issue by dbzdivik** [iBotPeaches/Apktool#3303]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - 11
3. **APK From? (Playstore, ROM, Other)** - Playstore
4. **Java Version (`java --version`)** - 20.0.2

### Stacktrace/Logcat
PFA error snapshot, due to which compiling is failing
![image](https://github.com/iBotPeaches/Apktool/assets/7036189/a03ff2e4-8230-473f-ba2a-cc95fe045d6a)

Include stacktrace here
`I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\animator\2130837504.xml:4: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\animator\2130837504.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\animator\2130837522.xml:4: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\animator\2130837522.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\color\2131100252.xml:5: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\color\2131100252.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\color\2131100253.xml:5: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\color\2131100253.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\font\2131296278.xml:2: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\font\2131296278.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\font\2131296280.xml:2: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\font\2131296280.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-land\2131625592.xml:2: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-land\2131625592.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-land\2131625599.xml:4: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-land\2131625599.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-ldrtl\2131625596.xml:2: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-ldrtl\2131625596.xml: error: file failed to compile.
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-v26\2131623959.xml:6: error: not well-formed (invalid token).
W: C:\Users\coold\AppData\Local\Temp\apk-mitm-ce02e7b45e71b833241d46a7a22d803e\decode\res\layout-v26\2131623959.xml: error: file failed to compile.
`

### Steps to Reproduce
1. `apktool `
2. apktool d test.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) none

### APK
If this APK can be freely shared, please upload/attach a link to it. nope

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
3. If you are trying to install a modified apk, did you resign it? no
4. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Yeah this happens when we can't decode an attribute - end up treating it as the numeric literal which is an invalid resource.

Unsure at moment if this is because we failed disassembly and finding that resource or if we need to support fake/unknown resources or just strip it.

Either way - this is known/documented in an existing issue here - https://github.com/iBotPeaches/Apktool/issues/3183#issuecomment-1644070864

Thanks for report.
