### ISSUE TITLE
[BUG] Android Beta m5-rc14 Home can´t be decompiled. (Yes, i know, that this an very, very old Android version, but maybe it can be fixed)

### ISSUE THREAD

**Issue by user0-tb** [iBotPeaches/Apktool#3311]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM
4. **Java Version (`java --version`)** - `java version "1.8.0_381"` `Java(TM) SE Runtime Environment (build 1.8.0_381-b09)` `Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)`
5. If you don´t know what Android Beta m5-rc14 is, [here](https://developer.android.com/sdk/older_releases?hl=en#version-m5-rc14) is the SDK with the Emulator, and [here](https://betawiki.net/wiki/Android_m5-rc14) is the BetaWiki.

### Stacktrace/Logcat

```
I: Using Apktool 2.8.1 on Home.apk
I: Loading resource table...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:351)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:318)
        at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:99)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:176)
        at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:126)
        at brut.androlib.res.ResourcesDecoder.getResTable(ResourcesDecoder.java:88)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:106)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:190)
        at brut.apktool.Main.main(Main.java:93)
```

### Steps to Reproduce
1. `apktool d Home.apk `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[Android Beta m3 framework-res.apk(doesn't changed anything to M5)](https://github.com/user0-tb/ApktoolDebug/raw/main/framework-res.apk)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[Home.apk](https://github.com/user0-tb/ApktoolDebug/raw/main/Home.apk)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - No, because it can´t decompile
2. If you are trying to install a modified apk, did you resign it? - I don´t can install it, because i can´t decompile it.
3. Are you using the latest apktool version? - Yes

**Comment by iBotPeaches** [comment]
Yeah doesn't work on latest. I'll take a look when I'm back in the zone of disassembly errors and take another look.

**Comment by user0-tb** [comment]
Thanks

**Comment by user0-tb** [comment]
The same with all Apks from Android Beta m5-rc-14. All available at [https://github.com/user0-tb/ApktoolDebug](https://github.com/user0-tb/ApktoolDebug)

**Comment by user0-tb** [comment]
Is it fixable?

**Comment by iBotPeaches** [comment]
Sorry I don't tend to like mixing working on issues recently. I've found it more helpful for me to stay focused on an a single issue on the way towards resolution. Once I'm complete with my latest ticket (#2836) - I'll revisit open tickets.

So I don't have an answer yet.

**Comment by user0-tb** [comment]
If you need any Files or Source Code, ask me.

**Comment by iBotPeaches** [comment]
I took a look - this is because we either regressed or the packing order of chunks was different back then.

```
F: Chunk #1 start: type=0x0002 chunkSize=0x0002c8fc
F: Chunk #2 start: type=0x0001 chunkSize=0x00010f84
F: Chunk #3 start: type=0x0200 chunkSize=0x0001b96c
F: Chunk #4 start: type=0x0201 chunkSize=0x00003b80
```

What I tend to normally expect

```
F: Chunk #1 start: type=0x0002 chunkSize=0x0010ca40
F: Chunk #2 start: type=0x0001 chunkSize=0x0007132c
F: Chunk #3 start: type=0x0200 chunkSize=0x0009b708
F: Chunk #4 start: type=0x0202 chunkSize=0x00000060
```

We are basically reading types without specs so lots of NPEs on that path. Probably fixable if we change up our type loading to be more deferred.

**Comment by iBotPeaches** [comment]
This looks to be a never ending journey of patches. I'm going to toss in backlog @user0-tb.

If you have source of the framework-res or ResourceTypes.h - I can revisit.

**Comment by user0-tb** [comment]
Here @iBotPeaches 
Framework-res: 
[framework-res_src.zip](https://github.com/iBotPeaches/Apktool/files/12569480/framework-res_src.zip)

**Comment by iBotPeaches** [comment]
@user0-tb - This doesn't look like the source of the application, just the source (java) portion.

**Comment by iBotPeaches** [comment]
I've decided after peeking a bit more - that there is real no chance of this older M builds working on compilation. The build tools of this era will generate a resource table that Milestone builds from '08 have zero chance of understanding.

So I'll merge a PR that at least fixes disassembly, but not going to have any chance of compilation. This seems like a happy medium for how old this is.

Ticket will close on merge of PR.

**Comment by user0-tb** [comment]
It´s working now! **_Thanks @iBotPeaches!_**
