### ISSUE TITLE
Apktool error, apktool does not recompile apk after decompiling

### ISSUE THREAD

**Issue by nketandesmond** [iBotPeaches/Apktool#3315]
Pls I can't recompile my apk but decompiling works fine. Only when it recompiles successfully is when I decompile it into raw format example:

apktool d -f -r test.apk (it recompiles successfully after this but, I cannot edit the androidmanifest.xml) 

When I use the following commands to decompile the apk it doesn't recompile after 
apktool d -f test.apk / apktool d test.apk

And I have tried just the simple decompile and recompile method to test is the apktool is working it still doesn't recompile unless it's decompiled into a raw format

Here's my error below 

```
apktool b /root/Ping    
I: Using Apktool 2.8.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Ping/res/layout/activity_main.xml:6: error: Error: Integer value out of range (at 'completionThreshold' with value '0').
W: 
W: /root/Ping/res/layout-v21/activity_main.xml:6: error: Error: Integer value out of range (at 'completionThreshold' with value '0').
W: 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_15687235703492694019837964072873730365.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 33, --version-code, 22, --version-name, 1.6.4, --no-version-vectors, -F, /tmp/APKTOOL14474031873088584453.tmp, -e, /tmp/APKTOOL12752392562691395923.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Ping/res, -M, /root/Ping/AndroidManifest.xml]
```

Pls I really need your help 😭😭😭

**Comment by iBotPeaches** [comment]
Apktool (short of a bug) would disassemble the values as they were. More recent build tools may be stricter during compilation.

You can see the error in the above stacktrace.

> Error: Integer value out of range (at 'completionThreshold' with value '0').

Since I don't see an application to triage - I hope that helps. You could dig into viable values for that property.
