### ISSUE TITLE
how to solve this bug plz suggest me compile error

### ISSUE THREAD

**Issue by tejasnikumbh1432** [iBotPeaches/Apktool#3323]
I: Using Apktool M 2.4.0-230829
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes10 folder into classes10.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes11 folder into classes11.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Using aapt2
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-h640dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-h640dp/layouts.xml: error: file failed to compile.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-land/layouts.xml: error: file failed to compile.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-sw600dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-sw600dp/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-sw600dp/layouts.xml: error: file failed to compile.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-v26/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values-v26/layouts.xml: error: file failed to compile.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:8: error: invalid value for type 'layout'. Expected a reference.
W: /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res/values/layouts.xml:9: error: invalid value for type 'layout'. Expected a reference.
W: a.a.b: a.b.a: could not exec (exit code = 1): [/data/user/0/ru.maximoff.apktool/files/bin/aapt2, compile, --dir, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res, --legacy, -o, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/build/resources.zip]
W: a.a.b: a.b.a: could not exec (exit code = 1): [/data/user/0/ru.maximoff.apktool/files/bin/aapt2, compile, --dir, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res, --legacy, -o, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/build/resources.zip]
W: a.a.a.a(Androlib.java:667)
W: a.a.a.a(Androlib.java:552)
W: a.a.a.d(Androlib.java:404)
W: a.a.a.a(Androlib.java:368)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:58)
W: ru.maximoff.apktool.c.a.a(AbstractTask.java:100)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:123)
W: ru.maximoff.apktool.c.a.doInBackground(Unknown Source:2)
W: android.os.AsyncTask$2.call(AsyncTask.java:333)
W: java.util.concurrent.FutureTask.run(FutureTask.java:266)
W: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W: java.lang.Thread.run(Thread.java:764)
W: a.b.a: could not exec (exit code = 1): [/data/user/0/ru.maximoff.apktool/files/bin/aapt2, compile, --dir, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res, --legacy, -o, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/build/resources.zip]
W: a.a.c.a.b(AndrolibResources.java:629)
W: a.a.c.a.a(AndrolibResources.java:767)
W: a.a.a.a(Androlib.java:645)
W: a.a.a.a(Androlib.java:552)
W: a.a.a.d(Androlib.java:404)
W: a.a.a.a(Androlib.java:368)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:58)
W: ru.maximoff.apktool.c.a.a(AbstractTask.java:100)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:123)
W: ru.maximoff.apktool.c.a.doInBackground(Unknown Source:2)
W: android.os.AsyncTask$2.call(AsyncTask.java:333)
W: java.util.concurrent.FutureTask.run(FutureTask.java:266)
W: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W: java.lang.Thread.run(Thread.java:764)
W: could not exec (exit code = 1): [/data/user/0/ru.maximoff.apktool/files/bin/aapt2, compile, --dir, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/res, --legacy, -o, /storage/emulated/0/Download/com.instagram.android_299.0.0.34.111-369911275_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com_mod_src/build/resources.zip]
W: a.d.f.a(OS.java:177)
W: a.a.c.a.b(AndrolibResources.java:625)
W: a.a.c.a.a(AndrolibResources.java:767)
W: a.a.a.a(Androlib.java:645)
W: a.a.a.a(Androlib.java:552)
W: a.a.a.d(Androlib.java:404)
W: a.a.a.a(Androlib.java:368)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:58)
W: ru.maximoff.apktool.c.a.a(AbstractTask.java:100)
W: ru.maximoff.apktool.c.d.a(BuildTask.java:123)
W: ru.maximoff.apktool.c.a.doInBackground(Unknown Source:2)
W: android.os.AsyncTask$2.call(AsyncTask.java:333)
W: java.util.concurrent.FutureTask.run(FutureTask.java:266)
W: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W: java.lang.Thread.run(Thread.java:764)
I: Time spent: 00:15:46.957

**Comment by iBotPeaches** [comment]
Apologies, but this doesn't look to be an official build and appears to be running on Android.

I can only review official builds - I'm afraid you'll have to look for support with whomever produced this.

Thanks for understanding.
