### ISSUE TITLE
[BUG] Decompile (decoding file-resources) freeze

### ISSUE THREAD

**Issue by SardanDev** [iBotPeaches/Apktool#3328]
### Information
1. **Apktool Version (`apktool -version`)** - v1.2
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Play Store
4. **Java Version (`java --version`)** - Idk

### Stacktrace/Logcat

```
[01:27:28] Decompiling com.snapchat.android_v12.49.0.67-102302_Android-5.0.apk...
[01:27:28] Using Apktool 2.7.0 on com.snapchat.android_v12.49.0.67-102302_Android-5.0.apk  
[01:27:28] Loading resource table...  
[01:27:34] Decoding AndroidManifest.xml with resources...  
[01:27:34] Loading resource table from file: C:\Users\legue\AppData\Local\apktool\framework\1.apk  
[01:27:39] Regular manifest package...  
[01:27:40] Decoding file-resources...  

```

### Steps to Reproduce
1. `apktool decompile`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
I don't recognize the tool in play, since Apktool's output doesn't look like that.

Additionally, 2.7.0 is pretty old when 2.8.1 is the latest.

So going to close.

**Comment by SardanDev** [comment]
> I don't recognize the tool in play, since Apktool's output doesn't look like that.
> 
> Additionally, 2.7.0 is pretty old when 2.8.1 is the latest.
> 
> So going to close.

Hi, i updated the apktool file but still freeze at the Decoding file-resources...

**Comment by iBotPeaches** [comment]
> Hi, i updated the apktool file but still freeze at the Decoding file-resources...

Try with verbose mode and see what you see.

**Comment by SardanDev** [comment]
> > Hi, i updated the apktool file but still freeze at the Decoding file-resources...
> 
> Try with verbose mode and see what you see.

I just reinstall apktool and that works. Thanks for the help
