### ISSUE TITLE
Decoding process exited with code 1

### ISSUE THREAD

**Issue by purplebyteone** [iBotPeaches/Apktool#3340]
### Information
1.APK tool VSCode extension
2. Parrot
3. Android apk file
4. openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb11u1, mixed mode, sharing)

Issue:

### Steps to Reproduce
1. codium
2. Ctrl+Shift+P
3. APKLab> Open an APK
4. Select .apk file
5. select "decompile_java"
6. Ok
![image](https://github.com/iBotPeaches/Apktool/assets/17739404/1e789782-ea9d-43ee-8081-bef89049c8c1)

### APK
If this APK can be freely shared, please upload/attach a link to it.
It's an HTB retired task

### Questions to ask before submission
1. NA
8. NA
9. NA

**Comment by auermich93** [comment]
In the screen above the `java -jar` command is missing the path to the `apktool.jar` file.

**Comment by iBotPeaches** [comment]
As mentioned above. This looks like an issue with the tool you are using that wraps apktool.

Closing.
