### ISSUE TITLE
UI is getting distorted after wrapping with apkTool in the apk with material theme applied on OS 12 and above

### ISSUE THREAD

**Issue by swetasamasti2310** [iBotPeaches/Apktool#3341]
Our customer has the apk with latest material theme applied. We are wrapping the apk with apkTool. In the wrapped apk, we observed that on launching the app, some unexpected access bar appears with some random icon and name in the launched activity.
In the wrapped apk, values-31 folder is there. The issue is observed on OS 12 and above. We tried with the latest apkTool version also, the issue persists.
When we delete values-31 folder while wrapping the apk, the app launches correctly without any UI distortion.
Can you please check if there is any issue in apkTool library for the latest material theme.

**Comment by iBotPeaches** [comment]
I don't believe there is any issue I'm aware of with that specific setup. As you might imagine though, very difficult and time consuming to investigate something when the issue template is removed.

I don't see any possibility researching this further, so closing.
