### ISSUE TITLE
I have issue to Google Login and Firebase Apps[BUG]

### ISSUE THREAD

**Issue by iTMaster228** [iBotPeaches/Apktool#3344]
### Information
1. **Apktool Version (`apktool -Latest`)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -
4. **Java Version (`java --version`)** -

I am having issue whenever i work on Firebase app or Login as Google type app after compiling. App does not work to login and firebase also stop working.

**Comment by iBotPeaches** [comment]
This is common as normally those methods have the application signing hash lodged within Firebase. That'll change unless you mimic signature.
