### ISSUE TITLE
built failed

### ISSUE THREAD

**Issue by Memory2314** [iBotPeaches/Apktool#3365]
Decompressed resources cannot be repackaged.
apktool version：2.8.1
operating environment：termux
Reproduction step
```
apktool d xxxx.apk
apktool b xxxx.apk
```
Error reporting information
```
I: Using Apktool 2.8.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_15968071904134654037497863256231218003.tmp, p, --forced-package-id, 127, --min-sdk-version, 31, --target-sdk-version, 31, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL484604293215624233.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL13218277324724027550.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/home/miui_monet_icon_script/demo/res, -M, /data/data/com.termux/files/home/miui_monet_icon_script/demo/AndroidManifest.xml]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_15968071904134654037497863256231218003.tmp[1]: ELF: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_15968071904134654037497863256231218003.tmp[19]: syntax error: unexpected '('
```
apk link [https://i-510.lanzouc.com:446/10041700140631375bb/2023/10/04/a6d2a3d1c675177031d22a819e312f96.apk?st=bw1mkrIknQoD_1txAkgZsA&e=1696413790&b=AjQAZQhlAmhWLVdgUnIFag_c_c&fi=140631375&pid=120-231-42-250&up=2&mp=1&co=0](https://i-510.lanzouc.com:446/10041700140631375bb/2023/10/04/a6d2a3d1c675177031d22a819e312f96.apk?st=bw1mkrIknQoD_1txAkgZsA&e=1696413790&b=AjQAZQhlAmhWLVdgUnIFag_c_c&fi=140631375&pid=120-231-42-250&up=2&mp=1&co=0)

Even if I haven't moved anything, I can't built it.
This problem has existed for a long time.

**Comment by iBotPeaches** [comment]
It looks like running this on Android, which isn't supported officially. We don't have the native architectures for aapt/aapt2 for Android usage.
