### ISSUE TITLE
Issue Report version 

### ISSUE THREAD

**Issue by IbrahemHossam** [iBotPeaches/Apktool#3382]
i keep getting weird I lines like the picture 2.6.1
even though i tried another versions
tried to reinstall java
did everything i could think of
can any one please help
![image](https://github.com/iBotPeaches/Apktool/assets/87953880/9080d051-b128-4a68-8813-ad6a1c0643d8)

**Comment by iBotPeaches** [comment]
We haven't had that type of output in years. I'd recommend you upgrade to latest Apktool and try again.

This is also the bug tracker, not support. So closing this.
