### ISSUE TITLE
[BUG] decompiling into -o path with # symbol breakes AndroidManifest fixer

### ISSUE THREAD

**Issue by aatv** [iBotPeaches/Apktool#3390]
### Information
1. **Apktool Version (`apktool -version`)** -2.9.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -Other
4. **Java Version (`java --version`)** - OpenJDK Runtime Environment (build 11.0.20)

### Steps to Reproduce
Use any test.apk that requires automatic AndroidManifest.xml fixing while decompiling 
In this example I am using test.apk with empty package name=""
and try to decompile it using -o values with "#" and without "#"
You will have different results:
for -o without "#" apktool will put fixed androidmanifest inside folder
for -o with "#" apktool will put fixed androidmanifest outside of the target folder 
into file named like folder name until # symbol and without any extension, see this example:

> ls -l
total 3724
-rw-r--r-- 1 u u 3813025 2023-10-10 04:07 test.apk

> apktool.jar d test.apk -o test1-a
I: Using Apktool 2.9.0 on test.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/u/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=, name=package, value=0x0000014f
W: Could not decode attr value, using undecoded value instead: ns=, name=package, value=0x0000014f
W: Could not decode attr value, using undecoded value instead: ns=, name=platformBuildVersionCode, value=0x00000021
W: Could not decode attr value, using undecoded value instead: ns=, name=platformBuildVersionName, value=0x0000000d
I: Renamed manifest package found! Replacing  with com.test
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

> ls -l
total 3728
-rw-r--r-- 1 u u 3813025 2023-10-10 04:07 test.apk
drwxr-xr-x 8 u u    4096 2023-10-10 04:13 test1-a

(correct result - test1-a folder with fixed AndroidManifest.xml inside)

> apktool.jar d test.apk -o test2#b
I: Using Apktool 2.9.0 on test.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/u/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=, name=package, value=0x0000014f
W: Could not decode attr value, using undecoded value instead: ns=, name=package, value=0x0000014f
W: Could not decode attr value, using undecoded value instead: ns=, name=platformBuildVersionCode, value=0x00000021
W: Could not decode attr value, using undecoded value instead: ns=, name=platformBuildVersionName, value=0x0000000d
I: Renamed manifest package found! Replacing  with com.test
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

> ls -l
total 3764
-rw-r--r-- 1 u u 3813025 2023-10-10 04:07 test.apk
drwxr-xr-x 8 u u    4096 2023-10-10 04:13 test1-a
drwxr-xr-x 8 u u    4096 2023-10-10 04:14 test2#b
-rw-r--r-- 1 u u   28841 2023-10-10 04:14 test2

(incorrect result - test2#b folder with unfixed AndroidManifest.xml inside with fixed AndroidManifest.xml file outside of the folder in file name test2)

**Comment by iBotPeaches** [comment]
I can't seem to replicate.

```
➜ 3390 apktool d 3390.apk -o test2#b
I: Using Apktool 2.9.0 on 3390.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Renamed manifest package found! Replacing foo.bar with com.ibotpeaches.arsctest
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  3390 apktool d 3390.apk -o "string#with#signs"
I: Using Apktool 2.9.0 on 3390.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Renamed manifest package found! Replacing foo.bar with com.ibotpeaches.arsctest
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  3390 ls -ls
total 60
52 -rw-r--r-- 1 ibotpeaches ibotpeaches 49395 Jul 16 19:31 3390.apk
 4 drwxr-xr-x 5 ibotpeaches ibotpeaches  4096 Oct 10 06:11 string#with#signs
 4 drwxr-xr-x 5 ibotpeaches ibotpeaches  4096 Oct 10 06:10 test2#b
➜  3390 
```

Thankfully it looks like if you are still affected you can just avoid that symbol.
