### ISSUE TITLE
[BUG] Non-latin filenames cannot be packaged as APK

### ISSUE THREAD

**Issue by zhongqingsong** [iBotPeaches/Apktool#3391]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - jdk17

### Stacktrace/Logcat

```
>I: Using Apktool 2.9.0
>I: Smaling smali folder into classes.dex...
>I: Smaling smali_classes2 folder into classes2.dex...
>I: Building resources...
>W: F:\gp\NewKiller\projects\鐤媯闉瓙澶т綔鎴榎Project\res: error: failed to open directory: 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆? (2).
>brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_49079672213223373052427138622113176401.tmp, compile, --dir, F:\gp\NewKiller\projects\疯狂鞭子大作战\Project\res, --legacy, -o, F:\gp\NewKiller\projects\疯狂鞭子大作战\Project\build\resources.zip]
```

### Steps to Reproduce
1. `apktool `
Using the same apk file, let's say the name is: 大作战.apk, will not be able to build as apk. The preceding error is displayed.

2、If change same file's name to ABC.apk, everything works. 

### APK
Any apk file to take a Chinese name, you can Reproduce. Chinese name example：疯狂摩托_小.apk、疯狂鞭子大作战.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
This works fine on Linux, so I'm tempted to say this is just a misconfiguration of your Windows environment.

```
➜  3391 apktool d 疯狂鞭子大作战.apk 
I: Using Apktool 2.9.0 on 疯狂鞭子大作战.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  3391 apktool b 疯狂鞭子大作战
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 疯狂鞭子大作战/dist/疯狂鞭子大作战.apk
➜  3391 
```

Alternatively, it may be this existing issue - https://github.com/iBotPeaches/Apktool/issues/1460

Thankfully as you spotted. You can easily workaround this issue in the meantime whether its a misconfiguration on your side or a bug specific to Windows.

Closing anyway since we have #1460 or its a misconfiguration.

**Comment by zhongqingsong** [comment]
@iBotPeaches By the way, I know why. Doesn't seem to be the reason you gave.
The reason for all this is because of **aapt2**. Apktool now uses aapt2 by default, but aap2 is stricter about verifying resource paths, resulting in non-ASCII symbols being treated as exceptions. 
There are only three solutions:
1. Small amount or single application: aapt2 is recommended. **Change apk to English name**, and then apktool d and b. Simplicity: ⭐
2. a large number of applications, still want to use aapt: it needs to manually switch back to aapt when calling apktool. Command line: **apktool b folder --use-aapt1 {options}** . Simplicity: ⭐
3. a large number of applications, want to use aapt2: you need to **write a script**, when calling aapt2, automatically change the project name to English name. When it's over, change the project name back to the original name. Simplicity: ⭐⭐⭐
