### ISSUE TITLE
[BUG]MCC - Mobile Country Code

### ISSUE THREAD

**Issue by rashpel77** [iBotPeaches/Apktool#3398]
### Information
1. **Apktool Version (`apktool_2.9.1_20231011`)** -
2. **Operating System (Linux, Windows)** -
3. **APK From? (ROM_MIUI)** -
4. **Java Version (`openjdk 11.0.19`)** -

### Stacktrace/Logcat
```
apktool d APK/framework-res.apk -o APK/framework-res
I: Using Apktool 2.9.1-dirty on framework-res.apk
I: Loading resource table...
I: Sparsely packed resources detected.
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
apktool b APK/framework-res --api-level 34 -o framework-res.apk
I: Using Apktool 2.9.1-dirty
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: APK/framework-res/res/values-mcc9460-mnc9000/bools.xml: error: invalid configuration 'mcc9460-mnc9000'.
W: APK/framework-res/res/values-mcc9998-mnc9999/arrays.xml: error: invalid configuration 'mcc9998-mnc9999'.
W: APK/framework-res/res/values-mcc9998-mnc9999/bools.xml: error: invalid configuration 'mcc9998-mnc9999'.
W: APK/framework-res/res/values-mcc9998-mnc9999/strings.xml: error: invalid configuration 'mcc9998-mnc9999'.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_73237029991629032398824865494476568592.tmp, compile, --dir, APK/framework-res/res, --legacy, -o, APK/framework-res/build/resources.zip]
```

### Steps to Reproduce
1. `apktool_2.9.1_20231011 `
2. tried using aapt1 and aapt2, no change
3. apktool_2.8.2 no bugs!

### Frameworks
none

### APK
If this APK can be freely shared, please upload/attach a link to it.
[apk link](https://cloud.mail.ru/public/2oWN/haVm8TF7f)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
4. If you are trying to install a modified apk, did you resign it? -
5. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
I'm guessing those are invalid configurations for aapt2. Since if you try with aapt1 it works.

```
➜  3398 apktool b framework-res --use-aapt1
I: Using Apktool v2.9.0-1-d2599874-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'wfcSpnFormat' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: framework-res/dist/framework-res.apk
➜  3398 
```

In my vague memory of mcc/mnc those values go from 0 to 999. So while aapt1 probably didn't care and frequently had a unsigned short as max - aapt2 will not allow that.

Thanks for the report, but since aapt1 works - I'm considering this a stricter aapt2 build requirement and closing.

**Comment by rashpel77** [comment]
Thanks for clarifying
