### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by starbucks2010** [iBotPeaches/Apktool#3400]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM
4. **Java Version (`java --version`)** - 20.0.2

### Stacktrace/Logcat

C:\apktool>java -jar apktool-2.9.0-20231009.jar d framework-res_g988b_hwi7.apk
I: Using Apktool 2.9.0 on framework-res_g988b_hwi7.apk
I: Loading resource table...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

### Steps to Reproduce
1. Decompile the framework-res.apk and check res/values/styles.xml file for duplicated lines (lines 1236-1237, 1313-1314, 1322-1323, 1324-1325, 2505-2506, 7108-7109). It always gets duplicated the same lines.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files

Use the attached framework file.

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes, same issue
2. If you are trying to install a modified apk, did you resign it? - No apk resign
3. Are you using the latest apktool version? - Yes
[framework-res_g988b_hwi7.zip](https://github.com/iBotPeaches/Apktool/files/12900191/framework-res_g988b_hwi7.zip)

**Comment by iBotPeaches** [comment]
@starbucks2010 - Am I correct you are only reporting the duplicates? Best I can tell in my research is these are duplicate in the entry table and Apktool is simply respecting that.

**Comment by starbucks2010** [comment]
yes, only duplicates lines in styles.xml.
is there any chance to check/fix the entry table for these duplicates?

thank you

**Comment by iBotPeaches** [comment]
Not positive. I'll spend an hour and if not - close it out.

**Comment by iBotPeaches** [comment]
Okay wasn't hard to add. PR linked above - we will dedupe attribute names ignoring whatever the duplicate one is.
