### ISSUE TITLE
[BUG]这次更新后不支持中文路径了，之前是支持的

### ISSUE THREAD

**Issue by shuajinanhai** [iBotPeaches/Apktool#3402]
### Information
1. **Apktool Version (`apktool -version`)** -2.9.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Playstore
4. **Java Version (`java --version`)** -jdk1.8.0_152

之前版本是支持中文路径，这次2.9.0不支持了吗
C:\Apk\AndroidKiller\bin\apktool\apktool>java -jar C:\Apk\AndroidKiller\bin\apktool\apktool\apktool_2.9.0.jar b C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib编译不过
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib缂栬瘧涓嶈繃\res: error: failed to open directory: 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆? (2).
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\wang\AppData\Local\Temp\brut_util_Jar_65149265943151950408816846036624919247.tmp, compile, --dir, C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib编译不过\res, --legacy, -o, C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib编译不过\build\resources.zip]

C:\Apk\AndroidKiller\bin\apktool\apktool>java -jar C:\Apk\AndroidKiller\bin\apktool\apktool\apktool_2.9.0.jar b C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib\dist\build_ids_lib缂栬瘧涓嶈繃.apk

**Comment by iBotPeaches** [comment]
This looks pretty close to this - https://github.com/iBotPeaches/Apktool/issues/3391

Please take a look and let me know.

**Comment by shuajinanhai** [comment]
去掉中文名字，就正常
C:\Apk\AndroidKiller\bin\apktool\apktool>java -jar C:\Apk\AndroidKiller\bin\apktool\apktool\apktool_2.9.0.jar d C:\Users\wang\Desktop\build_ids_lib.apk
I: Using Apktool 2.9.0 on build_ids_lib.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\wang\AppData\Local\apktool\framework\1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes3.dex...
I: Baksmaling assets/audience_network.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

C:\Apk\AndroidKiller\bin\apktool\apktool>java -jar C:\Apk\AndroidKiller\bin\apktool\apktool\apktool_2.9.0.jar b C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: C:\Apk\AndroidKiller\bin\apktool\apktool\build_ids_lib\dist\build_ids_lib.apk

**Comment by iBotPeaches** [comment]
thanks for testing. This looks out of my control and a limitation at the aapt2 level, so I'm going to close like #3391
