### ISSUE TITLE
How to modify system apps?

### ISSUE THREAD

**Issue by resatkrlc** [iBotPeaches/Apktool#3405]
Not really an issue, but i wanted to ask how can we edit system apps? I can't tell this is bug since it works for whatsapp.
I have created an android 13 emulator with Android Studio, pulled framework-res.apk from /system/ and Settings13.apk

Normally installing untouched apk with adb works, but while i decompile-compile, it doesn't.

It just says " (random resource) not found in manifest"

what i have tried is using -c but no luck.

I also copied original classes.dex to untouched apk, but after that i get this message:

 " Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Fail
ed to collect certificates from -- META-INF/CE
RT.SF -- is signed using APK Signatur
e Scheme v2, but no such signature was found. Signature stripped?]"

I also had dig almost half of issues here, xda developers etc, but none of them worked. Do anybody have knowledge about this thing? Thanks

(in any case, i can give more info)

**Comment by iBotPeaches** [comment]
Apologies, but as you mentioned. This is a bug tracker and not for generic support.
