### ISSUE TITLE
[BUG] NullPointerException in serializeToResValuesXml

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#3416]
Reviving issue #2709 as I stumbled upon it with an updated app I was trying to decompile.
The sample APK provided at the bottom of the issue is sufficient to demonstrate the issue.
Using aapt2 dump resources you can see a problematic `color` resource with an unexpected `@null` value:
```
...
    resource 0x7f0601f9 color/green_f2fdf1
      () #fff2fdf1
    resource 0x7f0601fa color/green_highlighter_feedback
      () #e9cbf2ce
    resource 0x7f0601fb color/green_light_gradient
      () #ff52cb8c
    resource 0x7f0601fc color/green_oc831f
      () @null
    resource 0x7f0601fd color/grey
      () #ffd0cecd
    resource 0x7f0601fe color/grey_121518
      () #ff121518
    resource 0x7f0601ff color/grey_535353
      () #ff9d9d9d
...
```

From debugging how Apktool categorizes the value type, it's detected as a `string` type rather than a `reference`. I have no idea how this happens to begin with, but we should at least allow this to be decompiled, even as an `<item>` with a `@null` reference (aapt2 allows to recompile that).

**Comment by iBotPeaches** [comment]
Thanks - I'll spend a bit on investigating why the type is acting odd before I just take a shortcut and patch an NPE.

**Comment by iBotPeaches** [comment]
So I peeked a few areas that I believe I need to investigate further.

https://github.com/iBotPeaches/Apktool/blob/63b19764482df5b99e7770e2c58a4c1fc547cca1/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java#L35-L40
* Controls the creation of value class and explains the oddity of string/empty/reference

https://github.com/iBotPeaches/Apktool/blob/63b19764482df5b99e7770e2c58a4c1fc547cca1/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java#L71
* Really old line that dates back to 2010 - unsure its purpose, but clearly the toggling of <item> vs the type is a buggy inference

https://github.com/iBotPeaches/Apktool/blob/63b19764482df5b99e7770e2c58a4c1fc547cca1/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java#L75-L94
* Tons of workarounds on swapping item on/off based on critiera

**Comment by iBotPeaches** [comment]
Taking a rework of the first code snippet I posted. PR is up.
