### ISSUE TITLE
[BUG] Can´t recompile Instagram apk

### ISSUE THREAD

**Issue by vojtanethio** [iBotPeaches/Apktool#3430]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Windows 11
3. **APK From? (Playstore, ROM, Other)** - APKMirror
4. **Java Version (`java --version`)** - openjdk version "17.0.7" 2023-04-18 LTS (but on different computer result was same with official latest Java)

I just used `apktool d`, `apktool b`  and this is what I´m getting:
```
PS F:\knihovny\Desktop\modovani> apktool.bat b F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522 -f -s
I: Using Apktool 2.9.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes9 folder into classes9.dex...
I: Building resources...
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-h640dp\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-h640dp\layouts.xml: error: file failed to compile.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-land\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-land\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-land\layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-land\layouts.xml: error: file failed to compile.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-sw600dp\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-sw600dp\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values-sw600dp\layouts.xml: error: file failed to compile.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:8: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:9: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:10: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:11: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:12: error: invalid value for type 'layout'. Expected a reference.
W: F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res\values\layouts.xml:13: error: invalid value for type 'layout'. Expected a reference.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\javoj\AppData\Local\Temp\brut_util_Jar_107286169584625975893219499458221152295.tmp, compile, --dir, F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\res, --legacy, -o, F:\knihovny\Desktop\modovani\com.instagram.android_292.0.0.28.110-369210522\build\resources.zip]
Press any key to continue . . .
```

My main goal previously was to modificate [AeroInsta apk](https://yonlendir.whatsaero.com/?LyQY7S57vvj=3BJWKZ3JfjJvGEyDGmDmDjVHc2hC87fw&2fVBfJ5W83bJMBfCvkVpSvt2hbVa=IF4As&lang=en) (same Instagram version) and this is what I got:
`PS F:\knihovny\Desktop\modovani> apktool.bat b F:\knihovny\Desktop\modovani\AeroInsta -f -s
I: Using Apktool 2.9.0
I: Smaling smali folder into classes.dex...
W: Unknown file type, ignoring: F:\knihovny\Desktop\modovani\AeroInsta\smali\X\desktop.ini
I: Smaling smali_classes10 folder into classes10.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes9 folder into classes9.dex...
I: Building resources...
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:3: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:4: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:5: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:6: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:7: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:8: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:9: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:10: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:11: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:12: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:13: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:14: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:15: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:16: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:17: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:18: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:19: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:20: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:21: error: unknown resource type 'hazar'.
W: F:\knihovny\Desktop\modovani\AeroInsta\res\values-ar\hazars.xml:22: error: unknown resource type 'hazar'.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\javoj\AppData\Local\Temp\brut_util_Jar_70453901770848914107982923504525608754.tmp, compile, --dir, F:\knihovny\Desktop\modovani\AeroInsta\res, --legacy, -o, F:\knihovny\Desktop\modovani\AeroInsta\build\resources.zip]
Press any key to continue . . .`

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-292-0-0-28-110-release/instagram-292-0-0-28-110-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes, that´s what I´m doing

**Comment by iBotPeaches** [comment]
Thanks for report. We are tracking this exact issue w/ Instagram in this report - https://github.com/iBotPeaches/Apktool/issues/2618

Closing for duplicate.

**Comment by vojtanethio** [comment]
Update:
It´s working as it should on v2.8.1

**Comment by pama1999** [comment]
@iBotPeaches @vojtanethio 
can confirm as well its working on v2.8.1
