### ISSUE TITLE
[BUG] Issue with attributes while decompiling, seems like its missing many attributes

### ISSUE THREAD

**Issue by HassanMirza01** [iBotPeaches/Apktool#3432]
### Information
1. **Apktool Version (`apktool -2.9.0-Snapshot`)** -
2. **Operating System (Linux)** -
3. **APK From? (ROM)** -
4. **Java Version (`17.0.5 LTS`)** -

### Stacktrace/Logcat
same corrected apk recompiled fine with both aapt1 and aapt2

This with AAPT2 option --use-aapt2, 
![image](https://github.com/iBotPeaches/Apktool/assets/26677817/f6024d7b-a57e-41e2-b9eb-1f1f9f16ac07)

this is with AAPT1 option
![image](https://github.com/iBotPeaches/Apktool/assets/26677817/0f8b590b-cf62-4f29-bf81-b669cd7acf7f)

```
Include stacktrace here
```

### Steps to Reproduce
1. just unpack apk and recompile without any edit

### Frameworks
https://drive.google.com/drive/folders/1btO62pJ95CIBwZbSu_fSX28zCzsC9Pw-?usp=sharing

### APK
https://drive.google.com/file/d/14DRWoHieuwLwNSi9DJ04RPG9P7BinxLm/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version?  Yes

**Comment by iBotPeaches** [comment]
This appears to be same issue I disclosed in this comment: https://github.com/iBotPeaches/Apktool/issues/3129#issuecomment-1752162277, which in short I believe might be resource shrinking killing an unused resource, but not removing it from all usage.

This is ignored on Android (host), but during rebuild since the source attribute is gone - it fails.

---
```
➜  3432 aapt2 d xmltree MiuiSystemUI.apk --file res/drawable/miuix_action_icon_cancel_dark.xml
N: android=http://schemas.android.com/apk/res/android (line=1)
  N: app=http://schemas.android.com/apk/res-auto (line=1)
    E: drawable (line=1)
      A: http://schemas.android.com/apk/res/android:height(0x01010155)=26.000000dp
      A: http://schemas.android.com/apk/res/android:width(0x01010159)=26.000000dp
      A: http://schemas.android.com/apk/res/android:viewportWidth(0x01010402)=26
      A: http://schemas.android.com/apk/res/android:viewportHeight(0x01010403)=26
      A: http://schemas.android.com/apk/res-auto:actionIconDisabledAlpha(0x7f04004f)=0.5
      A: http://schemas.android.com/apk/res-auto:actionIconNormalAlpha(0x7f040050)=0.8
      A: http://schemas.android.com/apk/res-auto:actionIconPressedAlpha(0x7f040051)=0.9
➜  3432 aapt2 d resources MiuiSystemUI.apk| grep 'actionIconDisabledAlpha'
➜  3432 aapt2 d resources MiuiSystemUI.apk| grep 'actionIcon'             
    resource 0x7f0a0052 id/actionIcon
```

**Comment by iBotPeaches** [comment]
Problem with Apktool though, it can't know a resource is unused till it's done parsing application. It then further would have to rewrite files. It seems that more invocation with aapt2 to dump resources prior (to detect unused) may be best path forward.

**Comment by iBotPeaches** [comment]
@HassanMirza01 - I'm not replicating, I confirm the patch is added - https://github.com/iBotPeaches/Apktool/commit/a9eacf657c7ad09a27dc8db2632822a6c68ed510

**Comment by iBotPeaches** [comment]
Sorry - as you saw above. I cannot replicate.
