### ISSUE TITLE
[BUG] Cannot read field "format" because "opcode" is null

### ISSUE THREAD

**Issue by amackpro** [iBotPeaches/Apktool#3435]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - WSL
3. **APK From? (Playstore, ROM, Other)** - Motorola Android 14 SystemUI
4. **Java Version (`java --version`)** -19.0.2

SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,4] Cannot read field "format" because "opcode" is null
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[73,4] Cannot read field "format" because "opcode" is null
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[86,4] Cannot read field "format" because "opcode" is null
Could not smali file: com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali

i havnt modded anything in SystemUIMoto , it just gives error like this
tried basic commands and advance commands both
systemui := https://drive.google.com/file/d/1mDG63tQZa0ic7_Uc-u5s-BxKKYNvgp3q/view?usp=sharing

**Comment by iBotPeaches** [comment]
Do you mind giving this a shot with smali directly? https://github.com/google/smali

I want to see if this is something we (Apktool) caused or upstream in smali.

**Comment by amackpro** [comment]
> Do you mind giving this a shot with smali directly? https://github.com/google/smali
> 
> I want to see if this is something we (Apktool) caused or upstream in smali.

i was currently trying that only but it getting failed to compile here and idk how to actually.

**Comment by amackpro** [comment]
i tried with old smali 2.2.5
that was also giving similar error 

SystemUIMoto/smali_classes2/com/motorola/plugin/core/utils/HiddenApiKt.smali[816,4] Cannot read field "format" because "opcode" is null
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,229] mismatched input 'DOWN' expecting set null
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,346] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,4] Cannot invoke "Object.hashCode()" because the return value of "org.jf.dexlib2.base.reference.BaseMethodHandleReference.getMemberReference()" is null
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,530] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_CATCHES
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[56,0] A non-abstract/non-native method must have at least 1 instruction
SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[62,4] mismatched tree node: I_LINE expecting I_FIELDS

**Comment by iBotPeaches** [comment]
Thanks for the confirmation. Since that is upstream I am going to close here. There is nothing Apktool can do until smali is patched and we upgrade.

**Comment by MarkZhongsh** [comment]
any solution? Facing this problem for a week.

**Comment by DarkSkull91** [comment]
Me too

**Comment by DarkSkull91** [comment]
> i tried with old smali 2.2.5 that was also giving similar error
> 
> SystemUIMoto/smali_classes2/com/motorola/plugin/core/utils/HiddenApiKt.smali[816,4] Cannot read field "format" because "opcode" is null SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,229] mismatched input 'DOWN' expecting set null SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,346] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,4] Cannot invoke "Object.hashCode()" because the return value of "org.jf.dexlib2.base.reference.BaseMethodHandleReference.getMemberReference()" is null SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[60,530] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_CATCHES SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[56,0] A non-abstract/non-native method must have at least 1 instruction SystemUIMoto/smali_classes2/com/motorola/systemui/metrics/handler/StatefulStatusValueHandler$StateValue.smali[62,4] mismatched tree node: I_LINE expecting I_FIELDS

How did you tried a different smali version?
