### ISSUE TITLE
apktool2.9 could open extensions file.HLEP!

### ISSUE THREAD

**Issue by lllastronaut** [iBotPeaches/Apktool#3451]
### Information
1. **Apktool Version (`apktool -version`)** -2.9
2. **Operating System (Mac, Linux, Windows)** -WIN
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -17

### Stacktrace/Logcat

```
Include stacktrace here
```
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: error: could not open extensions file C:\Users\神舟战~1\AppData\Local\Temp\APKTOOL14934632347351551842.tmp for reading.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\神舟战~1\AppData\Local\Temp\brut_util_Jar_163042542138797942355599067506965634750.tmp, link, -o, C:\Users\神舟战~1\AppData\Local\Temp\APKTOOL4669676797490746231.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 10, --version-name, 3.20, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\神舟战~1\AppData\Local\Temp\APKTOOL14934632347351551842.tmp, -0, arsc, -I, C:\Users\神舟战神fy\AppData\Local\apktool\framework\1.apk, --manifest, I:\hacker\apktool\work\AndroidManifest.xml, I:\hacker\apktool\work\build\resources.zip]

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[zt.zip](https://github.com/iBotPeaches/Apktool/files/13512289/zt.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? no
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?yes

**Comment by BensonMaZIHao** [comment]
Hello, have you found a solution?
