### ISSUE TITLE
recompiled apk file does not start any longer

### ISSUE THREAD

**Issue by DieselDriver** [iBotPeaches/Apktool#3456]
I tried apktool 2.5.0 dirty and 2.9.0.

Since I upgraded my Android Studio I have a little problem. I could decompile/recompile/sign and zip the Release 1 without problems. The file size of the original compiled version is quite similar than the recompiled version.

```
rel.    source      recompiled
1   38 MB       39 MB   ok
2   53 MB       43 MB   nok
3   54 MB       43 MB   nok
4   54 MB       43 MB   nok
```

When I try the same procedure for release 2, 3 or 4 (these were compiled with newer Android Studio), I am not able to install a decompiled/recompiled apk file. Moreover, I noticed that the filesize of the recompiled apk files is ~10 MB smaller than the original compiled file made with Android Studio.

Decompiling:

`apktool d -r Android_Studio.apk`

Recompiling:

```
apktool b -o recompiled.apk ./decompiled/
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../my.keystore ./recompiled.apk alias_name
zipalign -p -f 4 recompiled.apk recompiled_signed_zip.apk
```

I am able to install all the recompiled apk files, but release 2, 3 and 4 are ot startable. Release 1 starts in original and recompiled version.

Why is this not working any longer?

Thanks.

**Comment by qyzhaojinxi** [comment]
zipalign at first and signer apk at last

**Comment by iBotPeaches** [comment]
Sorry you are encountering this, as mentioned above - depending on the type of signature you have to zipalign prior now. However, you are using jarsigner which is quite old. So that isn't the problem.

Theres just not enough details here to work from - so apologies I'm not positive.

**Comment by DieselDriver** [comment]
Hm ok, I always ziped after signing.

But this seems not to be the problem.

I tried only unpacking and packing my apf file.
`apktool d -s compiled.apk -o whatever
apktool b whatever -o whatever_repacked.apk
`

Here I got several errors.
`/whatever/res/values-v31/colors.xml:34: error: resource android:color/background_floating_material_dark is private.`

This I could fix with replacing @android with @*android.

But then I got this errors.
`whatever/res/color-v31/m3_ref_palette_dynamic_neutral24.xml:4: error: attribute android:lStar not found.`

So, since I compile my app for Android 10+, I can not unpack and repack the apk file with apktool any longer.
Maybe my recompiled ans smaller app is not running, because there are some things missing while recompiling.

**Comment by DieselDriver** [comment]
This test worked:

```
apktool d -r compiled.apk -o whatever
apktool b whatever -o whatever_repacked.apk
```

**apktool 8.6.1:**

release 1:
37M compiled.apk
38M whatever_repacked.apk

latest release:
54M compiled.apk
43M  whatever_repacked.apk

You can see, that the latest release is quite smaller than the original apk file.

This does not work while recompiling
```
apktool d -s compiled.apk -o whatever
apktool b whatever -o whatever_repacked.apk
```

**Comment by iBotPeaches** [comment]
I see, so skipping resource disassembly leads to a proper build.

**Comment by DieselDriver** [comment]
Yes, but only on older release I compiled with older Android Studio.
Since I changed to Android 10+ apps, it also do not work with skipping resource disasselmbly. Then the recompiled apk file has 10 MB less size. It can be installed but it will not start.

Same procedure on 2.9.1. :-(

**Comment by DieselDriver** [comment]
Noone any idea?

Please re-open this issue.
