### ISSUE TITLE
[BUG] Apk can't recompile aarch64 (exit coad 132)

### ISSUE THREAD

**Issue by Mr-parfect** [iBotPeaches/Apktool#3466]
### Information
1. **Apktool Version (`2.9.1`)** -
2. **Operating System (Kali Linux aarch64)** -
3. **APK From? (Other)** -
4. **Java Version (`openjdk 11.0.20-ea`)** -

### Stacktrace/Logcat

```
apktool d -f facebook-lite-382-0-0-11-115.apk
I: Using Apktool 2.9.1 on facebook-lite-382-0-0-11-115.apk                  I: Loading resource table...
I: Decoding file-resources...                                               I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...                                              I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

┌──(root㉿localhost)-[/home/kali/Orignal_Apk]
└─# apktool b -f facebook-lite-382-0-0-11-115
I: Using Apktool 2.9.1
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_31908099058997817067855686471448335619.tmp, compile, --dir, /home/kali/Orignal_Apk/facebook-lite-382-0-0-11-115/res, --legacy, -o, /home/kali/Orignal_Apk/facebook-lite-382-0-0-11-115/build/resources.zip]

```

### Steps to Reproduce
1. `apktool d facebook-lite-382-0-0-11-115.apk
apktool d -f facebook-lite-382-0-0-11-115.apk
apktool b facebook-lite-382-0-0-11-115 
apktool b -f facebook-lite-382-0-0-11-115`

### APK
I was decompile apk successfully but when I recompile it they show a error. Please tell me what can I do?

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Exit code 132 is illegal instruction, which normally means you are running on an unsupported architecture
