### ISSUE TITLE
[BUG]Starting from version 2.9.0, it is not suitable for compiling files with Chinese paths.

### ISSUE THREAD

**Issue by maomc** [iBotPeaches/Apktool#3477]
Starting from the latest version 2.9.0, if there is a Chinese path, the compilation cannot be completed. For versions earlier than 2.9.0, the compilation can be completed.

**Comment by iBotPeaches** [comment]
I believe this is a new limitation of aapt2. You are welcome to use aapt1 or remove non-ascii characters from path.
