### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by trollogyadherent** [iBotPeaches/Apktool#3483]
### Information
1. **Apktool Version** - 2.9.1
2. **Operating System** - Linux
3. **APK From?** - Playstore
4. **Java Version** - openjdk 11.0.21 2023-10-17

### Stacktrace

d:
```
I: Using Apktool 2.9.1 on audioteka.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/-/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
```
b:
```
I: Using Apktool 2.9.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: audioteka_repack.apk
```

When trying to install over adb:
```
Performing Streamed Install
adb: failed to install signed.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl172274698.tmp/base.apk (at Binary XML file line #95): <meta-data> requires an android:value or android:resource attribute]
```

### Steps to Reproduce
* See stacktrace, I did no modification to files

### APK
[https://play.google.com/store/apps/details?id=com.audioteka&hl=en&gl=US](https://play.google.com/store/apps/details?id=com.audioteka&hl=en&gl=US)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
My guess based on the naming you have that you disassembled the main split apk, which probably has a `@xml/splits0` reference in the Manifest file.

Since Apktool is building 1 apk at a time and not like bundletool with access/knowledge of the splits - it probably nulled out that value and led to that.

We've got a few open tickets for split apk handling so I'll close this one.
