### ISSUE TITLE
[BUG] [-] zipalign: symbol lookup error

### ISSUE THREAD

**Issue by Atuls-git** [iBotPeaches/Apktool#3485]
### Information
1. **Apktool Version (`apktool -2.9.1`)** -
2. **Operating System ( Linux )** -
3. **APK From? (Other)** -
4. **Java Version (`11`)** -

### Stacktrace/Logcat

```
[*] Rebuilding apk with ```abc``` as /tmp/d20231231-119197-mcvihu/output.apk
[*] Aligning /tmp/d20231231-119197-mcvihu/output.apk
[-] zipalign: symbol lookup error: zipalign: undefined symbol: _ZN11zip_archive6WriterD2Ev
Error: Unable to align apk with zipalign.
```

### Steps to Reproduce
1. `apktool d netflix.apk`
2. `apktool b netfix.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it: **[Link](https://netflix-mobile.en.aptoide.com/app)**

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No, I did something with manifest of original apk.
3. If you are trying to install a modified apk, did you resign it? Couln't even rebuild it.
4. Are you using the latest apktool version? Yes, its 2.9.1

**Comment by iBotPeaches** [comment]
We don't have zipalign bundled, so this must be a different tool. Closing.

**Comment by Atuls-git** [comment]
Okay, however, I'm still writing the solution here to help people who will be searching for a solution to this error.

To fix this error, enter these commands:
1. `nano /etc/apt/sources.list`
Then you will see something like this:

![Screenshot_2023-12-31_23_46_46](https://github.com/iBotPeaches/Apktool/assets/54507991/006485b2-9fc4-43ed-9dda-bd30b1922809)

2. Add this line in the file: `deb http://ftp.de.debian.org/debian buster main` and comment out any line that is not in the comment, you can use `#` to comment out a line, after making changes, your file should look like this:

![Screenshot2](https://github.com/iBotPeaches/Apktool/assets/54507991/cae87e7d-180f-4538-889a-7bbfaa7b8bf0)

3. After that, hit `CTRL+X`, `Y`, `ENTER` in the same sequence I wrote.
4. Now, update your system using `apt update`
5. After the update is done, run this command: `apt --purge remove zipalign -y`, this removes all files of zipalign from the system.
6. Now install the zipalign again using `apt install zipalign -y`.
7. After installation, type `zipalign`. You will see the result :)
