### ISSUE TITLE
Jar wont open [BUG]

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [iBotPeaches/Apktool#3486]
Newest ApkTool Jar wont open for me. Windows 10, latest java version

**Comment by iBotPeaches** [comment]
What type of error?

**Comment by iBotPeaches** [comment]
Our CI is passing on Windows, so I'm closing as this seems like a support issue.

**Comment by TOBIBLASTER00912** [comment]
It doesnt open. The window is not popping up. Other java programs work

**Comment by iBotPeaches** [comment]
Its not a GUI tool, so it wouldn't pop a window.

**Comment by TOBIBLASTER00912** [comment]
how to use it then?

**Comment by iBotPeaches** [comment]
https://apktool.org/docs/install :)

**Comment by TOBIBLASTER00912** [comment]
ty
