### ISSUE TITLE
Build Failure with Apktool 2.9.3 on Linux due to Syntax Error in Temporary File

### ISSUE THREAD

**Issue by Arab-developers** [iBotPeaches/Apktool#3498]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux (Kali)
3. **APK From? (Playstore, ROM, Other)** - Playstore ([Phone Directory & Caller ID](https://play.google.com/store/apps/details?id=com.app.phonedir&hl=en&gl=US))
4. **Java Version (`java --version`)** - openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Debian-1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1, mixed mode, sharing)

### Stacktrace/Logcat

```
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_110116639072366788558884897057900241197.tmp, compile, --dir, /home/kali/Development/Apps/com.test/base/res, --legacy, -o, /home/kali/Development/Apps/com.test/base/build/resources.zip]
W: /tmp/brut_util_Jar_110116639072366788558884897057900241197.tmp: 4: Syntax error: Unterminated quoted string
```

### Steps to Reproduce
1. Run `apktool d base.apk` to decompile an APK.
2. Make no changes to the decompiled files.
3. Attempt to rebuild the APK with `apktool b base`.
4. Observe the syntax error and build failure.

### Frameworks
N/A - This issue occurred with a standard APK not specific to any OEM.

### APK
The APK in question is available on the Playstore: [Phone Directory & Caller ID](https://play.google.com/store/apps/details?id=com.app.phonedir&hl=en&gl=US).

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes, the error occurs even without making any changes to the decompiled APK.
2. If you are trying to install a modified apk, did you resign it? - Not applicable, as the issue occurs during the build process before signing.
3. Are you using the latest apktool version? - Yes, using Apktool 2.9.3.

**Comment by iBotPeaches** [comment]
May you pull the aapt(s) prebuilts from here and execute them in isolation to test? https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt

My guess is one of 2 things is happening

 * Our copy of those binaries out of Apktool into /tmp for execution is not allowed for x reason
 * The architecture in play is invalid
 
 They are static binaries so they should not depend on any shared objects.

**Comment by SebastiaanTheCoder** [comment]
Hey, was any solution found because I just ran into the exact same issue?

**Comment by iBotPeaches** [comment]
> Hey, was any solution found because I just ran into the exact same issue?

Are you positive its the same issue? If so, may you follow my unanswered question above?

**Comment by iBotPeaches** [comment]
Odd @MohamedAl-Kainai - I run apktool on my M1 - did the arch change between M2? I guess I'm a bit lost on the intended arch. If you are running Kali on a Apple M2, but inside a VM that supports Apple Silicon I guess I don't know what it should be. We have code to read Java vars to determine which arch/os to use.

Like maybe this mac binaries are the intended one? https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt/macosx

**Comment by SebastiaanTheCoder** [comment]
A fix that worked for me is downgrading to 2.8.1 (not sure if this step is needed) and afterwards running the following command:
`sudo apt install binfmt-support qemu-user-static`
as found in https://github.com/iBotPeaches/Apktool/issues/2407.

**Comment by iBotPeaches** [comment]
Thanks - good to know. So we either don't support the arch intended with aapt or improperly detecting the right arch to use.

**Comment by Arab-developers** [comment]
> A fix that worked for me is downgrading to 2.8.1 (not sure if this step is needed) and afterwards running the following command: `sudo apt install binfmt-support qemu-user-static` as found in #2407.

Thanks for sharing your solution! I tried running the command `sudo apt install binfmt-support qemu-user-static` without downgrading to 2.8.1, and it worked perfectly for me as well.

**Comment by MohamedAl-Kainai** [comment]
> A fix that worked for me is downgrading to 2.8.1 (not sure if this step is needed) and afterwards running the following command: `sudo apt install binfmt-support qemu-user-static` as found in #2407.

This solution worked for me too, thanks!

**Comment by iBotPeaches** [comment]
May some of you with this issue give me an output of: `java -XshowSettings:properties -version` ?

I'm curious of a few of those to see if our OS Detection is invalid and feeding wrong arch binaries to you forcing the usage of qemu emulation.

**Comment by micer** [comment]
I'm still having the same issues on Apktool 2.12.0 on Macbook Pro M1. I installed qemu via homebrew and that helped.

```
> java -XshowSettings:properties -version
Property settings:
    file.encoding = UTF-8
    file.separator = /
    ftp.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
    http.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
    java.class.path =
    java.class.version = 63.0
    java.home = /Users/micer/Library/Java/JavaVirtualMachines/azul-19.0.1/Contents/Home
    java.io.tmpdir = /var/folders/nl/3djf06cn207cvz4y0v5s522w0000gn/T/
    java.library.path = /Users/michal/Library/Java/Extensions
        /Library/Java/Extensions
        /Network/Library/Java/Extensions
        /System/Library/Java/Extensions
        /usr/lib/java
        .
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 19.0.1+10
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 19
    java.vendor = Azul Systems, Inc.
    java.vendor.url = http://www.azul.com/
    java.vendor.url.bug = http://www.azul.com/support/
    java.vendor.version = Zulu19.30+11-CA
    java.version = 19.0.1
    java.version.date = 2022-10-18
    java.vm.compressedOopsMode = Zero based
    java.vm.info = mixed mode, sharing
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 19
    java.vm.vendor = Azul Systems, Inc.
    java.vm.version = 19.0.1+10
    jdk.debug = release
    line.separator = \n
    native.encoding = UTF-8
    os.arch = aarch64
    os.name = Mac OS X
    os.version = 15.5
    path.separator = :
    socksNonProxyHosts = local|*.local|169.254/16|*.169.254/16
    stderr.encoding = UTF-8
    stdout.encoding = UTF-8
    sun.arch.data.model = 64
    sun.boot.library.path = /Users/micer/Library/Java/JavaVirtualMachines/azul-19.0.1/Contents/Home/lib
    sun.cpu.endian = little
    sun.io.unicode.encoding = UnicodeBig
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    user.country = ES
    user.dir = /Users/micer/Devel/
    user.home = /Users/micer
    user.language = en
    user.name = micer

openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Zulu19.30+11-CA (build 19.0.1+10)
OpenJDK 64-Bit Server VM Zulu19.30+11-CA (build 19.0.1+10, mixed mode, sharing)
```
