### ISSUE TITLE
Moovit map not shown

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#3502]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** -p https://moovit.en.uptodown.com/android Moovit 5.137..0.1613
4. **Java Version (`java --version`)** -p

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

I downloaded
.https://moovit.en.uptodown.com/android Moovit 5.137..0.1613

When I install this original version it works fine.
But then I use apktool.2.9.3 to decode with -r, then build, jarsign, install and execute.
I hit a line name or hit "Stops", but now it fails to draw the map

**Comment by iBotPeaches** [comment]
Applications can have many anti-tamper patterns. Do you have the logcat while that action is occurring? You'll want to see what its being logged during issues like that.

**Comment by beaumontk** [comment]
What should I be looking for in the logcat?
I logged both the original and the apktool built version, but have not found anything very interesting
[log_002_orig.txt](https://github.com/iBotPeaches/Apktool/files/14151804/log_002_orig.txt)
[log_001_built.txt](https://github.com/iBotPeaches/Apktool/files/14151805/log_001_built.txt)

**Comment by iBotPeaches** [comment]
> So the issue is not a bug and should be closed. But the crash due to the size of a smali directory could possibly be
handled more gracefully? See issue#3343

Glad you got it. The size limit comes from smali so outside of wrapping their exception we rely on them.
