### ISSUE TITLE
[BUG] Apk can not install after re build

### ISSUE THREAD

**Issue by newtimegpt** [iBotPeaches/Apktool#3505]
Information
Apktool Version (apktool -version) - Using Apktool 2.9.3 (install via brew)
Operating System (Mac, Linux, Windows) - MacOS
APK From? (Playstore, ROM, Other) - google play store
Java Version (java --version) - openjdk 21.0.1 2023-10-17

Steps to Reproduce
apktool d --only-main-classes -f -m --use-aapt2 app-release.apk -o out
apktool b --use-aapt2 out -o new.apk

Hi @iBotPeaches
After decoding and building this APK, it does not run despite there being no errors during the decode and build process. When installing the new.apk, I encounter the error: App not installed as package appears to be invalid.

(Please unzip to get app-release.apk for testing )
[app-release.apk.zip](https://github.com/iBotPeaches/Apktool/files/14119927/app-release.apk.zip)

**Comment by iBotPeaches** [comment]
If you run `adb logcat` during the execution you'll get the real error. At the moment what you've provided is not enough to go on.

**Comment by newtimegpt** [comment]
@iBotPeaches 

```
Performing Streamed Install
adb: failed to install new.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from base.apk: Attempt to get length of null array]
```

Thank you for helping me gain more knowledge to debug and understand the issue. I assume the reason for the installation failure is that the APK hasn't been signed with the new signature.

**Comment by PhaserEditor2D** [comment]
Hey @newtimegpt I'm getting the same error. Did you find the solution?

**Comment by gabrielparca** [comment]
same issue, antispliting and selecting match original signature when compiled the app isn't signed..
