### ISSUE TITLE
[BUG] Duplicate entry stamp-cert-sha256 when rebuilding

### ISSUE THREAD

**Issue by biggestsonicfan** [iBotPeaches/Apktool#3536]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore via QooApp
4. **Java Version (`java --version`)** - 11.0.21 2023-10-17 LTS

### Stacktrace/Logcat
(command prompt output)
```
c:\android3>java -jar apktool.jar d -r -s base.apk.orig
I: Using Apktool 2.9.3 on base.apk.orig
I: Copying raw resources...
I: Copying raw manifest...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

c:\android3>java -jar apktool.jar b -c -o base-mod.apk base.apk.orig.out
I: Using Apktool 2.9.3
I: Copying base.apk.orig.out classes.dex file...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy stamp-cert-sha256...
I: Copy META-INF...
I: Building apk file...
I: Copying unknown files/dir...
java.util.zip.ZipException: duplicate entry: stamp-cert-sha256
```

### Steps to Reproduce

1. Extract apk with apktool `java -jar apktool.jar d -r -s base.apk` (`-r` and `-s` params optional)
2. Rebuild apk `java -jar apktool.jar b -c -o base-mod.apk base` (`-c` param optional)

### Frameworks
N/A

### APK
[APK Mega Link](https://mega.nz/file/BR5QjLiB#q3cnK-N4UqOAKrCAu5agRd6ajPBAqFua_EH5wzFHeTs)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Y**
3. If you are trying to install a modified apk, did you resign it? ~~**N/A**, could not get that fair~~ Managed to get a "build", did not resign and installation is refused by nonroot.
4. Are you using the latest apktool version? **Y**

### Other info
`stamp-cert-sha256` appears to be extracted twice, once into the `original` folder and once into the `unknown` folder. Rebuilding with the file removed from either causes the rebuilt APK not to install (removing from the `unknown` folder requires modification of the generated `apktool.yml`, removing `stamp-cert-sha256` from the `unknownFiles` list)

**Comment by iBotPeaches** [comment]
```
➜  3536 apktool b base -c -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool v2.9.2-27-5422bd70-SNAPSHOT with 8 thread(s).
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy stamp-cert-sha256...
I: Copy META-INF...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: base/dist/base.apk
➜  3536 
```

Thanks for report. Will be fixed shortly.
