### ISSUE TITLE
[BUG] Rebuild of Citra MMJ with altered assets does not put altered assets into data folder

### ISSUE THREAD

**Issue by sirloinsteak11** [iBotPeaches/Apktool#3546]
### Information
1. **Apktool Version 2.9.3** -
2. **Operating System Windows** -
3. **APK From? Github** -
4. **Java Version 1.8.0_401** -

### Stacktrace/Logcat

```
>apktool b citrammj
I: Using Apktool 2.9.3
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: citrammj\dist\citrammj.apk
```

### Steps to Reproduce
1. `apktool b citrammj`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
N/A

### APK
https://github.com/weihuoya/citra/releases/tag/20231222 - original

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

original apk is around 16MB, added assets brings it up to around 512MB.

im basically trying to add mods through modifying the apk since I have no way of accessing it within the data folder. all i have done to modify the apk is copy over the folders i have from the pc version. when i install the modified version, the save data and configs transfer over, but the actual mods folder remains empty. also, when looking at the permissions of the mods folder when it is installed, it is not writeable.

**Comment by iBotPeaches** [comment]
I'm not following what you are doing. Apktool won't just take random new files you add and copy along to application. You have to tell it about them in `apktool.yml`, saying that still though. I don't see how this is a bug - it seems like a misunderstanding of the tool.
