### ISSUE TITLE
Unable to rebuild apk with apktool 

### ISSUE THREAD

**Issue by RahulTarafder** [iBotPeaches/Apktool#3548]
![Screenshot_2024_0320_102924](https://github.com/iBotPeaches/Apktool/assets/109901628/89461e0a-2e08-4155-81ec-07318693ea39)

**Comment by iBotPeaches** [comment]
Sorry not really enough details here to go on here, but exit code 132 is like unknown instruction so I'm getting the aapt binary executing on whatever you are trying is invalid.

**Comment by RahulTarafder** [comment]
> Sorry not really enough details here to go on here, but exit code 132 is like unknown instruction so I'm getting the aapt binary executing on whatever you are trying is invalid.

Actually I'm using proot-distro on termux and I'm facing this problem can have any solution need to fix this

**Comment by iBotPeaches** [comment]
Nope that explains it - its not supported.
