### ISSUE TITLE
[BUG] Attribute android:lStar not found

### ISSUE THREAD

**Issue by ThisMyBegin** [iBotPeaches/Apktool#3549]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - ubuntu
3. **APK From? (Playstore, ROM, Other)** - Website google.com
4. **Java Version (`java --version`)** - 11.0.22

### Stacktrace/Logcat
I: Using Apktool 2.9.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral12.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral17.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral22.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral24.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral4.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral6.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral87.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral92.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral94.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral96.xml:4: error: attribute android:lStar not found.
W: /home/joker/Desktop/workdir/4/res/color-v31/m3_ref_palette_dynamic_neutral98.xml:4: error: attribute android:lStar not found.
W: error: failed linking file resources.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_17536888358888737005835747520563167669.tmp, link, -o, /tmp/APKTOOL6292723299336878223.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 18, --version-name, 1.1.8, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, /tmp/APKTOOL12809554055167613163.tmp, -0, arsc, -I, /home/joker/.local/share/apktool/framework/1.apk, --manifest, /home/joker/Desktop/workdir/4/AndroidManifest.xml, /home/joker/Desktop/workdir/4/build/resources.zip]

```
Include stacktrace here
```

### Steps to Reproduce
1. 'apktool --frame-path /tmp d 4.apk'
2. `apktool  --frame-path /tmp b --force-all 4 --use-aapt2 -o 4.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
No

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.balaji.mykhata&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it?No, this error is when building apk
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Chances are you need to empty your framework files or have a stale one. Look into `apktool empty-framework-dir`

```
➜  3549 apktool d com.balaji.mykhata.apk 
I: Using Apktool v2.9.2-27-5422bd70-SNAPSHOT on com.balaji.mykhata.apk with 8 thread(s).
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3549 apktool b com.balaji.mykhata
I: Using Apktool v2.9.2-27-5422bd70-SNAPSHOT with 8 thread(s).
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: com.balaji.mykhata/dist/com.balaji.mykhata.apk
```
