### ISSUE TITLE
[BUG] brut.directory.PathNotExist: apktool.yml

### ISSUE THREAD

**Issue by RackYican** [iBotPeaches/Apktool#3555]
### Information
1. **Apktool Version (`2.9.3`)** -
2. **Operating System (Manjaro Linux)** -
3. **APK From? (Playstore)** -
4. **Java Version (`openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7)
OpenJDK 64-Bit Server VM (build 11.0.22+7, mixed mode)`)** -

### Stacktrace/Logcat

```
brut.directory.PathNotExist: apktool.yml
```

### Steps to Reproduce
1. `apktool b 'folder' -o output.apk`

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, outputs the same thing
2. If you are trying to install a modified apk, did you resign it? I'm not trying to install a modified apk, i'm trying to build it from a folder
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
If something like this was broken in the tool - we'd have massive CI failures and more. Double check you are disassembling the right location. Confirm you see a `apktool.yml` in the folder. Re-run the disassembly and look for errors.

Closing as not reproducible.
