### ISSUE TITLE
[BUG] Cannot recompile firefox

### ISSUE THREAD

**Issue by dirt2022** [iBotPeaches/Apktool#3557]
### Information
1. **Apktool Version (`apktool -version`)** -
 latest, 2.9.3
3. **Operating System (Mac, Linux, Windows)** -
 Android 10 (aarch64)
 (I use apktool on Termux)
5. **APK From? (Playstore, ROM, Other)** -
 Github
7. **Java Version (`java --version`)** -
  openjdk 17-internal 2021-09-14
  OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
  OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)

### Stacktrace/Logcat

```
Include stacktrace here

~/tmp $ apktool b base/
I: Using Apktool 2.9.3
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_5893680575882952219191133115008529216.tmp, compile, --dir, /data/data/com.termux/files/home/tmp/base/res, --legacy, -o, /data/data/com.termux/files/home/tmp/base/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_5893680575882952219191133115008529216.tmp[235]: syntax error: unexpected '('
```

### Steps to Reproduce
1. `apktool  d base.apk`
2. `apktool b base`

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://github.com/mozilla-mobile/firefox-android/releases/download/fenix-v124.1.0/fenix-124.1.0-arm64-v8a.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes 
2. If you are trying to install a modified apk, did you resign it?
It can't be repacked.So I cannot install it.
3. Are you using the latest apktool version?
Yes

**Comment by dirt2022** [comment]
When we're using debian arm64 chroot container,it will be also broken.

**Comment by iBotPeaches** [comment]
This isn't a supported OS

> Android 10 (aarch64)

Sorry.
