### ISSUE TITLE
[BUG]I HAVE BEEN FACING THIS ISSUE FOR SO LONG

### ISSUE THREAD

**Issue by Hypoonsil** [iBotPeaches/Apktool#3606]
APKTOOL VERSION 2.9.3
JAVA VERSION OPENJDK 21.0.3
OS KALI LINUX
APK FROM APKMONK

So this issue has happened from msfvenom and from apktool.
This happens when an apk is decompiled then when i try to recompile it it shows this error

### Stacktrace/Logcat

─$ sudo apktool b mp3.music.download.player.music.search_2024-03-14
I: Using Apktool 2.9.3
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/res/values/styles.xml:6336: error: expected enum but got (raw string) 1.
W: /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/res/values/styles.xml:6350: error: expected enum but got (raw string) 1.
W: /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/res/values/styles.xml:6420: error: expected enum but got (raw string) 2.
W: /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/res/values/styles.xml:6424: error: expected enum but got (raw string) 2.
W: error: failed linking references.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_154271610097745147249126741162488554419.tmp, link, -o, /tmp/APKTOOL4529704182983614538.tmp, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 90000455, --version-name, 4.5.5, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, /tmp/APKTOOL4105753560693934091.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, --manifest, /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/AndroidManifest.xml, /home/hypensil/badapks/mp3.music.download.player.music.search_2024-03-14/build/resources.zip]

### Steps to Reproduce
1. `apktool b {apk_folder} `

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?Yes
2. If you are trying to install a modified apk, did you resign it?i am not using a modified apk
3. Are you using the latest apktool version?Yes

### APK
[https://d2.apkmonk.com/apk-14/mp3.music.download.player.music.search_2024-03-14.apk?mac=DhPOGIZVACZccL22C11INj2M3xQ=&expiry=1716538803](url)

**Comment by iBotPeaches** [comment]
Thanks even with the upset tone. We are tracking this in #3534

**Comment by Hypoonsil** [comment]
Yeah sorry for the tone mb
