### ISSUE TITLE
[BUG]Can't find framework resources for package of id: 3. You must install proper framework files

### ISSUE THREAD

**Issue by Cipivious** [iBotPeaches/Apktool#3617]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - ROM
4. **Java Version (`java --version`)** - 21.0.3

### Stacktrace/Logcat
 I used apktool if VivoCameara.apk and successfully installed 127.apk under the specified path ~/.local/share/apktools/framework, but this file still does not load automatically when using apktool d
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

![截图 2024-06-10 09-21-31](https://github.com/iBotPeaches/Apktool/assets/135787619/2093a40f-5062-4851-ab37-c3c1dfeeb5b9)

**Comment by iBotPeaches** [comment]
Installing the same application as a framework won't help. You can see its `0x7F` (127) which is a private app - you need a system resource which is normally 1-3.

So you just haven't found the framework file you need. So I don't see a bug here - closing.
