### ISSUE TITLE
[BUG] in last release 2.9.3  [235] could not exec ..  syntax error: unexpected '('

### ISSUE THREAD

**Issue by coolshark** [iBotPeaches/Apktool#3620]
### Information
1. **Apktool Version 2.9.3 -
2. **Operating System Android Termux -
3. **APK From? Playstore -
4. **Java Version openjdk 17-internal

[235] could not exec ..  syntax error: unexpected '('

![Screenshot_20240612_234635_com termux](https://github.com/iBotPeaches/Apktool/assets/293121/60bb252b-823d-4206-92b4-f693cd794667)

**Comment by iBotPeaches** [comment]
Apktool was never officially supported on Android so I'm sorry - I'm closing this.
