### ISSUE TITLE
[BUG]Could not decode file

### ISSUE THREAD

**Issue by dingshaohua-com** [iBotPeaches/Apktool#3622]
### Information
1. **Apktool Version： 2.9.3** -
2. **Operating System： Linux or Windows** -
3. **APK From： [Gaode Map](https://www.amapauto.com/download)** -
4. **Java Version： 21.0.2** -

`apktool.bat d .\gaode.apk`
![QQ截图20240616162645](https://github.com/iBotPeaches/Apktool/assets/18003391/68b9d6eb-f4ef-455d-8747-837c3c2934c4)

`apktool.bat b .\gaode\`
![image](https://github.com/iBotPeaches/Apktool/assets/18003391/b4c49524-5c73-4798-8791-9661c4d719bd)

**Comment by dingshaohua-com** [comment]
I have discovered the problem. It only occurs when it is greater than v2.8.1

**Comment by iBotPeaches** [comment]
The 2nd issue is being tracked in - https://github.com/iBotPeaches/Apktool/issues/3534 so closing as duplicate.
