### ISSUE TITLE
Error Facing in building resources

### ISSUE THREAD

**Issue by noumanali1248** [iBotPeaches/Apktool#3623]
(kali㉿kali)-[~/Desktop]
└─$ apktool b original    
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.0-dirty
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$m3_avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_checked_unchecked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_checked_unchecked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_checked_unchecked__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_checked_indeterminate__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_checked_unchecked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_checked_unchecked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_checked_unchecked__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_indeterminate_checked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_indeterminate_unchecked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_indeterminate_unchecked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_indeterminate_unchecked__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_checked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_checked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_checked__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_indeterminate__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_indeterminate__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_icon_unchecked_indeterminate__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_unchecked_checked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_unchecked_checked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_checkbox_button_unchecked_checked__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_checked_pressed__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_checked_unchecked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_checked_unchecked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_pressed_checked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_pressed_unchecked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_unchecked_checked__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_unchecked_checked__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$mtrl_switch_thumb_unchecked_pressed__0.xml: Invalid file name: must contain only [a-z0-9_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 16, --target-sdk-version, 33, --version-code, 2900, --version-name, 2.9.0, --no-version-vectors, -F, /tmp/APKTOOL3703921588718326903.tmp, -0, resources.arsc, -0, META-INF/androidx.activity_activity.version, -0, META-INF/androidx.annotation_annotation-experimental.version, -0, META-INF/androidx.appcompat_appcompat-resources.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.browser_browser.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core-ktx.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.databinding_baseAdapters.version, -0, META-INF/androidx.databinding_databindingKtx.version, -0, META-INF/androidx.databinding_library.version, -0, META-INF/androidx.databinding_viewbinding.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.dynamicanimation_dynamicanimation.version, -0, META-INF/androidx.emoji2_emoji2-views-helper.version, -0, META-INF/androidx.emoji2_emoji2.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.profileinstaller_profileinstaller.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.room_room-runtime.version, -0, META-INF/androidx.savedstate_savedstate.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.sqlite_sqlite-framework.version, -0, META-INF/androidx.sqlite_sqlite.version, -0, META-INF/androidx.startup_startup-runtime.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.tracing_tracing.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager2_viewpager2.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/androidx.work_work-runtime.version, -0, META-INF/com.google.android.material_material.version, -0, META-INF/kotlinx_coroutines_android.version, -0, META-INF/kotlinx_coroutines_core.version, -0, META-INF/services/i8.y, -0, META-INF/services/kotlinx.coroutines.internal.o, -0, assets/mapk_signer_def_ks, -0, assets/dexopt/baseline.prof, -0, assets/dexopt/baseline.profm, -0, png, -0, arsc, -I, /home/kali/.local/share/apktool/framework/1.apk, -S, /home/kali/Desktop/original/res, -M, /home/kali/Desktop/original/AndroidManifest.xml]

facing this error when again recompiling ??

**Comment by iBotPeaches** [comment]
You are using 2.7.0 which is few years old + "dirty" (unofficial). So please upgrade to the latest official version.
