### ISSUE TITLE
Why am I facing this error

### ISSUE THREAD

**Issue by Mebarek0** [iBotPeaches/Apktool#3626]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 13500, --version-name, 4.3.5, --no-version-vectors, -F, /tmp/APKTOOL4361596499120655628.tmp, -0, resources.arsc, -0, res/raw/ic_arrow_up.svg, -0, res/raw/ic_arrow_down.svg, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/kali/Downloads/android/note/res, -M, /home/kali/Downloads/android/note/AndroidManifest.xml]

**Comment by iBotPeaches** [comment]
Sadly not enough details here to determine anything.
