### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mebarek0** [iBotPeaches/Apktool#3627]
I: Using Apktool 2.7.0-dirty
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt2_64 (defaulting to $PATH binary)
W: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0.
W: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1.
W: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2.
W: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0.
W: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1.
W: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2.
W: /home/kali/Downloads/android/note/res/values/public.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt2, compile, --dir, /home/kali/Downloads/android/note/res, --legacy, -o, /home/kali/Downloads/android/note/build/resources.zip]

**Comment by iBotPeaches** [comment]
Use a more modern version. That was fixed a long time ago. v2.7.0 is years old.
