### ISSUE TITLE
[BUG] brut.androlib.AndrolibException: brut.common.BrutException

### ISSUE THREAD

**Issue by devdan** [iBotPeaches/Apktool#3643]
### Information
1. **Apktool Version 2.9.3** -
2. **Operating System Linux** -
3. **APK From? Other** -
4. **Java Version 11.0.23** -

### Steps to Reproduce
1. This is not reproducable anymore because some garbage in ~/.local/share/apktool was responsible that is now removed

When trying to repack the apk with the b parameter, I got the following exception: brut.androlib.AndrolibException: brut.common.BrutException

Responsible was some garbage in ~/.local/share/apktool from previous versions or from previous runs (first I ran it without --use-aapt2, but later with).

IMO old data in ~/.local/share/apktool should never lead to an error. Is it possible to delete it before each run with "d" or maybe you could give a hint that this should be cleaned if errors occur.

**Comment by iBotPeaches** [comment]
I'm not sure what you are getting at here. You refer to it as "garbage", but its framework files. We have many docs about it.

 * https://apktool.org/docs/in-depth/frameworks/
 * https://apktool.org/docs/the-basics/frameworks
 
 You can even empty it
 
  * https://apktool.org/docs/cli-parameters#empty-framework-directory-options
  
  
Releases call out when the internal framework changes to clear it
 
![Screenshot 2024-07-18 at 10 58 10 AM](https://github.com/user-attachments/assets/a2ae52fc-48c9-4c16-847b-5b8cda1dbfef)

Closing.

**Comment by devdan** [comment]
Sorry if the word garbage triggered you. This was not my intention. I didn't want to say that there is garbage in general in this directory. In my particular case, it was some inconsistent data that lead to the bug I faced.

Thanks to your comment, I understand that it is clearly documented that in some cases, the internal framework needs to be deleted.

However, as a non regular user, I thought it would be helpful to get such a hint without reading all the documentation.
