### ISSUE TITLE
BrutException: could not exec (exit code = 2)

### ISSUE THREAD

**Issue by JametPemula** [iBotPeaches/Apktool#3644]
### Information
1. **Apktool Version (`apktool -version`)** - latest 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Repo
4. **Java Version (`java --version`)** - openjdk version "17.0.12-ea" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12-ea+6-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.12-ea+6-Debian-1, mixed mode, sharing)

### Stacktrace/Logcat
![IMG_20240720_090724](https://github.com/user-attachments/assets/fb226563-efd0-477c-9253-544e829a7b27)

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
no
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
exit code 2 generally means invalid arch - I develop Apktool on my Kali laptop, so I don't think this is a fault/bug.

(my `uname -a`)
```
Linux backwash 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-05-17) x86_64 GNU/Linux
```

Closing for unable to replicate - sorry.
