### ISSUE TITLE
[BUG] webp appears as png - this breaks building the apk

### ISSUE THREAD

**Issue by dzkh** [iBotPeaches/Apktool#3649]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Huawei App Store, Google Play Store BaiduNavigation app in chinese.
4. **Java Version (`java --version`)** - Jetbrains OpenJDK 17, Oracle JDK 22

APK contains several webp files  which being unpacked as PNG-files and thus breaks assembly of APK because of file signature/file extension mismatch during the "Building Resources" phase.

> \res\drawable-hdpi\big_default_img.png: error: failed to read PNG signature: file does not start with PNG signature.

BaiduMap.apk 19.8.0 (1355) downloaded from the Huawei App Store or Google Play Store. Version is latest.
Google Play: https://play.google.com/store/apps/details?id=com.baidu.BaiduMap&hl=en_US
### Steps to Reproduce
1. `apktool d com.baidu.BaiduMap.apk
2. `apktool b com.baidu.BaiduMap.apk 

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - **YES**
2. If you are trying to install a modified apk, did you resign it? **---**
3. Are you using the latest apktool version? **YES**

**Comment by iBotPeaches** [comment]
I guess the question being - were they webm that apktool improperly treated as png? Or png that are improperly webm?

**Comment by dzkh** [comment]
> I guess the question being - were they webm that apktool improperly treated as png? Or png that are improperly webm?
oh, sorry, am talking about webp.
That webp files are webp (with RIFF signature) inside the apk and the appear as png after extraction but still with the RIFF sigrature.
The signature loooks like this: RIFFR WEBPVP8 but this is a static graphic file like PNG.

**Comment by iBotPeaches** [comment]
Okay, can you run `unzip -l apk.apk | grep 'webp'` over the apk?

**Comment by dzkh** [comment]
> Okay, can you run `unzip -l apk.apk | grep 'webp'` over the apk?
[list.txt](https://github.com/user-attachments/files/16337099/list.txt)
1324 occurences.

**Comment by iBotPeaches** [comment]
I don't think Apktool can do anything here. These are labeled as PNGs in the source application and Apktool is not reading magic or determining the real image format.

```
F: Decoding file res/drawable-hdpi-v4/big_default_img.png to res/drawable-hdpi/big_default_img.png
```

**Comment by TheGreatRambler** [comment]
I was able to resolve this using `--wait` and a small script.
```
#!/bin/bash

# Ensure we have the directory as an argument
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

DIR=$1

# Check if the provided directory exists
if [ ! -d "$DIR" ]; then
  echo "Error: Directory $DIR does not exist."
  exit 1
fi

# Loop through all .png files in the directory recursively
find "$DIR" -type f -name "*.png" | while read -r file; do
  # Check if the file is actually a WebP file
  if file "$file" | grep -q "Web/P image"; then
    echo "Re-encoding $file (actually WebP) to PNG..."

    # Use ffmpeg or convert (ImageMagick) to re-encode
    if command -v convert > /dev/null; then
      convert "$file" "$file"
    else
      echo "Error: ffmpeg or ImageMagick (convert) is required for re-encoding."
      exit 1
    fi

    echo "Re-encoded $file"
  else
    echo "$file is already a valid PNG."
  fi
done

echo "Re-encoding process completed."
```
Would be interested in helping you with Baidu Maps @dzkh if you're still working on it, I am doing it as well.
