### ISSUE TITLE
[BUG] After decompiling, the new instruction "invoke-polymorphic" appears, causing the packing to fail.

### ISSUE THREAD

**Issue by binbin594738977** [iBotPeaches/Apktool#3652]
invoke-polymorphic {v3}, Ljava/lang/invoke/MethodHandle;->invokeExact([Ljava/lang/Object;)Ljava/lang/Object;, ()Ljava/util/function/BiFunction;

**Comment by iBotPeaches** [comment]
Not many details here, so I'll direct you to smali which is the repo that handles the source disassemble/assembly.

https://github.com/google/smali
