### ISSUE TITLE
[BUG] Multiple times decompiling a particular apk, generates different output.

### ISSUE THREAD

**Issue by j-kaltes** [iBotPeaches/Apktool#3655]
### Information
1. **Apktool Version (`apktool -version`)** -  2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** -  apkpure:
4. **Java Version (`java --version`)** - openjdk version "17.0.11" 2024-04-16

### Steps to Reproduce

Download 'Dexcom G7_2.2.1.7105_APKPure.apk' from https://d.apkpure.com/b/APK/com.dexcom.g7?version=latest

apktool d  'Dexcom G7_2.2.1.7105_APKPure.apk'  -o one
apktool d  'Dexcom G7_2.2.1.7105_APKPure.apk' -o two

diff -r one two

This shows a lot of differences. I think that it should every time produce the same output.
### APK
 https://d.apkpure.com/b/APK/com.dexcom.g7?version=latest
### Questions to ask before submission
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
![image](https://github.com/user-attachments/assets/9fca6f1b-153a-4326-953d-3a64ded03eb7)

I'm afraid I can't replicate. If you can provide more details for me to replicate - I can revisit. I don't even know from this submission what could have been shifting between disassembles to investigate further.

**Comment by j-kaltes** [comment]
The diff is 95670232 bytes long, but I can show the first part of it:


diff -r one/smali/ig/?.2.smali two/smali/ig/?.2.smali
1c1
< .class public interface abstract Lig/ࡢ;
\-\-\-
\> .class public interface abstract Lig/ࡣ;
3c3,6
< .source "ig.\u0862"
\-\-\-
\> .source "ig.\u0863"
 


[diffstart.txt](https://github.com/user-attachments/files/16522428/diffstart.txt)

**Comment by j-kaltes** [comment]
I also tried it three times under Windows 10 with the following Java version:
```java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
```
And now they were all the same, although I used exactly the same apktool.jar

Under Linux I tested the following Java versions and in all cases there were differences when I decompiled with apktool.jar two times:

```openjdk version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Open Edition 11.0.16.1 (build 11.0.16.1+1)
Eclipse OpenJ9 VM 11.0.16.1 (build openj9-0.33.1, JRE 11 Linux amd64-64-Bit Compressed References 20220818_500 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 84b84a0409 based on jdk-11.0.16.1+1)

openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9)
OpenJDK 64-Bit Server VM (build 17.0.11+9, mixed mode, sharing)

java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

openjdk version "22.0.1" 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8)
OpenJDK 64-Bit Server VM (build 22.0.1+8, mixed mode, sharing)
```
The filenames under Windows and Linux look very different:
**Windows**:
```bash
ls -hSs smali/ig/|head
```
total 7,0M
1,2M ᫙ࡩ.smali
616K ࡡࡠ.smali
220K ᫆᫜.smali
180K ᫞ࡠ.smali
172K ᫕.smali
172K ࡲࡠ.smali
168K ࡰࡩ.smali
148K ᫒ࡩ.smali
124K ᫓.smali
**Linux**:
```bash
ls -hSs smali/ig/|head
```
total 6,7M
1,2M ??.175.smali
580K ??.4.smali
208K ??.111.smali
172K ??.196.smali
164K ?.37.smali
160K ??.71.smali
156K ??.66.smali
140K ??.153.smali
116K ?.35.smali
