### ISSUE TITLE
[BUG]中文字符

### ISSUE THREAD

**Issue by jiangjiali** [iBotPeaches/Apktool#3658]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -

### Stacktrace/Logcat
```
W: error: could not open extensions file C:\Users\蒋佳李\AppData\Local\Temp\APKTOOL4179264087296352994.tmp for reading.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\������\AppData\Local\Temp\brut_util_Jar_9931861876776727203649383573304203455.tmp, link, -o, C:\Users\������\AppData\Local\Temp\APKTOOL5123804592909385344.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 34, --version-code, 2000, --version-name, 24.07.29+2000, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, C:\Users\������\AppData\Local\Temp\APKTOOL4179264087296352994.tmp, -0, arsc, -I, C:\soft\apk-editor-studio\data\frameworks\1.apk, --manifest, C:\soft\apk-editor-studio\data\temp\apk\{c86a3191-539f-4a86-85aa-c7bbd57611fa}\AndroidManifest.xml, C:\soft\apk-editor-studio\data\temp\apk\{c86a3191-539f-4a86-85aa-c7bbd57611fa}\build\resources.zip]

听说是中文字符的问题，不知道作者可否支持一下中文路径。
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
I've found on Windows especially with aapt/aapt2 execution that non-latin chars in directory path will break.

> 听说是中文字符的问题，不知道作者可否支持一下中文路径。

我认为 Apktool 不能解决这个问题

**Comment by jiangjiali** [comment]
> I've found on Windows especially with aapt/aapt2 execution that non-latin chars in directory path will break.
> 
> > 听说是中文字符的问题，不知道作者可否支持一下中文路径。
> 
> 我认为 Apktool 不能解决这个问题

感谢！
