### ISSUE TITLE
[BUG] Windows - apktool build fails due to UTF8 filename

### ISSUE THREAD

**Issue by baidwwy** [iBotPeaches/Apktool#3660]
java.exe -jar E:/GGE2/GGELUA2/build/android/apktool.jar build E:/GGE2/GGELUA2/examples/01-基础/02-图片/.ggelua/android --force-all -output outapk

2.8 is ok 
2.9 and latest not ok

**Comment by iBotPeaches** [comment]
Please stick to latin charsets - this is a regression in aapt2/aapt and not in my control
