### ISSUE TITLE
[BUG]brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by GoLuBnAtAsHa** [iBotPeaches/Apktool#3661]
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Xiaomi HyperOS 1.0.2.0 UNFEUXM (Termux) 
3. **APK From? (Playstore, ROM, Other)** - Playstore, extracted with X-plore
4. **Java Version (`java --version`)** - openjdk 17-internal 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)

### Stacktrace/Logcat
I: Using Apktool 2.9.3
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_9136709250805061954846869837092777736.tmp, compile, --dir, /data/data/com.termux/files/home/base/res, --legacy, -o, /data/data/com.termux/files/home/base/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_9136709250805061954846869837092777736.tmp[235]: syntax error: unexpected '('

### Steps to Reproduce
1. `apktool b base -o base1.apk --use-aapt2`

### Frameworks
I can't upload it(
So here is a [Google Drive link](https://drive.google.com/file/d/1w1DQrh6rKjcR-Sjy_SKkAhexErH1J2wH/view?usp=drivesdk)

### APK
[Google Play Store link](https://play.google.com/store/apps/details?id=com.google.earth)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? -
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Apologies - we don't officially support running on Android itself. Maybe I misunderstood, but I believe from the error and Xiaomi/Termux you are.

We don't have arm binaries for aapt/aapt2 which is required for usage.

**Comment by GoLuBnAtAsHa** [comment]
No, pls don't close it, maybe some termux users will answer it
