### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jedj1** [iBotPeaches/Apktool#3668]

**Comment by jedj1** [comment]
[*] Binding /storage/emulated/0/Download/facebook-lite.apk
Using APK template: /storage/emulated/0/Download/facebook-lite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.csxcd
[*] Loading /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Rebuilding apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/output.apk
[-] I: Using Apktool 2.9.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_99523958099729077894210157999496747253.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/original/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_99523958099729077894210157999496747253.tmp[1]: ELF: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_99523958099729077894210157999496747253.tmp[2]: syntax error: unexpected '&'
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[-] I: Using Apktool 2.9.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_133125348426705327074800226541565874503.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20240814-11394-4ritcw/original/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_133125348426705327074800226541565874503.tmp[1]: ELF: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_133125348426705327074800226541565874503.tmp[2]: syntax error: unexpected '&'

**Comment by iBotPeaches** [comment]
Apktool is not officially supported on Android. Apologies.
