### ISSUE TITLE
[BUG] About integer >Integer.MIN_VALUE at  AndroidManifest.xml

### ISSUE THREAD

**Issue by Bingoliallen** [iBotPeaches/Apktool#3685]
### Information
1. **Apktool Version (`2.9.3`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -
4. **Java Version (`java 1.8.0`)** -

Logcat

AndroidManifest.xml

meta-data android:name="com.hihonor.iap.sdk.cpid" android:value="109999795540"  bean changed meta-data android:name="com.hihonor.iap.sdk.cpid" android:value="2147483647"

if I use meta-data android:name="com.hihonor.iap.sdk.cpid" android:value="s109999795540" is OK!

When integer >Integer.MIN_VALUE, how to solve this problem?

**Comment by iBotPeaches** [comment]
Take a look at how we patched it here - https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AndroidManifestResourceParser.java#L53-L57

**Comment by Bingoliallen** [comment]
Haved a new Apktool Version? My  Apktool current version is 2.9.3.  Where can I download it?
