### ISSUE TITLE
[BUG] CountingInputStream is deprecated.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#3687]
Move towards `BoundedInputStream` - https://github.com/apache/commons-io/commit/812d8a4b53d9758b4f081d9b98a70ea9ef131a0e

**Comment by IgorEisberg** [comment]
Fixed by https://github.com/iBotPeaches/Apktool/commit/542b66cbd0b045ac5739b54f66d41c3994ff9769
