### ISSUE TITLE
[BUG] Fail to Compile [brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)]

### ISSUE THREAD

**Issue by ElixirXDE** [iBotPeaches/Apktool#3688]
### Information
1. **Apktool Version (`apktool -version`)** `2.9.3`
2. **Operating System (Mac, Linux, Windows)** `Linux`
3. **APK From? (Playstore, ROM, Other)** `Other :V`
4. **Java Version (`java --version`)** 
`openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)`

### Stacktrace/Logcat

```
I: Using Apktool 2.9.3
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_157967318797728042802486240958054026499.tmp, compile, --dir, /storage/emulated/0/Apktool_M/GTA_ SA_v2.11.245(3458304)/res, --legacy, -o, /storage/emulated/0/Apktool_M/GTA_ SA_v2.11.245(3458304)/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_157967318797728042802486240958054026499.tmp[235]: syntax error: unexpected '('
```

### Steps to Reproduce
1. `apktool b GTA_SA_v2.11.245(3458304)`
                                 or 
2. `apktool b --use-aapt2 GTA_SA_v2.11.245(3458304)`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) 

(`nop, no is a apk of system`)

### APK
If this APK can be freely shared, please upload/attach a link to it. 

(`nop`)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? n/a
3. If you are trying to install a modified apk, did you resign it? n/a
4. Are you using the latest apktool version?
`yes`

**Comment by iBotPeaches** [comment]
It appears you are executing on Android no? That is not supported sorry.

**Comment by ElixirXDE** [comment]
:"""""""""""""vvv thanks
