### ISSUE TITLE
[BUG] Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by Morsalin32k** [iBotPeaches/Apktool#3689]
/data/data/com.termux/files/usr/opt/metasploit-framework/config/application.rb:1: warning: /data/data/com.termux/files/usr/lib/ruby/3.3.0/fiddle.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
/data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/concern/logging.rb:1: warning: /data/data/com.termux/files/usr/lib/ruby/3.3.0/logger.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
Using APK template: hackyou.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.metasploit.stage.mvouh
[*] Loading /data/data/com.termux/files/usr/tmp/d20240909-8727-3nsrkl/original/smali/com/metasploit/stage/MainActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Rebuilding apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20240909-8727-3nsrkl/output.apk
[-] Could not identify aapt binary as executable.
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[-] Could not identify aapt binary as executable.
Error: Unable to rebuild apk with apktool

**Comment by iBotPeaches** [comment]
Apologies but it appears you are running on Android, which is not supported. Sorry.
