### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LucaNoTrops** [iBotPeaches/Apktool#3700]
Hey guys i keep getting the same error and i have no idea what im doing wrong. Help would be greatly appreciated thanks.

> I: Using Apktool 2.9.3
I: Copying C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7} classes.dex file...
I: Copying C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7} classes2.dex file...
I: Building resources...
W: C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\res\values\styles.xml:1888: error: expected enum but got (raw string) 0.
W: C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\res\values\styles.xml:1890: error: expected enum but got (raw string) 1.
W: C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\res\values-sw600dp\styles.xml:5: error: expected enum but got (raw string) 1.
W: C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\res\values-land\styles.xml:5: error: expected enum but got (raw string) 1.
W: error: failed linking references.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\lucat\AppData\Local\Temp\brut_util_Jar_66164035831412082423145381912455155259.tmp, link, -o, C:\Users\lucat\AppData\Local\Temp\APKTOOL963215288189156756.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 910, --version-name, 7.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, C:\Users\lucat\AppData\Local\Temp\APKTOOL2500811340978570433.tmp, -0, arsc, -I, C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\frameworks\1.apk, --manifest, C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\AndroidManifest.xml, C:\Users\lucat\Desktop\APK Editor Studio v1.7.1\data\temp\apk\{48700fc5-cfdb-4896-a2ed-15b5182d2bc7}\build\resources.zip]

**Comment by iBotPeaches** [comment]
Generally you'll want to find the lines that are called out - identify the property and take the literal value (ie 0 or 1) and convert it back to the enum that represents that value.

**Comment by LucaNoTrops** [comment]
> Generally you'll want to find the lines that are called out - identify the property and take the literal value (ie 0 or 1) and convert it back to the enum that represents that value.

Thanks! now I'm getting another error 

> I: Using Apktool 2.9.3
I: Copying C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d} classes.dex file...
I: Copying C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d} classes2.dex file...
I: Building resources...
W: C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\res\values\styles.xml:1888: error: expected enum but got (raw string) 0.
W: C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\res\values\styles.xml:1890: error: expected enum but got (raw string) 1.
W: C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\res\values-sw600dp\styles.xml:5: error: expected enum but got (raw string) 1.
W: C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\res\values-land\styles.xml:5: error: expected enum but got (raw string) 1.
W: error: failed linking references.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\lucat\AppData\Local\Temp\brut_util_Jar_53314395868128628644941075937753160786.tmp, link, -o, C:\Users\lucat\AppData\Local\Temp\APKTOOL7820210894263574505.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 910, --version-name, 7.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, C:\Users\lucat\AppData\Local\Temp\APKTOOL5679723954732259561.tmp, -0, arsc, -I, C:\Users\lucat\AppData\Local\apk-editor-studio\frameworks\1.apk, --manifest, C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\AndroidManifest.xml, C:\Users\lucat\AppData\Local\Temp\apk-editor-studio\apk\{f84a1eac-d1ab-4e65-b626-f3117c109d2d}\build\resources.zip]

any ideas?

**Comment by LucaNoTrops** [comment]
> Generally you'll want to find the lines that are called out - identify the property and take the literal value (ie 0 or 1) and convert it back to the enum that represents that value.

I'm new at this and I don't understand what you mean. I'm literally getting better with trial and error. Basically what I'm doing is trying to rebrand an app just to understand it better but I keep getting the error above. I tried an earlier build of the app and it worked perfectly fine. So just trying to figure out what is different between both builds. Thanks

**Comment by iBotPeaches** [comment]
Understood. Since this is the issue tracker - I'm going to close this out. My last comment does stand as the way to resolve this manually.
