### ISSUE TITLE
[BUG] [13:46:13] brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\2\brut_util_Jar_7103966949551277181881696964604925643.tmp, compile, --dir, C:\Users\Administrator\Downloads\Instagram\res, --legacy, -o, C:\Users\Administrator\Downloads\Instagram\build\resources.zip] [13:46:14] =====[ Error ]===== [13:46:14] Compiling failed

### ISSUE THREAD

**Issue by IXSENPA1XI** [iBotPeaches/Apktool#3712]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -

### Stacktrace/Logcat

[13:46:13] brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\2\brut_util_Jar_7103966949551277181881696964604925643.tmp, compile, --dir, C:\Users\Administrator\Downloads\Instagram\res, --legacy, -o, C:\Users\Administrator\Downloads\Instagram\build\resources.zip]
[13:46:14] =====[ Error ]=====
[13:46:14] Compiling failed
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
I'm afraid I don't recognize this output (must be some wrapper tool) and thus the details of the crash are suppressed.

Nothing to review so I'll close this out.
