### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KimetsuAndrea** [iBotPeaches/Apktool#3714]
### Information
1. **Apktool Version (`apktool -version`)** - **Answer: _2.10.0_**
2. **Operating System (Mac, Linux, Windows)** - **Answer: _Linux localhost 4.19.136-perf+ #1 SMP PREEMPT Sat Sep 28 15:44:54 CST 2024 aarch64 Android_**
3. **APK From? (Playstore, ROM, Other)** - **Answer: _Chrome_**
4. **Java Version (`java --version`)** - **Answer: _openjdk version "21.0.5" 2024-10-15_**

### Stacktrace/Logcat

```
❯ apktool b Data/ --output out.apk
I: Using Apktool 2.10.0 with 6 thread(s).
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_179186574957728854387583908200169979170.tmp[1]: ELF: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_179186574957728854387583908200169979170.tmp[2]: syntax error: unexpected '('
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_179186574957728854387583908200169979170.tmp, compile, --dir, /data/data/com.termux/files/home/downloads/Data/res, --legacy, -o, /data/data/com.termux/files/home/downloads/Data/build/resources.zip]
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[Real.Boxing.ver.2.11.0.build.300162_r.zip](https://github.com/user-attachments/files/17529684/Real.Boxing.ver.2.11.0.build.300162_r.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  **Answer: _Yes_**
2. If you are trying to install a modified apk, did you resign it? **Answer: _No_**
3. Are you using the latest apktool version? **Answer: _Yes_**

**Comment by iBotPeaches** [comment]
Sadly running on Android is not supported.
