### ISSUE TITLE
[BUG] APKTOOL modifys stuff automatically

### ISSUE THREAD

**Issue by amackpro** [iBotPeaches/Apktool#3717]
Tool Version - 2.10
 WSL-2
 OS: Ubuntu 23.04 on Windows 10 x86_64
 Kernel: 5.15.153.1-microsoft-standard-WSL2
 
 decompiled  OnePlus 12R framework.jar from Android 15
 and recompiled without touching any files
 somehow apktool automatically modified  some strings name "call_site_"
 like if it was call_site_7 then it become call_site_4
 
command used for recompilation

apktool -advance -api 35 -j 8 b framework.jar.out/

**Comment by iBotPeaches** [comment]
Apktool wouldn't change the name of resources. It's name changes are when conflicts are detected and are clearly named APKTOOL.

**Comment by amackpro** [comment]
> Apktool wouldn't change the name of resources. It's name changes are when conflicts are detected and are clearly named APKTOOL.
i can upload untouched and recompiled jars here
https://drive.google.com/file/d/17ZKbzlMKl5gSdrB7uwt_7XAdD8KOiEZF/view?usp=sharing

**Comment by amackpro** [comment]
when i compiled using smali.jar 

i got this as output 


out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[119,179] mismatched input 'DOWN' expecting set null
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[121,177] mismatched input 'DOWN' expecting set null
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[143,211] mismatched input 'DOWN' expecting set null
out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[119,290] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[143,326] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[121,290] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[143,434] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting <UP>
out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[119,369] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting <UP>
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[121,366] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting <UP>
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[143,551] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting I_CATCHES
out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[119,449] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting I_CATCHES
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[121,448] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting I_CATCHES
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[116,0] A non-abstract/non-native method must have at least 1 instruction
out/android/hardware/input/PhysicalKeyLayout$EnterKey.smali[121,581] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_FIELDS
out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[114,0] A non-abstract/non-native method must have at least 1 instruction
out/android/hardware/input/PhysicalKeyLayout$LayoutKey.smali[119,623] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_FIELDS
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[138,0] A non-abstract/non-native method must have at least 1 instruction
out/android/hardware/input/KeyboardLayoutPreviewDrawable$GlyphDrawable.smali[143,714] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_FIELDS
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[87,184] mismatched input 'DOWN' expecting set null
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[87,285] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[87,4] Cannot invoke "Object.hashCode()" because the return value of "org.jf.dexlib2.base.reference.BaseMethodHandleReference.getMemberReference()" is null
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[87,449] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_CATCHES
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[82,0] A non-abstract/non-native method must have at least 1 instruction
out/android/media/MediaRouter2$PackageNameUserHandlePair.smali[89,4] mismatched tree node: I_STATEMENT_FORMAT11x expecting I_FIELDS
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[103,199] mismatched input 'DOWN' expecting set null
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[103,306] mismatched tree node: I_ENCODED_METHOD_HANDLE expecting SIMPLE_NAME
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[103,4] Cannot invoke "Object.hashCode()" because the return value of "org.jf.dexlib2.base.reference.BaseMethodHandleReference.getMemberReference()" is null
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[103,492] mismatched tree node: Ljava/lang/invoke/MethodHandles$Lookup; expecting I_CATCHES
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[98,0] A non-abstract/non-native method must have at least 1 instruction
out/android/media/MediaRouter2$InstanceInvalidatedCallbackRecord.smali[105,4] mismatched tree node: I_STATEMENT_FORMAT11x expecting I_FIELDS

**Comment by Danda420** [comment]
encountered the same issue here with apktool version 2.9.3
