### ISSUE TITLE
[BUG] already been interned error when rebuilding

### ISSUE THREAD

**Issue by skiphansen** [iBotPeaches/Apktool#3718]
### Information
1. **Apktool Version (`apktool -version`)** -
```
skip@Dell-5510:~/open_src/audio/pandora_re/patch_pandora_v2107.1$ apktool -version
2.10.0
```

3. **Operating System (Mac, Linux, Windows)** -
```
skip@Dell-5510:~/open_src/audio/pandora_re/patch_pandora_v2107.1$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

5. **APK From? (Playstore, ROM, Other)** -
```
Pandora v21.07.1 from
from https://apkcombo.com/pandora/com.pandora.android/old-versions/
```

7. **Java Version (`java --version`)** -
```
skip@Dell-5510:~/open_src/audio/pandora_re/patch_pandora_v2107.1$ java --version
openjdk 11.0.24 2024-07-16
OpenJDK Runtime Environment (build 11.0.24+8-post-Ubuntu-1ubuntu322.04)
OpenJDK 64-Bit Server VM (build 11.0.24+8-post-Ubuntu-1ubuntu322.04, mixed mode, sharing)
```

### Steps to Reproduce
```
apktool d Pandora_v2107.1.apk
apktool b Pandora_v2107.1/
```

When building the following errors occur:
```
...
I: Building resources...
Pandora_v2107.1/smali_assets/com/facebook/ads/internal/DisplayAdController.smali[9,24] Class Lcom/facebook/ads/internal/DisplayAdController; has already been interned
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
Could not smali file: com/facebook/ads/internal/DisplayAdController.smali
```
Full log:  [rebuild.log](https://github.com/user-attachments/files/17634538/rebuild.log)

### APK
If this APK can be freely shared, please upload/attach a link to it.
```
Download from: https://apkcombo.com/pandora/com.pandora.android/download/phone-2107.1-apk
```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
```
Yes, exactly.
```
3. If you are trying to install a modified apk, did you resign it?
4. Are you using the latest apktool version?
```
yes
```

**Comment by iBotPeaches** [comment]
I believe my comment the last time this occurred here will help you out - https://github.com/iBotPeaches/Apktool/issues/2247#issuecomment-562545820

You may have secondary dex files intentionally made to trick Apktool. So `--only-main-classes` may help

**Comment by skiphansen** [comment]
@iBotPeaches Thanks for the response, adding --only-main-classes worked!
