### ISSUE TITLE
[BUG][build failed] attribute android:requiredSplitTypes not found

### ISSUE THREAD

**Issue by joshuachenn** [iBotPeaches/Apktool#3726]
### Information
1. **2.9.3/2.10.0** -
2. **Mac** -
3. **APKPure** -
4. **java version "1.8.0_271"** -

I'm using [xapk-to-apk](https://github.com/LuigiVampa92/xapk-to-apk) to transfer xapk to apk of [Photovoltaic Calculations_2.1.2_APKPure.xapk](https://apkpure.com/cn/photovoltaic-calculations/it.ettoregallina.calcolifotovoltaici/download/2.1.2), but also shows that repacked failed, and i dig into it,
found that in step `apktool b` failed. xapk-to-apk tool will produce middle product in .xpaktoapk directory in current directory,
and then this tool will execute apktool b command, and failed.

While I going into .xapktoapk directory, and execute apktool b command by my self, it shows errors below.

### Steps to Reproduce
```
➜  xapk-to-apk git:(development) ✗ python xapktoapk.py Photovoltaic\ Calculations_2.1.2_APKPure.xapk
➜  xapk-to-apk git:(development) ✗ cd .xapktoapk
➜  .xapktoapk git:(development) ✗ apktool b it.ettoregallina.calcolifotovoltaici 
I: Using Apktool 2.9.3
I: Checking whether resources has changed...
I: Building resources...
W: /Users/Tools/xapk-to-apk/.xapktoapk/it.ettoregallina.calcolifotovoltaici/AndroidManifest.xml:1: error: attribute android:requiredSplitTypes not found.
W: /Users/Tools/xapk-to-apk/.xapktoapk/it.ettoregallina.calcolifotovoltaici/AndroidManifest.xml:1: error: attribute android:splitTypes not found.
W: error: failed processing manifest.
```

### APK
[Photovoltaic Calculations_2.1.2_APKPure.xapk](https://apkpure.com/cn/photovoltaic-calculations/it.ettoregallina.calcolifotovoltaici/download/2.1.2)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?:**Yes**
2. If you are trying to install a modified apk, did you resign it?:**Not modified not resign**
3. Are you using the latest apktool version?:**Yes, tried already**

**Comment by iBotPeaches** [comment]
I'm not exactly sure why those attributes cannot be found. They look like a relic of building splits. I'm not confident yet, but I believe I'll have to update apktool to remove those attributes as it finds them.

Since Apktool cannot remake splits - it seems like right call.

**Comment by joshuachenn** [comment]
Yeah I guess so. cause xapktoapk tool will make xapk splits into apk, then it goes to make `apktool b`, this build command deals with no splits but as a whole package to pack apk. Looking forward to your updates. hope this will finally solve this problem!

**Comment by IgorEisberg** [comment]
> I'm not exactly sure why those attributes cannot be found. They look like a relic of building splits. I'm not confident yet, but I believe I'll have to update apktool to remove those attributes as it finds them.
> 
> Since Apktool cannot remake splits - it seems like right call.

I highly advise against touching attributes that have significant meaning.
`requiredSplitTypes` is not a relic, the types in there indicate the split APKs that are non-optional for the app to work.
Try Gboard split variant using the base.apk only and you'll have a broken keyboard.
If you sneakily remove the attribute - you mask the fact that the app won't work without the required split APKs.
Apktool does not and cannot deal with split APKs at this time, and should attempt to do so.
If someone wants to use some split APK merging tricks, they should remove the split APK-specific attributes themselves, plenty of ways to do that.

**Comment by joshuachenn** [comment]
I see, Thank you for your practical advice.
