### ISSUE TITLE
Query: Does ApkTool adds these extra initialization as part of any advanced feature?

### ISSUE THREAD

**Issue by GiantPluto** [iBotPeaches/Apktool#3731]
I am trying to reverse an APK to see if it has any additional code added compared to original apk. I see lots of dummy initialization code like `const/4 v2, 0x6` added in pretty much all the smali files. Is it something ApkTool does as part of some advanced switch during recompilation? Any idea or inputs on how these might have got added would be helpful.

![Screenshot 2024-11-23 093937](https://github.com/user-attachments/assets/25f980b2-5f6b-4f39-8e24-8ef547cae1f8)

Thanks

**Comment by iBotPeaches** [comment]
I just imagine the internal upgrades to smali between whatever versions those are changed and caused that. Ultimately best I can say with the details you've provided.
