### ISSUE TITLE
[BUG]windowOptOutEdgeToEdgeEnforcement not appearing in style.xml for sdk 35

### ISSUE THREAD

**Issue by avi112211** [iBotPeaches/Apktool#3737]
### Information
1. **Apktool Version 2.10.0** -
2. **Operating System Mac, Linux** -
3. **APK From? simple project** -
4. **Java Version java 17** -

### Steps to Reproduce
1. `apktool d on the given app`

### APK
attached

### Questions to ask before submission
Since SDK 35, a new attribute has been introduced for controling edge-to-edge display: windowOptOutEdgeToEdgeEnforcement
in short, the following should be added to style file: <item name="android:windowOptOutEdgeToEdgeEnforcement">true</item>

reference:
https://www.droidcon.com/2024/09/20/%F0%9F%9A%A8-google-secretly-adds-opt-out-api-for-android-15s-edge-to-edge-behaviour-%F0%9F%9A%A8/

when using apktool d on the build app, the attribute is not presented, which leads to misconfiguration when building back the app.

Does anyone know how I can overcome this issue?

Thanks.
[app-debug.apk.zip](https://github.com/user-attachments/files/17999081/app-debug.apk.zip)

Avi

**Comment by avi112211** [comment]
Closing the ticket, I've build the latest master version where I saw it contains commits regarding SDK 35, and it's solved my issue.
I guess the next official release will support it.

Thanks

**Comment by avi112211** [comment]
Is there a timeline for the next official release?

**Comment by iBotPeaches** [comment]
> Is there a timeline for the next official release?

Before end of year hopefully. Really waiting on a smali release to fix some issues.

**Comment by avi112211** [comment]
Great thank you
