### ISSUE TITLE
Failure [INSTALL_FAILED_USER_RESTRICTED: Invalid apk]

### ISSUE THREAD

**Issue by jiegege10** [iBotPeaches/Apktool#3741]
The apk was installed from Google. I used adb shell pm path to extract three apk files, namely xhdpi_signed.apk, arm64_v8a_signed.apk, and signed.apk. I used apktool to decompile them and then re-signed them. When I used adb install-multiple to install them, an error message appeared. Failure [INSTALL_FAILED_USER_RESTRICTED: Invalid apk]

**Comment by iBotPeaches** [comment]
I'm fairly sure this is some setting to allow installs from adb. Nothing apktool can change.
