### ISSUE TITLE
apktool doesn't regenerate configChanges="orientation|screenSize" 

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#415]
Original [issue 304](https://code.google.com/p/android-apktool/issues/detail?id=304) created by nathan@janrain.com on 2012-02-11T04:10:23.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. apktool d SimpleDemo-debug.apk
> 2. examine AndroidManifest.xml, there is no screenSize in the configChanges attribute of the JRFragmentHostActivity activities.

<b>What is the expected output? What do you see instead?</b>

I expect to find the JRFragmentHostActivity activities to have configChanges attributes of &quot;orientation|screenSize&quot;. Instead I see configChanges=&quot;orientation&quot;.

<b>What version of the product are you using? On what operating system?</b>

apktool1.4.3.tar.bz2 with apktool-install-macosx-r04-brut1.tar.bz2

<b>Please provide any additional information below.</b>

SimpleDemo-debug.apk was built with ant with project.properties target=android-15. The source manifest can be found here:
https://github.com/janrain/engage.android/blob/master/SimpleDemo/AndroidManifest.xml

I have seen this behavior with other APKs too. They behave on the device as if they do have the screensize attribute though.

**Comment by zi6xuan** [comment]
Hello, I use apktool 2.1.0, this problem still occurs
Platform: windows8 32bit
JDK: jdk1.7.0_25
