### ISSUE TITLE
public.xml id changes when recompile apk

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#569]
Original [issue 458](https://code.google.com/p/android-apktool/issues/detail?id=458) created by email.pl74 on 2013-05-12T14:20:45.000Z:

> <b>What steps will reproduce the problem?</b>
1. apktool if framework-res.apk (create 1.apk)
2. apktool if oppo-framework-res.apk (create 12.apk)
3. apktool d oppo-framework-res.apk
4. Don't change anything
5. apktool b oppo-framework-res oppo-new.apk
6. apktool d oppo-new.apk

<b>What is the expected output? What do you see instead?</b>

When i compare public.xml from original apk and recompiled apk the id are changed. Ex. in original public.xml i find the line:
&lt;public type=&quot;attr&quot; name=&quot;Dialog_Title_textAppearance&quot; id=&quot;0x0c010000&quot; /&gt;
in the recompiled public.xml same line became:
&lt;public type=&quot;attr&quot; name=&quot;Dialog_Title_textAppearance&quot; id=&quot;0x02010000&quot; /&gt;

So if i try to pull new apk to the phone i obtain rebooting system.

<b>What version of the product are you using? On what operating system?</b>

APKTool 1.5.2
aapt from apktool project site (i tried also aapt from latest android sdk)
Windows 7 Home Premium 64bit

<b>Please provide any additional information below.</b>

Here can find apks and two public.xml: http://d-h.st/A1K

**Comment by Fancyfree** [comment]
Did you found any solution on this issue???

**Comment by Fancyfree** [comment]
I found solution by using this software: xdaAutoAPKTool_V5.0.0b
The oppo-framework-res.apk file is finally compiled without this error in the public.xml file <public type="attr" name="Dialog_Title_textAppearance" id="0x02010000" />
The APP is WORKING !!! Tested!
The other problem with the KeKeThemeSpace_W20140729_V2.5.1.apk is gone too!!!
Only you have to modify the default_splash_bg.png image in the drawable-xxhdpi folder and the app will be compiled and working!
