### ISSUE TITLE
Error decode com.htc.resouces.apk 

### ISSUE THREAD

**Issue by hawst** [iBotPeaches/Apktool#59]
Error decode com.htc.resouces.apk  from HTC One X Sense ROM 4.0.4 (OrDroid 1.1.5)

cmdline: 
1) error.txt - apktool d -s -t  OrDroid-1.1.5 com.htc.resources.apk com.htc.resources
2) error_Debug.txt - apktool d -d -s -t  OrDroid-1.1.5 com.htc.resources.apk com.htc.resources

http://www.mediafire.com/download.php?mkwbc3mipse30xq

**Comment by iBotPeaches** [comment]
https://code.google.com/p/android-apktool/issues/detail?id=534
