### ISSUE TITLE
references broken in AndroidManifest.xml due to public.xml

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#636]
Original [issue 526](https://code.google.com/p/android-apktool/issues/detail?id=526) created by metsman83 on 2013-10-13T06:19:35.000Z:

 > <b>What steps will reproduce the problem?</b>
1.Decompile Google Keyboard APK
2.Recompile apk with or without changes.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Expected a recompiled usable apk, similar to when I run same commands to Android(Nexus) Keyboard. Instead I get tons of errors stateing cannot find res identifier.

<b>What version of the product are you using? On what operating system?</b>
1.5.2 and Windows 7 64bit

<b>Please provide any additional information below.</b>
This issue was touched on in topic #&nbsp;252. It is a somewhat old post and not extremly clear. I have tried doing what was suggested several times and cant get the command to work or the apk to recompile. The steps I took are:
1)apktool d com.google.android.inputmethod.latin-1.apk
2)changed package name in manifest to:&quot;com.android.inputmethod.latin&quot; (removing &quot;google&quot;)

FYI-Not sure if it matters but apktool.yml reads:
version: 1.5.2
apkFileName: com.google.android.inputmethod.latin-1.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '17'
packageInfo:
  cur_package: android
  orig_package: com.google.android.inputmethod.latin
compressionType: false

3)I think this is where Im running into problems. I tried the following 3 commands:
apktool b com.google.android.inputmethod.latin --rename-manifest-package 

apktool b com.google.android.inputmethod.latin --rename w/ original_package

apktool b com.google.android.inputmethod.latin --rename w/ com.google.android.inputmethod.latin

Nothing seems to work. All it does is rename the file. Im pretty new to this and apoligize for the potentially stupid questions. If someone could help that would be amazing! Not sure if this fix is being worked into 2.0, I really hope so!

**Comment by iBotPeaches** [comment]
Started working on this. Basically on rebuild we check the `AndroidManifest.xml` for any `android:authorities` attribute that has an `@string` reference. We then follow that reference for the literal value and replace it.

Two problems

1. The string cannot be found.
2. Sometimes mutliple `@string` references are in the attribute value. I found this 

> A list of one or more URI authorities that identify data offered by the content provider. Multiple authorities are listed by separating their names with a semicolon. To avoid conflicts, authority names should use a Java-style naming convention (such as com.example.provider.cartoonprovider). Typically, it's the name of the ContentProvider subclass that implements the provider

> There is no default. At least one authority must be specified.

**Comment by orilentz** [comment]
Hey,
I think I'm come across the same problem with the latest version (2.1.1) with the following app (CareZone): https://drive.google.com/file/d/0Bzicg_adEUDMVTgyNWYtbHppUEU/view?usp=sharing

I've had this problem with another app prior to 2.0 which fixed it, so I think it's something else. I've copied the value of the `<provider android:authorities` string from _values/string.xml_ and then it worked fine.

Thanks.
