### ISSUE TITLE
Can't find framework resources for package of id: 0

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#699]
Original [issue 589](https://code.google.com/p/android-apktool/issues/detail?id=589) created by loogeo@163.com on 2014-01-13T13:36:54.000Z:

> 1. framework-res.apk just a normal framework.
> 2. It can decode complete by apktool version 1.5.2

I: Using Apktool 2.0.0-Beta8 on framework-res.apk
I: Loading resource table...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Can't find framework resources for package of id: 0. You must install proper fra
mework files, see project website for more info.

**Comment by avborik** [comment]
Hi there, thank you for your app, it is amazing. but I got an error and i have no any idea how to fix it. The app is call recorder for huawei. For some reason it is not working on Android 10 and I want to decompile it, changes the sdk version and compile it again. However I cant decompile it. First I thought that the might be problems with my versions of adb, jadx and apktool. I reinstalled it but I am still receiving this 
Here is the .apk
[HwCallRecorder-1.zip](https://github.com/iBotPeaches/Apktool/files/4509675/HwCallRecorder-1.zip)
error.
 Error message:
Using Apktool 2.4.1 on HwCallRecorder-1.apk
I: Loading resource table...
I: Decoding Shared Library (androidhwext), pkgId: 2
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x90068020000.
W: Invalid config flags detected. Dropping resources: string-pl-ERR0
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D0082020000.
W: Invalid config flags detected. Dropping resources: string-pl-ERR1
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000FA000000.
W: Invalid config flags detected. Dropping resources: string-pl-ERR2
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000D4020000.
W: Invalid config flags detected. Dropping resources: string-pl-ERR3
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D00E7030000.
W: Invalid config flags detected. Dropping resources: string-ro-ERR4
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000FA000000.
W: Invalid config flags detected. Dropping resources: string-ro-ERR5
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000D4020000.
W: Invalid config flags detected. Dropping resources: string-ro-ERR6
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D0068020000.
W: Invalid config flags detected. Dropping resources: string-fr-ERR7
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D00F4020000.
W: Invalid config flags detected. Dropping resources: string-fr-ERR8
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000FA000000.
W: Invalid config flags detected. Dropping resources: string-fr-ERR9
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D00D4020000.
W: Invalid config flags detected. Dropping resources: string-es-ERR10
W: Config flags size > 56. Size = 68. Exceeding bytes: 0x6D00E7030000.
W: Invalid config flags detected. Dropping resources: string-es-ERR11
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000FA000000.
W: Invalid config flags detected. Dropping resources: string-es-ERR12
W: Config flags size > 56. Size = 68. Exceeding bytes: 0xE000D4020000.
W: Invalid config flags detected. Dropping resources: string-es-ERR13
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\avbor\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=src, value=0x02030033
W: Could not decode attr value, using undecoded value instead: ns=android, name=color, value=0x020501a2
W: Could not decode attr value, using undecoded value instead: ns=androidhwext, name=preferenceID, value=0x7f0b002b
I: Decoding values */* XMLs...
Can't find framework resources for package of id: 2. You must install proper framework files, see project website for more info.
Process exited with code 1.

**Comment by AlekKras** [comment]
I have the same issue with apktool right now.

**Comment by Prn-Ice** [comment]
Similar issue, 
```sh
I: Using Apktool 2.5.0 on ThemeManager.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (miui.system), pkgId: 18
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/havoc/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d003f
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0003
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x1002001f
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d0056
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d008d
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d008f
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x100d008f
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0004
W: Could not decode attr value, using undecoded value instead: ns=android, name=src, value=0x10020010
W: Could not decode attr value, using undecoded value instead: ns=android, name=background, value=0x1002006d
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0003
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x100d0078
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d0088
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_single_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_single_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0003
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0003
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0003
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=textSize, value=0x100a0000
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d004f
W: Could not decode attr value, using undecoded value instead: ns=miui, name=name, value=0x00000007
W: Could not decode attr value, using undecoded value instead: ns=miui, name=level, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=miui, name=name, value=0x0000000a
W: Could not decode attr value, using undecoded value instead: ns=miui, name=minLevel, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=, name=style, value=0x100d004e
W: Could not decode attr value, using undecoded value instead: ns=android, name=src, value=0x1001006a
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_h, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x10020063
I: Decoding values */* XMLs...
Can't find framework resources for package of id: 16. You must install proper framework files, see project website for more info.
```

**Comment by s1nistr4** [comment]
Do not know why this is closed, it is still an issue with many apks

**Comment by iBotPeaches** [comment]
> Do not know why this is closed, it is still an issue with many apks

Its locked now and will remain closed.

1. Not a single response to this thread was the actual original issue, which was pkgId 0 - which proved to be a flaw in Apktool. Every non-zero error is because framework files weren't installed.
2. 1/2 of the responses here don't even include a stacktrace to confirm/deny.
3. This is from 2015

I'd recommend filing a new issue following the template vs unhelpful generic call-outs on very old issues.
