### ISSUE TITLE
Large numbers in manifest casted to int, overflow MAX_INT

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#767]
Original [issue 657](https://code.google.com/p/android-apktool/issues/detail?id=657) created by lvs.tourist on 2014-07-15T23:32:13.000Z:

<b>What steps will reproduce the problem?</b>
1. Disassemble a Corona SDK apk file
2. Rebuild it

<b>What is the expected output? What do you see instead?</b>
A correct APK should be built.

<b>What version of the product are you using? On what operating system?</b>
Apktool v1.5.2, Mac OS X 10.9.2

There are two problems inside AndroidManifest.xml
1. For some reason package name is wrong and set to &quot;com.ansca.corona&quot;.
2. If Google Play Game Services are used, APP_ID is treated as number, but should be a string. The solution is to prepend the ID with an escaped space character.

&lt;meta-data android:name=&quot;com.google.android.gms.games.APP_ID&quot; android:value=&quot;\ 555555555555&quot;/&gt;

After that everything is fine.

**Comment by simtel12** [comment]
I'd like to take a crack at this - I think the place to start is brut.apktool/apktool-lib/.../AXmlResourceParser.java:m_attributes; is that correct?

**Comment by simtel12** [comment]
After a little more investigation: 

Meta-data does not support large numbers in Android.  It is not possible to read Long values from the metadata bundle - they are stored as integers with all the limitations that integers have.  Dumping the values via ```aapt l -a <apk>``` shows the same behavior - the value is already truncated.

Example:

Having a metadata in the manifest like this:

```   <application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@android:style/Theme.Holo.NoActionBar.Fullscreen">

        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="555555555555"/>
```
Leads to an aapt listing like this:
```
$ aapt l -a iap-sample-app-release.apk 
.
.
.
      E: meta-data (line=31)
        A: android:name(0x01010003)="com.google.android.gms.games.APP_ID" (Raw: "com.google.android.gms.games.APP_ID")
        A: android:value(0x01010024)=(type 0x10)0x59b108e3
```

This leads me to believe that all (type 0x10) values have a hard limit of MAX_INT, and the values get truncated when the apk is build initially.  I don't believe there is anything that Apktool can do about them.

Another case to consider is if the user modifies the decoded manifest and adds the too-large values there.  I haven't yet checked what happens in this case, but it's probably a good idea to at least spit out a warning if not an error.  Thoughts?

**Comment by iBotPeaches** [comment]
Very interesting research. I was gonna say, "well lets check the apk and see how it works", but there is no apk.

If I create an `INT`  in `<meta-data>` that exceeds `MAX_INT`. `AAPT`, as shown above, truncates it. I need to do more testing involving running said application and seeing if the value is parsed correctly on device or malformed during compilation from source -> binary.

**Comment by simtel12** [comment]
It is truncated in-application as well.  Using the following block, the value is truncated when read.  It is not possible to use ```bundle.getLong()``` due to a cast exception.

```
try {
    ApplicationInfo ai = getPackageManager().getApplicationInfo(activity.getPackageName(), PackageManager.GET_META_DATA);
    Bundle bundle = ai.metaData;
    int myApiKey = bundle.getInt("com.google.android.gms.games.APP_ID");
} catch (NameNotFoundException e) {
    Log.e(TAG, "Failed to load meta-data, NameNotFound: " + e.getMessage());
} 
```

**Comment by iBotPeaches** [comment]
Thanks a ton for this research @simtel12 

It appears this is a limitation in AOSP itself and nothing apktool can aim to fix. I might whip up a test apk just to log it into the system for records, but you've done the research and proof. Thanks!

**Comment by MarcMil** [comment]
Hi there,
I have an APK here similar to that one specified in the previous post.

AAPT reports
```
      E: meta-data (line=31)
        A: android:name(0x01010003)="com.google.android.gms.appstate.APP_ID" (Raw: "com.google.android.gms.appstate.APP_ID")
        A: android:value(0x01010024)="479116460380" (Raw: "479116460380")
```

So the value is really the String "479116460380" and not the number as integer.
APKTool should, instead of outputting
```
        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="479116460380" />
        <meta-data android:name="com.google.android.gms.appstate.APP_ID" android:value="479116460380" />
```
Should be escaped e.g. like this:
```
        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003479116460380" />
        <meta-data android:name="com.google.android.gms.appstate.APP_ID" android:value="\u0034479116460380" />
```
according to https://developer.android.com/guide/topics/manifest/meta-data-element.html

Afterwards, aapt builds a manifest identical to the manifest of the source apk file.

**Comment by MarcMil** [comment]
More research: It is sufficient to escape the value by prepending "\ " (slash and space). If you do that, aapt will consider it a string value and write it out as a string value without the slash and space, thus solving the problem.
So what should apktool do?
If it sees a String value (TYPE_STRING, 0x03) AND the value of the string corresponds to an integer number (or float number also btw), it should prepend "\ " without the quotes to the attribute value, so that
        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 479116460380" />
Otherwise aapt treats it as an integer value and writes it as integer value (TYPE_INT_DEC), which is wrong.
So this is clearly an apktool issue; aapt cannot know that it is not meant to be an integer.

**Comment by iBotPeaches** [comment]
Thanks for the large amount of research on this. That looks simple enough to do.

**Comment by iBotPeaches** [comment]
```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug767$ apktool d com.smgstudio.onemoreline.apk -f
I: Using Apktool 2.0.3-831765-SNAPSHOT on com.smgstudio.onemoreline.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug767$ cat com.smgstudio.onemoreline/AndroidManifest.xml | grep 'APP_ID'
        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 479116460379"/>
        <meta-data android:name="com.google.android.gms.appstate.APP_ID" android:value="\ 479116460379"/>
ibotpeaches@tombstone:~/Downloads/Apktool/Bug767$ 
```

Works great. Thanks for the research. Doing some profiling to make sure my changes doesn't slow anything down too much (since the change is on the `ResString`)
