### ISSUE TITLE
Error: Resource is not public. (at 'notification_subtext_size' with value '@android:dimen/notification_large_icon_circle_padding').

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#810]
Original [issue 701](https://code.google.com/p/android-apktool/issues/detail?id=701) created by c7syan on 2014-11-07T23:34:07.000Z:

> This error occurred when use the apk tool to build the apk. The original APK works, and the original APK was decoded using apk tool, then build using the same apk tool.

Android 4.4.2 API level 19
Apk tool: 2.0.0_CR (Latest)

No stack trace for error message, only message is:
E:\Android\TestApk\res\values-v17\dimens.xml:3: error: Error: Resource is not public. (at 'notification_subtext_size' with value '@android:dimen/notification_large_icon_circle_padding').

**Comment by Aaahh** [comment]
Running into this, and can't seem to find the solution

**Comment by iBotPeaches** [comment]
You are using private resources. You can't, as they will change between platform releases. You have to move private resources into your own application package and reference them that way.

**Comment by Aaahh** [comment]
Yeah I retried the @*android thing again and it worked, I don't know why it didn't before. 

I plan to ship the app with the system so that won't be a problem, thanks!

**Comment by idrisbohra** [comment]
Hi @Aaahh, can you please share the "@*android thing" code as i am having the same problem.

**Comment by Aaahh** [comment]
@idrisbohra 
So every resource that errors out, you replace @android with @*android

**Comment by hanchan112** [comment]
'So every resource that errors out, you replace @android with @*android'!
Yeah, it is a good solution. It works at least for app of mine.
Thanks!

**Comment by Linkz31** [comment]
Can you help me?  I changed the file string.xml an apk and suddenly it refuses compilation supposedly error: resource android/Idingo_800 is private
Do you have a solution to help me?

**Comment by pich4ya** [comment]
To fix this, go to the /res/values-vxx/xxx.xml file that is returned from the error message.

Replace all @android with @*android. Then, apktool b it once again !!
