### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#813]
Original [issue 704](https://code.google.com/p/android-apktool/issues/detail?id=704) created by yeweipeng on 2014-11-14T19:23:40.000Z:

> <b>What steps will reproduce the problem?</b>
> 1../apktool d www.apk
> 2../apktool b www/
> 3. error
> Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/brut_util_Jar_6336319417890230835.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 16, --version-code, 501, --version-name, 6.0.0.56_r856074, -F, /var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/APKTOOL3828683629041501515.tmp, -0, arsc, -I, /Users/max/Library/apktool/framework/1.apk, -S, /Users/max/Desktop/apktool-macosx/www/res, -M, /Users/max/Desktop/apktool-macosx/www/AndroidManifest.xml]
>     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:449)
>     at brut.androlib.Androlib.buildResources(Androlib.java:383)
>     at brut.androlib.Androlib.build(Androlib.java:286)
>     at brut.androlib.Androlib.build(Androlib.java:258)
>     at brut.apktool.Main.cmdBuild(Main.java:240)
>     at brut.apktool.Main.main(Main.java:89)
> Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/brut_util_Jar_6336319417890230835.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 16, --version-code, 501, --version-name, 6.0.0.56_r856074, -F, /var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/APKTOOL3828683629041501515.tmp, -0, arsc, -I, /Users/max/Library/apktool/framework/1.apk, -S, /Users/max/Desktop/apktool-macosx/www/res, -M, /Users/max/Desktop/apktool-macosx/www/AndroidManifest.xml]
>     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:487)
>     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:434)
>     ... 5 more
> Caused by: brut.common.BrutException: could not exec command: [/var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/brut_util_Jar_6336319417890230835.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 16, --version-code, 501, --version-name, 6.0.0.56_r856074, -F, /var/folders/w_/cvfs48z107l0czjbf51cv1sh0000gn/T/APKTOOL3828683629041501515.tmp, -0, arsc, -I, /Users/max/Library/apktool/framework/1.apk, -S, /Users/max/Desktop/apktool-macosx/www/res, -M, /Users/max/Desktop/apktool-macosx/www/AndroidManifest.xml]
>     at brut.util.OS.exec(OS.java:89)
>     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:481)
>     ... 6 more

<b>What version of the product are you using? On what operating system?</b>
apktool_2.0.0rc2.jar . Mac OX 10.10

**Comment by MarcMil** [comment]
Yes, that is aapt's fault.
I have opened an issue on AOSP:
https://code.google.com/p/android/issues/detail?id=163364&thanks=163364&ts=1428416235

**Comment by hao-opentown** [comment]
any workaround for this aapt bug?

**Comment by MarcMil** [comment]
Please add yourself to the "wants to be notified" list so that the AOSP team knows that at least some more people are interested in this.
For now, you can patch the code directly. Sadly I do not remember the file name of that particular code location exactly, but it's fairly easy to find it in the aapt directory.
