### ISSUE TITLE
sucessfully recompiled app not working at all

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#872]
Original [issue 763](https://code.google.com/p/android-apktool/issues/detail?id=763) created by hasankasir on 2015-02-18T16:59:33.000Z:

<b>What steps will reproduce the problem?</b>
1. whatsapp plus reborn 1.50
2.decompile sucessfully
3. compile sucessfully
4. installed normally
5. enteres and then exits immedietly. 
no crash message 
no changes where done yet...
<b>What is the expected output? What do you see instead?</b>
I expected a working app :)

<b>What version of the product are you using? On what operating system?</b>

rc3 and rc4  no difference same issue
<b>Please provide any additional information below.</b>
This app has extra lollipop support maybe this made a conflict to the apktool?

**Comment by hasankasir** [comment]
thanks for re locating the issue to github after moving...
still no solution for that app...
If you need the links again provided are not working
The old logcat:
https://storage.googleapis.com/google-code-attachments/android-apktool/issue-763/comment-3/reblogcat.txt
The link for the apk :
http://hasankasir.com/WA/WAR150R.apk
Knowing that this issue isn't important to me as much as decompiling and building successfully
the more recent version that gives on building : 
Error retrieving parent for item: No resource found that matches the given name
knowing that no changes were done...
http://hasankasir.com/WA/WAR180R.apk

**Comment by hasankasir** [comment]
The issue is now solved...
It was from the damn file 
C:\Users\%my username%\apktool\framework\1.apk
that was automatically generated from previous project when I used apktool therefore
I had to delete it before any new project then the resources are well generate and linked and the app launched successfully...

**Comment by iBotPeaches** [comment]
Glad you solved it. :)
