### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Multiple res specs: attr/name

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#894]
Original [issue 785](https://code.google.com/p/android-apktool/issues/detail?id=785) created by sh37092 on 2015-03-17T03:26:48.000Z:

<b>What steps will reproduce the problem?</b>
1.Decode mobileqq_android.apk
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
I: Using Apktool 2.0.0-RC4 on mobileqq_android.apk
I: Loading resource table...
```
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: Multiple res specs: attr/name
	at brut.androlib.res.data.ResType.addResSpec(ResType.java:58)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:213)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:113)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:622)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
	at brut.androlib.Androlib.getResTable(Androlib.java:63)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

<b>What version of the product are you using? On what operating system?</b>
Apktool 2.0.0-RC4 on MacOSX with Java 1.8_40

<b>Please provide any additional information below.</b>
You can download mobileqq_android.apk from http://down.myapp.com/myapp/qqteam/AndroidQQ/mobileqq_android.apk

**Comment by BobCromwell** [comment]
met same issue

**Comment by iBotPeaches** [comment]
@BobCromwell Do you have an apk to upload? The more apks of the similar issue I can get the better.

**Comment by amir1111** [comment]
i have 2 apks like this, compressed them to this link - http://www.filedropper.com/multipleres

**Comment by iBotPeaches** [comment]
Yes, both of those APKs exhibit the same problem.

**Comment by moqi2011** [comment]
met same issue [QQ.apk](http://106.185.47.75/f/QQ.apk)

**Comment by mooreliu** [comment]
Does this problem solved ?

**Comment by illuminator0723** [comment]
How to debug apktool myself?

**Comment by paulobrien** [comment]
I have the same issue with this SystemUI.apk (frameworks are also included):

http://content.modaco.net/dropzone/h7systemuibug.zip

P

**Comment by iBotPeaches** [comment]
Having some trouble extracting this.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug894$ unzip h7systemuibug.zip 
Archive:  h7systemuibug.zip
error [h7systemuibug.zip]:  missing 266 bytes in zipfile
  (attempting to process anyway)
error [h7systemuibug.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
  inflating: framework-res.apk       
  error:  invalid compressed data to inflate
file #2:  bad zipfile offset (local header sig):  8641411
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  8641411
file #3:  bad zipfile offset (local header sig):  19368381
ibotpeaches@tombstone:~/Downloads/Apktool/Bug894$ md5sum h7systemuibug.zip 
c36934e9203a48665bc4e8cb361028c3  h7systemuibug.zip
```

**Comment by paulobrien** [comment]
Not sure what happened there!

Reuploaded:

http://content.modaco.net/dropzone/h7systemuibug.2.zip

Thanks for your help. :) This is from the Honor 7 however (Huawei based), which could be the cause of the problem!

P

**Comment by iBotPeaches** [comment]
Yeah these apks have qualifiers that apktool does not know about.

`opta#` and `optb#`. Which causes all the strange errors, which isn't exactly the same as OP issue. Short of reverse engineering, I have no idea what these qualifiers serve, which makes it difficult to support, if at all. I believe this then is the same problem as in #836

**Comment by Henry2o1o** [comment]
here the same problem

LBE Security Master
https://drive.google.com/file/d/0B4Uzb0COihYbMnhYVzI3RVdXR3M/view?usp=sharing

**Comment by 13572293130** [comment]
The reason for "Exception in thread "main" brut.androlib.AndrolibException: Multiple res specs:
attr/0" is: res directory name and file name is proguarded. reference to  http://bbs.pediy.com/showthread.php?p=1308494

**Comment by iBotPeaches** [comment]
Started researching this. Most resources have the same key as shown

```
      spec resource 0x7f010000 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010001 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010002 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010003 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010004 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010005 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010006 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010007 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010008 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f010009 com.tencent.mobileqq:attr/name: flags=0x00000000
      spec resource 0x7f01000a com.tencent.mobileqq:attr/name: flags=0x00000000
```

Apktool stores based on `type/key_name`. This should be unique, but this proves otherwise. Hence the "double resource" errors. Anything on device goes by `resourceId`, so this doesn't cause a problem.

For apktool however, it does. I did a quick n dirty patch with Dexguard by just creating unique key names (https://github.com/iBotPeaches/Apktool/commit/f9323943db1776aad4d06862011ea2aea2416bfc). Since the only place the human readable key name is used is resources, we know the dummy value name from the resourceId, so this doesn't break anything.

The correct fix may be as follows.

1. If the `key_name` is `null` or `empty`, then replace with a dummy value that is unique. IE (`APKTOOL_DUMMYVAL_{HEXID}`).

2. If the `key_name` is not empty, but a duplicate occurs. Append a number onto the end (Probably resourceId) to prevent having to keep track of a counter.

3. During build, resources are followed to `resourceIds` which haven't changed so built apk should have the same functionality as original. Granted the decode application will look different, but the real key names have been destroyed/obfuscated/removed/something by Dexguard and other Obfuscation apps so we can't really ever use them.

4. Or maybe we are attacking this problem wrong and apktool shouldn't check for unique key names, but then we still have the problem of writing duplicate `key_names` in human readable form.

**Comment by SetoKaiba** [comment]
I build apktool from master branch. It should include the f9323943db1776aad4d06862011ea2aea2416bfc commit. But it still failed with com.tencent.mobileqq.

**Comment by iBotPeaches** [comment]
It shouldn't work with that commit. `com.tencent.mobileqq` has multiple names of the same word. The fix was for resources that had no name (ie empty). 

A fix to detect current resources and detect duplicates and avoid them by adding uniqueness needs to be added.

**Comment by SetoKaiba** [comment]
Thanks. I see. I misunderstood your words.

**Comment by donly** [comment]
See this Chinese blog please, http://www.mak-blog.com/tencent-shell-crack.html

**Comment by iBotPeaches** [comment]
Thanks @donly 

Looks like 3 separate issues at hand here. I'll try and get the `dex` files to the smali project to confirm if those patches will work for that issue. Then I already have a duplicate resource patch underway.

These fixes won't make the 2.0.3 release today, but should make 2.1.0.

**Comment by proninyaroslav** [comment]
@iBotPeaches 
When approximately wait 2.1.0 with fix?

**Comment by iBotPeaches** [comment]
Well the fix hasn't happened yet, so no idea. My releases tend to be 2-3 months apart and I just released 2.0.3 on 12/31/2015 so probably in late February or early March.

**Comment by lucca2011** [comment]
how to fix this problem now?

**Comment by VicV** [comment]
@iBotPeaches Giving you another ping on this one. :)

**Comment by iBotPeaches** [comment]
Sorry for delay on this issue. I've spent the past few days really working on it, and I can't seem to get rebuilding working yet, but decoding works. I'll get that pushed out here shortly.

```
➜  Bug894 apktool d mobileqq_android.apk -f
I: Using Apktool 2.2.0-e1dd43-SNAPSHOT on mobileqq_android.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

I've decided due to impending release of Android Nougat and the possibility that aapt2 (The 2nd iteration of aapt) will be out and thus changing the entire build side of apktool, I shouldn't spend too much time patching build support into a soon to be deprecated aapt binary.
