### ISSUE TITLE
apktool building fail: isAaptInstalledTest FAILED

### ISSUE THREAD

**Issue by aapo** [iBotPeaches/Apktool#900]
Issue when compiling Apktool on 64bit-Linux.

     git clone git://github.com/iBotPeaches/Apktool.git
     cd Apktool
     ./gradlew
     ./gradlew build fatJar

Ends with:

    Building SNAPSHOT (master): 9c874a
    (snip)
    
    :brut.apktool:apktool-lib:test
    brut.androlib.AaptTest > isAaptInstalledTest FAILED
    java.lang.AssertionError: expected:<true> but was:<false>
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.failNotEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:128)
        at org.junit.Assert.assertEquals(Assert.java:147)
        at brut.androlib.AaptTest.isAaptInstalledTest(AaptTest.java:38)
    
    52 tests completed, 1 failed
    :brut.apktool:apktool-lib:test FAILED
    (snip)
    BUILD FAILED

----
I read the source code of AaptTest.java and used successfully:

    TRAVIS=TRUE ./gradlew build fatJar

This was not documented, so I think this was not intented.

**Comment by iBotPeaches** [comment]
The environmental variable `TRAVIS` is for our continuous integration to skip the test there. On older versions of apktool you were required to have `aapt` (Android Asset Packaging Tool) in your `$PATH`.

Or more simply. You have to be able to execute `aapt` from CLI and have it run without errors. This is what that unit test is checking for. After we merged internal aapt's into the apktool jar, this test was no longer needed but I never removed it.

**Comment by aapo** [comment]
Now I understand. And it is documented in: http://ibotpeaches.github.io/Apktool/build/

    Requirements:    aapt in $PATH (Android Asset Packaging Tool)

So remove it from documentation too.

**Comment by raziel23x** [comment]
it is there because the 1.x version uses it and many users still use that version is why it has not been removed.

once 2.0 is officially released i am sure the documentation will be updated
