### ISSUE TITLE
Mutiple Dex Issue. classes2.dex file is missing

### ISSUE THREAD

**Issue by mingqlin** [iBotPeaches/Apktool#904]
To reproduce:
Run following command on a apk contain mutiple dex files.

1. Decompile with -s option
java -jar apktool.jar decode -s -f mutidex.apk -o C:\mutidex_source1

Result, in folder mutidex_source1, there are classes.dex, and classes2.dex, this is correct result
2. Compile the mutidex_source1 into apk
Java.exe -jar apktool.jar b C:\mutidex_source1 -o  c:\mutidex_source1.zip
open the result mutidex_source1.zip, inside there is only classes.dex. classes2.dex file is missing.

**Comment by iBotPeaches** [comment]
Duplicated. Will get fix out soon.
