### ISSUE TITLE
Building System application application Rumtimeerror

### ISSUE THREAD

**Issue by Hyundongs** [iBotPeaches/Apktool#907]
I was tried to decompile & rebuild SystemUI application.(AOSP)
when i use below command
"apktool d SystemUI.apk" & "apktool b System.apk"
(i already install framework-res.apk)

error message is occured "File  M14.0,20.0l10.0,10.0 10.0,-10.0z  from drawable resource ID #0x0 .xml extension required" 

"M14.0,20.0l10.0,10.0 10.0,-10.0z" is for vector animation.
Reference Code : http://androidxref.com/5.1.0_r1/xref/frameworks/base/packages/SystemUI/res/drawable/qs_subhead_caret.xml#24

 M14.0,20.0l10.0,10.0 10.0,-10.0z is not a file just value for VectorDrawable, but resource framework process it as a file....

If i use -r (no-res decompile )option, it works well....

I knew that VectorDrawable class is updated in Android L. 
Is there any problem with this, when building application?

If someone know about this problem, let me know....

**Comment by iBotPeaches** [comment]
Can you upload the apks? So I can investigate myself?

**Comment by iBotPeaches** [comment]
Will re-open if APK provided.
