### ISSUE TITLE
Rebuilding .APK with APKTOOL, changing names.

### ISSUE THREAD

**Issue by bartoshe** [iBotPeaches/Apktool#909]
I was thinking about creating a generic .APK to "play" some scripted own files, with renaming activity and java classes names from a base .APK
In my case, manifest and activity classes and inside must be renamed, so I've tried APKTOOL. depacking the APK works, repacking it too, it works, but when I change names and Inside "smali"s too, it can be installed but app crashes at start.

**Comment by iBotPeaches** [comment]
This is for bug reports. Not support. You have to resign apk.
