### ISSUE TITLE
apktool do not work

### ISSUE THREAD

**Issue by pisota** [iBotPeaches/Apktool#910]
I try to use apktool ,and run "apktool d" command ,and it don't work.Please see the attachment,thank you. I can not upload files Crackme0201.apk ,so I renamed Crackme0201.apk  to Crackme0201.jpg and help you find the problem.

![apktool_crashed](https://cloud.githubusercontent.com/assets/976255/7135206/d1fa8450-e2d6-11e4-9349-7368a6213220.jpg)

![apktool crashed](https://cloud.githubusercontent.com/assets/976255/7135160/7dd3ca6c-e2d6-11e4-87fd-d35cd520fb0f.jpg)

![crackme0201](https://cloud.githubusercontent.com/assets/976255/7135286/a06b7812-e2d7-11e4-8d42-5c11755b74d1.jpg)

**Comment by iBotPeaches** [comment]
Clever way to upload that!

In the latest source I could not duplicate. See below text.

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug910$ apktool d a06b7812-e2d7-11e4-8d42-5c11755b74d1.apk 
I: Using Apktool 2.0.0-ae15b2-SNAPSHOT on a06b7812-e2d7-11e4-8d42-5c11755b74d1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug910$ apktool b a06b7812-e2d7-11e4-8d42-5c11755b74d1
I: Using Apktool 2.0.0-ae15b2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
ibotpeaches@raganok:~/Downloads/Apktool/Bug910$ 
```

I would recommend reading this: http://ibotpeaches.github.io/Apktool/documentation/#framework-files
