### ISSUE TITLE
Recompiling specific applications breaks them?

### ISSUE THREAD

**Issue by IaguCool** [iBotPeaches/Apktool#915]
Using:
Windows 7 SP1 64-bit
JRE 1.7
Apktool v2.0.0 RC4

APK + framework:
https://mega.co.nz/#!HM4BwYIb!pdOZ5vOX4Hn4Yp-nKiE2WeXFSAkDZ84vtpQ-m7V32ww

Replacing original APK in system/priv-app after...
* Only re-sign & zipalign the APK --- Works [proves this isn't a signature-related issue]
* Decompile and recompile the APK (original signature) --- ActivityNotFoundException
* Decompile and recompile the APK + sign + zipalign --- ActivityNotFoundException

Trying to install as normal APK after...
* Decompile and recompile the APK + sign + zipalign --- Package manager shows "Parse error: There was a problem parsing the package."

Logcat:
http://www.iagucool.com/socialphonebook_error.txt

NOTE: The application disappears from the drawer, so to get this exception I used a home-screen icon on Nova Launcher, which doesn't disappear when you uninstall an application. When clicking the icon, a toast notification shows "App isn't installed".

**Comment by iBotPeaches** [comment]
So I haven't tested things yet, just did a preliminary check. I decoded the apk, rebuilt it, then decoded the rebuilt app. I then compared those two folders to check for differences.

A couple of values in `public.xml` got order changed, but `resID` stayed the same so that isn't yet. The only other thing missing is two files in `META-INF` called

* `SONY-ERICSSON-E-SHARED-SIGNING-LIVE-864F-4.RSA`
* `SONY-ERICSSON-E-SHARED-SIGNING-LIVE-864F-4.SF`

Is it possible those files are dependent on the installation? Not entirely sure. I also think the problem could be related to #636 which I almost have fixed. So hold tight, I will do some more testing.

**Comment by IaguCool** [comment]
No, those are the original Sony signatures. When you only re-sign the APK, those signatures are replaced, and the APK works perfectly. It's only when you decompile and recompile that the APK fails to even be parsed by Android. Like you, I have recompiled and decompiled again to compare what might have been broken, and haven't found anything of an issue, that's why I'm here XD
I've the feeling that you are right about the #636 issue, hope it gets fixed. If there's anything I could do to help I'd be glad to, even though I know basic Java while pretty good at C#.

**Comment by iBotPeaches** [comment]
Okay I'm 1-2 days away from fixing #636, so let me do that. Then I will test this against that fix.]

It has a `<provider>` in the manifest that fits the exact description of the mentioned bug. So this could be it.

```
        <provider android:authorities="@string/fileprovider_authority" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"/>
        </provider>
```

**Comment by IaguCool** [comment]
Hmm very possible... by the way, decompiling, moding and recompiling SystemUI.apk from the same ROM worked smoothly. So yeah, this must be some kind of referencing problem. (SystemUI doesn't have any "android:authorities" attributes)

**Comment by IaguCool** [comment]
Changing android:authorities="@string/fileprovider_authority" to its literal android:authorities="com.sonyericsson.android.socialphonebook.fileprovider" and recompiling seem to make the APK installable again.

**Comment by iBotPeaches** [comment]
Sweet! So it was related to 636. Good thing I have that fixed here: https://github.com/iBotPeaches/Apktool/pull/911

Just needs a bit more testing.

**Comment by IaguCool** [comment]
Anywhere to get the fixed apktool.jar? I tried to download the ZIP of the project and build it myself, but it seems the fix isn't implemented there.
