### ISSUE TITLE
Files extraction problem

### ISSUE THREAD

**Issue by Furniel** [iBotPeaches/Apktool#921]
Apktool 2.0.0 don`t extracts files without extension. For example Google Play Services raw folder contains:
gtm_analytics
indexes.txt
maps_dav_k2.bin
oss_notice.txt
pinyins.txt
pulsar_key_file

Latest version of apktool don`t extracts **gtm_analytics** & **pulsar_key_file** but creates **raws.xml** in values folder:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item type="raw" name="gtm_analytics">res/raw/gtm_analytics</item>
    <item type="raw" name="pulsar_key_file">res/raw/pulsar_key_file</item>
</resources>
```
Apk can`t be compiled without manual adding of this files and removing raws.xml.

**Comment by iBotPeaches** [comment]
If by `raw` you mean `res/raw`. I haven't touched that block of code in a long long time, but then again I have no unit-test for a no extension file there.

I've also never heard of `aapt` creating a `raws.xml` file. Basically, I need to investigate this. Thanks for the tip!

**Comment by iBotPeaches** [comment]
This is regression from here: https://github.com/iBotPeaches/Apktool/commit/bbc60230689b423eb027eaf80f26efc762f8a3d9

However, I'm not sure of a fix yet.

`res/foo` in some instances is a string literally named `res/foo`. In the case of many Japanese applications in order to break apktool. The fix above was looking for a `.` in the string, so it could cast it to a `ResFileValue`. This breaks files with no extensions, but there is no way to detect a bogus entry from real one at that point.

Checking if each string exists in the filesystem is slow as hell. Still investigating a proper fix.

**Comment by Furniel** [comment]
I`m not really sure that it will be true for all applications, but at this moment i found files without extension only in raw folder, so maybe we can fix this bug by this code
```
if ((value.startsWith("res/") && value.contains(".")) || value.startsWith("res/raw/")) {
```
and to be sure that it`s not a string we can add something like this:
```
if ((value.startsWith("res/") && value.contains(".")) || value.startsWith("res/raw/")) {
    File f = new File(value); //not sure that we can check if string exists in the filesystem in such way
    if(value.startsWith("res/raw/") && !f.exists()) {
        return new ResStringValue(value);
    }
    else
    {
        return new ResFileValue(value);
    }
}
```

**Comment by iBotPeaches** [comment]
The first fix would work in theory, but then it would be a matter of time until apk authors would adapt their bogus strings to be 'res/raw/foo' and then we are back to a broken apktool.

I think the best fix is for every `ResFileValue` we expect, we check the filesystem for it. It may slow down execution, but it prevents errors. The only problem is at this point in execution we don't have the variables needed to check the filesystem. I will work on a small refactor to adapt this.

**Comment by iBotPeaches** [comment]
Okay, the IO time for checking the filesystem is not an option. I think I'm overthinking this.

I might just wait for the `ClassCastException`, if it exists then we can force a `resStringValue` instead of `resFileValue`.
