### ISSUE TITLE
A group permission error while repackaging the APK

### ISSUE THREAD

**Issue by rex2er** [iBotPeaches/Apktool#923]
currently apktool seems not able to interpret a group permission which is written inside of the manifest xmlfile while only <B>repackging the APK</B> because of '-'

http://developer.android.com/guide/topics/manifest/permission-group-element.html
(im sorry to tell you that i cant attach the sample apk by some personal reasons)

highly appreciate your effort. thanks in advance!
-Rex

**Comment by iBotPeaches** [comment]
I'm having troubles understanding what you are saying.

Are you saying if I add this to the `AndroidManifest.xml`

```
<permission-group android:description="Foo"
                  android:icon="@image/reference"
                  android:label="@string/reference"
                  android:name="value" />
```

Then on decode this is lost?

**Comment by rex2er** [comment]
what I was trying to say is that if you add the permission-group one to androidmanifest.xml, apktool will successfully be able to decode it but not repackage it with the <b>b</b> option.

**Comment by iBotPeaches** [comment]
Yeah, just tested this. 

I added this

```
    <permission-group android:description="@string/app_name"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:name="value" />
```

in between the `<manifest>` tags. Not in the `<application>` tag and worked fine. Closing as cannot duplicate.
