### ISSUE TITLE
Small visual bug when recompiling AccuWeather

### ISSUE THREAD

**Issue by Silviumik** [iBotPeaches/Apktool#926]
Hello, i noticed a small visual bug when i try to recompile AccuweatherPhone2013.apk without any modifications made to code or pictures
Last version that worked good was apktool_2.0.0rc2 screenshot proving everything is ok 
![screenshot_2015-04-24-16-19-00](https://cloud.githubusercontent.com/assets/8281468/7319539/0b1303be-ea9f-11e4-91b2-1ee5a444056d.png)

apktool_2.0.0rc3 gives error http://pastebin.com/Q7Em2pMd when recompiling
apktool_2.0.0rc4 gives error http://pastebin.com/8DMTk2dZ when recompiling

apktool_2.0.0 final does not give any error but it lacks 4 checkboxes from right side after text if u check both screens u will notice.
![screenshot_2015-04-24-16-22-46](https://cloud.githubusercontent.com/assets/8281468/7319610/663b55fc-ea9f-11e4-80b4-f7270479cfc8.png)

Here are the original odexed Accuweather + framework files https://www.androidfilehost.com/?fid=96042739161892860
If u need anything else let me know pls. Thank u in advance ! :)

**Comment by iBotPeaches** [comment]
Not sure. Decompiling the application, rebuilding it, then decoding it only shows the following difference.

```
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0013">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0040">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0042">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0043">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_009a">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_00c1">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_00c7">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_00eb">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0144">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0159">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_0181">false</item>
res/values-sw360dp-land-hdpi/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_01a9">false</item>
```
A few resources, but strangely those are in `RC2` as well. So I have no idea yet.

**Comment by iBotPeaches** [comment]
I know this bug is very old and I'm sorry about that. I have no way to test this as I don't own a Samsung device, but I believe this patch earlier this year fixes this - https://github.com/iBotPeaches/Apktool/commit/e7b294a3eae8e241be64b89061b0659b1396275f

I'll leave another note here when I release 2.2.0 and then close this off.

**Comment by iBotPeaches** [comment]
Closing as mentioned comment above. Just 4 years too late. 

Sorry we never tracked this down.
