### ISSUE TITLE
Garbage in PATH env var

### ISSUE THREAD

**Issue by Tercete** [iBotPeaches/Apktool#927]
Hi... This is not a bug, but an inconvenient.
When you use this tool many times, it changes the PATH environment variable, appending the actual directory, many times...
To avoid this behavior, I suggest this:
```
@echo off
if "%PATH_BASE%" == "" set PATH_BASE=%PATH%
set PATH=%CD%;%PATH_BASE%;
java -jar -Duser.language=en "%~dp0\apktool.jar" %1 %2 %3 %4 %5 %6 %7 %8 %9
```

Thanks in advance...

**Comment by iBotPeaches** [comment]
Can you explain what the code you added changes? It looks to see if `PATH_BASE` is empty, then set it to `PATH`, but then it just sets `PATH` to current directory + `PATH_BASE`. This doesn't seem to fix the problem by looking at the code.

However, when actually testing it. It does fix it. The `PATH` only gains one iteration of the current directory, thus works. So thanks! I'll get this merged.
