### ISSUE TITLE
Get error from apktool

### ISSUE THREAD

**Issue by lamxung218** [iBotPeaches/Apktool#929]
I cmd gradlew.bat build fatJar then show error, anyone can help me, thanks very much!
![apktool2](https://cloud.githubusercontent.com/assets/11564910/7345362/1ab949fc-ecfe-11e4-89e8-35727c109514.png)

![apktool](https://cloud.githubusercontent.com/assets/11564910/7345338/e1a97434-ecfd-11e4-8e58-5a7a0c86f22d.png)

**Comment by iBotPeaches** [comment]
Remove the file at `~/apktool/framework/1.apk`. Not a bug.

**Comment by lamxung218** [comment]
Hi, thanks very much, I did successfully and get two files: apktool-cli.jar and apktool-2.0.1-dirty-small.jar, but how to use these files, what I use to do? How use to decode file apk.
Thanks.
![apktool13](https://cloud.githubusercontent.com/assets/11564910/7348687/c5bf9922-ed1d-11e4-94c7-55a52ac33013.png)

**Comment by iBotPeaches** [comment]
This isn't a support forum. Please check the project webpage

 http://ibotpeaches.github.io/Apktool/build - Building Guide
http://ibotpeaches.github.io/Apktool/install/ - Install Guide
