### ISSUE TITLE
Can't build Apktool-master

### ISSUE THREAD

**Issue by IaguCool** [iBotPeaches/Apktool#933]
Just what the title says...

org.jf.dexlib2.AccessorTest > testAccessors FAILED
    junit.framework.AssertionFailedError: expected:<12> but was:<1>
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.failNotEquals(Assert.java:277)
        at junit.framework.Assert.assertEquals(Assert.java:64)
        at junit.framework.Assert.assertEquals(Assert.java:195)
        at junit.framework.Assert.assertEquals(Assert.java:201)
        at org.jf.dexlib2.AccessorTest.testAccessors(AccessorTest.java:125)

**Comment by iBotPeaches** [comment]
OS? Java version?

Can't duplicate here.

**Comment by IaguCool** [comment]
Windows 7 SP1 x64
JRE 8 Update 45 (64-bit)

**Comment by iBotPeaches** [comment]
Can you try building this tool? - https://github.com/JesusFreke/smali

Apktool updated to `2.0.6`, which introduced this unit-test which is failing for you. I want to eliminate the possibility that I introduced the problem or if it also resides in the upstream repo.

**Comment by IaguCool** [comment]
Well a while ago I built this branch successfully:
https://github.com/iBotPeaches/Apktool/tree/3208624bf683a982ea8d23aa7d05a249e14c8c3c

**Comment by iBotPeaches** [comment]
Yeah, that doesn't matter much. I merged an entire new upstream version into master, which probably introduced this change.

**Comment by IaguCool** [comment]
Got the same result with the above project:
http://oi59.tinypic.com/242de.jpg

**Comment by iBotPeaches** [comment]
Okay thanks!

Must be a Windows issue with smali.

**Comment by IaguCool** [comment]
Stack Trace:
http://oi57.tinypic.com/122f4zo.jpg

**Comment by iBotPeaches** [comment]
```
:brut.apktool:apktool-lib:processTestResources UP-TO-DATE
:brut.apktool:apktool-lib:testClasses UP-TO-DATE
:brut.apktool:apktool-lib:test UP-TO-DATE
:brut.apktool:apktool-lib:check UP-TO-DATE
:brut.apktool:apktool-lib:build UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:assemble UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:compileTestJava UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:processTestResources UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:testClasses UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:test UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:check UP-TO-DATE
:brut.apktool.smali:dexlib2:accessorTestGenerator:build UP-TO-DATE
:brut.apktool:apktool-cli:fatJarPrepareFiles UP-TO-DATE
:brut.apktool:apktool-cli:fatJar

BUILD SUCCESSFUL

Total time: 58.52 secs
C:\Users\Connor\Desktop\Projects\Apktool>
```

```
:dexlib2:generateAccessorTestDex
:smali:signArchives SKIPPED
:smali:assemble
:smali:build
:dexlib2:processTestResources UP-TO-DATE
:dexlib2:testClasses
:dexlib2:test
:dexlib2:check
:dexlib2:build

BUILD SUCCESSFUL

Total time: 37.211 secs
C:\Users\Connor\Desktop\Projects\smali>
```

This is `Java 1.8.0_31` on Windows 8.1 Pro. Closing as "cannot duplicate".
