### ISSUE TITLE
SecContacts_Phone_OSup_FLAGSHIP_USA liolipop Error

### ISSUE THREAD

**Issue by andriodtaiz** [iBotPeaches/Apktool#938]
after Decoding SecContacts_Phone_OSup_FLAGSHIP_USA.apk 
and Building with this massage 
D:\apktool2>java -jar apktool2.jar d SecContacts_Phone_OSup_FLAGSHIP_USA11.apk
I: Using Apktool 2.0.0 on SecContacts_Phone_OSup_FLAGSHIP_USA11.apk
I: Loading resource table...
I: Decoding Shared Library (touchwiz), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\AL-HIRIWY\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\apktool2>java -jar apktool2.jar b -c SecContacts_Phone_OSup_FLAGSHIP_USA11
I: Using Apktool 2.0.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy META-INF...
I: Building apk file...

and when i try opening this apk 
the error show 
Describe error. There is a problem parsing the package. 
and not working 
i used win 7 64bit jave last ver

**Comment by iBotPeaches** [comment]
Do you have a logcat of the failure of the install? `This is a problem parsing the package` is not a helpful message at all.

Run `adb logcat` during the install of the application. Than post the applicable logs about the failure. You can put three backticks between your log (```) to put it in code mode.

**Comment by andriodtaiz** [comment]
the app is system app in pirv-app folder 
i test the app for trying install it just 
my app should to replace withe the original app in the same folder
my error in all same app of note 3 N900R4 N900T android 5.0

**Comment by iBotPeaches** [comment]
I can't do anything without a logcat. When you get one we can revisit this.

**Comment by andriodtaiz** [comment]
i'm sorry about open new issues 
but the app not working
if jave ver make error when Building app and resources
and anther app working Good in the same Phone
and i have a Q ? 
What did this line main?
I: Decoding Shared Library (touchwiz), pkgId: 2

**Comment by iBotPeaches** [comment]
It means there is a reference to a Shared Library. So it tells you the `packageName` (`touchwiz`), and the `pkgId` - `2`, of the package.

**Comment by andriodtaiz** [comment]
shout to be install touchwiz app 
apktool if 
to read Shared Library

**Comment by MAXIMATOR82** [comment]
Decompile Orig file
I: Using Apktool 2.0.0 on SecContacts_L_Phone_FLAGSHIP_USA.apk
I: Loading resource table...
I: Decoding Shared Library (touchwiz), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MAXIMATOR\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Build FILE
I: Using Apktool 2.0.0
W: Could not find sources
I: Building resources...
warning: string 'guide_call_addcall' has no default translation.
warning: string 'guide_call_endcall' has no default translation.
warning: string 'guide_call_headset' has no default translation.
warning: string 'guide_call_mute' has no default translation.
warning: string 'guide_call_on_hold' has no default translation.
warning: string 'guide_call_record' has no default translation.
warning: string 'guide_call_screen_end' has no default translation.
warning: string 'guide_call_speaker' has no default translation.
warning: string 'guide_contacts_saved' has no default translation.
warning: string 'guide_dialing' has no default translation.
warning: string 'guide_speed_dial_complete_popup' has no default translation.
warning: string 'guide_videocall_capture' has no default translation.
warning: string 'guide_videocall_dualcamera' has no default translation.
warning: string 'guide_videocall_hide' has no default translation.
warning: string 'guide_videocall_switchcamera' has no default translation.
warning: string 'guide_voicecall_swap' has no default translation.
warning: string 'import_from_4sim2' has no default translation.
I: Building apk file...

Decompile just builded file

I: Using Apktool 2.0.0 on SecContacts_L_Phone_FLAGSHIP_USA.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MAXIMATOR\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...


After rebuild no 
I: Decoding Shared Library (touchwiz), pkgId: 2

and package not working :(
