### ISSUE TITLE
Decode Error: java.lang.arrayindexoutofboundsexception

### ISSUE THREAD

**Issue by Valdak31** [iBotPeaches/Apktool#939]
Hey,

I was trying to decode an APK in order to translate the UI (from chinese to english) but I encountered some issues in the process.

If I decode, don't modify anything, then rebuild the APK, I get an analysis error and can't even click on "install". If I add -c to the build process I can trigger the installation but it ends with "Application not installed".

While decoding, with the -d argument, here is what I get:
![capturea](https://cloud.githubusercontent.com/assets/12256656/7476392/899279e8-f34d-11e4-8d02-77e42612293f.PNG)

I hosted the APK here so you can download it: http://www.filedropper.com/cloudmusicoffcial261

**Comment by iBotPeaches** [comment]
Why are you using `-d`? That is Debug mode. If there is an error during install you need a `logcat` of the failure.

**Comment by Valdak31** [comment]
I am using -d in order to check if the issue I encounter is related to the Decode process since I don't touch anything between Decode and Build.

**Comment by iBotPeaches** [comment]
`-d` is *not* decode. `d` is decode.

`-d` is Debug - http://ibotpeaches.github.io/Apktool/documentation/#smali-debugging

**Comment by Valdak31** [comment]
I know that. But "d" only do not provide any error. So I could not know if anything went wrong. That's why I added -d.

"Decode
These are all the options when decoding an apk. 

-d, --debug - Advanced
Decodes in Debug Mode. Read SmaliDebugging"

**Comment by iBotPeaches** [comment]
Yes, maybe an a misunderstanding but Debug mode has nothing at all to do with debugging the problem at hand. It is used for debugging the application literally.

As I said originally. I need a logcat of the failed app install. Do not use `-d`.

**Comment by Valdak31** [comment]
Ok, my bad then.

Here is the logcat of the failed installation:

--------- beginning of main

D/QcrilMsgTunnelSocket( 2758): readRilMessage: Buffer = [B@2792094b HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

D/QcrilMsgTunnelSocket( 2758): Rcvd UNSOL response with 28 bytes data for SUB0

D/QcrilMsgTunnelSocket( 2758): Response ID 525295 is not served in this process.

D/QcrilMsgTunnelSocket( 2758): To broadcast an Intent via the notifier to external apps

D/QcrilMsgTunnelIfaceManager( 2758): handleMessage what = 0

D/QcrilMsgTunnelIfaceManager( 2758): Broadcasting intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW

I/Timeline(10780): Timeline: Activity_launch_request id:com.android.packageinstaller time:7237667

--------- beginning of system

I/ActivityManager(  771): START u0 {dat=file:///storage/emulated/0/Download/CloudMusic_offcial_2.6.1.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10069 on display 0

I/ActivityManager(  771): Start proc com.android.defcontainer for service com.android.defcontainer/.DefaultContainerService: pid=10814 uid=10009 gids={50009, 9997, 1028, 1015, 1023, 2001, 1035} abi=armeabi-v7a

I/LoadedApk(10814): No resource references to update in package common

I/LoadedApk(10814): No resource references to update in package com.cyngn.hexo

I/ActivityManager(  771): Displayed com.android.packageinstaller/.InstallAppProgress: +138ms

D/OpenGLRenderer(10780): endAllStagingAnimators on 0xac6a8200 (RippleDrawable) with handle 0xac1a5190

I/Timeline(10780): Timeline: Activity_idle id: android.os.BinderProxy@3359979a time:7237863

I/ActivityManager(  771): Start proc com.android.vending for broadcast com.android.vending/com.google.android.vending.verifier.PackageVerificationReceiver: pid=10834 uid=10019 gids={50019, 9997, 3003, 1028, 1015} abi=armeabi-v7a

I/Timeline(  771): Timeline: Activity_windows_visible id: ActivityRecord{144adc12 u0 com.android.packageinstaller/.InstallAppProgress t219} time:7238185

I/LoadedApk(10834): No resource references to update in package common

I/LoadedApk(10834): No resource references to update in package com.cyngn.hexo

I/art     ( 2056): Explicit concurrent mark sweep GC freed 32784(1834KB) AllocSpace objects, 12(192KB) LOS objects, 25% free, 20MB/27MB, paused 633us total 49.722ms

I/art     ( 1781): Explicit concurrent mark sweep GC freed 6062(363KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 18MB/31MB, paused 1.133ms total 27.882ms

D/Finsky  (10834): [1] FinskyApp.onCreate: Initializing network with DFE https://android.clients.google.com/fdfe/

D/Finsky  (10834): [1] DailyHygiene.goMakeHygieneIfDirty: No need to run daily hygiene.

I/ActivityManager(  771): Start proc com.google.android.gms:car for service com.google.android.gms/.car.CarService: pid=10873 uid=10013 gids={50013, 9997, 2001, 3003, 1007, 3006, 1028, 1015, 3002, 3001, 1005, 3007} abi=armeabi-v7a

W/Settings(10834): Setting download_manager_max_bytes_over_mobile has moved from android.provider.Settings.Secure to android.provider.Settings.Global.

W/Settings(10834): Setting download_manager_recommended_max_bytes_over_mobile has moved from android.provider.Settings.Secure to android.provider.Settings.Global.

W/ResourcesManager(10873): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.

W/ResourcesManager(10873): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.

D/Finsky  (10834): [1] PackageVerificationReceiver.checkPrerequisites: Skipping verification because network inactive

D/Finsky  (10834): [1] 2.run: Loaded library for account: [5rnUrZZStZK0Fl3yyil-RNOl31g]

D/Finsky  (10834): [1] 2.run: Finished loading 1 libraries.

D/Finsky  (10834): [1] PackageVerificationReceiver.checkPrerequisites: Skipping verification because network inactive

D/DefContainer(10814): Copying /storage/emulated/0/Download/CloudMusic_offcial_2.6.1.apk to base.apk

I/MultiDex(10873): VM with version 2.1.0 has multidex support

I/MultiDex(10873): install

I/MultiDex(10873): VM has multidex support, MultiDex support library is disabled.

I/LoadedApk(10873): No resource references to update in package common

I/LoadedApk(10873): No resource references to update in package com.cyngn.hexo

I/ProviderInstaller(10873): Insert disabled by gate 'gms:security:enable_conscrypt_in_gms_application'

D/GCM     ( 1781): GcmService start Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService } com.google.android.gms.INITIALIZE

D/AuthorizationBluetoothService( 1781): Received GmsCore event: Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$AutoStarter }.

D/c       ( 1781): Getting all permits...

D/a       ( 1781): Opening database...

D/a       ( 1781): Opening database auth.proximity.permit_store...

D/a       ( 1781): Closing database...

V/GmsCoreStatsServiceLauncher( 2056): Received broadcast intent Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.common.stats.GmsCoreStatsServiceLauncher }

D/WearableService( 9327): callingUid 10013, callindPid: 9327

E/MDM     ( 1640): [146] b.run: Couldn't connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null}

D/LocationInitializer( 2056): Restart initialization of location

D/Finsky  (10834): [1] GmsCoreHelper.cleanupNlp: result=false type=4

D/Finsky  (10834): [1] RestoreTracker.stopServiceIfDone: Restore complete with 0 success and 0 failed.

V/Finsky  (10834): [1] GearheadStateMonitor.onReady: sIsProjecting:false

I/CAR.SERVICE(10873): listener not found in list

W/PackageManager(  771): Invalid verification token 12 received

W/PackageManager(  771): Failed collect during installPackageLI

W/PackageManager(  771): android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl632925838.tmp/base.apk has no certificates at entry res/drawable-hdpi/set_skin_icn_slt.png

W/PackageManager(  771): 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1185)

W/PackageManager(  771): 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1138)

W/PackageManager(  771): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11246)

W/PackageManager(  771): 	at com.android.server.pm.PackageManagerService.access$2500(PackageManagerService.java:270)

W/PackageManager(  771): 	at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:9292)

W/PackageManager(  771): 	at android.os.Handler.handleCallback(Handler.java:739)

W/PackageManager(  771): 	at android.os.Handler.dispatchMessage(Handler.java:95)

W/PackageManager(  771): 	at android.os.Looper.loop(Looper.java:135)

W/PackageManager(  771): 	at android.os.HandlerThread.run(HandlerThread.java:61)

W/PackageManager(  771): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

I/art     (  771): Explicit concurrent mark sweep GC freed 121522(5MB) AllocSpace objects, 22(5MB) LOS objects, 29% free, 38MB/54MB, paused 1.345ms total 106.048ms

D/InstallAppProgress(10780): Installation error code: -103

I/Process (10873): Sending signal. PID: 10873 SIG: 9

I/ActivityManager(  771): Process com.google.android.gms:car (pid 10873) has died

D/QcrilMsgTunnelSocket( 2758): readRilMessage: Buffer = [B@2792094b HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

D/QcrilMsgTunnelSocket( 2758): Rcvd UNSOL response with 28 bytes data for SUB0

D/QcrilMsgTunnelSocket( 2758): Response ID 525295 is not served in this process.

D/QcrilMsgTunnelSocket( 2758): To broadcast an Intent via the notifier to external apps

D/QcrilMsgTunnelIfaceManager( 2758): handleMessage what = 0

D/QcrilMsgTunnelIfaceManager( 2758): Broadcasting intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW

**Comment by iBotPeaches** [comment]
```

Valdak31 commented 20 minutes ago

Hey,

I was trying to decode an APK in order to translate the UI (from chinese to english) but I encountered some issues in the process.

If I decode, don't modify anything, then rebuild the APK, I get an analysis error and can't even click on "install". If I add -c to the build process I can trigger the installation but it ends with "Application not installed".

While decoding, with the -d argument, here is what I get:
capturea

I hosted the APK here so you can download it: http://www.filedropper.com/cloudmusicoffcial261
@iBotPeaches
Owner
iBotPeaches commented 13 minutes ago

Why are you using -d? That is Debug mode. If there is an error during install you need a logcat of the failure.
@iBotPeaches iBotPeaches added the Waiting for issuer label 13 minutes ago
@Valdak31
Valdak31 commented 12 minutes ago

I am using -d in order to check if the issue I encounter is related to the Decode process since I don't touch anything between Decode and Build.
@iBotPeaches
Owner
iBotPeaches commented 10 minutes ago

-d is not decode. d is decode.

-d is Debug - http://ibotpeaches.github.io/Apktool/documentation/#smali-debugging
@Valdak31
Valdak31 commented 7 minutes ago

I know that. But "d" only do not provide any error. So I could not know if anything went wrong. That's why I added -d.

"Decode
These are all the options when decoding an apk.

-d, --debug - Advanced
Decodes in Debug Mode. Read SmaliDebugging"
@iBotPeaches
Owner
iBotPeaches commented 4 minutes ago

Yes, maybe an a misunderstanding but Debug mode has nothing at all to do with debugging the problem at hand. It is used for debugging the application literally.

As I said originally. I need a logcat of the failed app install. Do not use -d.
@Valdak31
Valdak31 commented 2 minutes ago

Ok, my bad then.

Here is the logcat of the failed installation:

--------- beginning of main

D/QcrilMsgTunnelSocket( 2758): readRilMessage: Buffer = [B@2792094b HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

D/QcrilMsgTunnelSocket( 2758): Rcvd UNSOL response with 28 bytes data for SUB0

D/QcrilMsgTunnelSocket( 2758): Response ID 525295 is not served in this process.

D/QcrilMsgTunnelSocket( 2758): To broadcast an Intent via the notifier to external apps

D/QcrilMsgTunnelIfaceManager( 2758): handleMessage what = 0

D/QcrilMsgTunnelIfaceManager( 2758): Broadcasting intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW

I/Timeline(10780): Timeline: Activity_launch_request id:com.android.packageinstaller time:7237667

--------- beginning of system

I/ActivityManager(  771): START u0 {dat=file:///storage/emulated/0/Download/CloudMusic_offcial_2.6.1.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10069 on display 0

I/ActivityManager(  771): Start proc com.android.defcontainer for service com.android.defcontainer/.DefaultContainerService: pid=10814 uid=10009 gids={50009, 9997, 1028, 1015, 1023, 2001, 1035} abi=armeabi-v7a

I/LoadedApk(10814): No resource references to update in package common

I/LoadedApk(10814): No resource references to update in package com.cyngn.hexo

I/ActivityManager(  771): Displayed com.android.packageinstaller/.InstallAppProgress: +138ms

D/OpenGLRenderer(10780): endAllStagingAnimators on 0xac6a8200 (RippleDrawable) with handle 0xac1a5190

I/Timeline(10780): Timeline: Activity_idle id: android.os.BinderProxy@3359979a time:7237863

I/ActivityManager(  771): Start proc com.android.vending for broadcast com.android.vending/com.google.android.vending.verifier.PackageVerificationReceiver: pid=10834 uid=10019 gids={50019, 9997, 3003, 1028, 1015} abi=armeabi-v7a

I/Timeline(  771): Timeline: Activity_windows_visible id: ActivityRecord{144adc12 u0 com.android.packageinstaller/.InstallAppProgress t219} time:7238185

I/LoadedApk(10834): No resource references to update in package common

I/LoadedApk(10834): No resource references to update in package com.cyngn.hexo

I/art     ( 2056): Explicit concurrent mark sweep GC freed 32784(1834KB) AllocSpace objects, 12(192KB) LOS objects, 25% free, 20MB/27MB, paused 633us total 49.722ms

I/art     ( 1781): Explicit concurrent mark sweep GC freed 6062(363KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 18MB/31MB, paused 1.133ms total 27.882ms

D/Finsky  (10834): [1] FinskyApp.onCreate: Initializing network with DFE https://android.clients.google.com/fdfe/

D/Finsky  (10834): [1] DailyHygiene.goMakeHygieneIfDirty: No need to run daily hygiene.

I/ActivityManager(  771): Start proc com.google.android.gms:car for service com.google.android.gms/.car.CarService: pid=10873 uid=10013 gids={50013, 9997, 2001, 3003, 1007, 3006, 1028, 1015, 3002, 3001, 1005, 3007} abi=armeabi-v7a

W/Settings(10834): Setting download_manager_max_bytes_over_mobile has moved from android.provider.Settings.Secure to android.provider.Settings.Global.

W/Settings(10834): Setting download_manager_recommended_max_bytes_over_mobile has moved from android.provider.Settings.Secure to android.provider.Settings.Global.

W/ResourcesManager(10873): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.

W/ResourcesManager(10873): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.

D/Finsky  (10834): [1] PackageVerificationReceiver.checkPrerequisites: Skipping verification because network inactive

D/Finsky  (10834): [1] 2.run: Loaded library for account: [5rnUrZZStZK0Fl3yyil-RNOl31g]

D/Finsky  (10834): [1] 2.run: Finished loading 1 libraries.

D/Finsky  (10834): [1] PackageVerificationReceiver.checkPrerequisites: Skipping verification because network inactive

D/DefContainer(10814): Copying /storage/emulated/0/Download/CloudMusic_offcial_2.6.1.apk to base.apk

I/MultiDex(10873): VM with version 2.1.0 has multidex support

I/MultiDex(10873): install

I/MultiDex(10873): VM has multidex support, MultiDex support library is disabled.

I/LoadedApk(10873): No resource references to update in package common

I/LoadedApk(10873): No resource references to update in package com.cyngn.hexo

I/ProviderInstaller(10873): Insert disabled by gate 'gms:security:enable_conscrypt_in_gms_application'

D/GCM     ( 1781): GcmService start Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService } com.google.android.gms.INITIALIZE

D/AuthorizationBluetoothService( 1781): Received GmsCore event: Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$AutoStarter }.

D/c       ( 1781): Getting all permits...

D/a       ( 1781): Opening database...

D/a       ( 1781): Opening database auth.proximity.permit_store...

D/a       ( 1781): Closing database...

V/GmsCoreStatsServiceLauncher( 2056): Received broadcast intent Intent { act=com.google.android.gms.INITIALIZE flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.common.stats.GmsCoreStatsServiceLauncher }

D/WearableService( 9327): callingUid 10013, callindPid: 9327

E/MDM     ( 1640): [146] b.run: Couldn't connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null}

D/LocationInitializer( 2056): Restart initialization of location

D/Finsky  (10834): [1] GmsCoreHelper.cleanupNlp: result=false type=4

D/Finsky  (10834): [1] RestoreTracker.stopServiceIfDone: Restore complete with 0 success and 0 failed.

V/Finsky  (10834): [1] GearheadStateMonitor.onReady: sIsProjecting:false

I/CAR.SERVICE(10873): listener not found in list

W/PackageManager(  771): Invalid verification token 12 received

W/PackageManager(  771): Failed collect during installPackageLI

W/PackageManager(  771): android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl632925838.tmp/base.apk has no certificates at entry res/drawable-hdpi/set_skin_icn_slt.png

W/PackageManager(  771):    at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1185)

W/PackageManager(  771):    at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1138)
```

Appears to be a signature problem. Did you resign apk?

**Comment by iBotPeaches** [comment]
`--copy-original` should of retained `META-INF` and `AndroidManifest.xml`, but its buggy. Your best bet is to include modified files into the original apk. 

I don't think this is a bug, but quickly turning into a support query. So closing this.
