### ISSUE TITLE
SecContacts_Phone_OSup_FLAGSHIP_USA liolipop Error

### ISSUE THREAD

**Issue by andriodtaiz** [iBotPeaches/Apktool#942]
this the adb alogcat for https://github.com/iBotPeaches/Apktool/issues/938
that you need it
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthServiceInstalled() : HealthService is Installed.
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthService2xInstalled() : HEALTH SERVICE is INSTALLED.
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthService2xInstalled() : HEALTH SERVICE VERSION = 2.x
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthServiceInstalled() : HealthService is Installed.
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthService2xInstalled() : HEALTH SERVICE is INSTALLED.
D/SHealthUpgrade(SHealthUpgradeUtil)(14163): isShealthService2xInstalled() : HEALTH SERVICE VERSION = 2.x
D/ResourcesManager(15951): creating new AssetManager and set to /system/app/PackageInstaller/PackageInstaller.apk
W/PackageManager(15951): Failure retrieving resources for com.android.packageinstaller: Resource ID #0x0
W/PackageManager(15951): Failure retrieving resources for com.android.packageinstaller: Resource ID #0x0
V/ApplicationPolicy(  955): isApplicationStateBlocked userId 0 pkgname com.android.packageinstaller
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
W/PackageManager(15951): Failure retrieving resources for com.android.packageinstaller: Resource ID #0x0
W/PackageManager(15951): Failure retrieving resources for com.android.packageinstaller: Resource ID #0x0
W/PackageInstaller(16256): Parse error when parsing manifest. Discontinuing installation
D/ResourcesManager( 3736): creating new AssetManager and set to /system/app/PackageInstaller/PackageInstaller.apk
I/ActivityManager(  955): Displayed com.android.packageinstaller/.PackageInstallerActivity: +371ms
I/Timeline(  955): Timeline: Activity_windows_visible id: ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323} time:4381728
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}
I/WindowAnimator(  955): Remove SET_ORIENTATION_CHANGE_COMPLETE / token=AppWindowToken{856dcac token=Token{3a2bbeb9 ActivityRecord{297eb880 u0 com.android.packageinstaller/.PackageInstallerActivity t323}}}

**Comment by iBotPeaches** [comment]
You can respond directly to #938. No need for another bug report. Either way, there is no failure in this `logcat`. You are getting close though.
