### ISSUE TITLE
Please support Android Wear 5.x 

### ISSUE THREAD

**Issue by mapleshadow** [iBotPeaches/Apktool#948]
Use apktool 2.0 on Android wear 5.0.1 system within the APK to decompile, compile, system can not run normally..
PS：moto 360 5.0.2 system

**Comment by iBotPeaches** [comment]
Do you have a logcat of the failure? An apk to investigate? I will re-open this if we do.

**Comment by mapleshadow** [comment]
OK, I'll give logcat.
I tested with only one APK.

**Comment by mapleshadow** [comment]
Sorry, I think, in this bug is not resolved before, I submit this problem, Is it right? No meaning? Maybe I lead to this problem is the reason?
https://github.com/iBotPeaches/Apktool/issues/944

**Comment by mapleshadow** [comment]
Or, if you can provide only a BUG repair https://github.com/iBotPeaches/Apktool/issues/944 apktool to me, I have to test?!

**Comment by iBotPeaches** [comment]
I have no idea what you are trying to say. I need a logcat.

**Comment by mapleshadow** [comment]
I want to be able to advance the use of fixed https://github.com/iBotPeaches/Apktool/issues/944 the bug apktool, I can back to moto360 APK decompile, compile and test whether normal and provide logcat, because the apktool2.0 not fix this bug https://github.com/iBotPeaches/Apktool/issues/944, so provide a logcat should is meaningless.

**Comment by iBotPeaches** [comment]
I fixed #928 and #944 was a duplicate. Once again, I need a logcat. I see this is going no where though.

**Comment by mapleshadow** [comment]
Is repeated. You mean, I provide Logcat to bug repair, is?

**Comment by iBotPeaches** [comment]
I mean, I can't fix what I don't know what the problem is.

You can tell me this problem exists, but I need the why. This is provided by YOU via a logcat.

**Comment by mapleshadow** [comment]
Well, understand. Then I will provide the error of the logcat here for your reference, thank you.
