### ISSUE TITLE
Provider android:authorities is referencing resources, which is not allowed

### ISSUE THREAD

**Issue by MarcMil** [iBotPeaches/Apktool#951]
If you run
``apktool d``
on the APK from https://www.dropbox.com/s/jht3qsx6ttx13z5/Sunshine.apk?dl=0 apktool produces a manifest with the content
``<provider android:authorities="@string/content_authority" android:exported="false" android:name="com.example.android.sunshine.app.data.WeatherProvider" android:syncable="true"/>``

The problem is, that android:authorities must not reference a resource, as described in https://stackoverflow.com/questions/6461776/using-string-for-androidauthorities-in-a-contentprovider

Apktool should inline this kind of constant. I do not know what Apktool does to the android:versionCode attribute, but the behaviour should be the same there.

**Comment by iBotPeaches** [comment]
Before

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug951$ aapt d xmltree Sunshine.apk AndroidManifest.xml | grep 'authorities'
        A: android:authorities(0x01010018)=@0x7f0d0012
```

After decode & build

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug951$ cd Sunshine/dist
ibotpeaches@raganok:~/Downloads/Apktool/Bug951/Sunshine/dist$ aapt d xmltree Sunshine.apk AndroidManifest.xml | grep 'authorities'
        A: android:authorities(0x01010018)="com.example.android.sunshine.app" (Raw: "com.example.android.sunshine.app")
```

I fixed this issue already here - #911

**Comment by MarcMil** [comment]
Rebuilding works indeed, but why is the ResXmlPatcher not applied when the AndroidManifest.xml itself gets written out?
If you use decode and check out the AndroidManifest.xml plaintext file, you will see that the value did not get replaced.
I do not want to use apktool to rebuild the apk, but rather use the decoded resources (maybe modify them) and use plain aapt to repackage it (I can copy the dex file from the original apk). This does not work because apktool writes out the xml without the attribute getting replaced by the constant.

**Comment by iBotPeaches** [comment]
Other users reported that changing the value during the decode stage was improper as it didn't reflect the original application. Since apktool promises to decode matching the original nearly 100%, I agreed and did it that way. Thus the change occurs during the build stage.

I think your use case is quite rare and the existing method proves to please the greatest number.

**Comment by MarcMil** [comment]
If matching the original app is the goal, isn't match-original the option to use for it?
But what I do not understand is: If in the original app the string in the xml was actually a reference to the string resource, why does Android accept it at runtime? I mean, how could the original app manifest contain a reference to the string resource at that point if it does not get accept at runtime? Shouldn't the original apk manifest have the constant string in there?

You may be right that the use case is rare. I'll probably fork it and patch it to achieve my goals. Let's see what my teammates say :).
