### ISSUE TITLE
Cant decompile to folder

### ISSUE THREAD

**Issue by mimi86uk** [iBotPeaches/Apktool#953]
Ok so i finally got it working but now i cant decompile to a destination folder.
When i run apktool d myapk.apk it works fine.
But when i run apktool d myapk.apk destination/folder 
- it tells me "input file 'destination/folder' cant be found" 

Is this a bug?

**Comment by iBotPeaches** [comment]
No.

http://ibotpeaches.github.io/Apktool/documentation/#migration-instructions

Please read the documentation. You need `-o` like `apktool d myapk.apk -o destination/folder`

**Comment by mimi86uk** [comment]
THANKYOU!!
