### ISSUE TITLE
SecContacts_L_Phone_FLAGSHIP_USA after compiling not working.

### ISSUE THREAD

**Issue by MAXIMATOR82** [iBotPeaches/Apktool#958]
Decompile Orig file
```
I: Using Apktool 2.0.0 on SecContacts_L_Phone_FLAGSHIP_USA.apk
I: Loading resource table...
I: Decoding Shared Library (touchwiz), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MAXIMATOR\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values / XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
Build FILE
```
I: Using Apktool 2.0.0
W: Could not find sources
I: Building resources...
warning: string 'guide_call_addcall' has no default translation.
warning: string 'guide_call_endcall' has no default translation.
warning: string 'guide_call_headset' has no default translation.
warning: string 'guide_call_mute' has no default translation.
warning: string 'guide_call_on_hold' has no default translation.
warning: string 'guide_call_record' has no default translation.
warning: string 'guide_call_screen_end' has no default translation.
warning: string 'guide_call_speaker' has no default translation.
warning: string 'guide_contacts_saved' has no default translation.
warning: string 'guide_dialing' has no default translation.
warning: string 'guide_speed_dial_complete_popup' has no default translation.
warning: string 'guide_videocall_capture' has no default translation.
warning: string 'guide_videocall_dualcamera' has no default translation.
warning: string 'guide_videocall_hide' has no default translation.
warning: string 'guide_videocall_switchcamera' has no default translation.
warning: string 'guide_voicecall_swap' has no default translation.
warning: string 'import_from_4sim2' has no default translation.
I: Building apk file...
```
Decompile just builded file
```
I: Using Apktool 2.0.0 on SecContacts_L_Phone_FLAGSHIP_USA.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MAXIMATOR\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values / XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
After rebuild no 
```
I: Decoding Shared Library (touchwiz), pkgId: 2
```
and when package build `W: Could not find sources`

and package not working :(

orig files https://dl.dropboxusercontent.com/u/32328783/S6_problem_apk.rar

**Comment by iBotPeaches** [comment]
The warnings regarding sources is perfectly fine, because there is no sources. The output message from Decoding Shared Libraries is not a good indicator of an error. I simply output that text when I encounter a Shared Library reference, so it is a tad bit misleading.

Do you have a logcat `adb logcat` of the failure occurring?

**Comment by MAXIMATOR82** [comment]
Here is loggcat 
https://dl.dropboxusercontent.com/u/32328783/1.rar

**Comment by MAXIMATOR82** [comment]
Galaxy Note N910P same proplem
Original apk
C:\Users\MAXIMATOR>adb shell
shell@trltespr:/ $ am start -n com.android.contacts/com.android.dialer.DialtactsActivity
rt -n com.android.contacts/com.android.dialer.DialtactsActivity               <
Starting: Intent { cmp=com.android.contacts/com.android.dialer.DialtactsActivity }

Only recompiled with nothing changes
shell@trltespr:/ $
C:\Users\MAXIMATOR>adb shell
shell@trltespr:/ $ am start -n com.android.contacts/com.android.dialer.DialtactsActivity
rt -n com.android.contacts/com.android.dialer.DialtactsActivity               <
Starting: Intent { cmp=com.android.contacts/com.android.dialer.DialtactsActivity }
Error type 3
Error: Activity class {com.android.contacts/com.android.dialer.DialtactsActivity} does not exist.

**Comment by iBotPeaches** [comment]
I don't see a failure of `SecContacts_L_Phone_FLAGSHIP_USA` anywhere in that logcat. Since its a system apk, you cannot install it using `adb install`. You must push it `/system`.

**Comment by MAXIMATOR82** [comment]
SecContacts_L_Phone_FLAGSHIP_USA.apk stored in 
/system/priv-app/SecContacts_L_Phone_FLAGSHIP_USA

I dont install it. On both phones. Just replaced it in system folder.

**Comment by MAXIMATOR82** [comment]
Not apktool bug, - Samsung feature
