### ISSUE TITLE
Couldn't recompile framework-res.apk on MIUI V6 Base on Android L (Mi note Pro)

### ISSUE THREAD

**Issue by igobig** [iBotPeaches/Apktool#962]
error in below

U:\Desktop\apktoo>apktool if framework-res.apk
I: Framework installed to: C:\Users\miuidev\apktool\framework\1.apk

U:\Desktop\apktoo>apktool d framework-res.apk
I: Using Apktool 2.0.0 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

U:\Desktop\apktoo>apktool b framework-res
I: Using Apktool 2.0.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
invalid resource directory name: U:\Desktop\apktoo\framework-res\res values-mcc9
460-mnc9000
invalid resource directory name: U:\Desktop\apktoo\framework-res\res values-mcc9
466-mnc9999
invalid resource directory name: U:\Desktop\apktoo\framework-res\res values-mcc9
724-mnc9999
invalid resource directory name: U:\Desktop\apktoo\framework-res\res values-mcc9
998-mnc9999
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\miuide
v\AppData\Local\Temp\brut_util_Jar_35237846276028637.tmp, p, --forced-package-id
, 1, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --vers
ion-name, 5.0.2-5.5.22, -F, C:\Users\miuidev\AppData\Local\Temp\APKTOOL646761837
8688179285.tmp, -x, -0, arsc, -S, U:\Desktop\apktoo\framework-res\res, -M, U:\De
sktop\apktoo\framework-res\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        at brut.androlib.Androlib.buildResources(Androlib.java:396)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\miuidev\AppData\Local\Temp\brut_util_Jar_35237846276028
637.tmp, p, --forced-package-id, 1, --min-sdk-version, 21, --target-sdk-version,
 21, --version-code, 21, --version-name, 5.0.2-5.5.22, -F, C:\Users\miuidev\AppD
ata\Local\Temp\APKTOOL6467618378688179285.tmp, -x, -0, arsc, -S, U:\Desktop\apkt
oo\framework-res\res, -M, U:\Desktop\apktoo\framework-res\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\miuidev\
AppData\Local\Temp\brut_util_Jar_35237846276028637.tmp, p, --forced-package-id,
1, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --versio
n-name, 5.0.2-5.5.22, -F, C:\Users\miuidev\AppData\Local\Temp\APKTOOL64676183786
88179285.tmp, -x, -0, arsc, -S, U:\Desktop\apktoo\framework-res\res, -M, U:\Desk
top\apktoo\framework-res\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:413)
        ... 6 more

U:\Desktop\apktoo>

framework-res file
https://drive.google.com/file/d/0B3QXBNjbkCgrMWtwYVZmZmlkSWM/view?usp=sharing

**Comment by iBotPeaches** [comment]
`mnc` max is `999`. See my response here - http://stackoverflow.com/a/29590297/455008
