### ISSUE TITLE
Resources corrupted after decode/build cycle, rebuilt app force-closes

### ISSUE THREAD

**Issue by Lanchon** [iBotPeaches/Apktool#969]
A very simple app fails to start after decode/build cycle. No errors displayed by apktool. App installs correctly but force-closes on start.

Apktool: v2.0.0
Source app: https://f-droid.org/repository/browse/?fdid=makeinfo.com.getid (v1.0)
Logcat: http://pastebin.com/bH3QYEXK

Exception chain overview:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{makeinfo.com.getid/makeinfo.com.getid.MainActivity}
    Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class android.widget.ImageView
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/makeinfoapps from drawable resource ID #0x7f020036
    Caused by: java.io.FileNotFoundException: res/drawable/makeinfoapps
```

Workaround: use the --no-res option on decode.
Also tried: --keep-broken-res but does not work, the decoded output directory does not change with this option.

Maybe duplicate of: https://github.com/iBotPeaches/Apktool/issues/967

Thanks!

**Comment by Lanchon** [comment]
### more info

in the source app there is a jpeg file named:
>res/drawable/makeinfoapps

just dropping this file in place in the rebuilt app makes it work.

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug969$ unzip -l makeinfo.com.getid_1.apk | grep 'res/drawable/makeinfoapps'
    22756  2015-03-21 11:02   res/drawable/makeinfoapps
ibotpeaches@raganok:~/Downloads/Apktool/Bug969$ cd makeinfo.com.getid_1/dist
ibotpeaches@raganok:~/Downloads/Apktool/Bug969/makeinfo.com.getid_1/dist$ unzip -l makeinfo.com.getid_1.apk | grep 'res/drawable/makeinfoapps'
    22756  2015-06-03 22:50   res/drawable/makeinfoapps
```

Looks like this was fixed here: https://github.com/iBotPeaches/Apktool/commit/8254764c6c10b42f2db7d408ae32de7d7bdf082a

**Comment by Lanchon** [comment]
i suppose dist/makeinfo.com.getid_1.apk must be a rebuid. ok, so thanks for the fast turnaround!
