### ISSUE TITLE
Missing "0" numbers of HEX number after decompling

### ISSUE THREAD

**Issue by formoney000** [iBotPeaches/Apktool#972]
After decompiling an apk, some 0 number after x will be missing from a HEX number of manifest.
Example:
original format number: 0x00020000
after decompiling number: 0x20000

**Comment by iBotPeaches** [comment]
Where is this hex number at?
Can you provide an apk?

Or modify the unit-tests so they fail? Not sure where I should be looking for something like this.

**Comment by formoney000** [comment]
Where is this hex number at?
=> Easily found in the line <uses-feature android:glEsVersion="0x00020000" android:required="true" />

Can you provide an apk?
     http://revdownload.com/index.php?id=lara-croft-relic-run-android
Sorry for using the external URL but the attachment is limited to only 10MB

**Comment by iBotPeaches** [comment]
Okay I duplicate.

Before
```
<uses-feature android:glEsVersion="0x00020000" android:required="true" />
```

After
```
    <uses-feature android:glEsVersion="0x20000" android:required="true"/>
```

**Comment by iBotPeaches** [comment]
Hooked into the `XmlPullParser` to check for `glESVersion` and write our own value by appending `0000` to the current value. This produced `00000x2000`, which is wrong.

Progress is being made.
