### ISSUE TITLE
Public.xml error while compile

### ISSUE THREAD

**Issue by shmshd12** [iBotPeaches/Apktool#984]
This is the 1st time i get this error when the app released new version! I'm the regular user of Apktool who never got this type of issue.
What i did in the app is just tinted / changed the color of some icons and edited color.xml and string.xml ! But the error occur is totally different. The error defines about the drawable which i didn't even touch that drawable files!
check out the errors for your reference : http://pastebin.com/cnW7hG43

**Comment by iBotPeaches** [comment]
I'm having a hard time reading your log, since the formatting is all weird. Any chance you could upload the apk and I could take a peek myself?

**Comment by shmshd12** [comment]
This was solved in the latest Apktool :)
