### ISSUE TITLE
Adding smali classes and multidexing

### ISSUE THREAD

**Issue by pvertenten** [iBotPeaches/Apktool#985]
I've written a few shell scripts that can take an arbitrary aar file and include the resources, classes, etc. in the aar and merge them in with an app decompiled with apktool.

It works flawlessly for most apps, but some apps have near the maximum number of methods for a single classes.dex, so when I copy the classes from the aar into the apk smali directory I will get a build error that the short value can't support the number of methods in that classes.dex. 

Wondering if I am missing some other step.

Also I am not sure if there is any interest in adding this feature to apktool.

The feature opens up the apk, copies over the libraries, examines the public.xml and the R.txt in the aar, generates new ids for all of the resources, updates the ids.xml with the new resources, updates the public.xml with the new resources, smalis the classes from the aar and copies them into the app.

For most people the feature might not be that useful however, as they would need to edit some of the other code to actually use the newly included code, but it could be as simple as adding an additional service to  AndroidManifest.xml etc.

**Comment by iBotPeaches** [comment]
Apktool works just by a basic path, looking for `smali_classes#` and assembling those to that `classes#`.dex file. I'm not sure how exactly the multidex works, but apktool does not do anything for that. It simply disassembles and reassembles the dex files.

According to docs, it modifies `classes.dex` to load all other dex files. - https://developer.android.com/tools/building/multidex.html

As for your concern whether there is interest for such a feature. I will admit to not knowing enough about the `aar` files to have an opinion yet. Let me research them.

**Comment by pvertenten** [comment]
Thanks, thats a decent place to start.

**Comment by pvertenten** [comment]
I got it working with the smali_classes#. Was having some other issues with some injected code, but all working now, thanks for the quick feedback.

**Comment by iBotPeaches** [comment]
I meant to close this after your response. Closing now. Let me know if I missed something.

**Comment by seibelj** [comment]
Hi @pvertenten, are those shell scripts to copy AAR's into a decompiled multidex app in a repo somewhere? That's the exact same technique I'm struggling to accomplish

**Comment by shikhaverma2009** [comment]
Hi,
I try to add a new smali file in smali folder but its not working. But if i modify already created smali file it is working. My question is can I add a new smali file in decompiled apk and rebuild it ?
Please help !

**Comment by thanhnguyen1121** [comment]
hi, can you tell me how to add multidex in project with code smali? I try to add code smali of multidex after decode apk in my project, but it's not working.

**Comment by KORuL** [comment]
> прокомментировал

It is very necessary to include aar in the decompiled apk. You wrote that you have a perfectly working script. Please share with me!
