### ISSUE TITLE
(H81510B) LGSettings cannot be decompiled

### ISSUE THREAD

**Issue by szecs** [iBotPeaches/Apktool#987]
I am using for theming work for my LG G4 H815 running stock 10B (Android 5.1) sw apktool fresh compiled from the sources. Apk-s recompiled with the official version always caused fc, new compiled version works well. Only LGSettings cannot be decompiled.
Log: http://pastebin.com/Y0uBSfLz
Windows 8 64 bit. Framework properly installed.

**Comment by skoperst** [comment]
I also have this issue, other apk's from H815 are apktooled ok, but the LGSettings does not.
https://dl.dropboxusercontent.com/u/16440615/stuff/LGSettings.apk

**Comment by iBotPeaches** [comment]
I will need all the LG frameworks to investigate this properly. I'm missing the `pkgID` of `1` and `2`, so `framework-res.apk` and some LG framework probably `lge-res.apk`.

**Comment by szecs** [comment]
Will send soon.

**Comment by skoperst** [comment]
I'm attaching latest version's apks. So re-download LGSettings.apk also.

https://dl.dropboxusercontent.com/u/16440615/stuff/framework-res.apk
https://dl.dropboxusercontent.com/u/16440615/stuff/lge-res.apk
https://dl.dropboxusercontent.com/u/16440615/stuff/LGSettings.apk

**Comment by szecs** [comment]
I have just tried 2.0.1 and could decompile LGSettings.apk.

**Comment by laststandingdroid** [comment]
i can confirm this is fixed since 2.0.1 (tested with snapshot 2.0.1) as well

**Comment by iBotPeaches** [comment]
Appears 2.0.1 fixed this.
