### ISSUE TITLE
Keep original 'IDs' around for string/file resource values

### ISSUE THREAD

**Issue by mmastrac** [iBotPeaches/Apktool#990]
The Android on-device implementation for TypedValue uses the underlying data value as a cache key in various places (ie: the Drawable cache in Resources). This allows it to ensure that the various configuration versions of a resource don't overwrite each other in the cache without having to compute a hash each time. 

For projects where interacting with these on-device caches is important, we need a way to extract the raw version of the ResFileValue's data, ie: the index passed to mTableStrings to look up the string value in ARSCDecoder.java:

```
        return type == TypedValue.TYPE_STRING
                ? mPkg.getValueFactory().factory(mTableStrings.getHTML(data))
                : mPkg.getValueFactory().factory(type, data, null);
``` 

I can provide a patch for this if it's something you'd accept.

**Comment by iBotPeaches** [comment]
Yeah, if we are exposing some raw values, I will accept it. I'm pretty busy investigating some bugs, so a quick patch in a pull request would be quite helpful.

**Comment by mmastrac** [comment]
Closing in favour of PR #991
