### ISSUE TITLE
Google map is not showing after building

### ISSUE THREAD

**Issue by immnas** [iBotPeaches/Apktool#996]
Hi,

I have one apk which render on google map and it draw path at google map it gets from server API.
Original apk works fine but when I do the decoding and build again without any change.
New apk installed properly but I am not able to see google map on rebuild apk.
I need to change some of theme eventually but as it not working without any change so I cant able to modify the apk.

Regards,
Manas

**Comment by iBotPeaches** [comment]
Do you have an apk? A logcat or something?

Not much I can go on here.

**Comment by immnas** [comment]
You can download the apk from net.
Search "geocrat live" at play store.
You need to use following credentials to login
Ac id: Khalsa47
User id: Khalsa47
Password: Khalsa

Than you can track any vehicle. It will open in Google map.

If you use apktool in this apk & build it.
And signed it. All other thing works except google map will not show.

Regards,
Manas

Do you have an apk? A logcat or something?

Not much I can go on here.

—
Reply to this email directly or view it on GitHub
<https://github.com/iBotPeaches/Apktool/issues/996#issuecomment-121241785>.

**Comment by iBotPeaches** [comment]
I redacted your login credentials. I'll look later

**Comment by immnas** [comment]
Ok thanks, careful password is all in small latter.

**Comment by iBotPeaches** [comment]
Resigning an application with Google breaks breaks the signature, thus rejected. - http://stackoverflow.com/questions/24492881/google-maps-does-not-work-after-resigning-an-apk

This isn't a bug.
