### ISSUE TITLE
Android Marshmallow Support

### ISSUE THREAD

**Issue by jessfitzger** [iBotPeaches/Apktool#999]
<img width="1108" alt="apktool" src="https://cloud.githubusercontent.com/assets/13354948/8707638/d66b0b7e-2aeb-11e5-8f70-346482622592.png">

Uploading an Android M apk with the new tag "android:fullBackupContent" in the manifest produces the attached error.

The android sample app can be found here: https://github.com/googlesamples/android-AutoBackupForApps

**Comment by iBotPeaches** [comment]
Might be a lot of changes, might be a little. Who knows.

I will look into `Android M` once AOSP drops for the official build.

**Comment by iBotPeaches** [comment]
There is a new qualifier called "isScreenRound". This on top of a new set of SDK tools & framework seem to be only changes.

**Comment by iBotPeaches** [comment]
Info for me. Ignore.

```
public static final int SCREENLAYOUT_ROUND_MASK  -  Constant Value: 768 (0x00000300) 
public static final int SCREENLAYOUT_ROUND_NO -  Constant Value: 256 (0x00000100)
public static final int SCREENLAYOUT_ROUND_UNDEFINED -  Constant Value: 0 (0x00000000) 
public static final int SCREENLAYOUT_ROUND_YES -  Constant Value: 512 (0x00000200) 
```

`SCREENLAYOUT_ROUND_YES` corresponds to `-round` qualifier. They are fit into the existing `SCREENLAYOUT` qualifier, using a different mask.

**Comment by e-pom** [comment]
@iBotPeaches It looks like M is being posted to AOSP today.  Just curious if you had an estimate for when APKs targeting API version 23 would be supported.  Presumably they will be supported in ApkTool 2.0.2?  Sorry if it's a lot of work, I'm not clear on what's involved.  Thank you!

https://android.googlesource.com/platform/sdk/
https://android.googlesource.com/platform/build/

**Comment by iBotPeaches** [comment]
Yep,

commits of interest for me to patch into apktool

https://github.com/android/platform_frameworks_base/commit/2738c96d998dedfae5b4670d588d0cd299c4ca0f

Then I need to build new aapt binaries and we are good to go. Probably 1-2 days.

**Comment by e-pom** [comment]
Ok great, thanks!

**Comment by iBotPeaches** [comment]
Building aapt binaries now, then this will be fixed. A bit late of my estimated 1-2 days, but some aapt issues cropped up. Aiming before weekend hits to have 2.0.2 out.

**Comment by iBotPeaches** [comment]
Fixed - https://github.com/iBotPeaches/Apktool/commit/a29839bab27106b95bd3d41e713f37af562664f9

2.0.2 releasing today.
